CREATE EXTERNAL TABLE IF NOT EXISTS CDR.TT_ZTE_IPP_EXTRACT (
    IPP_NAME            VARCHAR(500),
    IPP_CODE            INT,
    IPP_AMOUNT          DOUBLE,
    CREATED_DATE        VARCHAR(50),
    ORIGINAL_FILE_NAME VARCHAR(60),
    ORIGINAL_FILE_SIZE INT,
    ORIGINAL_FILE_LINE_COUNT INT
)
COMMENT 'ZTE IPP EXTRACT'
ROW FORMAT DELIMITED FIELDS TERMINATED BY ';'
LOCATION '/PROD/TT/IN_ZTE/EXTRACT_IPP'
TBLPROPERTIES ('serialization.null.format'='');
