CREATE TABLE MON.SPARK_FT_MY_ORANGE (
    users_follow_daily bigint,
    users_follow_weekly bigint,
    users_follow_mtd bigint,
    users_backend_daily bigint,
    users_backend_weekly bigint,
    users_backend_mtd bigint,
    new_users_backend_daily bigint,
    new_users_backend_weekly bigint,
    new_users_backend_mtd bigint,
    new_users_backend_daily_percentage decimal(17, 2),
    new_users_backend_weekly_percentage decimal(17, 2),
    new_users_backend_mtd_percentage decimal(17, 2),
    welcome_pack_takers_global_daily bigint,
    welcome_pack_takers_global_weekly bigint,
    welcome_pack_takers_global_mtd bigint,
    welcome_pack_takers_new_backend_daily bigint,
    welcome_pack_takers_new_backend_weekly bigint,
    welcome_pack_takers_new_backend_mtd bigint,
    welcome_pack_takers_new_backend_daily_percentage decimal(17, 2),
    welcome_pack_takers_new_backend_weekly_percentage decimal(17, 2),
    welcome_pack_takers_new_backend_mtd_percentage decimal(17, 2),
    welcome_pack_data_usage_daily decimal(17, 2),
    welcome_pack_data_usage_weekly decimal(17, 2),
    welcome_pack_data_usage_mtd decimal(17, 2),
    myway_plus_takers_backend_daily bigint,
    myway_plus_takers_backend_weekly bigint,
    myway_plus_takers_backend_mtd bigint,
    myway_plus_subs_backend_daily bigint,
    myway_plus_subs_backend_weekly bigint,
    myway_plus_subs_backend_mtd bigint,
    myway_plus_revenu_backend_daily decimal(17, 2),
    myway_plus_revenu_backend_weekly decimal(17, 2),
    myway_plus_revenu_backend_mtd decimal(17, 2),
    insert_date TIMESTAMP
)
COMMENT 'Table for My Orange KPIs'
PARTITIONED BY (event_date DATE)
STORED AS PARQUET TBLPROPERTIES ('PARQUET.COMPRESS'='SNAPPY')
