SELECT IF(A.FT_EXIST = 0 AND B.FT_EXIST>0 AND C.FT_EXIST>0 AND D.FT_EXIST>0, "OK", "NOK") FROM
(SELECT COUNT(*) FT_EXIST FROM MON.SPARK_FT_MY_WAY WHERE EVENT_DATE='###SLICE_VALUE###') A,
(SELECT COUNT(*) FT_EXIST FROM MON.SPARK_FT_CBM_BUNDLE_SUBS_DAILY WHERE PERIOD='###SLICE_VALUE###') B,
(SELECT COUNT(*) FT_EXIST FROM MON.SPARK_FT_CLIENT_LAST_SITE_DAY WHERE EVENT_DATE='###SLICE_VALUE###') C,
(SELECT COUNT(*) FT_EXIST FROM MON.SPARK_FT_CLIENT_SITE_TRAFFIC_DAY WHERE EVENT_DATE='###SLICE_VALUE###') D
