SELECT IF(A.FT_EXIST = 0 and B.IT_EXIST>0 and C.IT_EXIST>0, "OK", "NOK") FROM
(SELECT COUNT(*) FT_EXIST FROM MON.SPARK_FT_MY_ORANGE WHERE EVENT_DATE='###SLICE_VALUE###') A,
(SELECT COUNT(*) IT_EXIST FROM CDR.SPARK_IT_MY_ORANGE_USERS_BACKEND WHERE EVENT_DATE='###SLICE_VALUE###')B,
(SELECT COUNT(*) IT_EXIST FROM CDR.SPARK_IT_MY_ORANGE_USERS_FOLLOW WHERE EVENT_DATE='###SLICE_VALUE###')C
