INSERT INTO MON.SPARK_FT_C2S_BY_CHANNEL_DAY

SELECT

    IS_VIA_ORANGE_MONEY,
    SITE_NAME,
    TOWNNAME,
    REGION,
    SUM(MONTANT) AS MONTANT,
    SUM(NOMBRE) AS NOMBRE,
    TO_DATE(CURRENT_TIMESTAMP) AS INSERT_DATE,
    REFILL_DATE AS EVENT_DATE

FROM
    (
    SELECT
        REFILL_DATE,
        RECEIVER_MSISDN AS MSISDN,
        (CASE WHEN SENDER_MSISDN IN ('695200088', '658080808') THEN 1 ELSE 0 END) AS IS_VIA_ORANGE_MONEY,
        SUM(REFILL_AMOUNT) AS MONTANT,
        COUNT(*) AS NOMBRE
    FROM MON.SPARK_FT_REFILL
    WHERE REFILL_DATE = ' ###SLICE_VALUE###' AND REFILL_MEAN = 'C2S' AND TERMINATION_IND = '200'
    GROUP BY REFILL_DATE, RECEIVER_MSISDN, (CASE WHEN SENDER_MSISDN IN ('695200088', '658080808') THEN 1 ELSE 0 END)
    ) a

    LEFT JOIN

    (
    SELECT
        MSISDN,
        SITE_NAME,
        TOWNNAME,
        ADMINISTRATIVE_REGION AS REGION
    FROM MON.SPARK_FT_CLIENT_LAST_SITE_DAY
    WHERE EVENT_DATE = ' ###SLICE_VALUE###'
    ) b

    ON a.MSISDN = b.MSISDN

GROUP BY REFILL_DATE, IS_VIA_ORANGE_MONEY, SITE_NAME, TOWNNAME, REGION

