SELECT IF(A.FT_EXIST = 0 and B.FT_COUNT>0 and C.FT_COUNT>0 , "OK","NOK") FROM
(SELECT COUNT(*) FT_EXIST FROM MON.SPARK_FT_C2S_BY_CHANNEL_DAY WHERE event_date='###SLICE_VALUE###') A,
(SELECT COUNT(*) FT_COUNT FROM MON.SPARK_FT_REFILL WHERE refill_date='###SLICE_VALUE###') B,
(SELECT COUNT(*) FT_COUNT FROM MON.SPARK_FT_CLIENT_LAST_SITE_DAY WHERE event_date='###SLICE_VALUE###') C




