SELECT IF( CHECK_FILE_COUNT < 24, 'OK','NOK')
FROM 
(
SELECT COUNT(DISTINCT ORIGINAL_FILE_NAME) CHECK_FILE_COUNT FROM CDR.SPARK_IT_ZTE_CHECK_FILE WHERE FILE_DATE = '###SLICE_VALUE###' AND ORIGINAL_FILE_NAME LIKE '%IN_ZTE_CHECK_FILELIST_2%'
) T