INSERT INTO MON.SPARK_FT_MSISDN_RECYCLE
SELECT MSISDN, PROD_STATE_DATE, PROD_STATE_NAME, OSP_ACCOUNT_TYPE, EST_PRESENT_OM, DUREE_INACTIVITE_OM, OM_BALANCE,
    CASE WHEN NVL(OM_BALANCE,0.0) >0 THEN 'FALSE' ELSE 'TRUE' END SOLDE_OM_NUL,
    CASE WHEN RECYCLABLE=1 AND PROD_STATE_NAME !='Termination' and EST_PRESENT_OM='false' then 'RECYCLABLE SANS OM'
        WHEN RECYCLABLE=1 AND PROD_STATE_NAME !='Termination' and EST_PRESENT_OM='true' then 'RECYCLABLE AVEC OM'
        WHEN PROD_STATE_NAME='Non-provisioning' then 'NON PROVISIONING' END CATEGORIE, RECYCLABLE, CURRENT_TIMESTAMP() INSERT_DATE, EVENT_DATE
FROM MON.SPARK_FT_MSISDN_RECYCLAGE A WHERE EVENT_DATE='###SLICE_VALUE###' --2020-05-04'
    AND upper(OSP_ACCOUNT_TYPE)='PREPAID'
    AND ( RECYCLABLE=1 AND PROD_STATE_NAME !='Termination' or PROD_STATE_NAME='Non-provisioning' )