CREATE TABLE MON.SPARK_FT_MSISDN_RECYCLE(
MSISDN VARCHAR(60),
PROD_STATE_DATE TIMESTAMP,
PROD_STATE_NAME VARCHAR(25),
OSP_ACCOUNT_TYPE VARCHAR(25),
EST_PRESENT_OM VARCHAR(10),
DUREE_INACTIVITE_OM VARCHAR(60),
OM_BALANCE DECIMAL(10,2),
SOLDE_OM_NUL VARCHAR(10),
RECYCLABLE INT,
CATEGORIE VARCHAR(50),
INSERT_DATE TIMESTAMP
)
PARTITIONED BY (EVENT_DATE DATE)
STORED AS PARQUET TBLPROPERTIES ('PARQUET.COMPRESS'='SNAPPY')