<<<<<<< Updated upstream
CREATE TABLE AGG.SPARK_FT_A_MSISDN_RECYCLAGE (
  TRANCHE_MSISDN VARCHAR(10),
  EST_PRESENT_ZEBRA VARCHAR(10),
  EST_PRESENT_OM VARCHAR(10),
  PROD_STATE_NAME VARCHAR(30),
  BLOCK_REASON VARCHAR(60),
  ORDER_REASON VARCHAR(100),
  OSP_ACCOUNT_TYPE VARCHAR(15),
  AGE_IN VARCHAR(10),
  SOLDE_OM_NUL VARCHAR(10),
  DUREE_INACTIVITE_OM VARCHAR(50),
  ANTERIORITE_ZEBRA VARCHAR(50),
  NBRE_MSISDN INT,
  NBRE_RECYCLABLE INT,
  INSERT_DATE TIMESTAMP
)
PARTITIONED BY (EVENT_DATE DATE)
STORED AS PARQUET TBLPROPERTIES ('PARQUET.COMPRESS'='SNAPPY')
=======
CREATE TABLE AGG.SPARK_FT_A_MSISDN_RECYCLAGE (
  TRANCHE_MSISDN VARCHAR(10),
  EST_PRESENT_ZEBRA VARCHAR(10),
  EST_PRESENT_OM VARCHAR(10),
  PROD_STATE_NAME VARCHAR(30),
  BLOCK_REASON VARCHAR(60),
  ORDER_REASON VARCHAR(100),
  OSP_ACCOUNT_TYPE VARCHAR(15),
  AGE_IN VARCHAR(10),
  SOLDE_OM_NUL VARCHAR(10),
  DUREE_INACTIVITE_OM VARCHAR(50),
  ANTERIORITE_ZEBRA VARCHAR(50),
  NBRE_MSISDN INT,
  NBRE_RECYCLABLE INT,
  INSERT_DATE TIMESTAMP
)
PARTITIONED BY (EVENT_DATE DATE)
STORED AS PARQUET TBLPROPERTIES ('PARQUET.COMPRESS'='SNAPPY')
>>>>>>> Stashed changes
;