<<<<<<< HEAD
<<<<<<< Updated upstream
SELECT IF( FT_EXIST=0 and PROD>10000 and SUBS>10000 and CONT>10000 and CONT_SNAP>10000 and OM_ACC>1000 and OM_TRANS>1000
    and ZEB_TRANS>1000 and ZEB_MASTER>1000, 'OK', 'NOK' ) TABLES_STATES
FROM ( SELECT COUNT(*) FT_EXIST FROM MON.SPARK_FT_MSISDN_RECYCLAGE WHERE EVENT_DATE='###SLICE_VALUE###' ) FT,
=======
SELECT IF( PROD>10000 and SUBS>10000 and CONT>10000 and CONT_SNAP>10000 and OM_ACC>1000 and OM_TRANS>1000
    and ZEB_TRANS>1000 and ZEB_MASTER>1000 and ZEB_ACTIVE>10000 and OM_ACTIVE>10000, 'OK', 'NOK' ) TABLES_STATES
FROM
>>>>>>> 22006d610ef8883f67a90e982867e4fb51bf3e89
( SELECT COUNT(*) PROD FROM CDR.SPARK_IT_ZTE_PROD_EXTRACT WHERE ORIGINAL_FILE_DATE= DATE_ADD('###SLICE_VALUE###',1) ) A,
( SELECT COUNT(*) SUBS FROM CDR.SPARK_IT_ZTE_SUBS_EXTRACT WHERE ORIGINAL_FILE_DATE= DATE_ADD('###SLICE_VALUE###',1) ) B,
( SELECT COUNT(*) CONT FROM CDR.SPARK_IT_CONT WHERE ORIGINAL_FILE_DATE='###SLICE_VALUE###' ) C,
( SELECT COUNT(*) CONT_SNAP FROM MON.SPARK_FT_CONTRACT_SNAPSHOT WHERE EVENT_DATE= DATE_ADD('###SLICE_VALUE###',1) ) D,
( SELECT COUNT(*) OM_ACC FROM MON.SPARK_FT_OMNY_ACCOUNT_SNAPSHOT WHERE EVENT_DATE=DATE_SUB('###SLICE_VALUE###',1) ) E,
( SELECT COUNT(*) OM_TRANS FROM CDR.spark_IT_OMNY_TRANSACTIONS WHERE TRANSFER_DATETIME='###SLICE_VALUE###' ) F,
( SELECT COUNT(*) ZEB_TRANS FROM CDR.SPARK_IT_ZEBRA_TRANSAC WHERE TRANSFER_DATE='###SLICE_VALUE###' ) G,
<<<<<<< HEAD
( SELECT COUNT(*) ZEB_MASTER FROM CDR.SPARK_IT_ZEBRA_MASTER WHERE TRANSACTION_DATE='###SLICE_VALUE###' ) H
=======
SELECT IF( FT_EXIST=0 and PROD>10000 and SUBS>10000 and CONT>10000 and CONT_SNAP>10000 and OM_ACC>1000 and OM_TRANS>1000
    and ZEB_TRANS>1000 and ZEB_MASTER>1000, 'OK', 'NOK' ) TABLES_STATES
FROM ( SELECT COUNT(*) FT_EXIST FROM MON.SPARK_FT_MSISDN_RECYCLAGE WHERE EVENT_DATE='###SLICE_VALUE###' ) FT,
( SELECT COUNT(*) PROD FROM CDR.SPARK_IT_ZTE_PROD_EXTRACT WHERE ORIGINAL_FILE_DATE= DATE_ADD('###SLICE_VALUE###',1) ) A,
( SELECT COUNT(*) SUBS FROM CDR.SPARK_IT_ZTE_SUBS_EXTRACT WHERE ORIGINAL_FILE_DATE= DATE_ADD('###SLICE_VALUE###',1) ) B,
( SELECT COUNT(*) CONT FROM CDR.SPARK_IT_CONT WHERE ORIGINAL_FILE_DATE='###SLICE_VALUE###' ) C,
( SELECT COUNT(*) CONT_SNAP FROM MON.SPARK_FT_CONTRACT_SNAPSHOT WHERE EVENT_DATE= DATE_ADD('###SLICE_VALUE###',1) ) D,
( SELECT COUNT(*) OM_ACC FROM MON.SPARK_FT_OMNY_ACCOUNT_SNAPSHOT WHERE EVENT_DATE='###SLICE_VALUE###' ) E,
( SELECT COUNT(*) OM_TRANS FROM CDR.spark_IT_OMNY_TRANSACTIONS WHERE TRANSFER_DATETIME='###SLICE_VALUE###' ) F,
( SELECT COUNT(*) ZEB_TRANS FROM CDR.SPARK_IT_ZEBRA_TRANSAC WHERE TRANSFER_DATE='###SLICE_VALUE###' ) G,
( SELECT COUNT(*) ZEB_MASTER FROM CDR.SPARK_IT_ZEBRA_MASTER WHERE TRANSACTION_DATE='###SLICE_VALUE###' ) H
>>>>>>> Stashed changes
=======
( SELECT COUNT(*) ZEB_MASTER FROM CDR.SPARK_IT_ZEBRA_MASTER WHERE TRANSACTION_DATE='###SLICE_VALUE###' ) H,
( SELECT COUNT(*) ZEB_ACTIVE FROM TMP.TT_ZEBRA_ACTIVE_USER WHERE EVENT_DATE=DATE_SUB('###SLICE_VALUE###',1) ) I,
( SELECT COUNT(*) OM_ACTIVE FROM TMP.TT_MSISDN_ACTIVE_OM WHERE EVENT_DATE=DATE_SUB('###SLICE_VALUE###',1) ) J
>>>>>>> 22006d610ef8883f67a90e982867e4fb51bf3e89
