CREATE TABLE MON.SPARK_FT_BDI_OM_KYA
(
    piece_identite varchar(250),
    iban varchar(250),
    rib varchar(250),
    ibu varchar(250),
    numero_compte varchar(250),
    nature_compte varchar(250),
    id_complete_mandataire varchar(250),
    date_creation varchar(250),
    duree_de_vie varchar(250),
    raison_sociale varchar(250),
    sigle_raison_sociale varchar(250),
    forme_juridique varchar(250),
    secteur_activite_eco varchar(250),
    numero_regis_commerce varchar(250),
    numero_identification_fiscale varchar(250),
    pays_siege_social varchar(250),
    ville_siege_social varchar(250),
    statut_client varchar(250),
    nature_client_titulaire_compte varchar(250),
    type_compte varchar(250),
    code_devise varchar(250),
    statut_compte varchar(250),
    id_interne_mandataire varchar(250),
    numero_piece_mandataire varchar(250),
    numero_compte_om_mandataire varchar(250),
    numero_ibu_mandataire varchar(250),
    situation_judiciaire varchar(250),
    date_debut_interdiction_judiciaire varchar(250),
    date_fin_interdiction_judiciaire varchar(250),
    service_souscrit varchar(250),
    guid varchar(250),
    pays_residence varchar(250),
    code_agent_economique varchar(250),
    code_secteur_activite varchar(250),
    notation_interne varchar(250),
    ppe varchar(250),
    risque_AML varchar(250),
    groupe varchar(250),
    profil_interne varchar(250),
    qualite_mandataire varchar(250),
    responsabilite_compte varchar(250),
    date_expiration_piece_mandataire varchar(250),
    lieu_emission_piece_mandataire varchar(250),
    nom_mandataire varchar(250),
    prenom_mandataire varchar(250),
    nationalite_mandataire varchar(250),
    date_naissance_mandataire varchar(250),
    est_conforme_hors_cip varchar(20),
    est_conforme_cip varchar(20),
    est_multicompte_om varchar(20),
    est_actif_30 varchar(250),
    est_actif_90 varchar(250),
    est_client_telco varchar(250),
    est_suspendu_telco varchar(250),
    est_suspendu_om varchar(250)
   )
  PARTITIONED BY (EVENT_DATE DATE)
  STORED AS PARQUET
  TBLPROPERTIES ("parquet.compress"="SNAPPY");




CREATE TABLE TMP.TT_BDI_OM_KYA_STEP_1
(
    new_iban  varchar(250),
    new_RIB  varchar(250),
    new_IBU varchar(250),
    msisdn varchar(250),
    new_Natureducompte varchar(250),
    new_mandatairepartenaireId varchar(250),
    new_Datedecration varchar(250),
    new_Dureedevie varchar(250),
    new_raisonsociale varchar(250),
    new_Sigledelaraisonsociale varchar(250),
    new_Formejuridique varchar(250),
    new_Secteurdactiviteconomique  varchar(250), 
    new_Numeroderegistredecommerce varchar(250),
    new_Numerodidentificationfiscale varchar(250),
    new_PaysdusigeSocial varchar(250),
    new_Ville varchar(250),
    new_Statutduclient  varchar(250),
    new_Natureduclienttitulaireducompte  varchar(250),
    new_Typeducompte varchar(250),
    new_Codedevise  varchar(250),
    new_Statutducompte varchar(250),
    new_Identifiantinternedumandataire varchar(250),
    new_Numerodepicedumandataire varchar(250),
    new_NumerodecompteOMdumandataire varchar(250),
    new_NumerodelIBUdumandataire varchar(250),
    new_Situationjudiciaire varchar(250),
    new_datedbutinterdictionjudiciaire  varchar(250),
    new_datefininterdictionjudiciaire  varchar(250),
    guid varchar(250),
    new_Codeagentconomique varchar(250),
    new_Codesecteurdactivit varchar(250),
    new_Notationinterne varchar(250),
    new_PPE  varchar(250),
    new_RisqueAML varchar(250),
    new_Groupe varchar(250),
    new_ProfilInterne  varchar(250),
    new_Qualitdumandataire varchar(250),
    new_Responsabilitducompte varchar(250),
    new_DatedExpirationdelapiece varchar(250),
    new_DelivrerA varchar(250),
    new_Nom varchar(250),
    new_Prenom varchar(250),
    new_Nationalite varchar(250),
    new_Datedenaissance varchar(250),
    est_suspendu_telco varchar(250),
    est_suspendu_om varchar(250),
    event_date varchar(250)
);


CREATE TABLE TMP.TT_BDI_OM_KYA_STEP_2
(
    new_npiecedidentite varchar(250),
    new_iban  varchar(250),
    new_RIB  varchar(250),
    new_IBU varchar(250),
    msisdn varchar(250),
    new_Natureducompte varchar(250),
    new_mandatairepartenaireId varchar(250),
    new_Datedecration varchar(250),
    new_Dureedevie varchar(250),
    new_raisonsociale varchar(250),
    new_Sigledelaraisonsociale varchar(250),
    new_Formejuridique varchar(250),
    new_Secteurdactiviteconomique  varchar(250),
    new_Numeroderegistredecommerce varchar(250),
    new_Numerodidentificationfiscale varchar(250),
    new_PaysdusigeSocial varchar(250),
    new_Ville varchar(250),
    new_Statutduclient  varchar(250),
    new_Natureduclienttitulaireducompte  varchar(250),
    new_Typeducompte varchar(250),
    new_Codedevise  varchar(250),
    new_Statutducompte varchar(250),
    new_Identifiantinternedumandataire varchar(250),
    new_Numerodepicedumandataire varchar(250),
    new_NumerodecompteOMdumandataire varchar(250),
    new_NumerodelIBUdumandataire varchar(250),
    new_Situationjudiciaire varchar(250),
    new_datedbutinterdictionjudiciaire  varchar(250),
    new_datefininterdictionjudiciaire  varchar(250),
    new_serviceorangemoney varchar(250),
    guid varchar(250),
    new_Paysdersidence varchar(250),
    new_Codeagentconomique varchar(250),
    new_Codesecteurdactivit varchar(250),
    new_Notationinterne varchar(250),
    new_PPE  varchar(250),
    new_RisqueAML varchar(250),
    new_Groupe varchar(250),
    new_ProfilInterne  varchar(250),
    new_Qualitdumandataire varchar(250),
    new_Responsabilitducompte varchar(250),
    new_DatedExpirationdelapiece varchar(250),
    new_DelivrerA varchar(250),
    new_Nom varchar(250),
    new_Prenom varchar(250),
    new_Nationalite varchar(250),
    new_Datedenaissance varchar(250),
    est_suspendu_telco varchar(250),
    est_suspendu_om varchar(250),
    event_date varchar(250)
   );

CREATE TABLE TMP.TT_BDI_OM_KYA_STEP_3
(
    piece_identite varchar(250),
    iban varchar(250),
    rib varchar(250),
    ibu varchar(250),
    numero_compte varchar(250),
    nature_compte varchar(250),
    id_complete_mandataire varchar(250),
    date_creation varchar(250),
    duree_de_vie varchar(250),
    raison_sociale varchar(250),
    sigle_raison_sociale varchar(250),
    forme_juridique varchar(250),
    secteur_activite_eco varchar(250),
    numero_regis_commerce varchar(250),
    numero_identification_fiscale varchar(250),
    pays_siege_social varchar(250),
    ville_siege_social varchar(250),
    statut_client varchar(250),
    nature_client_titulaire_compte varchar(250),
    type_compte varchar(250),
    code_devise varchar(250),
    statut_compte varchar(250),
    id_interne_mandataire varchar(250),
    numero_piece_mandataire varchar(250),
    numero_compte_om_mandataire varchar(250),
    numero_ibu_mandataire varchar(250),
    situation_judiciaire varchar(250),
    date_debut_interdiction_judiciaire varchar(250),
    date_fin_interdiction_judiciaire varchar(250),
    service_souscrit varchar(250),
    guid varchar(250),
    pays_residence varchar(250),
    code_agent_economique varchar(250),
    code_secteur_activite varchar(250),
    notation_interne varchar(250),
    ppe varchar(250),
    risque_AML varchar(250),
    groupe varchar(250),
    profil_interne varchar(250),
    qualite_mandataire varchar(250),
    responsabilite_compte varchar(250),
    date_expiration_piece_mandataire varchar(250),
    lieu_emission_piece_mandataire varchar(250),
    nom_mandataire varchar(250),
    prenom_mandataire varchar(250),
    nationalite_mandataire varchar(250),
    date_naissance_mandataire varchar(250),
    est_actif_30 varchar(250),
    est_actif_90 varchar(250),
    est_client_telco varchar(250),
    est_suspendu_telco varchar(250),
    est_suspendu_om varchar(250),
    event_date varchar(250)
   );


CREATE TABLE TMP.TT_BDI_OM_KYA_STEP_4
(
    numeropiece varchar(250),
    est_multicompte_om varchar(20)
);


CREATE TABLE TMP.TT_BDI_OM_KYA_STEP_5
(
    piece_identite varchar(250),
    iban varchar(250),
    rib varchar(250),
    ibu varchar(250),
    numero_compte varchar(250),
    nature_compte varchar(250),
    id_complete_mandataire varchar(250),
    date_creation varchar(250),
    duree_de_vie varchar(250),
    raison_sociale varchar(250),
    sigle_raison_sociale varchar(250),
    forme_juridique varchar(250),
    secteur_activite_eco varchar(250),
    numero_regis_commerce varchar(250),
    numero_identification_fiscale varchar(250),
    pays_siege_social varchar(250),
    ville_siege_social varchar(250),
    statut_client varchar(250),
    nature_client_titulaire_compte varchar(250),
    type_compte varchar(250),
    code_devise varchar(250),
    statut_compte varchar(250),
    id_interne_mandataire varchar(250),
    numero_piece_mandataire varchar(250),
    numero_compte_om_mandataire varchar(250),
    numero_ibu_mandataire varchar(250),
    situation_judiciaire varchar(250),
    date_debut_interdiction_judiciaire varchar(250),
    date_fin_interdiction_judiciaire varchar(250),
    service_souscrit varchar(250),
    guid varchar(250),
    pays_residence varchar(250),
    code_agent_economique varchar(250),
    code_secteur_activite varchar(250),
    notation_interne varchar(250),
    ppe varchar(250),
    risque_AML varchar(250),
    groupe varchar(250),
    profil_interne varchar(250),
    qualite_mandataire varchar(250),
    responsabilite_compte varchar(250),
    date_expiration_piece_mandataire varchar(250),
    lieu_emission_piece_mandataire varchar(250),
    nom_mandataire varchar(250),
    prenom_mandataire varchar(250),
    nationalite_mandataire varchar(250),
    date_naissance_mandataire varchar(250),
    est_multicompte_om varchar(20),
    est_actif_30 varchar(250),
    est_actif_90 varchar(250),
    est_client_telco varchar(250),
    est_suspendu_telco varchar(250),
    est_suspendu_om varchar(250)
   )
  PARTITIONED BY (EVENT_DATE DATE)
  STORED AS PARQUET
  TBLPROPERTIES ("parquet.compress"="SNAPPY");
