CREATE EXTERNAL TABLE CDR.tt_billcycle (
  ORIGINAL_FILE_NAME VARCHAR(200),
  ORIGINAL_FILE_SIZE INT,
  ORIGINAL_FILE_LINE_COUNT INT,
  BILL_CYCLE_ID  VARCHAR(200),
  DESCRIPTION  VARCHAR(200)
)
COMMENT 'external tables-TT'
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|'
LOCATION '/PROD/TT/ZSMART/BILLCYCLE_'
TBLPROPERTIES ('serialization.null.format'='')
;