CREATE EXTERNAL TABLE CDR.TT_BILLCYCLE
(

	BILL_CYCLE_ID VARCHAR(200),
	DESCRIPTION VARCHAR(200),
	ORIGINAL_FILE_NAME VARCHAR(200),
    ORIGINAL_FILE_SIZE INT,
    ORIGINAL_FILE_LINE_COUNT INT

)
COMMENT 'BILLCYCLE external tables-TT'
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|'
LOCATION '/PROD/TT/ZMART/BILLCYCLE_'
TBLPROPERTIES ('serialization.null.format'='');