CREATE EXTERNAL TABLE CDR.TT_CHANTEL
(
CustId VARCHAR(200),
Subs_id VARCHAR(200),
ACCNBR VARCHAR(200),
Update_date VARCHAR(200),
ORIGINAL_FILE_NAME VARCHAR(200),
ORIGINAL_FILE_SIZE INT,
ORIGINAL_FILE_LINE_COUNT INT
)
COMMENT 'CHANTEL external tables-TT'
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|'
LOCATION '/PROD/TT/ZMART/CHANTEL_'
TBLPROPERTIES ('serialization.null.format'='');

