CREATE EXTERNAL TABLE CDR.TT_RATEPLAN
(


Default_price_plan_ID VARCHAR(200),
DESCRIPTION VARCHAR(200),
ORIGINAL_FILE_NAME VARCHAR(200),
ORIGINAL_FILE_SIZE VARCHAR(200),
ORIGINAL_FILE_LINE_COUNT VARCHAR(200)

)
COMMENT 'RATEPLAN external tables-TT'
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|'
LOCATION '/PROD/TT/ZMART/RATEPLAN_'
TBLPROPERTIES ('serialization.null.format'='');

Default_price_plan_ID|DESCRIPTION