CREATE EXTERNAL TABLE CDR.TT_CHANSIM
(
    Cust_ID VARCHAR(200),
    SUBS_ID VARCHAR(200),
    ICCID VARCHAR(200),
    IMSI VARCHAR(200),
    UPDATE_DATE VARCHAR(200),
    CUID VARCHAR(200),
    ORIGINAL_FILE_NAME VARCHAR(200),
    ORIGINAL_FILE_SIZE VARCHAR(200),
    ORIGINAL_FILE_LINE_COUNT VARCHAR(200)
)
    COMMENT 'CHANSIM external tables-TT'
    ROW FORMAT DELIMITED FIELDS TERMINATED BY '|'
    LOCATION '/PROD/TT/ZMART/CHANSIM_'
    TBLPROPERTIES ('serialization.null.format'='');