CREATE EXTERNAL TABLE CDR.TT_PAY
(
PAYMENT_ID VARCHAR(200),
CUST_ID VARCHAR(200),
Invoice_number VARCHAR(200),
payment_amount VARCHAR(200),
PAYMENT_DATE VARCHAR(200),
CUID VARCHAR(200),
ORIGINAL_FILE_NAME VARCHAR(200),
ORIGINAL_FILE_SIZE VARCHAR(200),
ORIGINAL_FILE_LINE_COUNT VARCHAR(200)
)
COMMENT 'PAY external tables-TT'
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|'
LOCATION '/PROD/TT/ZSMART/PAY_'
TBLPROPERTIES ('serialization.null.format'='');