CREATE EXTERNAL TABLE CDR.TT_GESFLOT
(

CustId VARCHAR(200),
CustName VARCHAR(200),
phoneNumber VARCHAR(200),
Email VARCHAR(200),
faxNumber VARCHAR(200),
ORIGINAL_FILE_NAME VARCHAR(200),
ORIGINAL_FILE_SIZE VARCHAR(200),
ORIGINAL_FILE_LINE_COUNT VARCHAR(200)
)
COMMENT 'GESTFLOT external tables-TT'
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|'
LOCATION '/PROD/TT/ZSMART/GESTFLOT_'
TBLPROPERTIES ('serialization.null.format'='');