CREATE EXTERNAL TABLE CDR.tt_conserv (
  ORIGINAL_FILE_NAME VARCHAR(200),
  ORIGINAL_FILE_SIZE INT,
  ORIGINAL_FILE_LINE_COUNT INT,
  SUBS_ID  VARCHAR(200),
  SERVICE_TYPE  VARCHAR(200),
  OFFER_NAME  VARCHAR(200)
)
COMMENT 'external tables-TT'
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|'
LOCATION '/PROD/TT/ZSMART/CONSERV_'
TBLPROPERTIES ('serialization.null.format'='')
;
