SELECT IF(A.FT_EXIST = 0 and B.FT_PREVIEW_DAY_EXIST >=0 AND C.FT_MSC_EXISTS >0,"OK","NOK") FROM
(SELECT count(*) FT_EXIST FROM AGG.SPARK_FT_X_INTERCO_FINAL WHERE SDATE='###SLICE_VALUE###') A,
(SELECT COUNT(*) FT_PREVIEW_DAY_EXIST FROM AGG.SPARK_FT_X_INTERCO_FINAL WHERE SDATE=DATE_SUB('###SLICE_VALUE###',1))B,
(SELECT COUNT(*) FT_MSC_EXISTS FROM AGG.SPARK_FT_AG_INTERCO WHERE SDATE='###SLICE_VALUE###')C;

