SELECT IF(T_1.FT_EXIST = 0 and T_2.CONTRACT_SNAPSHOT_EXIST>0 and T_3.PRICE_PLAN_EXTRACT_EXIST>0,"OK","NOK") EXTRACT_EXIST
FROM
(SELECT COUNT(*) FT_EXIST FROM MON.spark_ft_recharge WHERE TRANSACTION_DATE='###SLICE_VALUE###') T_1,
(SELECT COUNT(*) CONTRACT_SNAPSHOT_EXIST FROM MON.SPARK_FT_CONTRACT_SNAPSHOT WHERE EVENT_DATE BETWEEN DATE_SUB('###SLICE_VALUE###',7) AND '###SLICE_VALUE###') T_2,
(SELECT COUNT(*) PRICE_PLAN_EXTRACT_EXIST FROM CDR.SPARK_IT_ZTE_PRICE_PLAN_EXTRACT WHERE ORIGINAL_FILE_DATE='###SLICE_VALUE###') T_3
