CREATE TABLE AGG.SPARK_FT_A_CBM_AGREGAT
(
site_name                 varchar(255),
 multi                     varchar(255),
 operateur                 varchar(255),
 tenure                    varchar(255),
 segment                   varchar(255),
 mou_onnet                 varchar(255),
 mou_ofnet                 varchar(255),
 mou_inter                 varchar(255),
 ma_voice_onnet            varchar(255),
 ma_voice_ofnet            varchar(255),
 ma_voice_inter            varchar(255),
 ma_sms_ofnet              varchar(255),
 ma_sms_inter              varchar(255),
 ma_sms_onnet              varchar(255),
 ma_data                   varchar(255),
 ma_vas                    varchar(255),
 ma_gos_sva                varchar(255),
 ma_voice_roaming          varchar(255),
 ma_sms_roaming            varchar(255),
 ma_sms_sva                varchar(255),
 ma_voice_sva              varchar(255),
 user_voice                varchar(255),
 bdle_name                 varchar(255),
 bdle_cost_retail          varchar(255),
 bdle_cost_subs            varchar(255),
 volume_data               varchar(600),
 user_data1                varchar(255),
 user_data2                varchar(255),
 montant_vas               varchar(255),
 destination_type          varchar(255),
 destination               varchar(255),
 traffic_data              varchar(255),
 rated_sms_total_count     varchar(255),
 in_duration               varchar(255),
 rated_duration            varchar(255),
 loc_site_name             varchar(255),
 actif_90                  varchar(255),
 inactif_90                varchar(255),
 gross_add                 varchar(255),
 insert_date               timestamp
)
COMMENT 'FT_CBM_CHURN_DAILY - FT'
  PARTITIONED BY (EVENT_DATE    DATE)
STORED AS PARQUET TBLPROPERTIES ('PARQUET.COMPRESS'='SNAPPY');
