SELECT
WINDOW.start START_TIME
,WINDOW.end END_TIME
, COALESCE(RATING_EVENT_SERVICE,CAST(RE_ID AS STRING),'UNKNOWN_SERVICE_CODE') SERVICE_CODE
, nvl((CASE WHEN RATING_EVENT_NAME LIKE 'VOICE%' THEN TRIM(SUBSTR(RATING_EVENT_NAME,6))
    WHEN RATING_EVENT_NAME LIKE 'SMS%' THEN TRIM(SUBSTR(RATING_EVENT_NAME,4))
    WHEN RATING_EVENT_NAME LIKE 'DATA%' THEN TRIM(SUBSTR(RATING_EVENT_NAME,5))
    WHEN RATING_EVENT_NAME LIKE 'FAX%' THEN TRIM(SUBSTR(RATING_EVENT_NAME,4))
    ELSE NVL(RATING_EVENT_NAME,CAST(RE_ID AS STRING)) END
    ),'UNKNOWN_OTHER_PARTY_ZONE') OTHER_PARTY_ZONE
, nvl((CASE
        WHEN RATING_EVENT_NAME LIKE '%URGENT%' AND FN_GET_NNP_MSISDN_9DIGITS (CALLED_NBR) LIKE '69%' THEN 'ONNET'
        WHEN RATING_EVENT_NAME LIKE '%URGENT%' AND FN_GET_NNP_MSISDN_9DIGITS (CALLED_NBR) NOT LIKE '69%' THEN 'OFFNET'
        ELSE NVL(RATING_EVENT_ZONE,CAST(RE_ID AS STRING))
   END),'UNKNOWN_CALL_DESTINATION_TYPE') CALL_DESTINATION_TYPE
, nvl(INTERNATIONAL_ROAMING_FLAG,'UNKNOWN_ROAMING_INDICATOR') ROAMING_INDICATOR
, nvl((CASE WHEN PROVIDER_ID = 0 OR PROVIDER_ID = 2 THEN 'OCM'
    WHEN PROVIDER_ID = 1 THEN 'SET'
    WHEN PROVIDER_ID IS NULL AND BILLING_NBR IS NULL THEN 'OCM'
    WHEN PROVIDER_ID IS NULL AND FN_GET_NNP_MSISDN_9DIGITS (BILLING_NBR) NOT LIKE '692%' THEN 'OCM'
    WHEN PROVIDER_ID IS NULL AND FN_GET_NNP_MSISDN_9DIGITS (BILLING_NBR) LIKE '692%' THEN 'SET'
    ELSE CAST(PROVIDER_ID AS STRING) END),'UNKNOWN_OPERATOR_CODE') OPERATOR_CODE
, nvl((CASE WHEN CALL_TYPE = 0 THEN 'UNK'
        WHEN CALL_TYPE = 1 THEN 'OUT'
        WHEN CALL_TYPE = 2 THEN 'INC'
        WHEN CALL_TYPE = 3 THEN 'FWD'
        ELSE CAST(CALL_TYPE AS STRING)
    END ),'UNKNOWN_TRANSACTION_TYPE') TRANSACTION_TYPE
, nvl(RESULT_CODE,'UNKNOWN_TRANSACTION_TERM_INDICATOR') TRANSACTION_TERM_INDICATOR
, coalesce (PC1.PROFILE_NAME,CAST(A.PROD_SPEC_ID AS STRING),'UNKNOWN_ORIGINAL_COMMERCIAL_PROFILE') ORIGINAL_COMMERCIAL_PROFILE
, nvl(TRIM(IF(RATING_EVENT_OPERATOR='OFFNET',
    CASE
        WHEN FN_GET_NNP_MSISDN_SIMPLE_DESTN(FN_GET_NNP_MSISDN(CALLED_NBR)) = 'OCM' THEN 'ONNET'
        WHEN FN_GET_NNP_MSISDN_SIMPLE_DESTN(FN_GET_NNP_MSISDN(CALLED_NBR)) = 'INTERNATIONAL' THEN 'INT'
        WHEN FN_GET_NNP_MSISDN_SIMPLE_DESTN(FN_GET_NNP_MSISDN(CALLED_NBR)) = 'VIETTEL' THEN 'NEXTTEL'
        WHEN FN_GET_NNP_MSISDN_SIMPLE_DESTN(FN_GET_NNP_MSISDN(CALLED_NBR)) = 'INTERNATIONAL_CMR' THEN 'INT'
        WHEN FN_GET_NNP_MSISDN_SIMPLE_DESTN(FN_GET_NNP_MSISDN(CALLED_NBR)) = 'CAMTEL' THEN 'CAM'
        WHEN FN_GET_NNP_MSISDN_SIMPLE_DESTN(FN_GET_NNP_MSISDN(CALLED_NBR)) = 'OCM_SHORT' THEN 'VAS'
        ELSE FN_GET_NNP_MSISDN_SIMPLE_DESTN(FN_GET_NNP_MSISDN(CALLED_NBR))
    END ,
 NVL(RATING_EVENT_OPERATOR,CAST(RE_ID AS STRING)))),'UNKNOWN_CALL_DESTINATION_CODE') CALL_DESTINATION_CODE
, nvl(NVL(PP1.PRICE_PLAN_NAME,NVL(PP2.PRICE_PLAN_NAME,NVL(PP3.PRICE_PLAN_NAME,NVL(PP4.PRICE_PLAN_NAME,CAST(PRICE_PLAN_ID4 AS STRING))))),'UNKNOWN_COMMERCIAL_OFFER') COMMERCIAL_OFFER
, nvl(NVL(PC1.PROFILE_NAME,CAST(A.PROD_SPEC_ID AS STRING)),'UNKNOWN_COMMERCIAL_PROFILE') COMMERCIAL_PROFILE
, nvl(A.ORIGINAL_FILE_NAME,'UNKNOWN_ORIGINAL_FILE_NAME') ORIGINAL_FILE_NAME
,APPROX_COUNT_DISTINCT(FN_GET_NNP_MSISDN_9DIGITS (CALLING_NBR))  NBS_SERVED_PARTY
,APPROX_COUNT_DISTINCT(FN_GET_NNP_MSISDN_9DIGITS (CALLED_NBR))  NBS_OTHER_PARTY
, MAX(CASE WHEN (NVL(CHARGE1,0) + NVL(CHARGE2,0) + NVL(CHARGE3,0) + NVL(CHARGE4,0)) > 0 THEN NVL(DURATION,0) ELSE 0 END) RATED_DURATION
, MAX(NVL(DURATION,0)) CALL_PROCESS_TOTAL_DURATION
, MAX(CELL_A) LOCATION_CI
, MAX((CASE WHEN BTI1.ACCT_RES_RATING_TYPE = 'MB' THEN NVL(CHARGE1,0)
        ELSE 0 END)
    + (CASE WHEN BTI2.ACCT_RES_RATING_TYPE = 'MB' THEN NVL(CHARGE2,0)
        ELSE 0 END)
    + (CASE WHEN BTI3.ACCT_RES_RATING_TYPE = 'MB' THEN NVL(CHARGE3,0)
        ELSE 0 END)
    + (CASE WHEN BTI4.ACCT_RES_RATING_TYPE = 'MB' THEN NVL(CHARGE4,0)
        ELSE 0 END))/100 MAIN_RATED_AMOUNT
, MAX((CASE WHEN BTI1.ACCT_RES_RATING_TYPE = 'PB' THEN NVL(CHARGE1,0)
        ELSE 0 END)
    + (CASE WHEN BTI2.ACCT_RES_RATING_TYPE = 'PB' THEN NVL(CHARGE2,0)
        ELSE 0 END)
    + (CASE WHEN BTI3.ACCT_RES_RATING_TYPE = 'PB' THEN NVL(CHARGE3,0)
        ELSE 0 END)
    + (CASE WHEN BTI4.ACCT_RES_RATING_TYPE = 'PB' THEN NVL(CHARGE4,0)
        ELSE 0 END))/100 PROMO_RATED_AMOUNT
, MAX((CASE WHEN BTI1.ACCT_RES_RATING_TYPE = 'MB' THEN -NVL(BALANCE1,0)
        ELSE 0 END)
    + (CASE WHEN BTI2.ACCT_RES_RATING_TYPE = 'MB' THEN -NVL(BALANCE2,0)
        ELSE 0 END)
    + (CASE WHEN BTI3.ACCT_RES_RATING_TYPE = 'MB' THEN -NVL(BALANCE3,0)
        ELSE 0 END)
    + (CASE WHEN BTI4.ACCT_RES_RATING_TYPE = 'MB' THEN -NVL(BALANCE4,0)
        ELSE 0 END))/100 MAIN_REMAINING_CREDIT
, MAX((CASE WHEN BTI1.ACCT_RES_RATING_TYPE = 'PB' THEN -NVL(BALANCE1,0)
        ELSE 0 END)
    + (CASE WHEN BTI2.ACCT_RES_RATING_TYPE = 'PB' THEN -NVL(BALANCE2,0)
        ELSE 0 END)
    + (CASE WHEN BTI3.ACCT_RES_RATING_TYPE = 'PB' THEN -NVL(BALANCE3,0)
        ELSE 0 END)
    + (CASE WHEN BTI4.ACCT_RES_RATING_TYPE = 'PB' THEN -NVL(BALANCE4,0)
        ELSE 0 END))/100 PROMO_REMAINING_CREDIT
FROM in_zte_voice_sms_stream A
LEFT JOIN DIM.SPARK_DT_RATING_EVENT B ON A.RE_ID = B.RATING_EVENT_ID
LEFT JOIN (SELECT ACCT_RES_ID, ACCT_ITEM_TYPE_ID, UPPER(ACCT_RES_NAME) ACCT_RES_NAME, ACCT_RES_RATING_TYPE, ACCT_RES_RATING_UNIT FROM DIM.DT_BALANCE_TYPE_ITEM) BTI1 ON A.ACCT_ITEM_TYPE_ID1 = BTI1.ACCT_ITEM_TYPE_ID
LEFT JOIN (SELECT ACCT_RES_ID, ACCT_ITEM_TYPE_ID, UPPER(ACCT_RES_NAME) ACCT_RES_NAME, ACCT_RES_RATING_TYPE, ACCT_RES_RATING_UNIT FROM DIM.DT_BALANCE_TYPE_ITEM) BTI2 ON ACCT_ITEM_TYPE_ID2 = BTI2.ACCT_ITEM_TYPE_ID
LEFT JOIN (SELECT ACCT_RES_ID, ACCT_ITEM_TYPE_ID, UPPER(ACCT_RES_NAME) ACCT_RES_NAME, ACCT_RES_RATING_TYPE, ACCT_RES_RATING_UNIT FROM DIM.DT_BALANCE_TYPE_ITEM) BTI3 ON A.ACCT_ITEM_TYPE_ID3 = BTI3.ACCT_ITEM_TYPE_ID
LEFT JOIN (SELECT ACCT_RES_ID, ACCT_ITEM_TYPE_ID, UPPER(ACCT_RES_NAME) ACCT_RES_NAME, ACCT_RES_RATING_TYPE, ACCT_RES_RATING_UNIT FROM DIM.DT_BALANCE_TYPE_ITEM) BTI4 ON A.ACCT_ITEM_TYPE_ID4 = BTI4.ACCT_ITEM_TYPE_ID
LEFT JOIN (SELECT PRICE_PLAN_ID, PRICE_PLAN_NAME, PRICE_PLAN_CODE FROM CDR.SPARK_IT_ZTE_PRICE_PLAN_EXTRACT WHERE ORIGINAL_FILE_DATE = '###SLICE_VALUE###' ) pp1 ON ( a.PRICE_PLAN_ID1 = pp1.PRICE_PLAN_ID)
LEFT JOIN (SELECT PRICE_PLAN_ID, PRICE_PLAN_NAME, PRICE_PLAN_CODE FROM cdr.SPARK_IT_ZTE_PRICE_PLAN_EXTRACT WHERE ORIGINAL_FILE_DATE = '###SLICE_VALUE###' ) pp2 ON ( a.PRICE_PLAN_ID2 = pp2.PRICE_PLAN_ID)
LEFT JOIN (SELECT PRICE_PLAN_ID, PRICE_PLAN_NAME, PRICE_PLAN_CODE FROM CDR.SPARK_IT_ZTE_PRICE_PLAN_EXTRACT WHERE ORIGINAL_FILE_DATE = '###SLICE_VALUE###' ) pp3 ON ( a.PRICE_PLAN_ID3 = pp3.PRICE_PLAN_ID)
LEFT JOIN (SELECT PRICE_PLAN_ID, PRICE_PLAN_NAME, PRICE_PLAN_CODE FROM cdr.SPARK_IT_ZTE_PRICE_PLAN_EXTRACT WHERE ORIGINAL_FILE_DATE = '###SLICE_VALUE###' ) pp4 ON ( a.PRICE_PLAN_ID4 = pp4.PRICE_PLAN_ID)
LEFT JOIN (SELECT PRICE_PLAN_ID, PRICE_PLAN_NAME, PRICE_PLAN_CODE FROM CDR.SPARK_IT_ZTE_PRICE_PLAN_EXTRACT WHERE ORIGINAL_FILE_DATE = '###SLICE_VALUE###' ) pp5 ON ( a.PRICE_PLAN_CODE = pp5.PRICE_PLAN_CODE)
LEFT JOIN (SELECT PROFILE_ID, MAX(UPPER(PROFILE_NAME)) PROFILE_NAME FROM CDR.SPARK_IT_ZTE_PROFILE GROUP BY PROFILE_ID) PC1 ON A.PROD_SPEC_ID = PC1.PROFILE_ID
GROUP BY
COALESCE(RATING_EVENT_SERVICE,CAST(RE_ID AS STRING),'UNKNOWN_SERVICE_CODE')
, nvl((CASE WHEN RATING_EVENT_NAME LIKE 'VOICE%' THEN TRIM(SUBSTR(RATING_EVENT_NAME,6))
    WHEN RATING_EVENT_NAME LIKE 'SMS%' THEN TRIM(SUBSTR(RATING_EVENT_NAME,4))
    WHEN RATING_EVENT_NAME LIKE 'DATA%' THEN TRIM(SUBSTR(RATING_EVENT_NAME,5))
    WHEN RATING_EVENT_NAME LIKE 'FAX%' THEN TRIM(SUBSTR(RATING_EVENT_NAME,4))
    ELSE NVL(RATING_EVENT_NAME,CAST(RE_ID AS STRING)) END
    ),'UNKNOWN_OTHER_PARTY_ZONE')
, nvl((CASE
        WHEN RATING_EVENT_NAME LIKE '%URGENT%' AND FN_GET_NNP_MSISDN_9DIGITS (CALLED_NBR) LIKE '69%' THEN 'ONNET'
        WHEN RATING_EVENT_NAME LIKE '%URGENT%' AND FN_GET_NNP_MSISDN_9DIGITS (CALLED_NBR) NOT LIKE '69%' THEN 'OFFNET'
        ELSE NVL(RATING_EVENT_ZONE,CAST(RE_ID AS STRING))
   END),'UNKNOWN_CALL_DESTINATION_TYPE')
, nvl(INTERNATIONAL_ROAMING_FLAG,'UNKNOWN_ROAMING_INDICATOR')
, nvl((CASE WHEN PROVIDER_ID = 0 OR PROVIDER_ID = 2 THEN 'OCM'
    WHEN PROVIDER_ID = 1 THEN 'SET'
    WHEN PROVIDER_ID IS NULL AND BILLING_NBR IS NULL THEN 'OCM'
    WHEN PROVIDER_ID IS NULL AND FN_GET_NNP_MSISDN_9DIGITS (BILLING_NBR) NOT LIKE '692%' THEN 'OCM'
    WHEN PROVIDER_ID IS NULL AND FN_GET_NNP_MSISDN_9DIGITS (BILLING_NBR) LIKE '692%' THEN 'SET'
    ELSE CAST(PROVIDER_ID AS STRING) END),'UNKNOWN_OPERATOR_CODE')
, nvl((CASE WHEN CALL_TYPE = 0 THEN 'UNK'
        WHEN CALL_TYPE = 1 THEN 'OUT'
        WHEN CALL_TYPE = 2 THEN 'INC'
        WHEN CALL_TYPE = 3 THEN 'FWD'
        ELSE CAST(CALL_TYPE AS STRING)
    END ),'UNKNOWN_TRANSACTION_TYPE')
, nvl(RESULT_CODE,'UNKNOWN_TRANSACTION_TERM_INDICATOR')
, coalesce (PC1.PROFILE_NAME,CAST(A.PROD_SPEC_ID AS STRING),'UNKNOWN_ORIGINAL_COMMERCIAL_PROFILE')
, nvl(TRIM(IF(RATING_EVENT_OPERATOR='OFFNET',
    CASE
        WHEN FN_GET_NNP_MSISDN_SIMPLE_DESTN(FN_GET_NNP_MSISDN(CALLED_NBR)) = 'OCM' THEN 'ONNET'
        WHEN FN_GET_NNP_MSISDN_SIMPLE_DESTN(FN_GET_NNP_MSISDN(CALLED_NBR)) = 'INTERNATIONAL' THEN 'INT'
        WHEN FN_GET_NNP_MSISDN_SIMPLE_DESTN(FN_GET_NNP_MSISDN(CALLED_NBR)) = 'VIETTEL' THEN 'NEXTTEL'
        WHEN FN_GET_NNP_MSISDN_SIMPLE_DESTN(FN_GET_NNP_MSISDN(CALLED_NBR)) = 'INTERNATIONAL_CMR' THEN 'INT'
        WHEN FN_GET_NNP_MSISDN_SIMPLE_DESTN(FN_GET_NNP_MSISDN(CALLED_NBR)) = 'CAMTEL' THEN 'CAM'
        WHEN FN_GET_NNP_MSISDN_SIMPLE_DESTN(FN_GET_NNP_MSISDN(CALLED_NBR)) = 'OCM_SHORT' THEN 'VAS'
        ELSE FN_GET_NNP_MSISDN_SIMPLE_DESTN(FN_GET_NNP_MSISDN(CALLED_NBR))
    END ,
 NVL(RATING_EVENT_OPERATOR,CAST(RE_ID AS STRING)))),'UNKNOWN_CALL_DESTINATION_CODE')
, nvl(NVL(PP1.PRICE_PLAN_NAME,NVL(PP2.PRICE_PLAN_NAME,NVL(PP3.PRICE_PLAN_NAME,NVL(PP4.PRICE_PLAN_NAME,CAST(PRICE_PLAN_ID4 AS STRING))))),'UNKNOWN_COMMERCIAL_OFFER')
, nvl(NVL(PC1.PROFILE_NAME,CAST(A.PROD_SPEC_ID AS STRING)),'UNKNOWN_COMMERCIAL_PROFILE')
, nvl(A.ORIGINAL_FILE_NAME,'UNKNOWN_ORIGINAL_FILE_NAME')
, WINDOW