SELECT
 (CASE PREPAY_FLAG
        WHEN 1 THEN 'PREPAID'
        WHEN 2 THEN 'POSTPAID'
        WHEN 3 THEN 'HYBRID'
        ELSE CAST(PREPAY_FLAG AS STRING)
 END ) CONTRACT_TYPE,
 NVL(PROD_SPEC.PROD_SPEC_NAME,  CAST(ITSUBSC.PROD_SPEC_CODE AS STRING)) COMMERCIAL_OFFER,
 NVL(CHANSUBSC.CHANNEL_NAME, CAST(ITSUBSC.CHANNEL_ID AS STRING)) SUBSCRIPTION_CHANNEL,
 COUNT(SUBSTRING(ACC_NBR, -9)) SUBS_TOTAL_COUNT,
 SUM(CAST(EVENT_COST AS DOUBLE)) / 100 SUBS_AMOUNT,
 approx_count_distinct( SUBSTRING(ACC_NBR, -9)) MSISDN_COUNT,
 SUM(CASE WHEN NVL(EVENT_COST, 0) > 0 THEN 1 ELSE 0 END) SUBS_EVENT_RATED_COUNT,
 SERVSUBSC.SUBSCRIPTION_SERVICE_NAME SUBSCRIPTION_SERVICE,
 NVL(PRICE_PLAN.PRICE_PLAN_NAME,CAST(ITSUBSC.PRICE_PLAN_CODE AS STRING)) SUBSCRIPTION_SERVICE_DETAILS,
 WINDOW.START START_DATE,
 WINDOW.END END_DATE,
 ORIGINAL_FILE_NAME
 FROM 
(SELECT 
    ACC_NBR,
    CHANNEL_ID,
    SUBS_EVENT_ID,
    CREATEDDATE,
    EVENT_COST,
    PROD_SPEC_CODE,
    PRICE_PLAN_CODE,
    PREPAY_FLAG, 
    WINDOW,
    ORIGINAL_FILE_NAME
 FROM in_zte_subscription_stream
 ) ITSUBSC
LEFT JOIN DIM.DT_SUBSCRIPTION_SERVICE SERVSUBSC ON NVL(ITSUBSC.SUBS_EVENT_ID, 1000000) = SERVSUBSC.SUBSCRIPTION_SERVICE_ID
LEFT JOIN DIM.DT_SUBSCRIPTION_CHANNEL CHANSUBSC ON NVL(ITSUBSC.CHANNEL_ID, 1000000) = CHANSUBSC.CHANNEL_ID
LEFT JOIN (SELECT NVL(PRICE_PLAN_CODE, 'UNKNOWN')PRICE_PLAN_CODE , MIN( PRICE_PLAN_NAME) PRICE_PLAN_NAME
   FROM CDR.STREAM_IT_ZTE_PRICE_PLAN_EXTRACT   
   GROUP BY NVL(PRICE_PLAN_CODE, 'UNKNOWN')) PRICE_PLAN
ON NVL(ITSUBSC.PRICE_PLAN_CODE, '1000000') = PRICE_PLAN.PRICE_PLAN_CODE
LEFT JOIN (SELECT STD_CODE, MIN(PROD_SPEC_NAME) PROD_SPEC_NAME
   FROM CDR.STREAM_IT_ZTE_PROD_SPEC_EXTRACT   
   GROUP BY STD_CODE) PROD_SPEC
ON NVL(ITSUBSC.PROD_SPEC_CODE, '1000000') =  PROD_SPEC.STD_CODE
GROUP BY 
      (CASE PREPAY_FLAG
        WHEN 1 THEN 'PREPAID'
        WHEN 2 THEN 'POSTPAID'
        WHEN 3 THEN 'HYBRID'
        ELSE CAST(PREPAY_FLAG AS STRING)
      END )
    , NVL(PROD_SPEC.PROD_SPEC_NAME,  CAST(ITSUBSC.PROD_SPEC_CODE AS STRING))
    , NVL(CHANSUBSC.CHANNEL_NAME, CAST(ITSUBSC.CHANNEL_ID AS STRING))
    , SERVSUBSC.SUBSCRIPTION_SERVICE_NAME
    , NVL(PRICE_PLAN.PRICE_PLAN_NAME,CAST(ITSUBSC.PRICE_PLAN_CODE AS STRING))
    , WINDOW 
    ,ORIGINAL_FILE_NAME

