CREATE TABLE CDR.SPARK_IT_GOOGLE_RCS_CLIENT (
    USERS VARCHAR(200),
    AGENT VARCHAR(200),
    200_TODAY VARCHAR(200),
    200_THIS_MONTH VARCHAR(200),
    503_TODAY VARCHAR(200),
    503_THIS_MONTH VARCHAR(200),
    INSERT_DATE DATE,
    ORIGINAL_FILE_NAME VARCHAR(200),
    ORIGINAL_FILE_SIZE INT,
    ORIGINAL_FILE_LINE_COUNT INT
)
PARTITIONED BY (FILE_DATE DATE)
STORED AS PARQUET TBLPROPERTIES ('PARQUET.COMPRESS'='SNAPPY')
