INSERT INTO CDR.SPARK_IT_GOOGLE_RCS_ACTIVITY PARTITION (FILE_DATE)
SELECT
    CREATION_DATE,
    FROM_USER,
    TO_USER,
    FROM_NETWORK,
    TO_NETWORK,
    TYPE,
    DURATION,
    BYTES_SENT,
    BYTES_RECEIVED,
    CALL_ID,
    CONTRIBUTION_ID,
    SRC_IP,
    SIP_CODE,
    SIP_REASON,
    USER_AGENT,
    MESSAGES_SENT,
    MESSAGES_RECEIVED,
    FROM_TENANT,
    TO_TENANT,
    ORIGINAL_FILE_NAME,
    ORIGINAL_FILE_SIZE,
    ORIGINAL_FILE_LINE_COUNT,
    CURRENT_TIMESTAMP() INSERT_DATE,
    TO_DATE(CREATION_DATE) START_DATE,
    TO_DATE(SUBSTRING (ORIGINAL_FILE_NAME, 10, 10)) FILE_DATE
FROM CDR.TT_GOOGLE_RCS_ACTIVITY  C
LEFT JOIN 
(
    SELECT DISTINCT  ORIGINAL_FILE_NAME FILE_NAME
    FROM CDR.SPARK_IT_GOOGLE_RCS_ACTIVITY 
    WHERE FILE_DATE BETWEEN DATE_SUB(CURRENT_DATE,${hivevar:date_offset}) AND CURRENT_DATE 
)T 
ON T.FILE_NAME=C.ORIGINAL_FILE_NAME
WHERE T.FILE_NAME IS NULL

