

CREATE EXTERNAL TABLE IF NOT EXISTS CDR.TT_RIGHTQ_REF_AGENTS

(

ORIGINAL_FILE_NAME VARCHAR(200),
ORIGINAL_FILE_SIZE INT,
ORIGINAL_FILE_LINE_COUNT INT,
Agence VARCHAR(200),
Nom_agent VARCHAR(200),
Email VARCHAR(200),
Statut VARCHAR(20),
Mobile VARCHAR(50),
Profile VARCHAR(20),
Date_creation TIMESTAMP,
Date_derniere_modif TIMESTAMP

)
COMMENT 'EXP_DIM_CTL_AUDIT_LOG external tables-TT'
ROW FORMAT DELIMITED FIELDS TERMINATED BY ';'
LOCATION '/PROD/RAW/RIGHTQ/REF_AGENTS'
TBLPROPERTIES ('serialization.null.format'='')