/*******  
-- Logging des donnees calculees pour cette date 
*******/
         
--INSERT INTO DT_DATES_SCRIPT_PROCESSED
--VALUES (TO_DATE(s_slice_value, 'yyyymmdd'), 'BASE_IDENTIFICATION', CURRENT_TIMESTAMP);


--UPDATE DATALAB.DT_BASE_IDENTIFICATION
--SET DATE_TABLE_MIS_A_JOUR = CURRENT_TIMESTAMP;


-- 3. Sauvegarde des identifications dont les MSISDN sont Incorrectes dans la table TT_BAD_IDENTIFICATION_MSISDN
MERGE INTO TT.TT_BAD_IDENTIFICATION_MSISDN a
USING
(
    SELECT MSISDN, NOM, PRENOM, NEE_LE, NEE_A, PROFESSION, QUARTIER_RESIDENCE,
        VILLE_VILLAGE, CNI, DATE_IDENTIFICATION, TYPE_DOCUMENT, FICHIER_CHARGEMENT, EST_SNAPPE, IDENTIFICATEUR
        , GENRE, CIVILITE, TYPE_PIECE_IDENTIFICATION, PROFESSION_IDENTIFICATEUR
    FROM DATALAB.TT_IDENTIFICATION_MSISDN
    WHERE FN_GET_OPERATOR_CODE(MSISDN)  NOT IN ('OCM', 'SET') OR CASE WHEN CAST(MSISDN AS INT) IS NULL THEN 'N' ELSE 'Y' END= 'N'
) b
ON (a.MSISDN = b.MSISDN)
WHEN MATCHED AND a.DATE_IDENTIFICATION < b.DATE_IDENTIFICATION THEN
    UPDATE
    SET CNI = b.CNI,
        NOM = b.NOM,
        PRENOM = b.PRENOM,
        NEE_LE = b.NEE_LE,
        NEE_A = b.NEE_A,
        PROFESSION = b.PROFESSION,
        QUARTIER_RESIDENCE = b.QUARTIER_RESIDENCE,
        VILLE_VILLAGE = b.VILLE_VILLAGE,
        DATE_IDENTIFICATION = b.DATE_IDENTIFICATION,
        TYPE_DOCUMENT = b.TYPE_DOCUMENT,
        FICHIER_CHARGEMENT = b.FICHIER_CHARGEMENT,
        EST_SNAPPE = b.EST_SNAPPE,
        IDENTIFICATEUR = b.IDENTIFICATEUR,
        DATE_MISE_A_JOUR = CURRENT_TIMESTAMP,
        DATE_TABLE_MIS_A_JOUR = CURRENT_TIMESTAMP,
        GENRE = b.GENRE,
        CIVILITE = b.CIVILITE,
        TYPE_PIECE_IDENTIFICATION = b.TYPE_PIECE_IDENTIFICATION,
        PROFESSION_IDENTIFICATEUR = b.PROFESSION_IDENTIFICATEUR
WHEN NOT MATCHED THEN
    INSERT
    VALUES (b.MSISDN, b.NOM, b.PRENOM, b.NEE_LE, b.NEE_A, b.PROFESSION, b.QUARTIER_RESIDENCE, b.VILLE_VILLAGE, b.CNI,
                 b.DATE_IDENTIFICATION, b.TYPE_DOCUMENT, b.FICHIER_CHARGEMENT, CURRENT_TIMESTAMP, b.EST_SNAPPE, b.IDENTIFICATEUR, CURRENT_TIMESTAMP , CURRENT_TIMESTAMP
                 , b.GENRE, b.CIVILITE, b.TYPE_PIECE_IDENTIFICATION, b.PROFESSION_IDENTIFICATEUR);
                 