-- Donnees base SNAP ID
MERGE INTO TT.TT_IDENTIFICATION_MSISDN a
USING
(
    SELECT MSISDN, NOM, PRENOM, NEE_LE,NEE_A, PROFESSION, QUARTIER_RESIDENCE, VILLE_VILLAGE,
         CNI, DATE_IDENTIFICATION, TYPE_DOCUMENT, FICHIER_CHARGEMENT, DATE_INSERTION, EST_SNAPPE,
         IDENTIFICATEUR, GENRE, CIVILITE, TYPE_PIECE_IDENTIFICATION, PROFESSION_IDENTIFICATEUR
    FROM
    (
        SELECT
            MSISDN,
            UPPER(NOM) AS NOM,
            UPPER(PRENOM) AS PRENOM,
            NVL(FROM_UNIXTIME(UNIX_TIMESTAMP(DATENAISSANCE,'yyyyMMdd HH:mm:ss')),FROM_UNIXTIME(UNIX_TIMESTAMP(DATENAISSANCE,'dd/MM/yy'))) NEE_LE,
            UPPER(LIEUNAISSANCE) AS NEE_A,
            NULL AS PROFESSION,
            UPPER(QUARTIER) AS QUARTIER_RESIDENCE,
            UPPER(VILLE) AS VILLE_VILLAGE,
            IDPIECEIDENTIFICATION AS CNI,
            LASTMOD AS DATE_IDENTIFICATION,
            NULL AS TYPE_DOCUMENT,
            UPPER(SOURCE) AS FICHIER_CHARGEMENT,
            CURRENT_TIMESTAMP AS DATE_INSERTION,
            'NON' AS EST_SNAPPE,
            IF(REGEXP_REPLACE(SELLER_MSISDN, "^237+(?!$)","")='237',NULL,REGEXP_REPLACE(SELLER_MSISDN, "^237+(?!$)","")) AS IDENTIFICATEUR,
            UPPER(GENRE) AS GENRE,
            UPPER(CIVILITE) AS CIVILITE,
            TYPEPIECEIDENTIFICATION AS TYPE_PIECE_IDENTIFICATION,
            UPPER(PROFESSION) AS PROFESSION_IDENTIFICATEUR,
            ROW_NUMBER() OVER (PARTITION BY MSISDN ORDER BY NVL(FROM_UNIXTIME(UNIX_TIMESTAMP(DATEDERNIEREMODIF,'yyyyMMdd HH:mm:ss')),
                FROM_UNIXTIME(UNIX_TIMESTAMP(DATEDERNIEREMODIF,'dd/MM/yy'))) DESC) AS RG
        FROM CDR.IT_CLIENT_SNAPID_DIRECTORY
        WHERE ORIGINAL_FILE_DATE >= DATE_SUB('###SLICE_VALUE###',30) and ORIGINAL_FILE_DATE<='###SLICE_VALUE###' -- pour récuperer les plus d'identifications récentes
    )T
    WHERE RG = 1 -- dedoublonnage    
) b
ON (a.MSISDN = b.MSISDN)
WHEN MATCHED THEN
    UPDATE SET
        NOM = b.NOM,
        PRENOM = b.PRENOM,
        NEE_LE = b.NEE_LE,
        NEE_A = b.NEE_A,
        QUARTIER_RESIDENCE = b.QUARTIER_RESIDENCE,
        VILLE_VILLAGE = b.VILLE_VILLAGE,
        CNI = b.CNI,
        DATE_IDENTIFICATION = b.DATE_IDENTIFICATION,
        FICHIER_CHARGEMENT = b.FICHIER_CHARGEMENT,
        IDENTIFICATEUR = b.IDENTIFICATEUR,
        GENRE = b.GENRE,
        CIVILITE = b.CIVILITE,
        TYPE_PIECE_IDENTIFICATION = b.TYPE_PIECE_IDENTIFICATION,
        PROFESSION_IDENTIFICATEUR = b.PROFESSION_IDENTIFICATEUR
WHEN NOT MATCHED THEN
INSERT   VALUES (b.MSISDN, b.NOM, b.PRENOM, b.NEE_LE, b.NEE_A, b.PROFESSION, b.QUARTIER_RESIDENCE, b.VILLE_VILLAGE, b.CNI,
               b.DATE_IDENTIFICATION, b.TYPE_DOCUMENT, b.FICHIER_CHARGEMENT, CURRENT_TIMESTAMP , b.EST_SNAPPE,
               b.IDENTIFICATEUR, b.GENRE, b.CIVILITE, b.TYPE_PIECE_IDENTIFICATION, b.PROFESSION_IDENTIFICATEUR
              )