SELECT IF(DATE_IS_PROCESSING=0  AND SNAP_ID>0 AND NOMAD>0,'OK','NOK') STATUS
FROM
(SELECT COUNT(*) DATE_IS_PROCESSING  FROM mon.backup_dt_base_identification WHERE PROCESSING_DATE = '###SLICE_VALUE###') a,
--(SELECT COUNT(*) IT_PREPAID_CLIENT  FROM cdr.it_prepaid_client_directory WHERE ORIGINAL_FILE_DATE = '###SLICE_VALUE###') b,
(SELECT COUNT(*) SNAP_ID FROM cdr.IT_CLIENT_SNAPID_DIRECTORY WHERE ORIGINAL_FILE_DATE = DATE_SUB('###SLICE_VALUE###',1)) c,
(SELECT COUNT(*) NOMAD FROM cdr.IT_NOMAD_CLIENT_DIRECTORY WHERE ORIGINAL_FILE_DATE = '###SLICE_VALUE###') d