SELECT IF(T_1.FT_EXIST = 0 and T_2.CONTRACT_SNAPSHOT_EXIST>0,"OK","NOK") EXTRACT_EXIST
FROM
(SELECT COUNT(*) FT_EXIST FROM MON.FT_OTARIE_DATA_TRAFFIC_DAY WHERE TRANSACTION_DATE='###SLICE_VALUE###') T_1,
(SELECT COUNT(*) CONTRACT_SNAPSHOT_EXIST FROM MON.FT_CONTRACT_SNAPSHOT WHERE EVENT_DATE = '###SLICE_VALUE###') T_2
