SELECT IF(FT_EXISTS = 0 and COMPLETUDE=30 ,"OK","NOK") STATUT
FROM
    (SELECT COUNT(*) FT_EXISTS FROM MON.SPARK_FT_OTARIE_USERS_TRAFFIC WHERE TRANSACTION_DATE='###SLICE_VALUE###') T_1,
    (SELECT COUNT(DISTINCT TRANSACTION_DATE) COMPLETUDE FROM MON.SPARK_FT_OTARIE_DATA_TRAFFIC_DAY WHERE TRANSACTION_DATE BETWEEN DATE_SUB('###SLICE_VALUE###',29) AND '###SLICE_VALUE###' ) T_2