SELECT IF(T_1.tt_analyse_decon_refill1 = 0
 AND T_2.TT_GROUP_SUBS_ACCT_DISCONNECT>0
AND T_3.FT_CLIENT_LAST_SITE_LOCATION > 0
AND T_4.FT_A_REFILL_RECEIVER>= TRUNC(abs(cast(months_between(add_months('###SLICE_VALUE###',-5),'###SLICE_VALUE###') as INT)))
AND T_5.FT_IMEI_TRAFFIC_MONTHLY>0
AND T_6.FT_IMEI_TRAFFIC_MONTHLY_prev3>0
, "OK", "NOK") FT_EXIST
FROM
(SELECT COUNT(*) tt_analyse_decon_refill1 FROM MON.SPARK_tt_analyse_decon_refill1 WHERE ACCOUNT_ACTIVITY_EVENT_DATE = '###SLICE_VALUE###' LIMIT 10) T_1,
(SELECT COUNT(*)  TT_GROUP_SUBS_ACCT_DISCONNECT FROM MON.SPARK_TT_GROUP_SUBS_ACCT_DISCONNECT WHERE EVENT_DATE =DATE_SUB(last_day('###SLICE_VALUE###'),-1) LIMIT 10) T_2,
(SELECT COUNT(*) FT_CLIENT_LAST_SITE_LOCATION FROM mon.SPARK_FT_CLIENT_LAST_SITE_LOCATION WHERE EVENT_MONTH = SUBSTR('###SLICE_VALUE###',1,7) LIMIT 10) T_3,
(SELECT COUNT(distinct REFILL_MONTH) FT_A_REFILL_RECEIVER FROM AGG.SPARK_FT_A_REFILL_RECEIVER WHERE REFILL_MONTH BETWEEN SUBSTR(add_months('###SLICE_VALUE###',-5),1,7)  AND  SUBSTR('###SLICE_VALUE###',1,7) LIMIT 10) T_4,
(SELECT COUNT(*) FT_IMEI_TRAFFIC_MONTHLY FROM MON.SPARK_FT_IMEI_TRAFFIC_MONTHLY WHERE smonth = SUBSTR('###SLICE_VALUE###',1,7) LIMIT 10) T_5,
(SELECT COUNT(*) FT_IMEI_TRAFFIC_MONTHLY_prev3 FROM MON.SPARK_FT_IMEI_TRAFFIC_MONTHLY WHERE SUBSTR(add_months('###SLICE_VALUE###',-3),1,7) LIMIT 10) T_6