CREATE TABLE MON.SPARK_FT_FAKE_ACTIVATION_STATUS(
   	EVENT_MONTH     VARCHAR(6),
	MSISDN          VARCHAR(25),
	RECEIVER_MSISDN VARCHAR(25),
	EST_FAKE_ACTIVATION INT,
	INSERT_DATE TIMESTAMP
   ) COMMENT 'SPARK FT_FAKE_ACTIVATION_STATUS'
 PARTITIONED BY (EVENT_DATE DATE)
 STORED AS PARQUET
 TBLPROPERTIES ("parquet.compress"="SNAPPY")
