SELECT IF(T_1.FT_COUNT = 0 AND T_2.FT_ACTIVATION_MONTH > 1 AND T_3.FT_C2S and T_4.FT_SC > 1 ,"OK","NOK") FT_EXIST
FROM
    (SELECT COUNT(*) FT_COUNT FROM MON.SPARK_FT_FAKE_ACTIVATION_STATUS WHERE EVENT_DATE= '###SLICE_VALUE###') T_1,
    (SELECT COUNT(*) FT_ACTIVATION_MONTH FROM MON.SPARK_FT_ACTIVATION_MONTH1 WHERE ACTIVATION_DATE=date_sub('###SLICE_VALUE###', 30)) T_2,
    (SELECT COUNT(*) FT_C2S FROM MON.SPARK_FT_REFILL WHERE REFILL_DATE BETWEEN date_sub('###SLICE_VALUE###', 30) AND '###SLICE_VALUE###' AND REFILL_MEAN = "C2S")T_3,
    (SELECT COUNT(*) FT_SC FROM MON.SPARK_FT_REFILL WHERE REFILL_DATE BETWEEN date_sub('###SLICE_VALUE###', 30) AND '###SLICE_VALUE###' AND REFILL_MEAN = "SCRATCH")T_4