
CREATE TABLE MON.SPARK_FT_ROAMING_RETAIL_OUT (
    MSISDN       VARCHAR (20),     
    DIRECTION    VARCHAR (255),
    TARRIF_PLAN   VARCHAR (255),
    TYPE_ABONNE       VARCHAR(20),
    SEGMENT_CLIENT VARCHAR(10), 
    PAYS_VISITE    VARCHAR (255),
    TAP_CODE   VARCHAR (255),
    OPERATEUR_VISITE VARCHAR(255), 
    FORFAIT_ROAMING VARCHAR(255), 
    SUBS_CHANNEL VARCHAR(255), 
    SERVICE_TYPE VARCHAR(255), 
    SERVICE_DETAIL VARCHAR(255), 
    DESTINATION VARCHAR(255), 
    NOMBRE_ACTE INT,
    VOLUME_MINUTE DECIMAL(20,5),
    VOLUME_DATA DECIMAL(20,5),
    REVENU_MAIN DECIMAL(20,5)
)
COMMENT 'SPARK_FT_ROAMING_RETAIL_OUT - FT'
PARTITIONED BY (EVENT_DATE DATE)
STORED AS PARQUET TBLPROPERTIES ('PARQUET.COMPRESS'='SNAPPY');


---Staging table in data lake
CREATE TABLE TMP.SQ_FT_ROAMING_RETAIL_OUT (
    MSISDN       VARCHAR (20),     
    DIRECTION    VARCHAR (255),
    TARRIF_PLAN   VARCHAR (255),
    TYPE_ABONNE       VARCHAR(20),
    SEGMENT_CLIENT VARCHAR(10), 
    PAYS_VISITE    VARCHAR (255),
    TAP_CODE   VARCHAR (255),
    OPERATEUR_VISITE VARCHAR(255), 
    FORFAIT_ROAMING VARCHAR(255), 
    SUBS_CHANNEL VARCHAR(255), 
    SERVICE_TYPE VARCHAR(255), 
    SERVICE_DETAIL VARCHAR(255), 
    DESTINATION VARCHAR(255), 
    NOMBRE_ACTE INT,
    VOLUME_MINUTE DECIMAL(20,5),
    VOLUME_DATA DECIMAL(20,5),
    REVENU_MAIN DECIMAL(20,5),
    EVENT_DATE DATE
) ;

---Staging table in DWH
CREATE TABLE MON.SQ_FT_ROAMING_RETAIL_OUT (
    MSISDN       VARCHAR (20 BYTE),     
    DIRECTION    VARCHAR (255 BYTE),
    TARRIF_PLAN   VARCHAR (255 BYTE),
    TYPE_ABONNE       VARCHAR(20 BYTE),
    SEGMENT_CLIENT VARCHAR(10 BYTE), 
    PAYS_VISITE    VARCHAR (255 BYTE),
    TAP_CODE   VARCHAR (255 BYTE),
    OPERATEUR_VISITE VARCHAR(255 BYTE), 
    FORFAIT_ROAMING VARCHAR(255 BYTE), 
    SUBS_CHANNEL VARCHAR(255 BYTE), 
    SERVICE_TYPE VARCHAR(255 BYTE), 
    SERVICE_DETAIL VARCHAR(255 BYTE), 
    DESTINATION VARCHAR(255 BYTE), 
    NOMBRE_ACTE INT,
    VOLUME_MINUTE DECIMAL(20,5),
    VOLUME_DATA DECIMAL(20,5),
    REVENU_MAIN DECIMAL(20,5),
    EVENT_DATE DATE
);


--final table in DWN
CREATE TABLE MON.FT_ROAMING_RETAIL_OUT (
    MSISDN       VARCHAR (20 BYTE),     
    DIRECTION    VARCHAR (255 BYTE),
    TARRIF_PLAN   VARCHAR (255 BYTE),
    TYPE_ABONNE       VARCHAR(20 BYTE),
    SEGMENT_CLIENT VARCHAR(10 BYTE), 
    PAYS_VISITE    VARCHAR (255 BYTE),
    TAP_CODE   VARCHAR (255 BYTE),
    OPERATEUR_VISITE VARCHAR(255 BYTE), 
    FORFAIT_ROAMING VARCHAR(255 BYTE), 
    SUBS_CHANNEL VARCHAR(255 BYTE), 
    SERVICE_TYPE VARCHAR(255 BYTE), 
    SERVICE_DETAIL VARCHAR(255 BYTE), 
    DESTINATION VARCHAR(255 BYTE), 
    NOMBRE_ACTE INT,
    VOLUME_MINUTE DECIMAL(20,5),
    VOLUME_DATA DECIMAL(20,5),
    REVENU_MAIN DECIMAL(20,5),
    EVENT_DATE DATE
);


DECLARE
  SAMPLE_TABLE VARCHAR2(200); MIN_DATE_PARTITION VARCHAR2(200); MAX_DATE_PARTITION VARCHAR2(200);  KEY_COLUMN_PART_NAME VARCHAR2(200);
  KEY_COLUMN_PART_TYPE VARCHAR2(200);   PART_OWNER VARCHAR2(200);  PART_TABLE_NAME VARCHAR2(200);  PART_PARTITION_NAME VARCHAR2(200);
  PART_TYPE_PERIODE VARCHAR2(200);  PART_RETENTION NUMBER;  PART_TBS_CIBLE VARCHAR2(200);  PART_GARDER_01_DU_MOIS VARCHAR2(200);
PART_PCT_FREE NUMBER;   PART_COMPRESSION VARCHAR2(200);  PART_ROTATION_ACTIVE VARCHAR2(200);  PART_FORMAT VARCHAR2(200);
BEGIN 
  SAMPLE_TABLE := 'MON.TMP_FT_ROAMING_RETAIL_OUT';
  MIN_DATE_PARTITION := '20210101';
  MAX_DATE_PARTITION := '20220101';
  KEY_COLUMN_PART_NAME := 'EVENT_DATE';
  KEY_COLUMN_PART_TYPE := 'JOUR';
  PART_OWNER := 'MON';
  PART_TABLE_NAME := 'FT_ROAMING_RETAIL_OUT';
  PART_PARTITION_NAME := 'ROAM_RETAIL_OUT_';
  PART_TYPE_PERIODE := 'JOUR';
  PART_RETENTION := 1000;
  PART_TBS_CIBLE :=  'TAB_MIG_64K';
  PART_GARDER_01_DU_MOIS := 'NON';
  PART_PCT_FREE := 0;
  PART_COMPRESSION := 'COMPRESS';
  PART_ROTATION_ACTIVE := 'OUI';
  PART_FORMAT := 'yyyymmdd';
  MON.CREATE_PARTITIONED_TABLE ( SAMPLE_TABLE, MIN_DATE_PARTITION, MAX_DATE_PARTITION, KEY_COLUMN_PART_NAME, KEY_COLUMN_PART_TYPE, PART_OWNER, PART_TABLE_NAME, PART_PARTITION_NAME, PART_TYPE_PERIODE, PART_RETENTION, PART_TBS_CIBLE, PART_GARDER_01_DU_MOIS, PART_PCT_FREE, PART_COMPRESSION, PART_ROTATION_ACTIVE, PART_FORMAT );
  COMMIT; 
END;






