SELECT IF(T_1.FT_EXIST = 0 and T_2.FT_REFILL_EXIST>0 ,"OK","NOK") EXTRACT_EXIST
FROM
(SELECT COUNT(*) FT_EXIST FROM AGG.SPARK_REVENUE_SUMMARY_DAILY WHERE EVENT_DATE='###SLICE_VALUE###' AND source_data='FT_REFILL') T_1,
(SELECT COUNT(*) FT_REFILL_EXIST FROM MON.SPARK_FT_REFILL WHERE REFILL_DATE = '###SLICE_VALUE###') T_2

