SELECT IF(T_1.FT_EXIST = 0 and T_2.IT_OM_TRANSACTIONS_EXIST>0  AND T_3.FT_CONTRACT_SNAPSHOT_EXIST>0,"OK","NOK") EXTRACT_EXIST
FROM
(SELECT COUNT(*) FT_EXIST FROM AGG.SPARK_REVENUE_SUMMARY_DAILY WHERE EVENT_DATE='###SLICE_VALUE###'  AND source_data='OM_TRANSACTIONS') T_1,
(SELECT COUNT(*) IT_OM_TRANSACTIONS_EXIST FROM CDR.SPARK_IT_OMNY_TRANSACTIONS WHERE file_date = '###SLICE_VALUE###') T_2,
(SELECT COUNT(*) FT_CONTRACT_SNAPSHOT_EXIST FROM MON.SPARK_FT_CONTRACT_SNAPSHOT WHERE event_date = '###SLICE_VALUE###') T_3

