SELECT IF(T_1.FT_EXIST = 0 and T_2.CONTRACT_SNAPSHOT_EXIST>0 AND T_3.IT_ZTE_ADJUSTMENT_EXIST>0 ,"OK","NOK") EXTRACT_EXIST
FROM
(SELECT COUNT(*) FT_EXIST FROM AGG.SPARK_REVENUE_SUMMARY_DAILY WHERE EVENT_DATE='###SLICE_VALUE###' AND   source_data='ADJUSTMENT') T_1,
(SELECT COUNT(*) CONTRACT_SNAPSHOT_EXIST FROM MON.SPARK_FT_CONTRACT_SNAPSHOT WHERE EVENT_DATE = '###SLICE_VALUE###') T_2,
(SELECT COUNT(*) IT_ZTE_ADJUSTMENT_EXIST FROM CDR.SPARK_IT_ZTE_ADJUSTMENT WHERE CREATE_DATE = '###SLICE_VALUE###') T_3
