CREATE TABLE MON.SPARK_FT_ACTIVATION_MONTH 
   (
    ACTIVATION_DATE DATE,
    MSISDN VARCHAR(25), 
    FIRST_DAY_REFILL DATE, 
    REFILL_COUNT BIGINT, 
    REFILL_AMOUNT BIGINT, 
    NEXT_MONTH_FIRST_DAY_REFIL_AMT BIGINT, 
    INSERT_DATE DATE, 
    REFRESH_DATE DATE, 
    FIRST_DAY_REFILL_AMOUNT BIGINT
   ) PARTITIONED BY(EVENT_MONTH VARCHAR(10))
     STORED AS PARQUET TBLPROPERTIES ('parquet.compress=SNAPPY')