add jar hdfs:///PROD/UDF/hive-udf-1.0.1.jar;
CREATE TEMPORARY FUNCTION FN_GET_NNP_MSISDN_SIMPLE_DESTN as 'cm.orange.bigdata.udf.GetNnpMsisdnSimpleDestn';
CREATE TEMPORARY FUNCTION FN_GET_OPERATOR_CODE as 'cm.orange.bigdata.udf.GetOperatorCode';
create table TT_SPHERE_TRAFFIC_MONTH_202003
STORED AS PARQUET TBLPROPERTIES ('PARQUET.COMPRESS'='SNAPPY')
as
SELECT
SERVED_MSISDN,
PARTNER_GT AS OTHER_PARTY
, SUM (CASE WHEN  TRANSACTION_DIRECTION = 'Sortant' AND SUBSTR (TRANSACTION_TYPE, 1, 3) <> 'SMS' THEN  TRANSACTION_DURATION   ELSE  0    END ) DUREE_SORTANT
, SUM (CASE WHEN  TRANSACTION_DIRECTION = 'Sortant' AND SUBSTR (TRANSACTION_TYPE, 1, 3) <> 'SMS' THEN  1   ELSE  0    END ) NBRE_TEL_SORTANT
, SUM (CASE WHEN  TRANSACTION_DIRECTION = 'Entrant' AND SUBSTR (TRANSACTION_TYPE, 1, 3) <> 'SMS' THEN  TRANSACTION_DURATION   ELSE  0    END ) DUREE_ENTRANT
, SUM (CASE WHEN  TRANSACTION_DIRECTION = 'Entrant' AND SUBSTR (TRANSACTION_TYPE, 1, 3) <> 'SMS' THEN  1   ELSE  0    END ) NBRE_TEL_ENTRANT
, SUM (CASE WHEN  TRANSACTION_DIRECTION = 'Sortant' AND SUBSTR (TRANSACTION_TYPE, 1, 3) = 'SMS' THEN  1   ELSE  0    END ) NBRE_SMS_SORTANT
, SUM (CASE WHEN  TRANSACTION_DIRECTION = 'Entrant' AND SUBSTR (TRANSACTION_TYPE, 1, 3) = 'SMS' THEN  1   ELSE  0    END ) NBRE_SMS_ENTRANT
, max (CASE WHEN  TRANSACTION_DIRECTION = 'Entrant' AND SUBSTR (TRANSACTION_TYPE, 1, 3) <> 'SMS'
        and TRANSACTION_DURATION > 0  THEN  transaction_date  ELSE null  END ) AS DERNIER_JOUR_TEL_ENTRANT
, max (CASE WHEN  TRANSACTION_DIRECTION = 'Sortant' AND SUBSTR (TRANSACTION_TYPE, 1, 3) <> 'SMS'
        and TRANSACTION_DURATION > 0  THEN  transaction_date   ELSE  null   END ) AS DERNIER_JOUR_TEL_SORTANT
, max (CASE WHEN  TRANSACTION_DIRECTION = 'Entrant' AND SUBSTR (TRANSACTION_TYPE, 1, 3) = 'SMS'
      THEN  transaction_date   ELSE  null    END ) AS DERNIER_JOUR_SMS_ENTRANT
, max (CASE WHEN  TRANSACTION_DIRECTION = 'Sortant' AND SUBSTR (TRANSACTION_TYPE, 1, 3) = 'SMS'
      THEN  transaction_date   ELSE  null    END ) AS DERNIER_JOUR_SMS_SORTANT
, min (CASE WHEN  TRANSACTION_DIRECTION = 'Entrant' AND SUBSTR (TRANSACTION_TYPE, 1, 3) <> 'SMS'
     and TRANSACTION_DURATION > 0 THEN  transaction_date   ELSE  null END ) AS PREMIER_JOUR_TEL_ENTRANT
, min (CASE WHEN  TRANSACTION_DIRECTION = 'Sortant' AND SUBSTR (TRANSACTION_TYPE, 1, 3) <> 'SMS'
     and TRANSACTION_DURATION > 0 THEN  transaction_date   ELSE  null END ) AS PREMIER_JOUR_TEL_SORTANT
, min (CASE WHEN  TRANSACTION_DIRECTION = 'Entrant' AND SUBSTR (TRANSACTION_TYPE, 1, 3) = 'SMS'
     THEN  transaction_date   ELSE  null    END ) AS PREMIER_JOUR_SMS_ENTRANT
, min (CASE WHEN  TRANSACTION_DIRECTION = 'Sortant' AND SUBSTR (TRANSACTION_TYPE, 1, 3) = 'SMS'
     THEN  transaction_date   ELSE  null   END ) AS PREMIER_JOUR_SMS_SORTANT
,FN_GET_OPERATOR_CODE(PARTNER_GT) AS OPERATOR_DEST,
current_timestamp() as insert_date,
substr(cast(transaction_date as string),1,7) as event_month
FROM
    Mon.spark_ft_msc_transaction
WHERE
    TRANSACTION_DATE between to_date('###SLICE_VALUE###' || '-01') and  last_day(to_date('###SLICE_VALUE###' || '-01'))
    AND fn_get_nnp_msisdn_simple_destn(PARTNER_GT) IN ('OCM', 'VIETTEL', 'MTN', 'CAMTEL', 'SET', 'INTERNATIONAL')
    AND fn_get_nnp_msisdn_simple_destn(SERVED_MSISDN) IN ('OCM')
    AND SERVED_MSISDN NOT IN ('699900999', '699900909', '699900808', '699900984', '699900762', '699900991')
GROUP BY substr(cast(transaction_date as string),1,7),SERVED_MSISDN, PARTNER_GT

