set hive.vectorized.execution.enabled=true;
set hive.vectorized.execution.reduce.enabled=true;
set hive.exec.parallel=true;
SET hive.exec.reducers.max=128;

INSERT INTO MON.FT_MSC_TRANSACTION PARTITION(TRANSACTION_DATE)
SELECT
TRANSACTION_TIME,
TRANSACTION_DIRECTION,
TRANSACTION_TYPE,
SERVED_MSISDN,
SERVED_IMSI,
SERVED_IMEI,
SERVED_PARTY_LOCATION,
(CASE WHEN subs_type <> 'ROAM'  AND 	( LENGTH(Other_Party) <= 6 OR Other_Party IN ('99900500', '99900999'))  THEN 'PREP/POST'
      ELSE subs_type
 END ) SUBSCRIBER_TYPE,
OTHER_PARTY,
(CASE
  WHEN LENGTH (OTHER_PARTY) = 13 AND SUBSTR(OTHER_PARTY,1,3)= '160' THEN 1
  WHEN LENGTH (OTHER_PARTY) > 9  THEN 0 -- INTERNATIONAL
  ELSE 1 --OTHER
END)  OTHER_PARTY_IS_NATIONAL,
PARTNER_GT,
(CASE
  WHEN LENGTH (PARTNER_GT) = 13 AND SUBSTR(PARTNER_GT,1,3)= '160' THEN 1
  WHEN LENGTH (PARTNER_GT) > 9  THEN 0 -- INTERNATIONAL
  ELSE 1 --OTHER
END) Partner_GT_Is_National	,
TRANSACTION_DURATION,
TRANSACTION_VOLUME,
MEASUREMENT_UNIT,
TRANSACTION_TERM_CODE,
TRUNCK_IN,
TRUNCK_OUT,
MSC_ADRESS,
MSC_SOURCE_FILE,
DATA_SOURCE,
SERVICE_CENTRE ,
TRANSACTION_SERVICE_CODE,
RECORD_TYPE,
FT_INSERT_DATE,
IT_INSERT_DATE,
ORIGIN_FILENAME,
OLD_CALLING_NUMBER ,
OLD_CALLED_NUMBER,
ROAMING_NUMBER,
INITIAL_DOUBLON_COUNT,
RAW_GSMSCFADDR,
RAW_USERTYPE,
RAW_LEVELCAMELSVC,
OTHER_PARTY_TRANSLATED_NUM,
NETCALLREF,
CALLER_PFLAG,
CALLED_PFLAG,
RN,
TRANSACTION_DATE FROM (
  SELECT
     TRANSACTION_TIME,
     TRANSACTION_DIRECTION,
     TRANSACTION_TYPE,
     SUBS_TYPE,
     (CASE
        WHEN LENGTH (SERVED_MSISDN_TRANSFORMED) = 8 THEN
          (CASE
            WHEN (substr(SERVED_MSISDN_TRANSFORMED,1,1) = '9') OR (substr(SERVED_MSISDN_TRANSFORMED,1,2) IN ('55', '56', '57', '58', '59')) THEN CONCAT('6',SERVED_MSISDN_TRANSFORMED)
            WHEN (substr(SERVED_MSISDN_TRANSFORMED,1,1) = '7') OR (substr(SERVED_MSISDN_TRANSFORMED,1,2) IN ('50', '51', '52', '53', '54','80','81','82','83')) THEN CONCAT('6',SERVED_MSISDN_TRANSFORMED)
            WHEN substr(SERVED_MSISDN_TRANSFORMED,1,1) = '6' OR substr(SERVED_MSISDN_TRANSFORMED,1,2) = '85'  THEN CONCAT('6',SERVED_MSISDN_TRANSFORMED)
            WHEN substr(SERVED_MSISDN_TRANSFORMED,1,1) in ('2','3') and substr(SERVED_MSISDN_TRANSFORMED,1,2)='22'  THEN CONCAT('242',substr(SERVED_MSISDN_TRANSFORMED,-6))
            WHEN substr(SERVED_MSISDN_TRANSFORMED,1,1) in ('2','3') and substr(SERVED_MSISDN_TRANSFORMED,1,2)='33'  THEN CONCAT('243',substr(SERVED_MSISDN_TRANSFORMED,-6))
            ELSE SERVED_MSISDN_TRANSFORMED
           END)
        ELSE SERVED_MSISDN_TRANSFORMED
      END) SERVED_MSISDN,
     SERVED_IMSI,
     SERVED_IMEI,
     SERVED_PARTY_LOCATION,
    (CASE
      WHEN LENGTH (OTHER_PARTY_TRANSFORMED2) = 8 THEN
      (CASE
        WHEN (substr(OTHER_PARTY_TRANSFORMED2,1,1) = '9') OR (substr(OTHER_PARTY_TRANSFORMED2,1,2) IN ('55', '56', '57', '58', '59')) THEN CONCAT('6',OTHER_PARTY_TRANSFORMED2)
        WHEN (substr(OTHER_PARTY_TRANSFORMED2,1,1) = '7') OR (substr(OTHER_PARTY_TRANSFORMED2,1,2) IN ('50', '51', '52', '53', '54','80','81','82','83')) THEN CONCAT('6',OTHER_PARTY_TRANSFORMED2)
        WHEN substr(OTHER_PARTY_TRANSFORMED2,1,1) = '6' OR substr(OTHER_PARTY_TRANSFORMED2,1,2) = '85'  THEN CONCAT('6',OTHER_PARTY_TRANSFORMED2)
        WHEN substr(OTHER_PARTY_TRANSFORMED2,1,1) in ('2','3') and substr(OTHER_PARTY_TRANSFORMED2,1,2)='22'  THEN CONCAT('242',substr(OTHER_PARTY_TRANSFORMED2,-6))
        WHEN substr(OTHER_PARTY_TRANSFORMED2,1,1) in ('2','3') and substr(OTHER_PARTY_TRANSFORMED2,1,2)='33'  THEN CONCAT('243',substr(OTHER_PARTY_TRANSFORMED2,-6))
        ELSE OTHER_PARTY_TRANSFORMED2
           END)
        ELSE OTHER_PARTY_TRANSFORMED2
      END)  OTHER_PARTY,
     (CASE
        WHEN LENGTH(PARTNER_GT_TRANSFORMED2) = 9
        AND  SUBSTR(PARTNER_GT_TRANSFORMED2, 1, 1) NOT IN ('0', '2')
          THEN PARTNER_GT_TRANSFORMED2
        WHEN SUBSTR(REGEXP_REPLACE(PARTNER_GT_TRANSFORMED2,"^0+(?!$)",""), 1, 3) = '237'
        AND LENGTH(REGEXP_REPLACE(PARTNER_GT_TRANSFORMED2,"^0+(?!$)","")) > 3
          THEN SUBSTR(REGEXP_REPLACE(PARTNER_GT_TRANSFORMED2,"^0+(?!$)",""), 4)
        ELSE IF(REGEXP_REPLACE(PARTNER_GT_TRANSFORMED2,"^0+(?!$)","") ="0", NULL, REGEXP_REPLACE(PARTNER_GT_TRANSFORMED2,"^0+(?!$)",""))
      END) PARTNER_GT,
     TRANSACTION_DURATION,
     TRANSACTION_VOLUME,
     MEASUREMENT_UNIT,
     TRANSACTION_TERM_CODE,
     TRUNCK_IN,
     TRUNCK_OUT,
     MSC_ADRESS,
     MSC_SOURCE_FILE,
     DATA_SOURCE,
     SERVICE_CENTRE ,
     TRANSACTION_SERVICE_CODE,
     RECORD_TYPE,
     FT_INSERT_DATE,
     IT_INSERT_DATE,
     ORIGIN_FILENAME,
     OLD_CALLING_NUMBER ,
     OLD_CALLED_NUMBER,
     ROAMING_NUMBER,
     INITIAL_DOUBLON_COUNT,
     RAW_GSMSCFADDR,
     RAW_USERTYPE,
     RAW_LEVELCAMELSVC,
     OTHER_PARTY_TRANSLATED_NUM,
     NETCALLREF,
     CALLER_PFLAG,
     CALLED_PFLAG,
     RN,
     TRANSACTION_DATE
   FROM(
   SELECT
    TO_DATE(cra_datetime) Transaction_Date
  , DATE_FORMAT(cra_datetime, 'HHmmss')  Transaction_Time
  , CALL_TYPE Transaction_Direction
  , transaction_type Transaction_Type
  , subs_type
  , (CASE
      WHEN MSISDN_TRANSFORMED IN ('44534952454D494E4445', '534D5350415243')   THEN '99999999'
      WHEN LENGTH(NVL(REGEXP_EXTRACT(MSISDN_TRANSFORMED,'[0-9]+', 0),MSISDN_TRANSFORMED)) = 9
      AND  SUBSTR(NVL(REGEXP_EXTRACT(MSISDN_TRANSFORMED,'[0-9]+', 0),MSISDN_TRANSFORMED), 1, 1) NOT IN ('0', '2')
        THEN NVL(REGEXP_EXTRACT(MSISDN_TRANSFORMED,'[0-9]+', 0),MSISDN_TRANSFORMED)
      WHEN SUBSTR(REGEXP_REPLACE(NVL(REGEXP_EXTRACT(MSISDN_TRANSFORMED,'[0-9]+', 0),MSISDN_TRANSFORMED),"^0+(?!$)",""), 1, 3) = '237'
      AND LENGTH(REGEXP_REPLACE(NVL(REGEXP_EXTRACT(MSISDN_TRANSFORMED,'[0-9]+', 0),MSISDN_TRANSFORMED),"^0+(?!$)","")) > 3
        THEN SUBSTR(REGEXP_REPLACE(NVL(REGEXP_EXTRACT(MSISDN_TRANSFORMED,'[0-9]+', 0),MSISDN_TRANSFORMED),"^0+(?!$)",""), 4)
      ELSE IF(REGEXP_REPLACE(NVL(REGEXP_EXTRACT(MSISDN_TRANSFORMED,'[0-9]+', 0),MSISDN_TRANSFORMED),"^0+(?!$)","") ="0", NULL, REGEXP_REPLACE(NVL(REGEXP_EXTRACT(MSISDN_TRANSFORMED,'[0-9]+', 0),MSISDN_TRANSFORMED),"^0+(?!$)",""))
    END) SERVED_MSISDN_TRANSFORMED
  , imsi Served_IMSI
  , IMEI Served_IMEI
  , MS_LOCATION Served_Party_Location
  , (CASE
      WHEN OTHER_PARTY_TRANSFORMED IN ('44534952454D494E4445', '534D5350415243') 	THEN '99999999'
      WHEN LENGTH(NVL(REGEXP_EXTRACT(OTHER_PARTY_TRANSFORMED,'[0-9]+', 0),OTHER_PARTY_TRANSFORMED)) = 9
      AND  SUBSTR(NVL(REGEXP_EXTRACT(OTHER_PARTY_TRANSFORMED,'[0-9]+', 0),OTHER_PARTY_TRANSFORMED), 1, 1) NOT IN ('0', '2') 	THEN NVL(REGEXP_EXTRACT(OTHER_PARTY_TRANSFORMED,'[0-9]+', 0),OTHER_PARTY_TRANSFORMED)
      WHEN SUBSTR(REGEXP_REPLACE(NVL(REGEXP_EXTRACT(OTHER_PARTY_TRANSFORMED,'[0-9]+', 0),OTHER_PARTY_TRANSFORMED),"^0+(?!$)",""), 1, 3) = '237'
      AND LENGTH(REGEXP_REPLACE(NVL(REGEXP_EXTRACT(OTHER_PARTY_TRANSFORMED,'[0-9]+', 0),OTHER_PARTY_TRANSFORMED),"^0+(?!$)","")) > 3 	THEN SUBSTR(REGEXP_REPLACE(NVL(REGEXP_EXTRACT(OTHER_PARTY_TRANSFORMED,'[0-9]+', 0),OTHER_PARTY_TRANSFORMED),"^0+(?!$)",""), 4)
      ELSE IF(REGEXP_REPLACE(NVL(REGEXP_EXTRACT(OTHER_PARTY_TRANSFORMED,'[0-9]+', 0),OTHER_PARTY_TRANSFORMED),"^0+(?!$)","") ="0", NULL, REGEXP_REPLACE(NVL(REGEXP_EXTRACT(OTHER_PARTY_TRANSFORMED,'[0-9]+', 0),OTHER_PARTY_TRANSFORMED),"^0+(?!$)",""))
     END) OTHER_PARTY_TRANSFORMED2
  , (CASE
      WHEN PARTNER_GT_TRANSFORMED IN ('44534952454D494E4445', '534D5350415243')
        THEN '99999999'
      WHEN LENGTH (PARTNER_GT_TRANSFORMED) > 8
        THEN IF(REGEXP_EXTRACT(PARTNER_GT_TRANSFORMED,'[0-9]{9,}', 0) = '', PARTNER_GT_TRANSFORMED, REGEXP_EXTRACT(PARTNER_GT_TRANSFORMED,'[0-9]{9,}', 0))
      ELSE NVL(REGEXP_EXTRACT(PARTNER_GT_TRANSFORMED,'[0-9]+', 0),PARTNER_GT_TRANSFORMED)
    END) PARTNER_GT_TRANSFORMED2
  , duration Transaction_Duration
  , duration Transaction_Volume
  , 'ss' Measurement_unit
  , TERM_TYPE Transaction_Term_code
  , TRUNCK_IN Trunck_in
  , TRUNCK_OUT Trunck_out
  , CRA_MSC_ID Msc_Adress
  , CRA_FICHIER Msc_Source_File
  , 'MSCHUA' Data_source
  , servicecentre Service_Centre
  , basic_serv Transaction_Service_Code
  , rec_type Record_Type
  , CURRENT_TIMESTAMP FT_Insert_date
  , INSERT_DATE IT_Insert_date
  , ORIGINAL_FILE_NAME Origin_filename
  , CALLINGNUMBER Old_Calling_Number
  , CALLEDNUMBER Old_Called_Number
  , ROAMINGNUMBER Roaming_Number
  , doublon_count Initial_Doublon_Count
  , gsmscfaddr Raw_gsmscfaddr
  , userType Raw_usertype
  , levelCAMELSvc Raw_levelcamelsvc
  , OTHER_PARTY_TRANSLATED_NUM
  , NETCALLREF
  , CALLER_PFLAG
  , CALLED_PFLAG
  , RN

  FROM (
    -- dedoublonnage
  SELECT
      MAX(CASE
        WHEN SYSTEMTYPE = 2 AND TELESERVICE = 34 AND RECTYPE = 6 THEN 'SMS_MO'
        WHEN SYSTEMTYPE = 2 AND TELESERVICE = 33 AND RECTYPE = 7 THEN 'SMS_MT'
        WHEN SYSTEMTYPE = 1 AND TELESERVICE = 34 AND RECTYPE = 6 THEN 'SMS_MO_NOTIF'
        WHEN SYSTEMTYPE = 2 AND TELESERVICE = 17 AND RECTYPE = 0 THEN 'TEL_MOC'
        WHEN SYSTEMTYPE = 2 AND TELESERVICE = 17 AND RECTYPE = 1 AND CALLEDNUMBER = CALLINGNUMBER THEN 'TEL_TRANSIT_OUT'
        WHEN SYSTEMTYPE = 2 AND TELESERVICE = 17 AND RECTYPE = 1 THEN 'TEL_MTC'
        WHEN RECTYPE = 5 THEN
          (CASE
              WHEN OUTTRUNKGROUP LIKE '%LOCMR%VMS%' THEN 'TEL_TRANSIT_IN'
              WHEN OUTTRUNKGROUP LIKE '%ILMT%' THEN 'TEL_TRANSIT_IN'
              WHEN INTRUNKGROUP LIKE '%DOUMS%IPBX%' OR INTRUNKGROUP LIKE '%LOCMR%IPBX%' THEN 'TEL_TRANSIT_OUT'
              WHEN INTRUNKGROUP NOT LIKE '%LOCMR%' THEN 'TEL_TRANSIT_IN'
              WHEN INTRUNKGROUP LIKE '%LOCMR%BICC%' THEN 'TEL_TRANSIT_IN'
              WHEN OUTTRUNKGROUP LIKE '%LOCMR%PABX%' THEN 'TEL_TRANSIT_IN'
              WHEN OUTTRUNKGROUP LIKE '%DOUMS%IPBX%' OR OUTTRUNKGROUP LIKE '%LOCMR%IPBX%' THEN 'TEL_TRANSIT_IN'
              ELSE 'TEL_TRANSIT_OUT'
          END )
        WHEN TELESERVICE = 17 AND RECTYPE = 2 THEN 'TEL_ROAM'
        WHEN TELESERVICE = 17 AND RECTYPE = 100 THEN 'TEL_CFW'
        WHEN TELESERVICE = 18 THEN 'Emergency calls'
        WHEN TELESERVICE = 98 THEN 'TEL_AUTOFACSIMGRP'
        WHEN TELESERVICE = 17 THEN 'TEL'
        WHEN TELESERVICE = 34 THEN 'SMS_MO'
        WHEN TELESERVICE = 33 THEN 'SMS_MT'
        WHEN RECTYPE = 3     THEN 'TEL_PABX'
        ELSE 'TEL_UKN'
      END )  TRANSACTION_TYPE
    , MAX(CASE
        WHEN  SUBSTR(SERVEDIMSI, 1, 5) <> '62402' AND SERVEDIMSI IS NOT NULL THEN 'ROAM'
        WHEN USERTYPE=1 OR USERTYPE =2 THEN 'PREP'
        WHEN USERTYPE=0 THEN 'POST'
        WHEN (USERTYPE IS NULL  AND (LEVELCAMELSVC IS NOT NULL OR GSMSCFADDR IS NOT NULL OR GSMSCFADDR2 IS NOT NULL OR CMLMODIF IS NOT NULL)) THEN 'PREP'
        WHEN (USERTYPE IS NULL  AND LEVELCAMELSVC IS NULL AND GSMSCFADDR IS NULL AND GSMSCFADDR2 IS NULL AND CMLMODIF IS NULL) THEN 'POST'
        ELSE 'PREP/POST'
      END)  SUBS_TYPE
    , MAX(CASE
        WHEN NVL (rectype, 0) IN (0,6,3) THEN 'Sortant'
        WHEN rectype IN (7, 1) THEN 'Entrant'
        WHEN rectype IN (100) THEN
        (CASE
           WHEN substr(outtrunkgroup, 1, 1) = 'I' then 'Sortant'
           ELSE 'Entrant'END)
        WHEN rectype = 5 THEN
        (CASE
         WHEN outtrunkgroup LIKE '%LOCMR%VMS%' THEN 'Entrant'
         WHEN outtrunkgroup LIKE '%ILMT%' THEN 'Entrant'
         WHEN intrunkgroup LIKE '%DOUMS%IPBX%' OR intrunkgroup LIKE '%LOCMR%IPBX%' THEN 'Sortant'
         WHEN intrunkgroup NOT LIKE '%LOCMR%' THEN 'Entrant'
         WHEN intrunkgroup LIKE '%LOCMR%BICC%' THEN 'Entrant'
         WHEN outtrunkgroup LIKE '%LOCMR%PABX%' THEN 'Entrant'
         WHEN outtrunkgroup LIKE '%DOUMS%IPBX%' OR outtrunkgroup LIKE '%LOCMR%IPBX%' THEN 'Entrant'
         ELSE 'Sortant'
         END )
        ELSE 'Entrant'
      END )  CALL_TYPE
    , (CASE
        WHEN RECTYPE =  3 THEN CALLINGNUMBER
        WHEN RECTYPE = 5 THEN
          (CASE
            WHEN OUTTRUNKGROUP LIKE '%LOCMR%VMS%' THEN CALLEDNUMBER
            WHEN OUTTRUNKGROUP LIKE '%ILMT%' THEN CALLEDNUMBER
            WHEN INTRUNKGROUP LIKE '%DOUMS%IPBX%' OR INTRUNKGROUP LIKE '%LOCMR%IPBX%' THEN CALLINGNUMBER
            WHEN INTRUNKGROUP NOT LIKE '%LOCMR%' THEN CALLEDNUMBER
            WHEN INTRUNKGROUP LIKE '%LOCMR%BICC%' THEN CALLEDNUMBER
            WHEN OUTTRUNKGROUP LIKE '%LOCMR%PABX%' THEN CALLEDNUMBER
            WHEN OUTTRUNKGROUP LIKE '%DOUMS%IPBX%' OR OUTTRUNKGROUP LIKE '%LOCMR%IPBX%' THEN CALLEDNUMBER
            ELSE CALLINGNUMBER
          END )
        ELSE SERVEDMSISDN
      END ) MSISDN_TRANSFORMED
    , MAX(CASE
           WHEN RECTYPE = 6 THEN  DESTINANUMBER
           WHEN RECTYPE = 7 THEN  ORIGINATION
           WHEN NVL (RECTYPE, 0) IN  (0, 3, 100) THEN  CALLEDNUMBER
           WHEN RECTYPE IN  (1, 2) THEN  CALLINGNUMBER
           WHEN RECTYPE = 5 THEN
             (CASE
               WHEN OUTTRUNKGROUP LIKE '%LOCMR%VMS%' THEN CALLINGNUMBER
               WHEN OUTTRUNKGROUP LIKE '%ILMT%' THEN CALLINGNUMBER
               WHEN INTRUNKGROUP LIKE '%DOUMS%IPBX%' OR INTRUNKGROUP LIKE '%LOCMR%IPBX%' THEN CALLEDNUMBER
               WHEN INTRUNKGROUP NOT LIKE '%LOCMR%' THEN CALLINGNUMBER
               WHEN INTRUNKGROUP LIKE '%LOCMR%BICC%' THEN CALLINGNUMBER
               WHEN OUTTRUNKGROUP LIKE '%LOCMR%PABX%' THEN CALLINGNUMBER
               WHEN OUTTRUNKGROUP LIKE '%DOUMS%IPBX%' OR OUTTRUNKGROUP LIKE '%LOCMR%IPBX%' THEN CALLINGNUMBER
               ELSE CALLEDNUMBER
               END )
           ELSE CALLEDNUMBER
        END ) OTHER_PARTY_TRANSFORMED
    , MAX(CASE
           WHEN RECTYPE = 6 THEN  DESTINANUMBER
           WHEN RECTYPE = 7 THEN  ORIGINATION
           WHEN NVL (RECTYPE, 0) IN  (0, 3, 100) THEN  CALLEDNUMBER
           WHEN RECTYPE IN  (1, 2) THEN  CALLINGNUMBER
           WHEN RECTYPE = 5 THEN
             (CASE
               WHEN OUTTRUNKGROUP LIKE '%LOCMR%VMS%' THEN CALLINGNUMBER
               WHEN OUTTRUNKGROUP LIKE '%ILMT%' THEN CALLINGNUMBER
               WHEN INTRUNKGROUP LIKE '%DOUMS%IPBX%' OR INTRUNKGROUP LIKE '%LOCMR%IPBX%' THEN CALLEDNUMBER
               WHEN INTRUNKGROUP NOT LIKE '%LOCMR%' THEN CALLINGNUMBER
               WHEN INTRUNKGROUP LIKE '%LOCMR%BICC%' THEN CALLEDNUMBER
               WHEN OUTTRUNKGROUP LIKE '%LOCMR%PABX%' THEN CALLINGNUMBER
               WHEN OUTTRUNKGROUP LIKE '%DOUMS%IPBX%' OR OUTTRUNKGROUP LIKE '%LOCMR%IPBX%' THEN CALLINGNUMBER
               ELSE CALLEDNUMBER
               END )
           ELSE CALLEDNUMBER
        END ) PARTNER_GT_TRANSFORMED
    , (CASE
        WHEN CALLEDNUMBER IN ('44534952454D494E4445', '534D5350415243') 	THEN '99999999'
        WHEN LENGTH(NVL(REGEXP_EXTRACT(CALLEDNUMBER,'[0-9]+', 0),CALLEDNUMBER)) = 9
          AND  SUBSTR(NVL(REGEXP_EXTRACT(CALLEDNUMBER,'[0-9]+', 0),CALLEDNUMBER), 1, 1) NOT IN ('0', '2')
          THEN NVL(REGEXP_EXTRACT(CALLEDNUMBER,'[0-9]+', 0),CALLEDNUMBER)
        WHEN SUBSTR(REGEXP_REPLACE(NVL(REGEXP_EXTRACT(CALLEDNUMBER,'[0-9]+', 0),CALLEDNUMBER),"^0+(?!$)",""), 1, 3) = '237'
        AND LENGTH(REGEXP_REPLACE(NVL(REGEXP_EXTRACT(CALLEDNUMBER,'[0-9]+', 0),CALLEDNUMBER),"^0+(?!$)","")) > 3
          THEN SUBSTR(REGEXP_REPLACE(NVL(REGEXP_EXTRACT(CALLEDNUMBER,'[0-9]+', 0),CALLEDNUMBER),"^0+(?!$)",""), 4)
        ELSE IF(REGEXP_REPLACE(NVL(REGEXP_EXTRACT(CALLEDNUMBER,'[0-9]+', 0),CALLEDNUMBER),"^0+(?!$)","") ="0", NULL, REGEXP_REPLACE(NVL(REGEXP_EXTRACT(CALLEDNUMBER,'[0-9]+', 0),CALLEDNUMBER),"^0+(?!$)",""))
      END) CALLEDNUMBER
    , (CASE
        WHEN CALLINGNUMBER IN ('44534952454D494E4445', '534D5350415243') 	THEN '99999999'
        WHEN LENGTH(NVL(REGEXP_EXTRACT(CALLINGNUMBER,'[0-9]+', 0),CALLINGNUMBER)) = 9
          AND  SUBSTR(NVL(REGEXP_EXTRACT(CALLINGNUMBER,'[0-9]+', 0),CALLINGNUMBER), 1, 1) NOT IN ('0', '2')
          THEN NVL(REGEXP_EXTRACT(CALLINGNUMBER,'[0-9]+', 0),CALLINGNUMBER)
        WHEN SUBSTR(REGEXP_REPLACE(NVL(REGEXP_EXTRACT(CALLINGNUMBER,'[0-9]+', 0),CALLINGNUMBER),"^0+(?!$)",""), 1, 3) = '237'
        AND LENGTH(REGEXP_REPLACE(NVL(REGEXP_EXTRACT(CALLINGNUMBER,'[0-9]+', 0),CALLINGNUMBER),"^0+(?!$)","")) > 3
          THEN SUBSTR(REGEXP_REPLACE(NVL(REGEXP_EXTRACT(CALLINGNUMBER,'[0-9]+', 0),CALLINGNUMBER),"^0+(?!$)",""), 4)
        ELSE IF(REGEXP_REPLACE(NVL(REGEXP_EXTRACT(CALLINGNUMBER,'[0-9]+', 0),CALLINGNUMBER),"^0+(?!$)","") ="0", NULL, REGEXP_REPLACE(NVL(REGEXP_EXTRACT(CALLINGNUMBER,'[0-9]+', 0),CALLINGNUMBER),"^0+(?!$)",""))
      END) CALLINGNUMBER
    ,(CASE
        WHEN SERVICECENTRE IN ('44534952454D494E4445', '534D5350415243') 	THEN '99999999'
        WHEN LENGTH(NVL(REGEXP_EXTRACT(SERVICECENTRE,'[0-9]+', 0),SERVICECENTRE)) = 9
          AND  SUBSTR(NVL(REGEXP_EXTRACT(SERVICECENTRE,'[0-9]+', 0),SERVICECENTRE), 1, 1) NOT IN ('0', '2')
          THEN NVL(REGEXP_EXTRACT(SERVICECENTRE,'[0-9]+', 0),SERVICECENTRE)
        WHEN SUBSTR(REGEXP_REPLACE(NVL(REGEXP_EXTRACT(SERVICECENTRE,'[0-9]+', 0),SERVICECENTRE),"^0+(?!$)",""), 1, 3) = '237'
        AND LENGTH(REGEXP_REPLACE(NVL(REGEXP_EXTRACT(SERVICECENTRE,'[0-9]+', 0),SERVICECENTRE),"^0+(?!$)","")) > 3
          THEN SUBSTR(REGEXP_REPLACE(NVL(REGEXP_EXTRACT(SERVICECENTRE,'[0-9]+', 0),SERVICECENTRE),"^0+(?!$)",""), 4)
        ELSE IF(REGEXP_REPLACE(NVL(REGEXP_EXTRACT(SERVICECENTRE,'[0-9]+', 0),SERVICECENTRE),"^0+(?!$)","") ="0", NULL, REGEXP_REPLACE(NVL(REGEXP_EXTRACT(SERVICECENTRE,'[0-9]+', 0),SERVICECENTRE),"^0+(?!$)",""))
      END)  SERVICECENTRE
    , (CASE
        WHEN ROAMINGNUMBER IN ('44534952454D494E4445', '534D5350415243') 	THEN '99999999'
        WHEN LENGTH(NVL(REGEXP_EXTRACT(ROAMINGNUMBER,'[0-9]+', 0),ROAMINGNUMBER)) = 9
          AND  SUBSTR(NVL(REGEXP_EXTRACT(ROAMINGNUMBER,'[0-9]+', 0),ROAMINGNUMBER), 1, 1) NOT IN ('0', '2')
          THEN NVL(REGEXP_EXTRACT(ROAMINGNUMBER,'[0-9]+', 0),ROAMINGNUMBER)
        WHEN SUBSTR(REGEXP_REPLACE(NVL(REGEXP_EXTRACT(ROAMINGNUMBER,'[0-9]+', 0),ROAMINGNUMBER),"^0+(?!$)",""), 1, 3) = '237'
        AND LENGTH(REGEXP_REPLACE(NVL(REGEXP_EXTRACT(ROAMINGNUMBER,'[0-9]+', 0),ROAMINGNUMBER),"^0+(?!$)","")) > 3
          THEN SUBSTR(REGEXP_REPLACE(NVL(REGEXP_EXTRACT(ROAMINGNUMBER,'[0-9]+', 0),ROAMINGNUMBER),"^0+(?!$)",""), 4)
        ELSE IF(REGEXP_REPLACE(NVL(REGEXP_EXTRACT(ROAMINGNUMBER,'[0-9]+', 0),ROAMINGNUMBER),"^0+(?!$)","") ="0", NULL, REGEXP_REPLACE(NVL(REGEXP_EXTRACT(ROAMINGNUMBER,'[0-9]+', 0),ROAMINGNUMBER),"^0+(?!$)",""))
      END) ROAMINGNUMBER
    , (CASE
        WHEN TRANSLATEDNUM IN ('44534952454D494E4445', '534D5350415243') 	THEN '99999999'
        WHEN LENGTH(NVL(REGEXP_EXTRACT(TRANSLATEDNUM,'[0-9]+', 0),TRANSLATEDNUM)) = 9
          AND  SUBSTR(NVL(REGEXP_EXTRACT(TRANSLATEDNUM,'[0-9]+', 0),TRANSLATEDNUM), 1, 1) NOT IN ('0', '2')
          THEN NVL(REGEXP_EXTRACT(TRANSLATEDNUM,'[0-9]+', 0),TRANSLATEDNUM)
        WHEN SUBSTR(REGEXP_REPLACE(NVL(REGEXP_EXTRACT(TRANSLATEDNUM,'[0-9]+', 0),TRANSLATEDNUM),"^0+(?!$)",""), 1, 3) = '237'
        AND LENGTH(REGEXP_REPLACE(NVL(REGEXP_EXTRACT(TRANSLATEDNUM,'[0-9]+', 0),TRANSLATEDNUM),"^0+(?!$)","")) > 3
          THEN SUBSTR(REGEXP_REPLACE(NVL(REGEXP_EXTRACT(TRANSLATEDNUM,'[0-9]+', 0),TRANSLATEDNUM),"^0+(?!$)",""), 4)
        ELSE IF(REGEXP_REPLACE(NVL(REGEXP_EXTRACT(TRANSLATEDNUM,'[0-9]+', 0),TRANSLATEDNUM),"^0+(?!$)","") ="0", NULL, REGEXP_REPLACE(NVL(REGEXP_EXTRACT(TRANSLATEDNUM,'[0-9]+', 0),TRANSLATEDNUM),"^0+(?!$)",""))
      END) OTHER_PARTY_TRANSLATED_NUM
    , NQ_CALLDATE cra_datetime
    , RECTYPE rec_type
    , NVL(CALLDURATION, 0) duration
    , SERVEDIMSI imsi
    , TELESERVICE basic_serv
    , MAX(NVL(CAUSEFORTERM, 0)) TERM_TYPE
    , NULL MSC_TYPE
    , MAX(MSCADDRESS) CRA_MSC_ID
    , MAX(GLOBALAREAID) MS_LOCATION
    , MAX(SERVEDIMEI) IMEI
    , MAX(OUTTRUNKGROUP) TRUNCK_OUT
    , MAX(INTRUNKGROUP) TRUNCK_IN
    , MAX(SOURCE) CRA_FICHIER
    , NULL type_heure
    , MAX (INSERT_DATE) INSERT_DATE
    , MAX (ORIGINAL_FILE_NAME) ORIGINAL_FILE_NAME
    , MAX (gsmscfaddr) gsmscfaddr
    , MAX (userType) userType
    , MAX (levelCAMELSvc) levelCAMELSvc
    , SUM (1) doublon_count
    , NETCALLREF
    , CALLER_PFLAG
    , CALLED_PFLAG
    , RN
  FROM CDR.IT_CRA_MSC_HUAWEI a
  WHERE
     CALLDATE = '2019-01-08'
     AND SUBSTR(nvl(ROAMINGNUMBER,'99999999'),1,7) NOT IN ('2371601','2371603')
  GROUP BY
      (CASE
        WHEN RECTYPE =  3 THEN CALLINGNUMBER
        WHEN RECTYPE = 5 THEN
          (CASE
            WHEN OUTTRUNKGROUP LIKE '%LOCMR%VMS%' THEN CALLEDNUMBER
            WHEN OUTTRUNKGROUP LIKE '%ILMT%' THEN CALLEDNUMBER
            WHEN INTRUNKGROUP LIKE '%DOUMS%IPBX%' OR INTRUNKGROUP LIKE '%LOCMR%IPBX%' THEN CALLINGNUMBER
            WHEN INTRUNKGROUP NOT LIKE '%LOCMR%' THEN CALLEDNUMBER
            WHEN INTRUNKGROUP LIKE '%LOCMR%BICC%' THEN CALLEDNUMBER
            WHEN OUTTRUNKGROUP LIKE '%LOCMR%PABX%' THEN CALLEDNUMBER
            WHEN OUTTRUNKGROUP LIKE '%DOUMS%IPBX%' OR OUTTRUNKGROUP LIKE '%LOCMR%IPBX%' THEN CALLEDNUMBER
            ELSE CALLINGNUMBER
          END )
        ELSE SERVEDMSISDN
      END )
    , NQ_CALLDATE
    , RECTYPE
    , NVL(CALLDURATION, 0)
    , SERVEDIMSI
    , TELESERVICE
    , (CASE
        WHEN CALLEDNUMBER IN ('44534952454D494E4445', '534D5350415243') 	THEN '99999999'
        WHEN LENGTH(NVL(REGEXP_EXTRACT(CALLEDNUMBER,'[0-9]+', 0),CALLEDNUMBER)) = 9
          AND  SUBSTR(NVL(REGEXP_EXTRACT(CALLEDNUMBER,'[0-9]+', 0),CALLEDNUMBER), 1, 1) NOT IN ('0', '2')
          THEN NVL(REGEXP_EXTRACT(CALLEDNUMBER,'[0-9]+', 0),CALLEDNUMBER)
        WHEN SUBSTR(REGEXP_REPLACE(NVL(REGEXP_EXTRACT(CALLEDNUMBER,'[0-9]+', 0),CALLEDNUMBER),"^0+(?!$)",""), 1, 3) = '237'
        AND LENGTH(REGEXP_REPLACE(NVL(REGEXP_EXTRACT(CALLEDNUMBER,'[0-9]+', 0),CALLEDNUMBER),"^0+(?!$)","")) > 3
          THEN SUBSTR(REGEXP_REPLACE(NVL(REGEXP_EXTRACT(CALLEDNUMBER,'[0-9]+', 0),CALLEDNUMBER),"^0+(?!$)",""), 4)
        ELSE IF(REGEXP_REPLACE(NVL(REGEXP_EXTRACT(CALLEDNUMBER,'[0-9]+', 0),CALLEDNUMBER),"^0+(?!$)","") ="0", NULL, REGEXP_REPLACE(NVL(REGEXP_EXTRACT(CALLEDNUMBER,'[0-9]+', 0),CALLEDNUMBER),"^0+(?!$)",""))
      END)
    , (CASE
        WHEN CALLINGNUMBER IN ('44534952454D494E4445', '534D5350415243') 	THEN '99999999'
        WHEN LENGTH(NVL(REGEXP_EXTRACT(CALLINGNUMBER,'[0-9]+', 0),CALLINGNUMBER)) = 9
          AND  SUBSTR(NVL(REGEXP_EXTRACT(CALLINGNUMBER,'[0-9]+', 0),CALLINGNUMBER), 1, 1) NOT IN ('0', '2')
          THEN NVL(REGEXP_EXTRACT(CALLINGNUMBER,'[0-9]+', 0),CALLINGNUMBER)
        WHEN SUBSTR(REGEXP_REPLACE(NVL(REGEXP_EXTRACT(CALLINGNUMBER,'[0-9]+', 0),CALLINGNUMBER),"^0+(?!$)",""), 1, 3) = '237'
        AND LENGTH(REGEXP_REPLACE(NVL(REGEXP_EXTRACT(CALLINGNUMBER,'[0-9]+', 0),CALLINGNUMBER),"^0+(?!$)","")) > 3
          THEN SUBSTR(REGEXP_REPLACE(NVL(REGEXP_EXTRACT(CALLINGNUMBER,'[0-9]+', 0),CALLINGNUMBER),"^0+(?!$)",""), 4)
        ELSE IF(REGEXP_REPLACE(NVL(REGEXP_EXTRACT(CALLINGNUMBER,'[0-9]+', 0),CALLINGNUMBER),"^0+(?!$)","") ="0", NULL, REGEXP_REPLACE(NVL(REGEXP_EXTRACT(CALLINGNUMBER,'[0-9]+', 0),CALLINGNUMBER),"^0+(?!$)",""))
      END)
    , (CASE
        WHEN SERVICECENTRE IN ('44534952454D494E4445', '534D5350415243') 	THEN '99999999'
        WHEN LENGTH(NVL(REGEXP_EXTRACT(SERVICECENTRE,'[0-9]+', 0),SERVICECENTRE)) = 9
          AND  SUBSTR(NVL(REGEXP_EXTRACT(SERVICECENTRE,'[0-9]+', 0),SERVICECENTRE), 1, 1) NOT IN ('0', '2')
          THEN NVL(REGEXP_EXTRACT(SERVICECENTRE,'[0-9]+', 0),SERVICECENTRE)
        WHEN SUBSTR(REGEXP_REPLACE(NVL(REGEXP_EXTRACT(SERVICECENTRE,'[0-9]+', 0),SERVICECENTRE),"^0+(?!$)",""), 1, 3) = '237'
        AND LENGTH(REGEXP_REPLACE(NVL(REGEXP_EXTRACT(SERVICECENTRE,'[0-9]+', 0),SERVICECENTRE),"^0+(?!$)","")) > 3
          THEN SUBSTR(REGEXP_REPLACE(NVL(REGEXP_EXTRACT(SERVICECENTRE,'[0-9]+', 0),SERVICECENTRE),"^0+(?!$)",""), 4)
        ELSE IF(REGEXP_REPLACE(NVL(REGEXP_EXTRACT(SERVICECENTRE,'[0-9]+', 0),SERVICECENTRE),"^0+(?!$)","") ="0", NULL, REGEXP_REPLACE(NVL(REGEXP_EXTRACT(SERVICECENTRE,'[0-9]+', 0),SERVICECENTRE),"^0+(?!$)",""))
      END)
    , (CASE
        WHEN ROAMINGNUMBER IN ('44534952454D494E4445', '534D5350415243') 	THEN '99999999'
        WHEN LENGTH(NVL(REGEXP_EXTRACT(ROAMINGNUMBER,'[0-9]+', 0),ROAMINGNUMBER)) = 9
          AND  SUBSTR(NVL(REGEXP_EXTRACT(ROAMINGNUMBER,'[0-9]+', 0),ROAMINGNUMBER), 1, 1) NOT IN ('0', '2')
          THEN NVL(REGEXP_EXTRACT(ROAMINGNUMBER,'[0-9]+', 0),ROAMINGNUMBER)
        WHEN SUBSTR(REGEXP_REPLACE(NVL(REGEXP_EXTRACT(ROAMINGNUMBER,'[0-9]+', 0),ROAMINGNUMBER),"^0+(?!$)",""), 1, 3) = '237'
        AND LENGTH(REGEXP_REPLACE(NVL(REGEXP_EXTRACT(ROAMINGNUMBER,'[0-9]+', 0),ROAMINGNUMBER),"^0+(?!$)","")) > 3
          THEN SUBSTR(REGEXP_REPLACE(NVL(REGEXP_EXTRACT(ROAMINGNUMBER,'[0-9]+', 0),ROAMINGNUMBER),"^0+(?!$)",""), 4)
        ELSE IF(REGEXP_REPLACE(NVL(REGEXP_EXTRACT(ROAMINGNUMBER,'[0-9]+', 0),ROAMINGNUMBER),"^0+(?!$)","") ="0", NULL, REGEXP_REPLACE(NVL(REGEXP_EXTRACT(ROAMINGNUMBER,'[0-9]+', 0),ROAMINGNUMBER),"^0+(?!$)",""))
      END)
    , (CASE
        WHEN TRANSLATEDNUM IN ('44534952454D494E4445', '534D5350415243') 	THEN '99999999'
        WHEN LENGTH(NVL(REGEXP_EXTRACT(TRANSLATEDNUM,'[0-9]+', 0),TRANSLATEDNUM)) = 9
          AND  SUBSTR(NVL(REGEXP_EXTRACT(TRANSLATEDNUM,'[0-9]+', 0),TRANSLATEDNUM), 1, 1) NOT IN ('0', '2')
          THEN NVL(REGEXP_EXTRACT(TRANSLATEDNUM,'[0-9]+', 0),TRANSLATEDNUM)
        WHEN SUBSTR(REGEXP_REPLACE(NVL(REGEXP_EXTRACT(TRANSLATEDNUM,'[0-9]+', 0),TRANSLATEDNUM),"^0+(?!$)",""), 1, 3) = '237'
        AND LENGTH(REGEXP_REPLACE(NVL(REGEXP_EXTRACT(TRANSLATEDNUM,'[0-9]+', 0),TRANSLATEDNUM),"^0+(?!$)","")) > 3
          THEN SUBSTR(REGEXP_REPLACE(NVL(REGEXP_EXTRACT(TRANSLATEDNUM,'[0-9]+', 0),TRANSLATEDNUM),"^0+(?!$)",""), 4)
        ELSE IF(REGEXP_REPLACE(NVL(REGEXP_EXTRACT(TRANSLATEDNUM,'[0-9]+', 0),TRANSLATEDNUM),"^0+(?!$)","") ="0", NULL, REGEXP_REPLACE(NVL(REGEXP_EXTRACT(TRANSLATEDNUM,'[0-9]+', 0),TRANSLATEDNUM),"^0+(?!$)",""))
      END)
    , NETCALLREF
    , CALLER_PFLAG
    , CALLED_PFLAG
    , RN
  ) T1
  ) T2
) T3
;
