SELECT 
IF(
    USASOLD.FT_EXIST = 0 
    and BAL1.FT_COUNT>0 and BAL2.FT_COUNT>0 
    and SUBSEX.FT_COUNT>0 
    and REC.FT_COUNT>0 
    and CONTSNAP.FT_COUNT>0 
    and SUBSCRIP.FT_COUNT>0 
    and CRABALID.FT_COUNT>0 
    ,"OK"
    ,"NOK"
) RESULT
FROM
(SELECT COUNT(*) FT_EXIST FROM MON.SPARK_FT_CBM_DAILY_USAGE_SOLDE_DATA WHERE EVENT_DATE = '###SLICE_VALUE###' ) USASOLD,
(SELECT COUNT(*) FT_COUNT FROM CDR.SPARK_IT_ZTE_BAL_EXTRACT WHERE ORIGINAL_FILE_DATE = '###SLICE_VALUE###' ) BAL1,
(SELECT COUNT(*) FT_COUNT FROM CDR.SPARK_IT_ZTE_BAL_EXTRACT WHERE ORIGINAL_FILE_DATE = DATE_ADD('###SLICE_VALUE###', 1)  ) BAL2,
(SELECT COUNT(*) FT_COUNT FROM CDR.SPARK_IT_ZTE_SUBS_EXTRACT WHERE ORIGINAL_FILE_DATE = DATE_ADD('###SLICE_VALUE###', 1) ) SUBSEX,
(SELECT COUNT(*) FT_COUNT FROM CDR.SPARK_IT_ZTE_RECURRING WHERE A.EVENT_DATE = '###SLICE_VALUE###' ) REC,
(SELECT COUNT(*) FT_COUNT FROM MON.SPARK_FT_CONTRACT_SNAPSHOT WHERE EVENT_DATE  = DATE_ADD('###SLICE_VALUE###', 1)) CONTSNAP,
(SELECT COUNT(*) FT_COUNT FROM MON.SPARK_FT_SUBSCRIPTION WHERE TRANSACTION_DATE='###SLICE_VALUE###') SUBSCRIP,
(SELECT COUNT(*) FT_COUNT FROM MON.SPARK_FT_CRA_GPRS_WITH_BAL_ID where SESSION_DATE = "###SLICE_VALUE###") CRABALID