SELECT IF(T_1.FT_EXIST = 0 and T_2.FT_DATA_DA_USAGE_DAILY>0 and T_3.FT_VOICE_SMS_DA_USAGE_DAILY>0 ,"OK","NOK") IT_CTI_EXIST
FROM
(SELECT COUNT(*) FT_EXIST FROM MON.SPARK_FT_CBM_DA_USAGE_DAILY WHERE PERIOD = '###SLICE_VALUE###') T_1,
(SELECT COUNT(*) FT_DATA_DA_USAGE_DAILY FROM MON.SPARK_FT_DATA_DA_USAGE_DAILY WHERE SESSION_DATE = '###SLICE_VALUE###') T_2,
(SELECT COUNT(*) FT_VOICE_SMS_DA_USAGE_DAILY FROM MON.FT_VOICE_SMS_DA_USAGE_DAILY WHERE TRANSACTION_DATE = '###SLICE_VALUE###') T_3

