SELECT IF(T_1.FT_COUNT = 0 AND T_2.FT_REFILL > 1 AND T_3.FT_REFILL > 1 AND T_4.FT_CLIENT_LAST_SITE_DAY > 1 AND T_5.FT_SUBSCRIPTION > 1 AND T_6.IT_ZEBRA_MASTER > 1 ,"OK","NOK") FT_EXIST
FROM
(SELECT COUNT(*) FT_COUNT FROM MON.SPARK_FT_RETAIL_BASE_DETAILLANT WHERE REFILL_DATE= '###SLICE_VALUE###') T_1,
(SELECT COUNT(*) FT_REFILL FROM MON.SPARK_FT_REFILL WHERE REFILL_DATE ='###SLICE_VALUE###' AND REFILL_MEAN = 'C2S')T_2,
(SELECT COUNT(*) FT_REFILL FROM MON.SPARK_FT_REFILL WHERE REFILL_DATE ='###SLICE_VALUE###' AND REFILL_MEAN = 'SCRATCH')T_3,
(SELECT COUNT(*) FT_CLIENT_LAST_SITE_DAY FROM MON.SPARK_FT_CLIENT_LAST_SITE_DAY WHERE EVENT_DATE ='###SLICE_VALUE###')T_4,
(SELECT COUNT(*) FT_SUBSCRIPTION FROM MON.SPARK_FT_SUBSCRIPTION WHERE TRANSACTION_DATE ='###SLICE_VALUE###')T_5,
(SELECT COUNT(*) IT_ZEBRA_MASTER FROM CDR.SPARK_IT_ZEBRA_MASTER WHERE TRANSACTION_DATE= '###SLICE_VALUE###') T_6