SELECT IF(A.FT_EXIST = 0 and B.FT_COUNT>0 and C.FT_COUNT>DATEDIFF(LAST_DAY('###SLICE_VALUE###') , TO_DATE(substr('###SLICE_VALUE###', 1,7) ||'-01')   , "OK","NOK") FROM
(SELECT COUNT(*) FT_EXIST FROM MON.SPARK_FT_CLAWBACKM1 WHERE EVENT_DATE='###SLICE_VALUE###') A,
(SELECT COUNT(*) FT_COUNT FROM MON.SPARK_ACTIV_IDENTIF_DETAILS  WHERE EVENT_DATE = add_months(last_day('###SLICE_VALUE###'), -1)) B,
(SELECT COUNT(DISTINCT REFILL_DATE) FT_COUNT FROM MON.SPARK_FT_REFILL WHERE REFILL_DATE BETWEEN TO_DATE(substr('###SLICE_VALUE###', 1,7) ||'-01') AND last_day('###SLICE_VALUE###')) C






