CREATE TABLE  CTI.FT_AGENT_SESSION
   (
    RESOURCE_NAME VARCHAR(255),
	AGENT_FIRST_NAME VARCHAR(255),
	AGENT_LAST_NAME VARCHAR(255),
	LOGIN TIMESTAMP,
	LOGOUT TIMESTAMP,
	DURATION INT,
	INSERT_DATE TIMESTAMP
	)
COMMENT 'FT_AGENT_SESSION - FT'
PARTITIONED BY (CALL_DATE    DATE)
STORED AS ORC TBLPROPERTIES ('transactional'='true',"orc.compress"="ZLIB","orc.stripe.size"="67108864")
