SELECT IF(T_1.FT_EXIST = 0 and T_2.IT_SM_RES_SESSION_FACT>0 ,"OK","NOK") FT_AGENT_SESSION
FROM
(SELECT COUNT(*) FT_EXIST FROM CTI.FT_AGENT_SESSION WHERE CALL_DATE='###SLICE_VALUE###') T_1,
(SELECT COUNT(*) IT_SM_RES_SESSION_FACT FROM CTI.IT_SM_RES_SESSION_FACT WHERE ORIGINAL_FILE_DATE='###SLICE_VALUE###') T_2