INSERT INTO AGG.SPARK_FT_A_RAF_SUBSCRIPTION_DD
SELECT
TRANSACTION_DATE,
COMMERCIAL_OFFER,
SUBSCRIPTION_CHANNEL,
SERVICE_CODE,
SUBSCRIPTION_SERVICE_DETAILS,
SUM(RATED_AMOUNT) MT_DEBIT,
COUNT(SUBSCRIPTION_SERVICE_DETAILS) NBR_SOUSCRIPTION,
SUM (AMOUNT_VOICE_ONNET) MT_VOICE_ONNET,
SUM (AMOUNT_VOICE_OFFNET) MT_VOICE_OFNET,
SUM (AMOUNT_VOICE_INTER) MT_VOICE_INT,
SUM (AMOUNT_VOICE_ROAMING) MT_VOICE_ROAM,
SUM (AMOUNT_SMS_ROAMING) MT_SMS_ROAM,
SUM (AMOUNT_DATA) MT_DATA,
SUM (AMOUNT_SVA) MT_SVA,
SUM (AMOUNT_SMS_ONNET) MT_SMS_ONNET,
SUM (AMOUNT_SMS_OFFNET) MT_SMS_OFNET,
SUM (AMOUNT_SMS_INTER) MT_SMS_INTER,
SUM(AMOUNT_VOICE_ONNET+ AMOUNT_VOICE_OFFNET+AMOUNT_VOICE_INTER
+AMOUNT_VOICE_ROAMING+AMOUNT_SMS_ROAMING+AMOUNT_DATA+AMOUNT_SVA+
AMOUNT_SMS_ONNET+AMOUNT_SMS_OFFNET+AMOUNT_SMS_INTER) MT_CREDIT,
CURRENT_TIMESTAMP AS INSERT_DATE,
"###SLICE_VALUE###" EVENT_DATE
FROM (SELECT DISTINCT TRANSACTION_DATE,TRANSACTION_TIME,SERVED_PARTY_MSISDN,CONTRACT_TYPE,COMMERCIAL_OFFER,OPERATOR_CODE,SUBSCRIPTION_CHANNEL,SERVICE_LIST,SUBSCRIPTION_SERVICE,SUBSCRIPTION_SERVICE_DETAILS,SUBSCRIPTION_RELATED_SERVICE,RATED_AMOUNT,MAIN_BALANCE_USED,SUBSCRIPTION_STATUS,PREVIOUS_COMMERCIAL_OFFER,SERVICE_CODE,AMOUNT_VOICE_ONNET,AMOUNT_VOICE_OFFNET,AMOUNT_VOICE_INTER,AMOUNT_VOICE_ROAMING,AMOUNT_SMS_ONNET,AMOUNT_SMS_OFFNET,AMOUNT_SMS_INTER,AMOUNT_SMS_ROAMING,AMOUNT_DATA,AMOUNT_SVA FROM MON.SPARK_FT_SUBSCRIPTION
WHERE TRANSACTION_DATE ="###SLICE_VALUE###")a
GROUP BY TRANSACTION_DATE,COMMERCIAL_OFFER,SUBSCRIPTION_CHANNEL,SERVICE_CODE,SUBSCRIPTION_SERVICE_DETAILS