SELECT IF(A.FT_EXIST = 0 and B.FT_COUNT>0 and C.FT_COUNT>0 , "OK","NOK") FROM
(SELECT COUNT(*) FT_EXIST FROM MON.SPARK_FT_DATAMART_OM_DAILY WHERE PERIOD='###SLICE_VALUE###') A,
(SELECT COUNT(*) FT_COUNT FROM CDR.SPARK_IT_OMNY_TRANSACTIONS WHERE transfer_datetime='###SLICE_VALUE###') B,
(SELECT COUNT(*) FT_COUNT FROM MON.SPARK_FT_OMNY_ACCOUNT_SNAPSHOT WHERE event_date='###SLICE_VALUE###') C



