SELECT IF(A.FT_EXIST = 0 AND B.FT_EXIST_1 >0 ,"OK","NOK") FROM
(SELECT COUNT(*) FT_EXIST FROM MON.SPARK_FT_CXD_NBRE_TRANSACTIONS_ECHECS WHERE EVENT_DATE= '###SLICE_VALUE###') A,
(SELECT COUNT(*) FT_EXIST_1 FROM cdr.spark_it_omny_transactions where transfer_datetime='###SLICE_VALUE###') B