
CREATE EXTERNAL TABLE IF NOT EXISTS CTI.FT_IXN_RESOURCE_STATE_FACT (
    IXN_RESOURCE_STATE_FACT_KEY  VARCHAR(20),
    START_DATE_TIME_KEY  VARCHAR(20),
    END_DATE_TIME_KEY  VARCHAR(20),
    TENANT_KEY  VARCHAR(20),
    MEDIA_TYPE_KEY  VARCHAR(20),
    RESOURCE_KEY  VARCHAR(20),
    MEDIA_RESOURCE_KEY  VARCHAR(20),
    PLACE_KEY  VARCHAR(20),
    INTERACTION_RESOURCE_STATE_KEY  VARCHAR(20),
    INTERACTION_TYPE_KEY  VARCHAR(20),
    CREATE_AUDIT_KEY  VARCHAR(20),
    UPDATE_AUDIT_KEY  VARCHAR(20),
    INTERACTION_RESOURCE_ID  VARCHAR(20),
    START_TS  VARCHAR(20),
    END_TS  VARCHAR(20),
    TOTAL_DURATION  VARCHAR(20),
    LEAD_CLIP_DURATION  VARCHAR(20),
    TRAIL_CLIP_DURATION  VARCHAR(20),
    TARGET_ADDRESS  VARCHAR(255),
    ACTIVE_FLAG  VARCHAR(20),
    PURGE_FLAG  VARCHAR(20),
    ORIGINAL_FILE_NAME  VARCHAR(20),
    ORIGINAL_FILE_SIZE INT,
    ORIGINAL_FILE_LINE_COUNT INT

)
PARTITIONED BY (TRANSACTION_DATE DATE)
STORED AS ORC TBLPROPERTIES ('transactional'='true',"orc.compress"="ZLIB","orc.stripe.size"="67108864")
;
