SELECT IF(
    T_1.FT_MARKETING_B2B_EXIT = 0
    AND T_2.FT_CLIENT_360 > 1
    --AND T_3.USER_CONTRACT_TYPE > 1 
    , 'OK'
    , 'NOK'
)
FROM
(SELECT COUNT(*) FT_MARKETING_B2B_EXIT FROM MON.SPARK_FT_MARKETING_B2B WHERE EVENT_DATE='###SLICE_VALUE###') T_1,
(SELECT COUNT(*) FT_CLIENT_360 FROM MON.SPARK_FT_CLIENT_360 WHERE EVENT_DATE='###SLICE_VALUE###') T_2
--(SELECT COUNT(*) USER_CONTRACT_TYPE FROM MON.SPARK_DT_USER_CONTRACT_TYPE WHERE PROCESSING_DATE='###SLICE_VALUE###') T_3