SELECT IF(
    A.nb_ft_susp > 0
    AND B.NB_EXPORT < 1
    , "OK"
    , "NOK"
)
FROM
(SELECT COUNT(*) nb_ft_susp FROM MON.SPARK_FT_SUSPENSIONS_TELCO WHERE event_date  = '###SLICE_VALUE###') A,
(SELECT COUNT(*) NB_EXPORT FROM
(SELECT * FROM (SELECT * FROM MON.EXPORT_HISTORY WHERE EVENT_DATE='###SLICE_VALUE###' AND JOB_INSTANCEID='LOAD_EXPORT_SPARK_FT_SUSPENSION_TELCO' ORDER BY INSERT_DATE DESC LIMIT 1)  T where T.STATUS = 'OK') M
) B
