SELECT IF(FT_ACCOUNT_ACTIVITY>0  AND FT_GROUP_USER_BASE=0, 'OK','NOK') STATUT FROM
(SELECT COUNT(*) FT_GROUP_USER_BASE FROM MON.SPARK_FT_GROUP_USER_BASE WHERE EVENT_DATE='###SLICE_VALUE###')A,
(SELECT COUNT(*) FT_ACCOUNT_ACTIVITY FROM MON.SPARK_FT_ACCOUNT_ACTIVITY WHERE EVENT_DATE='###SLICE_VALUE###')B