CREATE TABLE MON.SPARK_FT_STKAPRIM_REFILL_TYPE(
STKAPRIM VARCHAR(50),
PARTENAIRE VARCHAR(75),
TYPE_EVENT VARCHAR(50),
EVENT_SIMPLIFIE VARCHAR(50),
AMOUNT BIGINT,
COMMISSION BIGINT,
CAPILARITE BIGINT,
CAPAT_CUMUL BIGINT,
SOURCE VARCHAR(50),
INSERT_DATE TIMESTAMP,
REFILL_DATE DATE
)
STORED AS PARQUET TBLPROPERTIES ('PARQUET.COMPRESS'='SNAPPY')