CREATE TABLE TMP.TT_STKAPRIM_REFILL_TYPE(
STKAPRIM VARCHAR(25),
TYPE_EVENT VARCHAR(12),
EVENT_SIMPLIFIE VARCHAR(5),
AMOUNT BIGINT,
SOURCE VARCHAR(50),
REFILL_DATE DATE
)
STORED AS PARQUET TBLPROPERTIES ('PARQUET.COMPRESS'='SNAPPY')