CREATE TABLE IF NOT EXISTS CDR.SPARK_IT_OMNY_OPERATOR_BALANCE (
MSISDN VARCHAR(25),
USER_ID  VARCHAR(100),
LAST_TRANSFER_ID  VARCHAR(100),
LAST_TRANSFER_ON  DATE,
BALANCE  DECIMAL(17,2),
WALLET_SEQUENCE_NUMBER  DECIMAL(17,2),
USER_TYPE  VARCHAR(25),
STATUS VARCHAR(5),
ORIGINAL_FILE_NAME VARCHAR(50),
ORIGINAL_FILE_SIZE INT,
ORIGINAL_FILE_LINE_COUNT INT,
INSERT_DATE TIMESTAMP
)
PARTITIONED BY (ORIGINAL_FILE_DATE DATE)
CLUSTERED BY(USER_ID) INTO 8 BUCKETS
STORED AS PARQUET TBLPROPERTIES ('PARQUET.COMPRESS'='SNAPPY')