CREATE TABLE CDR.IT_OMNY_GRADE_DETAILS (
ORIGINAL_FILE_NAME     VARCHAR(50),
ORIGINAL_FILE_SIZE     INT,
ORIGINAL_FILE_LINE_COUNT INT,
GRADE_CODE           VARCHAR(10),
GRADE_NAME           VARCHAR(40),
CATEGORY_CODE        VARCHAR(10),
STATUS               VARCHAR(5),
INSERT_DATE               TIMESTAMP
)
PARTITIONED BY (ORIGINAL_FILE_DATE DATE)
CLUSTERED BY(GRADE_CODE) INTO 8 BUCKETS
STORED AS ORC
TBLPROPERTIES ('transactional'='true',"orc.compress"="ZLIB","orc.stripe.size"="67108864");

