CREATE TABLE CDR.SPARK_IT_OMNY_BalanceSubscribers(
ORIGINAL_FILE_NAME          VARCHAR(50),
ORIGINAL_FILE_SIZE          INT,
ORIGINAL_FILE_LINE_COUNT    INT,
CATEGORY_CODE               VARCHAR(30),
USER_ID                     VARCHAR(30),
WALLET_NUMBER               VARCHAR(30),
MSISDN                      VARCHAR(30),
PARENT_USER_ID              VARCHAR(30),
PARENT_MSISDN               VARCHAR(30),
OWNER_USER_ID               VARCHAR(30),
OWNER_MSISDN                VARCHAR(30),
OPENING_BALANCE             DECIMAL(17,2),
CLOSING_BALANCE             DECIMAL(17,2),
AMT_TRANS_OUT               DECIMAL(17,2),
NB_TRANS_OUT                BIGINT,
AMT_TRANS_IN                DECIMAL(17,2),
NB_TRANS_IN                 BIGINT,
AMT_TRANS_REIMB_OUT         DECIMAL(17,2),
NB_TRANS_REIMB_OUT          BIGINT,
AMT_TRANS_REIMB_IN          DECIMAL(17,2),
NB_TRANS_REIMB_IN           BIGINT,
AMT_SC_OUT                  DECIMAL(17,2),
NB_SC_OUT                   BIGINT,
AMT_SC_IN                   DECIMAL(17,2),
NB_SC_IN                    BIGINT,
AMT_COM_OUT                 DECIMAL(17,2),
NB_COM_OUT                  BIGINT,
AMT_COM_IN                  DECIMAL(17,2),
NB_COM_IN                   BIGINT,
AMT_COM_REIMB_OUT           DECIMAL(17,2),
NB_COM_REIMB_OUT            BIGINT,
AMT_COM_REIMB_IN            DECIMAL(17,2),
NB_COM_REIMB_IN             BIGINT,
AMT_COM_OUT_OTHER           DECIMAL(17,2),
NB_COM_OUT_OTHER            BIGINT,
AMT_COM_IN_OTHER            DECIMAL(17,2),
NB_COM_IN_OTHER             BIGINT,
AMT_COM_REIMB_OUT_OTHER     DECIMAL(17,2),
NB_COM_REIMB_OUT_OTHER      BIGINT,
AMT_COM_REIMB_IN_OTHER      DECIMAL(17,2),
NB_COM_REIMB_IN_OTHER       BIGINT,
NB_NONFIN_TRANS             BIGINT,
NB_NONFIN_TRANS_CANCELLED   BIGINT,
AMT_SC_NONFIN_OUT           DECIMAL(17,2),
NB_SC_NONFIN_OUT            BIGINT,
AMT_SC_NONFIN_IN            DECIMAL(17,2),
NB_SC_NONFIN_IN             BIGINT,
AMT_COM_NONFIN_OUT          DECIMAL(17,2),
NB_COM_NONFIN_OUT           BIGINT,
AMT_COM_NONFIN_IN           DECIMAL(17,2),
NB_COM_NONFIN_IN            BIGINT,
AMT_TOTAL_OUT               DECIMAL(17,2),
NB_TOTAL_OUT                BIGINT,
AMT_TOTAL_IN                DECIMAL(17,2),
NB_TOTAL_IN                 BIGINT,
INSERT_DATE                  TIMESTAMP
)
PARTITIONED BY (ORIGINAL_FILE_DATE DATE)
CLUSTERED BY(CATEGORY_CODE) INTO 8 BUCKETS
STORED AS PARQUET TBLPROPERTIES ('PARQUET.COMPRESS'='SNAPPY');


---Staging table in DWH
CREATE TABLE MON.SQ_IT_OMNY_BALANCE_SUBS (
  CATEGORY_CODE                 VARCHAR(50),
  PARTY_ID                  VARCHAR(50),
  WALLET_NUMBER             VARCHAR(50),
  MSISDN                    VARCHAR(25),
  PARENT_USER_ID            VARCHAR(25),
  PARENT_MSISDN             VARCHAR(25),
  OWNER_USER_ID             VARCHAR(20),
  OWNER_MSISDN              VARCHAR(25),
  OPENING_BALANCE            NUMBER,
  CLOSING_BALANCE            NUMBER,
  AMT_TRANS_OUT              NUMBER,
  NB_TRANS_OUT               NUMBER,
  AMT_TRANS_IN               NUMBER,
  NB_TRANS_IN                NUMBER,
  AMT_TRANS_REIMB_OUT        NUMBER,
  NB_TRANS_REIMB_OUT         NUMBER,
  AMT_TRANS_REIMB_IN         NUMBER,
  NB_TRANS_REIMB_IN          NUMBER,
  AMT_SC_OUT                 NUMBER,
  NB_SC_OUT                  NUMBER,
  AMT_SC_IN                  NUMBER,
  NB_SC_IN                   NUMBER,
  AMT_COM_OUT                NUMBER,
  NB_COM_OUT                 NUMBER,
  AMT_COM_IN                 NUMBER,
  NB_COM_IN                  NUMBER,
  AMT_COM_REIMB_OUT          NUMBER,
  NB_COM_REIMB_OUT           NUMBER,
  AMT_COM_REIMB_IN           NUMBER,
  NB_COM_REIMB_IN            NUMBER,
  AMT_COM_OUT_OTHER          NUMBER,
  NB_COM_OUT_OTHER           NUMBER,
  AMT_COM_IN_OTHER           NUMBER,
  NB_COM_IN_OTHER            NUMBER,
  AMT_COM_REIMB_OUT_OTHER    NUMBER,
  NB_COM_REIMB_OUT_OTHER     NUMBER,
  AMT_COM_REIMB_IN_OTHER     NUMBER,
  NB_COM_REIMB_IN_OTHER      NUMBER,
  NB_NONFIN_TRANS            NUMBER,
  NB_NONFIN_TRANS_CANCELLED  NUMBER,
  AMT_SC_NONFIN_OUT          NUMBER,
  NB_SC_NONFIN_OUT           NUMBER,
  AMT_SC_NONFIN_IN           NUMBER,
  NB_SC_NONFIN_IN            NUMBER,
  AMT_COM_NONFIN_OUT         NUMBER,
  NB_COM_NONFIN_OUT          NUMBER,
  AMT_COM_NONFIN_IN          NUMBER,
  NB_COM_NONFIN_IN           NUMBER,
  AMT_OUT                    NUMBER,
  NB_OUT                     NUMBER,
  AMT_IN                     NUMBER,
  NB_IN                     VARCHAR(100),
  ORIGINAL_FILE_NAME        VARCHAR(100),
  ORIGINAL_FILE_DATE         DATE,
  INSERT_DATE                DATE
);




---Staging table in data lake
CREATE TABLE TMP.SQ_IT_OMNY_BALANCE_SUBS(
  CATEGORY_CODE                 VARCHAR(50),
  PARTY_ID                  VARCHAR(50),
  WALLET_NUMBER             VARCHAR(50),
  MSISDN                    VARCHAR(25),
  PARENT_USER_ID            VARCHAR(25),
  PARENT_MSISDN             VARCHAR(25),
  OWNER_USER_ID             VARCHAR(20),
  OWNER_MSISDN              VARCHAR(25),
  OPENING_BALANCE           decimal(17,2),
  CLOSING_BALANCE           decimal(17,2),
  AMT_TRANS_OUT             decimal(17,2),
  NB_TRANS_OUT              BIGINT,
  AMT_TRANS_IN              decimal(17,2),
  NB_TRANS_IN               BIGINT,
  AMT_TRANS_REIMB_OUT       decimal(17,2),
  NB_TRANS_REIMB_OUT        BIGINT,
  AMT_TRANS_REIMB_IN        decimal(17,2),
  NB_TRANS_REIMB_IN         BIGINT,
  AMT_SC_OUT                decimal(17,2),
  NB_SC_OUT                 BIGINT,
  AMT_SC_IN                 decimal(17,2),
  NB_SC_IN                  BIGINT,
  AMT_COM_OUT               decimal(17,2),
  NB_COM_OUT                BIGINT,
  AMT_COM_IN                decimal(17,2),
  NB_COM_IN                 BIGINT,
  AMT_COM_REIMB_OUT         decimal(17,2),
  NB_COM_REIMB_OUT          BIGINT,
  AMT_COM_REIMB_IN          decimal(17,2),
  NB_COM_REIMB_IN           BIGINT,
  AMT_COM_OUT_OTHER         decimal(17,2),
  NB_COM_OUT_OTHER          BIGINT,
  AMT_COM_IN_OTHER          decimal(17,2),
  NB_COM_IN_OTHER           BIGINT,
  AMT_COM_REIMB_OUT_OTHER   decimal(17,2),
  NB_COM_REIMB_OUT_OTHER    BIGINT,
  AMT_COM_REIMB_IN_OTHER    decimal(17,2),
  NB_COM_REIMB_IN_OTHER     BIGINT,
  NB_NONFIN_TRANS           BIGINT,
  NB_NONFIN_TRANS_CANCELLED BIGINT,
  AMT_SC_NONFIN_OUT         decimal(17,2),
  NB_SC_NONFIN_OUT          BIGINT,
  AMT_SC_NONFIN_IN          decimal(17,2),
  NB_SC_NONFIN_IN           BIGINT,
  AMT_COM_NONFIN_OUT        decimal(17,2),
  NB_COM_NONFIN_OUT         BIGINT,
  AMT_COM_NONFIN_IN         decimal(17,2),
  NB_COM_NONFIN_IN          BIGINT,
  AMT_OUT                   decimal(17,2),
  NB_OUT                    BIGINT,
  AMT_IN                    decimal(17,2),
  NB_IN                     BIGINT,
  ORIGINAL_FILE_NAME        VARCHAR(100),
  ORIGINAL_FILE_DATE         DATE,
  INSERT_DATE                TIMESTAMP
);


DECLARE 
  SAMPLE_TABLE VARCHAR2(200); MIN_DATE_PARTITION VARCHAR2(200); MAX_DATE_PARTITION VARCHAR2(200);  KEY_COLUMN_PART_NAME VARCHAR2(200);
  KEY_COLUMN_PART_TYPE VARCHAR2(200);   PART_OWNER VARCHAR2(200);  PART_TABLE_NAME VARCHAR2(200);  PART_PARTITION_NAME VARCHAR2(200);
  PART_TYPE_PERIODE VARCHAR2(200);  PART_RETENTION NUMBER;  PART_TBS_CIBLE VARCHAR2(200);  PART_GARDER_01_DU_MOIS VARCHAR2(200);
PART_PCT_FREE NUMBER;   PART_COMPRESSION VARCHAR2(200);  PART_ROTATION_ACTIVE VARCHAR2(200);  PART_FORMAT VARCHAR2(200);
BEGIN 
  SAMPLE_TABLE := 'MON.SQ_IT_OMNY_BALANCE_SUBS';
  MIN_DATE_PARTITION := '20220101';
  MAX_DATE_PARTITION := '20250101';
  KEY_COLUMN_PART_NAME := 'ORIGINAL_FILE_DATE';
  KEY_COLUMN_PART_TYPE := 'JOUR';
  PART_OWNER := 'MON';
  PART_TABLE_NAME := 'IT_OMNY_BALANCE_SUBS';
  PART_PARTITION_NAME := 'IT_OMNY_BALANCE_SUBS_';
  PART_TYPE_PERIODE := 'JOUR';
  PART_RETENTION := 1000;
  PART_TBS_CIBLE :=  'TAB_P_MON_J01_256M';
  PART_GARDER_01_DU_MOIS := 'NON';
  PART_PCT_FREE := 0;
  PART_COMPRESSION := 'COMPRESS';
  PART_ROTATION_ACTIVE := 'OUI';
  PART_FORMAT := 'yyyymmdd';
  MON.CREATE_PARTITIONED_TABLE ( SAMPLE_TABLE, MIN_DATE_PARTITION, MAX_DATE_PARTITION, KEY_COLUMN_PART_NAME, KEY_COLUMN_PART_TYPE, PART_OWNER, PART_TABLE_NAME, PART_PARTITION_NAME, PART_TYPE_PERIODE, PART_RETENTION, PART_TBS_CIBLE, PART_GARDER_01_DU_MOIS, PART_PCT_FREE, PART_COMPRESSION, PART_ROTATION_ACTIVE, PART_FORMAT );
  COMMIT; 
END;