
CREATE TABLE CDR.SPARK_IT_OM_NEW_SUBSCRIBER_TRANSACTIONS_STATS

(
    MSISDN	VARCHAR(15),
    CREATION_DATE	TIMESTAMP,
    NB_OPERATIONS INT,
    NB_SERVICES_DISTINCTS INT,
    SOLDE_DEBUT_MOIS FLOAT ,
    SOLDE_FIN_MOIS FLOAT


)



STORED AS PARQUET TBLPROPERTIES ('PARQUET.COMPRESS'='SNAPPY');
