INSERT INTO CDR.SPARK_IT_VALIDATION_CGU_USSD
SELECT
    MSISDN,
    DATE_VALIDATION,
    ORIGINAL_FILE_NAME,
    ORIGINAL_FILE_SIZE,
    ORIGINAL_FILE_LINE_COUNT,
    TO_DATE(FROM_UNIXTIME(UNIX_TIMESTAMP(SUBSTRING (ORIGINAL_FILE_NAME, -14, 10),'yyyy-MM-dd'))) ORIGINAL_FILE_DATE,
    CURRENT_TIMESTAMP() INSERT_DATE,
    TO_DATE(FROM_UNIXTIME(UNIX_TIMESTAMP(SUBSTRING (ORIGINAL_FILE_NAME, -14, 10),'yyyy-MM-dd'))) FILE_DATE
FROM CDR.SPARK_TT_VALIDATION_CGU_USSD C
LEFT JOIN (SELECT DISTINCT ORIGINAL_FILE_NAME FILE_NAME FROM CDR.SPARK_IT_VALIDATION_CGU_USSD WHERE FILE_DATE BETWEEN DATE_SUB(CURRENT_DATE,7) AND CURRENT_DATE )T ON T.FILE_NAME = C.ORIGINAL_FILE_NAME
WHERE T.FILE_NAME IS NULL
