SELECT IF(A.CNI_EXPIREES = 0 AND B.FT_BDI >0 ,"OK","NOK") FROM
(SELECT COUNT(*) CNI_EXPIREES FROM MON.SPARK_FT_CNI_EXPIREES WHERE EVENT_DATE= '###SLICE_VALUE###') A,
(SELECT COUNT(*) FT_BDI FROM MON.SPARK_FT_KYC_BDI_PP WHERE EVENT_DATE= '###SLICE_VALUE###') B
