SELECT IF(A.CNI_EXPIREES = 0 AND B.FT_BDI >0 and C.BDI_CRM_B2C > 0 ,"OK","NOK") FROM
(SELECT COUNT(*) CNI_EXPIREES FROM MON.SPARK_FT_CNI_EXPIREES WHERE EVENT_DATE= '###SLICE_VALUE###') A,
(SELECT COUNT(*) FT_BDI FROM MON.SPARK_FT_BDI WHERE EVENT_DATE= '###SLICE_VALUE###') B,
(SELECT COUNT(*) BDI_CRM_B2C FROM MON.SPARK_FT_BDI_CRM_B2C WHERE EVENT_DATE= '###SLICE_VALUE###') C
