INSERT INTO MON.FT_GROUP_SUBSCRIBER_SUMMARY PARTITION(EVENT_DATE)
SELECT
  PROFILE
  , STATUT
  , ETAT
  , BSCS_COMM_OFFER
  , TRANCHE_AGE
  , CUST_BILLCYCLE
  , CREDIT
  , EFFECTIF
  , ACTIVATIONS
  , RESILIATIONS
  , SRC_TABLE
  , INSERT_DATE
  , PLATFORM_STATUS
  , NULL EFFECTIF_CLIENTS_OCM
  , NULL DECONNEXIONS
  , NULL CONNEXIONS
  , NULL RECONNEXIONS
  , NVL (B.OPERATOR_CODE, 'OCM') OPERATOR_CODE
  , EVENT_DATE
FROM (
      -- ajouter les données ICC =>  prepaid et hybride :
  SELECT
    UPPER (a.PROFILE) PROFILE
    , NVL (b.GP_STATUS, 'INACT') STATUT
     , NULL ETAT
     , UPPER (b.BSCS_COMM_OFFER) BSCS_COMM_OFFER
     , ROUND (
          CASE
              WHEN (a.ACTIVATION_DATE IS NULL) OR (a.ACTIVATION_DATE < TO_DATE(FROM_UNIXTIME(UNIX_TIMESTAMP('19880101','yyyyMMdd')))) THEN 0
              WHEN  DATEDIFF('###SLICE_VALUE###', a.ACTIVATION_DATE)-1  < 0 THEN 0
              WHEN  DATEDIFF('###SLICE_VALUE###', a.ACTIVATION_DATE)-1 > 365
                      THEN ROUND  ((DATEDIFF('###SLICE_VALUE###',DATE_FORMAT(a.ACTIVATION_DATE,'yyyy-MM-dd') )-1)/(12 * 30.4375) )*12
              ELSE (DATEDIFF('###SLICE_VALUE###',DATE_FORMAT(a.ACTIVATION_DATE,'yyyy-MM-dd') )-1)/30.4375
          END
      ) TRANCHE_AGE
     , SUM ((CASE WHEN MAIN_CREDIT IS NULL THEN 0 WHEN MAIN_CREDIT < 0 THEN 0 ELSE MAIN_CREDIT END )
            + (CASE WHEN PROMO_CREDIT IS NULL THEN 0 WHEN PROMO_CREDIT < 0 THEN 0 ELSE PROMO_CREDIT END ) ) CREDIT
     , SUM (1) EFFECTIF
     , SUM (IF(a.ACTIVATION_DATE=DATE_SUB('###SLICE_VALUE###',1),1,0)) ACTIVATIONS
     , SUM (IF(a.DEACTIVATION_DATE=DATE_SUB('###SLICE_VALUE###',1),1,0)) RESILIATIONS
     , a.SRC_TABLE
     , CURRENT_TIMESTAMP INSERT_DATE
     , NVL (a.OSP_CONTRACT_TYPE, 'PURE PREPAID' ) CUST_BILLCYCLE
     , a.OSP_STATUS PLATFORM_STATUS
     , '###SLICE_VALUE###' EVENT_DATE
    FROM MON.FT_CONTRACT_SNAPSHOT a
  LEFT JOIN (
    SELECT * FROM AGG.FT_ACCOUNT_ACTIVITY
    WHERE
    EVENT_DATE = '###SLICE_VALUE###'
  ) b ON a.ACCESS_KEY = b.MSISDN
  WHERE
      a.EVENT_DATE = '###SLICE_VALUE###'
      AND NVL (a.OSP_CONTRACT_TYPE, 'PURE PREPAID' ) IN ('PURE PREPAID', 'HYBRID')
  GROUP BY
       UPPER (a.PROFILE)
      , NVL (b.GP_STATUS, 'INACT')
      , UPPER (b.BSCS_COMM_OFFER)
      , ROUND (
          CASE
              WHEN (a.ACTIVATION_DATE IS NULL) OR (a.ACTIVATION_DATE < TO_DATE(FROM_UNIXTIME(UNIX_TIMESTAMP('19880101','yyyyMMdd')))) THEN 0
              WHEN  DATEDIFF('###SLICE_VALUE###', a.ACTIVATION_DATE)-1  < 0 THEN 0
              WHEN  DATEDIFF('###SLICE_VALUE###', a.ACTIVATION_DATE)-1 > 365
                      THEN ROUND  ((DATEDIFF('###SLICE_VALUE###',DATE_FORMAT(a.ACTIVATION_DATE,'yyyy-MM-dd') )-1)/(12 * 30.4375) )*12
              ELSE (DATEDIFF('###SLICE_VALUE###',DATE_FORMAT(a.ACTIVATION_DATE,'yyyy-MM-dd') )-1)/30.4375
          END
      )
      , a.SRC_TABLE, NVL (a.OSP_CONTRACT_TYPE, 'PURE PREPAID' ), a.OSP_STATUS

  UNION ALL
  -- Ajout des MSISDN ACTIF ayant disparu de la photo
  SELECT
    UPPER (b.FORMULE) PROFILE
    , NVL (b.GP_STATUS, 'INACT') STATUT
    , NULL ETAT
    , UPPER (b.BSCS_COMM_OFFER) BSCS_COMM_OFFER
    , ROUND (
        CASE
            WHEN (DATE_FORMAT(b.ACTIVATION_DATE,'yyyy-MM-dd') IS NULL) OR (DATE_FORMAT(b.ACTIVATION_DATE,'yyyy-MM-dd') < TO_DATE(FROM_UNIXTIME(UNIX_TIMESTAMP('19880101','yyyyMMdd')))) THEN 0
            WHEN  DATEDIFF('###SLICE_VALUE###',DATE_FORMAT(b.ACTIVATION_DATE,'yyyy-MM-dd') )-1 < 0 THEN 0
            WHEN  DATEDIFF('###SLICE_VALUE###',DATE_FORMAT(b.ACTIVATION_DATE,'yyyy-MM-dd') )-1 > 365
                    THEN ROUND  ((DATEDIFF('###SLICE_VALUE###',DATE_FORMAT(b.ACTIVATION_DATE,'yyyy-MM-dd') )-1)/(12 * 30.4375) )*12
            ELSE (DATEDIFF('###SLICE_VALUE###',DATE_FORMAT(b.ACTIVATION_DATE,'yyyy-MM-dd') )-1)/30.4375
        END
    ) TRANCHE_AGE
     , 0 CREDIT
     , SUM (1) EFFECTIF
     , SUM (IF(DATE_FORMAT(b.ACTIVATION_DATE,'yyyy-MM-dd')=DATE_SUB('###SLICE_VALUE###',1),1,0)) ACTIVATIONS
     , SUM (IF(b.RESILIATION_DATE=DATE_SUB('###SLICE_VALUE###',1),1,0)) RESILIATIONS
     , b.SRC_TABLE
     , CURRENT_TIMESTAMP INSERT_DATE
     , NVL (UPPER(d.CONTRACT_TYPE), 'PURE PREPAID' ) CUST_BILLCYCLE
     , b.PLATFORM_STATUS PLATFORM_STATUS
     , '###SLICE_VALUE###' EVENT_DATE
  FROM AGG.FT_ACCOUNT_ACTIVITY b
  LEFT JOIN (
    SELECT
      a.MSISDN
    FROM AGG.FT_ACCOUNT_ACTIVITY a
    LEFT JOIN (SELECT access_key MSISDN FROM MON.FT_CONTRACT_SNAPSHOT WHERE EVENT_DATE = '###SLICE_VALUE###') b ON a.MSISDN=b.MSISDN
    WHERE a.EVENT_DATE = '###SLICE_VALUE###' AND NVL (GP_STATUS, 'INACT')='ACTIF' AND b.MSISDN IS NULL
  ) c ON b.MSISDN = c.MSISDN
  LEFT JOIN DIM.DT_OFFER_PROFILES d ON b.FORMULE=d.PROFILE_CODE
  WHERE b.EVENT_DATE = '###SLICE_VALUE###'
      AND NVL (UPPER(d.CONTRACT_TYPE), 'PURE PREPAID' ) IN ('PURE PREPAID', 'HYBRID')
      AND c.MSISDN IS NOT NULL
      --AND ROWNUM < nb_to_inject -- injection petit à petit :: 2.000 par jour à partir du 20/04/2014
  GROUP BY
       UPPER (b.FORMULE)
      , NVL (b.GP_STATUS, 'INACT')
      , UPPER (b.BSCS_COMM_OFFER)
      , ROUND (
            CASE
              WHEN (DATE_FORMAT(b.ACTIVATION_DATE,'yyyy-MM-dd') IS NULL) OR (DATE_FORMAT(b.ACTIVATION_DATE,'yyyy-MM-dd') < TO_DATE(FROM_UNIXTIME(UNIX_TIMESTAMP('19880101','yyyyMMdd')))) THEN 0
              WHEN  DATEDIFF('###SLICE_VALUE###',DATE_FORMAT(b.ACTIVATION_DATE,'yyyy-MM-dd') )-1 < 0 THEN 0
              WHEN  DATEDIFF('###SLICE_VALUE###',DATE_FORMAT(b.ACTIVATION_DATE,'yyyy-MM-dd') )-1 > 365
                      THEN ROUND  ((DATEDIFF('###SLICE_VALUE###',DATE_FORMAT(b.ACTIVATION_DATE,'yyyy-MM-dd') )-1)/(12 * 30.4375) )*12
              ELSE (DATEDIFF('###SLICE_VALUE###',DATE_FORMAT(b.ACTIVATION_DATE,'yyyy-MM-dd') )-1)/30.4375
          END
      )
      , b.SRC_TABLE, NVL (UPPER(d.CONTRACT_TYPE), 'PURE PREPAID' ), b.PLATFORM_STATUS

  UNION ALL

  -- ajouter les données des postpaid : pure postpaid seulement car les hybrides ont été compté (puisque present à l'IN)
  SELECT
   UPPER (a.PROFILE) PROFILE --UPPER (NVL  ( SUBSTR(a.BSCS_COMM_OFFER, INSTR(a.BSCS_COMM_OFFER,'|',1,1)+1), a.OSP_CUSTOMER_FORMULE) ) PROFILE
   ,  (CASE
        WHEN  a.CURRENT_STATUS IN  ('a', 's')  THEN 'ACTIF'
        ELSE    'INACT'
     END) STATUT
   , NULL ETAT
   , UPPER (b.BSCS_COMM_OFFER) BSCS_COMM_OFFER
   , ROUND (
        CASE
            WHEN (a.ACTIVATION_DATE IS NULL) OR (a.ACTIVATION_DATE < TO_DATE(FROM_UNIXTIME(UNIX_TIMESTAMP('19880101','yyyyMMdd')))) THEN 0
            WHEN  DATEDIFF('###SLICE_VALUE###',DATE_FORMAT(a.ACTIVATION_DATE,'yyyy-MM-dd') )-1 < 0 THEN 0
            WHEN  DATEDIFF('###SLICE_VALUE###',DATE_FORMAT(a.ACTIVATION_DATE,'yyyy-MM-dd') )-1 > 365
                    THEN ROUND  ((DATEDIFF('###SLICE_VALUE###',DATE_FORMAT(a.ACTIVATION_DATE,'yyyy-MM-dd'))-1)/(12 * 30.4375) )*12
            ELSE (DATEDIFF('###SLICE_VALUE###',DATE_FORMAT(a.ACTIVATION_DATE,'yyyy-MM-dd') )-1)/30.4375
        END
    ) TRANCHE_AGE
   , SUM ((CASE WHEN MAIN_CREDIT IS NULL THEN 0 WHEN MAIN_CREDIT < 0 THEN 0 ELSE MAIN_CREDIT END )
          + (CASE WHEN PROMO_CREDIT IS NULL THEN 0 WHEN PROMO_CREDIT < 0 THEN 0 ELSE PROMO_CREDIT END ) ) CREDIT
   , SUM (1) EFFECTIF
   , SUM (IF(a.BSCS_ACTIVATION_DATE=DATE_SUB('###SLICE_VALUE###',1),1,0)) ACTIVATIONS
   , SUM (IF(a.BSCS_DEACTIVATION_DATE=DATE_SUB('###SLICE_VALUE###',1),1,0)) RESILIATIONS
   , 'FT_BSCS_CONTRACT' SRC_TABLE
   , CURRENT_TIMESTAMP INSERT_DATE
   , NVL (a.OSP_CONTRACT_TYPE, 'PURE PREPAID' ) CUST_BILLCYCLE
   , CASE
        WHEN NVL(a.CURRENT_STATUS, a.OSP_STATUS)='ACTIVE' THEN 'ACTIF'
        WHEN NVL(a.CURRENT_STATUS, a.OSP_STATUS)='a' THEN 'ACTIF'
        WHEN NVL(a.CURRENT_STATUS, a.OSP_STATUS)='d' THEN 'DEACT'
        WHEN NVL(a.CURRENT_STATUS, a.OSP_STATUS)='s' THEN 'INACT'
        WHEN NVL(a.CURRENT_STATUS, a.OSP_STATUS)='s' THEN 'INACT'
        WHEN NVL(a.CURRENT_STATUS, a.OSP_STATUS)='DEACTIVATED' THEN 'DEACT'
        WHEN NVL(a.CURRENT_STATUS, a.OSP_STATUS)='INACTIVE' THEN 'INACT'
        WHEN NVL(a.CURRENT_STATUS, a.OSP_STATUS)='VALID' THEN 'VALIDE'
        ELSE NVL(a.CURRENT_STATUS, a.OSP_STATUS)
    END PLATFORM_STATUS
   , '###SLICE_VALUE###' EVENT_DATE
  FROM MON.FT_CONTRACT_SNAPSHOT a
  LEFT JOIN (
    SELECT * FROM AGG.FT_ACCOUNT_ACTIVITY  WHERE EVENT_DATE = '###SLICE_VALUE###'
   ) b ON a.ACCESS_KEY = b.MSISDN
  WHERE -- ROWNUM < 1 AND
      a.EVENT_DATE = '###SLICE_VALUE###'
      --AND a.SRC_TABLE = 'IT_ICC_ACCOUNT'
      AND NVL (a.OSP_CONTRACT_TYPE, 'PURE PREPAID' ) = 'PURE POSTPAID'
  GROUP BY
       UPPER (a.PROFILE)--UPPER (NVL  ( SUBSTR(a.BSCS_COMM_OFFER, INSTR(a.BSCS_COMM_OFFER,'|',1,1)+1), a.OSP_CUSTOMER_FORMULE) )
      , CASE
          WHEN  a.CURRENT_STATUS IN  ('a', 's')  THEN 'ACTIF'
          ELSE    'INACT'
       END
      , UPPER (b.BSCS_COMM_OFFER)
      , ROUND (
          CASE
              WHEN (a.ACTIVATION_DATE IS NULL) OR (a.ACTIVATION_DATE < TO_DATE(FROM_UNIXTIME(UNIX_TIMESTAMP('19880101','yyyyMMdd')))) THEN 0
              WHEN  DATEDIFF('###SLICE_VALUE###',DATE_FORMAT(a.ACTIVATION_DATE,'yyyy-MM-dd') )-1 < 0 THEN 0
              WHEN  DATEDIFF('###SLICE_VALUE###',DATE_FORMAT(a.ACTIVATION_DATE,'yyyy-MM-dd') )-1 > 365
                      THEN ROUND  ((DATEDIFF('###SLICE_VALUE###',DATE_FORMAT(a.ACTIVATION_DATE,'yyyy-MM-dd'))-1)/(12 * 30.4375) )*12
              ELSE (DATEDIFF('###SLICE_VALUE###',DATE_FORMAT(a.ACTIVATION_DATE,'yyyy-MM-dd') )-1)/30.4375
          END
      )
      , NVL (a.OSP_CONTRACT_TYPE, 'PURE PREPAID' )
      , CASE
          WHEN NVL(a.CURRENT_STATUS, a.OSP_STATUS)='ACTIVE' THEN 'ACTIF'
          WHEN NVL(a.CURRENT_STATUS, a.OSP_STATUS)='a' THEN 'ACTIF'
          WHEN NVL(a.CURRENT_STATUS, a.OSP_STATUS)='d' THEN 'DEACT'
          WHEN NVL(a.CURRENT_STATUS, a.OSP_STATUS)='s' THEN 'INACT'
          WHEN NVL(a.CURRENT_STATUS, a.OSP_STATUS)='s' THEN 'INACT'
          WHEN NVL(a.CURRENT_STATUS, a.OSP_STATUS)='DEACTIVATED' THEN 'DEACT'
          WHEN NVL(a.CURRENT_STATUS, a.OSP_STATUS)='INACTIVE' THEN 'INACT'
          WHEN NVL(a.CURRENT_STATUS, a.OSP_STATUS)='VALID' THEN 'VALIDE'
          ELSE NVL(a.CURRENT_STATUS, a.OSP_STATUS)
      END
) a
LEFT JOIN DIM.DT_OFFER_PROFILES b ON  UPPER (a.PROFILE) = b.PROFILE_CODE
WHERE STATUT='ACTIF'