create table MON.FT_GROUP_DISCONNECT_DAY
(
  PARC_J        BIGINT,
  PARC_PRE      BIGINT,
  PARC_POS      BIGINT,
  NEW_PRE       BIGINT,
  NEW_POS       BIGINT,
  VAR_PARC      BIGINT,
  VAR_PARC_PRE  BIGINT,
  VAR_PARC_POST BIGINT,
  RECONN        BIGINT,
  INSERTED_DATE TIMESTAMP
)PARTITIONED BY (SDATE    DATE)
STORED AS ORC TBLPROPERTIES ("orc.compress"="ZLIB","orc.stripe.size"="67108864")
;