SELECT IF(FT_EXISTS=0 AND FT_CONTRACT_SNAP_EXISTS>0 ,'OK','NOK' )
FROM
(SELECT COUNT(*) FT_EXISTS FROM AGG.FT_A_SUBSCRIBER_SUMMARY WHERE DATECODE=DATE_SUB('###SLICE_VALUE###',1))T1,
(SELECT COUNT(*) FT_CONTRACT_SNAP_EXISTS FROM MON.FT_CONTRACT_SNAPSHOT WHERE EVENT_DATE=DATE_SUB('###SLICE_VALUE###',-1))T2