CREATE TABLE IF NOT EXISTS AGG.SPARK_KPI_RECO_CREANCES (
KPI VARCHAR(50),
VAL   FLOAT,
INSERT_DATE TIMESTAMP
)
COMMENT 'SPARK_KPI_RECO_CREANCES'
PARTITIONED BY (EVENT_MONTH VARCHAR(50))
STORED AS PARQUET TBLPROPERTIES ("parquet.compress"="SNAPPY")