INSERT INTO CTI.SVI_APPEL_SELFCARE
SELECT DISTINCT 
    DATE_DEBUT_OMS as JOUR,
    DATE_FORMAT(DATE_DEBUT_OMS_NQ, 'HH:mm:ss') HEURE,
    (
        CASE WHEN DATE_FORMAT(DATE_DEBUT_OMS_NQ, 'mm')<60 THEN DATE_FORMAT(DATE_DEBUT_OMS_NQ, 'HH')||':00'
        ELSE DATE_FORMAT(DATE_DEBUT_OMS_NQ, 'HH')||':30' 
        END
    ) TRANCHE_HEURE,
    S.ID_APPEL,
    S.MSISDN,
    S.SERVICE AS NUMERO_APPELE,
    S.SEGMENT_CLIENT AS SEGMENT_CLIENT,
    S.TYPE_HANGUP AS TYPE_HANGUP,
    S.DATE_DEBUT_OMS AS DATE_DEBUT_OMS,
    CURRENT_TIMESTAMP() INSERT_DATE,
    DATE_DEBUT_OMS AS EVENT_DATE
FROM 
(
    SELECT 
       * 
    FROM CTI.SVI_APPEL 
    WHERE DATE_DEBUT_OMS = '###SLICE_VALUE###'
) S
LEFT JOIN
(
    SELECT 
        ID_APPEL
    FROM 
    (
        SELECT 
            DISTINCT ID_APPEL 
        FROM CTI.SVI_NAVIGATION A
        LEFT JOIN 
        (
            SELECT DISTINCT MENU FROM CTI.MENU_SELFCARE
        ) B 
        ON UPPER(TRIM(A.ELEMENT)) = UPPER(TRIM(B.MENU))
        WHERE B.MENU IS NOT NULL

        MINUS 

        SELECT 
            DISTINCT ID_APPEL
        FROM CTI.SVI_APP_TRANSFERE
        WHERE JOUR = '###SLICE_VALUE###'
    ) T
) U
ON S.ID_APPEL = U.ID_APPEL
WHERE U.ID_APPEL IS NOT NULL