SELECT IF( 
    T_1.FT_EXIST > 0 
    AND T_2.FT_EXIST > 0
    AND T_21.FT_EXIST > 0
    AND T_22.FT_EXIST > 0
    AND T_3.FT_EXIST > 0
    AND NB_EXPORT < 1
    ,"OK","NOK")
FROM 
(SELECT COUNT(*) FT_EXIST FROM MON.spark_ft_omny_account_snapshot WHERE EVENT_DATE ='###SLICE_VALUE###') T_1,
(SELECT COUNT(*) FT_EXIST FROM MON.SPARK_FT_OM_ACTIVE_USER WHERE EVENT_DATE ='###SLICE_VALUE###') T_2,
(SELECT COUNT(*) FT_EXIST FROM MON.SPARK_FT_OM_ACTIVE_USER WHERE EVENT_DATE = date_sub('###SLICE_VALUE###', 30)) T_21,
(SELECT COUNT(*) FT_EXIST FROM MON.SPARK_FT_OM_ACTIVE_USER WHERE EVENT_DATE = date_sub('###SLICE_VALUE###', 60)) T_22,
(SELECT COUNT(*) FT_EXIST from mon.spark_FT_CONTRACT_SNAPSHOT where EVENT_DATE='###SLICE_VALUE###') T_3,
(select count(*) NB_EXPORT from (select * from (SELECT * FROM MON.EXPORT_HISTORY where event_date='###SLICE_VALUE###' and JOB_INSTANCEID='${hivevar:job_instanceid}' ORDER BY INSERT_DATE DESC LIMIT 1)  T where T.STATUS = 'OK') M) T_3