SELECT IF(
T_1.FT_EXIST = 0 AND
T_2.MSC_TRANSACTION>0
,"OK","NOK") QOS_MSC_TRANSACTION_EXIST
FROM
(SELECT COUNT(*) FT_EXIST FROM MON.SPARK_FT_QOS_MSC_TRANSACTION WHERE TRANSACTION_DATE =TO_DATE('###SLICE_VALUE###')) T_1,
(SELECT COUNT(*) MSC_TRANSACTION FROM MON.SPARK_FT_MSC_TRANSACTION WHERE TRANSACTION_DATE=TO_DATE('###SLICE_VALUE###')) T_2