
CREATE TABLE AGG.FT_A_CREDIT_TRANSFER_REVENUE (
    REFILL_HOUR  VARCHAR(2),
    TERMINATION_IND  VARCHAR(4),
    COMMERCIAL_OFFER VARCHAR(40),
    TRANSFER_COUNT INT,
    TRANSFER_AMOUNT  BIGINT,
    TRANSFER_FEES  BIGINT,
    LAST_UPDATE TIMESTAMP,
    OPERATOR_CODE VARCHAR(25),
    IS_VIP INT
)
PARTITIONED BY (REFILL_DATE  DATE)
STORED AS ORC TBLPROPERTIES ('transactional'='true',"orc.compress"="ZLIB","orc.stripe.size"="67108864")
