CREATE TABLE AGG.SPARK_FT_A_TRAFFIC_ENTRANT_NURAN
(
  SITE_NAME                  VARCHAR(50),
  DUREE_ENTRANT             bigint,
  NBRE_TEL_ENTRANT          bigint,
  NBRE_SMS_ENTRANT          bigint,
  NBRE_TEL_MTN_ENTRANT      bigint,
  NBRE_TEL_CAMTEL_ENTRANT   bigint,
  NBRE_TEL_OCM_ENTRANT      bigint,
  DUREE_TEL_MTN_ENTRANT     bigint,
  DUREE_TEL_CAMTEL_ENTRANT  bigint,
  DUREE_TEL_OCM_ENTRANT     bigint,
  NBRE_SMS_MTN_ENTRANT      bigint,
  NBRE_SMS_CAMTEL_ENTRANT   bigint,
  NBRE_SMS_OCM_ENTRANT      bigint,
  NBRE_SMS_ZEBRA_ENTRANT    bigint,
  NBRE_TEL_NEXTTEL_ENTRANT  bigint,
  DUREE_TEL_NEXTTEL_ENTRANT bigint,
  NBRE_SMS_NEXTTEL_ENTRANT  bigint,
  INSERT_DATE                TIMESTAMP,
  DUREE_TEL_INTERN_ENTRANT bigint,
  NBRE_SMS_INTERN_ENTRANT   bigint

) 
PARTITIONED BY (EVENT_DATE DATE)
STORED AS PARQUET TBLPROPERTIES ('PARQUET.COMPRESS'='SNAPPY');
  
alter table AGG.SPARK_FT_A_TRAFFIC_ENTRANT_NURAN add columns 
(NBRE_TEL_OCM_SHORT_ENTRANT bigint,
NBRE_SMS_OCM_SHORT_SORTANT bigint,
DUREE_TEL_OCM_SHORT_ENTRANT bigint,
DUREE_TEL_OCM_SHORT_SORTANT bigint,
NBRE_TEL_SET_ENTRANT bigint,
NBRE_SMS_SET_SORTANT bigint,
DUREE_TEL_SET_ENTRANT bigint,
NBRE_TEL_SET_SORTANT bigint
)