CREATE EXTERNAL TABLE CDR.tt_kaabu_client_directory (
  ORIGINAL_FILE_NAME VARCHAR(200),
  ORIGINAL_FILE_SIZE INT,
  ORIGINAL_FILE_LINE_COUNT INT,
  NUMERO  VARCHAR(250),
  TYPEDECONTRAT  VARCHAR(250),
  SOURCE  VARCHAR(250),
  TELEPHONE  VARCHAR(250),
  GENDER  VARCHAR(250),
  TITRE  VARCHAR(250),
  PRENOMDUCLIENT  VARCHAR(250),
  NOMDUCLIENT  VARCHAR(250),
  DATEDENAISSANCE  VARCHAR(250),
  LIEUDENAISSANCE  VARCHAR(250),
  PIECE  VARCHAR(250),
  NUMEROPIECE  VARCHAR(250),
  DELIVRANCE  VARCHAR(250),
  EXPIRATION  VARCHAR(250),
  NATIONALITE  VARCHAR(250),
  QUARTIER  VARCHAR(250),
  VILLE  VARCHAR(250),
  LOGINVENDEUR  VARCHAR(250),
  PRENOMVENDEUR  VARCHAR(250),
  NOMVENDEUR  VARCHAR(249),
  NUMERODUVENDEUR  VARCHAR(250),
  LOGINDISTRIBUTEUR  VARCHAR(250),
  PRENOMDISTRIBUTEUR  VARCHAR(250),
  NOMDISTRIBUTEUR  VARCHAR(250),
  EMISLE  VARCHAR(250),
  MAJLE  VARCHAR(250),
  LOGINMAJ  VARCHAR(250),
  PRENOMMAJ  VARCHAR(250),
  NOMMAJ  VARCHAR(250),
  ETAT  VARCHAR(250),
  ETATDEXPORTGLOBAL  VARCHAR(250),
  LOGINVALIDATEUR  VARCHAR(250),
  PRENOMVALIDATEUR  VARCHAR(249),
  NOMVALIDATEUR  VARCHAR(250),
  CAUSEECHEC  VARCHAR(250),
  COMMENTAIRE  VARCHAR(250),
  PWDCLIENT  VARCHAR(250),
  LAST_UPDATE_DATE  VARCHAR(250),
  DELIVRANCE1  VARCHAR(250),
  LIEUDEDELIVRANCE  VARCHAR(250),
  COPIE  VARCHAR(250),
  UPDATE_ON  VARCHAR(250),
  ID  VARCHAR(250),
  PICTURE_LOADED_DATE  VARCHAR(250),
  SOURCE_DONNEES VARCHAR(250)
)
COMMENT 'external tables-TT'
ROW FORMAT DELIMITED FIELDS TERMINATED BY ';'
LOCATION '/PROD/TT/IDENTIFICATION/KAABU_PROD'
TBLPROPERTIES ('serialization.null.format'='')
;


CREATE TABLE CDR.SPARK_IT_KAABU_CLIENT_DIRECTORY
(
  NUMERO              VARCHAR(250),
  TYPEDECONTRAT       VARCHAR(250),
  SOURCE              VARCHAR(250),
  TELEPHONE           VARCHAR(250),
  GENDER              VARCHAR(250),
  TITRE               VARCHAR(250),
  PRENOMDUCLIENT      VARCHAR(250),
  NOMDUCLIENT         VARCHAR(250),
  DATEDENAISSANCE     VARCHAR(250),
  LIEUDENAISSANCE     VARCHAR(250),
  PIECE               VARCHAR(250),
  NUMEROPIECE         VARCHAR(250),
  DELIVRANCE          VARCHAR(250),
  EXPIRATION          VARCHAR(250),
  NATIONALITE         VARCHAR(250),
  QUARTIER            VARCHAR(250),
  VILLE               VARCHAR(250),
  LOGINVENDEUR        VARCHAR(250),
  PRENOMVENDEUR       VARCHAR(250),
  NOMVENDEUR          VARCHAR(249),
  NUMERODUVENDEUR     VARCHAR(250),
  LOGINDISTRIBUTEUR   VARCHAR(250),
  PRENOMDISTRIBUTEUR  VARCHAR(250),
  NOMDISTRIBUTEUR     VARCHAR(250),
  EMISLE              VARCHAR(250),
  MAJLE               VARCHAR(250),
  LOGINMAJ            VARCHAR(250),
  PRENOMMAJ           VARCHAR(250),
  NOMMAJ              VARCHAR(250),
  ETAT                VARCHAR(250),
  ETATDEXPORTGLOBAL   VARCHAR(250),
  LOGINVALIDATEUR     VARCHAR(250),
  PRENOMVALIDATEUR    VARCHAR(249),
  NOMVALIDATEUR       VARCHAR(250),
  CAUSEECHEC          VARCHAR(250),
  COMMENTAIRE         VARCHAR(250),
  PWDCLIENT           VARCHAR(250),
  LAST_UPDATE_DATE    VARCHAR(250),
  DELIVRANCE1         VARCHAR(250),
  LIEUDEDELIVRANCE    VARCHAR(250),
  COPIE               VARCHAR(250),
  UPDATE_ON           VARCHAR(250),
  ID                  VARCHAR(250),
  PICTURE_LOADED_DATE VARCHAR(250),
  SOURCE_DONNEES      VARCHAR(250),
  ORIGINAL_FILE_NAME  VARCHAR(50),
  ORIGINAL_FILE_SIZE  INT,
  ORIGINAL_FILE_LINE_COUNT INT,
  INSERT_DATE TIMESTAMP
   )
  PARTITIONED BY (ORIGINAL_FILE_DATE DATE)
  CLUSTERED BY(NUMERO) INTO 64 BUCKETS
  STORED AS PARQUET TBLPROPERTIES ('PARQUET.COMPRESS'='SNAPPY');


---Staging table in DWH
CREATE TABLE MON.SQ_IT_KAABU_CLIENT (
  NUMERO              VARCHAR(250),
  TYPEDECONTRAT       VARCHAR(250),
  SOURCE              VARCHAR(250),
  TELEPHONE           VARCHAR(250),
  GENDER              VARCHAR(250),
  TITRE               VARCHAR(250),
  PRENOMDUCLIENT      VARCHAR(250),
  NOMDUCLIENT         VARCHAR(250),
  DATEDENAISSANCE     VARCHAR(250),
  LIEUDENAISSANCE     VARCHAR(250),
  PIECE               VARCHAR(250),
  NUMEROPIECE         VARCHAR(250),
  DELIVRANCE          VARCHAR(250),
  EXPIRATION          VARCHAR(250),
  NATIONALITE         VARCHAR(250),
  QUARTIER            VARCHAR(250),
  VILLE               VARCHAR(250),
  LOGINVENDEUR        VARCHAR(250),
  PRENOMVENDEUR       VARCHAR(250),
  NOMVENDEUR          VARCHAR(249),
  NUMERODUVENDEUR     VARCHAR(250),
  LOGINDISTRIBUTEUR   VARCHAR(250),
  PRENOMDISTRIBUTEUR  VARCHAR(250),
  NOMDISTRIBUTEUR     VARCHAR(250),
  EMISLE              VARCHAR(250),
  MAJLE               VARCHAR(250),
  LOGINMAJ            VARCHAR(250),
  PRENOMMAJ           VARCHAR(250),
  NOMMAJ              VARCHAR(250),
  ETAT                VARCHAR(250),
  ETATDEXPORTGLOBAL   VARCHAR(250),
  LOGINVALIDATEUR     VARCHAR(250),
  PRENOMVALIDATEUR    VARCHAR(249),
  NOMVALIDATEUR       VARCHAR(250),
  CAUSEECHEC          VARCHAR(250),
  COMMENTAIRE         VARCHAR(250),
  PWDCLIENT           VARCHAR(250),
  LAST_UPDATE_DATE    VARCHAR(250),
  DELIVRANCE1         VARCHAR(250),
  LIEUDEDELIVRANCE    VARCHAR(250),
  COPIE               VARCHAR(250),
  UPDATE_ON           VARCHAR(250),
  ID                  VARCHAR(250),
  PICTURE_LOADED_DATE VARCHAR(250),
  SOURCE_DONNEES      VARCHAR(250),
  ORIGINAL_FILE_NAME  VARCHAR(50),
  ORIGINAL_FILE_SIZE  INTEGER,
  ORIGINAL_FILE_LINE_COUNT INTEGER,
  INSERT_DATE TIMESTAMP,
  ORIGINAL_FILE_DATE DATE
);




---Staging table in data lake
CREATE TABLE TMP.SQ_IT_KAABU_CLIENT_DIRECTORY (
NUMERO              VARCHAR(250),
  TYPEDECONTRAT       VARCHAR(250),
  SOURCE              VARCHAR(250),
  TELEPHONE           VARCHAR(250),
  GENDER              VARCHAR(250),
  TITRE               VARCHAR(250),
  PRENOMDUCLIENT      VARCHAR(250),
  NOMDUCLIENT         VARCHAR(250),
  DATEDENAISSANCE     VARCHAR(250),
  LIEUDENAISSANCE     VARCHAR(250),
  PIECE               VARCHAR(250),
  NUMEROPIECE         VARCHAR(250),
  DELIVRANCE          VARCHAR(250),
  EXPIRATION          VARCHAR(250),
  NATIONALITE         VARCHAR(250),
  QUARTIER            VARCHAR(250),
  VILLE               VARCHAR(250),
  LOGINVENDEUR        VARCHAR(250),
  PRENOMVENDEUR       VARCHAR(250),
  NOMVENDEUR          VARCHAR(249),
  NUMERODUVENDEUR     VARCHAR(250),
  LOGINDISTRIBUTEUR   VARCHAR(250),
  PRENOMDISTRIBUTEUR  VARCHAR(250),
  NOMDISTRIBUTEUR     VARCHAR(250),
  EMISLE              VARCHAR(250),
  MAJLE               VARCHAR(250),
  LOGINMAJ            VARCHAR(250),
  PRENOMMAJ           VARCHAR(250),
  NOMMAJ              VARCHAR(250),
  ETAT                VARCHAR(250),
  ETATDEXPORTGLOBAL   VARCHAR(250),
  LOGINVALIDATEUR     VARCHAR(250),
  PRENOMVALIDATEUR    VARCHAR(249),
  NOMVALIDATEUR       VARCHAR(250),
  CAUSEECHEC          VARCHAR(250),
  COMMENTAIRE         VARCHAR(250),
  PWDCLIENT           VARCHAR(250),
  LAST_UPDATE_DATE    VARCHAR(250),
  DELIVRANCE1         VARCHAR(250),
  LIEUDEDELIVRANCE    VARCHAR(250),
  COPIE               VARCHAR(250),
  UPDATE_ON           VARCHAR(250),
  ID                  VARCHAR(250),
  PICTURE_LOADED_DATE VARCHAR(250),
  SOURCE_DONNEES      VARCHAR(250),
  ORIGINAL_FILE_NAME  VARCHAR(50),
  ORIGINAL_FILE_SIZE  INT,
  ORIGINAL_FILE_LINE_COUNT INT,
  INSERT_DATE TIMESTAMP,
  ORIGINAL_FILE_DATE DATE
);


DECLARE 
  SAMPLE_TABLE VARCHAR2(200); MIN_DATE_PARTITION VARCHAR2(200); MAX_DATE_PARTITION VARCHAR2(200);  KEY_COLUMN_PART_NAME VARCHAR2(200);
  KEY_COLUMN_PART_TYPE VARCHAR2(200);   PART_OWNER VARCHAR2(200);  PART_TABLE_NAME VARCHAR2(200);  PART_PARTITION_NAME VARCHAR2(200);
  PART_TYPE_PERIODE VARCHAR2(200);  PART_RETENTION NUMBER;  PART_TBS_CIBLE VARCHAR2(200);  PART_GARDER_01_DU_MOIS VARCHAR2(200);
PART_PCT_FREE NUMBER;   PART_COMPRESSION VARCHAR2(200);  PART_ROTATION_ACTIVE VARCHAR2(200);  PART_FORMAT VARCHAR2(200);
BEGIN 
  SAMPLE_TABLE := 'MON.SQ_IT_KAABU_CLIENT';
  MIN_DATE_PARTITION := '20220101';
  MAX_DATE_PARTITION := '20270101';
  KEY_COLUMN_PART_NAME := 'ORIGINAL_FILE_DATE';
  KEY_COLUMN_PART_TYPE := 'JOUR';
  PART_OWNER := 'MON';
  PART_TABLE_NAME := 'IT_KAABU_CLIENT';
  PART_PARTITION_NAME := 'IT_KAABU_CLIENT_';
  PART_TYPE_PERIODE := 'JOUR';
  PART_RETENTION := 1000;
  PART_TBS_CIBLE :=  'TAB_P_CDR_J01_256M';
  PART_GARDER_01_DU_MOIS := 'NON';
  PART_PCT_FREE := 0;
  PART_COMPRESSION := 'COMPRESS';
  PART_ROTATION_ACTIVE := 'OUI';
  PART_FORMAT := 'yyyymmdd';
  MON.CREATE_PARTITIONED_TABLE ( SAMPLE_TABLE, MIN_DATE_PARTITION, MAX_DATE_PARTITION, KEY_COLUMN_PART_NAME, KEY_COLUMN_PART_TYPE, PART_OWNER, PART_TABLE_NAME, PART_PARTITION_NAME, PART_TYPE_PERIODE, PART_RETENTION, PART_TBS_CIBLE, PART_GARDER_01_DU_MOIS, PART_PCT_FREE, PART_COMPRESSION, PART_ROTATION_ACTIVE, PART_FORMAT );
  COMMIT; 
END;
