CREATE EXTERNAL TABLE cdr.spark_tt_kaabu_transactions (
    ORIGINAL_FILE_NAME VARCHAR(200),
    ORIGINAL_FILE_SIZE INT,
    ORIGINAL_FILE_LINE_COUNT INT,
    TRANSFER_ID VARCHAR(200),
    CANAL VARCHAR(200),
    EXTRA_DATA VARCHAR(500),
    LIBELLE_A_AFFICHER VARCHAR(1000),
    AGENT_NUMBER VARCHAR(100),
    NUMERO_CLIENT VARCHAR(100),
    TRANSACTION_AMOUNT VARCHAR(100),
    TRANSFER_STATUS VARCHAR(50),
    TYPE_OP VARCHAR(250),
    SOURCE VARCHAR(250),
    LOGIN VARCHAR(100),
    Id VARCHAR(200),
    TRANSFER_DATETIME VARCHAR(100)
)
COMMENT 'external tables-TT'
ROW FORMAT DELIMITED FIELDS TERMINATED BY ';'
LOCATION '/PROD/TT/IDENTIFICATION/KAABU_TRANS'
TBLPROPERTIES ('serialization.null.format'='')
;


CREATE TABLE cdr.spark_it_kaabu_transactions
(
    TRANSFER_ID VARCHAR(200),
    CANAL VARCHAR(200),
    EXTRA_DATA VARCHAR(500),
    LIBELLE_A_AFFICHER VARCHAR(1000),
    AGENT_NUMBER VARCHAR(100),
    NUMERO_CLIENT VARCHAR(100),
    TRANSACTION_AMOUNT VARCHAR(100),
    TRANSFER_STATUS VARCHAR(50),
    TYPE_OP VARCHAR(250),
    SOURCE VARCHAR(250),
    LOGIN VARCHAR(100),
    Id VARCHAR(200),
    TRANSFER_DATETIME VARCHAR(100),
    original_file_name varchar(200),
    original_file_size int,
    original_file_line_count  int,
    INSERT_DATE TIMESTAMP
)
PARTITIONED BY (ORIGINAL_FILE_DATE DATE,DATE_CONTROLE DATE)
CLUSTERED BY(NUMERO) INTO 64 BUCKETS
STORED AS PARQUET TBLPROPERTIES ('PARQUET.COMPRESS'='SNAPPY');
