INSERT INTO cdr.spark_it_kaabu_client_directory 
SELECT
       numero,
       typedecontrat,
       source,
       telephone,
       gender,
       titre,
       prenomduclient,
       nomduclient,
       datedenaissance,
       lieudenaissance,
       piece,
       numeropiece,
       delivrance,
       expiration,
       nationalite,
       quartier,
       ville,
       loginvendeur,
       prenomvendeur,
       nomvendeur,
       numeroduvendeur,
       logindistributeur,
       prenomdistributeur,
       nomdistributeur,
       emisle,
       majle,
       loginmaj,
       prenommaj,
       nommaj,
       etat,
       etatdexportglobal,
       loginvalidateur,
       prenomvalidateur,
       nomvalidateur,
       causeechec,
       commentaire,
       pwdclient,
       last_update_date last_update_datetime,
       delivrance1,
       lieudedelivrance,
       copie,
       update_on,
       id,
       picture_loaded_date,
       source_donnees,
       original_file_name,
       original_file_size,
       original_file_line_count,
       CURRENT_TIMESTAMP() INSERT_DATE,
       To_date(last_update_date) last_update_date
FROM   cdr.tt_kaabu_client_directory C
       LEFT JOIN (SELECT DISTINCT original_file_name FILE_NAME FROM   cdr.spark_it_kaabu_client_directory) T ON T.file_name = C.original_file_name
WHERE  T.file_name IS NULL