SELECT IF(T_1.FT_B2B_EXIST = 0 and T_2.FT_EXIST_1 > 0  and T_3.FT_EXIST_2 >0,"OK","NOK") FT_SUBS_EXIST_B2B
FROM
(SELECT COUNT(*) FT_B2B_EXIST FROM MON.SPARK_KAABU_CLIENT_DEC  WHERE EVENT_DATE = '###SLICE_VALUE###') T_1,
(SELECT COUNT(*) FT_EXIST_1 FROM cdr.spark_it_kaabu_client_directory  WHERE DATE_CREATION = '###SLICE_VALUE###') T_2,
(SELECT COUNT(*) FT_EXIST_2 FROM CDR.SPARK_IT_KAABU_CLIENT_DEC WHERE DATE_CONTROLE = '###SLICE_VALUE###') T_3

