SELECT IF(T_1.FT_CON > 0 and T_2.TMP_AC = 0 ,"OK","NOK") TMP_ACTIVATION_MONTH
FROM
(SELECT COUNT(*) FT_CON FROM MON.SPARK_FT_CONTRACT_SNAPSHOT WHERE EVENT_DATE = '###SLICE_VALUE###') T_1,
(SELECT COUNT(*) TMP_AC FROM MON.SPARK_TMP_ACTIVATION_MONTH WHERE EVENT_MONTH = SUBSTR('###SLICE_VALUE###',1,7) and ACTIVATION_DATE='###SLICE_VALUE###') T_2