SELECT IF(
T_1.FT_EXIST = 0 AND 
T_2.COMMISSION_EXIST>0 AND 
T_3.SERVICE_CHARGE_EXIST>0 AND 
T_4.TRANSACTIONS_EXIST>0 AND
T_5.NB_UNKNOWN_SERVICE=0
,"OK","NOK")
FROM
(SELECT COUNT(*) FT_EXIST FROM MON.SPARK_TTVMW_OM_BICEC_TRANS WHERE EVENT_DATE ='###SLICE_VALUE###') T_1,
(SELECT COUNT(*) COMMISSION_EXIST FROM CDR.SPARK_IT_OMNY_COMMISSION_DETAILS WHERE TRANSACTION_DATE='###SLICE_VALUE###') T_2,
(SELECT COUNT(*) SERVICE_CHARGE_EXIST FROM CDR.SPARK_IT_OMNY_SERVICES_CHARGES_DETAILS WHERE TRANSACTION_DATE='###SLICE_VALUE###') T_3,
(SELECT COUNT(*) TRANSACTIONS_EXIST FROM CDR.SPARK_IT_OMNY_TRANSACTIONS WHERE transfer_datetime='###SLICE_VALUE###') T_4,
(select count(distinct T.service_type) NB_UNKNOWN_SERVICE from
(
select A.service_type
from CDR.SPARK_IT_OMNY_SERVICES_CHARGES_DETAILS A
left join DIM.DT_OM_OPERATION_TYPE B on (A.SERVICE_TYPE = B.SERVICE_TYPE)
where
A.SERVICE_CHARGE_AMOUNT > 0
and A.TRANSACTION_DATE = '2020-07-01'
and B.SERVICE_TYPE IS NULL
union
select A.service_type
FROM
CDR.SPARK_IT_OMNY_COMMISSION_DETAILS A
left join DIM.DT_OM_OPERATION_TYPE B on (A.SERVICE_TYPE = B.SERVICE_TYPE)
WHERE
A.COMMISSION_AMOUNT > 0
AND A.TRANSACTION_DATE = '2020-07-01'
and B.SERVICE_TYPE IS NULL
union
select A.service_type
from
CDR.SPARK_IT_OMNY_TRANSACTIONS A
left join DIM.DT_OM_OPERATION_TYPE B on (A.SERVICE_TYPE = B.SERVICE_TYPE)
WHERE
(
TRANSFER_STATUS = 'TS'
OR
(
TRANSFER_STATUS = 'TF'
AND RECONCILIATION_BY IS NOT NULL
)
OR
(
TRANSFER_STATUS = 'TF'
AND SENDER_PRE_BAL <> SENDER_POST_BAL
)
)
AND TRANSFER_DATETIME = '2020-07-01'
and B.SERVICE_TYPE IS NULL
) T
) T_5