SELECT IF(
T_1.FT_EXIST = 0 AND
T_2.TT_EXIST>0
,"OK","NOK") BICEC_EXIST
FROM
(SELECT COUNT(*) FT_EXIST FROM MON.SPARK_FT_OM_BICEC_TRANSACTION WHERE EVENT_DATE ='###SLICE_VALUE###') T_1,
(SELECT COUNT(*) TT_EXIST FROM MON.SPARK_TTVMW_OM_BICEC_TRANS WHERE EVENT_DATE='###SLICE_VALUE###') T_2