select
nvl(trim(replace(msisdn,';',' ')),'') as msisdn,
nvl(trim(replace(type_personne,';',' ')),'') as type_personne,
nvl(trim(replace(nom_prenom,';',' ')),'') as nom_prenom,
nvl(trim(replace(id_type_piece,';',' ')),'') as id_type_piece,
nvl(trim(replace(type_piece,';',' ')),'') as type_piece,
nvl(trim(replace(numero_piece,';',' ')),'') as numero_piece,
nvl(trim(replace(date_expiration,';',' ')),'') as date_expiration,
nvl(trim(replace(date_naissance,';',' ')),'') as date_naissance,
nvl(trim(replace(date_activation,';',' ')),'') as date_activation,
nvl(trim(replace(adresse,';',' ')),'') as addresse,
nvl(trim(replace(quartier,';',' ')),'') as quartier,
nvl(trim(replace(ville,';',' ')),'') as ville,
nvl(trim(replace(statut,';',' ')),'') as statut_bscs,
nvl(trim(replace(statut_validation_bo,';',' ')),'') as statut_validation_bo,
nvl(trim(replace(motif_rejet_bo,';',' ')),'') as motif_rejet_bo,
nvl(trim(replace(date_validation_bo,';',' ')),'') as date_validation_bo,
nvl(trim(replace(login_validateur_bo,';',' ')),'') as login_validateur_bo,
nvl(trim(replace(canal_validateur_bo,';',' ')),'') as canal_validateur_bo,
nvl(trim(replace(type_abonnement,';',' ')),'') as type_abonnement,
nvl(trim(replace(csmoddate,';',' ')),'') as csmoddate,
nvl(trim(replace(ccmoddate,';',' ')),'') as ccmoddate,
nvl(trim(replace(compte_client_structure,';',' ')),'') as compte_client_structure,
nvl(trim(replace(nom_structure,';',' ')),'') as nom_structure,
nvl(trim(replace(numero_registre_commerce,';',' ')),'') as numero_registre_commerce,
nvl(trim(replace(numero_piece_representant_legal,';',' ')),'') as numero_piece_rep_legal,
nvl(trim(replace(imei,';',' ')),'') as imei,
nvl(trim(replace(statut_derogation,';',' ')),'') as statut_derogation,
nvl(trim(replace(region_administrative,';',' ')),'') as region_administrative,
nvl(trim(replace(region_commerciale,';',' ')),'') as region_commerciale,
nvl(trim(replace(site_name,';',' ')),'') as site_name,
nvl(trim(replace(ville_site,';',' ')),'') as ville_site,
nvl(trim(replace(offre_commerciale,';',' ')),'') as offre_commerciale,
nvl(trim(replace(type_contrat,';',' ')),'') as type_contrat,
nvl(trim(replace(segmentation,';',' ')),'') as segmentation,
nvl(trim(replace(score_vip,';',' ')),'') as score_vip,
nvl(trim(replace(date_souscription,';',' ')),'') as date_souscription,
nvl(trim(replace(date_changement_statut,';',' ')),'') as date_changement_statut,
nvl(trim(replace(ville_structure,';',' ')),'') as ville_structure,
nvl(trim(replace(quartier_structure,';',' ')),'') as quartier_structure,
nvl(trim(replace(raison_statut,';',' ')),'') as raison_statut,
nvl(trim(replace(prenom,';',' ')),'') as prenom,
nvl(trim(replace(nom,';',' ')),'') as nom,
nvl(trim(replace(customer_id,';',' ')),'') as customer_id,
nvl(trim(replace(contract_id,';',' ')),'') as contract_id,
nvl(trim(replace(compte_client,';',' ')),'') as compte_client,
nvl(trim(replace(plan_localisation,';',' ')),'') as plan_localisation,
nvl(trim(replace(contrat_soucription,';',' ')),'') as contrat_soucription,
nvl(trim(replace(acceptation_cgv,';',' ')),'') as acceptation_cgv,
nvl(trim(replace(disponibilite_scan,';',' ')),'') as disponibilite_scan,
nvl(trim(replace(nom_tuteur ||' '||prenom_tuteur,';',' ')),'') as nom_parent,
nvl(trim(replace(prenom_tuteur,';',' ')),'') as prenom_tuteur,
nvl(trim(replace(date_naissance_tuteur,';',' ')),'') as date_naissance_tuteur,
nvl(trim(replace(numero_piece_tuteur,';',' ')),'') as numero_piece_tuteur,
nvl(trim(replace(date_expiration_tuteur,';',' ')),'') as date_expiration_tuteur,
nvl(trim(replace(id_type_piece_tuteur,';',' ')),'') as id_type_piece_tuteur,
nvl(trim(replace(type_piece_tuteur,';',' ')),'') as type_piece_tuteur,
nvl(trim(replace(adresse_tuteur,';',' ')),'') as adresse_tuteur,
nvl(trim(replace(identificateur,';',' ')),'') as identificateur,
nvl(trim(replace(localisation_identificateur,';',' ')),'') as localisation_identificateur,
nvl(trim(replace(profession,';',' ')),'') as profession,
nvl(trim(replace(odbincomingcalls,';',' ')),'') as odbincomingcalls,
nvl(trim(replace(odboutgoingcalls,';',' ')),'') as odboutgoingcalls,
nvl(insert_date,'') as insert_date,
nvl(original_file_date,'') as original_file_date
-- from CDR.SPARK_IT_BDI where original_file_date='###SLICE_VALUE###'
from CDR.SPARK_IT_KYC_BDI_FULL 
WHERE original_file_date='###SLICE_VALUE###' and UPPER(TYPE_PERSONNE) <> 'FLOTTE' 