SELECT IF(A.KPI_CNI_EXPIREES = 0 AND B.CNI_EXPIREES >0 AND C.PREV_CNI_EXPIREES > 0 ,"OK","NOK") FROM
(SELECT COUNT(*) KPI_CNI_EXPIREES FROM MON.SPARK_FT_A_CNI_EXPIREES WHERE EVENT_DATE= '###SLICE_VALUE###') A,
(SELECT COUNT(*) CNI_EXPIREES FROM MON.SPARK_FT_CNI_EXPIREES WHERE EVENT_DATE= '###SLICE_VALUE###') B,
(SELECT COUNT(*) PREV_CNI_EXPIREES FROM MON.SPARK_FT_CNI_EXPIREES WHERE EVENT_DATE= DATE_SUB(to_date('###SLICE_VALUE###'),1)) C

