SELECT
    AGE,
    DEV,
    CHA,
    TRIM(NCP) NCP,
    SUF,
    regexp_replace(regexp_replace(OPE,'\r',''),'\n','') OPE ,  
    '' MVTI,
    '' RGP,
    UTI,  
    '' EVE,
    CLC, 
    from_unixtime(unix_timestamp(DCO, 'yyyy-MM-dd'), 'dd/MM/yyyy') DCO,  
    '' SER,
    from_unixtime(unix_timestamp(DVA, 'yyyy-MM-dd'), 'dd/MM/yyyy') DVA, 
    replace(regexp_replace(MON, '\\.*(0)+$', ''), '.', ',') as MON,
    SEN, 
    regexp_replace(regexp_replace(LIB,'\r',''),'\n','') LIB ,  
    'N' EXO,
    regexp_replace(regexp_replace(PIE,'\r',''),'\n','') PIE ,  
    '' RLET,
    ''  DES1,
    ''  DES2,
    ''  DES3, 
    ''  DES4,
    ''  DES5,
    ''  UTR,
    ''  UTA,
    ''  TAU,
    ''  DIN,
    ''  TPR,
    ''  NPR,
    ''  NCC,
    ''  SUC,
    ''  ESI,
    ''  IMP,
    ''  CTA,
    '' MAR,
    '' DECH,
    AGSA,
    AGEM,
    AGDE,
    DEVC,
    replace(regexp_replace(MCTV, '\\.*(0)+$', ''), '.', ',') as MCTV,
    regexp_replace(regexp_replace(PIEO,'\r',''),'\n','') PIEO ,  
    '' IDEN,
    '' NOSEQ
FROM MON.SPARK_FT_OM_BICEC_TRANSACTION a
WHERE 
    EVENT_DATE='###SLICE_VALUE###' AND 
    MON > 0  AND 
    LIB NOT LIKE '%stock%'
ORDER BY DVA, PIEO