INSERT INTO CTI.FT_CALL_QUEUE PARTITION(SDATE)
SELECT

 V.START_DATE_TIME_KEY ,
 R.RESOURCE_NAME FILE_NAME,
 IT.INTERACTION_TYPE_CODE TYPE_INTERACTION,
 T.TECHNICAL_RESULT_CODE RESULTAT_TECH,
 T.RESULT_REASON_CODE RAISON_RESULTAT_TECH,
 UDCD1.DIM_ATTRIBUTE_1 UD_LANGUE,
 UDCD1.DIM_ATTRIBUTE_2 UD_VIPGSM,
 UDCD1.DIM_ATTRIBUTE_3 UD_VIPOMY,
 UDCD1.DIM_ATTRIBUTE_4 UD_ISOMY,
 UDCD1.DIM_ATTRIBUTE_5 UD_LISTSEGMENT,

 UDCD2.DIM_ATTRIBUTE_1 UD_SEGMENT,
 UDCD2.DIM_ATTRIBUTE_2 UD_SITE_CIBLE,
 UDCD2.DIM_ATTRIBUTE_3 UD_SITE_CHOISI,
 UDCD2.DIM_ATTRIBUTE_4 UD_COMP,
 UDCD2.DIM_ATTRIBUTE_5 UD_COMP_DEB,

 UDCD3.DIM_ATTRIBUTE_1 UD_COMP_CHOISI,
 UDCD3.DIM_ATTRIBUTE_3 UD_CRISE_SITE,
 UDCD3.DIM_ATTRIBUTE_4 UD_CRISE_FERM,
 UDCD3.DIM_ATTRIBUTE_5 UD_CRISE_FLUX,

 UDCD4.DIM_ATTRIBUTE_1 UD_CRISE_DISSU,
 UDCD4.DIM_ATTRIBUTE_2 UD_DISTRIBUTED,
 UDCD4.DIM_ATTRIBUTE_3 UD_NRONA,
 UDCD4.DIM_ATTRIBUTE_4 UD_HNO,
 UDCD4.DIM_ATTRIBUTE_5 UD_XFER_PRESTA,

 UDCD5.DIM_ATTRIBUTE_1 UD_FERMETURE,
 UDCD5.DIM_ATTRIBUTE_2 UD_DISSUASION,
 UDCD5.DIM_ATTRIBUTE_3 UD_DNIS,
 IRFUD1.CUSTOM_DATA_1 UD_DUREEATTENTE,
 IRFUD1.CUSTOM_DATA_2 UD_PRIORITEFLUX,

 IRFUD1.Custom_Data_3 CLIENT,
 V.MEDIATION_DURATION TPS_VQ,
 IRF.Routing_Point_Duration TPS_RP,
 IRF.AFTER_CALL_WORK_DURATION TPS_ACW,
 IRF.RING_DURATION TPS_SONNERIE,
 IRF.TALK_DURATION TPS_CONVERSATION_AGENT,
 IRF.Customer_Talk_Duration TPS_CONVERSATION_CLIENT,
 IRF.Hold_Duration TPS_HOLD_DURATION,
 FROM_UTC_TIMESTAMP(CAST(V.START_DATE_TIME_KEY AS BIGINT) * 1000, '${hivevar:time_zone}') SDATETIME,
 current_timestamp INSERT_DATE,
 to_date(FROM_UTC_TIMESTAMP(CAST(V.START_DATE_TIME_KEY AS BIGINT) * 1000, '${hivevar:time_zone}')) SDATE

FROM

 (SELECT * 
FROM CTI.FT_MEDIATION_SEGMENT_FACT where ORIGINAL_FILE_DATE='###SLICE_VALUE###'
) V,

 (SELECT * 
 FROM CTI.DT_INTERACTION_TYPE where ORIGINAL_FILE_DATE =(select max(original_file_date) from CTI.DT_INTERACTION_TYPE)
 ) IT, 
 
 (SELECT * 
 FROM CTI.DT_MEDIA_TYPE where ORIGINAL_FILE_DATE =(select max(original_file_date) from CTI.DT_MEDIA_TYPE)
 ) MT,
 
 (SELECT * FROM 
 CTI.DT_RESOURCE where ORIGINAL_FILE_DATE =(select max(original_file_date) from CTI.DT_RESOURCE)
 ) R,
 
 (SELECT * FROM 
 CTI.DT_TECHNICAL_DESCRIPTOR where ORIGINAL_FILE_DATE = (select max(original_file_date) from CTI.DT_TECHNICAL_DESCRIPTOR)
 ) T,
 
 (SELECT * FROM 
 CTI.IT_INTERACTION_RESOURCE_FACT where ORIGINAL_FILE_DATE='###SLICE_VALUE###'
 ) IRF,
 
 (SELECT * FROM CTI.FT_IRF_USER_DATA_KEYS where ORIGINAL_FILE_DATE='###SLICE_VALUE###'
 ) UDKEY,
 
 (SELECT * FROM 
 CTI.DT_USER_DATA_CUST_DIM_1 where ORIGINAL_FILE_DATE=(select max(original_file_date) from CTI.DT_USER_DATA_CUST_DIM_1)
 ) UDCD1,
 
 (SELECT * FROM 
 CTI.DT_USER_DATA_CUST_DIM_2 where ORIGINAL_FILE_DATE=(select max(original_file_date) from CTI.DT_USER_DATA_CUST_DIM_2)
 ) UDCD2,
 
 (SELECT * FROM 
 CTI.DT_USER_DATA_CUST_DIM_3 where ORIGINAL_FILE_DATE=(select max(original_file_date) from CTI.DT_USER_DATA_CUST_DIM_3)
 ) UDCD3,
 
 (SELECT * FROM 
 CTI.DT_USER_DATA_CUST_DIM_4 where ORIGINAL_FILE_DATE=(select max(original_file_date) from CTI.DT_USER_DATA_CUST_DIM_4)
 ) UDCD4,
 
 (SELECT * FROM 
 CTI.DT_USER_DATA_CUST_DIM_5 where ORIGINAL_FILE_DATE=(select max(original_file_date) from CTI.DT_USER_DATA_CUST_DIM_5)
 ) UDCD5,
 
(SELECT * FROM 
CTI.FT_IRF_USER_DATA_CUST_1 where ORIGINAL_FILE_DATE='###SLICE_VALUE###'
) IRFUD1
WHERE
 V.TECHNICAL_DESCRIPTOR_KEY = T.TECHNICAL_DESCRIPTOR_KEY
 AND IRF.Interaction_Id=V.Interaction_Id
 AND UDKEY.Interaction_Resource_Id=IRF.Interaction_Resource_Id
 AND UDKEY.Custom_Key_1=UDCD1.ID
 AND UDKEY.Custom_Key_2=UDCD2.ID
 AND UDKEY.Custom_Key_3=UDCD3.ID
 AND UDKEY.Custom_Key_4=UDCD4.ID
 AND UDKEY.Custom_Key_5=UDCD5.ID

 AND IRFUD1.Interaction_Resource_Id=IRF.Interaction_Resource_Id

 AND V.MEDIA_TYPE_KEY = MT.MEDIA_TYPE_KEY
 AND V.INTERACTION_TYPE_KEY = IT.INTERACTION_TYPE_KEY
 AND V.RESOURCE_KEY = R.RESOURCE_KEY
 AND R.RESOURCE_SUBTYPE = 'VirtualQueue'