SELECT IF(T_1.FT_EXIST = 0 and T_2.IT_SM_STATE_FACT>0 and T_3.IT_SM_RES_STATE_REASON_FACT>0,"OK","NOK") IT_CTI_EXIST
FROM
(SELECT COUNT(*) FT_EXIST FROM CTI.FT_AGENT_ACTIVITY WHERE SDATE='###SLICE_VALUE###') T_1,
(SELECT COUNT(*) IT_SM_STATE_FACT FROM CTI.IT_SM_STATE_FACT WHERE ORIGINAL_FILE_DATE='###SLICE_VALUE###') T_2,
(SELECT COUNT(*) IT_SM_RES_STATE_REASON_FACT FROM CTI.IT_SM_RES_STATE_REASON_FACT WHERE ORIGINAL_FILE_DATE='###SLICE_VALUE###') T_3