SELECT IF(
T_1.NB_BASE_IDENT < 1
,"OK","NOK")
FROM
(
select count(*) NB_BASE_IDENT from
(select * 
    from (SELECT * FROM MON.EXPORT_HISTORY where event_date='###SLICE_VALUE###' and JOB_INSTANCEID='LOAD_SPARK_COM_BASE_IDENTIFICATION' ORDER BY INSERT_DATE DESC LIMIT 1)  T where T.STATUS = 'OK') M
) T_1