SELECT IF(T_1.FT_EXIST = 0 and T_2.IT_EXIST>0 and T_3.IT_EXIST > 0 ,"OK","NOK") FT_OM_APGL_EXIST
FROM
(SELECT COUNT(*) FT_EXIST FROM mon.spark_ft_om_bacm_transactions WHERE event_date='###SLICE_VALUE###') T_1,
(SELECT COUNT(*) IT_EXIST FROM CDR.SPARK_IT_OMNY_TRANSACTIONS WHERE TRANSFER_DATETIME = '###SLICE_VALUE###') T_2,
(SELECT COUNT(*) IT_EXIST FROM CDR.SPARK_IT_OM_ALL_USERS WHERE original_file_date = '###SLICE_VALUE###') T_3

