CREATE TABLE AGG.SPARK_FT_A_SUBSCRIBER_SUMMARY_B2B 
(
    FAMILLE_KPI VARCHAR(10),
    DATECODE DATE,
    SUBSCRIBER_TYPE VARCHAR(40),
    OFFER_NAME VARCHAR(50),
    COMMERCIAL_OFFER VARCHAR(50),
    TOTAL_COUNT INT
)
STORED AS PARQUET
TBLPROPERTIES ('PARQUET.COMPRESS'='SNAPPY')
