SELECT IF(A.FT_EXIST = 0 and B.FT_COUNT>0  , "OK","NOK") FROM
(SELECT COUNT(*) FT_EXIST FROM MON.SPARK_FT_DATA_CONSO_MSISDN_DAY_POST WHERE EVENT_DATE='###SLICE_VALUE###') A,
(SELECT COUNT(*) FT_COUNT FROM MON.SPARK_FT_CRA_GPRS_POST WHERE session_date='###SLICE_VALUE###') B





