SELECT 
nvl(to_date(EVENT_DATE),'') EVENT_DATE,
nvl(MSISDN,'') MSISDN,
nvl(SITE_NAME,'') SITE_NAME,
nvl(TOWNNAME,'') TOWNNAME,
nvl(ADMINISTRATIVE_REGION, '') ADMINISTRATIVE_REGION,
nvl(COMMERCIAL_REGION,'') COMMERCIAL_REGION,
nvl(to_date(LAST_LOCATION_DAY),'') LAST_LOCATION_DAY,
nvl(OPERATOR_CODE,'') OPERATOR_CODE
FROM MON.SPARK_FT_CLIENT_LAST_SITE_DAY
WHERE EVENT_DATE ='###SLICE_VALUE###'