insert into MON.SPARK_FT_IMEI_ONLINE_ACTIVE PARTITION(EVENT_DATE)
SELECT
    nvl(a.IMEI,b.IMEI) IMEI,
    SDATE EVENT_DATE
FROM 
( 
    SELECT * FROM MON.SPARK_FT_IMEI_ONLINE_ACTIVE WHERE EVENT_DATE=DATE_SUB('###SLICE_VALUE###',1)
    UNION 
    SELECT DISTINCT IMEI, SDATE EVENT_DATE  FROM MON.SPARK_FT_IMEI_ONLINE WHERE SDATE = '###SLICE_VALUE###'
)
