CREATE TABLE TMP.SPARK_TT_FT_IMEI_ONLINE (
    IMEI VARCHAR(50),
    IMSI VARCHAR(50),
    MSISDN VARCHAR(50),
    SRC_TABLE VARCHAR(100),
    TRANSACTION_COUNT INT
) COMMENT 'FT_IMEI_ONLINE - FT'
  PARTITIONED BY (SDATE DATE)
STORED AS PARQUET TBLPROPERTIES ('PARQUET.COMPRESS'='SNAPPY');
