create table MON.SPARK_FT_CLIENT_LAST_IMEI_DAILY (
    msisdn varchar(50),
    IMEI varchar(50),
    REFRESH_DATE timestamp
)   COMMENT 'MON_SPARK_FT_CdateENT_LAST_IMEI_DAILY'
PARTITIONED BY (EVENT_DATE DATE)
STORED AS PARQUET TBLPROPERTIES ('PARQUET.COMPRESS'='SNAPPY')