select 
SERVED_MSISDN,
OTHER_PARTY, 
TRANSACTION_DIRECTION ,
TRANSACTION_DATE
FROM MON.SPARK_FT_MSC_TRANSACTION 
WHERE TRANSACTION_DATE BETWEEN DATE_SUB(CURRENT_DATE, 92) AND DATE_SUB(CURRENT_DATE, 3) 
AND LENGTH(SERVED_MSISDN)=9 
AND LENGTH(OTHER_PARTY)=9 
AND UPPER(TRANSACTION_TYPE) LIKE "TEL%"