SELECT IF(A.FT_EXIST = 0 and B.ACCOUNT_ACTIVITY_EXIST>0 AND T1.CLIENT_LAST_SITE_DAY_EXISTS>0,"OK","NOK") FROM
(SELECT COUNT(*) FT_EXIST FROM MON.FT_CBM_CHURN_DAILY WHERE EVENT_DATE='###SLICE_VALUE###') A,
(SELECT COUNT(*) ACCOUNT_ACTIVITY_EXIST FROM AGG.FT_ACCOUNT_ACTIVITY WHERE EVENT_DATE='###SLICE_VALUE###')B,
(SELECT COUNT(*) CLIENT_LAST_SITE_DAY_EXISTS FROM MON.FT_CLIENT_LAST_SITE_DAY WHERE EVENT_DATE="###SLICE_VALUE###")T1


