INSERT INTO MON.SPARK_FT_DATAMART_OM_TRANS

SELECT

    OT.SENDER_MSISDN MSISDN,
    TO_DATE(OT.TRANSFER_DATETIME) PERIOD,
    OT.RECEIVER_MSISDN MSISDN_BENEFICIAIRE,
    OT.SERVICE_TYPE SERVICE,
    DT.SERVICE_NAME SERVICE_DETAILS,
    OT.TRANSACTION_AMOUNT MONTANT_TRANSACTION,
    OT.SERVICE_CHARGE_RECEIVED + OT.SERVICE_CHARGE_PAID FRAIS_TRANSACTION,
    current_timestamp INSERT_DATE
    
FROM BACKUP_DWH.IT_OMNY_TRANSACTIONS OT

LEFT JOIN 
    (SELECT * 
     FROM BACKUP_DWH.IT_OMNY_SYSSERVICETYPES
     WHERE ORIGINAL_FILE_DATE =(SELECT MAX(ORIGINAL_FILE_DATE) FROM CDR.SPARK_IT_OMNY_SYSSERVICETYPES WHERE ORIGINAL_FILE_DATE >= DATE_SUB('2020-02-17', 7))) DT

ON OT.SERVICE_TYPE = DT.SERVICE_TYPE

WHERE OT.TRANSFER_DATETIME = '2020-02-17' AND OT.TRANSFER_DONE LIKE '%Y%'
