INSERT INTO MON.FT_OMNY_BALANCE
SELECT
      USER_DOMAIN,
      USER_CATEGORY,
      USER_TYPE,
      sum(1) TOTAL_COUNT,
      sum(ACCOUNT_BALANCE) ACCOUNT_BALANCE,
      current_timestamp INSERT_DATE,
      "###SLICE_VALUE###" EVENT_DATE
FROM MON.FT_OMNY_ACCOUNT_SNAPSHOT
WHERE EVENT_DATE = "###SLICE_VALUE###"
GROUP BY
       EVENT_DATE,
       USER_DOMAIN ,
       USER_CATEGORY,
       USER_TYPE;