CREATE TABLE MON.FT_OMNY_BALANCE
(
  USER_DOMAIN      VARCHAR(100),
  USER_CATEGORY    VARCHAR(100),
  USER_TYPE        VARCHAR(50),
  TOTAL_COUNT      BIGINT,
  ACCOUNT_BALANCE  DECIMAL(17,2),
  INSERT_DATE      TIMESTAMP
)
PARTITIONED BY (EVENT_DATE DATE)
 TBLPROPERTIES ("orc.compress"="ZLIB","orc.stripe.size"="67108864")
