CREATE TABLE MON.SPARK_FT_TRANSFERT_P2P
(
  COMMERCIAL_OFFER   VARCHAR(300) ,
  MONTH              VARCHAR(10),
  OSP_CONTRACT_TYPE  VARCHAR(35),
  MONTANT_TRANSFER   BIGINT,
  MONTANT_FRAIS      BIGINT,
  NOMBRE             BIGINT,
  SEGMENTATION       VARCHAR(60)
)
PARTITIONED BY (REFILL_DATE DATE)
STORED AS PARQUET
TBLPROPERTIES ('PARQUET.COMPRESS'='SNAPPY')