SELECT IF(T_1.COMPLETUDE = 0 and T_2.FT_CREDIT_EXIST>0 and T_3.CONTRACT_SNAPSHOT_EXIST>0,"OK","NOK") EXTRACT_EXIST
FROM FT_CREDIT_EXIST
(SELECT COUNT(*) COMPLETUDE FROM MON.SPARK_FT_TRANSFERT_P2P WHERE REFILL_DATE='###SLICE_VALUE###') T_1,
(SELECT COUNT(*) FT_CREDIT_EXIST FROM MON.SPARK_FT_CREDIT_TRANSFER WHERE REFILL_DATE='###SLICE_VALUE###') T_2,
(SELECT COUNT(*) CONTRACT_SNAPSHOT_EXIST FROM MON.SPARK_FT_CONTRACT_SNAPSHOT WHERE EVENT_DATE = '###SLICE_VALUE###') T_3

