

CREATE EXTERNAL TABLE IF NOT EXISTS CDR.TT_IMEI

(

IMEI VARCHAR(50)

)
COMMENT 'EXP_DIM_CTL_AUDIT_LOG external tables-TT'
ROW FORMAT DELIMITED FIELDS TERMINATED BY ';'
LOCATION '/DATALAB/TEST/JOTIO/TABLES'
TBLPROPERTIES ('serialization.null.format'='')