

CREATE EXTERNAL TABLE IF NOT EXISTS CDR.TT_RIGHTQ_TRANSACTIONS

(

ORIGINAL_FILE_NAME VARCHAR(200),
ORIGINAL_FILE_SIZE INT,
ORIGINAL_FILE_LINE_COUNT INT,
Agence VARCHAR(200),
Ticket VARCHAR(10) ,
Service VARCHAR(100),
Client VARCHAR(100),
Mobile VARCHAR(50),
Arrivee TIMESTAMP,
Attente INT,
Service INT,
Note VARCHAR(100),
Commentaire VARCHAR(100),
Status VARCHAR(10),
Utilisateur VARCHAR(100),
Updated_tickets VARCHAR(100),
email VARCHAR(100)

)
COMMENT 'EXP_DIM_CTL_AUDIT_LOG external tables-TT'
ROW FORMAT DELIMITED FIELDS TERMINATED BY ';'
LOCATION '/PROD/RAW/RIGHTQ/TRANSACTIONS'
TBLPROPERTIES ('serialization.null.format'='')