
CREATE TABLE MON.EXPORT_HISTORY (
    JOB_INSTANCEID     VARCHAR(100),
    STATUS   VARCHAR(10),
    INSERT_DATE    TIMESTAMP
)
PARTITIONED BY (EVENT_DATE VARCHAR(20))
STORED AS PARQUET
TBLPROPERTIES ("parquet.compress"="SNAPPY")
