SELECT IF(A.FT_COUNT > 0 and B.FT_COUNT>0 and C.FT_COUNT>0 and D.FT_COUNT>0 and F.FT_COUNT>0 and E.FT_COUNT=0 , "OK","NOK") FROM
(SELECT COUNT(*) FT_COUNT FROM MON.SPARK_FT_CLIENT_LAST_SITE_LOCATION WHERE EVENT_MONTH='###SLICE_VALUE###') A,
(SELECT COUNT(*) FT_COUNT FROM MON.SPARK_FT_IMEI_TRAFFIC_MONTHLY WHERE SMONTH=date_format('###SLICE_VALUE###' || '-01', 'yyyyMM')) B,
(SELECT COUNT(*) FT_COUNT FROM MON.SPARK_FT_IMEI_TRAFFIC_MONTHLY WHERE SMONTH=date_format(ADD_MONTHS('###SLICE_VALUE###' || '-01' , -3),'yyyyMM')) C,
(SELECT COUNT(*) FT_COUNT FROM MON.SPARK_TF_SPECIFIC_SUBSCRIPTION_MONTH WHERE EVENT_MONTH='###SLICE_VALUE###') D,
(SELECT COUNT(*) FT_COUNT FROM MON.SPARK_TT_GROUP_SUBS_ACCT_DISCONNECT WHERE EVENT_DATE = date_sub(last_day('###SLICE_VALUE###'|| '-01'),-1)) F,
(SELECT COUNT(*) FT_COUNT FROM MON.SPARK_TT_ANALYSE_DECON_SUBSC_SPEC1 WHERE EVENT_MONTH='###SLICE_VALUE###') E
