SELECT IF(ACCOUNT_EXISTS_M0=0 AND ACCOUNT_EXISTS_M1>0 ,'OK','NOK') RESULT
FROM
(SELECT COUNT(*) ACCOUNT_EXISTS_M1 FROM MON.SPARK_FT_ACCOUNT_ACTIVITY WHERE EVENT_DATE=CONCAT(SUBSTR ('###SLICE_VALUE###', 1,7 ),'01'))A,
(SELECT COUNT(*) ACCOUNT_EXISTS_M0 FROM MON.SPARK_FT_ACCOUNT_ACTIVITY WHERE EVENT_DATE=last_day('###SLICE_VALUE###')+1)B