SELECT IF(A.NEW_REC = 0 AND B.REC >0 AND C.BAL>0 ,"OK","NOK") FROM
(SELECT COUNT(*) NEW_REC FROM MON.SPARK_FT_A_CXD_RECOUVREMENT WHERE EVENT_DATE= '###SLICE_VALUE###') A,
(SELECT COUNT(*) REC FROM MON.SPARK_FT_A_CXD_RECOUVREMENT where EVENT_DATE=last_day(add_months("###SLICE_VALUE###",-1))) B,
(SELECT COUNT(*) BAL FROM CDR.SPARK_IT_BALANCE_AGEE where as_of_date="###SLICE_VALUE###") C