INSERT INTO TMP.TT_OMNY_SDT_2
SELECT
    T.SENDER_MSISDN
    , MIN(T.TRANSFER_DATETIME_NQ) MIDATETR
    , SUM(T.TRANSACTION_AMOUNT) MTT_TRANS
    , COUNT(T.TRANSFER_ID) NB_TRANSACTION
    , MIN(T.TRANSACTION_AMOUNT) FIRSTTRAN
    , MIN(T.RECEIVER_MSISDN) DEST_TRAN
    , MIN(T.SERVICE_TYPE) SERV_TRAN
FROM
(
    SELECT
        SENDER_MSISDN
        , TRANSFER_DATETIME_NQ
        , TRANSACTION_AMOUNT
        , TRANSFER_ID
        , RECEIVER_MSISDN
        , SERVICE_TYPE
        , MIN(TRANSFER_DATETIME_NQ) OVER(PARTITION BY SENDER_MSISDN) AS MIN_TRANSFER_DATETIME_NQ
    FROM CDR.SPARK_IT_OMNY_TRANSACTIONS
    WHERE TRANSFER_DATETIME = "###SLICE_VALUE###" AND TRANSFER_STATUS = 'TS' AND SERVICE_TYPE IN ('CASHOUT','P2P','P2PNONREG','RC','BILLPAY','MERCHPAY')
) T
WHERE T.TRANSFER_DATETIME_NQ = T.MIN_TRANSFER_DATETIME_NQ
GROUP BY T.SENDER_MSISDN