INSERT INTO TMP.TT_OMNY_SDT_4
SELECT
    DISTINCT TELEPHONE
    , LOGINVENDEUR
FROM CDR.SPARK_IT_NOMAD_CLIENT_DIRECTORY
WHERE TYPEDECONTRAT='Orange Money' AND (ETATDEXPORTGLOBAL='FAIL' or ETATDEXPORTGLOBAL='SUCCES')
AND ORIGINAL_FILE_DATE >= DATE_SUB("###SLICE_VALUE###", 7)
