SELECT IF(T_1.FT_EXIST = 0 and T_2.IT_1_EXIST>0, "OK", "NOK")
FROM
(SELECT COUNT(*) FT_EXIST FROM MON.SPARK_FT_OMNY_SDT WHERE DATE_INSCRIPT='###SLICE_VALUE###') T_1,
(SELECT COUNT(*) IT_1_EXIST FROM CDR.SPARK_IT_OM_SUBSCRIBERS WHERE modification_date='###SLICE_VALUE###') T_2
