SELECT IF(T_1.FT_MSC_EXIST > 0 and T_2.FT_BILLED_EXIST > 0 and T_3.FT_CRA_EXIST > 0 and  T_4.REVENU_LOCALISE_EXIST  = 0,"OK","NOK") EXTRACT_EXIST
FROM
    (SELECT COUNT(*) FT_MSC_EXIST FROM MON.SPARK_FT_MSC_TRANSACTION WHERE TRANSACTION_DATE='###SLICE_VALUE###') T_1,
    (SELECT COUNT(*) FT_BILLED_EXIST FROM MON.SPARK_FT_BILLED_TRANSACTION_PREPAID WHERE TRANSACTION_DATE='###SLICE_VALUE###') T_2,
    (SELECT COUNT(*) FT_CRA_EXIST FROM MON.SPARK_FT_CRA_GPRS WHERE SESSION_DATE='###SLICE_VALUE###') T_3,
    (SELECT COUNT(*) REVENU_LOCALISE_EXIST FROM MON.SPARK_FT_REVENU_LOCALISE WHERE EVENT_DATE ='###SLICE_VALUE###') T_4
