SELECT IF(T_1.TABLE_COUNT = 0 AND T_2.PREV_TABLE_COUNT > 1 AND T_3.IT_OM_SUBSCRIBERS > 1 AND T_4.IT_OMNY_CHANNEL_USERS > 1 AND T_5.IT_OM_ALL_BALANCE > 1,"OK","NOK") FT_EXIST
FROM
(SELECT COUNT(*) TABLE_COUNT FROM cdr.spark_it_omny_account_snapshot WHERE ORIGINAL_FILE_DATE= '###SLICE_VALUE###') T_1,
(SELECT COUNT(*) PREV_TABLE_COUNT FROM cdr.spark_it_omny_account_snapshot WHERE ORIGINAL_FILE_DATE=DATE_SUB("###SLICE_VALUE###",1)) T_2,
(SELECT COUNT(*) IT_OM_SUBSCRIBERS FROM cdr.spark_it_om_subscribers WHERE FILE_DATE=DATE_SUB("###SLICE_VALUE###",1)) T_3,
(SELECT COUNT(*) IT_OMNY_CHANNEL_USERS FROM CDR.SPARK_IT_OMNY_ChannelUsers WHERE ORIGINAL_FILE_DATE=DATE_SUB("###SLICE_VALUE###",1)) T_4,
(SELECT COUNT(*) IT_OM_ALL_BALANCE FROM cdr.spark_it_om_all_balance WHERE ORIGINAL_FILE_DATE=DATE_SUB("###SLICE_VALUE###",1)) T_5