SELECT IF(T_1.TABLE_COUNT = 0 AND T_2.IT_OM_SUBSCRIBERS > 0 ,"OK","NOK") FT_EXIST
FROM
(SELECT COUNT(*) TABLE_COUNT FROM MON.SPARK_FT_OMNY_USER_REGISTRATION WHERE ORIGINAL_FILE_DATE= '###SLICE_VALUE###' and original_file_name like '%Subscribers_%') T_1,
(SELECT COUNT(*) IT_OM_SUBSCRIBERS FROM cdr.spark_it_om_subscribers WHERE FILE_DATE="###SLICE_VALUE###") T_2
