CREATE TABLE DD.SPARK_FT_A_RUPT_RETAILER_OM
(
    PARTENAIRE    VARCHAR(250),
    SITE_NAME    VARCHAR(250),
    MSISDN_COUNT BIGINT,
    NBRE_RUPT    BIGINT,
    INSERT_DATE    TIMESTAMP
)
PARTITIONED BY (EVENT_DATE DATE, EVENT_TIME VARCHAR(250))
STORED AS PARQUET
TBLPROPERTIES ('PARQUET.COMPRESS'='SNAPPY')