SELECT IF(A.NB_EVENT_TIME<B.NB_EVENT_TIME AND C.LOCATION_EXISTS>0 , "OK", "NOK")
FROM
(SELECT COUNT(DISTINCT EVENT_TIME) NB_EVENT_TIME FROM DD.SPARK_FT_A_RUPT_RETAILER_OM WHERE EVENT_DATE = '###SLICE_VALUE###') A,
(SELECT COUNT(DISTINCT EVENT_TIME) NB_EVENT_TIME FROM DD.SPARK_FT_RUPT_RETAILER_OM WHERE EVENT_DATE = '###SLICE_VALUE###') B,
(SELECT COUNT(*) LOCATION_EXISTS FROM MON.SPARK_FT_CLIENT_LAST_SITE_DAY WHERE EVENT_DATE = '###SLICE_VALUE###' OR EVENT_DATE=DATE_SUB('###SLICE_VALUE###', 1)) C