CREATE TABLE AGG.SPARK_FT_A_RAS_RECHARGE_3(
REFILL_DATE   DATE,
SENDER_MSISDN  varchar(10) ,
RECEIVER_MSISDN   varchar(10),
COMMERCIAL_OFFER    varchar(40),
MONTANT_TRANFERT   bigint,
FRAIS              bigint,
NOMBRE             bigint,
DAY_CREDIT         int,
YEAR_CREDIT       int,
MONTH_CREDIT    int,
INSERT_DATE  TIMESTAMP
)
COMMENT ' SPARK_FT_A_RAS_RECHARGE_3 '
 PARTITIONED BY (EVENT_DATE DATE)
 STORED AS PARQUET
 TBLPROPERTIES ("parquet.compress"="SNAPPY")