SELECT IF( FT=0 and CUST>1000 and CONT>10000 and BILL>100 , 'OK', 'NOK' ) TABLES_STATES
FROM  ( SELECT COUNT(*) FT FROM MON.SPARK_FT_BALANCE_AGEE WHERE EVENT_DATE='###SLICE_VALUE###'  ) A,
( SELECT COUNT(*) CUST FROM CDR.SPARK_IT_CUST_FULL WHERE ORIGINAL_FILE_DATE= '###SLICE_VALUE###' ) B,
( SELECT COUNT(*) CONT FROM CDR.SPARK_IT_CONT WHERE ORIGINAL_FILE_DATE='###SLICE_VALUE###' ) C,
( SELECT COUNT(*) BILL FROM CDR.SPARK_IT_BILL WHERE ORIGINAL_FILE_DATE= '###SLICE_VALUE###' ) B,
