SELECT  
DATE_FORMAT(EVENT_DATE, 'dd/MM/yyyy'),
MSISDN,
COMMERCIAL_OFFER,
BYTES_SENT,
BYTES_RECEIVED,
MAIN_RATED_AMOUNT,
BYTES_USED_IN_BUNDLE,
BYTES_USED_OUT_BUNDLE,
BUNDLE_BYTES_REMAINING_VOLUME
FROM MON.SPARK_FT_DATA_CONSO_MSISDN_DAY
WHERE EVENT_DATE =  '###SLICE_VALUE###'