CREATE TABLE MON.SPARK_FT_CLIENT_LAST_SITE_DAY
   (
	MSISDN VARCHAR(25),
	SITE_NAME VARCHAR(50),
	TOWNNAME VARCHAR(50),
	ADMINISTRATIVE_REGION VARCHAR(50),
	COMMERCIAL_REGION VARCHAR(50),
	LAST_LOCATION_DAY TIMESTAMP,
	OPERATOR_CODE VARCHAR(20),
	INSERT_DATE TIMESTAMP
   )
  COMMENT 'FT_CLIENT_LAST_SITE_DAY - FT'
  PARTITIONED BY (EVENT_DATE    DATE)
STORED AS PARQUET TBLPROPERTIES ('PARQUET.COMPRESS'='SNAPPY')
