SELECT IF(A.FT_EXIST = 0 and B.CLIENT_SITE_TRAFFIC_DAY_EXIST>0 AND FT_PREV_EXIST>0,"OK","NOK") FROM
(SELECT COUNT(*) FT_EXIST FROM MON.FT_CLIENT_LAST_SITE_DAY WHERE EVENT_DATE='###SLICE_VALUE###') A,
(SELECT COUNT(*) FT_PREV_EXIST FROM MON.FT_CLIENT_LAST_SITE_DAY WHERE EVENT_DATE=DATE_SUB('###SLICE_VALUE###',1)) A,
(SELECT COUNT(*) CLIENT_SITE_TRAFFIC_DAY_EXIST FROM MON.FT_CLIENT_SITE_TRAFFIC_DAY WHERE EVENT_DATE='###SLICE_VALUE###')B


