CREATE TABLE MON.SPARK_FT_IMEI_TRANSACTION
(
    IMEI VARCHAR(40),
    MSISDN VARCHAR(40),
    SITE_VOIX VARCHAR(40),
    SITE_DATA VARCHAR(40),
    TECHNOLOGIE VARCHAR(40),
    TERMINAL_TYPE VARCHAR(40),
    MSISDN_COUNT DOUBLE,
    NOMBRE_TRANSACTIONS_ENTRANT DOUBLE,
    NOMBRE_TRANSACTIONS_SORTANT DOUBLE,
    DUREE_ENTRANT DOUBLE,
    DUREE_SORTANT DOUBLE,
    VOLUME_DATA_GPRS DOUBLE,
    VOLUME_DATA_GPRS_2G DOUBLE,
    VOLUME_DATA_GPRS_3G DOUBLE,
    VOLUME_DATA_GPRS_4G DOUBLE,
    VOLUME_DATA_OTARIE DOUBLE,
    VOLUME_DATA_OTARIE_2G DOUBLE,
    VOLUME_DATA_OTARIE_3G DOUBLE,
    VOLUME_DATA_OTARIE_4G DOUBLE,
    SRC_TABLE VARCHAR(100),
    INSERT_DATE timestamp

)
PARTITIONED BY(EVENT_DATE DATE)
STORED AS PARQUET
TBLPROPERTIES ("parquet.compress"="SNAPPY")




BACKUP_DWH.FT_IMEI_TRANSACTION