SELECT IF(A.FT_EXIST = 0 and B.FT_COUNT>0 and C.FT_COUNT>0 and D.FT_COUNT>0 and E.FT_COUNT>0, "OK","NOK") FROM
(SELECT COUNT(*) FT_EXIST FROM MON.SPARK_FT_IMEI_TRANSACTION WHERE EVENT_DATE='2020-01-25') A,
(SELECT COUNT(*) FT_COUNT FROM MON.SPARK_FT_OTARIE_DATA_TRAFFIC_DAY WHERE TRANSACTION_DATE='2020-01-25') B,
(SELECT COUNT(*) FT_COUNT FROM MON.SPARK_FT_CRA_GPRS_POST WHERE SESSION_DATE='2020-01-25') C,
(SELECT COUNT(*) FT_COUNT FROM MON.SPARK_FT_CRA_GPRS WHERE SESSION_DATE='2020-01-25') D,
(SELECT COUNT(*) FT_COUNT FROM MON.SPARK_FT_MSC_TRANSACTION WHERE TRANSACTION_DATE='2020-01-25') E
