
INSERT INTO FT_DAILY_STATUS
SELECT '###SLICE_VALUE###' TABLE_DATE,'${hivevar:table_type}' TABLE_TYPE, '${hivevar:table_name}' TABLE_NAME, NB_ROWS,TABLE_INSERT_DATE,LAST_INCIDENT_DAY,CURRENT_TIMESTAMP INSERT_DATE
FROM (
    SELECT COUNT(*) NB_ROWS,MAX(${hivevar:insert_date_column}) TABLE_INSERT_DATE FROM  ${hivevar:database_table_name} WHERE ${hivevar:table_partition}='###SLICE_VALUE###'
)A
LEFT JOIN (SELECT TABLE_NAME,MAX(TABLE_DATE) LAST_INCIDENT_DAY FROM FT_DAILY_STATUS2 WHERE NB_ROWS <1 AND TABLE_DATE<'###SLICE_VALUE###' GROUP BY TABLE_NAME)B

;