ANALYZE TABLE CDR.IT_ZTE_VOICE_SMS PARTITION(START_DATE='###SLICE_VALUE###') COMPUTE STATISTICS FOR COLUMNS;

ANALYZE TABLE CDR.IT_ZTE_DATA PARTITION(START_DATE='###SLICE_VALUE###') COMPUTE STATISTICS FOR COLUMNS;

ANALYZE TABLE CDR.IT_CRA_MSC_HUAWEI PARTITION(CALLDATE='###SLICE_VALUE###') COMPUTE STATISTICS FOR COLUMNS;

ANALYZE TABLE CDR.IT_SMSC_MVAS_A2P PARTITION(WRITE_DATE='###SLICE_VALUE###') COMPUTE STATISTICS FOR COLUMNS;