INSERT  INTO MON.SPARK_FT_POST_DATA_DA_USAGE_DAY
SELECT SESSION_DATE,
MSISDN,
DA_NAME,
MAX(NVL(ACCT_RES_RATING_UNIT, DA_UNIT)) DA_UNIT,
MAX(NVL(ACCT_RES_RATING_TYPE, DA_TYPE)) DA_TYPE,
SUM (CASE WHEN CHARGE >=0 THEN CHARGE ELSE 0 END) POSITIVE_CHARGE_AMOUNT,
SUM (CASE WHEN CHARGE < 0 THEN CHARGE ELSE 0 END) NEGATIVE_CHARGE_AMOUNT,
OPERATOR_CODE,
CONTRACT_TYPE,
COMMERCIAL_PROFILE,
TARIFF_PLAN,
TYPE_OF_MEASUREMENT,
SERVICE_TYPE,
SERVICE_ZONE,
SDP_GOS_SERVICE,
'FT_CRA_GPRS_POST' SOURCE_TABLE,
SYSDATE INSERT_DATE
FROM mon.TT_POST_DATA_DA_USAGE_DAY a
, (SELECT UPPER(ACCT_RES_NAME) ACCT_RES_NAME
, max(ACCT_RES_RATING_TYPE) ACCT_RES_RATING_TYPE
, max(ACCT_RES_RATING_UNIT) ACCT_RES_RATING_UNIT
FROM DIM.DT_BALANCE_TYPE_ITEM
GROUP BY UPPER(ACCT_RES_NAME)
) b
WHERE SESSION_DATE = TO_DATE(s_slice_value,'yyyymmdd')
AND a.DA_NAME = b.ACCT_RES_NAME (+)
GROUP BY SESSION_DATE,
MSISDN,
DA_NAME,
OPERATOR_CODE,
CONTRACT_TYPE,
COMMERCIAL_PROFILE,
TARIFF_PLAN,
TYPE_OF_MEASUREMENT,
SERVICE_TYPE,
SERVICE_ZONE,
SDP_GOS_SERVICE
;