SELECT IF(T_1.FT_EXIST = 0 and T_2.FT_EXIST>0, "OK", "NOK")
FROM
(SELECT COUNT(*) FT_EXIST FROM MON.SPARK_FT_SITE_TRAFFIC_USAGE_DAILY WHERE EVENT_DATE = '###SLICE_VALUE###') T_1,
(SELECT COUNT(*) FT_EXIST FROM MON.SPARK_FT_CELL_TRAFIC_DAYLY WHERE EVENT_DATE = '###SLICE_VALUE###') T_2
