insert into cdr.spark_it_bdi_crm_b2c
select
msisdn,
null as type_personne,
null as nom_prenom,
id_type_piece,
null as type_piece,
numero_piece,
date_expiration,
date_naissance,
date_activation,
case when adresse is null or trim(adresse) = '' then quartier else adresse end as adresse,
quartier,
ville,
statut,
statut_validation_bo,
motif_rejet_bo,
date_validation_bo,
login_validateur_bo,
canal_validateur_bo,
type_abonnement,
csmoddate,
ccmoddate,
compte_client_structure,
nom_structure,
numero_registre_commerce,
numero_piece_representant_legal,
null as imei,
null as statut_derogation,
null as region_administrative,
null as region_commerciale,
null site_name,
null ville_site,
null offre_commerciale,
null type_contrat,
null segmentation,
date_souscription,
date_changement_statut,
ville_structure,
quartier_structure,
raison_statut,
prenom,
nom,
customer_id,
contract_id,
compte_client,
plan_localisation,
contrat_soucription,
acceptation_cgv,
disponibilite_scan,
nom_tuteur,
prenom_tuteur,
date_naissance_tuteur,
numero_piece_tuteur,
date_expiration_tuteur,
id_type_piece_tuteur,
null as type_piece_tuteur,
adresse_tuteur,
identificateur,
localisation_identificateur,
profession,
original_file_name,
original_file_size,
original_file_line_count,
current_timestamp() insert_date,
'###SLICE_VALUE###' original_file_date
from TMP.TT_ZSMART_GAP2 A
left join (select distinct msisdn as num_tel
from cdr.spark_it_bdi_crm_b2c
where original_file_date='###SLICE_VALUE###') B
on substr(upper(trim(A.msisdn)),-9,9) = substr(upper(trim(B.num_tel)),-9,9)
where B.num_tel is null