INSERT INTO TMP.TT_BDI_PERS_MORALE_TMP
SELECT
nvl(A.COMPTE_CLIENT,B.COMPTE_CLIENT),
case when A.COMPTE_CLIENT is null or B.COMPTE_CLIENT is null then nvl(A.RAISON_SOCIALE, B.RAISON_SOCIALE) else trim(B.RAISON_SOCIALE) end AS RAISON_SOCIALE,
case when A.COMPTE_CLIENT is null or B.COMPTE_CLIENT is null then nvl(A.NOM_REPRESENTANT_LEGAL, B.NOM_REPRESENTANT_LEGAL) else trim(B.NOM_REPRESENTANT_LEGAL) end AS NOM_REPRESENTANT_LEGAL,
trim(A.PRENOM_REPRESENTANT_LEGAL) AS  PRENOM_REPRESENTANT_LEGAL,
case when A.COMPTE_CLIENT is null or B.COMPTE_CLIENT is null then nvl(A.CNI_REPRESENTANT_LOCAL, B.CNI_REPRESENTANT_LOCAL) else trim(B.CNI_REPRESENTANT_LOCAL) end AS CNI_REPRESENTANT_LOCAL,
trim(A.CONTACT_TELEPHONIQUE) AS  CONTACT_TELEPHONIQUE,
case when A.COMPTE_CLIENT is null or B.COMPTE_CLIENT is null then nvl(A.VILLE_STRUCTURE, B.VILLE_STRUCTURE) else trim(B.VILLE_STRUCTURE) end AS VILLE_STRUCTURE,
case when A.COMPTE_CLIENT is null or B.COMPTE_CLIENT is null then nvl(A.QUARTIER_STRUCTURE, B.QUARTIER_STRUCTURE) else trim(B.QUARTIER_STRUCTURE) end AS QUARTIER_STRUCTURE,
case when A.COMPTE_CLIENT is null or B.COMPTE_CLIENT is null then nvl(A.ADRESSE_STRUCTURE, B.ADRESSE_STRUCTURE) else trim(B.ADRESSE_STRUCTURE) end AS ADRESSE_STRUCTURE,
case when A.COMPTE_CLIENT is null or B.COMPTE_CLIENT is null then nvl(A.NUMERO_REGISTRE_COMMERCE, B.NUMERO_REGISTRE_COMMERCE) else trim(B.NUMERO_REGISTRE_COMMERCE) end AS NUMERO_REGISTRE_COMMERCE,
trim(A.SMS_CONTACT) AS  SMS_CONTACT,
trim(A.DOC_PLAN_LOCALISATION) AS  DOC_PLAN_LOCALISATION,
trim(A.DOC_FICHE_SOUSCRIPTION) AS  DOC_FICHE_SOUSCRIPTION,
trim(A.ACCEPTATION_CGV) AS  ACCEPTATION_CGV,
trim(A.DOC_ATTESTATION_CNPS) AS  DOC_ATTESTATION_CNPS,
trim(A.DOC_RCCM) AS  DOC_RCCM,
trim(A.DISPONIBILITE_SCAN) AS  DISPONIBILITE_SCAN,
case when A.COMPTE_CLIENT is null or B.COMPTE_CLIENT is null then nvl(A.type_client, B.typeclient) else trim(B.typeclient) end AS type_client
FROM (SELECT * FROM  CDR.SPARK_IT_BDI_PERS_MORALE WHERE ORIGINAL_FILE_DATE=DATE_SUB('###SLICE_VALUE###',1)) A
FULL OUTER JOIN
(SELECT * FROM CDR.SPARK_IT_BDI_CRM_B2B where original_file_date = '###SLICE_VALUE###') B
ON trim(A.compte_client) = trim(B.compte_client)