SELECT IF(A.IT_BDI_FIN_EXIST = 0 and B.it_bdi_EXIST=0 and C.IT_BDI_LIGNE_FLOTTE_EXIST=0 and D.IT_BDI_PERS_MORALE_EXIST=0
and E.it_bdi_crm_b2c_EXIST >0 AND F.it_bdi_hlr_EXISTS>0 AND G.IT_BDI_ZSMART_EXISTS>0 AND H.IT_BDI_ZSMART_EXISTS>0 AND I.IT_BDI_CRM_B2B_EXISTS>0 AND
J.ZSMART_SIZE_IS_OK>4000000000 AND K.hlr_nb_file_is_ok=6 AND L.IT_BDI_TMP_EXITE>0 AND M.PREV_IT_BDI_PERS_MORALE_EXIST>0,"OK","NOK") FROM
(SELECT COUNT(*)  IT_BDI_FIN_EXIST FROM CDR.SPARK_IT_BDI WHERE original_file_date='###SLICE_VALUE###') A,
(SELECT COUNT(*)  it_bdi_EXIST FROM cdr.spark_it_bdi WHERE original_file_date='###SLICE_VALUE###') B,
(SELECT COUNT(*)  IT_BDI_LIGNE_FLOTTE_EXIST FROM CDR.SPARK_IT_BDI_LIGNE_FLOTTE WHERE original_file_date='###SLICE_VALUE###') C,
(SELECT COUNT(*) IT_BDI_PERS_MORALE_EXIST FROM CDR.SPARK_IT_BDI_PERS_MORALE WHERE original_file_date='###SLICE_VALUE###') D,
(SELECT COUNT(*) it_bdi_crm_b2c_EXIST FROM CDR.SPARK_it_bdi_crm_b2c WHERE original_file_date= '###SLICE_VALUE###' )E,
(SELECT COUNT(*) it_bdi_hlr_EXISTS FROM CDR.spark_it_bdi_hlr WHERE original_file_date='###SLICE_VALUE###') F,
(SELECT COUNT(*) IT_BDI_ZSMART_EXISTS FROM CDR.SPARK_IT_BDI_ZSMART  WHERE original_file_date='###SLICE_VALUE###')G,
(SELECT COUNT(*) IT_BDI_ZSMART_EXISTS FROM MON.SPARK_FT_MSISDN_IMEI_LOCALISATION_TO_BDI WHERE EVENT_DATE='###SLICE_VALUE###') H,
(SELECT COUNT(*) IT_BDI_CRM_B2B_EXISTS FROM CDR.SPARK_IT_BDI_CRM_B2B WHERE original_file_date='###SLICE_VALUE###') I,
(SELECT distinct  original_file_size ZSMART_SIZE_IS_OK FROM CDR.SPARK_IT_BDI_ZSMART  WHERE original_file_date='###SLICE_VALUE###') J,
(SELECT count(distinct  original_file_name) hlr_nb_file_is_ok FROM CDR.spark_it_bdi_hlr WHERE original_file_date='###SLICE_VALUE###') K,
(SELECT count(*) IT_BDI_TMP_EXITE FROM CDR.SPARK_IT_BDI_TMP WHERE original_file_date=DATE_SUB('###SLICE_VALUE###',1)) L,
(SELECT COUNT(*) PREV_IT_BDI_PERS_MORALE_EXIST FROM CDR.SPARK_IT_BDI_PERS_MORALE WHERE original_file_date=DATE_SUB('###SLICE_VALUE###',1)) M