SELECT IF(T_1.FT_COUNT = 0 AND T_2.FT_OMNY_ACCOUNT_SNAPSHOT > 1,"OK","NOK") FT_EXIST
FROM
(SELECT COUNT(*) FT_COUNT FROM MON.FT_OMNY_BALANCE_SNAPSHOT WHERE EVENT_DATE="###SLICE_VALUE###") T_1,
(SELECT COUNT(*) FT_OMNY_ACCOUNT_SNAPSHOT FROM MON.FT_OMNY_ACCOUNT_SNAPSHOT WHERE EVENT_DATE="###SLICE_VALUE###") T_2