SELECT IF(FT_A_NOT_EXISTS = 0 and FT_EXISTS>0 and FT_PREV_EXISTS>0 ,"OK","NOK") TABLES_EXIST
FROM
(SELECT COUNT(*) FT_A_NOT_EXISTS FROM AGG.SPARK_FT_A_EDR_PRPD_EQT WHERE EVENT_DAY='###SLICE_VALUE###') A,
(SELECT COUNT(*) FT_EXISTS FROM MON.SPARK_FT_EDR_PRPD_EQT WHERE EVENT_DATE='###SLICE_VALUE###') B,
(SELECT COUNT(*) FT_PREV_EXISTS FROM MON.SPARK_FT_EDR_PRPD_EQT WHERE EVENT_DATE=DATE_SUB('###SLICE_VALUE###',1)) D