CREATE EXTERNAL TABLE CDR.TT_PARRAINAGE_ACCESSPRO (
ORIGINAL_FILE_NAME VARCHAR(200), 
ORIGINAL_FILE_SIZE INT, 
ORIGINAL_FILE_LINE_COUNT INT, 
numero_comando VARCHAR(15),
numero_migre VARCHAR(15),
date_migration TIMESTAMP,
offre_migree VARCHAR(100)
) 
ROW FORMAT DELIMITED FIELDS TERMINATED BY ';' 
LOCATION '/PROD/TT/PARRAINAGE_ACCESSPRO' 
TBLPROPERTIES ('serialization.null.format'='');