
CREATE TABLE MON.SPARK_FT_CLIENT_LAST_SITE_LOCATION
(
    MSISDN VARCHAR(25),
    SITE_NAME VARCHAR(50),
    LAST_LOCATION_MONTH VARCHAR(6),
    TOWNNAME VARCHAR(50),
    ADMINISTRATIVE_REGION VARCHAR(50),
    COMMERCIAL_REGION VARCHAR(50),
    OPERATOR_CODE VARCHAR(20),
    REFRESH_DATE DATE,
    INSERT_DATE TIMESTAMP
) 
PARTITIONED BY (EVENT_MONTH VARCHAR(10))
STORED AS PARQUET
TBLPROPERTIES ('PARQUET.COMPRESS'='SNAPPY')