CREATE TABLE IF NOT EXISTS MON.TT_CLIENT_CELL_TRAFIC_DAY
   (

	MSISDN VARCHAR(40),
	LOCATION_CI VARCHAR(5),
	DUREE_SORTANT INT,
	NBRE_TEL_SORTANT INT,
	DUREE_ENTRANT INT,
	NBRE_TEL_ENTRANT INT,
	NBRE_SMS_SORTANT INT,
	NBRE_SMS_ENTRANT INT,
	SERVED_PARTY_LOCATION VARCHAR(25),
	OPERATOR_CODE VARCHAR(4000),
	EVENT_DATE DATE
   )
 STORED AS ORC TBLPROPERTIES ('transactional'='true',"orc.compress"="ZLIB","orc.stripe.size"="67108864");


