SELECT IF(T_1.FT_EXIST > 0 and T_2.FT_EXIST=0,"OK","NOK") FROM
(SELECT COUNT(*) FT_EXIST FROM MON.SPARK_FT_GSM_LOCATION_REVENUE_DAILY WHERE TRANSACTION_DATE = '###SLICE_VALUE###'  ) T_1,
(SELECT COUNT(*) FT_EXIST FROM MON.SPARK_FT_GSM_SITE_REVENU_DAILY WHERE TRANSACTION_DATE = '###SLICE_VALUE###') T_2