SELECT IF(
    T_1.COUNT_ALL_USERS > 0
    AND 
    T_2.NB_EXPORT < 1
    , "OK"
    , "NOK"
)
FROM
(SELECT COUNT(*) COUNT_ALL_USERS FROM CDR.SPARK_IT_OM_ALL_USERS WHERE ORIGINAL_FILE_DATE='###SLICE_VALUE###') T_1,
(
    SELECT COUNT(*) NB_EXPORT FROM
    (SELECT * FROM (SELECT * FROM MON.EXPORT_HISTORY WHERE EVENT_DATE='###SLICE_VALUE###' AND JOB_INSTANCEID='${hivevar:job_instanceid}' ORDER BY INSERT_DATE DESC LIMIT 1)  T where T.STATUS = 'OK') M
) T_2
