CREATE TABLE AGG.SPARK_FT_A_REPORTING_INTERCO (
    OPERATEUR VARCHAR(400),
    NBR_UNIQ_USER VARCHAR(400),
    TYPE_SERVICE VARCHAR(400),
    TYPE_APPEL VARCHAR(400),
    TYPE_HEURE VARCHAR(400),
    NOMBRE_TRANSACTION VARCHAR(400),
    VOLUME VARCHAR(400),
    REVENU VARCHAR(400),
    CHARGE VARCHAR(400),
    INSERT_DATE TIMESTAMP
)
PARTITIONED BY (PROCESSING_DATE DATE)
STORED AS PARQUET
TBLPROPERTIES ("parquet.compress"="SNAPPY")