INSERT INTO AGG.SPARK_REGIONAL_DOM_DASHBOARD
SELECT
     X.POSITION,
     X.DESCRIPTION,
     TRIM(COALESCE(upper(REPLACE(site.administrative_region_b,'Ê','E')),upper(REPLACE(site.administrative_region_a,'Ê','E')), 'INCONNU'))  REGION,
    SUM(X.VOL) VOL,
    SUM(X.VAL) VAL,
    ROUND(SUM(X.REVENU),0) REVENU,
    ROUND(SUM(X.COMM),0) COMM,
    ROUND(SUM(X.FRAIS),0) FRAIS,
    X.JOUR
FROM
    (SELECT
        TRANSFER_DATETIME JOUR,
       1.0 POSITION,
        'P2P' DESCRIPTION,
        SENDER_MSISDN MSISDN,
        COUNT(CASE WHEN UPPER(RECEIVER_GRADE_NAME) NOT LIKE '%INFORMEL%' THEN 1 ELSE NULL END) VOL,
        SUM(CASE WHEN UPPER(RECEIVER_GRADE_NAME) NOT LIKE '%INFORMEL%' THEN TRANSACTION_AMOUNT ELSE 0 END) VAL,
        SUM(SERVICE_CHARGE_RECEIVED) REVENU,
        SUM(COMMISSIONS_PAID) COMM,
        SUM(COMMISSIONS_RECEIVED) FRAIS
    FROM CDR.SPARK_IT_OMNY_TRANSACTIONS2
    WHERE
        TRANSFER_DATETIME ='###SLICE_VALUE###' AND
        TRANSFER_STATUS='TS' AND SUBSTR(TRANSFER_ID, 1, 2) IN ('PP') AND
        SENDER_CATEGORY_CODE = 'SUBS' AND
        RECEIVER_MSISDN NOT IN (SELECT MSISDN FROM BACKUP_DWH.OM_TEST_MSISDNS) AND
        SENDER_MSISDN NOT IN (SELECT MSISDN FROM BACKUP_DWH.OM_TEST_MSISDNS)
    GROUP BY TRANSFER_DATETIME, SENDER_MSISDN
    UNION ALL
    SELECT
        TRANSFER_DATETIME JOUR,
       2.0 POSITION,
        'TNO' DESCRIPTION,
        SENDER_MSISDN MSISDN,
        COUNT(*) VOL,
        SUM(TRANSACTION_AMOUNT) VAL,
        SUM(SERVICE_CHARGE_RECEIVED) REVENU,
        SUM(COMMISSIONS_PAID) COMM,
        SUM(COMMISSIONS_RECEIVED) FRAIS
    FROM CDR.SPARK_IT_OMNY_TRANSACTIONS2
    WHERE
        TRANSFER_STATUS='TS' AND
        SUBSTR(TRANSFER_ID,1,2)='PN' AND
        TRANSFER_DATETIME ='###SLICE_VALUE###'
    GROUP BY TRANSFER_DATETIME, SENDER_MSISDN
    UNION ALL
    SELECT
        TRANSFER_DATETIME JOUR,
       3.0 POSITION,
        'Cash-out' DESCRIPTION,
        SENDER_MSISDN MSISDN,
        COUNT(*) VOL,
        SUM(TRANSACTION_AMOUNT) VAL,
        SUM(SERVICE_CHARGE_RECEIVED) REVENU,
        SUM(COMMISSIONS_PAID) COMM,
        SUM(COMMISSIONS_RECEIVED) FRAIS
    FROM CDR.SPARK_IT_OMNY_TRANSACTIONS2
    WHERE
        TRANSFER_DATETIME ='###SLICE_VALUE###' AND
        TRANSFER_STATUS = 'TS' AND
        RECEIVER_MSISDN NOT IN (SELECT MSISDN FROM BACKUP_DWH.OM_TEST_MSISDNS UNION ALL SELECT MSISDN FROM BACKUP_DWH.MSISDN_VISA UNION ALL
            SELECT MSISDN FROM BACKUP_DWH.MSISDN_B2W UNION ALL SELECT MSISDN FROM BACKUP_DWH.MSISDN_GIMAC) AND
        SENDER_MSISDN NOT IN (SELECT MSISDN FROM BACKUP_DWH.OM_TEST_MSISDNS UNION ALL SELECT MSISDN FROM BACKUP_DWH.MSISDN_VISA UNION ALL
            SELECT MSISDN FROM BACKUP_DWH.MSISDN_B2W UNION ALL SELECT MSISDN FROM BACKUP_DWH.MSISDN_GIMAC) AND
        SUBSTR(TRANSFER_ID, 1, 2)='CO'
    GROUP BY TRANSFER_DATETIME, SENDER_MSISDN
    UNION ALL
    SELECT
        TRANSFER_DATETIME JOUR,
       4.0 POSITION,
        'Cash-out Offnet' DESCRIPTION,
        RECEIVER_MSISDN MSISDN,
        COUNT(*) VOL,
       SUM(TRANSACTION_AMOUNT) VAL,
        SUM(SERVICE_CHARGE_RECEIVED) REVENU,
        SUM(COMMISSIONS_PAID) COMM,
        SUM(COMMISSIONS_RECEIVED) FRAIS
    FROM CDR.SPARK_IT_OMNY_TRANSACTIONS2
    WHERE
        TRANSFER_STATUS='TS' AND
        SUBSTR(TRANSFER_ID,1,2)='CN' AND
        TRANSFER_DATETIME ='###SLICE_VALUE###'
    GROUP BY TRANSFER_DATETIME, RECEIVER_MSISDN
--/*     UNION ALL
--    SELECT
--        TRANSFER_DATETIME JOUR,
--       5.0 POSITION,
--        'FEE_B2B_TRANSACTION (Trx Agent 2 Agent)' DESCRIPTION,
--        SENDER_MSISDN MSISDN,
--        COUNT(*) VOL,
--        SUM(TRANSACTION_AMOUNT) VAL,
--        SUM(SERVICE_CHARGE_RECEIVED) REVENU,
--        SUM(COMMISSIONS_PAID) COMM,
--        SUM(COMMISSIONS_RECEIVED) FRAIS
--    FROM CDR.SPARK_IT_OMNY_TRANSACTIONS2
--    WHERE
--        TRANSFER_STATUS='TS' AND
--        SENDER_CATEGORY_CODE<>'SUBS' AND
--        RECEIVER_CATEGORY_CODE<>'SUBS' AND
--        SUBSTR(TRANSFER_ID,1,2)='PP' AND
--        TRANSFER_DATETIME ='###SLICE_VALUE###'
--    GROUP BY TRANSFER_DATETIME, SENDER_MSISDN */
    UNION ALL
    SELECT
        TRANSFER_DATETIME JOUR,
       6.0 POSITION,
        'B2W' DESCRIPTION,
        RECEIVER_MSISDN MSISDN,
        COUNT(*) VOL,
        SUM(TRANSACTION_AMOUNT) VAL,
        SUM(SERVICE_CHARGE_RECEIVED) REVENU,
        SUM(COMMISSIONS_PAID) COMM,
        SUM(COMMISSIONS_RECEIVED) FRAIS
    FROM CDR.SPARK_IT_OMNY_TRANSACTIONS2
    WHERE
        TRANSFER_STATUS='TS' AND
        SENDER_MSISDN IN (SELECT MSISDN FROM BACKUP_DWH.MSISDN_B2W) AND
        SUBSTR(TRANSFER_ID,1,2)='CI' AND
        TRANSFER_DATETIME ='###SLICE_VALUE###'
    GROUP BY TRANSFER_DATETIME, RECEIVER_MSISDN
    UNION ALL
    SELECT
        TRANSFER_DATETIME JOUR,
       7.0 POSITION,
        'W2B' DESCRIPTION,
        SENDER_MSISDN MSISDN,
        COUNT(*) VOL,
        SUM(TRANSACTION_AMOUNT) VAL,
        SUM(SERVICE_CHARGE_RECEIVED) REVENU,
        SUM(COMMISSIONS_PAID) COMM,
        SUM(COMMISSIONS_RECEIVED) FRAIS
    FROM CDR.SPARK_IT_OMNY_TRANSACTIONS2
    WHERE
        TRANSFER_STATUS='TS' AND
        RECEIVER_MSISDN IN (SELECT MSISDN FROM BACKUP_DWH.MSISDN_B2W) AND
        SUBSTR(TRANSFER_ID,1,2)='CO' AND
        TRANSFER_DATETIME ='###SLICE_VALUE###'
    GROUP BY TRANSFER_DATETIME, SENDER_MSISDN
    UNION ALL
    SELECT
        TRANSFER_DATETIME JOUR,
        8.1 POSITION,
        'ENEO' DESCRIPTION,
        SENDER_MSISDN MSISDN,
        COUNT(*) VOL,
        SUM(TRANSACTION_AMOUNT) VAL,
        ROUND(SUM(CASE WHEN
        SERVICE_CHARGE_RECEIVED > 0 THEN SERVICE_CHARGE_RECEIVED
        WHEN TRANSACTION_AMOUNT BETWEEN 0 AND 4999 THEN 100
        WHEN TRANSACTION_AMOUNT BETWEEN 5000 AND 10000 THEN 220
        WHEN TRANSACTION_AMOUNT BETWEEN 10001 AND 25000 THEN 400
        WHEN TRANSACTION_AMOUNT BETWEEN 25001 AND 50000 THEN 400
        WHEN TRANSACTION_AMOUNT BETWEEN 50001 AND 100000 THEN 500
        ELSE 750 END)*0.6,0) REVENU,
        SUM(COMMISSIONS_PAID) COMM,
        SUM(COMMISSIONS_RECEIVED) FRAIS
    FROM CDR.SPARK_IT_OMNY_TRANSACTIONS2
    WHERE
        TRANSFER_STATUS='TS' AND
        TRANSFER_DATETIME ='###SLICE_VALUE###' AND
        SUBSTR(TRANSFER_ID,1,2) IN ('BP','MP','IN') AND
        RECEIVER_MSISDN  IN (SELECT MSISDN FROM BACKUP_DWH.MSISDN_ENEO) AND SENDER_MSISDN NOT IN (SELECT MSISDN FROM BACKUP_DWH.OM_TEST_MSISDNS)
    GROUP BY TRANSFER_DATETIME, SENDER_MSISDN
    UNION ALL
    SELECT
        TRANSFER_DATETIME JOUR,
        8.2 POSITION,
        'CANAL' DESCRIPTION,
        SENDER_MSISDN MSISDN,
        COUNT(*) VOL,
        SUM(TRANSACTION_AMOUNT) VAL,
        SUM(SERVICE_CHARGE_RECEIVED) REVENU,
        SUM(COMMISSIONS_PAID) COMM,
        SUM(COMMISSIONS_RECEIVED) FRAIS
    FROM CDR.SPARK_IT_OMNY_TRANSACTIONS2
    WHERE
        TRANSFER_STATUS = 'TS' AND
        TRANSFER_DATETIME ='###SLICE_VALUE###' AND
        RECEIVER_MSISDN IN ('699703939') AND
        SENDER_MSISDN NOT IN (SELECT MSISDN FROM BACKUP_DWH.OM_TEST_MSISDNS) AND
        SUBSTR(TRANSFER_ID, 1, 2) IN ('MP' )
    GROUP BY TRANSFER_DATETIME, SENDER_MSISDN
    UNION ALL
    SELECT
        TRANSFER_DATETIME JOUR,
        8.3 POSITION,
        'CAMWATER' DESCRIPTION,
        SENDER_MSISDN MSISDN,
        COUNT(*) VOL,
        SUM(TRANSACTION_AMOUNT) VAL,
        SUM(SERVICE_CHARGE_RECEIVED) REVENU,
        SUM(COMMISSIONS_PAID) COMM,
        SUM(COMMISSIONS_RECEIVED) FRAIS
    FROM CDR.SPARK_IT_OMNY_TRANSACTIONS2
    WHERE
        TRANSFER_STATUS='TS' AND
        TRANSFER_DATETIME ='###SLICE_VALUE###' AND
        SUBSTR(TRANSFER_ID,1,2) IN ('BP','MP', 'IN') AND
        RECEIVER_MSISDN  IN (SELECT MSISDN FROM BACKUP_DWH.MSISDN_EAU) AND SENDER_MSISDN NOT IN (SELECT MSISDN FROM BACKUP_DWH.OM_TEST_MSISDNS)
    GROUP BY TRANSFER_DATETIME, SENDER_MSISDN
    UNION ALL
    SELECT
        TRANSFER_DATETIME JOUR,
        8.4 POSITION,
        'Autre' DESCRIPTION,
        SENDER_MSISDN MSISDN,
        COUNT(*) VOL,
        SUM(TRANSACTION_AMOUNT) VAL,
        SUM(SERVICE_CHARGE_RECEIVED) REVENU,
        SUM(COMMISSIONS_PAID) COMM,
        SUM(COMMISSIONS_RECEIVED) FRAIS
    FROM CDR.SPARK_IT_OMNY_TRANSACTIONS2
    WHERE
        TRANSFER_STATUS='TS' AND
        TRANSFER_DATETIME ='###SLICE_VALUE###' AND
        SUBSTR(TRANSFER_ID,1,2) = 'BP' AND
        RECEIVER_MSISDN NOT IN (SELECT MSISDN FROM BACKUP_DWH.MSISDN_EAU UNION ALL SELECT '699703939' UNION ALL
        SELECT 'AES'  UNION ALL SELECT MSISDN FROM BACKUP_DWH.ENEOPREPAID_MSISDNS UNION ALL SELECT MSISDN FROM BACKUP_DWH.OM_TEST_MSISDNS) AND
        SENDER_MSISDN NOT IN (SELECT MSISDN FROM BACKUP_DWH.OM_TEST_MSISDNS)
    GROUP BY TRANSFER_DATETIME, SENDER_MSISDN
    UNION ALL
    SELECT
        TRANSFER_DATETIME JOUR,
       9.0 POSITION,
        'Paiement Marchands' DESCRIPTION,
        SENDER_MSISDN MSISDN,
        COUNT(*) VOL,
        SUM(TRANSACTION_AMOUNT) VAL,
        SUM(SERVICE_CHARGE_RECEIVED + COMMISSIONS_RECEIVED) REVENU,
        SUM(COMMISSIONS_PAID) COMM,
        SUM(COMMISSIONS_RECEIVED) FRAIS
    FROM CDR.SPARK_IT_OMNY_TRANSACTIONS2
    WHERE
        TRANSFER_STATUS='TS' AND
        TRANSFER_DATETIME ='###SLICE_VALUE###' AND
        SUBSTR(TRANSFER_ID,1,2) = 'MP' AND
        RECEIVER_MSISDN NOT IN (SELECT MSISDN FROM BACKUP_DWH.NON_MERCHANT_MSISDNS UNION ALL SELECT MSISDN FROM BACKUP_DWH.OM_TEST_MSISDNS) AND
        SENDER_MSISDN NOT IN (SELECT MSISDN FROM BACKUP_DWH.OM_TEST_MSISDNS)
    GROUP BY TRANSFER_DATETIME, SENDER_MSISDN
    UNION ALL
    SELECT
        TRANSFER_DATETIME JOUR,
       9.0 POSITION,
        'Paiement Marchands' DESCRIPTION,
        SENDER_MSISDN MSISDN,
        COUNT(*) VOL,
        SUM(TRANSACTION_AMOUNT) VAL,
        SUM(COMMISSIONS_RECEIVED) REVENU,
        SUM(COMMISSIONS_PAID) COMM,
        NULL FRAIS
    FROM CDR.SPARK_IT_OMNY_TRANSACTIONS2
    WHERE
        TRANSFER_STATUS='TS' AND
        UPPER(RECEIVER_GRADE_NAME) LIKE '%INFORMEL%' AND
        SUBSTR(TRANSFER_ID,1,2)='PP' AND
        TRANSFER_DATETIME ='###SLICE_VALUE###' AND
        (RECEIVER_MSISDN NOT IN (SELECT MSISDN FROM BACKUP_DWH.OM_TEST_MSISDNS))
    GROUP BY TRANSFER_DATETIME, SENDER_MSISDN
    UNION ALL
    SELECT
        TRANSFER_DATETIME JOUR,
       9.0 POSITION,
        'Paiement Marchands' DESCRIPTION,
        SENDER_MSISDN MSISDN,
        NULL VOL,
        NULL VAL,
        SUM(SERVICE_CHARGE_RECEIVED + COMMISSIONS_RECEIVED) REVENU,
        NULL COMM,
        NULL FRAIS
    FROM CDR.SPARK_IT_OMNY_TRANSACTIONS2
    WHERE
        TRANSFER_STATUS='TS' AND
        SENDER_CATEGORY_CODE<>'SUBS' AND
        RECEIVER_CATEGORY_CODE<>'SUBS' AND
        SUBSTR(TRANSFER_ID,1,2)='PP' AND
        TRANSFER_DATETIME ='###SLICE_VALUE###'
    GROUP BY TRANSFER_DATETIME, SENDER_MSISDN
    UNION ALL
    SELECT
        TRANSFER_DATETIME JOUR,
       9.0 POSITION,
        'Paiement Marchands' DESCRIPTION,
        RECEIVER_MSISDN MSISDN,
        NULL VOL,
        NULL VAL,
        SUM(SERVICE_CHARGE_RECEIVED + COMMISSIONS_RECEIVED) REVENU,
        NULL COMM,
        NULL FRAIS
    FROM CDR.SPARK_IT_OMNY_TRANSACTIONS2
    WHERE
        TRANSFER_STATUS='TS' AND
        UPPER(SENDER_DOMAIN_CODE) NOT LIKE 'B2W%' AND
        RECEIVER_CATEGORY_CODE='SUBS' AND
        SUBSTR(TRANSFER_ID,1,2)='CI' AND
        TRANSFER_DATETIME ='###SLICE_VALUE###'
    GROUP BY TRANSFER_DATETIME, RECEIVER_MSISDN
--/*     UNION ALL
--    SELECT
--        TRANSFER_DATETIME JOUR,
--        9.1 POSITION,
--        'Web Payment' DESCRIPTION,
--        SENDER_MSISDN MSISDN,
--        COUNT(*) VOL,
--        SUM(TRANSACTION_AMOUNT) VAL,
--        SUM(SERVICE_CHARGE_RECEIVED + COMMISSIONS_RECEIVED) REVENU,
--        SUM(COMMISSIONS_PAID) COMM,
--        NULL FRAIS
--    FROM
--        CDR.SPARK_IT_OMNY_TRANSACTIONS2 A
--    WHERE
--        TRANSFER_STATUS='TS' AND
--        TRANSFER_DATETIME ='###SLICE_VALUE###' AND
--        SUBSTR(TRANSFER_ID,1,2)='MP' AND
--        SENDER_CATEGORY_CODE='SUBS' AND
--        RECEIVER_MSISDN IN (SELECT DISTINCT MSISDN FROM REF_OM_PRODUCTS
--            WHERE REF_DATE=(SELECT MAX(REF_DATE) FROM REF_OM_PRODUCTS B WHERE REF_DATE<=TO_DATE('22102020 235959','DDMMYYYY HH24MISS')) AND
--        UPPER(TECHNOLOGY) LIKE '%WEB%') AND
--        (RECEIVER_MSISDN NOT IN (SELECT MSISDN FROM BACKUP_DWH.OM_TEST_MSISDNS UNION ALL SELECT MSISDN FROM BACKUP_DWH.NON_MERCHANT_MSISDNS) AND
--        SENDER_MSISDN NOT IN (SELECT MSISDN FROM BACKUP_DWH.OM_TEST_MSISDNS UNION ALL SELECT MSISDN FROM BACKUP_DWH.NON_MERCHANT_MSISDNS))
--    GROUP BY TRANSFER_DATETIME, SENDER_MSISDN */
    UNION ALL
    SELECT
        TRANSFER_DATETIME JOUR,
       10.0 POSITION,
        'Paiement de masse' DESCRIPTION,
        RECEIVER_MSISDN MSISDN,
        COUNT(*) VOL,
        SUM(TRANSACTION_AMOUNT) VAL,
        SUM(SERVICE_CHARGE_RECEIVED) REVENU,
        SUM(COMMISSIONS_PAID) COMM,
        SUM(COMMISSIONS_RECEIVED) FRAIS
    FROM CDR.SPARK_IT_OMNY_TRANSACTIONS2
    WHERE
        TRANSFER_STATUS='TS' AND
        TRANSFER_DATETIME ='###SLICE_VALUE###' AND
        SUBSTR(TRANSFER_ID,1,2)='ER'
    GROUP BY TRANSFER_DATETIME, RECEIVER_MSISDN
--   /*  UNION ALL
--    SELECT
--        TRANSFER_DATETIME JOUR,
--       11.0 POSITION,
--        'Remontée de Fonds' DESCRIPTION,
--        SENDER_MSISDN MSISDN,
--        COUNT(*) VOL,
--        SUM(TRANSACTION_AMOUNT) VAL,
--        SUM(SERVICE_CHARGE_RECEIVED + COMMISSIONS_RECEIVED) REVENU,
--        SUM(COMMISSIONS_PAID) COMM,
--        NULL FRAIS
--    FROM
--        CDR.SPARK_IT_OMNY_TRANSACTIONS2 A
--    WHERE
--        TRANSFER_STATUS='TS' AND
--        TRANSFER_DATETIME ='###SLICE_VALUE###' AND
--        SUBSTR(TRANSFER_ID,1,2)='MP' AND
--        SENDER_CATEGORY_CODE='SUBS' AND
--        RECEIVER_MSISDN IN (SELECT DISTINCT MSISDN FROM REF_OM_PRODUCTS
--            WHERE REF_DATE=(SELECT MAX(REF_DATE) FROM REF_OM_PRODUCTS B WHERE REF_DATE<=TO_DATE('22102020 235959','DDMMYYYY HH24MISS')) AND
--        UPPER(PRODUCT) LIKE '%FOND%') AND
--        (RECEIVER_MSISDN NOT IN (SELECT MSISDN FROM BACKUP_DWH.OM_TEST_MSISDNS UNION ALL SELECT MSISDN FROM BACKUP_DWH.NON_MERCHANT_MSISDNS) AND
--        SENDER_MSISDN NOT IN (SELECT MSISDN FROM BACKUP_DWH.OM_TEST_MSISDNS UNION ALL SELECT MSISDN FROM BACKUP_DWH.NON_MERCHANT_MSISDNS))
--    GROUP BY TRANSFER_DATETIME, SENDER_MSISDN */
    UNION ALL
    SELECT
        TRANSFER_DATETIME JOUR,
        12.1 POSITION,
        'Top Up' DESCRIPTION,
        SENDER_MSISDN MSISDN,
        COUNT(*) VOL,
        SUM(TRANSACTION_AMOUNT) VAL,
        SUM(SERVICE_CHARGE_RECEIVED) REVENU,
        SUM(COMMISSIONS_PAID) COMM,
        SUM(COMMISSIONS_RECEIVED) FRAIS
    FROM CDR.SPARK_IT_OMNY_TRANSACTIONS2
    WHERE
        TRANSFER_STATUS='TS' AND
        TRANSFER_DATETIME ='###SLICE_VALUE###' AND
        SUBSTR(TRANSFER_ID,1,2) = 'RC'
    GROUP BY TRANSFER_DATETIME, SENDER_MSISDN
    UNION ALL
    SELECT
        TRANSFER_DATETIME JOUR,
        12.2 POSITION,
        'Data' DESCRIPTION,
        SENDER_MSISDN MSISDN,
        COUNT(*) VOL,
        SUM(TRANSACTION_AMOUNT) VAL,
        SUM(SERVICE_CHARGE_RECEIVED) REVENU,
        SUM(COMMISSIONS_PAID) COMM,
        SUM(COMMISSIONS_RECEIVED) FRAIS
    FROM CDR.SPARK_IT_OMNY_TRANSACTIONS2
    WHERE
        TRANSFER_STATUS='TS' AND
        TRANSFER_DATETIME ='###SLICE_VALUE###' AND
        SUBSTR(TRANSFER_ID,1,2) = 'MP' AND
        RECEIVER_MSISDN IN (SELECT MSISDN FROM BACKUP_DWH.INTERNET_MSISDNS) AND SENDER_MSISDN NOT IN (SELECT MSISDN FROM BACKUP_DWH.OM_TEST_MSISDNS)
    GROUP BY TRANSFER_DATETIME, SENDER_MSISDN
    UNION ALL
    SELECT
        TRANSFER_DATETIME JOUR,
       0.0 POSITION,
        'Cash In' DESCRIPTION,
        SENDER_MSISDN MSISDN,
        COUNT(*) VOL,
        SUM(TRANSACTION_AMOUNT) VAL,
        SUM(SERVICE_CHARGE_RECEIVED) REVENU,
        SUM(COMMISSIONS_PAID) COMM,
        SUM(COMMISSIONS_RECEIVED) FRAIS
    FROM CDR.SPARK_IT_OMNY_TRANSACTIONS2
    WHERE
        TRANSFER_STATUS='TS' AND
        TRANSFER_DATETIME ='###SLICE_VALUE###' AND
        SUBSTR(TRANSFER_ID,1,2)='CI' AND
        RECEIVER_CATEGORY_CODE='SUBS' AND
        RECEIVER_MSISDN NOT IN (SELECT MSISDN FROM BACKUP_DWH.OM_TEST_MSISDNS UNION ALL SELECT MSISDN FROM BACKUP_DWH.MSISDN_VISA UNION ALL
            SELECT MSISDN FROM BACKUP_DWH.MSISDN_B2W UNION ALL SELECT MSISDN FROM BACKUP_DWH.MSISDN_GIMAC) AND
        SENDER_MSISDN NOT IN (SELECT MSISDN FROM BACKUP_DWH.OM_TEST_MSISDNS UNION ALL SELECT MSISDN FROM BACKUP_DWH.MSISDN_VISA UNION ALL
            SELECT MSISDN FROM BACKUP_DWH.MSISDN_B2W UNION ALL SELECT MSISDN FROM BACKUP_DWH.MSISDN_GIMAC)
    GROUP BY TRANSFER_DATETIME, SENDER_MSISDN
    UNION ALL
    SELECT
        TRANSFER_DATETIME JOUR,
       13.0 POSITION,
        'Visa' DESCRIPTION,
        SENDER_MSISDN MSISDN,
        COUNT(*) VOL,
        SUM(TRANSACTION_AMOUNT) VAL,
        SUM(SERVICE_CHARGE_RECEIVED) REVENU,
        SUM(COMMISSIONS_PAID) COMM,
        SUM(COMMISSIONS_RECEIVED) FRAIS
    FROM CDR.SPARK_IT_OMNY_TRANSACTIONS2
    WHERE
        TRANSFER_STATUS='TS' AND
        TRANSFER_DATETIME ='###SLICE_VALUE###' AND
        SUBSTR(TRANSFER_ID,1,2) IN ('CO','MP') AND
        RECEIVER_MSISDN IN (SELECT MSISDN FROM BACKUP_DWH.MSISDN_VISA)
    GROUP BY TRANSFER_DATETIME, SENDER_MSISDN
    UNION ALL
    SELECT
        TRANSFER_DATETIME JOUR,
       15.0 POSITION,
        'Micro Assurance' DESCRIPTION,
        SENDER_MSISDN MSISDN,
        COUNT(*) VOL,
        SUM(TRANSACTION_AMOUNT) VAL,
        SUM(TRANSACTION_AMOUNT)*0.07 REVENU,
        SUM(COMMISSIONS_PAID) COMM,
        SUM(COMMISSIONS_RECEIVED) FRAIS
    FROM CDR.SPARK_IT_OMNY_TRANSACTIONS2
    WHERE
    TRANSFER_DATETIME ='###SLICE_VALUE###'
    AND TRANSFER_STATUS = 'TS'
    AND RECEIVER_MSISDN  IN (SELECT MSISDN FROM BACKUP_DWH.MICROASSURANCE_MSISDNS)
    AND SENDER_MSISDN NOT IN (SELECT MSISDN FROM BACKUP_DWH.OM_TEST_MSISDNS)
    AND SUBSTR(TRANSFER_ID, 1, 2) IN ('CI', 'CO', 'PN', 'RC', 'MP', 'BP', 'ER' )
    GROUP BY TRANSFER_DATETIME, SENDER_MSISDN
    UNION ALL
    SELECT
        TRANSFER_DATETIME JOUR,
       14.0 POSITION,
        (CASE WHEN SERVICE_TYPE='CASHIN' THEN 'GIMAC In' ELSE 'GIMAC Out' END) DESCRIPTION,
        (CASE WHEN SENDER_CATEGORY_CODE='SUBS' THEN SENDER_MSISDN ELSE RECEIVER_MSISDN END) MSISDN,
        COUNT(*) VOL,
        SUM(TRANSACTION_AMOUNT) VAL,
        SUM(SERVICE_CHARGE_RECEIVED + COMMISSIONS_RECEIVED + COMMISSIONS_OTHERS) REVENU,
        SUM(COMMISSIONS_PAID) COMM,
        SUM(COMMISSIONS_RECEIVED) FRAIS
    FROM CDR.SPARK_IT_OMNY_TRANSACTIONS2
    WHERE TRANSFER_STATUS='TS' AND
    TRANSFER_DATETIME ='###SLICE_VALUE###'
    AND (SENDER_MSISDN IN (SELECT MSISDN FROM BACKUP_DWH.MSISDN_GIMAC) OR RECEIVER_MSISDN IN (SELECT MSISDN FROM BACKUP_DWH.MSISDN_GIMAC))
    GROUP BY TRANSFER_DATETIME, (CASE WHEN SERVICE_TYPE='CASHIN' THEN 'GIMAC In' ELSE 'GIMAC Out' END),
    (CASE WHEN SENDER_CATEGORY_CODE='SUBS' THEN SENDER_MSISDN ELSE RECEIVER_MSISDN END)

) X
left join (
    select
        a.msisdn,
        max(a.administrative_region) administrative_region_a,
        max(b.administrative_region) administrative_region_b
    from mon.spark_ft_client_last_site_day a
    left join (
        select * from mon.spark_ft_client_site_traffic_day where event_date='###SLICE_VALUE###'
    ) b on a.msisdn = b.msisdn
    where a.event_date='###SLICE_VALUE###'
    group by a.msisdn
) site on  site.msisdn =x.MSISDN
GROUP BY 
X.JOUR, 
X.POSITION, 
X.DESCRIPTION, 
TRIM(COALESCE(upper(REPLACE(site.administrative_region_b,'Ê','E')),upper(REPLACE(site.administrative_region_a,'Ê','E')), 'INCONNU'))

--SELECT
--    JOUR, POSITION, DESCRIPTION, COALESCE(REGION,'AUTRE') REGION, SUM(VOL) VOL, SUM(VAL) VAL, SUM(REVENU) REVENU, SUM(COMM) COMM, SUM(FRAIS) FRAIS
--FROM REGIONAL_DOM_DASHBOARD
--GROUP BY JOUR, POSITION, DESCRIPTION, COALESCE(REGION,'AUTRE')
--ORDER BY JOUR DESC, POSITION

--select
--JOUR,
--sum (if(round(position,0)=0, val,0)) cash_in,
--sum (if(round(position,0)=3, val,0)) cash_out,
--sum (if(round(position,0)=8, val,0)) bill_pay,
--sum (if(round(position,0)=9, val,0)) merch_pay,
--round(sum (revenu+FRAIS)/1.1925,0) revenu_total
--from AGG.SPARK_REGIONAL_DOM_DASHBOARD
--group by
--    JOUR
--Order by 1