INSERT INTO AGG.SPARK_FT_GLOBAL_ACTIVITY_DAILY_MKT_DG
---------- Revenue Orange Money

SELECT
     'REVENUE_OM' DESTINATION_CODE
     , PROFILE_CODE
     , 'UNKNOWN'  SERVICE_CODE
     , 'REVENUE_OM' KPI
     , 'UNKNOWN' SUB_ACCOUNT
     , 'HIT' MEASUREMENT_UNIT
     , 'DATAMART_OM_MARKETING' SOURCE_TABLE
     , OPERATOR_CODE
     , SUM(nvl(REVENU,0)) TOTAL_AMOUNT
     , SUM(nvl(REVENU,0)) RATED_AMOUNT
     , CURRENT_TIMESTAMP INSERT_DATE
     , REGION_ID
     , JOUR TRANSACTION_DATE
FROM AGG.SPARK_FT_A_DATAMART_OM_MARKETING B2
LEFT JOIN DIM.DT_REGIONS_MKT r ON UPPER(nvl(B2.administrative_region,'INCONNU')) = upper(r.ADMINISTRATIVE_REGION)
WHERE JOUR ='###SLICE_VALUE###' --and STYLE  IN ('RECHARGE','TOP_UP')
GROUP BY
    JOUR,
    PROFILE_CODE,
    OPERATOR_CODE,
    REGION_ID

UNION ALL

------ cash in OM


SELECT
     'CASH_IN_OM' DESTINATION_CODE
     , PROFILE_CODE
     , 'UNKNOWN'  SERVICE_CODE
     , 'CASH_IN_OM' KPI
     , 'UNKNOWN' SUB_ACCOUNT
     , 'HIT' MEASUREMENT_UNIT
     , 'DATAMART_OM_MARKETING' SOURCE_TABLE
     , OPERATOR_CODE
     , SUM(nvl(val,0)) TOTAL_AMOUNT
     , SUM(nvl(val,0)) RATED_AMOUNT
     , CURRENT_TIMESTAMP INSERT_DATE
     , REGION_ID
     , JOUR TRANSACTION_DATE
FROM AGG.SPARK_FT_A_DATAMART_OM_MARKETING B2
LEFT JOIN DIM.DT_REGIONS_MKT r ON UPPER(nvl(B2.administrative_region,'INCONNU')) = upper(r.ADMINISTRATIVE_REGION)
WHERE JOUR ='###SLICE_VALUE###' and service_type  IN ('CASHIN')
GROUP BY
    JOUR,
    PROFILE_CODE,
    OPERATOR_CODE,
    REGION_ID

UNION ALL

------ cash out OM


SELECT
     'CASH_OUT_OM' DESTINATION_CODE
     , PROFILE_CODE
     , 'UNKNOWN'  SERVICE_CODE
     , 'CASH_OUT_OM' KPI
     , 'UNKNOWN' SUB_ACCOUNT
     , 'HIT' MEASUREMENT_UNIT
     , 'DATAMART_OM_MARKETING' SOURCE_TABLE
     , OPERATOR_CODE
     , SUM(nvl(val,0)) TOTAL_AMOUNT
     , SUM(nvl(val,0)) RATED_AMOUNT
     , CURRENT_TIMESTAMP INSERT_DATE
     , REGION_ID
     , JOUR TRANSACTION_DATE
FROM AGG.SPARK_FT_A_DATAMART_OM_MARKETING B2
LEFT JOIN DIM.DT_REGIONS_MKT r ON UPPER(nvl(B2.administrative_region,'INCONNU')) = upper(r.ADMINISTRATIVE_REGION)
WHERE JOUR ='###SLICE_VALUE###' and service_type  IN ('CASHOUT')
GROUP BY
    JOUR,
    PROFILE_CODE,
    OPERATOR_CODE,
    REGION_ID


UNION ALL

------ cash MERCH


SELECT
     'MERCH_PAY_OM' DESTINATION_CODE
     , PROFILE_CODE
     , 'UNKNOWN'  SERVICE_CODE
     , 'MERCH_PAY_OM' KPI
     , 'UNKNOWN' SUB_ACCOUNT
     , 'HIT' MEASUREMENT_UNIT
     , 'DATAMART_OM_MARKETING' SOURCE_TABLE
     , OPERATOR_CODE
     , SUM(nvl(val,0)) TOTAL_AMOUNT
     , SUM(nvl(val,0)) RATED_AMOUNT
     , CURRENT_TIMESTAMP INSERT_DATE
     , REGION_ID
     , JOUR TRANSACTION_DATE
FROM AGG.SPARK_FT_A_DATAMART_OM_MARKETING B2
LEFT JOIN DIM.DT_REGIONS_MKT r ON UPPER(nvl(B2.administrative_region,'INCONNU')) = upper(r.ADMINISTRATIVE_REGION)
WHERE JOUR ='###SLICE_VALUE###' and service_type  IN ('MERCHPAY')
GROUP BY
    JOUR,
    PROFILE_CODE,
    OPERATOR_CODE,
    REGION_ID


UNION ALL

------ cash BILLPAY


SELECT
     'BILL_PAY_OM' DESTINATION_CODE
     , PROFILE_CODE
     , 'UNKNOWN'  SERVICE_CODE
     , 'BILL_PAY_OM' KPI
     , 'UNKNOWN' SUB_ACCOUNT
     , 'HIT' MEASUREMENT_UNIT
     , 'DATAMART_OM_MARKETING' SOURCE_TABLE
     , OPERATOR_CODE
     , SUM(nvl(val,0)) TOTAL_AMOUNT
     , SUM(nvl(val,0)) RATED_AMOUNT
     , CURRENT_TIMESTAMP INSERT_DATE
     , REGION_ID
     , JOUR TRANSACTION_DATE
FROM AGG.SPARK_FT_A_DATAMART_OM_MARKETING B2
LEFT JOIN DIM.DT_REGIONS_MKT r ON UPPER(nvl(B2.administrative_region,'INCONNU')) = upper(r.ADMINISTRATIVE_REGION)
WHERE JOUR ='###SLICE_VALUE###' and service_type  IN ('BILLPAY')
GROUP BY
    JOUR,
    PROFILE_CODE,
    OPERATOR_CODE,
    REGION_ID

UNION ALL

------------- -  Recharges (OM)

SELECT
     'REFILL_OM' DESTINATION_CODE
     , PROFILE_CODE
     , 'UNKNOWN'  SERVICE_CODE
     , 'REFILL_OM' KPI
     , 'UNKNOWN' SUB_ACCOUNT
     , 'HIT' MEASUREMENT_UNIT
     , 'DATAMART_OM_MARKETING' SOURCE_TABLE
     , OPERATOR_CODE
     , SUM(nvl(VAL,0)) TOTAL_AMOUNT
     , SUM(nvl(VAL,0)) RATED_AMOUNT
     , CURRENT_TIMESTAMP INSERT_DATE
     , REGION_ID
     , JOUR TRANSACTION_DATE
FROM AGG.SPARK_FT_A_DATAMART_OM_MARKETING B2
LEFT JOIN DIM.DT_REGIONS_MKT r ON UPPER(nvl(B2.administrative_region,'INCONNU')) = upper(r.ADMINISTRATIVE_REGION)
WHERE JOUR ='###SLICE_VALUE###' and STYLE  IN ('RECHARGE','TOP_UP')
GROUP BY
    JOUR,
    PROFILE_CODE,
    OPERATOR_CODE,
    REGION_ID


