
SELECT IF(T1.KPI_IS_LOAD=0 AND T2.FT_USERS_DAY>0 AND T3.FT_USERS_DATA_DAY>0 AND T2.nbs_ci>1000 AND T3.nbs_ci>1000 AND T2.INSERT_COUNT=0 AND T3.INSERT_COUNT=0,'OK','NOK')
 FROM
(SELECT COUNT(*) KPI_IS_LOAD FROM AGG.SPARK_FT_GLOBAL_ACTIVITY_DAILY_MKT_DG  WHERE TRANSACTION_DATE='###SLICE_VALUE###' AND JOB_NAME='COMPUTE_KPI_UNIQUE_USER')T1,
(SELECT COUNT(*) FT_USERS_DAY,count(distinct location_ci ) nbs_ci, COUNT(DISTINCT INSERT_DATE) INSERT_COUNT FROM MON.SPARK_FT_USERS_DAY WHERE EVENT_DATE='###SLICE_VALUE###')T2,
(SELECT COUNT(*) FT_USERS_DATA_DAY,count(distinct location_ci ) nbs_ci, COUNT(DISTINCT INSERT_DATE) INSERT_COUNT FROM MON.SPARK_FT_USERS_DATA_DAY WHERE EVENT_DATE='###SLICE_VALUE###')T3
