SELECT IF(T1.KPI_IS_LOAD=0 AND T2.FT_GROUP_USER_BASE>0 AND T3.FT_GROUP_SUBSCRIBER_SUMMARY >0 AND T4.FT_A_SUBSCRIBER_SUMMARY>0,'OK','NOK')
 FROM
(SELECT COUNT(*) KPI_IS_LOAD FROM AGG.SPARK_FT_GLOBAL_ACTIVITY_DAILY_MKT_DG WHERE TRANSACTION_DATE='###SLICE_VALUE###' AND SOURCE_TABLE IN('FT_A_SUBSCRIBER_SUMMARY','FT_GROUP_SUBSCRIBER_SUMMARY','FT_ACCOUNT_ACTIVITY'))T1,
(SELECT COUNT(*) FT_GROUP_USER_BASE FROM MON.SPARK_FT_GROUP_USER_BASE WHERE EVENT_DATE='###SLICE_VALUE###')T2,
(SELECT COUNT(*) FT_GROUP_SUBSCRIBER_SUMMARY FROM MON.SPARK_FT_GROUP_SUBSCRIBER_SUMMARY WHERE EVENT_DATE= DATE_ADD('###SLICE_VALUE###',1))T3,
(SELECT COUNT(*) FT_A_SUBSCRIBER_SUMMARY FROM AGG.SPARK_FT_A_SUBSCRIBER_SUMMARY WHERE DATECODE='###SLICE_VALUE###')T4