
SELECT IF(T1.KPI_IS_LOAD=0 AND T2.DM_EXISTS>0 AND T3.FT_EXISTS > 0 AND T4.FT_EXISTS > 0 ,'OK','NOK')
 FROM
(SELECT COUNT(*) KPI_IS_LOAD FROM AGG.SPARK_FT_A_PARC_OM  WHERE JOUR='###SLICE_VALUE###')T1,
(SELECT COUNT(*) DM_EXISTS FROM MON.SPARK_DATAMART_OM_MARKETING2 WHERE JOUR = '###SLICE_VALUE###' )T2,
(SELECT COUNT(*) FT_EXISTS FROM MON.SPARK_FT_CONTRACT_SNAPSHOT WHERE EVENT_DATE = '###SLICE_VALUE###' )T3,
(SELECT COUNT(*) FT_EXISTS FROM MON.SPARK_FT_CLIENT_LAST_SITE_DAY WHERE EVENT_DATE = '###SLICE_VALUE###' )T4


