
SELECT IF(T1.KPI_IS_LOAD=0 AND cdr_exists>0 AND loca1>0 and loca2>0,'OK','NOK')
 FROM
(SELECT COUNT(*) KPI_IS_LOAD FROM AGG.SPARK_REGIONAL_DOM_DASHBOARD  WHERE JOUR='###SLICE_VALUE###')T1,
(SELECT COUNT(*) cdr_exists FROM CDR.SPARK_IT_OMNY_TRANSACTIONS WHERE TRANSFER_DATETIME = '###SLICE_VALUE###' )T2,
(SELECT COUNT(*) loca1 FROM mon.spark_ft_client_site_traffic_day WHERE EVENT_DATE = '###SLICE_VALUE###' )T3,
(SELECT COUNT(*) loca2 FROM mon.spark_ft_client_last_site_day WHERE EVENT_DATE = '###SLICE_VALUE###' )T4