SELECT
        TRANSFER_DATETIME JOUR,
       9.0 POSITION,
        'Paiement Marchands' DESCRIPTION,
        SENDER_MSISDN MSISDN,
        COUNT(*) VOL,
        SUM(TRANSACTION_AMOUNT) VAL,
        SUM(SERVICE_CHARGE_RECEIVED + COMMISSIONS_RECEIVED) REVENU,
        SUM(COMMISSIONS_PAID) COMM,
        SUM(COMMISSIONS_RECEIVED) FRAIS
    FROM CDR.SPARK_IT_OMNY_TRANSACTIONS
    WHERE
        TRANSFER_STATUS='TS' AND
        TRANSFER_DATETIME ='2020-11-01' AND
        SUBSTR(TRANSFER_ID,1,2) = 'MP' AND
        RECEIVER_MSISDN NOT IN (SELECT MSISDN FROM BACKUP_DWH.NON_MERCHANT_MSISDNS UNION ALL SELECT MSISDN FROM BACKUP_DWH.OM_TEST_MSISDNS) AND
        SENDER_MSISDN NOT IN (SELECT MSISDN FROM BACKUP_DWH.OM_TEST_MSISDNS)
    GROUP BY TRANSFER_DATETIME, SENDER_MSISDN
    UNION ALL
    SELECT
        TRANSFER_DATETIME JOUR,
       9.0 POSITION,
        'Paiement Marchands' DESCRIPTION,
        SENDER_MSISDN MSISDN,
        COUNT(*) VOL,
        SUM(TRANSACTION_AMOUNT) VAL,
        SUM(COMMISSIONS_RECEIVED) REVENU,
        SUM(COMMISSIONS_PAID) COMM,
        NULL FRAIS
    FROM CDR.SPARK_IT_OMNY_TRANSACTIONS
    WHERE
        TRANSFER_STATUS='TS' AND
        UPPER(RECEIVER_GRADE_NAME) LIKE '%INFORMEL%' AND
        SUBSTR(TRANSFER_ID,1,2)='PP' AND
        TRANSFER_DATETIME ='2020-11-01' AND
        (RECEIVER_MSISDN NOT IN (SELECT MSISDN FROM BACKUP_DWH.OM_TEST_MSISDNS))
    GROUP BY TRANSFER_DATETIME, SENDER_MSISDN
    UNION ALL
    SELECT
        TRANSFER_DATETIME JOUR,
       9.0 POSITION,
        'Paiement Marchands' DESCRIPTION,
        SENDER_MSISDN MSISDN,
        NULL VOL,
        NULL VAL,
        SUM(SERVICE_CHARGE_RECEIVED + COMMISSIONS_RECEIVED) REVENU,
        NULL COMM,
        NULL FRAIS
    FROM CDR.SPARK_IT_OMNY_TRANSACTIONS
    WHERE
        TRANSFER_STATUS='TS' AND
        SENDER_CATEGORY_CODE<>'SUBS' AND
        RECEIVER_CATEGORY_CODE<>'SUBS' AND
        SUBSTR(TRANSFER_ID,1,2)='PP' AND
        TRANSFER_DATETIME ='2020-11-01'
    GROUP BY TRANSFER_DATETIME, SENDER_MSISDN
    UNION ALL
    SELECT
        TRANSFER_DATETIME JOUR,
       9.0 POSITION,
        'Paiement Marchands' DESCRIPTION,
        RECEIVER_MSISDN MSISDN,
        NULL VOL,
        NULL VAL,
        SUM(SERVICE_CHARGE_RECEIVED + COMMISSIONS_RECEIVED) REVENU,
        NULL COMM,
        NULL FRAIS
    FROM CDR.SPARK_IT_OMNY_TRANSACTIONS
    WHERE
        TRANSFER_STATUS='TS' AND
        UPPER(SENDER_DOMAIN_CODE) NOT LIKE 'B2W%' AND
        RECEIVER_CATEGORY_CODE='SUBS' AND
        SUBSTR(TRANSFER_ID,1,2)='CI' AND
        TRANSFER_DATETIME ='2020-11-01'
    GROUP BY TRANSFER_DATETIME, RECEIVER_MSISDN

   UNION ALL
     SELECT
         TRANSFER_DATETIME JOUR,
         9.1 POSITION,
         'Web Payment' DESCRIPTION,
         SENDER_MSISDN MSISDN,
         COUNT(*) VOL,
         SUM(TRANSACTION_AMOUNT) VAL,
         SUM(SERVICE_CHARGE_RECEIVED + COMMISSIONS_RECEIVED) REVENU,
         SUM(COMMISSIONS_PAID) COMM,
         NULL FRAIS
     FROM
         CDR.SPARK_IT_OMNY_TRANSACTIONS A
     WHERE
         TRANSFER_STATUS='TS' AND
         TRANSFER_DATETIME ='2020-11-01' AND
         SUBSTR(TRANSFER_ID,1,2)='MP' AND
         SENDER_CATEGORY_CODE='SUBS' AND
         RECEIVER_MSISDN IN (SELECT DISTINCT MSISDN FROM mon.REF_OM_PRODUCTS
             WHERE REF_DATE in (SELECT MAX(REF_DATE) FROM MON.REF_OM_PRODUCTS B WHERE REF_DATE<='2020-11-01') AND
         UPPER(TECHNOLOGY) LIKE '%WEB%') AND
         (RECEIVER_MSISDN NOT IN (SELECT MSISDN FROM BACKUP_DWH.OM_TEST_MSISDNS UNION ALL SELECT MSISDN FROM BACKUP_DWH.NON_MERCHANT_MSISDNS) AND
         SENDER_MSISDN NOT IN (SELECT MSISDN FROM BACKUP_DWH.OM_TEST_MSISDNS UNION ALL SELECT MSISDN FROM BACKUP_DWH.NON_MERCHANT_MSISDNS))
     GROUP BY TRANSFER_DATETIME, SENDER_MSISDN 
     
     
select event_date, count(distinct msisdn) pdvs from (
SELECT
DISTINCT '2020-07-01' EVENT_DATE, SENDER_MSISDN MSISDN
FROM CDR.SPARK_IT_OMNY_TRANSACTIONS
WHERE TRANSFER_DATETIME BETWEEN date_sub('2020-07-01' ,29) AND '2020-07-01'
AND TRANSFER_STATUS='TS' AND SERVICE_TYPE IN ('CASHIN','CASHOUT','INVC2C', 'P2P', 'COUTBYCODE','Cash Out offne' )  AND
SENDER_CATEGORY_CODE<>'SUBS' AND SENDER_MSISDN NOT IN (SELECT MSISDN FROM BACKUP_DWH.MSISDN_GIMAC UNION ALL SELECT MSISDN FROM BACKUP_DWH.MSISDN_VISA UNION ALL
SELECT MSISDN FROM BACKUP_DWH.MSISDN_B2W)
UNION
SELECT
DISTINCT '2020-07-01' EVENT_DATE, RECEIVER_MSISDN MSISDN
FROM CDR.SPARK_IT_OMNY_TRANSACTIONS
WHERE TRANSFER_DATETIME BETWEEN date_sub('2020-07-01' ,29) AND '2020-07-01'
AND TRANSFER_STATUS='TS' AND SERVICE_TYPE IN ('CASHIN','CASHOUT','INVC2C', 'P2P', 'COUTBYCODE','Cash Out offne' )  AND
RECEIVER_CATEGORY_CODE<>'SUBS' AND RECEIVER_MSISDN NOT IN (SELECT MSISDN FROM BACKUP_DWH.MSISDN_GIMAC UNION ALL SELECT MSISDN FROM BACKUP_DWH.MSISDN_VISA UNION ALL
SELECT MSISDN FROM BACKUP_DWH.MSISDN_B2W))d group by event_date order by 1,2;
