SELECT IF(T1.KPI_IS_LOAD=0 AND T2.FT_GROUP_USER_BASE>0 AND T3.FT_GROUP_SUBSCRIBER_SUMMARY >0 AND T4.FT_A_SUBSCRIBER_SUMMARY>0 AND T2.nbs_ci>1000 AND T3.nbs_ci>1000 AND T4.nbs_ci>1000 AND T2.INSERT_COUNT=1 AND T3.INSERT_COUNT=1 AND T4.INSERT_COUNT=1,'OK','NOK')
 FROM
(SELECT COUNT(*) KPI_IS_LOAD FROM AGG.SPARK_FT_GLOBAL_ACTIVITY_DAILY_MKT_DG WHERE TRANSACTION_DATE='2021-01-24' AND JOB_NAME ='COMPUTE_KPI_CUSTOMER_BASE')T1,
(SELECT COUNT(*) FT_GROUP_USER_BASE,count(distinct location_ci ) nbs_ci, COUNT(distinct INSERT_DATE) INSERT_COUNT FROM MON.SPARK_FT_GROUP_USER_BASE WHERE EVENT_DATE='2021-01-24')T2,
(SELECT COUNT(*) FT_GROUP_SUBSCRIBER_SUMMARY,count(distinct location_ci ) nbs_ci, COUNT(distinct INSERT_DATE) INSERT_COUNT FROM MON.SPARK_FT_GROUP_SUBSCRIBER_SUMMARY WHERE EVENT_DATE= DATE_ADD('2021-01-24',1))T3,
(SELECT COUNT(*) FT_A_SUBSCRIBER_SUMMARY,count(distinct location_ci ) nbs_ci, COUNT(distinct REFRESH_DATE) INSERT_COUNT FROM AGG.SPARK_FT_A_SUBSCRIBER_SUMMARY WHERE DATECODE='2021-01-24')T4
