 -- ajouter les données ICC =>  prepaid et hybride :
INSERT INTO TMP.TT_PARCS_SITE_DAY
    (PARC_TYPE, PROFILE, STATUT, EFFECTIF, 
     SITE_NAME, TOWNNAME, ADMINISTRATIVE_REGION, 
     COMMERCIAL_REGION, SRC_TABLE, INSERT_DATE, 
     CONTRACT_TYPE, OPERATOR_CODE, EVENT_DATE)
    SELECT
        'PARC_GROUPE' AS PARC_TYPE
        , UPPER(a.PROFILE) PROFILE
        , NVL(b.GP_STATUS, 'INACT') STATUT
        , COUNT(*) as EFFECTIF
        , SITE_NAME, TOWNNAME
        , ADMINISTRATIVE_REGION
        , COMMERCIAL_REGION
        , a.SRC_TABLE, CURRENT_TIMESTAMP INSERT_DATE
        , NVL(a.OSP_CONTRACT_TYPE, 'PURE PREPAID') CONTRACT_TYPE
        , 'OCM' AS OPERATOR_CODE, DATE_ADD('###SLICE_VALUE###',-1) EVENT_DATE
    FROM
        (SELECT * FROM MON.SPARK_FT_CONTRACT_SNAPSHOT 
          WHERE TO_DATE(EVENT_DATE) = '2020-01-03'
          AND NVL(OSP_CONTRACT_TYPE, 'PURE PREPAID') IN ('PURE PREPAID', 'HYBRID')) a
      LEFT JOIN
        (SELECT * FROM MON.SPARK_FT_ACCOUNT_ACTIVITY  WHERE
         TO_DATE(EVENT_DATE) = '###SLICE_VALUE###') b
      ON a.ACCESS_KEY = b.MSISDN
      LEFT JOIN
        (SELECT MSISDN, SITE_NAME, TOWNNAME, ADMINISTRATIVE_REGION, COMMERCIAL_REGION
         FROM MON.SPARK_FT_CLIENT_LAST_SITE_DAY
         WHERE TO_DATE(EVENT_DATE) = DATE_ADD('###SLICE_VALUE###',-1)) c
      ON a.ACCESS_KEY = c.MSISDN
    GROUP BY
         UPPER(a.PROFILE)
        , NVL(b.GP_STATUS, 'INACT')
        , SITE_NAME, TOWNNAME
        , ADMINISTRATIVE_REGION
        , COMMERCIAL_REGION
        , a.SRC_TABLE, NVL (a.OSP_CONTRACT_TYPE, 'PURE PREPAID');


