-- AJOUT DES MSISDN QUI DISPARAISSENT DE LA PHOTO
INSERT INTO TMP.TT_TMP_MISS_MSISDN_SITE 
SELECT a.MSISDN
FROM
(SELECT MSISDN  FROM MON.SPARK_FT_ACCOUNT_ACTIVITY 
 WHERE TO_DATE(EVENT_DATE) = '###SLICE_VALUE###' AND NVL(COMGP_STATUS, 'INACT') = 'ACTIF') a
LEFT JOIN
(SELECT access_key MSISDN FROM MON.SPARK_FT_CONTRACT_SNAPSHOT a WHERE TO_DATE(a.EVENT_DATE) = '###SLICE_VALUE###') b
ON a.MSISDN = b.MSISDN WHERE b.MSISDN IS NULL