SELECT 
TRANSACTION_DATE, 
OTHER_PARTY AS SHORT_NUMBER, 
COUNT(*) NBR_TRANSACTIONS 
FROM MON.SPARK_FT_MSC_TRANSACTION 
WHERE TRANSACTION_DATE ='###SLICE_VALUE###' AND OTHER_PARTY IN ('950', '951', '9111', '955', '8950', '8951', '89111', '8955')
GROUP BY TRANSACTION_DATE,OTHER_PARTY 
ORDER BY TRANSACTION_DATE