CREATE TABLE SPOOL.SPOOL_SOLDE_DATA_SUP_100GO (
    MSISDN VARCHAR(200),
    ACCT_RES_NAME VARCHAR(200),
    DATA_BYTES VARCHAR(200),
    EFFECTIVE_DATE TIMESTAMP,
    EXPIRATION_DATE TIMESTAMP,
    UPDATE_DATE TIMESTAMP,
    SERVICE_CODE VARCHAR(200)
)
PARTITIONED BY (ORIGINAL_FILE_DATE DATE)
STORED AS PARQUET TBLPROPERTIES ('PARQUET.COMPRESS'='SNAPPY')