
INSERT INTO MON.SPARK_FT_USERS_REGION_LOCATION
SELECT
    A.FORMULE,
    B.ADMINISTRATIVE_REGION,
    COUNT(DISTINCT CASE WHEN A.EVENT_DATE = '###SLICE_VALUE###' THEN FN_FORMAT_MSISDN_TO_9DIGITS(A.MSISDN) END) AS USERS_COUNT,
    A.OPERATOR_CODE,
    CURRENT_TIMESTAMP AS INSERT_DATE,
    COUNT(DISTINCT CASE WHEN A.EVENT_DATE BETWEEN DATE_SUB('###SLICE_VALUE###', 6) AND '###SLICE_VALUE###' THEN FN_FORMAT_MSISDN_TO_9DIGITS(A.MSISDN) END) AS USERS_COUNT_7_DAYS,
    COUNT(DISTINCT FN_FORMAT_MSISDN_TO_9DIGITS(A.MSISDN)) AS USERS_COUNT_30_DAYS,
    '###SLICE_VALUE###' EVENT_DATE
FROM
(
    SELECT *
    FROM MON.SPARK_FT_CONSO_MSISDN_DAY
    WHERE EVENT_DATE BETWEEN DATE_SUB('###SLICE_VALUE###', 29) AND '###SLICE_VALUE###'
) A
LEFT JOIN
(
    SELECT
        ADMINISTRATIVE_REGION,
        FN_FORMAT_MSISDN_TO_9DIGITS(MSISDN) MSISDN
    FROM MON.SPARK_FT_CLIENT_LAST_SITE_LOCATION
    WHERE EVENT_MONTH = SUBSTRING(ADD_MONTHS('###SLICE_VALUE###',-1),1,7)
) B ON FN_FORMAT_MSISDN_TO_9DIGITS(A.MSISDN) = B.MSISDN
GROUP BY FORMULE,
    B.ADMINISTRATIVE_REGION,
    A.OPERATOR_CODE
