CREATE TABLE MON.SPARK_FT_USERS_REGION_LOCATION
(
    FORMULE                      VARCHAR(70),
    ADMINISTRATIVE_REGION        VARCHAR(50),
    USERS_COUNT                  BIGINT,
    OPERATOR_CODE                VARCHAR(50),
    INSERT_DATE                 TIMESTAMP
)
PARTITIONED BY (EVENT_DATE DATE)
STORED AS PARQUET
TBLPROPERTIES ('PARQUET.COMPRESS'='SNAPPY')