SELECT IF(A.COUNT_FT = 0 and B.COUNT_SNAPSHOT>0,"OK","NOK") FROM
(SELECT count(*) COUNT_FT FROM MON.FT_DATA_TRANSFER WHERE TRANSACTION_DATE='###SLICE_VALUE###') A,
(SELECT COUNT(*) COUNT_SNAPSHOT FROM MON.FT_CONTRACT_SNAPSHOT WHERE EVENT_DATE='###SLICE_VALUE###')B;

