CREATE EXTERNAL TABLE CDR.TT_GOOGLE_RCS_CLIENT (
    ORIGINAL_FILE_NAME VARCHAR(200),
    ORIGINAL_FILE_SIZE INT,
    ORIGINAL_FILE_LINE_COUNT INT,
    USERS VARCHAR(200),
    AGENT VARCHAR(200),
    200_TODAY VARCHAR(200),
    200_THIS_MONTH VARCHAR(200),
    503_TODAY VARCHAR(200),
    503_THIS_MONTH VARCHAR(200)
)
COMMENT 'external tables-TT'
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t'
LOCATION '/PROD/TT/GOOGLE_RCS/CLIENT'
TBLPROPERTIES ('serialization.null.format'='')
;