CREATE EXTERNAL TABLE CDR.TT_GOOGLE_RCS_PROVISION (
    ORIGINAL_FILE_NAME VARCHAR(200),
    ORIGINAL_FILE_SIZE INT,
    ORIGINAL_FILE_LINE_COUNT INT,
    MSISDN VARCHAR(200),
    TENANT VARCHAR(200)
)
COMMENT 'external tables-TT'
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t'
LOCATION '/PROD/TT/GOOGLE_RCS/PROVISION'
TBLPROPERTIES ('serialization.null.format'='')
;