INSERT INTO MON.SPARK_FT_INTERCO_SORTANT_INTERNATIONAL
SELECT
  A.MSISDN,
  B.COUNTRY DESTINATION,
  SUM(A.MOU_INTER),
  CURRENT_TIMESTAMP() INSERT_DATE,
  A.TRANSACTION_DATE TRANSACTION_DATE
FROM
(
    SELECT
        SERVED_PARTY MSISDN,
        OTHER_PARTY,
        SUM
        (
            CASE
                WHEN UPPER(SERVICE_CODE) IN ('TEL', 'OC','OCFWD','OCRMG','TCRMG') THEN CALL_PROCESS_TOTAL_DURATION
                WHEN UPPER(SERVICE_CODE) LIKE '%FNF%MODIFICATION%'  THEN CALL_PROCESS_TOTAL_DURATION
                WHEN UPPER(SERVICE_CODE) LIKE '%ACCOUNT%INTERRO%' THEN CALL_PROCESS_TOTAL_DURATION
                ELSE 0
            END
        ) / 60 AS MOU_INTER,
        TRANSACTION_DATE
    FROM MON.SPARK_FT_BILLED_TRANSACTION_PREPAID
    WHERE TRANSACTION_DATE = '###SLICE_VALUE###'
        AND UPPER(TRIM(CALL_DESTINATION_CODE)) = 'INT'
    GROUP BY SERVED_PARTY,
        OTHER_PARTY,
        TRANSACTION_DATE
) A
LEFT JOIN
(
    SELECT
        CODE,
        COUNTRY
    FROM
    (
         SELECT
              UPPER(TRIM (NAME)) COUNTRY,
              UPPER(TRIM(CODE)) CODE,
              ROW_NUMBER() OVER(PARTITION BY UPPER(TRIM(CODE)) ORDER BY LENGTH(UPPER(TRIM(NAME))) DESC NULLS LAST) AS RANG
         FROM DIM.SPARK_DT_COUNTRIES
    ) C
    WHERE RANG = 1
) B
ON SUBSTR(TRIM(A.OTHER_PARTY), 1,  LENGTH(TRIM(B.CODE))) = TRIM(B.CODE)
GROUP BY A.MSISDN,
B.COUNTRY,
A.TRANSACTION_DATE