SELECT IF(A.FT_EXISTS = 0 AND B.NB_BILL > 0 , "OK", "NOK")
FROM
(SELECT COUNT(*) FT_EXISTS FROM MON.SPARK_FT_INTERCO_SORTANT_INTERNATIONAL WHERE TRANSACTION_DATE = '###SLICE_VALUE###') A,
(SELECT COUNT(*) NB_BILL FROM MON.SPARK_FT_BILLED_TRANSACTION_PREPAID WHERE TRANSACTION_DATE = '###SLICE_VALUE###',1) B