CREATE TABLE MON.SPARK_FT_GROSS_ADD_COMPETITIORS
   (
	 OPERATOR_CODE    VARCHAR(100),
	 SUBSCRIBER_COUNT INT,
	 INSERT_DATE TIMESTAMP
	)
	PARTITIONED BY(EVENT_DATE DATE)
    STORED AS PARQUET
    TBLPROPERTIES ("parquet.compress"="SNAPPY")