INSERT INTO MON.SPARK_FT_GROSS_ADD_COMPETITIORS
SELECT
OPERATOR_CODE,
COUNT(DISTINCT MSISDN) AS SUBSCRIBER_COUNT,
CURRENT_TIMESTAMP INSERT_DATE,
'###SLICE_VALUE###' EVENT_DATE
FROM
(
-- clients concourrence "existants" en interco le jour J et n'ayant pas ete en interco les 90 jours precedents
SELECT
a.MSISDN,
a.OPERATOR_CODE,
'###SLICE_VALUE###' AS EVENT_DATE
FROM
(
-- clients concurrence en interco le jour J
SELECT MSISDN, OPERATOR_CODE
FROM MON.SPARK_FT_OPERATOR_ACCT_ACTIVITY
WHERE EVENT_DATE ='###SLICE_VALUE###'
AND GREATEST(COALESCE(OG_CALL_4,TO_DATE('19700101')), COALESCE(IC_CALL_4,TO_DATE('19700101'))) = EVENT_DATE
AND OPERATOR_CODE IN ('CAMTEL', 'VIETTEL', 'MTN')
) a
INNER JOIN
(
-- clients concurrence de la veille n'ayant pas ete en interco depuis plus de 90 jours
SELECT MSISDN, OPERATOR_CODE
FROM MON.SPARK_FT_OPERATOR_ACCT_ACTIVITY
WHERE EVENT_DATE =  DATE_SUB('2020-02-21',1)
AND DATE_SUB('###SLICE_VALUE###',89) > GREATEST(COALESCE(OG_CALL_4,TO_DATE('19700101')), COALESCE(IC_CALL_4,TO_DATE('19700101')))
AND OPERATOR_CODE IN ('CAMTEL', 'VIETTEL', 'MTN')
) b
ON a.MSISDN = b.MSISDN
UNION ALL
-- clients concurrence "nouveaux" en interco pour la premiere fois le jour J
SELECT
MSISDN,
OPERATOR_CODE,
'###SLICE_VALUE###' AS EVENT_DATE
FROM MON.SPARK_FT_OPERATOR_ACCT_ACTIVITY
WHERE EVENT_DATE = '###SLICE_VALUE###'
AND FIRST_ENTRY_DATE = '###SLICE_VALUE###'
AND OPERATOR_CODE IN ('CAMTEL', 'VIETTEL', 'MTN')
)v
GROUP BY OPERATOR_CODE,EVENT_DATE