CREATE EXTERNAL TABLE CDR.TT_PULSE_SPIDER_FORFAIT (
ORIGINAL_FILE_NAME VARCHAR(50),
ORIGINAL_FILE_SIZE INT,
ORIGINAL_FILE_LINE_COUNT INT,
IPP_NAME VARCHAR(60),
IPP_CODE VARCHAR(15),
BEGIN_DATE VARCHAR(15),
END_DATE VARCHAR(15)
)
COMMENT 'Pulse Spider forfait external table'
ROW FORMAT DELIMITED FIELDS TERMINATED BY ';'
LOCATION '/PROD/TT/PULSE_SPIDER/FORFAIT'
TBLPROPERTIES ('serialization.null.format'='')
;