CREATE EXTERNAL TABLE CDR.TT_PULSE_SPIDER_PARRAIN (
ORIGINAL_FILE_NAME VARCHAR(50),
ORIGINAL_FILE_SIZE INT,
ORIGINAL_FILE_LINE_COUNT INT,
MSISDN_PARRAIN VARCHAR(15),
MSISDN_PARRAINE VARCHAR(15),
REGISTER_TIME VARCHAR(20)
)
COMMENT 'Pulse Spider Parrain external table'
ROW FORMAT DELIMITED FIELDS TERMINATED BY ';'
LOCATION '/PROD/TT/PULSE_SPIDER/PARRAIN'
TBLPROPERTIES ('serialization.null.format'='')
;