CREATE TABLE CDR.SPARK_IT_ZTE_BALANCE_TYPE (
    ORIGINAL_FILE_NAME VARCHAR(200),
    ORIGINAL_FILE_SIZE INT,
    ORIGINAL_FILE_LINE_COUNT INT,
    BALANCE_TYPE_ID DECIMAL(17,2),
    ACCT_ITEM_TYPE_ID DECIMAL(17,2),
    BALANCE_TYPE_NAME VARCHAR(80),
    BALANCE_TYPE_STD_CODE DECIMAL(17,2),
    INSERT_DATE TIMESTAMP
)
PARTITIONED BY (ORIGINAL_FILE_DATE DATE)
CLUSTERED BY(BALANCE_TYPE_ID) INTO 8 BUCKETS
STORED AS PARQUET TBLPROPERTIES ('PARQUET.COMPRESS'='SNAPPY');


