SELECT IF(A.COUNT_FT_A_VAS_REVENUE_DAILY = 0 and B.COUNT_FT_VAS_REVENUE_DETAIL>0,"OK","NOK") FROM
(SELECT count(*) COUNT_FT_A_VAS_REVENUE_DAILY FROM AGG.SPARK_FT_A_VAS_REVENUE_DAILY WHERE TRANSACTION_DATE='###SLICE_VALUE###' LIMIT 10) A,
(SELECT COUNT(*) COUNT_FT_VAS_REVENUE_DETAIL FROM MON.FT_VAS_REVENUE_DETAIL WHERE TRANSACTION_DATE='###SLICE_VALUE###' LIMIT 10) B
;
