SELECT 
  MSISDN_IDWIMAX,
  VALEUR_LIGNE_VOIX,
  VALEUR_LIGNE_SMS,
  VALEUR_LIGNE_DATA,
  VALEUR_LIGNE_OM,
  VALEUR_LIGNE_GLOBALE,
  SEGMENT_LIGNE_VOIX,
  SEGMENT_LIGNE_DATA,
  SEGMENT_LIGNE_SMS,
  SEGMENT_LIGNE_OM,
  SEGMENT_LIGNE_GLOBALE
FROM MON.SPARK_FT_CRM_OUTPUT_ABONNEMENT
WHERE EVENT_MONTH='###SLICE_VALUE###'