CREATE TABLE SPOOL.SPOOL_BICEC_TRANS_RECONCILIATION
(
    PERIODE_REFERENCE DATE,
    PARTNER_FIRST_NAME VARCHAR(90),
    PARTNER_LAST_NAME VARCHAR(90),
    ACCOUNT_AGENCY VARCHAR(8),
    ACCOUNT_NUMBER VARCHAR(90),
    ACCOUNT_KEY VARCHAR(4),
    BALANCE_DEBUT DECIMAL(17,2),
    CREDIT DECIMAL(17,2),
    DEBIT DECIMAL(17,2),
    BALANCE_ESTIME_FIN DECIMAL(17,2),
    INSERT_DATE TIMESTAMP
)
PARTITIONED BY (EVENT_DATE DATE)
STORED AS PARQUET
TBLPROPERTIES ('PARQUET.COMPRESS'='SNAPPY')