SELECT IF(T_1.SPOOL_COUNT = 0 AND T_2.FT_COUNT > 0 AND T_3.FT_COUNT > 0  AND T_4.FT_COUNT > 0, "OK", "NOK") FT_EXIST
FROM
(SELECT COUNT(*) SPOOL_COUNT FROM SPOOL.SPOOL_BICEC_TRANS_RECONCILIATION WHERE EVENT_DATE = '###SLICE_VALUE###') T_1,
(SELECT COUNT(*) FT_COUNT FROM MON.SPARK_FT_OM_BICEC_TRANSACTION WHERE EVENT_DATE = '###SLICE_VALUE###') T_2,
(SELECT COUNT(*) FT_COUNT FROM MON.SPARK_FT_OMNY_BALANCE_SNAPSHOT WHERE EVENT_DATE = DATE_SUB('###SLICE_VALUE###', 1)) T_3,
(SELECT COUNT(*) FT_COUNT FROM MON.SPARK_FT_OMNY_BALANCE_SNAPSHOT WHERE EVENT_DATE = '###SLICE_VALUE###') T_4
