CREATE TABLE TMP.TT_MSISDN_DATA_SITE
(
    SESSION_DATE DATE,
    MSISDN VARCHAR(100),
    IMEI VARCHAR(100),
    SITE_NAME VARCHAR(50),
    BYTES_USED DECIMAL(20,2),
    TOTAL_COST DECIMAL(20,2),
    BUNDLE_VOLUME_USED DECIMAL(20,2),
    INSERT_DATE DATE
--     OTARIE_BYTES_2G DECIMAL(20,2),
--     OTARIE_BYTES_3G DECIMAL(20,2),
--     OTARIE_BYTES_4G DECIMAL(20,2),
--     OTARIE_BYTES_UKN DECIMAL(20,2)
)
STORED AS PARQUET TBLPROPERTIES ('PARQUET.COMPRESS'='SNAPPY')