SELECT IF(TT_NOT_EXISTS = 0 and TRANS_EXISTS>0 ,"OK","NOK") TABLES_EXIST
FROM
(SELECT COUNT(*) TT_NOT_EXISTS FROM MON.SPARK_TT_PICO_KPIS WHERE event_month='###SLICE_VALUE###' and KPI='OM_DEPOSIT_AMT') A,
(SELECT COUNT(*) TRANS_EXISTS FROM cdr.spark_it_omny_transactions WHERE transfer_datetime='###SLICE_VALUE###-01') B