SELECT IF(
    A.FT_EXIST = 0
    AND B.FT_EXIST > 0
    , "OK"
    , "NOK"
) FROM
(SELECT COUNT(*) FT_EXIST FROM MON.SPARK_FT_CLIENT_LOCATION_30_DAYS WHERE EVENT_DATE = '###SLICE_VALUE###') A,
(SELECT COUNT(*) FT_EXIST FROM MON.SPARK_FT_CLIENT_SITE_TRAFFIC_DAY WHERE EVENT_DATE BETWEEN DATE_SUB('###SLICE_VALUE###', 29) AND '###SLICE_VALUE###') B