SELECT IF(A.KPI_MULTISIM = 0 AND B.BDI >0 ,"OK","NOK") FROM
(SELECT COUNT(*) KPI_MULTISIM FROM AGG.SPARK_FT_A_MULTISIM WHERE EVENT_DATE= '###SLICE_VALUE###') A,
(SELECT COUNT(*) BDI FROM MON.SPARK_FT_KYC_BDI_PP WHERE EVENT_DATE= '###SLICE_VALUE###') B

