
CREATE EXTERNAL TABLE CDR.tt_zte_subscription (
  ORIGINAL_FILE_NAME VARCHAR(200),
  ORIGINAL_FILE_SIZE INT,
  ORIGINAL_FILE_LINE_COUNT INT,
  ACC_NBR  VARCHAR(16),
  CHANNEL_ID  INT,
  SUBS_EVENT_ID  INT,
  CREATEDDATE  TIMESTAMP,
  OLD_SUBS_STATE  VARCHAR(3),
  NEW_SUBS_STATE  VARCHAR(3),
  EVENT_COST  INT,
  BENEFIT_NAME  VARCHAR(50),
  BENEFIT_BAL_LIST  VARCHAR(2000),
  OLD_PROD_SPEC_CODE  VARCHAR(10),
  PROD_SPEC_CODE  VARCHAR(10),
  OLD_PRICE_PLAN_CODE  VARCHAR(10),
  PRICE_PLAN_CODE  VARCHAR(50),
  OLD_RELATED_PROD_CODE  VARCHAR(10),
  RELATED_PROD_CODE  VARCHAR(10),
  ACTIVE_DATE  TIMESTAMP,
  EXPIRED_DATE  TIMESTAMP,
  PROVIDER_ID  INT,
  PREPAY_FLAG  INT,
  PAYMENT_NUMBER  VARCHAR(20),
  SUBSCRIPTION_COST  BIGINT,
  TRANSACTIONSN  BIGINT
)
COMMENT 'external tables-TT'
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|'
LOCATION '/PROD/TT/IN_ZTE/SUBSCRIPTION'
TBLPROPERTIES ('serialization.null.format'='')
;

-- COLONNES DEJA PRESENTES DANS LA TT. MAIS LES ALTER TABLE SONT ABSENTES
-- EXP_LAC,
-- EXP_CELL_ID,
-- BAL_ID,

-- NOUVELLES COLONNES PRESENTES DANS LE FICHIER CDR. 
-- ALTER TABLE POUR LES RAJOUTER A LA TT DANS CET ORDRE
-- UNKNOWN_COL,
ALTER TABLE CDR.tt_zte_subscription ADD COLUMNS (UNKNOWN_COL VARCHAR(200));

-- ACCOUNT_RES_ID,
ALTER TABLE CDR.tt_zte_subscription ADD COLUMNS (ACCOUNT_RES_ID VARCHAR(200));

-- REQUEST_ID
ALTER TABLE CDR.tt_zte_subscription ADD COLUMNS (REQUEST_ID VARCHAR(200));


-- LES MODIFICATIONS A FAIRE SUR LA COLONNE EVENT_COST
--  EVENT_COST  INT,
-- IL FAUT LA FAIRE PASSER DE INT POUR VARCHAR DANS LA TT
ALTER TABLE CDR.tt_zte_subscription CHANGE EVENT_COST EVENT_COST VARCHAR(200);

-- DANS L'IT IL FAUT FAIRE UN SPLIT PAR LA VIRGULE
-- ET SOMMER LES VALEURS DES POSITIONS 0 1 2 3 
-- SACHANT QUE NOUS AVONS JUSTE 2 VALEURS A CE JOUR.
