

CREATE EXTERNAL TABLE CDR.tt_zte_subscription (
  ORIGINAL_FILE_NAME VARCHAR(200),
  ORIGINAL_FILE_SIZE INT,
  ORIGINAL_FILE_LINE_COUNT INT,
  ACC_NBR  VARCHAR(16),
  CHANNEL_ID  INT,
  SUBS_EVENT_ID  INT,
  CREATEDDATE  TIMESTAMP,
  OLD_SUBS_STATE  VARCHAR(3),
  NEW_SUBS_STATE  VARCHAR(3),
  EVENT_COST  INT,
  BENEFIT_NAME  VARCHAR(50),
  BENEFIT_BAL_LIST  VARCHAR(2000),
  OLD_PROD_SPEC_CODE  VARCHAR(10),
  PROD_SPEC_CODE  VARCHAR(10),
  OLD_PRICE_PLAN_CODE  VARCHAR(10),
  PRICE_PLAN_CODE  VARCHAR(50),
  OLD_RELATED_PROD_CODE  VARCHAR(10),
  RELATED_PROD_CODE  VARCHAR(10),
  ACTIVE_DATE  TIMESTAMP,
  EXPIRED_DATE  TIMESTAMP,
  PROVIDER_ID  INT,
  PREPAY_FLAG  INT,
  PAYMENT_NUMBER  VARCHAR(20),
  SUBSCRIPTION_COST  BIGINT,
  TRANSACTIONSN  BIGINT,
  EXP_LAC VARCHAR(100),
  EXP_CELL_ID  VARCHAR(100),
  BAL_ID VARCHAR(100)
)
COMMENT 'external tables-TT'
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|'
LOCATION '/PROD/TT/IN_ZTE/SUBSCRIPTION'
TBLPROPERTIES ('serialization.null.format'='')
;