CREATE TABLE MON.SPARK_FT_MARKETING_DATAMART

(
msisdn                          varchar(50),
loc_site_name                   varchar(50),
loc_town_name                   varchar(50),
loc_admintrative_region         varchar(50),
loc_commercial_region           varchar(50),
ter_tac_code                    varchar(8) ,
ter_constructor                 varchar(255) ,
ter_model                       varchar(255) ,
ter_2g_3g_4g_compatibility      varchar(50),
ter_2g_compatibility            char(1)    ,
ter_3g_compatibility            char(1)    ,
ter_4g_compatibility            char(1)    ,
contract_type                   varchar(50),
commercial_offer                varchar(50),
activation_date                 DATE  ,
deactivation_date               DATE  ,
lang                            varchar(5) ,
osp_status                      varchar(30),
imsi                            varchar(25),
grp_last_og_call                DATE  ,
grp_last_ic_call                DATE  ,
grp_remain_credit_main          decimal(20,2),
grp_remain_credit_promo         decimal(20,2),
grp_gp_status                   varchar(5) ,
dir_first_name                  varchar(250) ,
dir_last_name                   varchar(250) ,
dir_birth_date                  DATE  ,
dir_identification_town         varchar(250) ,
dir_identification_date         DATE  ,
data_main_rated_amount          decimal(20,2),
data_gos_main_rated_amount      decimal(20,2),
data_promo_rated_amount         decimal(20,2),
data_roam_main_rated_amount     decimal(20,2),
data_roam_promo_rated_amount    decimal(20,2),
data_bytes_received             decimal(20,2),
data_bytes_sent                 decimal(20,2),
data_bytes_used_in_bundle       decimal(20,2),
data_bytes_used_paygo           decimal(20,2),
data_bytes_used_in_bundle_roam  decimal(20,2),
data_byte_used_out_bundle_roam  decimal(20,2),
data_mms_used                   decimal(20,2),
data_mms_used_in_bundle         decimal(20,2),
sos_loan_count                  decimal(20,2),
sos_loan_amount                 decimal(20,2),
sos_reimbursement_count         decimal(20,2),
sos_reimbursement_amount        decimal(20,2),
sos_fees                        decimal(20,2),
total_revenue                   decimal(20,2),
total_voice_revenue             decimal(20,2),
total_sms_revenue               decimal(20,2),
total_subs_revenue              decimal(20,2),
c2s_refill_count                decimal(20,2),
c2s_main_refill_amount          decimal(20,2),
c2s_promo_refill_amount         decimal(20,2),
p2p_refill_count                decimal(20,2),
p2p_refill_amount               decimal(20,2),
scratch_refill_count            decimal(20,2),
scratch_main_refill_amount      decimal(20,2),
scratch_promo_refill_amount     decimal(20,2),
p2p_refill_fees                 decimal(20,2),
total_data_revenue              decimal(20,2),
roam_data_revenue               decimal(20,2),
roam_in_voice_revenue           decimal(20,2),
roam_out_voice_revenue          decimal(20,2),
roam_in_sms_revenue             decimal(20,2),
roam_out_sms_revenue            decimal(20,2),
og_call_total_count             decimal(20,2),
og_call_ocm_count               decimal(20,2),
og_call_mtn_count               decimal(20,2),
og_call_nexttel_count           decimal(20,2),
og_call_camtel_count            decimal(20,2),
og_call_set_count               decimal(20,2),
og_call_roam_in_count           decimal(20,2),
og_call_roam_out_count          decimal(20,2),
og_call_sva_count               decimal(20,2),
og_call_international_count     decimal(20,2),
og_rated_call_duration          decimal(20,2),
og_total_call_duration          decimal(20,2),
rated_tel_ocm_duration          decimal(20,2),
rated_tel_mtn_duration          decimal(20,2),
rated_tel_nexttel_duration      decimal(20,2),
rated_tel_camtel_duration       decimal(20,2),
rated_tel_set_duration          decimal(20,2),
rated_tel_roam_in_duration      decimal(20,2),
rated_tel_roam_out_duration     decimal(20,2),
rated_tel_sva_duration          decimal(20,2),
rated_tel_int_duration          decimal(20,2),
main_rated_tel_amount           decimal(20,2),
promo_rated_tel_amount          decimal(20,2),
og_total_rated_call_amount      decimal(20,2),
main_rated_tel_ocm_amount       decimal(20,2),
main_rated_tel_mtn_amount       decimal(20,2),
main_rated_tel_nexttel_amount   decimal(20,2),
main_rated_tel_camtel_amount    decimal(20,2),
main_rated_tel_set_amount       decimal(20,2),
main_rated_tel_roam_in_amount   decimal(20,2),
main_rated_tel_roam_out_amount  decimal(20,2),
main_rated_tel_sva_amount       decimal(20,2),
main_rated_tel_int_amount       decimal(20,2),
promo_rated_tel_ocm_amount      decimal(20,2),
promo_rated_tel_mtn_amount      decimal(20,2),
promo_rated_tel_nexttel_amount  decimal(20,2),
promo_rated_tel_camtel_amount   decimal(20,2),
promo_rated_tel_set_amount      decimal(20,2),
promo_rated_tel_roamin_amount   decimal(20,2),
promo_rated_tel_roamout_amount  decimal(20,2),
promo_rated_tel_int_amount      decimal(20,2),
og_sms_total_count              decimal(20,2),
og_sms_ocm_count                decimal(20,2),
og_sms_mtn_count                decimal(20,2),
og_sms_nexttel_count            decimal(20,2),
og_sms_camtel_count             decimal(20,2),
og_sms_set_count                decimal(20,2),
og_sms_roam_in_count            decimal(20,2),
og_sms_roam_out_count           decimal(20,2),
og_sms_sva_count                decimal(20,2),
og_sms_international_count      decimal(20,2),
main_rated_sms_amount           decimal(20,2),
main_rated_sms_ocm_amount       decimal(20,2),
main_rated_sms_mtn_amount       decimal(20,2),
main_rated_sms_nexttel_amount   decimal(20,2),
main_rated_sms_camtel_amount    decimal(20,2),
main_rated_sms_set_amount       decimal(20,2),
main_rated_sms_roam_in_amount   decimal(20,2),
main_rated_sms_roam_out_amount  decimal(20,2),
main_rated_sms_sva_amount       decimal(20,2),
main_rated_sms_int_amount       decimal(20,2),
subs_bundle_plenty_count        decimal(20,2),
subs_orange_bonus_count         decimal(20,2),
subs_fnf_modify_count           decimal(20,2),
subs_data_2g_count              decimal(20,2),
subs_data_3g_jour_count         decimal(20,2),
subs_data_3g_semaine_count      decimal(20,2),
subs_data_3g_mois_count         decimal(20,2),
subs_maxi_bonus_count           decimal(20,2),
subs_pro_count                  decimal(20,2),
subs_intern_jour_count          decimal(20,2),
subs_intern_semaine_count       decimal(20,2),
subs_intern_mois_count          decimal(20,2),
subs_pack_sms_jour_count        decimal(20,2),
subs_pack_sms_semaine_count     decimal(20,2),
subs_pack_sms_mois_count        decimal(20,2),
subs_ws_count                   decimal(20,2),
subs_obonus_illimite_count      decimal(20,2),
subs_orange_phenix_count        decimal(20,2),
subs_recharge_plenty_count      decimal(20,2),
subs_autres_count               decimal(20,2),
subs_data_flybox_count          decimal(20,2),
subs_data_autres_count          decimal(20,2),
subs_roaming_count              decimal(20,2),
subs_sms_autres_count           decimal(20,2),
subs_bundle_plenty_amount       decimal(20,2),
subs_orange_bonus_amount        decimal(20,2),
subs_fnf_modify_amount          decimal(20,2),
subs_data_2g_amount             decimal(20,2),
subs_data_3g_jour_amount        decimal(20,2),
subs_data_3g_semaine_amount     decimal(20,2),
subs_data_3g_mois_amount        decimal(20,2),
subs_maxi_bonus_amount          decimal(20,2),
subs_pro_amount                 decimal(20,2),
subs_intern_jour_amount         decimal(20,2),
subs_intern_semaine_amount      decimal(20,2),
subs_intern_mois_amount         decimal(20,2),
subs_pack_sms_jour_amount       decimal(20,2),
subs_pack_sms_semaine_amount    decimal(20,2),
subs_pack_sms_mois_amount       decimal(20,2),
subs_ws_amount                  decimal(20,2),
subs_obonus_illimite_amount     decimal(20,2),
subs_orange_phenix_amount       decimal(20,2),
subs_recharge_plenty_amount     decimal(20,2),
subs_autres_amount              decimal(20,2),
subs_data_flybox_amount         decimal(20,2),
subs_data_autres_amount         decimal(20,2),
subs_roaming_amount             decimal(20,2),
subs_sms_autres_amount          decimal(20,2),
insert_date                     timestamp  ,
refresh_date                    timestamp  ,
subs_voice_count                decimal(20,2),
subs_sms_count                  decimal(20,2),
subs_data_count                 decimal(20,2),
subs_voice_amount               decimal(20,2),
subs_sms_amount                 decimal(20,2),
subs_data_amount                decimal(20,2),
revenu_moyen                    decimal(20,2),
premium                         decimal(20,2),
conso_moy_data                  decimal(20,2),
recharge_moy                    decimal(20,2),
premium_plus                    decimal(20,2),
ter_imei                        varchar(16)

)
PARTITIONED BY (EVENT_DATE DATE)
STORED AS PARQUET TBLPROPERTIES ('PARQUET.COMPRESS'='SNAPPY')







CREATE TABLE BACKUP_DWH.FT_MARKETING_DATAMART_TMP

(
msisdn                          varchar(50),
loc_site_name                   varchar(50),
loc_town_name                   varchar(50),
loc_admintrative_region         varchar(50),
loc_commercial_region           varchar(50),
ter_tac_code                    varchar(8) ,
ter_constructor                 varchar(255) ,
ter_model                       varchar(255) ,
ter_2g_3g_4g_compatibility      varchar(50),
ter_2g_compatibility           varchar(1)    ,
ter_3g_compatibility           varchar(1)    ,
ter_4g_compatibility           varchar(1)    ,
contract_type                   varchar(50),
commercial_offer                varchar(50),
activation_date                varchar(24)  ,
deactivation_date              varchar(24)  ,
lang                            varchar(5) ,
osp_status                      varchar(30),
imsi                            varchar(25),
grp_last_og_call               varchar(24)  ,
grp_last_ic_call               varchar(24)  ,
grp_remain_credit_main         varchar(24),
grp_remain_credit_promo        varchar(24),
grp_gp_status                   varchar(5) ,
dir_first_name                  varchar(250) ,
dir_last_name                   varchar(250) ,
dir_birth_date                 varchar(24)  ,
dir_identification_town         varchar(250) ,
dir_identification_date        varchar(24)  ,
data_main_rated_amount         varchar(24),
data_gos_main_rated_amount     varchar(24),
data_promo_rated_amount        varchar(24),
data_roam_main_rated_amount    varchar(24),
data_roam_promo_rated_amount   varchar(24),
data_bytes_received            varchar(24),
data_bytes_sent                varchar(24),
data_bytes_used_in_bundle      varchar(24),
data_bytes_used_paygo          varchar(24),
data_bytes_used_in_bundle_roam varchar(24),
data_byte_used_out_bundle_roam varchar(24),
data_mms_used                  varchar(24),
data_mms_used_in_bundle        varchar(24),
sos_loan_count                 varchar(24),
sos_loan_amount                varchar(24),
sos_reimbursement_count        varchar(24),
sos_reimbursement_amount       varchar(24),
sos_fees                       varchar(24),
total_revenue                  varchar(24),
total_voice_revenue            varchar(24),
total_sms_revenue              varchar(24),
total_subs_revenue             varchar(24),
c2s_refill_count               varchar(24),
c2s_main_refill_amount         varchar(24),
c2s_promo_refill_amount        varchar(24),
p2p_refill_count               varchar(24),
p2p_refill_amount              varchar(24),
scratch_refill_count           varchar(24),
scratch_main_refill_amount     varchar(24),
scratch_promo_refill_amount    varchar(24),
p2p_refill_fees                varchar(24),
total_data_revenue             varchar(24),
roam_data_revenue              varchar(24),
roam_in_voice_revenue          varchar(24),
roam_out_voice_revenue         varchar(24),
roam_in_sms_revenue            varchar(24),
roam_out_sms_revenue           varchar(24),
og_call_total_count            varchar(24),
og_call_ocm_count              varchar(24),
og_call_mtn_count              varchar(24),
og_call_nexttel_count          varchar(24),
og_call_camtel_count           varchar(24),
og_call_set_count              varchar(24),
og_call_roam_in_count          varchar(24),
og_call_roam_out_count         varchar(24),
og_call_sva_count              varchar(24),
og_call_international_count    varchar(24),
og_rated_call_duration         varchar(24),
og_total_call_duration         varchar(24),
rated_tel_ocm_duration         varchar(24),
rated_tel_mtn_duration         varchar(24),
rated_tel_nexttel_duration     varchar(24),
rated_tel_camtel_duration      varchar(24),
rated_tel_set_duration         varchar(24),
rated_tel_roam_in_duration     varchar(24),
rated_tel_roam_out_duration    varchar(24),
rated_tel_sva_duration         varchar(24),
rated_tel_int_duration         varchar(24),
main_rated_tel_amount          varchar(24),
promo_rated_tel_amount         varchar(24),
og_total_rated_call_amount     varchar(24),
main_rated_tel_ocm_amount      varchar(24),
main_rated_tel_mtn_amount      varchar(24),
main_rated_tel_nexttel_amount  varchar(24),
main_rated_tel_camtel_amount   varchar(24),
main_rated_tel_set_amount      varchar(24),
main_rated_tel_roam_in_amount  varchar(24),
main_rated_tel_roam_out_amount varchar(24),
main_rated_tel_sva_amount      varchar(24),
main_rated_tel_int_amount      varchar(24),
promo_rated_tel_ocm_amount     varchar(24),
promo_rated_tel_mtn_amount     varchar(24),
promo_rated_tel_nexttel_amount varchar(24),
promo_rated_tel_camtel_amount  varchar(24),
promo_rated_tel_set_amount     varchar(24),
promo_rated_tel_roamin_amount  varchar(24),
promo_rated_tel_roamout_amount varchar(24),
promo_rated_tel_int_amount     varchar(24),
og_sms_total_count             varchar(24),
og_sms_ocm_count               varchar(24),
og_sms_mtn_count               varchar(24),
og_sms_nexttel_count           varchar(24),
og_sms_camtel_count            varchar(24),
og_sms_set_count               varchar(24),
og_sms_roam_in_count           varchar(24),
og_sms_roam_out_count          varchar(24),
og_sms_sva_count               varchar(24),
og_sms_international_count     varchar(24),
main_rated_sms_amount          varchar(24),
main_rated_sms_ocm_amount      varchar(24),
main_rated_sms_mtn_amount      varchar(24),
main_rated_sms_nexttel_amount  varchar(24),
main_rated_sms_camtel_amount   varchar(24),
main_rated_sms_set_amount      varchar(24),
main_rated_sms_roam_in_amount  varchar(24),
main_rated_sms_roam_out_amount varchar(24),
main_rated_sms_sva_amount      varchar(24),
main_rated_sms_int_amount      varchar(24),
subs_bundle_plenty_count       varchar(24),
subs_orange_bonus_count        varchar(24),
subs_fnf_modify_count          varchar(24),
subs_data_2g_count             varchar(24),
subs_data_3g_jour_count        varchar(24),
subs_data_3g_semaine_count     varchar(24),
subs_data_3g_mois_count        varchar(24),
subs_maxi_bonus_count          varchar(24),
subs_pro_count                 varchar(24),
subs_intern_jour_count         varchar(24),
subs_intern_semaine_count      varchar(24),
subs_intern_mois_count         varchar(24),
subs_pack_sms_jour_count       varchar(24),
subs_pack_sms_semaine_count    varchar(24),
subs_pack_sms_mois_count       varchar(24),
subs_ws_count                  varchar(24),
subs_obonus_illimite_count     varchar(24),
subs_orange_phenix_count       varchar(24),
subs_recharge_plenty_count     varchar(24),
subs_autres_count              varchar(24),
subs_data_flybox_count         varchar(24),
subs_data_autres_count         varchar(24),
subs_roaming_count             varchar(24),
subs_sms_autres_count          varchar(24),
subs_bundle_plenty_amount      varchar(24),
subs_orange_bonus_amount       varchar(24),
subs_fnf_modify_amount         varchar(24),
subs_data_2g_amount            varchar(24),
subs_data_3g_jour_amount       varchar(24),
subs_data_3g_semaine_amount    varchar(24),
subs_data_3g_mois_amount       varchar(24),
subs_maxi_bonus_amount         varchar(24),
subs_pro_amount                varchar(24),
subs_intern_jour_amount        varchar(24),
subs_intern_semaine_amount     varchar(24),
subs_intern_mois_amount        varchar(24),
subs_pack_sms_jour_amount      varchar(24),
subs_pack_sms_semaine_amount   varchar(24),
subs_pack_sms_mois_amount      varchar(24),
subs_ws_amount                 varchar(24),
subs_obonus_illimite_amount    varchar(24),
subs_orange_phenix_amount      varchar(24),
subs_recharge_plenty_amount    varchar(24),
subs_autres_amount             varchar(24),
subs_data_flybox_amount        varchar(24),
subs_data_autres_amount        varchar(24),
subs_roaming_amount            varchar(24),
subs_sms_autres_amount         varchar(24),
insert_date                     timestamp  ,
refresh_date                    timestamp  ,
subs_voice_count               varchar(24),
subs_sms_count                 varchar(24),
subs_data_count                varchar(24),
subs_voice_amount              varchar(24),
subs_sms_amount                varchar(24),
subs_data_amount               varchar(24),
revenu_moyen                   varchar(24),
premium                        varchar(24),
conso_moy_data                 varchar(24),
recharge_moy                   varchar(24),
premium_plus                   varchar(24),
ter_imei                        varchar(16),
EVENT_DATE varchar(24)

)
STORED AS PARQUET TBLPROPERTIES ('PARQUET.COMPRESS'='SNAPPY')



