INSERT INTO MON.SPARK_FT_MSISDN_IMEI_LOCALISATION
SELECT
    A.MSISDN MSISDN,
    IMEI,
    SITE_NAME,
    CURRENT_TIMESTAMP() INSERT_DATE,
    '###SLICE_VALUE###' EVENT_DATE
FROM
(
    SELECT *
    FROM MON.SPARK_FT_IMEI_ONLINE
    WHERE SDATE = '###SLICE_VALUE###'
) A
LEFT JOIN
(
    SELECT
        B0.MSISDN,
        UPPER(NVL(B0.SITE_NAME, B1.SITE_NAME)) SITE_NAME
    FROM
    (
        SELECT
            MSISDN,
            MAX(SITE_NAME) SITE_NAME
        FROM MON.SPARK_FT_CLIENT_LAST_SITE_DAY
        WHERE EVENT_DATE = '###SLICE_VALUE###'
        GROUP BY MSISDN
    ) B0
    LEFT JOIN
    (
        SELECT
            MSISDN,
            MAX(SITE_NAME) SITE_NAME
        FROM MON.SPARK_FT_CLIENT_SITE_TRAFFIC_DAY
        WHERE EVENT_DATE = '###SLICE_VALUE###'
        GROUP BY MSISDN
    ) B1
    ON B0.MSISDN = B1.MSISDN
) B
ON A.MSISDN = B.MSISDN