CREATE TABLE MON.SPARK_FT_MSISDN_IMEI_LOCALISATION(
    MSISDN varchar(255),
    IMEI varchar(255),
    SITE_NAME varchar(255),
    INSERT_DATE TIMESTAMP
)
PARTITIONED BY (EVENT_DATE DATE)
STORED AS PARQUET
TBLPROPERTIES ('PARQUET.COMPRESS'='SNAPPY')