SELECT IF(
    T_1.FT_COUNT = 0
    AND T_2.FT_COUNT > 0
    AND T_3.FT_COUNT > 0
    , "OK"
    , "NOK"
)
FROM
(SELECT COUNT(*) FT_COUNT FROM MON.SPARK_FT_MSISDN_IMEI_LOCALISATION WHERE EVENT_DATE='###SLICE_VALUE###') T_1,
(SELECT COUNT(*) FT_COUNT FROM MON.SPARK_FT_CLIENT_LAST_SITE_DAY WHERE EVENT_DATE='###SLICE_VALUE###') T_2,
(SELECT COUNT(*) FT_COUNT FROM MON.SPARK_FT_CLIENT_SITE_TRAFFIC_DAY WHERE EVENT_DATE='###SLICE_VALUE###') T_3