SELECT IF(
    A.FT_EXIST = 0
    AND B.FT_COUNT > DATEDIFF(LAST_DAY('###SLICE_VALUE###'||'-01') , '###SLICE_VALUE###'||'-01') , "OK","NOK"
) FROM
(SELECT COUNT(*) FT_EXIST FROM MON.SPARK_FT_CBM_CUST_INSIGTH_MONTHLY WHERE PERIOD = '###SLICE_VALUE###') A,
(SELECT COUNT(DISTINCT PERIOD) FT_COUNT FROM MON.SPARK_FT_CBM_CUST_INSIGTH_DAILY WHERE PERIOD BETWEEN TO_DATE('###SLICE_VALUE###'||'-01') AND LAST_DAY('###SLICE_VALUE###'||'-01')) B