SELECT IF(A.FT_EXIST = 0 and B.FT_COUNT>0 and C.FT_COUNT > datediff(last_day('###SLICE_VALUE###'||'-01') , '###SLICE_VALUE###'||'-01') , "OK","NOK") FROM
(SELECT COUNT(*) FT_EXIST FROM MON.SPARK_FT_MARKETING_DATAMART_MONTH WHERE EVENT_MONTH='###SLICE_VALUE###') A,
(SELECT COUNT(DISTINCT EVENT_DATE) FT_COUNT FROM MON.SPARK_FT_MARKETING_DATAMART WHERE EVENT_DATE BETWEEN TO_DATE('###SLICE_VALUE###'||'-01') AND LAST_DAY('###SLICE_VALUE###'||'-01')) B,




