INSERT INTO MON.SPARK_FT_CBM_BUNDLE_SUBS_DAILY PARTITION(PERIOD)
    SELECT
    SERVED_PARTY_MSISDN AS MSISDN,
    (CASE 
        WHEN SUBSCRIPTION_CHANNEL='PARRAINAGE' THEN SUM(BDLE_COST_DEFAULT)
        ELSE SUM(RATED_AMOUNT)
    END ) BDLE_COST, --Prise en compte des couts souscriptions via OM: Channel Id 32
    COUNT(*) AS NBER_PURCHASE,
    SUBSCRIPTION_SERVICE_DETAILS AS BDLE_NAME,
    (CASE 
        WHEN UPPER(SUBSCRIPTION_SERVICE_DETAILS) LIKE '%JRS' THEN CAST(SUBSTR(SUBSCRIPTION_SERVICE_DETAILS, -5, 2) AS BIGINT)
        ELSE  DATEDIFF(EXPIRE_DATE,ACTIVE_DATE)
    END) Validity,
    SUBSCRIPTION_CHANNEL,
    SUM(AMOUNT_VOICE_ONNET) AS AMOUNT_VOICE_ONNET,
    SUM(AMOUNT_VOICE_OFFNET)  AS AMOUNT_VOICE_OFFNET,
    SUM(AMOUNT_VOICE_INTER)  AS AMOUNT_VOICE_INTER,
    SUM(AMOUNT_VOICE_ROAMING)  AS AMOUNT_VOICE_ROAMING,
    SUM(AMOUNT_SMS_ONNET)  AS AMOUNT_SMS_ONNET,
    SUM(AMOUNT_SMS_OFFNET)  AS AMOUNT_SMS_OFFNET,
    SUM(AMOUNT_SMS_INTER)  AS AMOUNT_SMS_INTER,
    SUM(AMOUNT_SMS_ROAMING)  AS AMOUNT_SMS_ROAMING,
    SUM(AMOUNT_DATA) AS AMOUNT_DATA,
    SUM(AMOUNT_SVA)  AS AMOUNT_SVA,
    current_timestamp AS INSERT_DATE,
    BENEFIT_BAL_LIST,
    BAL_ID,
    '###SLICE_VALUE###' AS PERIOD

    FROM 
    (
        SELECT SERVED_PARTY_MSISDN
            , RATED_AMOUNT
            , SUBSCRIPTION_SERVICE_DETAILS
            , SUBSCRIPTION_CHANNEL
            , EXPIRE_DATE
            , ACTIVE_DATE
            , AMOUNT_VOICE_ONNET
            , AMOUNT_VOICE_OFFNET
            , AMOUNT_VOICE_INTER
            , AMOUNT_VOICE_ROAMING
            , AMOUNT_SMS_ONNET
            , AMOUNT_SMS_OFFNET
            , AMOUNT_SMS_INTER
            , AMOUNT_SMS_ROAMING
            , AMOUNT_DATA
            , AMOUNT_SVA
            , BENEFIT_BAL_LIST
            , BAL_ID
        FROM MON.SPARK_FT_SUBSCRIPTION
        WHERE TRANSACTION_DATE = '###SLICE_VALUE###'
    ) A
    LEFT JOIN 
    (
        SELECT IPP_NAME
            , IPP_CODE
            , IPP_AMOUNT
            , CREATE_DATE
        FROM DIM.REF_SOUSCRIPTION_PRICE
    ) B
    ON UPPER(A.SUBSCRIPTION_SERVICE_DETAILS) = UPPER(B.IPP_NAME)
    LEFT JOIN
    (
        SELECT BDLE_NAME
            , BDLE_COST BDLE_COST_DEFAULT
        FROM CDR.DT_SERVICES_DEFAULT
    ) C
    ON UPPER(A.SUBSCRIPTION_SERVICE_DETAILS) = UPPER(C.BDLE_NAME)
    GROUP BY
        SERVED_PARTY_MSISDN,
        SUBSCRIPTION_SERVICE_DETAILS,
        SUBSCRIPTION_CHANNEL,
        BENEFIT_BAL_LIST,
        bal_id,
        (CASE WHEN UPPER(SUBSCRIPTION_SERVICE_DETAILS) LIKE '%JRS' then cast(SUBSTR(SUBSCRIPTION_SERVICE_DETAILS, -5, 2) AS BIGINT)
            ELSE  datediff(EXPIRE_DATE,ACTIVE_DATE)
            end),
        BAL_ID
