SELECT IF(T.FT_EXIST = 0 and NOMAD_EXIST > 0 ,"OK","NOK") TABLES_EXIST
FROM
(SELECT COUNT(*) FT_EXIST FROM MON.SPARK_OMNY_NEW_ACCOUNT WHERE ORIGINAL_FILE_DATE='###SLICE_VALUE###') T,
(SELECT COUNT(*) NOMAD_EXIST FROM CDR.SPARK_IT_NOMAD_CLIENT_DIRECTORY WHERE ORIGINAL_FILE_DATE=DATE_ADD("###SLICE_VALUE###",1)) A