CREATE TABLE DIM.DT_SITE_ZONE(
SITE_COD VARCHAR(50),
SITE VARCHAR(100),
VILLE VARCHAR(70),
REGION VARCHAR(70),
LONG VARCHAR(70),
LAT VARCHAR(70),
ZONE VARCHAR(30),
TECHNO VARCHAR(20),
ZONE_LIB VARCHAR(150),
REGION_PMO VARCHAR(50),
SECTEUR VARCHAR(150)
) STORED AS PARQUET TBLPROPERTIES ('PARQUET.COMPRESS'='SNAPPY');