INSERT INTO DIM.BDI_DEROGATION
SELECT
NUMERO_PIECE ,
VALID_FROM ,
VALID_TO ,
CURRENT_TIMESTAMP AS INSERT_DATE ,
TO_DATE(FROM_UNIXTIME(UNIX_TIMESTAMP(SUBSTRING ('bdi_20200313_derogation.txt', -23, 8),'yyyyMMdd'))) FILE_DATE
FROM DIM.TT_BDI_DEROGATION C
LEFT JOIN (SELECT DISTINCT  ORIGINAL_FILE_NAME FILE_NAME FROM CDR.SPARK_IT_BDI WHERE ORIGINAL_FILE_DATE BETWEEN DATE_SUB(CURRENT_DATE,${hivevar:date_offset}) AND CURRENT_DATE )T ON T.FILE_NAME=C.ORIGINAL_FILE_NAME
WHERE T.FILE_NAME IS NULL
