INSERT INTO MON.SMS_FICHIERS_IN
SELECT
    MSISDN,
    sms,
    CURRENT_TIMESTAMP INSERT_DATE,
    transaction_date
FROM(
    SELECT *
    FROM  dim.dt_smsnotification_recipient
    WHERE type='FICHIERS_IN' AND actif='YES'
) A
LEFT JOIN (
  SELECT
        transaction_date,
        CONCAT(
        'LE M ',DATE_FORMAT(B.TRANSACTION_DATE,'dd/MM')
		, ' \n' ,NB_TOTAL,' Fichiers manquant'
        , ' \n' ,'-SOURCE :  ','IN'
        , ' \n' ,'-TYPES: '
	    , ' \n' ,CASE WHEN DATA<>0  THEN '-DATA :' ELSE '' END,CASE WHEN DATA<>0  THEN DATA ELSE '' END
		, ' \n' ,CASE WHEN SMS<>0  THEN '-VOIX/SMS: ' ELSE '' END,CASE WHEN DATA<>0  THEN SMS ELSE '' END
		, ' \n' ,CASE WHEN SUBSCRIB<>0  THEN '-SUBSCRIB: ' ELSE '' END,CASE WHEN DATA<>0  THEN SUBSCRIB ELSE '' END
		, ' \n' ,CASE WHEN EMER_CREDIT<>0  THEN '-EMER_CREDIT: ' ELSE '' END,CASE WHEN DATA<>0  THEN EMER_CREDIT ELSE '' END
		, ' \n' ,CASE WHEN AJUSTMENT<>0  THEN '-AJUSTMENT: ' ELSE '' END,CASE WHEN DATA<>0  THEN AJUSTMENT ELSE '' END
		, ' \n' ,CASE WHEN RECHARGE<>0  THEN '-RECHARGE: ' ELSE '' END,CASE WHEN DATA<>0  THEN RECHARGE ELSE '' END
		, ' \n' ,CASE WHEN EXTRA<>0  THEN '-EXTRA: ' ELSE '' END,CASE WHEN DATA<>0  THEN EXTRA ELSE '' END
		, ' \n' ,CASE WHEN PROFILE<>0  THEN '-PROFILE: ' ELSE '' END,CASE WHEN DATA<>0  THEN PROFILE ELSE '' END
		, ' \n' ,CASE WHEN DATA_POST<>0  THEN '-DATA_POST: ' ELSE '' END,CASE WHEN DATA<>0  THEN DATA_POST ELSE '' END
		, ' \n' ,CASE WHEN TRANSFER<>0  THEN '-TRANSFER: ' ELSE '' END,CASE WHEN DATA<>0  THEN TRANSFER ELSE '' END
		)  SMS

        FROM(
            select
                '###SLICE_VALUE###' transaction_date,
                SUM(CASE  WHEN TABLE_SOURCE = 'IN' THEN 1 ELSE 0 END) NB_TOTAL,

				SUM(CASE  WHEN TABLE_SOURCE = 'IN' AND UPPER(SUBSTR(FILE_NAME,-34,6))='_DATA_' THEN 1 ELSE 0 END) DATA,
				SUM(CASE  WHEN TABLE_SOURCE = 'IN' AND UPPER(SUBSTR(FILE_NAME,-33,5))='_SMS_' THEN 1 ELSE 0 END) SMS,
				SUM(CASE  WHEN TABLE_SOURCE = 'IN' AND UPPER(SUBSTR(FILE_NAME,-33,14))='_SUBSCRIPTION_' THEN 1 ELSE 0 END) SUBSCRIB,
				SUM(CASE  WHEN TABLE_SOURCE = 'IN' AND UPPER(SUBSTR(FILE_NAME,1,9))='IN_PR_EC_' THEN 1 ELSE 0 END) EMER_CREDIT,
				SUM(CASE  WHEN TABLE_SOURCE = 'IN' AND UPPER(SUBSTR(FILE_NAME,1,9))='IN_PR_ED_' THEN 1 ELSE 0 END)  EMER_DATA,
				SUM(CASE  WHEN TABLE_SOURCE = 'IN' AND UPPER(SUBSTR(FILE_NAME,-33,5))='_ADJUSTMENT_' THEN 1 ELSE 0 END) AJUSTMENT,
				SUM(CASE  WHEN TABLE_SOURCE = 'IN' AND UPPER(SUBSTR(FILE_NAME,-21,9))='_RECHARGE_' THEN 1 ELSE 0 END) RECHARGE,
				SUM(CASE  WHEN TABLE_SOURCE = 'IN' AND UPPER(SUBSTR(FILE_NAME,-21,9))='_EXTRACT_' OR UPPER(SUBSTR(FILE_NAME,-31,8))='_ETRACT_' THEN 1 ELSE 0 END) EXTRA,
				SUM(CASE  WHEN TABLE_SOURCE = 'IN' AND UPPER(SUBSTR(FILE_NAME,1,8))='PROFILE_' THEN 1 ELSE 0 END) PROFILE,
				SUM(CASE  WHEN TABLE_SOURCE = 'IN' AND UPPER(SUBSTR(FILE_NAME,18,6))='_DATA_' THEN 1 ELSE 0 END) DATA_POST,
				SUM(CASE  WHEN TABLE_SOURCE = 'IN' AND UPPER(SUBSTR(FILE_NAME,1,12))='IN_PR_TRANSFER_' THEN 1 ELSE 0 END) TRANSFER
				FROM  mon.missing_files WHERE original_file_date = date_sub('###SLICE_VALUE###',1)

		) B
	) C