SELECT IF(T_1.REVENUE_EXISTS = 0 AND T_2.SOURCE_DATA=14,"OK","NOK") REVENUE_EXISTS
FROM
(SELECT COUNT(*) REVENUE_EXISTS FROM REVENUE_MARKETING WHERE TRANSACTION_DATE='###SLICE_VALUE###') T_1,
(SELECT COUNT(DISTINCT SOURCE_DATA) SOURCE_DATA  FROM REPORT.FT_GLOBAL_ACTIVITY_DAILY WHERE TRANSACTION_DATE='###SLICE_VALUE###') T_2
