SELECT  IF(T_1.SMS_EXISTS = 0 AND T_2.SMS_PREV_EXISTS>=1 AND T_3.FT_OMNY_GLOBAL_ACTIVITY>=1,"OK","NOK") REVENUE_EXISTS
FROM
(SELECT COUNT(*) SMS_EXISTS FROM MON.SPARK_SMS_OM WHERE SDATE='###SLICE_VALUE###') T_1,
(SELECT COUNT(*) SMS_PREV_EXISTS FROM MON.SPARK_SMS_OM WHERE SDATE=DATE_SUB('###SLICE_VALUE###',1)) T_2,
(SELECT COUNT(*) FT_OMNY_GLOBAL_ACTIVITY  FROM MON.SPARK_FT_OMNY_GLOBAL_ACTIVITY WHERE EVENT_DATE='###SLICE_VALUE###') T_3