SELECT IF(T_1.SMS_EXISTS = 0 AND T_5.SMS_PREV_EXISTS > 0 AND T_2.GSM_TRAFFIC_EXISTS>0 AND T_3.FT_A_GPRS_ACTIVITY_EXISTS>0 ,"OK","NOK") REVENUE_EXISTS
FROM
(SELECT COUNT(*) SMS_EXISTS FROM MON.SPARK_SMS_USAGE WHERE TRANSACTION_DATE='###SLICE_VALUE###') T_1,
(SELECT COUNT(*) SMS_PREV_EXISTS FROM MON.SPARK_SMS_USAGE WHERE TRANSACTION_DATE=DATE_SUB('###SLICE_VALUE###',1)) T_5,
(SELECT COUNT(*) GSM_TRAFFIC_EXISTS  FROM AGG.SPARK_FT_GSM_TRAFFIC_REVENUE_DAILY WHERE TRANSACTION_DATE='###SLICE_VALUE###') T_2,
(SELECT COUNT(*) FT_A_GPRS_ACTIVITY_EXISTS  FROM AGG.SPARK_FT_A_GPRS_ACTIVITY WHERE DATECODE='###SLICE_VALUE###') T_3