CREATE TABLE SPOOL.SPOOL_CONFORMITE_OM_KYC

(
NOM varchar(200),
PRENOM varchar(200),
DATE_NAISSANCE DATE,
NUMERO_CNI varchar(50),
MSISDN varchar(50),
EST_ACTIF_OM CHAR(3),
Activation_date_TEL TIMESTAMP ,
Created_date_OM TIMESTAMP,
INSERT_DATE TIMESTAMP
)

PARTITIONED BY (EVENT_DATE DATE)
STORED AS PARQUET TBLPROPERTIES ('PARQUET.COMPRESS' = 'SNAPPY')


