CREATE TABLE MON.SPARK_FT_LOCATION_RETAILLER_TMP
(
	SITE_NAME VARCHAR(50),
	CATEGORY VARCHAR(126),
	REFILL_AMOUNT INT,
	TRANSACTION_COUNT INT,
	SOURCE_TYPE VARCHAR(250),
	INSERT_DATE TIMESTAMP
   ) COMMENT 'SPARK_FT_RETAIL_BASE_DETAILLANT'
 PARTITIONED BY (REFILL_DATE DATE)
 STORED AS PARQUET
 TBLPROPERTIES ("parquet.compress"="SNAPPY")
