 INSERT INTO MON.FT_SUBSCRIPTION_MSISDN_DAY PARTITION(EVENT_DATE)
        SELECT 
          
          SERVED_PARTY_MSISDN MSISDN
        , MAX(COMMERCIAL_OFFER) CUSTOMER_PROFILE
        , MAX(CONTRACT_TYPE) AS CONTRACT_TYPE
        , COUNT(1) TOTAL_SUBS_COUNT
        , SUM(NVL(RATED_AMOUNT, 0)) TOTAL_SUBS_AMOUNT
        , SUM(CASE WHEN SERVICE_CODE = 'BUN_VOI' THEN 1 ELSE 0 END) VOICE_BUNDLE_COUNT
        , NULL AS VOICE_BUNDLE_MINUTES
        , SUM(CASE WHEN SERVICE_CODE = 'BUN_VOI' THEN NVL(RATED_AMOUNT, 0) ELSE 0 END) VOICE_BUNDLE_AMOUNT
        , SUM(CASE WHEN SERVICE_CODE = 'BUN_SMS' THEN 1 ELSE 0 END) SMS_BUNDLE_COUNT
        , NULL SMS_BUNDLE_VOLUME 
        , SUM(CASE WHEN SERVICE_CODE = 'BUN_SMS' THEN NVL(RATED_AMOUNT, 0) ELSE 0 END) SMS_BUNDLE_AMOUNT
        , SUM(CASE WHEN SERVICE_CODE = 'BUN_DAT' THEN 1 ELSE 0 END) DATA_BUNDLE_COUNT
        , NULL DATA_BUNDLE_BYTES
        , SUM(CASE WHEN SERVICE_CODE = 'BUN_DAT' THEN NVL(RATED_AMOUNT, 0) ELSE 0 END) DATA_BUNDLE_AMOUNT
        , SUM(CASE WHEN SERVICE_CODE = 'BUN_VSD' THEN 1 ELSE 0 END) VOI_DAT_SMS_BUN_COUNT
        , SUM(CASE WHEN SERVICE_CODE = 'BUN_VSD' THEN NVL(RATED_AMOUNT, 0) ELSE 0 END) VOI_DAT_SMS_BUN_AMOUNT
        , SUM(CASE WHEN SERVICE_CODE = 'BUN_VOS' THEN 1 ELSE 0 END) VOI_SMS_BUN_COUNT
        , SUM(CASE WHEN SERVICE_CODE = 'BUN_VOS' THEN NVL(RATED_AMOUNT, 0) ELSE 0 END) VOI_SMS_BUN_AMOUNT
        , SUM(CASE WHEN SERVICE_CODE = 'BUN_VOD' THEN 1 ELSE 0 END) VOI_DAT_BUN_COUNT
        , SUM(CASE WHEN SERVICE_CODE = 'BUN_VOD' THEN NVL(RATED_AMOUNT, 0) ELSE 0 END) VOI_DAT_BUN_AMOUNT
        , SUM(CASE WHEN SERVICE_CODE = 'BUN_SMD' THEN 1 ELSE 0 END) DAT_SMS_BUN_COUNT
        , SUM(CASE WHEN SERVICE_CODE = 'BUN_SMD' THEN NVL(RATED_AMOUNT, 0) ELSE 0 END) DAT_SMS_BUN_AMOUNT
        , SUM(CASE WHEN SERVICE_CODE NOT IN ('BUN_VOI', 'BUN_SMS', 'BUN_DAT', 'BUN_VSD', 'BUN_VOS', 'BUN_VOD', 'BUN_SMD') THEN 1 ELSE 0 END) OTHER_SUBS_COUNT
        , SUM(CASE WHEN SERVICE_CODE NOT IN ('BUN_VOI', 'BUN_SMS', 'BUN_DAT', 'BUN_VSD', 'BUN_VOS', 'BUN_VOD', 'BUN_SMD') THEN NVL(RATED_AMOUNT, 0) ELSE 0 END) OTHER_SUBS_AMOUNT
        , 'FT_SUBSCRIPTION' SRC_TABLE
        , MAX(OPERATOR_CODE) AS OPERATOR_CODE
        , CURRENT_TIMESTAMP INSERT_DATE
        ,SUM(AMOUNT_VOICE_ONNET) AMOUNT_VOICE_ONNET
        ,SUM(AMOUNT_VOICE_OFFNET) AMOUNT_VOICE_OFFNET
        ,SUM(AMOUNT_VOICE_INTER) AMOUNT_VOICE_INTER
        ,SUM(AMOUNT_VOICE_ROAMING) AMOUNT_VOICE_ROAMING
        ,SUM(AMOUNT_SMS_ONNET)  AMOUNT_SMS_ONNET
        ,SUM(AMOUNT_SMS_OFFNET) AMOUNT_SMS_OFFNET
        ,SUM(AMOUNT_SMS_INTER)  AMOUNT_SMS_INTER
        ,SUM(AMOUNT_SMS_ROAMING) AMOUNT_SMS_ROAMING
        ,SUM(AMOUNT_DATA)  AMOUNT_DATA
        ,SUM(AMOUNT_SVA)  AMOUNT_SVA
        ,TRANSACTION_DATE EVENT_DATE
        FROM MON.SPARK_FT_SUBSCRIPTION WHERE TRANSACTION_DATE = '###SLICE_VALUE###'
        GROUP BY SERVED_PARTY_MSISDN, TRANSACTION_DATE