CREATE  TABLE CDR.IT_GESFLOT
(

CustId VARCHAR(200),
CustName VARCHAR(200),
phoneNumber VARCHAR(200),
Email VARCHAR(200),
faxNumber VARCHAR(200),
ORIGINAL_FILE_NAME VARCHAR(200),
ORIGINAL_FILE_SIZE VARCHAR(200),
ORIGINAL_FILE_LINE_COUNT VARCHAR(200),
INSERT_DATE timestamp
)
PARTITIONED BY (original_file_date DATE)
CLUSTERED BY(CustId) INTO 8 BUCKETS
STORED AS ORC
TBLPROPERTIES ('transactional'='true',"orc.compress"="ZLIB","orc.stripe.size"="67108864");