CREATE  TABLE CDR.SPARK_IT_BILLCYCLE
(
    BILL_CYCLE_ID VARCHAR(200),
    DESCRIPTION VARCHAR(200),
    ORIGINAL_FILE_NAME VARCHAR(200),
    ORIGINAL_FILE_SIZE INT,
    ORIGINAL_FILE_LINE_COUNT INT,
    INSERT_DATE timestamp

)
PARTITIONED BY (original_file_date DATE)
CLUSTERED BY(BILL_CYCLE_ID) INTO 8 BUCKETS
STORED AS PARQUET
TBLPROPERTIES ("parquet.compress"="SNAPPY");