CREATE  TABLE CDR.IT_CHANTEL
(
CustId VARCHAR(200),
Subs_id VARCHAR(200),
ACCNBR VARCHAR(200),
Update_date timestamp,
ORIGINAL_FILE_NAME VARCHAR(200),
ORIGINAL_FILE_SIZE INT,
ORIGINAL_FILE_LINE_COUNT INT,
INSERT_DATE timestamp
)
PARTITIONED BY (original_file_date DATE)
CLUSTERED BY(CustId) INTO 8 BUCKETS
STORED AS ORC
TBLPROPERTIES ('transactional'='true',"orc.compress"="ZLIB","orc.stripe.size"="67108864");