SELECT
  EVENT_MONTH,
  RAISON_SOCIALE,
  CODE_CLIENT,
  VALEUR_CLIENT_VOIX,
  VALEUR_CLIENT_SMS,
  VALEUR_CLIENT_DATA,
  VALEUR_CLIENT_OM,
  VALEUR_CLIENT_GLOBALE,
  SEGMENT_VALEUR_CLIENT_VOIX,
  SEGMENT_VALEUR_CLIENT_DATA,
  SEGMENT_VALEUR_CLIENT_SMS,
  SEGMENT_VALEUR_CLIENT_OM,
  SEGMENT_VALEUR_CLIENT_GLOBALE,
  INSERT_DATE
FROM 
  MON.SPARK_FT_CRM_OUTPUT_B2B
WHERE EVENT_MONTH='###SLICE_VALUE###'