SELECT IF(
T_1.FT_EXIST > DATEDIFF(TO_DATE(DATE_SUB('###SLICE_VALUE###',6)) , TO_DATE('###SLICE_VALUE###')) AND
T_2.NB_EXPORT < 1
,"OK","NOK")
FROM
(SELECT COUNT(DISTINCT MODIFICATION_DATE) FT_EXIST FROM CDR.SPARK_IT_OM_SUBSCRIBERS WHERE MODIFICATION_DATE BETWEEN TO_DATE(DATE_SUB('###SLICE_VALUE###',6)) AND TO_DATE('###SLICE_VALUE###')) T_1,
(
select count(*) NB_EXPORT from
(select * from (SELECT * FROM MON.EXPORT_HISTORY where event_date='###SLICE_VALUE###' and JOB_INSTANCEID='LOAD_OM_ABONNER_OM_HEBDO' ORDER BY INSERT_DATE DESC LIMIT 1)  T where T.STATUS = 'OK') M
) T_2