CREATE EXTERNAL TABLE IF NOT EXISTS CDR.TT_SMSC_MVAS_A2P_CHECKFILES (
    FILE_NAME VARCHAR(50),
    ORIGINAL_FILE_NAME VARCHAR(100),
    ORIGINAL_FILE_SIZE INT,
    ORIGINAL_FILE_LINE_COUNT INT
)
COMMENT 'SMSC MVAS'
ROW FORMAT DELIMITED FIELDS TERMINATED BY ','
LOCATION '/PROD/TT/MVAS/MVAS_CHECKFILES'
TBLPROPERTIES ('serialization.null.format'='');