CREATE EXTERNAL TABLE CDR.tt_smsc_mvas_a2p_checkfiles (
  ORIGINAL_FILE_NAME VARCHAR(200),
  ORIGINAL_FILE_SIZE INT,
  ORIGINAL_FILE_LINE_COUNT INT,
  FILE_NAME  VARCHAR(50)
)
COMMENT 'external tables-TT'
ROW FORMAT DELIMITED FIELDS TERMINATED BY ','
LOCATION '/PROD/TT/MVAS/MVAS_CHECKFILES'
TBLPROPERTIES ('serialization.null.format'='')
;