SELECT IF(
T_1.FT_COUNT > 0 AND
T_2.NB_EXPORT < 1
,"OK","NOK")
FROM
(SELECT COUNT(*) FT_COUNT FROM MON.SPARK_FT_OM_APGL_TRANSACTION WHERE DOCUMENT_DATE='###SLICE_VALUE###') T_1,
(
select count(*) NB_EXPORT from
(select * from (SELECT * FROM MON.EXPORT_HISTORY where event_date='###SLICE_VALUE###' and JOB_INSTANCEID='LOAD_OM_ECRITURE_APGL_TVA' ORDER BY INSERT_DATE DESC LIMIT 1)  T where T.STATUS = 'OK') M
) T_2