CREATE TABLE AGG.SPARK_FT_A_RAS_CONSO_DATA (
BYTES_USED  DOUBLE,
IN_BUNDLE  DOUBLE,
OUT_BUNDLE  DOUBLE,
THROTTLING  DOUBLE,
DAY  INT,
YEAR  INT,
MONTH  INT,
INSERT_DATE  TIMESTAMP
)
COMMENT ' SPARK_FT_A_RAS_CONSO_DATA '
 PARTITIONED BY (EVENT_DATE DATE)
 STORED AS PARQUET
 TBLPROPERTIES ("parquet.compress"="SNAPPY")