SELECT IF(T_1.FT_A_RAS_IPP = 0 and T_2.SEVERAL_SUBSCRIPTIONS > 1 and T_3.FT_SUBSCRIPTION > 1,"OK","NOK") FT_EXIST
FROM
    (SELECT COUNT(*) FT_A_RAS_IPP FROM AGG.SPARK_FT_A_RAS_IPP WHERE EVENT_DATE='###SLICE_VALUE###') T_1,
    (SELECT COUNT(*) SEVERAL_SUBSCRIPTIONS FROM MON.SEVERAL_SUBSCRIPTIONS WHERE EVENT_DATE='###SLICE_VALUE###') T_2,
    (SELECT COUNT(*) FT_SUBSCRIPTION FROM MON.SPARK_FT_SUBSCRIPTION WHERE TRANSACTION_DATE >= DATE_SUB('###SLICE_VALUE###',45)) T_3