
INSERT INTO MON.SPARK_GLOBAL_ACTIVITY_DAILY_STATUS
SELECT
  SOURCE_DATA
  , CAST(SUM(TAXED_AMOUNT) AS INT) TAXED_AMOUNT
  , CURRENT_TIMESTAMP INSERT_DATE
  , '###SLICE_VALUE###' TRANSACTION_DATE
FROM AGG.SPARK_FT_GLOBAL_ACTIVITY_DAILY
WHERE TRANSACTION_DATE='###SLICE_VALUE###'
GROUP BY SOURCE_DATA