
INSERT INTO MON.GLOBAL_ACTIVITY_DAILY_STATUS
SELECT
  SOURCE_DATA
  , ROUND(SUM(TAXED_AMOUNT)) TAXED_AMOUNT
  , CURRENT_TIMESTAMP INSERT_DATE
  , '###SLICE_VALUE###' TRANSACTION_DATE
FROM REPORT.FT_GLOBAL_ACTIVITY_DAILY
WHERE TRANSACTION_DATE='###SLICE_VALUE###'
GROUP BY SOURCE_DATA