
INSERT INTO  MISSING_FILES

SELECT
'###SLICE_VALUE###' ORIGINAL_FILE_DATE,'MSC' TABLE_SOURCE,'NORMAL' FLUX_TYPE,'CRA_MSC_HUAWEI' FLUX_NAME,SEQUENCE FILE_NAME, CURRENT_TIMESTAMP INSERT_DATE
FROM (
    SELECT GENERATE_SEQUENCE_FROM_INTERVALE(PREVIOUS+1,INDEX-1)  SEQ FROM (
        SELECT LAG(INDEX, 1) OVER (PARTITION BY MSC_TYPE ORDER BY INDEX) PREVIOUS,INDEX FROM (
            SELECT
                DISTINCT
                CAST(SUBSTRING(SOURCE,11,9) AS INT) INDEX,
                SUBSTRING(SOURCE,5,11) MSC_TYPE
            FROM CDR.IT_CRA_MSC_HUAWEI
            WHERE CALLDATE = '###SLICE_VALUE###' --AND TO_DATE(ORIGINAL_FILE_DATE)='###SLICE_VALUE###'
        )A
    )D WHERE INDEX-PREVIOUS >1
)R
LATERAL VIEW EXPLODE(SPLIT(SEQ, ',')) SEQUENCE AS SEQUENCE
