
CREATE TABLE IF NOT EXISTS MON.FT_DAILY_STATUS(
    TABLE_TYPE STRING,
    TABLE_SOURCE STRING,
    TABLE_NAME STRING,
    DEPENDANCES STRING,
    STATUT STRING,
    NB_ROWS INT,
    LAST_INCIDENT_DAY TIMESTAMP,
    TABLE_INSERT_DATE TIMESTAMP,
    INSERT_DATE TIMESTAMP
)
PARTITIONED BY (TABLE_DATE DATE)
STORED AS ORC
TBLPROPERTIES ('transactional'='true',"orc.compress"="ZLIB","orc.stripe.size"="67108864")
