
CREATE TABLE IF NOT EXISTS MON.SPARK_MISSING_FILES(
    TABLE_SOURCE STRING,
    FLUX_TYPE STRING,
    FLUX_NAME STRING,
    FILE_NAME STRING,
    INSERT_DATE TIMESTAMP
)

PARTITIONED BY (ORIGINAL_FILE_DATE DATE)
STORED AS PARQUET TBLPROPERTIES ('PARQUET.COMPRESS'='SNAPPY');
