
CREATE TABLE  MON.SPARK_MISSING_OM_FILES(
    TABLE_SOURCE STRING,
    FLUX_TYPE STRING,
    RAWDIR STRING,
    HDDFS_SUBDIR STRING,
    NB_HEADER_MOVE INT,
    CSV_SEPARAROR STRING,
    FLUX_NAME STRING,
    FILE_NAME STRING,
    INSERT_DATE TIMESTAMP
)

PARTITIONED BY (ORIGINAL_FILE_DATE DATE)
STORED AS PARQUET TBLPROPERTIES ('PARQUET.COMPRESS'='SNAPPY');
