CREATE TABLE IF NOT EXISTS MON.SPARK_GLOBAL_ACTIVITY_DAILY_STATUS(
    SOURCE_DATA STRING,
    TAXED_AMOUNT BIGINT,
    INSERT_DATE TIMESTAMP
)
PARTITIONED BY (TRANSACTION_DATE DATE)
STORED AS PARQUET TBLPROPERTIES ('PARQUET.COMPRESS'='SNAPPY')
