
CREATE TABLE IF NOT EXISTS MISSING_FILES(
    ORIGINAL_FILE_DATE STRING,
    TABLE_SOURCE STRING,
    FLUX_TYPE STRING,
    FLUX_NAME STRING,
    FILE_NAME STRING,
    INSERT_DATE TIMESTAMP
)
STORED AS ORC
TBLPROPERTIES('TRANSACTIONAL'='TRUE')
;
