
CREATE TABLE IF NOT EXISTS FT_DAILY_STATUS(
    TABLE_DATE STRING,
    TABLE_TYPE STRING,
    TABLE_SOURCE STRING,
    TABLE_NAME STRING,
    DEPENDANCES STRING,
    STATUT STRING,
    NB_ROWS INT,
    LAST_INCIDENT_DAY TIMESTAMP,
    TABLE_INSERT_DATE TIMESTAMP,
    INSERT_DATE TIMESTAMP
)
STORED AS ORC
TBLPROPERTIES('transactional'='true')
;
