CREATE TABLE MON.SPARK_14_FT_DAILY_STATUS
(
table_name STRING,
jour14 STRING,
jour13  STRING,
jour12 STRING,
jour11 STRING,
jour10 STRING,
jour09 STRING,
jour08 STRING,
jour07 STRING,
jour06 STRING,
jour05 STRING,
jour04 STRING,
jour03 STRING,
jour02 STRING,
jour01 STRING,
INSERT_DATE TIMESTAMP

)
COMMENT ''SPARK_14_FT_DAILY_STATUS - FT_A''
PARTITIONED BY (EVENT_DATE    DATE)
STORED AS PARQUET TBLPROPERTIES (''PARQUET.COMPRESS''=''SNAPPY'');