
CREATE TABLE IF NOT EXISTS FT_DAILY_STATUS2(
    TABLE_DATE STRING,
    TABLE_TYPE STRING,
    TABLE_SOURCE STRING,
    TABLE_NAME STRING,
    DEPENDANCES STRING,
    STATUT STRING,
    NB_ROWS INT,
    LAST_INCIDENT_DAY TIMESTAMP,
    TABLE_INSERT_DATE TIMESTAMP,
    INSERT_DATE TIMESTAMP
)
CLUSTERED BY(TABLE_TYPE) INTO 20 BUCKETS
STORED AS ORC
TBLPROPERTIES ('transactional'='true',"orc.compress"="ZLIB","orc.stripe.size"="67108864")
