INSERT INTO TMP.TT_SITE_360_1
SELECT
    MSISDN,
    CI
FROM
(
    SELECT
        MSISDN,
        MAX(SITE_NAME) SITE_NAME
    FROM MON.SPARK_FT_CLIENT_LAST_SITE_DAY
    WHERE EVENT_DATE = '###SLICE_VALUE###'
    GROUP BY MSISDN
) A
LEFT JOIN
(
    SELECT
        MAX(CI) CI,
        SITE_NAME
    FROM DIM.DT_GSM_CELL_CODE
    GROUP BY SITE_NAME
) B ON A.SITE_NAME = B.SITE_NAME