CREATE TABLE MON.SPARK_FT_CLIENT_CELL_TRAFFIC_HOUR
(
    MSISDN VARCHAR(100),
    HOUR_PERIOD VARCHAR(2),
    LAST_CI VARCHAR(5),
    LAST_LAC VARCHAR(5),
    LAST_TRANSACTION_TIME VARCHAR(8),
    LAST_TRANSACTION_TYPE VARCHAR(5),
    insert_date timestamp
)
PARTITIONED BY (EVENT_DATE DATE)
STORED AS PARQUET
TBLPROPERTIES ('PARQUET.COMPRESS'='SNAPPY')