SELECT IF(A.FT_EXIST = 0 and B.FT_COUNT>0 and (C.FT_COUNT_PREV>0 or substring('###SLICE_VALUE###',1,7)<>substring(date_sub('###SLICE_VALUE###',1),1,7)) and D.FT_COUNT>0 and E.FT_COUNT>0, "OK","NOK") FROM
(SELECT COUNT(*) FT_EXIST FROM MON.SPARK_FT_MSISDN_SUMMARY_DATA WHERE EVENT_DATE='###SLICE_VALUE###') A,
(SELECT COUNT(*) FT_COUNT FROM MON.SPARK_FT_MSISDN_TRAFIC_DATA_SITE WHERE EVENT_DATE='###SLICE_VALUE###') B,
(SELECT COUNT(*) FT_COUNT_PREV FROM MON.SPARK_FT_MSISDN_SUMMARY_DATA WHERE EVENT_DATE=date_sub('###SLICE_VALUE###',1)) C,
(SELECT COUNT(*) FT_COUNT FROM MON.SPARK_ft_contract_snapshot WHERE EVENT_DATE=DATE_ADD('###SLICE_VALUE###',1)) D,
(SELECT COUNT(*) FT_COUNT FROM MON.SPARK_FT_OTARIE_DATA_TRAFFIC_DAY WHERE TRANSACTION_DATE='###SLICE_VALUE###') E
