insert into TMP.TT_BDI_LIGNE_FLOTTE2
select
g.MSISDN  MSISDN,
h.CUSTOMER_ID  CUSTOMER_ID,
h.CONTRACT_ID  CONTRACT_ID,
h.COMPTE_CLIENT  COMPTE_CLIENT,
'M2M'  TYPE_PERSONNE,
h.TYPE_PIECE,
h.NUMERO_PIECE,
h.ID_TYPE_PIECE,
h.NOM_PRENOM,
h.NOM,
h.PRENOM,
h.DATE_NAISSANCE,
h.DATE_EXPIRATION,
h.ADRESSE,
'DOUALA'  VILLE,
'AKWA'  QUARTIER,
h.DATE_SOUSCRIPTION  DATE_SOUSCRIPTION,
h.DATE_ACTIVATION  DATE_ACTIVATION,
h.STATUT  STATUT,
h.RAISON_STATUT  RAISON_STATUT,
h.DATE_CHANGEMENT_STATUT  DATE_CHANGEMENT_STATUT,
null  PLAN_LOCALISATION,
null  CONTRAT_SOUCRIPTION,
null  DISPONIBILITE_SCAN,
null  ACCEPTATION_CGV,
null  TYPE_PIECE_TUTEUR,
null  NUMERO_PIECE_TUTEUR,
null  NOM_TUTEUR,
null  PRENOM_TUTEUR,
null  DATE_NAISSANCE_TUTEUR,
null  DATE_EXPIRATION_TUTEUR,
null  ADRESSE_TUTEUR,
'4.4335'  COMPTE_CLIENT_STRUCTURE,
'FORIS TELECOM'  NOM_STRUCTURE,
'RC/DLA/2008/B/782' NUMERO_REGISTRE_COMMERCE,
'110046646' NUMERO_PIECE_REPRESENTANT_LEGAL,
h.IMEI  IMEI,
null  STATUT_DEROGATION,
h.REGION_ADMINISTRATIVE  REGION_ADMINISTRATIVE,
h.REGION_COMMERCIALE  REGION_COMMERCIALE,
h.SITE_NAME  SITE_NAME,
h.VILLE_SITE  VILLE_SITE,
h.OFFRE_COMMERCIALE  OFFRE_COMMERCIALE,
h.TYPE_CONTRAT  TYPE_CONTRAT,
h.SEGMENTATION  SEGMENTATION,
h.odbIncomingCalls  odbIncomingCalls,
h.odbOutgoingCalls  odbOutgoingCalls,
null  DEROGATION_IDENTIFICATION,
current_timestamp() AS insert_date,
'###SLICE_VALUE###' AS original_file_date
from (
select e.*
from (
select MSISDN,NUMERO_PIECE
from TMP.TT_BDI3_1
where NUMERO_PIECE in  ( select NUMERO_PIECE from (
SELECT NUMERO_PIECE, COUNT(*) AS NB
FROM TMP.TT_BDI3_1
WHERE (odbIncomingCalls = '0' ANd odbOutgoingCalls = '0') AND
NUMERO_PIECE NOT LIKE "1122334455%" GROUP BY NUMERO_PIECE HAVING NB > 3
) a
)
) e
left join
(
select msisdn, numero_piece
from (
select msisdn, numero_piece,
row_number() over( partition by numero_piece order by msisdn ) AS RANG from (
select MSISDN,NUMERO_PIECE
from TMP.TT_BDI3_1
where NUMERO_PIECE in 
    ( select DISTINCT NUMERO_PIECE from (
    SELECT NUMERO_PIECE, COUNT(*) AS NB 
    FROM TMP.TT_BDI3_1
    WHERE (odbIncomingCalls = '0' ANd odbOutgoingCalls = '0') AND
    NUMERO_PIECE NOT LIKE "1122334455%" GROUP BY NUMERO_PIECE HAVING COUNT(*) > 3
    ) a )  
) c
) d
where RANG <= 3
) f
on FN_FORMAT_MSISDN_TO_9DIGITS(trim(e.msisdn)) = FN_FORMAT_MSISDN_TO_9DIGITS(trim(f.msisdn))
where f.msisdn is null
) g
join  TMP.TT_BDI3_1 h
on FN_FORMAT_MSISDN_TO_9DIGITS(trim(g.msisdn)) = FN_FORMAT_MSISDN_TO_9DIGITS(trim(h.msisdn))