SELECT IF(T_1.FT_A_RAS_TRAFIC_D = 0 and T_2.FT_MSC_CMR_BAD_CALL > 1,"OK","NOK") FT_EXIST
FROM
    (SELECT COUNT(*) FT_A_RAS_TRAFIC_D FROM AGG.SPARK_FT_A_RAS_TRAFIC_D WHERE EVENT_DATE='###SLICE_VALUE###') T_1,
    (SELECT COUNT(*) FT_MSC_CMR_BAD_CALL FROM MON.SPARK_FT_MSC_CMR_BAD_CALL WHERE TRANSACTION_DATE='###SLICE_VALUE###') T_2