SELECT IF(A.FT_EXIST = 0 and B.FT_COUNT>0 and C.FT_COUNT>0 , "OK","NOK") FROM
(SELECT COUNT(*) FT_EXIST FROM MON.SPARK_FT_SUBSCRIPTION_MSISDN_MONTH WHERE EVENT_MONTH='###SLICE_VALUE###') A,
(SELECT COUNT(*) FT_COUNT FROM MON.SPARK_FT_SUBSCRIPTION_MSISDN_DAY WHERE EVENT_DATE BETWEEN TO_DATE ('###SLICE_VALUE###' || '-01') AND DATE_SUB(ADD_MONTHS (TO_DATE ('###SLICE_VALUE###' || '-01'), 1), 1) AND SRC_TABLE ='IT_CRA_ICC_TRADUIT') B,
(SELECT COUNT(*) FT_COUNT FROM MON.SPARK_FT_CONTRACT_SNAPSHOT WHERE EVENT_DATE=ADD_MONTHS (TO_DATE ('###SLICE_VALUE###' || '-01'), 1)) C
