SELECT IF(T_1.FT_B2B_EXIST > 0 AND T_2.NB_EXPORT < 1 ,"OK","NOK") FT_SUBS_EXIST_B2B
FROM
(SELECT COUNT(*) FT_B2B_EXIST FROM MON.SPARK_DEPOT_CLIENT_B2B WHERE EVENT_DATE = concat('###SLICE_VALUE###','-','01')) T_1,
(
    SELECT COUNT(*) NB_EXPORT FROM
    (SELECT * FROM (SELECT * FROM MON.EXPORT_HISTORY WHERE EVENT_DATE='###SLICE_VALUE###' AND JOB_INSTANCEID='${hivevar:job_instanceid}' ORDER BY INSERT_DATE DESC LIMIT 1)  T where T.STATUS = 'OK') M
) T_2

