INSERT INTO TMP.SPARK_IT_ZTE_PROFILE
SELECT 
    PROFILE_ID, 
    MAX(UPPER(PROFILE_NAME)) PROFILE_NAME,
    CURRENT_TIMESTAMP INSERT_DATE,
    '###SLICE_VALUE###' EVENT_DATE
FROM CDR.SPARK_IT_ZTE_PROFILE 
GROUP BY PROFILE_ID