SELECT IF(T_1.IT_EXIST = 0 and T_2.IT_PROFILE_EXIST>0,"OK","NOK") PROFILE_EXIST
FROM
(SELECT COUNT(*) IT_EXIST FROM TMP.SPARK_IT_ZTE_PROFILE WHERE EVENT_DATE='###SLICE_VALUE###') T_1,
(SELECT COUNT(*) IT_PROFILE_EXIST FROM CDR.SPARK_IT_ZTE_PROFILE WHERE ORIGINAL_FILE_DATE='###SLICE_VALUE###') T_2
