CREATE TABLE AGG.SPARK_FT_A_REVENU_SITE_AMN
(
  SITE_NAME           VARCHAR(100),
  TYPE                VARCHAR(30),
  DESTINATION         VARCHAR(13),
  NB_APPELS           BIGINT,
  VOLUME_TOTAL        DECIMAL(17,2),
  REVENU_MAIN_KFCFA   DECIMAL(17,2),
  REVENU_PROMO_KFCFA DECIMAL(17,2),
  INSERT_DATE         TIMESTAMP,
  CONTRACT_TYPE       VARCHAR(20)
)
PARTITIONED BY (EVENT_DATE    DATE)
STORED AS PARQUET TBLPROPERTIES ('PARQUET.COMPRESS'='SNAPPY') 