CREATE TABLE MON.SPARK_FT_CONSO_SIMBOX(
   MSISDN VARCHAR(20),
   CONSO_MONTH VARCHAR(10),
   CONSO double,
   TEL_DURATION bigint,
   TEL_COUNT int,
   PLATFORM VARCHAR(20 ),
   PROFILE VARCHAR(30 ),
   MTN_DURATION int,
   CAMTEL_DURATION int,
   INTERNATIONAL_DURATION int,
   INSERTED_DATE TIMESTAMP
   )COMMENT ' SPARK_FT_CONSO_SIMBOX '
 PARTITIONED BY (DETECT_MONTH VARCHAR(10))
 STORED AS PARQUET
 TBLPROPERTIES ("parquet.compress"="SNAPPY")