SELECT IF(A.FT_DATA_CONSO_MSISDN_MONTH_hold = 0 AND B.FT_CONTRACT_SNAPSHOT_01>0 and C.FT_DATA_CONSO_MSISDN_DAY_hold > datediff(last_day(concat('###SLICE_VALUE###','-01')), concat('###SLICE_VALUE###','-01')) ,"OK","NOK") FROM
(SELECT COUNT(*) FT_DATA_CONSO_MSISDN_MONTH_hold FROM MON.SPARK_FT_DATA_CONSO_MSISDN_MONTH WHERE EVENT_MONTH= '###SLICE_VALUE###') A,
(SELECT COUNT(*) FT_CONTRACT_SNAPSHOT_01 FROM MON.SPARK_FT_CONTRACT_SNAPSHOT WHERE EVENT_DATE = ADD_MONTHS(CONCAT('###SLICE_VALUE###', '-01'), 1)) B,
(SELECT COUNT(DISTINCT EVENT_DATE) FT_DATA_CONSO_MSISDN_DAY_hold FROM MON.SPARK_FT_DATA_CONSO_MSISDN_DAY WHERE EVENT_DATE BETWEEN to_date(concat('###SLICE_VALUE###','-01')) AND last_day(concat('###SLICE_VALUE###','-01'))) C
