CREATE TABLE MON.SPARK_FT_ACCOUNT_OM_INACTIF_30J(

  MSISDN VARCHAR(50 )

  )COMMENT ' SPARK_FT_INACTIF_OM '
 PARTITIONED BY (EVENT_DATE DATE)
 STORED AS PARQUET
 TBLPROPERTIES ("parquet.compress"="SNAPPY")