CREATE TABLE MON.SPARK_FT_ACCOUNT_OM_INACTIF_DAILY(

  MSISDN VARCHAR(100)

  )COMMENT ' SPARK_FT_INACTIF_OM '
 PARTITIONED BY (EVENT_DATE DATE)
 STORED AS PARQUET
 TBLPROPERTIES ("parquet.compress"="SNAPPY")