SELECT IF(T_1.FT_EXIST = 0 and T_2.IT_OMNY_TRANSACTIONS_EXIST>0 AND T_3.FT_EXIST_1 >0,"OK","NOK")
FROM
(SELECT COUNT(*) FT_EXIST FROM MON.SPARK_FT_ACCOUNT_OM_INACTIF_DAILY WHERE EVENT_DATE='###SLICE_VALUE###') T_1,
(SELECT COUNT(*) IT_OMNY_TRANSACTIONS_EXIST FROM CDR.SPARK_IT_OMNY_TRANSACTIONS WHERE TRANSFER_DATETIME='###SLICE_VALUE###') T_2,
(SELECT COUNT(*) FT_EXIST_1 FROM MON.SPARK_FT_OMNY_ACCOUNT_SNAPSHOT_NEW WHERE EVENT_DATE=date_sub('###SLICE_VALUE###',1)) T_3