-- Insertion des Users uniques  Voix et SMS
INSERT INTO AGG.SPARK_FT_GLOBAL_ACTIVITY_DAILY_MKT
SELECT
    (CASE
        WHEN DESTINATION='ONNET' AND SERVICE='NVX_SMS' THEN 'USER_SMS_ONNET'
        WHEN DESTINATION='BUNDLE' AND SERVICE='NVX_SMS' THEN 'USER_SMS_BUNDLE'
        WHEN DESTINATION='MTN' AND SERVICE='NVX_SMS' THEN 'USER_SMS_MTN'
        WHEN DESTINATION='NEXTTEL' AND SERVICE='NVX_SMS' THEN 'USER_SMS_NEXTTEL'
        WHEN DESTINATION='CAMTEL' AND SERVICE='NVX_SMS' THEN 'USER_SMS_CAMTEL'
        WHEN DESTINATION='INTERNATIONAL' AND SERVICE='NVX_SMS' THEN 'USER_SMS_INTERNATIONAL'
        WHEN DESTINATION='ROAM' AND SERVICE='NVX_SMS' THEN 'USER_SMS_ROAM'
        WHEN DESTINATION='INROAM' AND SERVICE='NVX_SMS' THEN 'USER_SMS_INROAM'
        WHEN DESTINATION='ONNET' AND SERVICE='VOI_VOX' THEN 'USER_VOICE_ONNET'
        WHEN DESTINATION='BUNDLE' AND SERVICE='VOI_VOX' THEN 'USER_VOICE_BUNDLE'
        WHEN DESTINATION='MTN' AND SERVICE='VOI_VOX' THEN 'USER_VOICE_MTN'
        WHEN DESTINATION='NEXTTEL' AND SERVICE='VOI_VOX' THEN 'USER_VOICE_NEXTTEL'
        WHEN DESTINATION='CAMTEL' AND SERVICE='VOI_VOX' THEN 'USER_VOICE_CAMTEL'
        WHEN DESTINATION='INTERNATIONAL' AND SERVICE='VOI_VOX' THEN 'USER_VOICE_INTERNATIONAL'
        WHEN DESTINATION='ROAM' AND SERVICE='VOI_VOX' THEN 'USER_VOICE_ROAM'
        WHEN DESTINATION='INROAM' AND SERVICE='VOI_VOX' THEN 'USER_VOICE_INROAM'
    END) DESTINATION_CODE,
    FORMULE PROFILE_CODE,
    'UNKNOWN' SUB_ACCOUNT,
    'HIT' MEASUREMENT_UNIT,
    'FT_USERS_DAY' SOURCE_TABLE,
     OPERATOR_CODE,
    SUM(USERS_COUNT) TOTAL_AMOUNT,
    SUM(USERS_COUNT) RATED_AMOUNT,
    CURRENT_TIMESTAMP INSERT_DATE ,
    NULL REGION_ID,
    EVENT_DATE TRANSACTION_DATE
FROM
(
    SELECT
        ud.EVENT_DATE,
        ud.FORMULE,
        TRIM(ud.SERVICE) SERVICE,
        TRIM(d.DESTINATION) DESTINATION,
        OPERATOR_CODE,
        (CASE
            WHEN d.DESTINATION='ONNET' THEN ud.ONNET
            WHEN d.DESTINATION='BUNDLE' THEN ud.BUNDLE
            WHEN d.DESTINATION='MTN' THEN ud.MTN
            WHEN d.DESTINATION='NEXTTEL' THEN ud.NEXTTEL
            WHEN d.DESTINATION='CAMTEL' THEN ud.CAMTEL
            WHEN d.DESTINATION='INTERNATIONAL' THEN ud.INTERNATIONAL
            WHEN d.DESTINATION='ROAM' THEN ud.ROAM
            WHEN d.DESTINATION='SET' THEN ud.`SET`
            WHEN d.DESTINATION='INROAM' THEN ud.INROAM
        END) USERS_COUNT
    FROM MON.SPARK_FT_USERS_DAY ud
    CROSS JOIN
    (
        SELECT 'ONNET' DESTINATION  UNION ALL
        SELECT 'BUNDLE' DESTINATION  UNION ALL
        SELECT 'MTN' DESTINATION UNION ALL
        SELECT 'NEXTTEL' DESTINATION UNION ALL
        SELECT 'CAMTEL' DESTINATION UNION ALL
        SELECT 'INTERNATIONAL' DESTINATION UNION ALL
        SELECT 'ROAM' DESTINATION UNION ALL
        SELECT 'SET' DESTINATION UNION ALL
        SELECT 'INROAM' DESTINATION
    ) d
    WHERE EVENT_DATE ='###SLICE_VALUE###'
        AND TRIM(SERVICE) <> 'ALL'
)T
WHERE DESTINATION <> 'SET'
GROUP BY
    EVENT_DATE,
    OPERATOR_CODE,
    (CASE
        WHEN DESTINATION='ONNET' AND SERVICE='NVX_SMS' THEN 'USER_SMS_ONNET'
        WHEN DESTINATION='BUNDLE' AND SERVICE='NVX_SMS' THEN 'USER_SMS_BUNDLE'
        WHEN DESTINATION='MTN' AND SERVICE='NVX_SMS' THEN 'USER_SMS_MTN'
        WHEN DESTINATION='NEXTTEL' AND SERVICE='NVX_SMS' THEN 'USER_SMS_NEXTTEL'
        WHEN DESTINATION='CAMTEL' AND SERVICE='NVX_SMS' THEN 'USER_SMS_CAMTEL'
        WHEN DESTINATION='INTERNATIONAL' AND SERVICE='NVX_SMS' THEN 'USER_SMS_INTERNATIONAL'
        WHEN DESTINATION='ROAM' AND SERVICE='NVX_SMS' THEN 'USER_SMS_ROAM'
        WHEN DESTINATION='INROAM' AND SERVICE='NVX_SMS' THEN 'USER_SMS_INROAM'
        WHEN DESTINATION='ONNET' AND SERVICE='VOI_VOX' THEN 'USER_VOICE_ONNET'
        WHEN DESTINATION='BUNDLE' AND SERVICE='VOI_VOX' THEN 'USER_VOICE_BUNDLE'
        WHEN DESTINATION='MTN' AND SERVICE='VOI_VOX' THEN 'USER_VOICE_MTN'
        WHEN DESTINATION='NEXTTEL' AND SERVICE='VOI_VOX' THEN 'USER_VOICE_NEXTTEL'
        WHEN DESTINATION='CAMTEL' AND SERVICE='VOI_VOX' THEN 'USER_VOICE_CAMTEL'
        WHEN DESTINATION='INTERNATIONAL' AND SERVICE='VOI_VOX' THEN 'USER_VOICE_INTERNATIONAL'
        WHEN DESTINATION='ROAM' AND SERVICE='VOI_VOX' THEN 'USER_VOICE_ROAM'
        WHEN DESTINATION='INROAM' AND SERVICE='VOI_VOX' THEN 'USER_VOICE_INROAM'
    END) ,
    FORMULE

UNION ALL

-- Insertion des Users uniques  DATA
SELECT
    DESTINATION_CODE,
    PROFILE_CODE,
    'UNKNOWN' SUB_ACCOUNT,
    'UNKNOWN' MEASUREMENT_UNIT,
    'FT_USERS_DATA_DAY' SOURCE_TABLE,
     OPERATOR_CODE,
    SUM(TOTAL_AMOUNT) TOTAL_AMOUNT,
    SUM(RATED_AMOUNT) RATED_AMOUNT,
    CURRENT_TIMESTAMP INSERT_DATE,
    NULL AS REGION_ID,
    EVENT_DATE TRANSACTION_DATE

FROM
(
    SELECT
        EVENT_DATE,
        CASE
            WHEN SERVICE_DATA = '2G_PAYGO' THEN 'USER_2G_PAYGO'
            WHEN SERVICE_DATA = '2G_BUNDLE' THEN 'USER_2G_BUNDLE'
        END DESTINATION_CODE,
        COMMERCIAL_OFFER PROFILE_CODE,
         OPERATOR_CODE,
        CASE
            WHEN SERVICE_DATA = '2G_PAYGO' THEN OUT_BUNDLE_COUNT
            WHEN SERVICE_DATA = '2G_BUNDLE' THEN IN_BUNDLE_COUNT
        END TOTAL_AMOUNT,
        CASE
            WHEN SERVICE_DATA = '2G_PAYGO' THEN OUT_BUNDLE_COUNT
            WHEN SERVICE_DATA = '2G_BUNDLE' THEN IN_BUNDLE_COUNT
        END RATED_AMOUNT,
        CURRENT_TIMESTAMP INSERT_DATE
    FROM
    (
        SELECT '2G_PAYGO' SERVICE_DATA  UNION
        SELECT '2G_BUNDLE' SERVICE_DATA
    ) a
    CROSS JOIN MON.SPARK_FT_USERS_DATA_DAY b
    WHERE EVENT_DATE ='###SLICE_VALUE###'
)T
GROUP BY EVENT_DATE, DESTINATION_CODE, PROFILE_CODE, OPERATOR_CODE