INSERT INTO AGG.SPARK_FT_A_CREDIT_TRANSFER_SENDER

SELECT

SENDER_MSISDN,
COMMERCIAL_OFFER,
count(*) TRANSFER_COUNT,
sum(TRANSFER_AMT) TRANSFER_AMOUNT,
sum(TRANSFER_FEES) TRANSFER_FEES,
current_timestamp LAST_UPDATE,
SENDER_OPERATOR_CODE OPERATOR_CODE,
(CASE WHEN UPPER(ORIGINAL_FILE_NAME) LIKE '%VIP%' THEN 1 ELSE 0 END) IS_VIP,
CURRENT_TIMESTAMP INSERT_DATE,
REFILL_DATE


from MON.SPARK_FT_CREDIT_TRANSFER
WHERE REFILL_DATE ='###SLICE_VALUE###' and termination_ind='000'
group by refill_date, sender_msisdn, TERMINATION_IND, commercial_offer, SENDER_OPERATOR_CODE
,(CASE WHEN UPPER(ORIGINAL_FILE_NAME) LIKE '%VIP%' THEN 1 ELSE 0 END)
order by refill_date




