SELECT
    DATE_FORMAT(EVENT_DATE,'yyyyMM') EVENT_MONTH,
    ADMINISTRATIVE_REGION,
    trim(TOWNNAME) ,
    (CASE WHEN trim(SITE_NAME) LIKE '%ACROPOLE-IHS' THEN 'ACROPOLE-IHS'
    WHEN trim(SITE_NAME) = 'NGD-TROUA MALA II' THEN 'NGD-TROUA-MALA-II'
    WHEN trim(SITE_NAME) = 'SANTA-BARBRA-YDE-IHS' THEN 'SANTA-BARBARA-YDE-IHS'
    WHEN trim(SITE_NAME) = 'SKY-WAY-HOTEL_IHS' THEN 'SKY-WAY-HOTEL-IHS'
    WHEN trim(SITE_NAME) = 'SODIKO-GARE-ROUTI¿RE' THEN 'SODIKO-GARE-ROUTIÃ'
    WHEN trim(SITE_NAME) = 'SODIKO-GARE-ROUTI?RE' THEN 'SODIKO-GARE-ROUTIÃ'
    WHEN trim(SITE_NAME) = 'TAM-TAM WEEK-END-IHS' THEN 'TAMTAM-WEEKEND-IHS'
    WHEN trim(SITE_NAME) = 'TAM-TAM WEEK-END-IHS' THEN 'TAMTAM-WEEKEND-IHS'
    WHEN trim(SITE_NAME) = 'MAK¿P¿' THEN 'MAKEPE'
    ELSE trim(SITE_NAME) END) ,
    sum(DUREE_ENTRANT) ,
    sum(NBRE_TEL_ENTRANT) ,
    sum(NBRE_SMS_ENTRANT),
    sum(TOTAL_NBRE_ENTRANT),
    sum(DUREE_SORTANT),
    sum(NBRE_TEL_SORTANT) ,
    sum(NBRE_SMS_SORTANT) ,
    sum(TOTAL_NBRE_SORTANT)

FROM MON.SPARK_FT_SITE_TRAFFIC_USAGE_DAILY
WHERE EVENT_DATE BETWEEN DATE_ADD(ADD_MONTHS('###SLICE_VALUE###', -1 ),1) AND  Last_day('###SLICE_VALUE###')

GROUP BY
DATE_FORMAT(EVENT_DATE,'yyyyMM'),
ADMINISTRATIVE_REGION,
trim(TOWNNAME),
(CASE WHEN trim(SITE_NAME) LIKE '%ACROPOLE-IHS' THEN 'ACROPOLE-IHS'
WHEN trim(SITE_NAME) = 'NGD-TROUA MALA II' THEN 'NGD-TROUA-MALA-II'
WHEN trim(SITE_NAME) = 'SANTA-BARBRA-YDE-IHS' THEN 'SANTA-BARBARA-YDE-IHS'
WHEN trim(SITE_NAME) = 'SKY-WAY-HOTEL_IHS' THEN 'SKY-WAY-HOTEL-IHS'
WHEN trim(SITE_NAME) = 'SODIKO-GARE-ROUTI¿RE' THEN 'SODIKO-GARE-ROUTIÃ'
WHEN trim(SITE_NAME) = 'SODIKO-GARE-ROUTI?RE' THEN 'SODIKO-GARE-ROUTIÃ'
WHEN trim(SITE_NAME) = 'TAM-TAM WEEK-END-IHS' THEN 'TAMTAM-WEEKEND-IHS'
WHEN trim(SITE_NAME) = 'TAM-TAM WEEK-END-IHS' THEN 'TAMTAM-WEEKEND-IHS'
WHEN trim(SITE_NAME) = 'MAK¿P¿' THEN 'MAKEPE'
ELSE trim(SITE_NAME) END)