SELECT IF( T_1.FT_EXIST > 0 AND
T2.FT_EXIST > 0 AND
--T3.FT_EXIST > 0 AND 
T_2.NB_EXPORT < 1 ,"OK","NOK")
FROM
(SELECT COUNT(*) FT_EXIST FROM CDR.SPARK_IT_OM_SUBSCRIBERS WHERE to_date(REGISTERED_ON) = '###SLICE_VALUE###') T_1,
(SELECT COUNT(*) FT_EXIST FROM MON.SPARK_FT_ALIGNEMENT_TANGO_TELCO WHERE event_date = date_sub('###SLICE_VALUE###', 1)) T2,
--Table décommissionnée
--(SELECT COUNT(*) FT_EXIST FROM CDR.SPARK_IT_NOMAD_CLIENT_DIRECTORY_30J WHERE original_file_date = '###SLICE_VALUE###') T3,
(select count(*) NB_EXPORT from (select * from (SELECT * FROM MON.EXPORT_HISTORY where event_date='###SLICE_VALUE###' and JOB_INSTANCEID='${hivevar:job_instanceid}' ORDER BY INSERT_DATE DESC LIMIT 1)  T where T.STATUS = 'OK') M) T_2