
INSERT INTO AGG.SPARK_FT_ROAMING_CEMAC

    SELECT 
    CLIENT_OPERATOR,
    DIRECTION,
    ROAMING_PARTNER_NAME,
    ROAMING_PARTNER_COUNTRY,
    SERVICE_FAMILY,
    NUMBER_OF_CALLS,
    IF(MINUTES-10 <= 0, 0,round(MINUTES-10)) MINUTES,
    IMSI,
    CALL_DATE
    FROM MON.SPARK_FT_ROAMING_CEMAC_IN_OUT WHERE CALL_DATE = '###SLICE_VALUE###'
