SELECT
EVENT_DATE,
ACCESS_KEY,
OSP_STATUS,
ACTIVATION_DATE,
DEACTIVATION_DATE,
PROFILE,
LANG,
MAIN_CREDIT,
PROMO_CREDIT,
OSP_CONTRACT_TYPE,
CURRENT_STATUS_1,
administrative_region,
DATE_FORMAT(STATE_DATETIME, 'yyyy-MM-dd HH:mm:ss') STATE_DATETIME
FROM MON.SPARK_FT_CONTRACT_SNAPSHOT A
left join 
(select msisdn, administrative_region from MON.SPARK_FT_CLIENT_LAST_SITE_DAY where event_date='###SLICE_VALUE###') B 
on A.ACCESS_KEY= B.msisdn
WHERE EVENT_DATE='###SLICE_VALUE###'