SELECT
EVENT_DATE,
ACCESS_KEY,
OSP_STATUS,
ACTIVATION_DATE,
DEACTIVATION_DATE,
PROFILE,
LANG,
MAIN_CREDIT,
PROMO_CREDIT,
OSP_CONTRACT_TYPE,
CURRENT_STATUS_1,
DATE_FORMAT(STATE_DATETIME, 'yyyy-MM-dd HH:mm:ss') STATE_DATETIME
FROM MON.SPARK_FT_CONTRACT_SNAPSHOT
WHERE EVENT_DATE=(select MAX( EVENT_DATE) from MON.SPARK_FT_CONTRACT_SNAPSHOT)