SELECT  TRANSACTION_DATE,MSISDN,APPLI_TYPE,IDAPN,NBYTESDN,NBYTEST,NBYTESUP,RADIO_ACCESS_TECHNO,ROAMING,TERMINAL_BRAND,TERMINAL_MODEL,TERMINAL_TYPE
FROM MON.SPARK_FT_OTARIE_DATA_TRAFFIC_DAY
WHERE TRANSACTION_DATE = "###SLICE_VALUE###"