SELECT
    MSISDN
    ,IMSI
FROM
(
    SELECT
        ACCNBR AS MSISDN,
        FIRST_VALUE(IMSI) OVER (PARTITION BY ACCNBR ORDER BY UPDATE_DATE DESC) AS IMSI
    FROM CDR.SPARK_IT_CONT
    WHERE ORIGINAL_FILE_DATE ='###SLICE_VALUE###' AND UPPER(PROD_STATE) ='ACTIVE'
) T
WHERE IMSI IS NOT NULL