INSERT INTO MON.SPARK_FT_OMNY_ACCOUNT_SNAPSHOT_NEW
    SELECT
    trim(b.USER_ID) USER_ID,
    a.MSISDN ACCOUNT_NUMBER,
    b.MSISDN MSISDN,
    b.USER_FIRST_NAME,
    b.USER_LAST_NAME,
    b.REGISTERED_ON,
    NULL CITY,
    NULL ADDRESS,
    NULL SEX,
    b.ID_NUMBER,
    b.ACCOUNT_STATUS,
    NULL CREATED_BY,
    NULL FIRST_TRANSACTION_ON,
    a.USER_DOMAIN,
    a.USER_CATEGORY,
    NULL GEOGRAPHICAL_DOMAIN,
    a.USER_TYPE,
    NULL DELETED_ON,
    NULL DEACTIVATION_BY,
    NULL BILL_COMPANY_CODE,
    NULL COMPANY_TYPE,
    NULL NOTIFICATION_TYPE,
    NULL PROFILE_ID,
    NULL PARENT_USER_ID,
    b.CREATION_DATE,
    NULL MODIFIED_BY,
    b.MODIFIED_ON,
    b.BIRTH_DATE,
    b.ACCOUNT_BALANCE,
    b.PAYMENT_TYPE_ID,
    NULL CREATED_BY_MSISDN,
    current_timestamp INSERT_DATE,
    "###SLICE_VALUE###" EVENT_DATE
    FROM
    (
        SELECT DISTINCT
        USER_ID,MSISDN,
        REGISTERED_ON,
        ID_NUMBER,
        ACCOUNT_STATUS,
        CREATION_DATE,
        MODIFIED_ON,
        BIRTH_DATE,USER_FIRST_NAME,
        USER_LAST_NAME,
        ACCOUNT_BALANCE,PAYMENT_TYPE_ID
        FROM
        (
        SELECT
        trim(USER_ID) USER_ID,MSISDN,
        CREATED_ON REGISTERED_ON,
        EXTERNAL_CODE ID_NUMBER,
        IS_ACTIVE ACCOUNT_STATUS,
        CREATED_ON CREATION_DATE,
        MODIFIED_ON MODIFIED_ON,
        BIRTH_DATE BIRTH_DATE,
        USER_NAME USER_FIRST_NAME,
        LAST_NAME USER_LAST_NAME,
        BALANCE ACCOUNT_BALANCE,PAYMENT_TYPE_ID,
        ROW_NUMBER() OVER (PARTITION BY trim(USER_ID) ORDER BY MODIFIED_ON DESC)  AS RANG
        FROM CDR.SPARK_IT_OMNY_ACCOUNT_SNAPSHOT_NEW
        WHERE TO_DATE(ORIGINAL_FILE_DATE)= DATE_ADD("###SLICE_VALUE###",1)
        )m
        WHERE RANG=1
    ) b
    join
    (
        SELECT
        trim(ACCOUNT_NAME) USER_ID,
        ACCOUNT_ID MSISDN,
        USER_NAME USER_FIRST_NAME,
        LAST_NAME USER_LAST_NAME,
        USER_DOMAIN,
        USER_CATEGORY,
        ACCOUNT_TYPE USER_TYPE,
        BALANCE ACCOUNT_BALANCE
        FROM CDR.SPARK_IT_OM_ALL_BALANCE WHERE TO_DATE(ORIGINAL_FILE_DATE)="###SLICE_VALUE###"
    ) a
    ON trim(a.USER_ID)=trim(b.USER_ID)