SELECT IF(T.FT_EXIST = 0 and ACC_NBR_EXTRACT_EXIST>0 and PROD_EXTRACT_EXIST>0 and SUBS_EXTRACT_EXIST>0 and BASE_IDENTIFICATION_EXIST>0 ,"OK","NOK") TABLES_EXIST
FROM
(SELECT COUNT(*) FT_EXIST FROM MON.SPARK_FT_ACTIVATION_ALL_BY_CUMUL WHERE EVENT_DATE='###SLICE_VALUE###') T,
(SELECT COUNT(*) ACC_NBR_EXTRACT_EXIST FROM CDR.SPARK_IT_ZTE_ACC_NBR_EXTRACT WHERE ORIGINAL_FILE_DATE=DATE_ADD("###SLICE_VALUE###",1)) A,
(SELECT COUNT(*) PROD_EXTRACT_EXIST FROM CDR.SPARK_IT_ZTE_PROD_EXTRACT WHERE ORIGINAL_FILE_DATE=DATE_ADD("###SLICE_VALUE###",1)) B,
(SELECT COUNT(*) SUBS_EXTRACT_EXIST FROM CDR.SPARK_IT_ZTE_SUBS_EXTRACT WHERE ORIGINAL_FILE_DATE=DATE_ADD("###SLICE_VALUE###",1)) C,
(SELECT COUNT(*) BASE_IDENTIFICATION_EXIST FROM DIM.DT_BASE_IDENTIFICATION WHERE DATE_IDENTIFICATION=TO_DATE((substr("###SLICE_VALUE###",1,7)) || '-01')) D