INSERT INTO AGG.SPARK_FT_A_REPORTING_360
SELECT 
NVL(ADMINISTRATIVE_REGION, 'INCONNU') ADMINISTRATIVE_REGION,
NVL(COMMERCIAL_REGION, 'INCONNU') COMMERCIAL_REGION,
'REVENUE PER STREAM' KPI_GROUP_NAME,
KPI_NAME,
VALUE,
CURRENT_TIMESTAMP INSERT_DATE,
'###SLICE_VALUE###' PROCESSING_DATE  
FROM (
    -- 1. TOTAL VOICE 
    SELECT
        B.ADMINISTRATIVE_REGION ADMINISTRATIVE_REGION,
        B.COMMERCIAL_REGION COMMERCIAL_REGION,
        'TOTAL VOICE' KPI_NAME,
        SUM(RATED_AMOUNT) VALUE
    FROM AGG.SPARK_FT_GLOBAL_ACTIVITY_DAILY_MKT_DG A
    LEFT JOIN DIM.SPARK_DT_REGIONS_MKT_V2 B ON A.REGION_ID = B.REGION_ID
    WHERE TRANSACTION_DATE='###SLICE_VALUE###' AND 
        KPI='REVENUE' AND SUB_ACCOUNT='MAIN' AND 
        (SUBSTRING(DESTINATION_CODE,1,13)='REVENUE_VOICE' OR SOURCE_TABLE IN('FT_SUBS_RETAIL_ZEBRA','FT_CREDIT_TRANSFER','FT_CONTRACT_SNAPSHOT') OR DESTINATION_CODE IN ('UNKNOWN_BUN'))
    GROUP BY
        B.ADMINISTRATIVE_REGION,
        B.COMMERCIAL_REGION

    UNION ALL
    -- 2. VOICE PYG 
    SELECT 
        A.ADMINISTRATIVE_REGION ADMINISTRATIVE_REGION,
        A.COMMERCIAL_REGION COMMERCIAL_REGION,
        'VOICE PYG' KPI_NAME,
        SUM(RATED_AMOUNT) VALUE
    FROM
    (
        SELECT
            B.ADMINISTRATIVE_REGION ADMINISTRATIVE_REGION,
            B.COMMERCIAL_REGION COMMERCIAL_REGION,
            A.SERVICE_CODE SERVICE_CODE,
            A.RATED_AMOUNT RATED_AMOUNT
        FROM AGG.SPARK_FT_GLOBAL_ACTIVITY_DAILY_MKT_DG A
        LEFT JOIN DIM.SPARK_DT_REGIONS_MKT_V2 B ON A.REGION_ID = B.REGION_ID
        WHERE TRANSACTION_DATE='###SLICE_VALUE###' AND 
            KPI='REVENUE' AND 
            SUB_ACCOUNT='MAIN'
    ) A
    LEFT JOIN DIM.DT_USAGES B ON UPPER(A.SERVICE_CODE) = UPPER(B.USAGE_CODE)
    WHERE UPPER(B.USAGE_DESCRIPTION) = 'VOIX'
    GROUP BY
        A.ADMINISTRATIVE_REGION,
        A.COMMERCIAL_REGION

    UNION ALL
    -- 3. VOICE BUNDLES 
    SELECT
        B.ADMINISTRATIVE_REGION ADMINISTRATIVE_REGION,
        B.COMMERCIAL_REGION COMMERCIAL_REGION,
        'VOICE BUNDLES' KPI_NAME,
        SUM(RATED_AMOUNT) VALUE
    FROM AGG.SPARK_FT_GLOBAL_ACTIVITY_DAILY_MKT_DG A
    LEFT JOIN DIM.SPARK_DT_REGIONS_MKT_V2 B ON A.REGION_ID = B.REGION_ID
    WHERE TRANSACTION_DATE='###SLICE_VALUE###' AND 
        KPI='REVENUE' AND 
        SUB_ACCOUNT='MAIN' AND 
        DESTINATION_CODE='REVENUE_VOICE_BUNDLE'
    GROUP BY
        B.ADMINISTRATIVE_REGION,
        B.COMMERCIAL_REGION
    
    -- 4. VOICE COMBO NOK

    UNION ALL
    -- 5. TOTAL DATA 
    SELECT
        B.ADMINISTRATIVE_REGION ADMINISTRATIVE_REGION,
        B.COMMERCIAL_REGION COMMERCIAL_REGION,
        'TOTAL DATA' KPI_NAME,
        SUM(RATED_AMOUNT) VALUE
    FROM AGG.SPARK_FT_GLOBAL_ACTIVITY_DAILY_MKT_DG A
    LEFT JOIN DIM.SPARK_DT_REGIONS_MKT_V2 B ON A.REGION_ID = B.REGION_ID
    WHERE TRANSACTION_DATE='###SLICE_VALUE###' AND 
        KPI='REVENUE' AND 
        SUB_ACCOUNT='MAIN' AND 
        (DESTINATION_CODE='REVENUE_DATA_BUNDLE' OR DESTINATION_CODE='OM_DATA' OR (DESTINATION_CODE='REVENUE_DATA_PAYGO' AND SERVICE_CODE<>'NVX_GPRS_SVA') OR SOURCE_TABLE IN ('FT_EMERGENCY_DATA','FT_DATA_TRANSFER'))
    GROUP BY
        B.ADMINISTRATIVE_REGION,
        B.COMMERCIAL_REGION

    UNION ALL
    -- 6. DATA BUNDLES 
    SELECT
        B.ADMINISTRATIVE_REGION ADMINISTRATIVE_REGION,
        B.COMMERCIAL_REGION COMMERCIAL_REGION,
        'DATA BUNDLES' KPI_NAME,
        SUM(RATED_AMOUNT) VALUE
    FROM AGG.SPARK_FT_GLOBAL_ACTIVITY_DAILY_MKT_DG A
    LEFT JOIN DIM.SPARK_DT_REGIONS_MKT_V2 B ON A.REGION_ID = B.REGION_ID
    WHERE TRANSACTION_DATE='###SLICE_VALUE###' AND 
        KPI='REVENUE' AND SUB_ACCOUNT='MAIN' AND 
        DESTINATION_CODE='REVENUE_DATA_BUNDLE'
    GROUP BY
        B.ADMINISTRATIVE_REGION,
        B.COMMERCIAL_REGION

    UNION ALL
    -- 7. DATA COMBO 
    SELECT
        B.ADMINISTRATIVE_REGION ADMINISTRATIVE_REGION,
        B.COMMERCIAL_REGION COMMERCIAL_REGION,
        'DATA COMBO' KPI_NAME,
        SUM(RATED_AMOUNT) VALUE
    FROM AGG.SPARK_FT_GLOBAL_ACTIVITY_DAILY_MKT_DG A
    LEFT JOIN DIM.SPARK_DT_REGIONS_MKT_V2 B ON A.REGION_ID = B.REGION_ID
    WHERE TRANSACTION_DATE='###SLICE_VALUE###' AND 
        KPI='REVENUE_COMBO_DATA' AND SUB_ACCOUNT='MAIN' AND 
        DESTINATION_CODE='COMBO_DATA'
    GROUP BY
        B.ADMINISTRATIVE_REGION,
        B.COMMERCIAL_REGION

    UNION ALL
    -- 8. DATA ROAMING 
    SELECT
        B.ADMINISTRATIVE_REGION ADMINISTRATIVE_REGION,
        B.COMMERCIAL_REGION COMMERCIAL_REGION,
        'DATA ROAMING' KPI_NAME,
        SUM(RATED_AMOUNT) VALUE
    FROM AGG.SPARK_FT_GLOBAL_ACTIVITY_DAILY_MKT_DG A
    LEFT JOIN DIM.SPARK_DT_REGIONS_MKT_V2 B ON A.REGION_ID = B.REGION_ID
    WHERE TRANSACTION_DATE='###SLICE_VALUE###' AND 
        KPI='REVENUE' AND 
        SERVICE_CODE='NVX_GPRS_ROAMING'
    GROUP BY
        B.ADMINISTRATIVE_REGION,
        B.COMMERCIAL_REGION

    UNION ALL
    -- 9. TOTAL SMS 
    SELECT
        B.ADMINISTRATIVE_REGION ADMINISTRATIVE_REGION,
        B.COMMERCIAL_REGION COMMERCIAL_REGION,
        'SMS' KPI_NAME,
        SUM(RATED_AMOUNT) VALUE
    FROM AGG.SPARK_FT_GLOBAL_ACTIVITY_DAILY_MKT_DG A
    LEFT JOIN DIM.SPARK_DT_REGIONS_MKT_V2 B ON A.REGION_ID = B.REGION_ID
    WHERE TRANSACTION_DATE='###SLICE_VALUE###' AND 
        KPI='REVENUE' AND 
        SUB_ACCOUNT='MAIN' AND 
        SUBSTRING(DESTINATION_CODE,1,11)='REVENUE_SMS'
    GROUP BY
        B.ADMINISTRATIVE_REGION,
        B.COMMERCIAL_REGION

    UNION ALL
    -- 10. SMS PYG 
    SELECT 
        A.ADMINISTRATIVE_REGION ADMINISTRATIVE_REGION,
        A.COMMERCIAL_REGION COMMERCIAL_REGION,
        'SMS PYG' KPI_NAME,
        SUM(RATED_AMOUNT) VALUE
    FROM
    (
        SELECT
            B.ADMINISTRATIVE_REGION ADMINISTRATIVE_REGION,
            B.COMMERCIAL_REGION COMMERCIAL_REGION,
            A.SERVICE_CODE SERVICE_CODE,
            A.RATED_AMOUNT RATED_AMOUNT
        FROM AGG.SPARK_FT_GLOBAL_ACTIVITY_DAILY_MKT_DG A
        LEFT JOIN DIM.SPARK_DT_REGIONS_MKT_V2 B ON A.REGION_ID = B.REGION_ID
        WHERE TRANSACTION_DATE='###SLICE_VALUE###' AND 
            KPI='REVENUE' AND 
            SUB_ACCOUNT='MAIN'
    ) A
    LEFT JOIN DIM.DT_USAGES B ON UPPER(A.SERVICE_CODE) = UPPER(B.USAGE_CODE)
    WHERE UPPER(B.USAGE_DESCRIPTION) = 'SMS'
    GROUP BY
        A.ADMINISTRATIVE_REGION,
        A.COMMERCIAL_REGION

    UNION ALL
    -- 11. SMS BUNDLES 
    SELECT
        B.ADMINISTRATIVE_REGION ADMINISTRATIVE_REGION,
        B.COMMERCIAL_REGION COMMERCIAL_REGION,
        'SMS BUNDLES' KPI_NAME,
        SUM(RATED_AMOUNT) VALUE
    FROM AGG.SPARK_FT_GLOBAL_ACTIVITY_DAILY_MKT_DG A
    LEFT JOIN DIM.SPARK_DT_REGIONS_MKT_V2 B ON A.REGION_ID = B.REGION_ID
    WHERE TRANSACTION_DATE='###SLICE_VALUE###' AND 
        KPI='REVENUE' AND 
        SUB_ACCOUNT='MAIN' AND 
        DESTINATION_CODE='REVENUE_SMS_BUNDLE'
    GROUP BY
        B.ADMINISTRATIVE_REGION,
        B.COMMERCIAL_REGION
    
    -- 12. SMS COMBO NOK

    UNION ALL
    -- 13. TOTAL VAS 
    SELECT
        B.ADMINISTRATIVE_REGION ADMINISTRATIVE_REGION,
        B.COMMERCIAL_REGION COMMERCIAL_REGION,
        'VAS' KPI_NAME,
        SUM(RATED_AMOUNT) VALUE
    FROM AGG.SPARK_FT_GLOBAL_ACTIVITY_DAILY_MKT_DG A
    LEFT JOIN DIM.SPARK_DT_REGIONS_MKT_V2 B ON A.REGION_ID = B.REGION_ID
    WHERE TRANSACTION_DATE='###SLICE_VALUE###' AND 
        KPI='REVENUE' AND SUB_ACCOUNT='MAIN' AND 
        DESTINATION_CODE IN ('P2P_DATA_VAS','REVENUE_SMS_VAS','REVENUE_VOICE_VAS')
    GROUP BY
        B.ADMINISTRATIVE_REGION,
        B.COMMERCIAL_REGION

    UNION ALL
    -- 14. SOS CREDIT 
    SELECT
        B.ADMINISTRATIVE_REGION ADMINISTRATIVE_REGION,
        B.COMMERCIAL_REGION COMMERCIAL_REGION,
        'SOS CREDIT' KPI_NAME,
        SUM(RATED_AMOUNT) VALUE
    FROM AGG.SPARK_FT_GLOBAL_ACTIVITY_DAILY_MKT_DG A
    LEFT JOIN DIM.SPARK_DT_REGIONS_MKT_V2 B ON A.REGION_ID = B.REGION_ID
    WHERE TRANSACTION_DATE='###SLICE_VALUE###' AND 
        KPI='REVENUE' AND 
        SUB_ACCOUNT='MAIN' AND 
        DESTINATION_CODE='SOS_CREDIT'
    GROUP BY
        B.ADMINISTRATIVE_REGION,
        B.COMMERCIAL_REGION

    UNION ALL
    -- 15. ZEBRA SERVICE 
    SELECT
        B.ADMINISTRATIVE_REGION ADMINISTRATIVE_REGION,
        B.COMMERCIAL_REGION COMMERCIAL_REGION,
        'ZEBRA SERVICE' KPI_NAME,
        SUM(RATED_AMOUNT) VALUE
    FROM AGG.SPARK_FT_GLOBAL_ACTIVITY_DAILY_MKT_DG A
    LEFT JOIN DIM.SPARK_DT_REGIONS_MKT_V2 B ON A.REGION_ID = B.REGION_ID
    WHERE TRANSACTION_DATE='###SLICE_VALUE###' AND 
        KPI='REVENUE' AND 
        SUB_ACCOUNT='MAIN' AND 
        SOURCE_TABLE = 'FT_SUBS_RETAIL_ZEBRA'
    GROUP BY
        B.ADMINISTRATIVE_REGION,
        B.COMMERCIAL_REGION

    UNION ALL
    -- 16. ORANGE MONEY 
    SELECT
        B.ADMINISTRATIVE_REGION ADMINISTRATIVE_REGION,
        B.COMMERCIAL_REGION COMMERCIAL_REGION,
        'ORANGE MONEY' KPI_NAME,
        SUM(RATED_AMOUNT) VALUE
    FROM AGG.SPARK_FT_GLOBAL_ACTIVITY_DAILY_MKT_DG A
    LEFT JOIN DIM.SPARK_DT_REGIONS_MKT_V2 B ON A.REGION_ID = B.REGION_ID
    WHERE TRANSACTION_DATE ='###SLICE_VALUE###' AND 
        KPI='REVENUE_OM'
    GROUP BY
    B.ADMINISTRATIVE_REGION,
    B.COMMERCIAL_REGION

)