INSERT INTO AGG.SPARK_FT_A_REPORTING_360
SELECT
    ADMINISTRATIVE_REGION,
    COMMERCIAL_REGION,
    'SUBSCRIBERS' KPI_GROUP_NAME,
    KPI_NAME,
    KPI_VALUE VALUE,
    current_timestamp() INSERT_DATE,
    '###SLICE_VALUE###' PROCESSING_DATE
from
(
    select
        case
            WHEN DESTINATION_CODE = 'USER_ART' THEN 'PARC_ART_DAILY'
            WHEN DESTINATION_CODE = 'USER_GROUP' THEN 'PARC_GROUP_DAILY'
            WHEN DESTINATION_CODE = 'PARC_OM_DAILY' THEN 'PARC_OM_DAILY'
            WHEN DESTINATION_CODE = 'PARC_OM_MTD' THEN 'PARC_OM_MTD'
            WHEN DESTINATION_CODE = 'PARC_OM_30Jrs' THEN 'PARC_OM_30Jrs'
            WHEN DESTINATION_CODE = 'UNIQUE_DATA_USERS_1Mo' THEN 'DATA_USERS_DAILY'
            WHEN DESTINATION_CODE = 'UNIQUE_DATA_USERS_MTD_1Mo' THEN 'DATA_USERS_MTD'
            WHEN DESTINATION_CODE = 'UNIQUE_DATA_USERS_1Mo_30Jrs' THEN 'DATA_USERS_30Jrs'
            WHEN DESTINATION_CODE = 'USER_DAILY_ACTIVE' THEN 'DAILY_BASE'
            WHEN DESTINATION_CODE = 'USER_30DAYS_GROUP' THEN 'CHARGED_BASE'
        end KPI_NAME,
        sum(TOTAL_AMOUNT) KPI_VALUE,
        REGION_ID
    from AGG.SPARK_FT_GLOBAL_ACTIVITY_DAILY_MKT_DG
    where transaction_date = '###SLICE_VALUE###'
        and DESTINATION_CODE in ('USER_ART', 'USER_GROUP', 'PARC_OM_DAILY', 'PARC_OM_MTD', 'PARC_OM_30Jrs', 'UNIQUE_DATA_USERS_1Mo', 'UNIQUE_DATA_USERS_MTD_1Mo', 'UNIQUE_DATA_USERS_1Mo_30Jrs', 'USER_DAILY_ACTIVE', 'USER_30DAYS_GROUP')
    group by region_id,
        case
            WHEN DESTINATION_CODE = 'USER_ART' THEN 'PARC_ART_DAILY'
            WHEN DESTINATION_CODE = 'USER_GROUP' THEN 'PARC_GROUP_DAILY'
            WHEN DESTINATION_CODE = 'PARC_OM_DAILY' THEN 'PARC_OM_DAILY'
            WHEN DESTINATION_CODE = 'PARC_OM_MTD' THEN 'PARC_OM_MTD'
            WHEN DESTINATION_CODE = 'PARC_OM_30Jrs' THEN 'PARC_OM_30Jrs'
            WHEN DESTINATION_CODE = 'UNIQUE_DATA_USERS_1Mo' THEN 'DATA_USERS_DAILY'
            WHEN DESTINATION_CODE = 'UNIQUE_DATA_USERS_MTD_1Mo' THEN 'DATA_USERS_MTD'
            WHEN DESTINATION_CODE = 'UNIQUE_DATA_USERS_1Mo_30Jrs' THEN 'DATA_USERS_30Jrs'
            WHEN DESTINATION_CODE = 'USER_DAILY_ACTIVE' THEN 'DAILY_BASE'
            WHEN DESTINATION_CODE = 'USER_30DAYS_GROUP' THEN 'CHARGED_BASE'
        end
) A
LEFT JOIN DIM.SPARK_DT_REGIONS_MKT_V2 B
ON A.REGION_ID = B.REGION_ID
