INSERT INTO AGG.SPARK_FT_A_REPORTING_360
SELECT
    ADMINISTRATIVE_REGION,
    COMMERCIAL_REGION,
    'REFILL' KPI_GROUP_NAME,
    KPI_NAME,
    KPI_VALUE VALUE,
    current_timestamp() INSERT_DATE,
    '###SLICE_VALUE###' PROCESSING_DATE
from
(
    select
        case
            WHEN DESTINATION_CODE = 'VALEUR_AIRTIME' THEN 'EVD_TOTAL'
            WHEN DESTINATION_CODE = 'REFILL_SELF_TOP' THEN 'ORANGE_MONEY_REFILL'
            WHEN DESTINATION_CODE = 'DATA_VIA_OM' THEN 'DATA_VIA_OM'
        end KPI_NAME,
        sum(TOTAL_AMOUNT) KPI_VALUE,
        REGION_ID
    from AGG.SPARK_FT_GLOBAL_ACTIVITY_DAILY_MKT_DG
    where transaction_date = '###SLICE_VALUE###'
        and DESTINATION_CODE in ('VALEUR_AIRTIME', 'REFILL_SELF_TOP', 'DATA_VIA_OM')
    group by region_id,
        case
            WHEN DESTINATION_CODE = 'VALEUR_AIRTIME' THEN 'EVD_TOTAL'
            WHEN DESTINATION_CODE = 'REFILL_SELF_TOP' THEN 'ORANGE_MONEY_REFILL'
            WHEN DESTINATION_CODE = 'DATA_VIA_OM' THEN 'ORANGE_MONEY_REFILL'
        end
) A
LEFT JOIN DIM.SPARK_DT_REGIONS_MKT_V2 B
ON A.REGION_ID = B.REGION_ID
