SELECT IF(
    T1.KPI_IS_LOAD=0 
    and T2.FT_GLOBAL_ACTIVITY_DAILY_MKT_DG_INSERTED_SOURCES = 3
    and T3.FT_EXISTS > 0
    , 'OK'
    , 'NOK'
)
FROM
(SELECT COUNT(*) KPI_IS_LOAD FROM AGG.SPARK_FT_A_REPORTING_360 WHERE PROCESSING_DATE='###SLICE_VALUE###' AND KPI_GROUP_NAME='REFILL') T1,
(
    SELECT COUNT(distinct source_table) FT_GLOBAL_ACTIVITY_DAILY_MKT_DG_INSERTED_SOURCES
    FROM AGG.SPARK_FT_GLOBAL_ACTIVITY_DAILY_MKT_DG_NEW
    WHERE TRANSACTION_DATE='###SLICE_VALUE###'
        and source_table in ('FT_RETAIL_BASE_DETAILLANT', 'FT_SUBSCRIPTION', 'FT_REFILL')
) T2,
(
    SELECT COUNT(*) FT_EXISTS FROM CDR.SPARK_IT_OMNY_TRANSACTIONS WHERE transfer_datetime='###SLICE_VALUE###'
) T3

