SELECT IF(
            T1.KPI_IS_LOAD=0 AND 
            T2.SRC_EXISTS > 0 AND
            T3.SRC_EXISTS > 0 AND
            T4.SRC_EXISTS > 0 AND
            T5.SRC_EXISTS > 0 AND
            T6.SRC_EXISTS > 0 AND
            T7.SRC_EXISTS > 0 AND
            T8.SRC_EXISTS > 0 AND
            T9.SRC_EXISTS > 0 AND
            T10.SRC_EXISTS > 0 AND
            T11.SRC_EXISTS > 0 AND
            T12.SRC_EXISTS > 0
        'OK','NOK')
 FROM
(SELECT COUNT(*) KPI_IS_LOAD FROM AGG.SPARK_FT_A_REPORTING_360 WHERE PROCESSING_DATE='###SLICE_VALUE###' AND KPI_GROUP_NAME='REVENUE PER STREAM')T1,
(SELECT COUNT(*) SRC_EXISTS FROM AGG.SPARK_FT_GLOBAL_ACTIVITY_DAILY_MKT_DG WHERE TRANSACTION_DATE='###SLICE_VALUE###' AND SOURCE_TABLE='FT_EMERGENCY_DATA') T2,
(SELECT COUNT(*) SRC_EXISTS FROM AGG.SPARK_FT_GLOBAL_ACTIVITY_DAILY_MKT_DG WHERE TRANSACTION_DATE='###SLICE_VALUE###' AND SOURCE_TABLE='FT_GSM_TRAFFIC_REVENUE_DAILY') T3,
(SELECT COUNT(*) SRC_EXISTS FROM AGG.SPARK_FT_GLOBAL_ACTIVITY_DAILY_MKT_DG WHERE TRANSACTION_DATE='###SLICE_VALUE###' AND SOURCE_TABLE='IT_ZTE_ADJUSTMENT') T4,
(SELECT COUNT(*) SRC_EXISTS FROM AGG.SPARK_FT_GLOBAL_ACTIVITY_DAILY_MKT_DG WHERE TRANSACTION_DATE='###SLICE_VALUE###' AND SOURCE_TABLE='FT_DATA_TRANSFER') T5,
(SELECT COUNT(*) SRC_EXISTS FROM AGG.SPARK_FT_GLOBAL_ACTIVITY_DAILY_MKT_DG WHERE TRANSACTION_DATE='###SLICE_VALUE###' AND SOURCE_TABLE='FT_OVERDRAFT') T6,
(SELECT COUNT(*) SRC_EXISTS FROM AGG.SPARK_FT_GLOBAL_ACTIVITY_DAILY_MKT_DG WHERE TRANSACTION_DATE='###SLICE_VALUE###' AND SOURCE_TABLE='FT_A_SUBSCRIPTION') T7,
(SELECT COUNT(*) SRC_EXISTS FROM AGG.SPARK_FT_GLOBAL_ACTIVITY_DAILY_MKT_DG WHERE TRANSACTION_DATE='###SLICE_VALUE###' AND SOURCE_TABLE = 'FT_CONTRACT_SNAPSHOT') T8,
(SELECT COUNT(*) SRC_EXISTS FROM AGG.SPARK_FT_GLOBAL_ACTIVITY_DAILY_MKT_DG WHERE TRANSACTION_DATE='###SLICE_VALUE###' AND SOURCE_TABLE='FT_CREDIT_TRANSFER') T9,
(SELECT COUNT(*) SRC_EXISTS FROM AGG.SPARK_FT_GLOBAL_ACTIVITY_DAILY_MKT_DG WHERE TRANSACTION_DATE='###SLICE_VALUE###' AND SOURCE_TABLE='FT_SUBS_RETAIL_ZEBRA') T10,
(SELECT COUNT(*) SRC_EXISTS FROM AGG.SPARK_FT_GLOBAL_ACTIVITY_DAILY_MKT_DG WHERE TRANSACTION_DATE='###SLICE_VALUE###' AND SOURCE_TABLE = 'REGIONAL_DOM_DASHBOARD') T11,
(SELECT COUNT(*) SRC_EXISTS FROM AGG.SPARK_FT_GLOBAL_ACTIVITY_DAILY_MKT_DG WHERE TRANSACTION_DATE='###SLICE_VALUE###' AND SOURCE_TABLE='FT_A_GPRS_ACTIVITY') T12

