SELECT IF(
            T1.KPI_IS_LOAD=0 AND 
            T2.KPI_EXISTS>0 
        'OK','NOK')
 FROM
(SELECT COUNT(*) KPI_IS_LOAD FROM AGG.SPARK_FT_A_REPORTING_360 WHERE PROCESSING_DATE='###SLICE_VALUE###' AND KPI_GROUP_NAME='REVENUE PER STREAM')T1,
(SELECT COUNT(*) KPI_EXISTS FROM AGG.SPARK_FT_GLOBAL_ACTIVITY_DAILY_MKT_DG WHERE TRANSACTION_DATE='###SLICE_VALUE###')T2