SELECT IF(A.FT_EXIST = 0 and B.FT_COUNT>0 and C.FT_COUNT>0 , "OK","NOK") FROM
(SELECT COUNT(*) FT_EXIST FROM MON.SPARK_FT_OPERATOR_ACCT_ACTIVITY WHERE EVENT_DATE='###SLICE_VALUE###') A,
(SELECT COUNT(*) FT_COUNT FROM MON.SPARK_FT_OPERATOR_ACCT_ACTIVITY WHERE EVENT_DATE=DATE_SUB('###SLICE_VALUE###',1)) B,
(SELECT COUNT(*) FT_COUNT FROM MON.SPARK_FT_HUA_OPERATOR_OG_IC_SNAPSHOT WHERE EVENT_DATE='###SLICE_VALUE###') C
