create table MON.spark_ft_crm_output_orange_money (
NOM  VARCHAR(250),
PRENOM  VARCHAR(250),
CODE_CLIENT  VARCHAR(100),
SERVICE_ORANGE_MONEY  INTEGER,
SOUSCRIPTION_MSISDN_OM  INTEGER,
MSISDN  VARCHAR(25),
INSERT_DATE  TIMESTAMP
) COMMENT 'MON_spark_ft_crm_output_orange_money'
PARTITIONED BY (EVENT_DATE DATE)
STORED AS PARQUET TBLPROPERTIES ('PARQUET.COMPRESS'='SNAPPY')