INSERT INTO  AGG.FT_A_POKE_CALL
SELECT
    RESULT STATUT,
    CAUSENAME CAUSE_NAME,
    SUM(1) EVENT_COUNT,
    SUM(MAIN_RATED_AMOUNT) MAIN_RATED_AMOUNT,
    SUM(PROMO_RATED_AMOUNT) PROMO_RATED_AMOUNT,
    SETUPDATE EVENT_DATE,
    CURRENT_TIMESTAMP INSERT_DATE
FROM  MON.FT_POKE_CALL WHERE SETUPDATE='2019-06-09'
GROUP BY
    SETUPDATE,
    RESULT,
    CAUSENAME