
CREATE TABLE MON.FT_SUBS_RETAIL_ZEBRA (
    TRANSACTION_TIME VARCHAR(6),
    SERVED_PARTY_MSISDN VARCHAR(40),
    SUBSCRIPTION_SERVICE_DETAILS VARCHAR(50),
    ZEBRA_DATETIME VARCHAR(25),
    ZEBRA_SENDER_MSISDN VARCHAR(20),
    ZEBRA_RECEIVER_MSISDN VARCHAR(20),
    MAIN_AMOUNT DECIMAL(20,2),
    INSERT_DATE TIMESTAMP,
    COMMERCIAL_OFFER VARCHAR(50),
    OPERATOR_CODE VARCHAR(50)
)
COMMENT 'Subs Retail Zebra - FT'
PARTITIONED BY (TRANSACTION_DATE    DATE)
STORED AS ORC TBLPROPERTIES ('transactional'='true',"orc.compress"="ZLIB","orc.stripe.size"="67108864")

