CREATE TABLE TMP.TMP_RECEIVED_NOTIFICATION_SMS
(
    Hour_Min VARCHAR(25),
    served_msisdn VARCHAR(100),
    location_ci VARCHAR(100),
    location_lac VARCHAR(100),
    site_name VARCHAR(100)
)
STORED AS PARQUET
TBLPROPERTIES ('PARQUET.COMPRESS'='SNAPPY')