create table MON.FT_OG_IC_CALL_SNAPSHOT
(
    MSISDN     VARCHAR(40),
    OG_CALL    TIMESTAMP,
    IC_CALL_1  TIMESTAMP,
    IC_CALL_2  TIMESTAMP,
    IC_CALL_3  TIMESTAMP,
    IC_CALL_4  TIMESTAMP,
    INSERT_DATE TIMESTAMP
) COMMENT 'FT_ACCOUNT_ACTIVITY table'
PARTITIONED BY (EVENT_DATE DATE)
STORED AS ORC
TBLPROPERTIES ("orc.compress"="ZLIB","orc.stripe.size"="67108864")

