create table MON.FT_OG_IC_CALL_SNAPSHOT
(
    MSISDN     VARCHAR(40),
    OG_CALL    DATE,
    IC_CALL_1  DATE,
    IC_CALL_2  DATE,
    IC_CALL_3  DATE,
    IC_CALL_4  DATE,
    INSERT_DATE DATE
) COMMENT 'FT_ACCOUNT_ACTIVITY table'
PARTITIONED BY (EVENT_DATE DATE)
CLUSTERED BY(MSISDN) INTO 8 BUCKETS STORED AS ORC
TBLPROPERTIES ("orc.compress"="ZLIB","orc.stripe.size"="67108864")

