create table MON.TMP_OG_IC_CALL_SNAPSHOT_PRE
(
    MSISDN     VARCHAR(40),
    OG_CALL    TIMESTAMP,
    IC_CALL_1  TIMESTAMP,
    IC_CALL_2  TIMESTAMP,
    IC_CALL_3  TIMESTAMP,
    IC_CALL_4  TIMESTAMP
) COMMENT 'FT_ACCOUNT_ACTIVITY table'
STORED AS ORC
TBLPROPERTIES ("orc.compress"="ZLIB","orc.stripe.size"="67108864")