create table MON.SPARK_TMP_OG_IC_CALL_SNAPSHOT_PRE
(
    MSISDN     VARCHAR(40),
    OG_CALL    DATE,
    IC_CALL_1  DATE,
    IC_CALL_2  DATE,
    IC_CALL_3  DATE,
    IC_CALL_4  DATE
) COMMENT 'TMP_OG_IC_CALL_SNAPSHOT_PRE table'
 STORED AS PARQUET TBLPROPERTIES ('PARQUET.COMPRESS'='SNAPPY');
