--- Etape 5 : Merge entre PP et FLOTTE/M2M.
insert into TMP.TT_KYC_BDI_FULL_ST5
(select 
guid,
cust_guid,
msisdn,
type_personne,
nom_prenom,
id_type_piece,
type_piece,
numero_piece,
date_expiration,
date_naissance,
date_activation,
adresse,
quartier,
ville,
statut,
statut_validation_bo,
motif_rejet_bo,
date_validation_bo,
login_validateur_bo,
canal_validateur_bo,
type_abonnement,
csmoddate,
ccmoddate,
compte_client_structure,
nom_structure,
numero_registre_commerce,
numero_piece_representant_legal,
adresse_structure,
imei,
odbIncomingCalls,
odbOutgoingCalls,
(case when trim(odbOutgoingCalls) is null OR trim(odbIncomingCalls)  is null then 'U'
    WHEN trim(odbOutgoingCalls) = '1'
    then case when trim(odbIncomingCalls) = '1' then  'SUSPENDU'
              else 'SUSPENDU_SORTANT'
          end
    WHEN trim(odbIncomingCalls) = '1'
    then case when trim(odbOutgoingCalls) <> '1' then  'SUSPENDU_ENTRANT'
          end
    else 'ACTIF'
end) as statut_hlr,
statut_derogation,
region_administrative,
region_commerciale,
site_name,
ville_site,
offre_commerciale,
type_contrat,
segmentation,
date_souscription,
date_changement_statut,
ville_structure,
quartier_structure,
raison_statut,
prenom,
nom,
customer_id,
contract_id,
compte_client,
plan_localisation,
contrat_soucription,
acceptation_cgv,
disponibilite_scan,
nom_tuteur,
prenom_tuteur,
date_naissance_tuteur,
numero_piece_tuteur,
date_expiration_tuteur,
id_type_piece_tuteur,
type_piece_tuteur,
adresse_tuteur,
identificateur,
localisation_identificateur,
profession from  TMP.TT_KYC_BDI_FULL_ST4)
union
(select 
guid,
cust_guid,
msisdn,
type_personne,
nom_prenom,
id_type_piece,
type_piece,
numero_piece,
date_expiration,
date_naissance,
date_activation,
adresse,
quartier,
ville,
statut,
statut_validation_bo,
motif_rejet_bo,
date_validation_bo,
login_validateur_bo,
canal_validateur_bo,
type_abonnement,
csmoddate,
ccmoddate,
compte_client_structure,
nom_structure,
numero_registre_commerce,
numero_piece_representant_legal,
adresse_structure,
imei,
odbIncomingCalls,
odbOutgoingCalls,
(case when trim(odbOutgoingCalls) is null OR trim(odbIncomingCalls)  is null then 'U'
    WHEN trim(odbOutgoingCalls) = '1'
    then case when trim(odbIncomingCalls) = '1' then  'SUSPENDU'
              else 'SUSPENDU_SORTANT'
          end
    WHEN trim(odbIncomingCalls) = '1'
    then case when trim(odbOutgoingCalls) <> '1' then  'SUSPENDU_ENTRANT'
          end
    else 'ACTIF'
end) as statut_hlr,
statut_derogation,
region_administrative,
region_commerciale,
site_name,
ville_site,
offre_commerciale,
type_contrat,
segmentation,
date_souscription,
date_changement_statut,
ville_structure,
quartier_structure,
raison_statut,
prenom,
nom,
customer_id,
contract_id,
compte_client,
plan_localisation,
contrat_soucription,
acceptation_cgv,
disponibilite_scan,
nom_tuteur,
prenom_tuteur,
date_naissance_tuteur,
numero_piece_tuteur,
date_expiration_tuteur,
id_type_piece_tuteur,
type_piece_tuteur,
adresse_tuteur,
identificateur,
localisation_identificateur,
profession
from TMP.TT_KYC_BDI_FULL_ST3 where not(offre_commerciale like '%FLEX%' or offre_commerciale like '%MIX%' or offre_commerciale like '%INTENSE%'))