CREATE EXTERNAL TABLE IF NOT EXISTS CDR.TT_ZTE_CHECK_FILE_ALL (
    CDR_NAME VARCHAR (100),
    ORIGINAL_FILE_NAME VARCHAR (100)
)
COMMENT 'External Table Check files All'
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|'
LOCATION '/PROD/TT/IN_ZTE/CHECK_FILE_ALL'
TBLPROPERTIES ('serialization.null.format'='')
;
