SELECT IF(A.FT_EXIST = 0 and B.FT_SUBSCRIPTION_EXIST>0 and C.DIM_ACTIVATION >0, "OK", "NOK") FROM
(SELECT count(*) FT_EXIST FROM mon.spark_FT_ACTIVATION_BY_IDENTIF_DAY WHERE ACTIVATION_DATE='###SLICE_VALUE###') A,
(SELECT COUNT(*) FT_SUBSCRIPTION_EXIST FROM MON.SPARK_ft_subscription WHERE TRANSACTION_DATE='###SLICE_VALUE###') B
(SELECT COUNT(*) DIM_ACTIVATION FROM DIM.spark_DT_BASE_IDENTIFICATION WHERE DATE_IDENTIFICATION ='###SLICE_VALUE###') C