SELECT IF(T_1.FT_EXIST = 0 and T_2.IT_OM_TRANSACTIONS_EXIST>0,"OK","NOK") EXTRACT_EXIST
FROM
(SELECT COUNT(*) FT_EXIST FROM MON.SPARK_FT_OMNY_GLOBAL_ACTIVITY WHERE EVENT_DATE='###SLICE_VALUE###') T_1,
(SELECT COUNT(*) IT_OM_TRANSACTIONS_EXIST FROM CDR.SPARK_IT_OMNY_TRANSACTIONS WHERE TRANSFER_DATETIME='###SLICE_VALUE###') T_2
