CREATE TABLE SPOOL.SPOOL_BRI_REVENU_DATA_PAR_SITE_DETAIL

(
ADMINISTRATIVE_REGION varchar(50),
COMMERCIAL_REGION varchar(50),
TOWNNAME varchar(50),
SITE_NAME varchar(50),
TOTAL_USERS_BUNDLE_DATA bigint,
MAIN_COST_BUNDLE_DATA bigint,
TOTAL_USERS_PAYASGO_DATA bigint,
MAIN_COST_PAYASGO_DATA bigint,
TOTAL_USERS_DATA bigint,
MAIN_COST_DATA bigint,
INSERT_DATE TIMESTAMP
)

PARTITIONED BY (base_month DATE)
STORED AS PARQUET TBLPROPERTIES ('PARQUET.COMPRESS' = 'SNAPPY')




