CREATE TABLE AGG.SPARK_FT_FT_REFILL_SLICE_MKT
(
    KPI                     VARCHAR(50),
    REFILL_MEAN             VARCHAR(50),
    SLICE_ID                VARCHAR(50),
    PROFILE_CODE            VARCHAR(50),
    SOURCE_TABLE            VARCHAR(50),
    OPERATOR_CODE           VARCHAR(50),
    TOTAL_AMOUNT            DOUBLE,
    INSERT_DATE             TIMESTAMP
)
PARTITIONED BY (TRANSACTION_DATE DATE)
STORED AS PARQUET
TBLPROPERTIES ('PARQUET.COMPRESS'='SNAPPY')