SELECT IF(A.FT_EXIST = 0 and B.FT_KPI_EXIST = 0 and C.IT_EXIST>0,"OK","NOK") FROM
(SELECT COUNT(*) FT_EXIST FROM MON.SPARK_FT_ORANGEPRO_PU_ACTE_GESTION WHERE EVENT_DATE='###SLICE_VALUE###') A,
(SELECT COUNT(*) FT_KPI_EXIST FROM MON.SPARK_FT_ORANGEPRO_PU_KPI WHERE EVENT_DATE='###SLICE_VALUE###')B,
(SELECT COUNT(*) IT_EXIST FROM CDR.SPARK_IT_ORANGEPRO_PORTAIL_UNIFIE WHERE ORIGINAL_FILE_DATE='###SLICE_VALUE###')C;