INSERT INTO CDR.IT_TRAFFIC_CUST_OTARIE PARTITION(TRANSACTION_DATE)
SELECT
    IDCUST
    ,IDAPPLI
    ,IDAPN
    ,IDTAC
    ,IDRAT
    ,IDGGSN
    ,ROAMING
    ,NBYTESDN
    ,NBYTESUP
    ,NBYTEST
    ,TERMINAL_TYPE
    ,TERMINAL_BRAND
    ,TERMINAL_MODEL
    ,TOFIND_1
    ,TOFIND_2
    ,TOFIND_3
    ,TOFIND_4
    ,TOFIND_5
    ,ORIGINAL_FILE_NAME
    ,TO_DATE(FROM_UNIXTIME(UNIX_TIMESTAMP(SUBSTRING (ORIGINAL_FILE_NAME, -18, 8),'yyyyMMdd'))) ORIGINAL_FILE_DATE
    ,ORIGINAL_FILE_SIZE
    ,ORIGINAL_FILE_LINE_COUNT
    ,CURRENT_TIMESTAMP
    ,TRANSACTION_DATE
FROM CDR.TT_TRAFFIC_CUST_OTARIE C
LEFT JOIN (SELECT DISTINCT  ORIGINAL_FILE_NAME FILE_NAME FROM CDR.IT_TRAFFIC_CUST_OTARIE WHERE TRANSACTION_DATE BETWEEN DATE_SUB(CURRENT_DATE,${hivevar:date_offset}) AND CURRENT_DATE )T ON T.FILE_NAME=C.ORIGINAL_FILE_NAME
WHERE T.FILE_NAME IS NULL;