CREATE TABLE TMP.SPARK_TT_FT_CBM_DOLA_DAILY(
 EVENT_DATE       DATE,
 MSISDN           VARCHAR(40),
 ACTIVATION_DATE  DATE,
 DOLA             DATE,
 DOLIA            DATE,
 ACTIVITY_TYPE    VARCHAR(80),
 RGSX             VARCHAR(80),
 REGION           VARCHAR(80),
 TOWN             VARCHAR(80),
 QUARTER          VARCHAR(80),
 INSERT_DATE      TIMESTAMP
)COMMENT 'MON.TT_FT_CBM_DOLA_DAILY Table'
STORED AS PARQUET TBLPROPERTIES ('PARQUET.COMPRESS'='SNAPPY')
    