 CREATE TABLE MON.SPARK_FT_CBM_DOLA_DAILY (
	MSISDN          VARCHAR(40), 
	ACTIVATION_DATE DATE, 
	DOLA            DATE, 
	DOLIA           DATE, 
	ACTIVITY_TYPE   VARCHAR(80), 
	RGSX            VARCHAR(80), 
	REGION          VARCHAR(80), 
	TOWN            VARCHAR(80), 
	QUARTER         VARCHAR(80), 
	INSERT_DATE     TIMESTAMP
  ) COMMENT 'MON.FT_CBM_DOLA_DAILY Table'
PARTITIONED BY (EVENT_DATE DATE)
STORED AS PARQUET TBLPROPERTIES ('PARQUET.COMPRESS'='SNAPPY')
    
