CREATE TABLE TMP.TT_FT_CBM_DOLA_DAILY_PRE  (
	EVENT_DATE DATE, 
    MSISDN VARCHAR(40),
    DOLA DATE, 
    ACTIVITY_TYPE VARCHAR(80)
    ) COMMENT 'MON.TT_FT_CBM_DOLA_DAILY_PRE Table'
STORED AS ORC TBLPROPERTIES ('transactional'='true',"orc.compress"="ZLIB","orc.stripe.size"="67108864");
    