INSERT INTO AGG.SPARK_FT_A_TRAFFIC_ENTRANT_AMN2
 SELECT
 SITE_NAME, 
 SUM(DUREE_ENTRANT) AS DUREE_ENTRANT,
 SUM(NBRE_TEL_ENTRANT) AS NBRE_TEL_ENTRANT, 
 SUM(NBRE_SMS_ENTRANT) AS NBRE_SMS_ENTRANT,
 SUM(NBRE_TEL_MTN_ENTRANT) AS NBRE_TEL_MTN_ENTRANT, 
 SUM(NBRE_TEL_CAMTEL_ENTRANT) AS NBRE_TEL_CAMTEL_ENTRANT, 
 SUM(NBRE_TEL_OCM_ENTRANT) AS NBRE_TEL_OCM_ENTRANT, 
 SUM(DUREE_TEL_MTN_ENTRANT) AS DUREE_TEL_MTN_ENTRANT,
 SUM(DUREE_TEL_CAMTEL_ENTRANT) AS DUREE_TEL_CAMTEL_ENTRANT, 
 SUM(DUREE_TEL_OCM_ENTRANT) AS DUREE_TEL_OCM_ENTRANT, 
 SUM(NBRE_SMS_MTN_ENTRANT) AS NBRE_SMS_MTN_ENTRANT, 
 SUM(NBRE_SMS_CAMTEL_ENTRANT) AS NBRE_SMS_CAMTEL_ENTRANT, 
 SUM(NBRE_SMS_OCM_ENTRANT) AS NBRE_SMS_OCM_ENTRANT, 
 SUM(NBRE_SMS_ZEBRA_ENTRANT) AS NBRE_SMS_ZEBRA_ENTRANT, 
 SUM(NBRE_TEL_NEXTTEL_ENTRANT) AS NBRE_TEL_NEXTTEL_ENTRANT, 
 SUM(DUREE_TEL_NEXTTEL_ENTRANT) AS DUREE_TEL_NEXTTEL_ENTRANT, 
 SUM(NBRE_SMS_NEXTTEL_ENTRANT) AS NBRE_SMS_NEXTTEL_ENTRANT,
 CURRENT_TIMESTAMP AS INSERT_DATE,
 '###SLICE_VALUE###' AS EVENT_DATE
        FROM MON.SPARK_FT_CELL_TRAFIC_DAYLY a
            JOIN (select (case when length(ci) =2 then concat('000',ci)
            when length(ci) =3 then concat('00',ci)
            when length(ci) =4 then concat('0',ci) else ci end) ci, lac, site_name
from dim.dt_ci_lac_site_amn) b
                ON SUBSTR(MS_LOCATION,14,5) = b.CI
        WHERE a.EVENT_DATE = '###SLICE_VALUE###'
        GROUP BY b.SITE_NAME