CREATE TABLE SPOOL.SPOOL_BASE_IDENTIFICATION_DMC
(
    MSISDN VARCHAR(255)
    , GENRE VARCHAR(255)
    , TYPE_PIECE VARCHAR(255)
    , NUMERO_PIECE VARCHAR(255)
    , DATE_EXPIRATION VARCHAR(255)
    , DATE_NAISSANCE VARCHAR(255)
    , STATUT_VALIDATION_BOO VARCHAR(255)
    , EST_SUSPENDU VARCHAR(255)
    , INSERT_DATE TIMESTAMP
)
PARTITIONED BY (EVENT_DATE DATE)
STORED AS PARQUET
TBLPROPERTIES ('PARQUET.COMPRESS'='SNAPPY')