INSERT INTO TMP.TT_SPARK_FT_CLIENT_LAST_CALLED_90_DAYS_FILTERED
SELECT 
    CALLER,
    CALLEE_LIST,
    NBR_CALLEE,
    SITE_NAME
FROM TMP.TT_SPARK_FT_CLIENT_LAST_CALLED_90_DAYS
WHERE SITE_NAME IS NOT NULL
    AND NBR_CALLEE >= 3
    AND NBR_CALLEE <=150
    AND CALLER IS NOT NULL
    AND CALLEE_LIST IS NOT NULL
    