CREATE TABLE DD.SPARK_FT_RUPT_RETAILER_OM
(
    MOBILE_NUMBER    VARCHAR(250),
    PARTENAIRE    VARCHAR(250),
    SITE_NAME    VARCHAR(250),
    SITE_SOURCE    VARCHAR(250),
    STOCK     DECIMAL(17, 2),
    AVERAGE_HOUR_AMOUNT    DECIMAL(17, 2),
    RUPTURE_HOUR_MSISDN    INT,
    INSERT_DATE    TIMESTAMP
)
PARTITIONED BY (EVENT_DATE DATE, EVENT_TIME VARCHAR(250))
STORED AS PARQUET
TBLPROPERTIES ('PARQUET.COMPRESS'='SNAPPY')