CREATE TABLE MON.SPARK_FT_BDI_SF(
 msisdn VARCHAR(100),
 type_piece VARCHAR(100),
 numero_piece VARCHAR(100),
 nom_prenom VARCHAR(100),
 nom VARCHAR(100),
 prenom VARCHAR(100),
 date_naissance date,
 date_expiration date,
 adresse VARCHAR(100),
 numero_piece_tuteur VARCHAR(100),
 nom_parent VARCHAR(100),
 date_naissance_tuteur date,
 date_activation date,
 date_changement_statut date,
 statut_zsmart VARCHAR(100),
 imei VARCHAR(100),
 statut_derogation VARCHAR(100),
 region_administrative VARCHAR(100),
 region_commerciale VARCHAR(100),
 site_name VARCHAR(100),
 ville VARCHAR(100),
 longitude VARCHAR(100),
 latitude VARCHAR(100),
 offre_commerciale VARCHAR(100),
 type_contrat VARCHAR(100),
 segmentation VARCHAR(100),
 statut_in VARCHAR(100),
 numero_piece_absent VARCHAR(100),
 numero_piece_tut_absent VARCHAR(100),
 numero_piece_inf_4 VARCHAR(100),
 numero_piece_tut_inf_4 VARCHAR(100),
 numero_piece_non_authorise VARCHAR(100),
 numero_piece_tut_non_auth VARCHAR(100),
 numero_piece_egale_msisdn VARCHAR(100),
 numero_piece_tut_egale_msisdn VARCHAR(100),
 numero_piece_a_caract_non_auth VARCHAR(100),
 numero_piece_tut_carac_non_a VARCHAR(100),
 numero_piece_uniquement_lettre VARCHAR(100),
 numero_piece_tut_uniq_lettre VARCHAR(100),
 nom_prenom_absent VARCHAR(100),
 nom_parent_absent VARCHAR(100),
 nom_prenom_douteux VARCHAR(100),
 nom_parent_douteux VARCHAR(100),
 date_naissance_absent VARCHAR(100),
 date_naissance_tut_absent VARCHAR(100),
 date_expiration_absent VARCHAR(100),
 adresse_absent VARCHAR(100),
 adresse_douteuse VARCHAR(100),
 type_personne VARCHAR(100),
 date_naissance_douteux VARCHAR(100),
 date_naissance_tut_douteux VARCHAR(100),
 date_expiration_douteuse VARCHAR(100),
 cni_expire VARCHAR(100),
 est_suspendu VARCHAR(100),
 conforme_art VARCHAR(100),
 imei_absent VARCHAR(100),
 adresse_tuteur VARCHAR(100),
 type_piece_tuteur VARCHAR(100),
 acceptation_cgv VARCHAR(100),
 contrat_soucription VARCHAR(100),
 disponibilite_scan VARCHAR(100),
 plan_localisation VARCHAR(100),
 identificateur VARCHAR(100),
 profession_identificateur VARCHAR(100),
 motif_rejet_bo VARCHAR(100),
 est_conforme_maj_kyc VARCHAR(100),
 est_conforme_min_kyc VARCHAR(100),
 est_snappe VARCHAR(100),
 statut_validation_bo VARCHAR(100),
 part_msisdn VARCHAR(100),
 langue VARCHAR(100),
 insert_date TIMESTAMP) COMMENT 'MON.SPARK_FT_BDI_SF'
PARTITIONED BY (EVENT_DATE DATE)
STORED AS PARQUET TBLPROPERTIES ('PARQUET.COMPRESS'='SNAPPY');


TMP.SQ_SPARK_FT_BDI_SF
--staging table in DATALAKE
CREATE TABLE TMP.SQ_FT_BDI_SF(
 msisdn VARCHAR(100),
 type_piece VARCHAR(100),
 numero_piece VARCHAR(100),
 nom_prenom VARCHAR(100),
 nom VARCHAR(100),
 prenom VARCHAR(100),
 date_naissance date,
 date_expiration date,
 adresse VARCHAR(100),
 numero_piece_tuteur VARCHAR(100),
 nom_parent VARCHAR(100),
 date_naissance_tuteur date,
 date_activation date,
 date_changement_statut date,
 statut_zsmart VARCHAR(100),
 imei VARCHAR(100),
 statut_derogation VARCHAR(100),
 region_administrative VARCHAR(100),
 region_commerciale VARCHAR(100),
 site_name VARCHAR(100),
 ville VARCHAR(100),
 longitude VARCHAR(100),
 latitude VARCHAR(100),
 offre_commerciale VARCHAR(100),
 type_contrat VARCHAR(100),
 segmentation VARCHAR(100),
 statut_in VARCHAR(100),
 numero_piece_absent VARCHAR(100),
 numero_piece_tut_absent VARCHAR(100),
 numero_piece_inf_4 VARCHAR(100),
 numero_piece_tut_inf_4 VARCHAR(100),
 numero_piece_non_authorise VARCHAR(100),
 numero_piece_tut_non_auth VARCHAR(100),
 numero_piece_egale_msisdn VARCHAR(100),
 numero_piece_tut_egale_msisdn VARCHAR(100),
 numero_piece_a_caract_non_auth VARCHAR(100),
 numero_piece_tut_carac_non_a VARCHAR(100),
 numero_piece_uniquement_lettre VARCHAR(100),
 numero_piece_tut_uniq_lettre VARCHAR(100),
 nom_prenom_absent VARCHAR(100),
 nom_parent_absent VARCHAR(100),
 nom_prenom_douteux VARCHAR(100),
 nom_parent_douteux VARCHAR(100),
 date_naissance_absent VARCHAR(100),
 date_naissance_tut_absent VARCHAR(100),
 date_expiration_absent VARCHAR(100),
 adresse_absent VARCHAR(100),
 adresse_douteuse VARCHAR(100),
 type_personne VARCHAR(100),
 date_naissance_douteux VARCHAR(100),
 date_naissance_tut_douteux VARCHAR(100),
 date_expiration_douteuse VARCHAR(100),
 cni_expire VARCHAR(100),
 est_suspendu VARCHAR(100),
 conforme_art VARCHAR(100),
 imei_absent VARCHAR(100),
 adresse_tuteur VARCHAR(100),
 type_piece_tuteur VARCHAR(100),
 acceptation_cgv VARCHAR(100),
 contrat_soucription VARCHAR(100),
 disponibilite_scan VARCHAR(100),
 plan_localisation VARCHAR(100),
 identificateur VARCHAR(100),
 profession_identificateur VARCHAR(100),
 motif_rejet_bo VARCHAR(100),
 est_conforme_maj_kyc VARCHAR(100),
 est_conforme_min_kyc VARCHAR(100),
 est_snappe VARCHAR(100),
 statut_validation_bo VARCHAR(100),
 part_msisdn VARCHAR(100),
 langue VARCHAR(100),
 insert_date DATE,
 event_date DATE);


--Table in DHW
CREATE TABLE BDI_TEST.FT_BDI_PP(
  MSISDN                          VARCHAR2(50 BYTE),
  TYPE_PIECE                      VARCHAR2(100 BYTE),
  NUMERO_PIECE                    VARCHAR2(100 BYTE),
  NOM_PRENOM                      VARCHAR2(100 BYTE),
  NOM                             VARCHAR2(100 BYTE),
  PRENOM                          VARCHAR2(100 BYTE),
  DATE_NAISSANCE                  DATE,
  DATE_EXPIRATION                 DATE,
  ADRESSE                         VARCHAR2(100 BYTE),
  NUMERO_PIECE_TUTEUR             VARCHAR2(100 BYTE),
  NOM_PARENT                      VARCHAR2(100 BYTE),
  DATE_NAISSANCE_TUTEUR           DATE,
  DATE_ACTIVATION                 DATE,
  DATE_CHANGEMENT_STATUT          DATE,
  STATUT_ZSMART                   VARCHAR2(50 BYTE),
  IMEI                            VARCHAR2(50 BYTE),
  STATUT_DEROGATION               VARCHAR2(50 BYTE),
  REGION_ADMINISTRATIVE           VARCHAR2(100 BYTE),
  REGION_COMMERCIALE              VARCHAR2(100 BYTE),
  SITE_NAME                       VARCHAR2(100 BYTE),
  VILLE                           VARCHAR2(100 BYTE),
  LONGITUDE                       VARCHAR2(100 BYTE),
  LATITUDE                        VARCHAR2(100 BYTE),
  OFFRE_COMMERCIALE               VARCHAR2(100 BYTE),
  TYPE_CONTRAT                    VARCHAR2(100 BYTE),
  SEGMENTATION                    VARCHAR2(100 BYTE),
  STATUT_IN                       VARCHAR2(50 BYTE),
  NUMERO_PIECE_ABSENT             CHAR(3 BYTE),
  NUMERO_PIECE_TUT_ABSENT         CHAR(3 BYTE),
  NUMERO_PIECE_INF_4              CHAR(3 BYTE),
  NUMERO_PIECE_TUT_INF_4          CHAR(3 BYTE),
  NUMERO_PIECE_NON_AUTHORISE      CHAR(3 BYTE),
  NUMERO_PIECE_TUT_NON_AUTH       CHAR(3 BYTE),
  NUMERO_PIECE_EGALE_MSISDN       CHAR(3 BYTE),
  NUMERO_PIECE_TUT_EGALE_MSISDN   CHAR(3 BYTE),
  NUMERO_PIECE_A_CARACT_NON_AUTH  CHAR(3 BYTE),
  NUMERO_PIECE_TUT_CARAC_NON_A    CHAR(3 BYTE),
  NUMERO_PIECE_UNIQUEMENT_LETTRE  CHAR(3 BYTE),
  NUMERO_PIECE_TUT_UNIQ_LETTRE    CHAR(3 BYTE),
  NOM_PRENOM_ABSENT               CHAR(3 BYTE),
  NOM_PARENT_ABSENT               CHAR(3 BYTE),
  NOM_PRENOM_DOUTEUX              CHAR(3 BYTE),
  NOM_PARENT_DOUTEUX              CHAR(3 BYTE),
  DATE_NAISSANCE_ABSENT           CHAR(3 BYTE),
  DATE_NAISSANCE_TUT_ABSENT       CHAR(3 BYTE),
  DATE_EXPIRATION_ABSENT          CHAR(3 BYTE),
  ADRESSE_ABSENT                  CHAR(3 BYTE),
  ADRESSE_DOUTEUSE                CHAR(3 BYTE),
  TYPE_PERSONNE                   VARCHAR2(50 BYTE),
  DATE_NAISSANCE_DOUTEUX          CHAR(3 BYTE),
  DATE_NAISSANCE_TUT_DOUTEUX      CHAR(3 BYTE),
  DATE_EXPIRATION_DOUTEUSE        CHAR(3 BYTE),
  CNI_EXPIRE                      CHAR(3 BYTE),
  EST_SUSPENDU                    CHAR(5 BYTE),
  CONFORME_ART                    CHAR(5 BYTE),
  IMEI_ABSENT                     CHAR(5 BYTE),
  ADRESSE_TUTEUR                  VARCHAR2(100 BYTE),
  TYPE_PIECE_TUTEUR               VARCHAR2(100 BYTE),
  ACCEPTATION_CGV                 VARCHAR2(50 BYTE),
  CONTRAT_SOUCRIPTION             VARCHAR2(100 BYTE),
  DISPONIBILITE_SCAN              VARCHAR2(50 BYTE),
  PLAN_LOCALISATION               VARCHAR2(100 BYTE),
  IDENTIFICATEUR                  VARCHAR2(100 BYTE),
  PROFESSION_IDENTIFICATEUR       VARCHAR2(100 BYTE),
  MOTIF_REJET_BO                  VARCHAR2(200 BYTE),
  EST_CONFORME_MAJ_KYC            CHAR(3 BYTE),
  EST_CONFORME_MIN_KYC            CHAR(3 BYTE),
  EST_SNAPPE                      VARCHAR2(50 BYTE),
  STATUT_VALIDATION_BO            VARCHAR2(100 BYTE),
  PART_MSISDN                     VARCHAR2(10 BYTE),
  LANGUE                          VARCHAR2(50 BYTE),
  INSERT_DATE                     DATE,
  EVENT_DATE                      DATE
);

---staggin table in DWH
CREATE TABLE BDI_TEST.SQ_FT_BDI_PP(
  MSISDN                          VARCHAR2(50 BYTE),
  TYPE_PIECE                      VARCHAR2(100 BYTE),
  NUMERO_PIECE                    VARCHAR2(100 BYTE),
  NOM_PRENOM                      VARCHAR2(100 BYTE),
  NOM                             VARCHAR2(100 BYTE),
  PRENOM                          VARCHAR2(100 BYTE),
  DATE_NAISSANCE                  DATE,
  DATE_EXPIRATION                 DATE,
  ADRESSE                         VARCHAR2(100 BYTE),
  NUMERO_PIECE_TUTEUR             VARCHAR2(100 BYTE),
  NOM_PARENT                      VARCHAR2(100 BYTE),
  DATE_NAISSANCE_TUTEUR           DATE,
  DATE_ACTIVATION                 DATE,
  DATE_CHANGEMENT_STATUT          DATE,
  STATUT_ZSMART                   VARCHAR2(50 BYTE),
  IMEI                            VARCHAR2(50 BYTE),
  STATUT_DEROGATION               VARCHAR2(50 BYTE),
  REGION_ADMINISTRATIVE           VARCHAR2(100 BYTE),
  REGION_COMMERCIALE              VARCHAR2(100 BYTE),
  SITE_NAME                       VARCHAR2(100 BYTE),
  VILLE                           VARCHAR2(100 BYTE),
  LONGITUDE                       VARCHAR2(100 BYTE),
  LATITUDE                        VARCHAR2(100 BYTE),
  OFFRE_COMMERCIALE               VARCHAR2(100 BYTE),
  TYPE_CONTRAT                    VARCHAR2(100 BYTE),
  SEGMENTATION                    VARCHAR2(100 BYTE),
  STATUT_IN                       VARCHAR2(50 BYTE),
  NUMERO_PIECE_ABSENT             CHAR(3 BYTE),
  NUMERO_PIECE_TUT_ABSENT         CHAR(3 BYTE),
  NUMERO_PIECE_INF_4              CHAR(3 BYTE),
  NUMERO_PIECE_TUT_INF_4          CHAR(3 BYTE),
  NUMERO_PIECE_NON_AUTHORISE      CHAR(3 BYTE),
  NUMERO_PIECE_TUT_NON_AUTH       CHAR(3 BYTE),
  NUMERO_PIECE_EGALE_MSISDN       CHAR(3 BYTE),
  NUMERO_PIECE_TUT_EGALE_MSISDN   CHAR(3 BYTE),
  NUMERO_PIECE_A_CARACT_NON_AUTH  CHAR(3 BYTE),
  NUMERO_PIECE_TUT_CARAC_NON_A    CHAR(3 BYTE),
  NUMERO_PIECE_UNIQUEMENT_LETTRE  CHAR(3 BYTE),
  NUMERO_PIECE_TUT_UNIQ_LETTRE    CHAR(3 BYTE),
  NOM_PRENOM_ABSENT               CHAR(3 BYTE),
  NOM_PARENT_ABSENT               CHAR(3 BYTE),
  NOM_PRENOM_DOUTEUX              CHAR(3 BYTE),
  NOM_PARENT_DOUTEUX              CHAR(3 BYTE),
  DATE_NAISSANCE_ABSENT           CHAR(3 BYTE),
  DATE_NAISSANCE_TUT_ABSENT       CHAR(3 BYTE),
  DATE_EXPIRATION_ABSENT          CHAR(3 BYTE),
  ADRESSE_ABSENT                  CHAR(3 BYTE),
  ADRESSE_DOUTEUSE                CHAR(3 BYTE),
  TYPE_PERSONNE                   VARCHAR2(50 BYTE),
  DATE_NAISSANCE_DOUTEUX          CHAR(3 BYTE),
  DATE_NAISSANCE_TUT_DOUTEUX      CHAR(3 BYTE),
  DATE_EXPIRATION_DOUTEUSE        CHAR(3 BYTE),
  CNI_EXPIRE                      CHAR(3 BYTE),
  EST_SUSPENDU                    CHAR(5 BYTE),
  CONFORME_ART                    CHAR(5 BYTE),
  IMEI_ABSENT                     CHAR(5 BYTE),
  ADRESSE_TUTEUR                  VARCHAR2(100 BYTE),
  TYPE_PIECE_TUTEUR               VARCHAR2(100 BYTE),
  ACCEPTATION_CGV                 VARCHAR2(50 BYTE),
  CONTRAT_SOUCRIPTION             VARCHAR2(100 BYTE),
  DISPONIBILITE_SCAN              VARCHAR2(50 BYTE),
  PLAN_LOCALISATION               VARCHAR2(100 BYTE),
  IDENTIFICATEUR                  VARCHAR2(100 BYTE),
  PROFESSION_IDENTIFICATEUR       VARCHAR2(100 BYTE),
  MOTIF_REJET_BO                  VARCHAR2(200 BYTE),
  EST_CONFORME_MAJ_KYC            CHAR(3 BYTE),
  EST_CONFORME_MIN_KYC            CHAR(3 BYTE),
  EST_SNAPPE                      VARCHAR2(50 BYTE),
  STATUT_VALIDATION_BO            VARCHAR2(100 BYTE),
  PART_MSISDN                     VARCHAR2(10 BYTE),
  LANGUE                          VARCHAR2(50 BYTE),
  INSERT_DATE                     DATE,
  EVENT_DATE                      DATE
);