SELECT IF(FT_DATA_CONSO_MSISDN_DAY>0  AND FT_USERS_DATA_DAY=0, 'OK','NOK') STATUT FROM
(SELECT COUNT(*) FT_USERS_DATA_DAY FROM MON.SPARK_FT_USERS_DATA_DAY WHERE EVENT_DATE='###SLICE_VALUE###')A,
(SELECT COUNT(*) FT_DATA_CONSO_MSISDN_DAY FROM MON.SPARK_FT_DATA_CONSO_MSISDN_DAY WHERE EVENT_DATE='###SLICE_VALUE###')B