SELECT IF(T_1.IT_COUNT= 0 AND T_2.FT_MSC_TRANSACTION> 0 ,"OK","NOK") SITE_DAY_EXIST
FROM
    (SELECT COUNT(*) IT_COUNT FROM mon.SPARK_FT_PDM_OCM_SITE_DAY WHERE START_DATE='###SLICE_VALUE###') T_1,
    (SELECT COUNT(*) FT_MSC_TRANSACTION FROM MON.SPARK_FT_MSC_TRANSACTION WHERE transaction_date='###SLICE_VALUE###') T_2