INSERT INTO CDR.SPARK_IT_RAPPORT_DAILY PARTITION (DATE_SAISIE)
SELECT
ORIGINAL_FILE_NAME,
ORIGINAL_FILE_SIZE,
ORIGINAL_FILE_LINE_COUNT,
CODE_COMPTABLE,
MARCHE,
NUM_RECU,
TYPE_PAIEMENT,
TYPE_PAIEMENT_DETAIL,
MONTANT,
CODE_CLIENT,
ACCOUNT_NUMBER,
CUSTOMER_NAME,
INVOICE_NUMBER,
FROM_UNIXTIME(UNIX_TIMESTAMP(INVOICE_DATE,'yyyy/MM/dd'),'yyyy-MM-dd')INVOICE_DATE,
TYPE_CLIENT,
CUSTOMER_SEGMENT,
CHECK_NUMBER,
CREDIT_CARD_NUMBER,
BANK_DEPOSIT_NUMBER,
BANK_TRANSFER_NUMBER,
PAYMENT_METHON_NAME,
CURRENT_TIMESTAMP() INSERT_DATE,
TO_DATE(FROM_UNIXTIME(UNIX_TIMESTAMP(SUBSTRING(ORIGINAL_FILE_NAME, -19, 8),'yyyyMMdd'))) ORIGINAL_FILE_DATE,
FROM_UNIXTIME(UNIX_TIMESTAMP(DATE_SAISIE,'dd/MM/yyyy'),'yyyy-MM-dd')DATE_SAISIE
FROM CDR.TT_RAPPORT_DAILY C
LEFT JOIN (SELECT DISTINCT  ORIGINAL_FILE_NAME FILE_NAME FROM CDR.SPARK_IT_RAPPORT_DAILY)T ON T.FILE_NAME=C.ORIGINAL_FILE_NAME
WHERE T.FILE_NAME IS NULL