INSERT INTO MON.SPARK_FT_ROAMING_RETAIL_OUT_SUBS
SELECT 
E.nbr_subs nbr_subs,
E.subscription_service_details FORFAIT_ROAMING, 
E.subscription_channel SUBS_CHANNEL,
(E.SA *C.coef_voix) REVENU_VOIX, 
(E.SA *C.coef_sms) REVENU_SMS,
(E.SA *C.data_combo) REVENU_DATA_COMBO, 
(E.SA *C.data_pur) REVENU_DATA_PUR, 
E.SA REVENU_TOTAL,
"Week "||weekofyear(transaction_date) WEEK_OF_YEAR,
E.transaction_date EVENT_DATE

FROM
(SELECT A.transaction_date,count(A.served_party_msisdn) nbr_subs, A.subscription_service_details,A.subscription_channel, sum(rated_amount) SA
 FROM mon.spark_ft_subscription A 
 INNER JOIN dim.spark_dt_offer_profiles B ON upper(A.commercial_offer) = upper(B.profile_code)
 WHERE B.profile_code is not null
 AND A.transaction_date ='###SLICE_VALUE###' AND (upper(trim(subscription_service_details)) LIKE '%ROAMING%' OR 
 upper(trim(subscription_service_details)) IN ("IPP PREPAID PASS VOYAGE DECOUVERTE",
"IPP PREPAID PASS VOYAGE JOUR","IPP PREPAID PASS VOYAGE SEMAINE",
"IPP PREPAID PASS VOYAGE MOIS","IPP PREPAID 3G VOYAGE JOUR",
"IPP PREPAID 3G VOYAGE SEMAINE","IPP PREPAID 3G VOYAGE MOIS",
"IPP ROAMING VOICE FORTNIGHT SAUDI ARABIA","IPP ROAMING VOICE WEEK SAUDI ARABIA",
"IPP ROAMING DATA WEEK SAUDI ARABIA","IPP ROAMING VOICE MONTH SAUDI ARABIA",
"IPP ROAMING DATA FORTNIGHT SAUDI ARABIA","IPP ROAMING DATA MONTH SAUDI ARABIA",
"PREPAID_PASS ROAMING FRANCE SMS 3DAYS","PREPAID_PASS ROAMING FRANCE SMS WEEK",
"PREPAID_PASS ROAMING FRANCE VOICE&SMS 3DAYS","PREPAID_PASS ROAMING FRANCE VOICE&SMS WEEK",
"PREPAID_PASS ROAMING FRANCE VOICE 3DAYS","PREPAID_PASS ROAMING FRANCE VOICE WEEK",
"PREPAID_PASS ROAMING FRANCE DATA 3DAYS","PREPAID_PASS ROAMING FRANCE DATA WEEK",
"PREPAID_PASS ROAMING NIGERIA SMS 2DAYS","PREPAID_PASS ROAMING NIGERIA SMS WEEK",
"PREPAID_PASS ROAMING NIGERIA VOICE 2DAYS","PREPAID_PASS ROAMING NIGERIA VOICE WEEK",
"PREPAID_PASS ROAMING NIGERIA VOICE&SMS 2DAYS","PREPAID_PASS ROAMING NIGERIA VOICE&SMS WEEK",
"PREPAID_PASS ROAMING NIGERIA DATA 2DAYS","PREPAID_PASS ROAMING NIGERIA DATA WEEK",
"PREPAID_PASS ROAMING AFRIQUE MIXTE 3J","PREPAID_PASS ROAMING AFRIQUE MIXTE 7J",
"PREPAID_PASS ROAMING AFRIQUE VOIX_SMS 3J","PREPAID_PASS ROAMING AFRIQUE VOIX_SMS 7J",
"PREPAID_PASS ROAMING AFRIQUE INTERNET 3J","PREPAID_PASS ROAMING AFRIQUE INTERNET 7J",
"PREPAID_PASS ROAMING EUROPE MIXTE 3J","PREPAID_PASS ROAMING EUROPE MIXTE 7J",
"PREPAID_PASS ROAMING EUROPE VOIX_SMS 3J","PREPAID_PASS ROAMING EUROPE VOIX_SMS 7J",
"PREPAID_PASS ROAMING EUROPE INTERNET 3J","PREPAID_PASS ROAMING EUROPE INTERNET 7J",
"PREPAID_PASS ROAMING Canada MIXTE 3J","PREPAID_PASS ROAMING Canada MIXTE 7J",
"PREPAID_PASS ROAMING Canada VOIX_SMS 3J","PREPAID_PASS ROAMING Canada VOIX_SMS 7J",
"PREPAID_PASS ROAMING Amerique INTERNET 3J","PREPAID_PASS ROAMING Amerique INTERNET 7J",
"PREPAID_PASS ROAMING USA MIXTE 3J","PREPAID_PASS ROAMING USA MIXTE 7J",
"PREPAID_PASS ROAMING USA VOIX_SMS 3J","PREPAID_PASS ROAMING USA VOIX_SMS 7J",
"PREPAID_PASS ROAMING Moyen Orient MIXTE 3J","PREPAID_PASS ROAMING Moyen Orient  MIXTE 7J",
"PREPAID_PASS ROAMING Moyen Orient  VOIX_SMS 3J","PREPAID_PASS ROAMING Moyen Orient  VOIX_SMS 7J",
"PREPAID_PASS ROAMING Moyen Orient  INTERNET 3J","PREPAID_PASS ROAMING Moyen Orient  INTERNET 7J"))
 GROUP BY A.transaction_date, A.subscription_service_details,A.subscription_channel) E
INNER JOIN
(SELECT event,
  (nvl(VOIX_ONNET,0) + nvl(VOIX_OFFNET,0) + nvl(VOIX_INTER,0)+ nvl(VOIX_ROAMING,0)) coef_voix,
  (nvl(SMS_ONNET,0) +nvl(SMS_OFFNET,0)+nvl(SMS_INTER,0)+nvl(SMS_ROAMING,0)) coef_sms,
  (case when data_bundle != 1 then nvl(DATA_BUNDLE,0) else 0 end) data_combo,
  (case when  data_bundle = 1 then nvl(DATA_BUNDLE,0) else 0 end) data_pur
FROM dim.dt_services) C ON upper(trim(E.subscription_service_details)) = upper(trim(C.EVENT))
