CREATE TABLE MON.SPARK_FT_ROAMING_RETAIL_OUT_SUBS (
    MSISDN       VARCHAR (20),     
    FORFAIT_ROAMING VARCHAR(255), 
    SUBS_CHANNEL VARCHAR(255), 
    REVENU_VOIX  DECIMAL(20,5),
    REVENU_SMS DECIMAL(20,5),
    REVENU_DATA_COMBO DECIMAL(20,5),
    REVENU_DATA_PUR DECIMAL(20,5),
    REVENU_TOTAL DECIMAL(20,5)
)
COMMENT 'SPARK_FT_ROAMING_RETAIL_OUT_SUBS MON'
PARTITIONED BY (EVENT_DATE DATE)
STORED AS PARQUET TBLPROPERTIES ('PARQUET.COMPRESS'='SNAPPY')