SELECT IF(T_1.FT_EXIST = 0 and T_2.FT_SUBSCRIPTION > 0 ,"OK","NOK") FT_ROAM_EXIST
FROM
(SELECT COUNT(*) FT_EXIST FROM MON.SPARK_FT_ROAMING_RETAIL_OUT_SUBS WHERE EVENT_DATE = '###SLICE_VALUE###') T_1,
(SELECT COUNT(*) FT_SUBSCRIPTION FROM MON.SPARK_FT_SUBSCRIPTION WHERE TRANSACTION_DATE = '###SLICE_VALUE###') T_2