SELECT IF(T_1.FT_SITE_DAY_COUNT = 0 and T_2.FT_COUNT > 0 and T_3.FT_COUNT > 0,"OK","NOK") SITE_DAY_EXIST
FROM
    (SELECT COUNT(*) FT_SITE_DAY_COUNT FROM MON.SPARK_FT_SUBSCRIPTION_SITE_DAY WHERE EVENT_DATE='###SLICE_VALUE###') T_1,
    (SELECT COUNT(*) FT_COUNT FROM MON.SPARK_FT_SUBSCRIPTION WHERE TRANSACTION_DATE='###SLICE_VALUE###') T_2,
    (SELECT COUNT(*) FT_COUNT FROM MON.SPARK_FT_CLIENT_LAST_SITE_DAY WHERE EVENT_DATE='###SLICE_VALUE###') T_3