INSERT INTO DIM.DT_REF_CBM
select
MSISDN,
MULTI,
OPERATEUR,
TENURE,
SEGMENT,
REGION,
ZONE,
ORIGINAL_FILE_NAME,
ORIGINAL_FILE_SIZE,
ORIGINAL_FILE_LINE_COUNT,
CURRENT_TIMESTAMP INSERT_DATE,
substr(ORIGINAL_FILE_NAME,-10,6) ORIGINAL_FILE_DATE
from DIM.TT_REF_CBM C
LEFT JOIN (SELECT DISTINCT  ORIGINAL_FILE_NAME FILE_NAME FROM DIM.DT_REF_CBM)T ON T.FILE_NAME=C.ORIGINAL_FILE_NAME
WHERE T.FILE_NAME IS NULL