SELECT IF(T_1.FT_CON > 0 and T_2.TMP_AC = 0 ,"OK","NOK") TMP_ACQ_SNAP_MONTH
FROM
(SELECT COUNT(*) FT_CON FROM MON.SPARK_FT_CONTRACT_SNAPSHOT WHERE EVENT_DATE = DATE_ADD('###SLICE_VALUE###',1)) T_1,
(SELECT COUNT(*) TMP_AC FROM MON.SPARK_FT_TMP_ACQ_SNAP_MONTH WHERE EVENT_MONTH = SUBSTR('###SLICE_VALUE###',1,7) and ACTIVATION_DATE='###SLICE_VALUE###') T_2
