SELECT DISTINCT
TO_DATE(s_slice_value, 'yyyymmdd') EVENT_DATE
, a.MSISDN
, b.OSP_STATUS
, b.PROFILE
, b.ACTIVATION_DATE
, b.PROVISIONING_DATE
, b.DEACTIVATION_DATE
, NVL(b.MAIN_CREDIT, 0) MAIN_REMAINING_CREDIT
, NVL(b.PROMO_CREDIT,0) PROMO_REMAINING_CREDIT
, NVL(c.REIMBOURSMENT_AMOUNT,0) TOTAL_REIMBOURSMENT_AMOUNT
, NVL(c.REIMBOURSMENT_COUNT,0) TOTAL_REIMBOURSMENT_COUNT
, NVL(c.LOAN_AMOUNT,0) TOTAL_LOAN_AMOUNT
, NVL(c.LOAN_COUNT,0) TOTAL_LOAN_COUNT
, NVL(c.FEE_AMOUNT,0) TOTAL_PAYED_FEE_AMOUNT
, NVL(c.FEE_COUNT,0) TOTAL_PAYED_FEE_COUNT
, NVL(c.REIMBOURSMENT_AMOUNT,0) DAILY_REIMBOURSMENT_AMOUNT
, NVL(c.REIMBOURSMENT_COUNT,0) DAILY_REIMBOURSMENT_COUNT
, NVL(c.LOAN_AMOUNT,0) DAILY_LOAN_AMOUNT
, NVL(c.LOAN_COUNT,0) DAILY_LOAN_COUNT
, NVL(c.FEE_AMOUNT,0) DAILY_PAYED_FEE_AMOUNT
, NVL(c.FEE_COUNT,0) DAILY_PAYED_FEE_COUNT
, NVL((a.LOAN_AMOUNT),0) LOAN_AMOUNT
, NVL((a.LOAN_TO_PAY),0) LOAN_TO_PAY
, a.EC_DATE
, a.LAST_PAYMENT_DATE
, NVL(a.FEE_AMOUNT,0) DUE_FEE_AMOUNT
, a.EC_DATE ACTIVITY_BEGIN_DATE
, 'ZTE' SOURCE_PLATFORM
, 'IT_EC_EXTRACT' SOURCE_DATA
, SYSDATE
FROM (
    SELECT * FROM FT_LAST_UPDATE_EC_EXTRACT where EVENT_DATE = TO_DATE(s_next_value, 'yyyymmdd')
   /* SELECT a.*, ROW_NUMBER() OVER(PARTITION BY MSISDN ORDER BY EC_DATE DESC) AS RN
    FROM CDR.IT_EC_EXTRACT a WHERE a.ORIGINAL_FILE_DATE = TO_DATE(s_next_value, 'yyyymmdd')
    */
) a
, FT_CONTRACT_SNAPSHOT b
, (
    SELECT TRUNC(TRANSACTION_DATE) SDATE
        , SERVED_PARTY_MSISDN MSISDN
        , SUM(CASE WHEN OPERATION_TYPE = 'REIMBURSMENT' THEN NVL(LOAN_AMOUNT, 0) ELSE 0 END) REIMBOURSMENT_AMOUNT
        , SUM(CASE WHEN OPERATION_TYPE = 'REIMBURSMENT' THEN 1 ELSE 0 END) REIMBOURSMENT_COUNT
        , SUM(CASE WHEN OPERATION_TYPE = 'LOAN' THEN NVL(LOAN_AMOUNT, 0) ELSE 0 END) LOAN_AMOUNT
        , SUM(CASE WHEN OPERATION_TYPE = 'LOAN' THEN 1 ELSE 0 END) LOAN_COUNT
        , SUM(NVL(FEE,0)) FEE_AMOUNT
        , SUM(CASE WHEN NVL(FEE_FLAG, 'NO')='YES' THEN 1 ELSE 0 END) FEE_COUNT
    FROM FT_OVERDRAFT
    WHERE TRANSACTION_DATE BETWEEN TO_DATE(s_slice_value||' 000000', 'yyyymmdd hh24miss') AND TO_DATE(s_slice_value||' 235959', 'yyyymmdd hh24miss')
    GROUP BY TRUNC(TRANSACTION_DATE)
        , SERVED_PARTY_MSISDN
) c
WHERE --a.RN=1
b.EVENT_DATE = TO_DATE(s_contract_snapshot_date, 'yyyymmdd')
AND a.MSISDN = b.ACCESS_KEY(+)
AND a.MSISDN = c.MSISDN(+)
;
--