

SELECT IF(T1.LAST_UPDATE_EXISTS = 0 and T2.LAST_UPDATE_PREV_EXISTS>0 AND T3.CDR_EXISTS>0,"OK","NOK") FROM
(SELECT COUNT(*) LAST_UPDATE_EXISTS FROM MON.FT_LAST_UPDATE_EC_EXTRACT WHERE EVENT_DATE='###SLICE_VALUE###') T1,
(SELECT COUNT(*) LAST_UPDATE_PREV_EXISTS FROM MON.FT_LAST_UPDATE_EC_EXTRACT WHERE EVENT_DATE=DATE_SUB('###SLICE_VALUE###',1))T2,
(SELECT COUNT(*) CDR_EXISTS FROM CDR.IT_ZTE_EMERGENCY_DATA WHERE TRANSACTION_DATE='###SLICE_VALUE###')T3


