

SELECT IF(A.FT_EXIST = 0 and B.CONTRACT_SNAPSHOT_EXIST>0 AND T1.IT_EXISTS>0,"OK","NOK") FROM
(SELECT COUNT(*) FT_EXIST FROM MON.FT_EMERGENCY_DATA WHERE TRANSACTION_DATE='###SLICE_VALUE###') A,
(SELECT COUNT(*) CONTRACT_SNAPSHOT_EXIST FROM MON.FT_CONTRACT_SNAPSHOT WHERE EVENT_DATE='###SLICE_VALUE###')B,
(SELECT COUNT(*) IT_EXISTS FROM CDR.IT_ZTE_EMERGENCY_DATA WHERE TRANSACTION_DATE="###SLICE_VALUE###" AND ORIGINAL_FILE_DATE="###SLICE_VALUE###")T1


