
SELECT IF(T1.FT_EXISTS = 0 and T2.FT_PREV_EXISTS>0 AND T3.CONTRACT_SNAPSHOT_EXISTS>0 AND T4.FT_OVERDRAFT_EXISTS>0 AND T5.LAST_UPDATE_EXISTS>0,'OK','NOK') FROM
(SELECT COUNT(*) FT_EXISTS FROM MON.FT_EMERGENCY_CREDIT_ACTIVITY WHERE EVENT_DATE='###SLICE_VALUE###') T1,
(SELECT COUNT(*) FT_PREV_EXISTS FROM MON.FT_EMERGENCY_CREDIT_ACTIVITY WHERE EVENT_DATE=DATE_SUB('###SLICE_VALUE###',1)) T2,
(SELECT COUNT(*) CONTRACT_SNAPSHOT_EXISTS FROM MON.FT_CONTRACT_SNAPSHOT WHERE EVENT_DATE=DATE_SUB('###SLICE_VALUE###',-1))T3,
(SELECT COUNT(*) FT_OVERDRAFT_EXISTS FROM MON.FT_OVERDRAFT WHERE TRANSACTION_DATE='###SLICE_VALUE###')T4,
(SELECT COUNT(*) LAST_UPDATE_EXISTS FROM MON.FT_LAST_UPDATE_EC_EXTRACT WHERE EVENT_DATE='###SLICE_VALUE###')T5


