---***********************************************************---
------------    TT ZEBRA_MASTER  -------------------
---- ARNOLD CHUENFFO 06-02-2019
---***********************************************************---

CREATE EXTERNAL TABLE CDR.tt_zebra_master (
  ORIGINAL_FILE_NAME VARCHAR(200),
  ORIGINAL_FILE_SIZE INT,
  ORIGINAL_FILE_LINE_COUNT INT,
  CHANNEL_USER_ID  VARCHAR(20),
  PARENT_USER_ID  VARCHAR(20),
  OWNER_USER_ID  VARCHAR(20),
  USER_TYPE  VARCHAR(20),
  EXTERNAL_CODE  VARCHAR(20),
  PRIMARY_MSISDN  VARCHAR(20),
  USER_STATUS  VARCHAR(20),
  LOGIN_ID  VARCHAR(25),
  CATEGORY_CODE  VARCHAR(15),
  CATEGORY_NAME  VARCHAR(50),
  GEOGRAPHICAL_DOMAIN_CODE  VARCHAR(20),
  GEOGRAPHICAL_DOMAIN_NAME  VARCHAR(50),
  CHANNEL_USER_NAME  VARCHAR(80),
  CITY  VARCHAR(40),
  STATE  VARCHAR(20),
  COUNTRY  VARCHAR(40),
  DUMMY_C1  VARCHAR(40),
  DUMMY_C2  VARCHAR(40),
  DUMMY_C3  VARCHAR(40)
)
COMMENT 'external tables-TT'
ROW FORMAT DELIMITED FIELDS TERMINATED BY ','
LOCATION '/PROD/TT/ZEBRA/ZEBRA_MASTER'
TBLPROPERTIES ('serialization.null.format'='')
;