CREATE EXTERNAL TABLE CDR.SPARK_TT_GIMAC_AMA_DR (
    ORIGINAL_FILE_NAME VARCHAR(200),
    ORIGINAL_FILE_SIZE INT,
    ORIGINAL_FILE_LINE_COUNT INT,
    ISSUER_REF varchar(100),
    ACQUIRER_REF  varchar(100),
    WALLET_SOURCE  varchar(100),
    WALLET_DESTINATION  varchar(100),
    AMOUNT  varchar(100),
    STATUS varchar(100),
    ERROR_MESSAGE  varchar(100),
    TRANSFER_DATETIME varchar(100),
    ACCOUNTING_STATUS  varchar(100),
    CHARGEBACK_DATE varchar(100),
    TYPE varchar(100)
)
COMMENT 'external tables-TT'
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|'
LOCATION '/PROD/TT/AMA_DR'
TBLPROPERTIES ('serialization.null.format'='')
;

CREATE TABLE CDR.SPARK_IT_GIMAC_AMA_DR
(
    ISSUER_REF varchar(100),
    ACQUIRER_REF  varchar(100),
    WALLET_SOURCE  varchar(100),
    WALLET_DESTINATION  varchar(100),
    AMOUNT  varchar(100),
    STATUS varchar(100),
    ERROR_MESSAGE  varchar(100),
    TRANSFER_DATETIME varchar(100),
    ACCOUNTING_STATUS  varchar(100),
    CHARGEBACK_DATE varchar(100),
    TYPE varchar(100),
    ORIGINAL_FILE_NAME  VARCHAR(100),
    ORIGINAL_FILE_SIZE  INT,
    ORIGINAL_FILE_LINE_COUNT INT,
    INSERT_DATE TIMESTAMP
   )
  PARTITIONED BY (ORIGINAL_FILE_DATE DATE)
  STORED AS PARQUET
  TBLPROPERTIES ("parquet.compress"="SNAPPY");