SELECT IF(DATE_IS_PROCESSING=0  AND NOMAD>0 and max_PROCESSING_DATE<'###SLICE_VALUE###','OK','NOK' ) STATUS
FROM
(SELECT COUNT(*) DATE_IS_PROCESSING  FROM mon.backup_dt_base_identification WHERE PROCESSING_DATE = '###SLICE_VALUE###') a,
--(SELECT COUNT(*) IT_PREPAID_CLIENT  FROM cdr.SPARK_it_prepaid_client_directory WHERE ORIGINAL_FILE_DATE = '###SLICE_VALUE###') b,
--(SELECT COUNT(*) SNAP_ID FROM cdr.SPARK_IT_CLIENT_SNAPID_DIRECTORY WHERE ORIGINAL_FILE_DATE = DATE_SUB('###SLICE_VALUE###',1)) c,
(SELECT COUNT(*) NOMAD FROM cdr.SPARK_IT_NOMAD_CLIENT_DIRECTORY WHERE ORIGINAL_FILE_DATE = '###SLICE_VALUE###') d,
(SELECT max(PROCESSING_DATE) max_PROCESSING_DATE FROM mon.backup_dt_base_identification WHERE PROCESSING_DATE >=DATE_SUB('###SLICE_VALUE###',1)) e
