SELECT IF(
T_1.FT_EXIST = 0 AND
T_2.MSC_TRANS>0
,"OK","NOK") ACT_MONT_EXIST
FROM
(SELECT COUNT(*) FT_EXIST FROM MON.SPARK_FT_CALL_NEW_CUSTOMER_SERVICE WHERE TO_DATE(EVENT_DATE) = '###SLICE_VALUE###') T_1,
(SELECT COUNT(*) MSC_TRANS FROM MON.SPARK_FT_MSC_TRANSACTION WHERE TO_DATE(TRANSACTION_DATE) = '###SLICE_VALUE###') T_2