INSERT INTO MON.SPARK_FT_CALL_NEW_CUSTOMER_SERVICE
SELECT 
    SERVED_MSISDN,
    SERVED_IMSI,
    OTHER_PARTY,
    '###SLICE_VALUE###' EVENT_DATE
FROM
    MON.SPARK_FT_MSC_TRANSACTION
WHERE TRANSACTION_DATE = TO_DATE('###SLICE_VALUE###') AND OTHER_PARTY IN ('950', '951', '900' , '955')
AND SERVED_MSISDN NOT IN (
    SELECT SERVED_MSISDN FROM TMP.TT_CALL_NEW_CUSTOMER_SERVICE
) 
    