CREATE TABLE MON.COMPUTE_HISTORY
(
  JOB_INSTANCEID                  VARCHAR(1000),
  STATUS                          VARCHAR(100),
  INSERT_DATE                     TIMESTAMP
)
PARTITIONED BY (EVENT_DATE  VARCHAR(100))
STORED AS PARQUET TBLPROPERTIES ('PARQUET.COMPRESS'='SNAPPY')