SELECT IF(T_1.TMP_AC > 0 and T_2.RE_SC > 0 and T_3.RE_C2 > 0  and T_4.FT_AC = 0,"OK","NOK") TMP_ACTIVATION_MONTH
FROM
(SELECT COUNT(*) TMP_AC FROM MON.SPARK_TMP_ACTIVATION_MONTH WHERE EVENT_MONTH = SUBSTR('###SLICE_VALUE###',1,7) and ACTIVATION_DATE='###SLICE_VALUE###') T_1,
(SELECT COUNT(*) RE_SC FROM MON.SPARK_FT_REFILL WHERE REFILL_DATE = '###SLICE_VALUE###' and REFILL_MEAN='SCRATCH') T_2,
(SELECT COUNT(*) RE_C2 FROM MON.SPARK_FT_REFILL WHERE REFILL_DATE = '###SLICE_VALUE###' and REFILL_MEAN='C2S') T_3,
(SELECT COUNT(*) FT_AC FROM MON.SPARK_FT_ACTIVATION_MONTH1 WHERE EVENT_MONTH = SUBSTR('###SLICE_VALUE###',1,7) and ACTIVATION_DATE='###SLICE_VALUE###') T_4
