CREATE TABLE AGG.SPARK_FT_A_RAS_SF_S (
TRANSACTION_DATE DATE,
TRANSACTION_DURATION  DOUBLE,
TRANSACTION_TYPE     VARCHAR(40),
TRUNCK_IN    VARCHAR(50),
TRUNCK_OUT   VARCHAR(50),
TRUNCK2      VARCHAR(50),
INSERT_DATE TIMESTAMP
)
COMMENT ' SPARK_FT_A_RAS_SF_S '
 PARTITIONED BY (EVENT_DATE DATE)
 STORED AS PARQUET
 TBLPROPERTIES ("parquet.compress"="SNAPPY")