SELECT IF(T_1.FT_A_RAS_SF_S = 0 and T_2.FT_MSC_TRANSACTION > 1,"OK","NOK") FT_EXIST
FROM
    (SELECT COUNT(*) FT_A_RAS_SF_S FROM AGG.SPARK_FT_A_RAS_SF_S WHERE EVENT_DATE='###SLICE_VALUE###') T_1,
    (SELECT COUNT(*) FT_MSC_TRANSACTION FROM MON.SPARK_FT_MSC_TRANSACTION WHERE TRANSACTION_DATE='###SLICE_VALUE###') T_2