insert into DD.SPARK_FT_RECHARGE_BY_RETAILER
select
    A.MSISDN MSISDN 
    , A.CANAUX CANAUX 
    , A.DIRECTION DIRECTION
    , A.EVENT EVENT
    , A.CANAL_TYPE CANAL_TYPE
    , A.CANAL_EVENT CANAL_EVENT 
    , A.AMOUNT AMOUNT
    , A.COMMISSION COMMISSION
    , A.REVENUE REVENUE
    , A.TRANSACTION_COUNT TRANSACTION_COUNT
    , A.OTHER_PARTY_COUNT OTHER_PARTY_COUNT
    , A.SOURCE SOURCE
    , A.INSERT_DATE INSERT_DATE
    , A.CATEGORY_MSISDN CATEGORY_MSISDN
    , A.PARENT PARENT 
    , A.GRDPARENT GRDPARENT
    , A.PARTNER_NAME PARTNER_NAME
    , B.SITE_NAME SITE
    , A.REFILL_DATE REFILL_DATE
from (
    select
     MSISDN 
    , CANAUX 
    , DIRECTION
    , EVENT
    , CANAL_TYPE
    , CANAL_EVENT 
    , AMOUNT
    , COMMISSION
    , REVENUE
    , TRANSACTION_COUNT
    , OTHER_PARTY_COUNT
    , SOURCE
    , INSERT_DATE
    , REFILL_DATE
    , CATEGORY_MSISDN
    , PARENT 
    , GRDPARENT
    , PARTNER_NAME
    from DD.TMP_SPARK_FT_RECHARGE_BY_RETAILER
    where REFILL_DATE = '###SLICE_VALUE###') A
    left join
    (
        SELECT
        MSISDN,
        MAX(SITE_NAME) SITE_NAME
        FROM MON.SPARK_FT_CLIENT_LAST_SITE_DAY
        WHERE EVENT_DATE = '###SLICE_VALUE###'
        GROUP BY MSISDN
    ) B
on A.MSISDN = B.MSISDN