CREATE TABLE MON.SPARK_FT_SUBSCRIPTION_B2B (
    TRANSACTION_TIME  VARCHAR (6),
    SERVED_PARTY_MSISDN  VARCHAR (40),
    CONTRACT_TYPE   VARCHAR (50),
    COMMERCIAL_OFFER  VARCHAR (50),
    OPERATOR_CODE  VARCHAR (50),
    SUBSCRIPTION_CHANNEL  VARCHAR (50),
    SERVICE_LIST  VARCHAR (50),
    SUBSCRIPTION_SERVICE  VARCHAR (50),
    SUBSCRIPTION_SERVICE_DETAILS  VARCHAR (50),
    SUBSCRIPTION_RELATED_SERVICE  VARCHAR (50),
    RATED_AMOUNT    FLOAT,
    MAIN_BALANCE_USED  VARCHAR (10),
    ACTIVE_DATE  DATE,
    ACTIVE_TIME  VARCHAR (6),
    EXPIRE_DATE  DATE,
    EXPIRE_TIME  VARCHAR (6),
    SUBSCRIPTION_STATUS  VARCHAR (50),
    PREVIOUS_COMMERCIAL_OFFER  VARCHAR (50),
    PREVIOUS_STATUS  VARCHAR (50),
    PREVIOUS_SUBS_SERVICE_DETAILS  VARCHAR (50),
    PREVIOUS_SUBS_RELATED_SERVICE  VARCHAR (50),
    TERMINATION_INDICATOR  VARCHAR (50),
    BENEFIT_BALANCE_LIST  VARCHAR (1000),
    BENEFIT_UNIT_LIST  VARCHAR (255),
    BENEFIT_ADDED_VALUE_LIST  VARCHAR (1000),
    BENEFIT_RESULT_VALUE_LIST  VARCHAR (1000),
    BENEFIT_ACTIVE_DATE_LIST  VARCHAR (2000),
    BENEFIT_EXPIRE_DATE_LIST  VARCHAR (2000),
    TOTAL_OCCURENCE  INT,
    INSERT_DATE  TIMESTAMP,
    SOURCE_INSERT_DATE  DATE,
    ORIGINAL_FILE_NAME  VARCHAR (100),
    SERVICE_CODE  VARCHAR (50),
    AMOUNT_VOICE_ONNET  FLOAT,
    AMOUNT_VOICE_OFFNET  FLOAT,
    AMOUNT_VOICE_INTER  FLOAT,
    AMOUNT_VOICE_ROAMING  FLOAT,
    AMOUNT_SMS_ONNET  FLOAT,
    AMOUNT_SMS_OFFNET  FLOAT,
    AMOUNT_SMS_INTER  FLOAT,
    AMOUNT_SMS_ROAMING  FLOAT,
    AMOUNT_DATA  FLOAT,
    AMOUNT_SVA  FLOAT,
    COMBO VARCHAR (10),
    benefit_bal_list STRING
)
COMMENT 'ZTE Subscriptions B2B - FT'
PARTITIONED BY (TRANSACTION_DATE    DATE)
STORED AS PARQUET TBLPROPERTIES ('PARQUET.COMPRESS'='SNAPPY')


flux.sqoop.export-rdms.staging-table = "MON.SQ_FT_SUBSCRIPTION_B2B"
flux.sqoop.export-rdms.dest-table = "MON.FT_SUBSCRIPTION_B2B"
flux.sqoop.export-hive.staging-table = "SQ_FT_SUBSCRIPTION_B2B"


---Staging table in DWH
CREATE TABLE MON.SQ_FT_SUBSCRIPTION_B2B (
    TRANSACTION_TIME  VARCHAR (6),
    SERVED_PARTY_MSISDN  VARCHAR (40),
    CONTRACT_TYPE   VARCHAR (50),
    COMMERCIAL_OFFER  VARCHAR (50),
    OPERATOR_CODE  VARCHAR (50),
    SUBSCRIPTION_CHANNEL  VARCHAR (50),
    SERVICE_LIST  VARCHAR (50),
    SUBSCRIPTION_SERVICE  VARCHAR (50),
    SUBSCRIPTION_SERVICE_DETAILS  VARCHAR (50),
    SUBSCRIPTION_RELATED_SERVICE  VARCHAR (50),
    RATED_AMOUNT    FLOAT,
    MAIN_BALANCE_USED  VARCHAR (10),
    ACTIVE_DATE  DATE,
    ACTIVE_TIME  VARCHAR (6),
    EXPIRE_DATE  DATE,
    EXPIRE_TIME  VARCHAR (6),
    SUBSCRIPTION_STATUS  VARCHAR (50),
    PREVIOUS_COMMERCIAL_OFFER  VARCHAR (50),
    PREVIOUS_STATUS  VARCHAR (50),
    PREVIOUS_SUBS_SERVICE_DETAILS  VARCHAR (50),
    PREVIOUS_SUBS_RELATED_SERVICE  VARCHAR (50),
    TERMINATION_INDICATOR  VARCHAR (50),
    BENEFIT_BALANCE_LIST  VARCHAR (1000),
    BENEFIT_UNIT_LIST  VARCHAR (255),
    BENEFIT_ADDED_VALUE_LIST  VARCHAR (1000),
    BENEFIT_RESULT_VALUE_LIST  VARCHAR (1000),
    BENEFIT_ACTIVE_DATE_LIST  VARCHAR (2000),
    BENEFIT_EXPIRE_DATE_LIST  VARCHAR (2000),
    TOTAL_OCCURENCE  INT,
    INSERT_DATE  TIMESTAMP,
    SOURCE_INSERT_DATE  DATE,
    ORIGINAL_FILE_NAME  VARCHAR (100),
    SERVICE_CODE  VARCHAR (50),
    AMOUNT_VOICE_ONNET  FLOAT,
    AMOUNT_VOICE_OFFNET  FLOAT,
    AMOUNT_VOICE_INTER  FLOAT,
    AMOUNT_VOICE_ROAMING  FLOAT,
    AMOUNT_SMS_ONNET  FLOAT,
    AMOUNT_SMS_OFFNET  FLOAT,
    AMOUNT_SMS_INTER  FLOAT,
    AMOUNT_SMS_ROAMING  FLOAT,
    AMOUNT_DATA  FLOAT,
    AMOUNT_SVA  FLOAT,
    COMBO VARCHAR (10),
    benefit_bal_list VARCHAR(255),
    TRANSACTION_DATE    DATE
);




---Staging table in data lake
CREATE TABLE TMP.SQ_FT_SUBSCRIPTION_B2B(
    TRANSACTION_TIME  VARCHAR (6),
    SERVED_PARTY_MSISDN  VARCHAR (40),
    CONTRACT_TYPE   VARCHAR (50),
    COMMERCIAL_OFFER  VARCHAR (50),
    OPERATOR_CODE  VARCHAR (50),
    SUBSCRIPTION_CHANNEL  VARCHAR (50),
    SERVICE_LIST  VARCHAR (50),
    SUBSCRIPTION_SERVICE  VARCHAR (50),
    SUBSCRIPTION_SERVICE_DETAILS  VARCHAR (50),
    SUBSCRIPTION_RELATED_SERVICE  VARCHAR (50),
    RATED_AMOUNT    FLOAT,
    MAIN_BALANCE_USED  VARCHAR (10),
    ACTIVE_DATE  DATE,
    ACTIVE_TIME  VARCHAR (6),
    EXPIRE_DATE  DATE,
    EXPIRE_TIME  VARCHAR (6),
    SUBSCRIPTION_STATUS  VARCHAR (50),
    PREVIOUS_COMMERCIAL_OFFER  VARCHAR (50),
    PREVIOUS_STATUS  VARCHAR (50),
    PREVIOUS_SUBS_SERVICE_DETAILS  VARCHAR (50),
    PREVIOUS_SUBS_RELATED_SERVICE  VARCHAR (50),
    TERMINATION_INDICATOR  VARCHAR (50),
    BENEFIT_BALANCE_LIST  VARCHAR (1000),
    BENEFIT_UNIT_LIST  VARCHAR (255),
    BENEFIT_ADDED_VALUE_LIST  VARCHAR (1000),
    BENEFIT_RESULT_VALUE_LIST  VARCHAR (1000),
    BENEFIT_ACTIVE_DATE_LIST  VARCHAR (2000),
    BENEFIT_EXPIRE_DATE_LIST  VARCHAR (2000),
    TOTAL_OCCURENCE  INT,
    INSERT_DATE  TIMESTAMP,
    SOURCE_INSERT_DATE  DATE,
    ORIGINAL_FILE_NAME  VARCHAR (100),
    SERVICE_CODE  VARCHAR (50),
    AMOUNT_VOICE_ONNET  FLOAT,
    AMOUNT_VOICE_OFFNET  FLOAT,
    AMOUNT_VOICE_INTER  FLOAT,
    AMOUNT_VOICE_ROAMING  FLOAT,
    AMOUNT_SMS_ONNET  FLOAT,
    AMOUNT_SMS_OFFNET  FLOAT,
    AMOUNT_SMS_INTER  FLOAT,
    AMOUNT_SMS_ROAMING  FLOAT,
    AMOUNT_DATA  FLOAT,
    AMOUNT_SVA  FLOAT,
    COMBO VARCHAR (10),
    benefit_bal_list VARCHAR(255),
    TRANSACTION_DATE    DATE
);


DECLARE 
  SAMPLE_TABLE VARCHAR2(200); MIN_DATE_PARTITION VARCHAR2(200); MAX_DATE_PARTITION VARCHAR2(200);  KEY_COLUMN_PART_NAME VARCHAR2(200);
  KEY_COLUMN_PART_TYPE VARCHAR2(200);   PART_OWNER VARCHAR2(200);  PART_TABLE_NAME VARCHAR2(200);  PART_PARTITION_NAME VARCHAR2(200);
  PART_TYPE_PERIODE VARCHAR2(200);  PART_RETENTION NUMBER;  PART_TBS_CIBLE VARCHAR2(200);  PART_GARDER_01_DU_MOIS VARCHAR2(200);
PART_PCT_FREE NUMBER;   PART_COMPRESSION VARCHAR2(200);  PART_ROTATION_ACTIVE VARCHAR2(200);  PART_FORMAT VARCHAR2(200);
BEGIN 
  SAMPLE_TABLE := 'MON.SQ_FT_SUBSCRIPTION_B2B';
  MIN_DATE_PARTITION := '20220101';
  MAX_DATE_PARTITION := '20270101';
  KEY_COLUMN_PART_NAME := 'TRANSACTION_DATE';
  KEY_COLUMN_PART_TYPE := 'JOUR';
  PART_OWNER := 'MON';
  PART_TABLE_NAME := 'FT_SUBSCRIPTION_B2B';
  PART_PARTITION_NAME := 'FT_SUBSCRIPTION_B2B_';
  PART_TYPE_PERIODE := 'JOUR';
  PART_RETENTION := 1000;
  PART_TBS_CIBLE :=  'TAB_P_MON_J12_256M';
  PART_GARDER_01_DU_MOIS := 'NON';
  PART_PCT_FREE := 0;
  PART_COMPRESSION := 'COMPRESS';
  PART_ROTATION_ACTIVE := 'OUI';
  PART_FORMAT := 'yyyymmdd';
  MON.CREATE_PARTITIONED_TABLE ( SAMPLE_TABLE, MIN_DATE_PARTITION, MAX_DATE_PARTITION, KEY_COLUMN_PART_NAME, KEY_COLUMN_PART_TYPE, PART_OWNER, PART_TABLE_NAME, PART_PARTITION_NAME, PART_TYPE_PERIODE, PART_RETENTION, PART_TBS_CIBLE, PART_GARDER_01_DU_MOIS, PART_PCT_FREE, PART_COMPRESSION, PART_ROTATION_ACTIVE, PART_FORMAT );
  COMMIT; 
END;
