SELECT IF(T_1.FT_B2B_EXIST = 0 and T_2.FT_EXIST > 0 and T_3.FT_EXIST_1 >0,"OK","NOK") FT_SUBS_EXIST_B2B
FROM
(SELECT COUNT(*) FT_B2B_EXIST FROM MON.SPARK_SOLDE_CLIENT_B2B WHERE EVENT_DATE = '###SLICE_VALUE###') T_1,
(SELECT COUNT(*) FT_EXIST FROM MON.SPARK_FT_CONTRACT_SNAPSHOT WHERE EVENT_DATE = '###SLICE_VALUE###') T_2,
(SELECT COUNT(*) FT_EXIST_1 FROM CDR.SPARK_IT_ZTE_SUBS_EXTRACT  WHERE ORIGINAL_FILE_DATE = '###SLICE_VALUE###') T_3