SELECT IF(T_1.FT_B2B_EXIST = 0 and T_2.FT_EXIST > 0 ,"OK","NOK") FT_SUBS_EXIST_B2B
FROM
(SELECT COUNT(*) FT_B2B_EXIST FROM MON.SPARK_FT_SUBSCRIPTION_B2B WHERE TRANSACTION_DATE = '###SLICE_VALUE###') T_1,
(SELECT COUNT(*) FT_EXIST FROM MON.SPARK_FT_SUBSCRIPTION WHERE TRANSACTION_DATE = '###SLICE_VALUE###') T_2

