SELECT
    TRANSACTION_DATE `DATE`
    , TRANSACTION_DIRECTION SENS
    , TRANSACTION_TYPE TYPE
    , SERVED_MSISDN MSISDN_A
    , MAX(SERVED_IMEI) IMEI_A            
    , OTHER_PARTY MSISDN_B
    , SUM(NVL(TRANSACTION_DURATION,0)) DUREE
    , COUNT(1) NOMBRE
    , MAX(SERVED_PARTY_LOCATION) LOCATION_MSISDN_A
FROM MON.SPARK_FT_MSC_TRANSACTION
WHERE TRANSACTION_DATE = '###SLICE_VALUE###'
GROUP BY TRANSACTION_DATE
    , TRANSACTION_DIRECTION
    , TRANSACTION_TYPE
    , SERVED_MSISDN
    , OTHER_PARTY