SELECT
    EVENT_DATE
    , MSISDN
    , BYTES_USED_IN_BUNDLE
    , BYTES_USED_OUT_BUNDLE
    , (MAIN_RATED_AMOUNT  - ( GOS_DEBIT_AMOUNT + GOS_REFUND_AMOUNT +  GOS_SESSION_AMOUNT)) MAIN_RATED_AMOUNT_PYG
    , (GOS_DEBIT_AMOUNT + GOS_REFUND_AMOUNT +  GOS_SESSION_AMOUNT) MAIN_RATED_AMOUNT_GOS_SVA
FROM MON.SPARK_FT_DATA_CONSO_MSISDN_DAY
WHERE EVENT_DATE = '###SLICE_VALUE###'
