SELECT 
    regexp_replace(from_unixtime(unix_timestamp(TRANSACTION_DATE ,'yyyy-MM-dd'), 'dd-MM-yyyy'),'-','/')  AS `DATE`,
    SERVED_PARTY_MSISDN AS MSISDN,
    OPERATION_TYPE AS OPERATION_TYPE,
    REIMBURSMENT_CHANNEL AS REIMBURSMENT_CHANNEL,
    SUM(LOAN_AMOUNT) AS LOAN_AMOUNT,
    SUM(REFILL_AMOUNT) AS REFILL_AMOUNT,
    SUM(FEE) AS FEE,
    COUNT(*) AS TRANSACTION_COUNT
FROM MON.SPARK_FT_OVERDRAFT
WHERE TRANSACTION_DATE='###SLICE_VALUE###'
GROUP BY regexp_replace(from_unixtime(unix_timestamp(TRANSACTION_DATE ,'yyyy-MM-dd'), 'dd-MM-yyyy'),'-','/')
    ,OPERATION_TYPE
    ,REIMBURSMENT_CHANNEL
    ,SERVED_PARTY_MSISDN 