SELECT
    SERVED_PARTY_MSISDN beneficiaire
    , NOM nom_beneficiaire
    , PRENOM prenom_beneficiaire
    , SUBSCRIPTION_SERVICE_DETAILS bundle_name
    , PRIX bdle_cost
    , COUNT(*) nber_purchase
    , CURRENT_TIMESTAMP() insert_date
    , '###SLICE_VALUE###' transaction_date
FROM
(
    SELECT
        SERVED_PARTY_MSISDN
        , SUBSCRIPTION_SERVICE_DETAILS
    FROM MON.SPARK_FT_SUBSCRIPTION
    WHERE TRANSACTION_DATE = '###SLICE_VALUE###' AND SUBSCRIPTION_CHANNEL = '32'
) A
LEFT JOIN DIM.DT_BASE_IDENTIFICATION B
ON A.SERVED_PARTY_MSISDN=B.MSISDN
LEFT JOIN DIM.DT_CBM_REF_SOUSCRIPTION_PRICE C
ON UPPER(A.SUBSCRIPTION_SERVICE_DETAILS) = UPPER(C.BDLE_NAME)
GROUP BY SERVED_PARTY_MSISDN
    , NOM
    , PRENOM
    , SUBSCRIPTION_SERVICE_DETAILS
    , PRIX
