SELECT IF(A.FT_EXIST = 0 and B.CONTRACT_SNAPSHOT_EXIST>0 AND MAX_SEQUENCE=FILE_COUNTER,"OK","NOK") FROM
(SELECT COUNT(*) FT_EXIST FROM MON.FT_EMERGENCY_DATA WHERE TRANSACTION_DATE='###SLICE_VALUE###') A,
(SELECT COUNT(*) CONTRACT_SNAPSHOT_EXIST FROM MON.FT_CONTRACT_SNAPSHOT WHERE EVENT_DATE='###SLICE_VALUE###')B,
(SELECT MAX(CAST(SEQUENCE AS INT)) MAX_SEQUENCE, COUNT(DISTINCT ORIGINAL_FILE_NAME) FILE_COUNTER FROM (
        SELECT SUBSTRING(ORIGINAL_FILE_NAME,-19,6) SEQUENCE ,ORIGINAL_FILE_NAME FROM  CDR.IT_ZTE_EMERGENCY_DATA WHERE TRANSACTION_DATE="###SLICE_VALUE###" AND ORIGINAL_FILE_DATE="###SLICE_VALUE###"
    )T1)T2


