insert into tt.subscription_ipp
SELECT 
    IPP_NAME,
    MAX(IPP_AMOUNT) AMOUNT_VIA_OM_VAS
FROM CDR.SPARK_IT_ZTE_IPP_EXTRACT IPP_EXTRACT
WHERE IPP_EXTRACT.ORIGINAL_FILE_DATE IN (SELECT MAX(ORIGINAL_FILE_DATE) ORIGINAL_FILE_DATE FROM CDR.SPARK_IT_ZTE_IPP_EXTRACT)
GROUP BY IPP_NAME