insert into tt.subscription_price_plan
SELECT 
    NVL(PRICE_PLAN_CODE, 'UNKNOWN') PRICE_PLAN_CODE , 
    MIN(PRICE_PLAN_NAME) PRICE_PLAN_NAME
FROM CDR.SPARK_IT_ZTE_PRICE_PLAN_EXTRACT
WHERE ORIGINAL_FILE_DATE = '###SLICE_VALUE###'
GROUP BY NVL(PRICE_PLAN_CODE, 'UNKNOWN') 