SELECT IF(A.FT_EXIST = 0 AND B.FT_BILLED_TRANSACTION_PREPAID_EXIST>0,"OK","NOK") FROM
(SELECT COUNT(*) FT_EXIST FROM MON.SPARK_FT_SUBSCRIBER_LOCATION WHERE EVENT_DATE='###SLICE_VALUE###') A,
(SELECT COUNT(*) FT_BILLED_TRANSACTION_PREPAID_EXIST FROM MON.SPARK_FT_BILLED_TRANSACTION_PREPAID WHERE TRANSACTION_DATE='###SLICE_VALUE###')B
