INSERT INTO AGG.SPARK_FT_GLOBAL_ACTIVITY_DAILY PARTITION(TRANSACTION_DATE)
SELECT
    UPPER(OFFER_PROFILE_CODE) COMMERCIAL_OFFER_CODE
     ,'SOS_DATA' TRANSACTION_TYPE
     ,'MAIN' SUB_ACCOUNT
     ,'-' TRANSACTION_SIGN
     , 'ZTE' SOURCE_PLATFORM
     ,'FT_EMERGENCY_DATA'  SOURCE_DATA
     , 'IN_TRAFFIC' SERVED_SERVICE
     , 'NVX_SOS_DATA' SERVICE_CODE
     , 'DEST_ND' DESTINATION_CODE
     , NULL SERVED_LOCATION
     ,'HIT' MEASUREMENT_UNIT
     , SUM (1) RATED_COUNT
     , SUM (1) RATED_VOLUME
     , SUM (AMOUNT) TAXED_AMOUNT
     , SUM ((1-0.1925) *AMOUNT) UNTAXED_AMOUNT
     , CURRENT_TIMESTAMP INSERT_DATE
     ,'REVENUE' TRAFFIC_MEAN
     , OPERATOR_CODE OPERATOR_CODE
     , NULL LOCATION_CI
     , TRANSACTION_DATE TRANSACTION_DATE
FROM MON.SPARK_FT_EMERGENCY_DATA
WHERE TRANSACTION_DATE = '###SLICE_VALUE###' AND NVL(TRANSACTION_TYPE,'ND') ='LOAN'
GROUP BY
    UPPER(OFFER_PROFILE_CODE)
       , OPERATOR_CODE
       , TRANSACTION_DATE

UNION

SELECT
    UPPER(OFFER_PROFILE_CODE) COMMERCIAL_OFFER_CODE
     ,'SOS_VOICE' TRANSACTION_TYPE
     ,'MAIN' SUB_ACCOUNT
     ,'-' TRANSACTION_SIGN
     , 'ZTE' SOURCE_PLATFORM
     ,'ZTE_LOAN_CDR'  SOURCE_DATA
     , 'IN_TRAFFIC' SERVED_SERVICE
     , 'NVX_SOS_VOICE' SERVICE_CODE
     , 'DEST_ND' DESTINATION_CODE
     , NULL SERVED_LOCATION
     ,'HIT' MEASUREMENT_UNIT
     , SUM (1) RATED_COUNT
     , SUM (1) RATED_VOLUME
     , SUM (AMOUNT) TAXED_AMOUNT
     , SUM ((1-0.1925) *AMOUNT) UNTAXED_AMOUNT
     , CURRENT_TIMESTAMP INSERT_DATE
     ,'REVENUE' TRAFFIC_MEAN
     , NULL OPERATOR_CODE
     , NULL LOCATION_CI
     , EVENT_DATE TRANSACTION_DATE
FROM
(
    SELECT OFFER_PROFILE_CODE
        , SUM(AMOUNT) AMOUNT
        , SUM(FEE) FEE
        , EVENT_DATE 
    FROM
    (
        SELECT MSISDN
            , AMOUNT/100 AMOUNT
            , FEE/100 FEE
        FROM CDR.SPARK_IT_ZTE_LOAN_CDR
        WHERE ORIGINAL_FILE_DATE = '###SLICE_VALUE###' AND NVL(TRANSACTION_TYPE,'ND') ='LOAN'
    ) A 
    LEFT JOIN 
    (
        SELECT ACCESS_KEY MSISDN
            , NVL(PROFILE, OSP_CUSTOMER_FORMULE) OFFER_PROFILE_CODE
            , EVENT_DATE
        FROM MON.SPARK_FT_CONTRACT_SNAPSHOT 
        WHERE EVENT_DATE = '###SLICE_VALUE###' AND OSP_STATUS <> 'TERMINATED'
    ) B ON IF(regexp_replace( a.MSISDN,"^(237)+(?!$)","")='237',NULL,regexp_replace( A.MSISDN,"^(237)+(?!$)",""))= B.MSISDN
    GROUP BY OFFER_PROFILE_CODE
        , EVENT_DATE
)
GROUP BY
    UPPER(OFFER_PROFILE_CODE)
    , EVENT_DATE

UNION

SELECT
    UPPER(OFFER_PROFILE_CODE) COMMERCIAL_OFFER_CODE
     ,'FEES_SOS_DATA' TRANSACTION_TYPE
     ,'MAIN' SUB_ACCOUNT
     ,'-' TRANSACTION_SIGN
     , 'ZTE' SOURCE_PLATFORM
     ,'FT_EMERGENCY_DATA'  SOURCE_DATA
     , 'IN_TRAFFIC' SERVED_SERVICE
     , 'NVX_FEES_SOS_DATA' SERVICE_CODE
     , 'DEST_ND' DESTINATION_CODE
     , NULL SERVED_LOCATION
     ,'HIT' MEASUREMENT_UNIT
     , SUM (1) RATED_COUNT
     , SUM (1) RATED_VOLUME
     , SUM (BYTES_OBTAINED)/100 TAXED_AMOUNT -- il y avait eu une confusion dans le nom de la colone, c'est bien les fees qui sont dans bytes_obtained
     , SUM ((1-0.1925) *BYTES_OBTAINED)/100 UNTAXED_AMOUNT
     , CURRENT_TIMESTAMP INSERT_DATE
     ,'REVENUE' TRAFFIC_MEAN
     , NULL OPERATOR_CODE
     , NULL LOCATION_CI
     , TRANSACTION_DATE
FROM MON.SPARK_FT_EMERGENCY_DATA
WHERE TRANSACTION_DATE = '###SLICE_VALUE###' AND NVL(TRANSACTION_TYPE,'ND') ='PAYBACK'
GROUP BY
    UPPER(OFFER_PROFILE_CODE)
       , TRANSACTION_DATE

UNION

SELECT
    UPPER(OFFER_PROFILE_CODE) COMMERCIAL_OFFER_CODE
     ,'FEES_SOS_VOICE' TRANSACTION_TYPE
     ,'MAIN' SUB_ACCOUNT
     ,'-' TRANSACTION_SIGN
     , 'ZTE' SOURCE_PLATFORM
     ,'ZTE_LOAN_CDR'  SOURCE_DATA
     , 'IN_TRAFFIC' SERVED_SERVICE
     , 'NVX_FEES_SOS_VOICE' SERVICE_CODE
     , 'DEST_ND' DESTINATION_CODE
     , NULL SERVED_LOCATION
     ,'HIT' MEASUREMENT_UNIT
     , SUM (1) RATED_COUNT
     , SUM (1) RATED_VOLUME
     , SUM (FEE) TAXED_AMOUNT
     , SUM ((1-0.1925) *FEE) UNTAXED_AMOUNT
     , CURRENT_TIMESTAMP INSERT_DATE
     ,'REVENUE' TRAFFIC_MEAN
     , NULL OPERATOR_CODE
     , NULL LOCATION_CI
     , EVENT_DATE TRANSACTION_DATE
FROM
(
    SELECT OFFER_PROFILE_CODE
        , SUM(AMOUNT) AMOUNT
        , SUM(FEE) FEE
        , EVENT_DATE 
    FROM
    (
        SELECT MSISDN
            , AMOUNT/100 AMOUNT
            , FEE/100 FEE
        FROM CDR.SPARK_IT_ZTE_LOAN_CDR
        WHERE ORIGINAL_FILE_DATE = '###SLICE_VALUE###' AND NVL(TRANSACTION_TYPE,'ND') ='PAYBACK'
    ) A 
    LEFT JOIN 
    (
        SELECT ACCESS_KEY MSISDN
            , NVL(PROFILE, OSP_CUSTOMER_FORMULE) OFFER_PROFILE_CODE
            , EVENT_DATE
        FROM MON.SPARK_FT_CONTRACT_SNAPSHOT 
        WHERE EVENT_DATE = '###SLICE_VALUE###' AND OSP_STATUS <> 'TERMINATED'
    ) B ON IF(regexp_replace( a.MSISDN,"^(237)+(?!$)","")='237',NULL,regexp_replace( A.MSISDN,"^(237)+(?!$)",""))= B.MSISDN
    GROUP BY OFFER_PROFILE_CODE
        , EVENT_DATE
)
GROUP BY
    UPPER(OFFER_PROFILE_CODE)
    , EVENT_DATE