CREATE TABLE AGG.SPARK_FT_A_REPORTING_INTERCO_INTERNATIONAL (
    MON VARCHAR(400),
    USER_TYPE VARCHAR(400),
    CARRIER VARCHAR(400),
    COUNTRY VARCHAR(400),
    OPERATOR VARCHAR(400),
    SERVICE_TYPE VARCHAR(400),
    CALL_DIRECTION VARCHAR(400),
    NBR_TRANSACTION VARCHAR(400),
    CALL_DURATION VARCHAR(400),
    INSERT_DATE TIMESTAMP
)
PARTITIONED BY (PROCESSING_DATE DATE)
STORED AS PARQUET
TBLPROPERTIES ("parquet.compress"="SNAPPY")