SELECT IF(
    A.EXIST_RECYCLES_DAILY = 0 AND 
    B.EXIST_ZTE_SUBS_EXTRACT > 0 AND 
    C.EXIST_ZTE_PROD_EXTRACT > 0,"OK","NOK") 
FROM
(SELECT COUNT(*) EXIST_RECYCLES_DAILY FROM MON.SPARK_FT_CBM_RECYCLES_DAILY WHERE recyclage_date = '###SLICE_VALUE###') A,
(SELECT COUNT(DISTINCT ORIGINAL_FILE_DATE) EXIST_ZTE_SUBS_EXTRACT FROM CDR.SPARK_IT_ZTE_SUBS_EXTRACT WHERE ORIGINAL_FILE_DATE = '###SLICE_VALUE###') B, 
(SELECT COUNT(DISTINCT ORIGINAL_FILE_DATE) EXIST_ZTE_PROD_EXTRACT FROM CDR.SPARK_IT_ZTE_PROD_EXTRACT WHERE  original_file_date=date_add('###SLICE_VALUE###', 1)) C