SELECT IF(T_1.SPOOL_COUNT = 0 AND T_2.IT_COUNT > 0, "OK", "NOK") FT_EXIST
FROM
    (SELECT COUNT(*) SPOOL_COUNT FROM SPOOL.SPOOL_ECRITURE_APGL WHERE EVENT_DATE='###SLICE_VALUE###') T_1,
    (SELECT COUNT(*) IT_COUNT FROM CDR.SPARK_IT_OM_APGL WHERE TRANSACTION_DATE='###SLICE_VALUE###') T_2
