CREATE TABLE CDR.SPARK_IT_ZTE_RECURRING (
ACC_NBR VARCHAR(16),
EVENT_TIME TIMESTAMP,
RECURRING_TYPE  VARCHAR(10),
CYCLE_BEGIN_DATE TIMESTAMP,
CYCLE_END_DATE  TIMESTAMP,
EVENT_COST_LIST VARCHAR(255),
ACCT_ID VARCHAR(20),
EVENT_COST_RES_LIST VARCHAR(255),
BENEFIT_BAL_LIST VARCHAR(500),
BAL_UPDATE_DATE TIMESTAMP,
PROD_SPEC_CODE VARCHAR(10),
PRICE_PLAN_CODE VARCHAR(10),
ORIGINAL_FILE_NAME VARCHAR(50),
ORIGINAL_FILE_DATE DATE,
ORIGINAL_FILE_SIZE INT,
ORIGINAL_FILE_LINE_COUNT INT,
INSERT_DATE TIMESTAMP
)
PARTITIONED BY (EVENT_DATE DATE,FILE_DATE DATE)
CLUSTERED BY(RECURRING_TYPE,PROD_SPEC_CODE,PRICE_PLAN_CODE) INTO 5 BUCKETS
STORED AS PARQUET TBLPROPERTIES ('PARQUET.COMPRESS'='SNAPPY');
