add jar hdfs:///PROD/UDF/hive-udf-1.0.1.jar;
create temporary function FN_NNP_SIMPLE_DESTINATION as 'cm.orange.bigdata.udf.GetNnpSimpleDestn';
insert into  tmp.msisdn_vue_360
SELECT
    NVL(a.MSISDN, b.MSISDN) AS MSISDN,
    CONTRACT_TYPE,
    COMMERCIAL_OFFER,
    ACTIVATION_DATE,
    DEACTIVATION_DATE,
    LANG,
    OSP_STATUS,
    IMSI,
    GRP_LAST_OG_CALL,
    GRP_LAST_IC_CALL,
    GRP_REMAIN_CREDIT_MAIN,
    GRP_REMAIN_CREDIT_PROMO,
    GRP_GP_STATUS,
    DIR_FIRST_NAME,
    DIR_LAST_NAME,
    DIR_BIRTH_DATE,
    DIR_IDENTIFICATION_TOWN,
    DIR_IDENTIFICATION_DATE,
    NVL(EST_PRESENT_DANS_ACCOUNT_ACTIVITY,'NON') EST_PRESENT_DANS_ACCOUNT_ACTIVITY,
    NVL(EST_PRESENT_DANS_DT_BASE_IDENTIF,'NON') EST_PRESENT_DANS_DT_BASE_IDENTIF,
    NVL(EST_PRESENT_DANS_MSC,'NON') EST_PRESENT_DANS_MSC
FROM
(
    SELECT
        NVL(a.MSISDN, b.MSISDN) AS MSISDN,
        CONTRACT_TYPE,
        COMMERCIAL_OFFER,
        ACTIVATION_DATE,
        DEACTIVATION_DATE,
        LANG,
        OSP_STATUS,
        IMSI,
        GRP_LAST_OG_CALL,
        GRP_LAST_IC_CALL,
        GRP_REMAIN_CREDIT_MAIN,
        GRP_REMAIN_CREDIT_PROMO,
        GRP_GP_STATUS,
        EST_PRESENT_DANS_ACCOUNT_ACTIVITY
    FROM
    (
        -- infos generales
        SELECT ACCESS_KEY MSISDN,
            OSP_CONTRACT_TYPE CONTRACT_TYPE,
            COMMERCIAL_OFFER,
            ACTIVATION_DATE,
            DEACTIVATION_DATE,
            LANG,
            OSP_STATUS,
            MAIN_IMSI IMSI
        FROM MON.FT_CONTRACT_SNAPSHOT
        WHERE EVENT_DATE = DATE_ADD('2019-10-04',1)
            AND OSP_STATUS IN ('ACTIVE', 'INACTIVE')
    ) a
    FULL JOIN
    (
        -- infos groupe
        SELECT
            MSISDN,
            OG_CALL GRP_LAST_OG_CALL,
            IC_CALL_4 GRP_LAST_IC_CALL,
            REMAIN_CREDIT_MAIN GRP_REMAIN_CREDIT_MAIN,
            REMAIN_CREDIT_PROMO GRP_REMAIN_CREDIT_PROMO,
            GP_STATUS GRP_GP_STATUS,
            'OUI' EST_PRESENT_DANS_ACCOUNT_ACTIVITY
        FROM MON.FT_ACCOUNT_ACTIVITY
        WHERE EVENT_DATE = DATE_ADD('2019-10-04',1)
    ) b  ON a.MSISDN = b.MSISDN
) a
FULL JOIN (
    SELECT
         NVL(a.MSISDN,b.MSISDN) MSISDN,
         DIR_FIRST_NAME,
         DIR_LAST_NAME,
         DIR_BIRTH_DATE,
         DIR_IDENTIFICATION_TOWN,
         DIR_IDENTIFICATION_DATE,
         EST_PRESENT_DANS_DT_BASE_IDENTIF,
         EST_PRESENT_DANS_MSC
    FROM
    (
        SELECT
            MSISDN,
            PRENOM AS DIR_FIRST_NAME,
            NOM AS DIR_LAST_NAME,
            NEE_LE AS DIR_BIRTH_DATE,
            VILLE_VILLAGE AS DIR_IDENTIFICATION_TOWN,
            TO_DATE(DATE_IDENTIFICATION) AS DIR_IDENTIFICATION_DATE,
            'OUI' EST_PRESENT_DANS_DT_BASE_IDENTIF
        FROM MON.BACKUP_DT_BASE_IDENTIFICATION WHERE PROCESSING_DATE='2019-10-04'
    )a
    FULL JOIN (
        SELECT
            MSISDN,
            'OUI' EST_PRESENT_DANS_MSC
        FROM MON.FT_OG_IC_CALL_SNAPSHOT
        WHERE EVENT_DATE='2019-10-04' AND FN_NNP_SIMPLE_DESTINATION (MSISDN)='OCM'
    )b on a.MSISDN = b.MSISDN
)b on a.MSISDN = b.MSISDN
WHERE  NVL(a.MSISDN, b.MSISDN) IS NOT NULL