CREATE TABLE tmp.msisdn_vue_360_1 AS 
SELECT 
    a.*,
    NVL(DATA_MAIN_RATED_AMOUNT, 0) + NVL(DATA_PROMO_RATED_AMOUNT, 0) AS TOTAL_DATA_REVENUE,
    NVL(DATA_ROAM_MAIN_RATED_AMOUNT, 0) + NVL(DATA_ROAM_PROMO_RATED_AMOUNT, 0) AS ROAM_DATA_REVENUE,
    DATA_MAIN_RATED_AMOUNT,
    DATA_GOS_MAIN_RATED_AMOUNT,
    DATA_PROMO_RATED_AMOUNT,
    DATA_ROAM_MAIN_RATED_AMOUNT,
    DATA_ROAM_PROMO_RATED_AMOUNT,
    DATA_BYTES_RECEIVED,
    DATA_BYTES_SENT,
    DATA_BYTES_USED_IN_BUNDLE,
    DATA_BYTES_USED_PAYGO,
    DATA_BYTES_USED_IN_BUNDLE_ROAM,
    DATA_BYTE_USED_OUT_BUNDLE_ROAM,
    DATA_MMS_USED,
    DATA_MMS_USED_IN_BUNDLE
FROM tmp.msisdn_vue_360 a
LEFT JOIN (
    SELECT
        MSISDN,
        NVL(MAIN_RATED_AMOUNT, 0) AS DATA_MAIN_RATED_AMOUNT,
        NVL(GOS_DEBIT_AMOUNT, 0) AS DATA_GOS_MAIN_RATED_AMOUNT,
        NVL(PROMO_RATED_AMOUNT, 0) AS DATA_PROMO_RATED_AMOUNT,
        NVL(MAIN_RATED_AMOUNT_ROAMING, 0) AS DATA_ROAM_MAIN_RATED_AMOUNT,
        NVL(PROMO_RATED_AMOUNT_ROAMING, 0) AS DATA_ROAM_PROMO_RATED_AMOUNT,
        NVL(BYTES_RECEIVED, 0) AS DATA_BYTES_RECEIVED,
        NVL(BYTES_SENT, 0) AS DATA_BYTES_SENT,
        NVL(BYTES_USED_IN_BUNDLE, 0) AS DATA_BYTES_USED_IN_BUNDLE,
        NVL(BYTES_USED_OUT_BUNDLE, 0) AS DATA_BYTES_USED_PAYGO,
        NVL(BYTES_USED_IN_BUNDLE_ROAMING, 0) AS DATA_BYTES_USED_IN_BUNDLE_ROAM,
        NVL(BYTES_USED_OUT_BUNDLE_ROAMING, 0) AS DATA_BYTE_USED_OUT_BUNDLE_ROAM,
        NVL(MMS_COUNT, 0) AS DATA_MMS_USED,
        NVL(BUNDLE_MMS_USED_VOLUME, 0) AS DATA_MMS_USED_IN_BUNDLE
    FROM MON.FT_DATA_CONSO_MSISDN_DAY
    WHERE EVENT_DATE = '2019-10-04' 
)b on a.MSISDN = b.MSISDN