CREATE TABLE tmp.msisdn_vue_360_6 AS
SELECT
    a.*,
    TOTAL_SUBS_REVENUE,
    SUBS_AUTRES_COUNT,
    SUBS_AUTRES_AMOUNT,
    SUBS_VOICE_COUNT,
    SUBS_SMS_COUNT,
    SUBS_DATA_COUNT,
    SUBS_VOICE_AMOUNT,
    SUBS_SMS_AMOUNT,
    SUBS_DATA_AMOUNT,
    DATA_VIA_OM
FROM tmp.msisdn_vue_360_4 a
LEFT JOIN
(
    SELECT
        MSISDN,
        nvl(TOTAL_SUBS_AMOUNT, 0) AS TOTAL_SUBS_REVENUE
    FROM MON.FT_SUBSCRIPTION_MSISDN_DAY
    WHERE EVENT_DATE = '2019-10-04'
)b on a.MSISDN=b.MSISDN
LEFT JOIN (
     -- Souscriptions
    SELECT
        MSISDN,
        SUM(CASE WHEN UPPER(USAGE_MKT) = 'AUTRES' THEN NBRE_SUBS ELSE 0 END)  AS SUBS_AUTRES_COUNT,
        SUM(CASE WHEN UPPER(USAGE_MKT) = 'AUTRES' THEN RATED_AMOUNT ELSE 0 END) AS SUBS_AUTRES_AMOUNT,
        SUM(CASE WHEN UPPER(USAGE_MKT) = 'VOIX' THEN NBRE_SUBS ELSE 0 END) AS SUBS_VOICE_COUNT,
        SUM(CASE WHEN UPPER(USAGE_MKT) = 'SMS' THEN NBRE_SUBS ELSE 0 END) AS SUBS_SMS_COUNT,
        SUM(CASE WHEN UPPER(USAGE_MKT) = 'DATA' THEN NBRE_SUBS ELSE 0 END) AS SUBS_DATA_COUNT,
        SUM(CASE WHEN UPPER(USAGE_MKT) = 'VOIX' THEN RATED_AMOUNT ELSE 0 END) AS SUBS_VOICE_AMOUNT,
        SUM(CASE WHEN UPPER(USAGE_MKT) = 'SMS' THEN RATED_AMOUNT ELSE 0 END) AS SUBS_SMS_AMOUNT,
        SUM(CASE WHEN UPPER(USAGE_MKT) = 'DATA' THEN RATED_AMOUNT ELSE 0 END) AS SUBS_DATA_AMOUNT,
        SUM(DATA_VIA_OM) AS DATA_VIA_OM
    FROM
    (
        SELECT
            MSISDN,
            nvl(USAGE_MKT, 'AUTRES') AS USAGE_MKT,
            SUM(TOTAL_OCCURENCE) AS NBRE_SUBS,
            SUM(RATED_AMOUNT) AS RATED_AMOUNT,
            SUM(CASE WHEN SUBSCRIPTION_CHANNEL='32' THEN RATED_AMOUNT ELSE 0 END )DATA_VIA_OM
        FROM
        (
            SELECT 
                SERVED_PARTY_MSISDN AS MSISDN, 
                SUBSCRIPTION_SERVICE_DETAILS, 
                TOTAL_OCCURENCE, 
                RATED_AMOUNT,
                SUBSCRIPTION_CHANNEL
            FROM MON.FT_SUBSCRIPTION
            WHERE TRANSACTION_DATE = '2019-10-04'
        ) a
        LEFT JOIN
        (
            SELECT EVENT, USAGE_MKT
            FROM DIM.DT_SERVICES
        ) b
            ON a.SUBSCRIPTION_SERVICE_DETAILS = b.EVENT
        GROUP BY MSISDN, nvl(USAGE_MKT, 'AUTRES')
    )a GROUP BY MSISDN
)c on a.MSISDN=c.MSISDN