INSERT INTO MON.SPARK_FT_CLIENT_360
SELECT
    MSISDN,
    NULL DATE_PREMIERE_ACTIVATION,
    TYPE_PIECE,
    NUMERO_PIECE,
    SEX,
    DIR_FIRST_NAME,
    DIR_LAST_NAME,
    DATE_NAISSANCE,
    LANG,
    DATE_EXPIRATION,
    ADDRESSE,
    NUMERO_PIECE_TUTEUR,
    NOM_PARENT,
    DATE_NAISSANCE_TUTEUR,
    NOM_STRUCTURE,
    NUMERO_REGISTRE_COMMERCE,
    NUMERO_PIECE_REP_LEGAL,
    DIR_IDENTIFICATION_TOWN,
    DIR_IDENTIFICATION_DATE,
    ACTIVATION_DATE,
    DEACTIVATION_DATE,
    DATE_CHANGEMENT_STATUT,
    STATUT_DEROGATION,
    STATUT_BSCS,
    OSP_STATUS,
    ODBINCOMINGCALLS,
    ODBOUTGOINGCALLS,
    REGION_ADMINISTRATIVE,
    REGION_COMMERCIALE,
    SITE_NAME,
    VILLE,
    LONGITUDE,
    LATITUDE,
    OFFRE_COMMERCIALE,
    TYPE_CONTRAT,
    SEGMENTATION,
    IMSI,
    IMEI,
    DATA_VIA_OM,
    TER_TAC_CODE,
    TER_CONSTRUCTOR,
    TER_MODEL,
    TER_2G_3G_4G_COMPATIBILITY,
    TER_2G_COMPATIBILITY,
    TER_3G_COMPATIBILITY,
    TER_4G_COMPATIBILITY,
    GRP_GP_STATUS,
    GRP_LAST_OG_CALL,
    GRP_LAST_IC_CALL,
    GRP_REMAIN_CREDIT_MAIN,
    GRP_REMAIN_CREDIT_PROMO,
    DATA_MAIN_RATED_AMOUNT,
    DATA_GOS_MAIN_RATED_AMOUNT,
    DATA_PROMO_RATED_AMOUNT,
    DATA_ROAM_MAIN_RATED_AMOUNT,
    DATA_ROAM_PROMO_RATED_AMOUNT,
    DATA_BYTES_RECEIVED,
    DATA_BYTES_SENT,
    DATA_BYTES_USED_IN_BUNDLE,
    DATA_BYTES_USED_PAYGO,
    DATA_BYTES_USED_IN_BUNDLE_ROAM,
    DATA_BYTE_USED_OUT_BUNDLE_ROAM,
    DATA_MMS_USED,
    DATA_MMS_USED_IN_BUNDLE,
    SOS_LOAN_COUNT,
    SOS_LOAN_AMOUNT,
    SOS_REIMBURSEMENT_COUNT,
    SOS_REIMBURSEMENT_AMOUNT,
    SOS_FEES,
    TOTAL_REVENUE,
    TOTAL_VOICE_REVENUE,
    TOTAL_SMS_REVENUE,
    TOTAL_SUBS_REVENUE,
    C2S_REFILL_COUNT,
    C2S_MAIN_REFILL_AMOUNT,
    C2S_PROMO_REFILL_AMOUNT,
    P2P_REFILL_COUNT,
    P2P_REFILL_AMOUNT,
    P2P_REFILL_FEES,
    SCRATCH_REFILL_COUNT,
    SCRATCH_MAIN_REFILL_AMOUNT,
    SCRATCH_PROMO_REFILL_AMOUNT,
    TOTAL_DATA_REVENUE,
    ROAM_DATA_REVENUE,
    ROAM_IN_VOICE_REVENUE,
    ROAM_OUT_VOICE_REVENUE,
    ROAM_IN_SMS_REVENUE,
    ROAM_OUT_SMS_REVENUE,
    OG_CALL_TOTAL_COUNT,
    OG_CALL_OCM_COUNT,
    OG_CALL_MTN_COUNT,
    OG_CALL_NEXTTEL_COUNT,
    OG_CALL_CAMTEL_COUNT,
    OG_CALL_SET_COUNT,
    OG_CALL_ROAM_IN_COUNT,
    OG_CALL_ROAM_OUT_COUNT,
    OG_CALL_SVA_COUNT,
    OG_CALL_INTERNATIONAL_COUNT,
    OG_RATED_CALL_DURATION,
    OG_TOTAL_CALL_DURATION,
    RATED_TEL_OCM_DURATION,
    RATED_TEL_MTN_DURATION,
    RATED_TEL_NEXTTEL_DURATION,
    RATED_TEL_CAMTEL_DURATION,
    RATED_TEL_SET_DURATION,
    RATED_TEL_ROAM_IN_DURATION,
    RATED_TEL_ROAM_OUT_DURATION,
    RATED_TEL_SVA_DURATION,
    RATED_TEL_INT_DURATION,
    MAIN_RATED_TEL_AMOUNT,
    PROMO_RATED_TEL_AMOUNT,
    OG_TOTAL_RATED_CALL_AMOUNT,
    MAIN_RATED_TEL_OCM_AMOUNT,
    MAIN_RATED_TEL_MTN_AMOUNT,
    MAIN_RATED_TEL_NEXTTEL_AMOUNT,
    MAIN_RATED_TEL_CAMTEL_AMOUNT,
    MAIN_RATED_TEL_SET_AMOUNT,
    MAIN_RATED_TEL_ROAM_IN_AMOUNT,
    MAIN_RATED_TEL_ROAM_OUT_AMOUNT,
    MAIN_RATED_TEL_SVA_AMOUNT,
    MAIN_RATED_TEL_INT_AMOUNT,
    PROMO_RATED_TEL_OCM_AMOUNT,
    PROMO_RATED_TEL_MTN_AMOUNT,
    PROMO_RATED_TEL_NEXTTEL_AMOUNT,
    PROMO_RATED_TEL_CAMTEL_AMOUNT,
    PROMO_RATED_TEL_SET_AMOUNT,
    PROMO_RATED_TEL_ROAMIN_AMOUNT,
    PROMO_RATED_TEL_ROAMOUT_AMOUNT,
    PROMO_RATED_TEL_INT_AMOUNT,
    OG_SMS_TOTAL_COUNT,
    OG_SMS_OCM_COUNT,
    OG_SMS_MTN_COUNT,
    OG_SMS_NEXTTEL_COUNT,
    OG_SMS_CAMTEL_COUNT,
    OG_SMS_SET_COUNT,
    OG_SMS_ROAM_IN_COUNT,
    OG_SMS_ROAM_OUT_COUNT,
    OG_SMS_SVA_COUNT,
    OG_SMS_INTERNATIONAL_COUNT,
    MAIN_RATED_SMS_AMOUNT,
    MAIN_RATED_SMS_OCM_AMOUNT,
    MAIN_RATED_SMS_MTN_AMOUNT,
    MAIN_RATED_SMS_NEXTTEL_AMOUNT,
    MAIN_RATED_SMS_CAMTEL_AMOUNT,
    MAIN_RATED_SMS_SET_AMOUNT,
    MAIN_RATED_SMS_ROAM_IN_AMOUNT,
    MAIN_RATED_SMS_ROAM_OUT_AMOUNT,
    MAIN_RATED_SMS_SVA_AMOUNT,
    MAIN_RATED_SMS_INT_AMOUNT,
    SUBS_BUNDLE_PLENTY_COUNT,
    SUBS_ORANGE_BONUS_COUNT,
    SUBS_FNF_MODIFY_COUNT,
    SUBS_DATA_2G_COUNT,
    SUBS_DATA_3G_JOUR_COUNT,
    SUBS_DATA_3G_SEMAINE_COUNT,
    SUBS_DATA_3G_MOIS_COUNT,
    SUBS_MAXI_BONUS_COUNT,
    SUBS_PRO_COUNT,
    SUBS_INTERN_JOUR_COUNT,
    SUBS_INTERN_SEMAINE_COUNT,
    SUBS_INTERN_MOIS_COUNT,
    SUBS_PACK_SMS_JOUR_COUNT,
    SUBS_PACK_SMS_SEMAINE_COUNT,
    SUBS_PACK_SMS_MOIS_COUNT,
    SUBS_WS_COUNT,
    SUBS_OBONUS_ILLIMITE_COUNT,
    SUBS_ORANGE_PHENIX_COUNT,
    SUBS_RECHARGE_PLENTY_COUNT,
    SUBS_AUTRES_COUNT,
    SUBS_DATA_FLYBOX_COUNT,
    SUBS_DATA_AUTRES_COUNT,
    SUBS_ROAMING_COUNT,
    SUBS_SMS_AUTRES_COUNT,
    SUBS_BUNDLE_PLENTY_AMOUNT,
    SUBS_ORANGE_BONUS_AMOUNT,
    SUBS_FNF_MODIFY_AMOUNT,
    SUBS_DATA_2G_AMOUNT,
    SUBS_DATA_3G_JOUR_AMOUNT,
    SUBS_DATA_3G_SEMAINE_AMOUNT,
    SUBS_DATA_3G_MOIS_AMOUNT,
    SUBS_MAXI_BONUS_AMOUNT,
    SUBS_PRO_AMOUNT,
    SUBS_INTERN_JOUR_AMOUNT,
    SUBS_INTERN_SEMAINE_AMOUNT,
    SUBS_INTERN_MOIS_AMOUNT,
    SUBS_PACK_SMS_JOUR_AMOUNT,
    SUBS_PACK_SMS_SEMAINE_AMOUNT,
    SUBS_PACK_SMS_MOIS_AMOUNT,
    SUBS_WS_AMOUNT,
    SUBS_OBONUS_ILLIMITE_AMOUNT,
    SUBS_ORANGE_PHENIX_AMOUNT,
    SUBS_RECHARGE_PLENTY_AMOUNT,
    SUBS_AUTRES_AMOUNT,
    SUBS_DATA_FLYBOX_AMOUNT,
    SUBS_DATA_AUTRES_AMOUNT,
    SUBS_ROAMING_AMOUNT,
    SUBS_SMS_AUTRES_AMOUNT,
    SUBS_VOICE_COUNT,
    SUBS_SMS_COUNT,
    SUBS_DATA_COUNT,
    SUBS_VOICE_AMOUNT,
    SUBS_SMS_AMOUNT,
    SUBS_DATA_AMOUNT,
    REVENU_MOYEN,
    PREMIUM,
    CONSO_MOY_DATA,
    RECHARGE_MOY,
    PREMIUM_PLUS,
    STATUT_IN,
    NUMERO_PIECE_ABSENT,
    NUMERO_PIECE_TUT_ABSENT,
    NUMERO_PIECE_INF_4,
    NUMERO_PIECE_TUT_INF_4,
    NUMERO_PIECE_NON_AUTHORISE,
    NUMERO_PIECE_TUT_NON_AUTH,
    NUMERO_PIECE_EGALE_MSISDN,
    NUMERO_PIECE_TUT_EGALE_MSISDN,
    NUMERO_PIECE_A_CARACT_NON_AUTH,
    NUMERO_PIECE_TUT_CARAC_NON_A,
    NUMERO_PIECE_UNIQUEMENT_LETTRE,
    NUMERO_PIECE_TUT_UNIQ_LETTRE,
    NOM_ABSENT,
    NOM_PARENT_ABSENT,
    NOM_DOUTEUX,
    NOM_PARENT_DOUTEUX,
    DATE_NAISSANCE_ABSENT,
    DATE_NAISSANCE_TUT_ABSENT,
    DATE_EXPIRATION_ABSENT,
    ADDRESSE_ABSENT,
    ADDRESSE_DOUTEUSE,
    TYPE_PERSONNE_INCONNU,
    MINEUR_MAL_IDENTIFIE,
    TYPE_PERSONNE,
    NULL DATE_ACQUISITION, -- A REVOIR
    DATE_NAISSANCE_DOUTEUX,
    DATE_NAISSANCE_TUT_DOUTEUX,
    DATE_EXPIRATION_DOUTEUSE,
    CNI_EXPIRE,
    MULTI_SIM,
    NULL EST_PRESENT_OM,-- A REVOIR
    EST_PRESENT_ZEB,
    EST_PRESENT_ART,
    EST_PRESENT_GP,
    EST_PRESENT_OCM,
    NULL EST_ACTIF_OM,-- A REVOIR
    EST_CLIENT_VIP,
    NULL EST_ACTIF_DATA,-- A REVOIR
    CONFORM_OCM_P_MORALE_M2M,
    CONFORM_ART_P_MORALE_M2M,
    CONFORM_OCM_P_MORALE_FLOTTE,
    CONFORM_ART_P_MORALE_FLOTTE,
    CONFORM_OCM_P_PHY_MAJEUR,
    CONFORM_ART_P_PHY_MAJEUR,
    CONFORM_OCM_P_PHY_MINEUR,
    CONFORM_ART_P_PHY_MINEUR,
    EST_SUSPENDU,
    NOM_STRUCTURE_ABSENT,
    NUMERO_REGISTRE_ABSENT,
    NUMERO_REGISTRE_DOUTEUX,
    CONFORME_ART,
    CONFORME_OCM,
    IMEI_ABSENT,
    ADRESSE_ABSENT, ---SERT A QUOI?????????? IL Y'A DEJA ADDRESSE_ABSENT
    EST_PREMIUM,
    ADRESSE_TUTEUR,
    TYPE_PIECE_TUTEUR,
    ACCEPTATION_CGV,
    CONTRAT_SOUCRIPTION,
    DISPONIBILITE_SCAN,
    PLAN_LOCALISATION,
    PROFESSION_IDENTIFIER,
    DATE_VALIDATION_BO,
    STATUT_VALIDATION_BO,
    MOTIF_REJET_BO,
    STATUT_VALIDATION_BOO,

    -- DISTRIBUTION
    INSCRIPTEUR,
    MIDATEDEP,
    MTT_DEPOT,
    NB_DEPOT,
    IDSPEC,
    FIRSTDEPOT,
    FIRSTTRAN,
    DEST_TRAN,
    SERV_TRAN,
    MIDATETR,
    MTT_TRANS,
    NB_TRANSACTION,
    REG_LEVEL,
    SEUIL_OK,
    AUTO_INSCRIPTION,
    BOUCLE_P2P,
    DOUBLE_PROFIL,
    BOUCLE,
    CONFORMITE,

    --SOS CREDIT
    ED_AMOUNT,
    ED_TRANSACTION_TYPE,
    ED_BYTES_OBTAINED,
    ED_CONTACT_CHANNEL,
    --OMNY
    OMNY_TRANSACTION_AMOUNT,
    OMNY_COMMISSIONS_PAID,
    OMNY_COMMISSIONS_RECEIVED,
    OMNY_COMMISSIONS_OTHERS,
    OMNY_SERVICE_CHARGE_RECEIVED,
    OMNY_SERVICE_CHARGE_PAID,
    OMNY_TAXES,
    OMNY_SERVICE_TYPE,
    OMNY_SENDER_PRE_BAL,
    OMNY_SENDER_POST_BAL,
    OMNY_RECEIVER_PRE_BAL,
    OMNY_RECEIVER_POST_BAL,
    CURRENT_TIMESTAMP() INSERT_DATE,
    '###SLICE_VALUE###' EVENT_DATE
FROM (
    SELECT
        A.MSISDN MSISDN,--OKAY
        A.CONTRACT_TYPE,--NOT_USED
        A.COMMERCIAL_OFFER,--NOT_USED
        A.ACTIVATION_DATE,--OKAY
        A.DEACTIVATION_DATE,--OKAY
        A.LANG,--OKAY
        A.OSP_STATUS,--OKAY
        A.IMSI,--OKAY
        A.GRP_LAST_OG_CALL,--OKAY
        A.GRP_LAST_IC_CALL,--OKAY
        A.GRP_REMAIN_CREDIT_MAIN,--OKAY
        A.GRP_REMAIN_CREDIT_PROMO,--OKAY
        A.GRP_GP_STATUS,--OKAY
        A.DIR_FIRST_NAME,--OKAY
        A.DIR_LAST_NAME,--OKAY
        A.DIR_BIRTH_DATE,--NOT_USED
        A.DIR_IDENTIFICATION_TOWN,--OKAY
        A.DIR_IDENTIFICATION_DATE,--OKAY
        A.PROFESSION_IDENTIFICATEUR PROFESSION_IDENTIFIER,--OKAY
        A.SEX,--OKAY
        --A.EST_PRESENT_DANS_ACCOUNT_ACTIVITY,--NOT_USED
        --A.EST_PRESENT_DANS_DT_BASE_IDENTIF,--NOT_USED
        --A.EST_PRESENT_DANS_MSC,--NOT_USED
        A.TYPE_PIECE,--OKAY
        A.NUMERO_PIECE,--OKAY
        A.DATE_NAISSANCE,--OKAY
        NVL(B.DATA_MAIN_RATED_AMOUNT, 0) + NVL(B.DATA_PROMO_RATED_AMOUNT, 0) AS TOTAL_DATA_REVENUE,--A_VERIFIER
        NVL(B.DATA_ROAM_MAIN_RATED_AMOUNT, 0) + NVL(B.DATA_ROAM_PROMO_RATED_AMOUNT, 0) AS ROAM_DATA_REVENUE,--A_VERIFIER
        B.DATA_MAIN_RATED_AMOUNT,--A_VERIFIER
        B.DATA_GOS_MAIN_RATED_AMOUNT,--A_VERIFIER
        B.DATA_PROMO_RATED_AMOUNT,--A_VERIFIER
        B.DATA_ROAM_MAIN_RATED_AMOUNT,--A_VERIFIER
        B.DATA_ROAM_PROMO_RATED_AMOUNT,--A_VERIFIER
        B.DATA_BYTES_RECEIVED,--OKAY
        B.DATA_BYTES_SENT,--OKAY
        B.DATA_BYTES_USED_IN_BUNDLE,--OKAY
        B.DATA_BYTES_USED_PAYGO,--OKAY
        B.DATA_BYTES_USED_IN_BUNDLE_ROAM,--OKAY
        B.DATA_BYTE_USED_OUT_BUNDLE_ROAM,--OKAY
        B.DATA_MMS_USED,--OKAY
        B.DATA_MMS_USED_IN_BUNDLE,--OKAY
        G.TOTAL_SUBS_REVENUE,--OKAY
        NVL(C.TOTAL_VOICE_REVENUE, 0) + NVL(C.TOTAL_SMS_REVENUE, 0) + NVL(G.TOTAL_SUBS_REVENUE, 0) + NVL(B.DATA_MAIN_RATED_AMOUNT, 0) + NVL(B.DATA_PROMO_RATED_AMOUNT, 0) AS TOTAL_REVENUE,--OKAY
        C.TOTAL_VOICE_REVENUE,--OKAY
        C.TOTAL_SMS_REVENUE,--OKAY
        C.ROAM_IN_VOICE_REVENUE,--OKAY
        C.ROAM_OUT_VOICE_REVENUE,--OKAY
        C.ROAM_IN_SMS_REVENUE,--OKAY
        C.ROAM_OUT_SMS_REVENUE,--OKAY
        C.OG_CALL_TOTAL_COUNT,--OKAY
        C.OG_CALL_OCM_COUNT,--OKAY
        C.OG_CALL_MTN_COUNT,--OKAY
        C.OG_CALL_NEXTTEL_COUNT,--OKAY
        C.OG_CALL_CAMTEL_COUNT,--OKAY
        C.OG_CALL_SET_COUNT,--OKAY
        C.OG_CALL_ROAM_IN_COUNT,--OKAY
        C.OG_CALL_ROAM_OUT_COUNT,--OKAY
        C.OG_CALL_SVA_COUNT,--OKAY
        C.OG_CALL_INTERNATIONAL_COUNT,--OKAY
        C.OG_RATED_CALL_DURATION,--OKAY
        C.OG_TOTAL_CALL_DURATION,--OKAY
        C.RATED_TEL_OCM_DURATION,--OKAY
        C.RATED_TEL_MTN_DURATION,--OKAY
        C.RATED_TEL_NEXTTEL_DURATION,--OKAY
        C.RATED_TEL_CAMTEL_DURATION,--OKAY
        C.RATED_TEL_SET_DURATION,--OKAY
        C.RATED_TEL_ROAM_IN_DURATION,--OKAY
        C.RATED_TEL_ROAM_OUT_DURATION,--OKAY
        C.RATED_TEL_SVA_DURATION,--OKAY
        C.RATED_TEL_INT_DURATION,--OKAY
        C.MAIN_RATED_TEL_AMOUNT,--OKAY
        C.PROMO_RATED_TEL_AMOUNT,--OKAY
        C.OG_TOTAL_RATED_CALL_AMOUNT,--OKAY
        C.MAIN_RATED_TEL_OCM_AMOUNT,--OKAY
        C.MAIN_RATED_TEL_MTN_AMOUNT,--OKAY
        C.MAIN_RATED_TEL_NEXTTEL_AMOUNT,--OKAY
        C.MAIN_RATED_TEL_CAMTEL_AMOUNT,--OKAY
        C.MAIN_RATED_TEL_SET_AMOUNT,--OKAY
        C.MAIN_RATED_TEL_ROAM_IN_AMOUNT,--OKAY
        C.MAIN_RATED_TEL_ROAM_OUT_AMOUNT,--OKAY
        C.MAIN_RATED_TEL_SVA_AMOUNT,--OKAY
        C.MAIN_RATED_TEL_INT_AMOUNT,--OKAY
        C.PROMO_RATED_TEL_OCM_AMOUNT,--OKAY
        C.PROMO_RATED_TEL_MTN_AMOUNT,--OKAY
        C.PROMO_RATED_TEL_NEXTTEL_AMOUNT,--OKAY
        C.PROMO_RATED_TEL_CAMTEL_AMOUNT,--OKAY
        C.PROMO_RATED_TEL_SET_AMOUNT,--OKAY
        C.PROMO_RATED_TEL_ROAMIN_AMOUNT,--OKAY
        C.PROMO_RATED_TEL_ROAMOUT_AMOUNT,--OKAY
        C.PROMO_RATED_TEL_INT_AMOUNT,--OKAY
        C.OG_SMS_TOTAL_COUNT,--OKAY
        C.OG_SMS_OCM_COUNT,--OKAY
        C.OG_SMS_MTN_COUNT,--OKAY
        C.OG_SMS_NEXTTEL_COUNT,--OKAY
        C.OG_SMS_CAMTEL_COUNT,--OKAY
        C.OG_SMS_SET_COUNT,--OKAY
        C.OG_SMS_ROAM_IN_COUNT,--OKAY
        C.OG_SMS_ROAM_OUT_COUNT,--OKAY
        C.OG_SMS_SVA_COUNT,--OKAY
        C.OG_SMS_INTERNATIONAL_COUNT,--OKAY
        C.MAIN_RATED_SMS_AMOUNT,--OKAY
        C.MAIN_RATED_SMS_OCM_AMOUNT,--OKAY
        C.MAIN_RATED_SMS_MTN_AMOUNT,--OKAY
        C.MAIN_RATED_SMS_NEXTTEL_AMOUNT,--OKAY
        C.MAIN_RATED_SMS_CAMTEL_AMOUNT,--OKAY
        C.MAIN_RATED_SMS_SET_AMOUNT,--OKAY
        C.MAIN_RATED_SMS_ROAM_IN_AMOUNT,--OKAY
        C.MAIN_RATED_SMS_ROAM_OUT_AMOUNT,--OKAY
        C.MAIN_RATED_SMS_SVA_AMOUNT,--OKAY
        C.MAIN_RATED_SMS_INT_AMOUNT,--OKAY
        D.LOC_SITE_NAME,--NOT_USED
        D.LOC_TOWN_NAME,--NOT_USED
        D.LOC_ADMINTRATIVE_REGION,--NOT_USED
        D.LOC_COMMERCIAL_REGION,--NOT_USED
        E.C2S_REFILL_COUNT,--A_VERIFIER
        E.C2S_MAIN_REFILL_AMOUNT,--A_VERIFIER
        E.C2S_PROMO_REFILL_AMOUNT,--A_VERIFIER
        E.P2P_REFILL_COUNT,--A_VERIFIER
        E.P2P_REFILL_AMOUNT,--A_VERIFIER
        E.SCRATCH_REFILL_COUNT,--A_VERIFIER
        E.SCRATCH_MAIN_REFILL_AMOUNT,--A_VERIFIER
        E.SCRATCH_PROMO_REFILL_AMOUNT,--A_VERIFIER
        E.P2P_REFILL_FEES,--A_VERIFIER
        F.SOS_REIMBURSEMENT_AMOUNT,--A_VERIFIER
        F.SOS_REIMBURSEMENT_COUNT,--A_VERIFIER
        F.SOS_LOAN_AMOUNT,--A_VERIFIER
        F.SOS_LOAN_COUNT,--A_VERIFIER
        F.SOS_FEES,--A_VERIFIER
        H.SUBS_AUTRES_COUNT,--A_VERIFIER
        H.SUBS_AUTRES_AMOUNT,--A_VERIFIER
        H.SUBS_VOICE_COUNT,--A_VERIFIER
        H.SUBS_SMS_COUNT,--A_VERIFIER
        H.SUBS_DATA_COUNT,--A_VERIFIER
        H.SUBS_VOICE_AMOUNT,--A_VERIFIER
        H.SUBS_SMS_AMOUNT,--A_VERIFIER
        H.SUBS_DATA_AMOUNT,--A_VERIFIER
        0 AS SUBS_BUNDLE_PLENTY_COUNT,
        0 AS SUBS_ORANGE_BONUS_COUNT,
        0 AS SUBS_FNF_MODIFY_COUNT,
        0 AS SUBS_DATA_2G_COUNT,
        0 AS SUBS_DATA_3G_JOUR_COUNT,
        0 AS SUBS_DATA_3G_SEMAINE_COUNT,
        0 AS SUBS_DATA_3G_MOIS_COUNT,
        0 AS SUBS_MAXI_BONUS_COUNT,
        0 AS SUBS_PRO_COUNT,
        0 AS SUBS_INTERN_JOUR_COUNT,
        0 AS SUBS_INTERN_SEMAINE_COUNT,
        0 AS SUBS_INTERN_MOIS_COUNT,
        0 AS SUBS_PACK_SMS_JOUR_COUNT,
        0 AS SUBS_PACK_SMS_SEMAINE_COUNT,
        0 AS SUBS_PACK_SMS_MOIS_COUNT,
        0 AS SUBS_WS_COUNT,
        0 AS SUBS_OBONUS_ILLIMITE_COUNT,
        0 AS SUBS_ORANGE_PHENIX_COUNT,
        0 AS SUBS_RECHARGE_PLENTY_COUNT,
        0 AS SUBS_DATA_FLYBOX_COUNT,
        0 AS SUBS_DATA_AUTRES_COUNT,
        0 AS SUBS_ROAMING_COUNT,
        0 AS SUBS_SMS_AUTRES_COUNT,
        0 AS SUBS_BUNDLE_PLENTY_AMOUNT,
        0 AS SUBS_ORANGE_BONUS_AMOUNT,
        0 AS SUBS_FNF_MODIFY_AMOUNT,
        0 AS SUBS_DATA_2G_AMOUNT,
        0 AS SUBS_DATA_3G_JOUR_AMOUNT,
        0 AS SUBS_DATA_3G_SEMAINE_AMOUNT,
        0 AS SUBS_DATA_3G_MOIS_AMOUNT,
        0 AS SUBS_MAXI_BONUS_AMOUNT,
        0 AS SUBS_PRO_AMOUNT,
        0 AS SUBS_INTERN_JOUR_AMOUNT,
        0 AS SUBS_INTERN_SEMAINE_AMOUNT,
        0 AS SUBS_INTERN_MOIS_AMOUNT,
        0 AS SUBS_PACK_SMS_JOUR_AMOUNT,
        0 AS SUBS_PACK_SMS_SEMAINE_AMOUNT,
        0 AS SUBS_PACK_SMS_MOIS_AMOUNT,
        0 AS SUBS_WS_AMOUNT,
        0 AS SUBS_OBONUS_ILLIMITE_AMOUNT,
        0 AS SUBS_ORANGE_PHENIX_AMOUNT,
        0 AS SUBS_RECHARGE_PLENTY_AMOUNT,
        0 AS SUBS_DATA_FLYBOX_AMOUNT,
        0 AS SUBS_DATA_AUTRES_AMOUNT,
        0 AS SUBS_ROAMING_AMOUNT,
        0 AS SUBS_SMS_AUTRES_AMOUNT,
        H.DATA_VIA_OM,--A_VERIFIER
        L.TER_TAC_CODE,--OKAY
        L.TER_IMEI,--OKAY
        L.TER_CONSTRUCTOR,--OKAY
        L.TER_MODEL,--OKAY
        L.TER_2G_3G_4G_COMPATIBILITY,--OKAY
        L.TER_2G_COMPATIBILITY,--OKAY
        L.TER_3G_COMPATIBILITY,--OKAY
        L.TER_4G_COMPATIBILITY,--OKAY
        '' REVENU_MOYEN,
        '' PREMIUM,
        '' CONSO_MOY_DATA,
        '' RECHARGE_MOY,
        '' PREMIUM_PLUS,
        M.INSCRIPTEUR,--OKAY
        M.MIDATEDEP,--OKAY
        M.MTT_DEPOT,--OKAY
        M.NB_DEPOT,--OKAY
        M.IDSPEC,--OKAY
        M.FIRSTDEPOT,--OKAY
        M.FIRSTTRAN,--OKAY
        M.DEST_TRAN,--OKAY
        M.SERV_TRAN,--OKAY
        M.MIDATETR,--OKAY
        M.MTT_TRANS,--OKAY
        M.NB_TRANSACTION,--OKAY
        M.REG_LEVEL,--OKAY
        M.SEUIL_OK,--OKAY
        M.AUTO_INSCRIPTION,--OKAY
        M.BOUCLE_P2P,--OKAY
        M.DOUBLE_PROFIL,--OKAY
        M.BOUCLE,--OKAY
        M.CONFORMITE,--OKAY
        --K.TYPE_PIECE TYPE_PIECE,
        --K.NUMERO_PIECE NUMERO_PIECE,
        --K.DATE_NAISSANCE DATE_NAISSANCE,
        K.DATE_EXPIRATION DATE_EXPIRATION,
        K.ADDRESSE ADDRESSE,
        K.NUMERO_PIECE_TUTEUR NUMERO_PIECE_TUTEUR,
        K.NOM_PARENT NOM_PARENT,
        K.DATE_NAISSANCE_TUTEUR DATE_NAISSANCE_TUTEUR,
        K.NOM_STRUCTURE NOM_STRUCTURE,
        K.NUMERO_REGISTRE_COMMERCE NUMERO_REGISTRE_COMMERCE,
        K.NUMERO_PIECE_REP_LEGAL NUMERO_PIECE_REP_LEGAL,
        K.DATE_ACTIVATION DATE_ACTIVATION,
        K.DATE_CHANGEMENT_STATUT DATE_CHANGEMENT_STATUT,
        K.STATUT_BSCS STATUT_BSCS,
        K.ODBINCOMINGCALLS ODBINCOMINGCALLS,
        K.ODBOUTGOINGCALLS ODBOUTGOINGCALLS,
        K.IMEI IMEI,
        K.STATUT_DEROGATION STATUT_DEROGATION,
        K.REGION_ADMINISTRATIVE REGION_ADMINISTRATIVE,
        K.REGION_COMMERCIALE REGION_COMMERCIALE,
        K.SITE_NAME SITE_NAME,
        K.VILLE VILLE,
        K.LONGITUDE LONGITUDE,
        K.LATITUDE LATITUDE,
        K.OFFRE_COMMERCIALE OFFRE_COMMERCIALE,
        K.TYPE_CONTRAT TYPE_CONTRAT,
        K.SEGMENTATION SEGMENTATION,
        K.STATUT_IN STATUT_IN,
        K.NUMERO_PIECE_ABSENT NUMERO_PIECE_ABSENT,
        K.NUMERO_PIECE_TUT_ABSENT NUMERO_PIECE_TUT_ABSENT,
        K.NUMERO_PIECE_INF_4 NUMERO_PIECE_INF_4,
        K.NUMERO_PIECE_TUT_INF_4 NUMERO_PIECE_TUT_INF_4,
        K.NUMERO_PIECE_NON_AUTHORISE NUMERO_PIECE_NON_AUTHORISE,
        K.NUMERO_PIECE_TUT_NON_AUTH NUMERO_PIECE_TUT_NON_AUTH,
        K.NUMERO_PIECE_EGALE_MSISDN NUMERO_PIECE_EGALE_MSISDN,
        K.NUMERO_PIECE_TUT_EGALE_MSISDN NUMERO_PIECE_TUT_EGALE_MSISDN,
        K.NUMERO_PIECE_A_CARACT_NON_AUTH NUMERO_PIECE_A_CARACT_NON_AUTH,
        K.NUMERO_PIECE_TUT_CARAC_NON_A NUMERO_PIECE_TUT_CARAC_NON_A,
        K.NUMERO_PIECE_UNIQUEMENT_LETTRE NUMERO_PIECE_UNIQUEMENT_LETTRE,
        K.NUMERO_PIECE_TUT_UNIQ_LETTRE NUMERO_PIECE_TUT_UNIQ_LETTRE,
        K.NOM_PRENOM_ABSENT NOM_ABSENT,
        K.NOM_PARENT_ABSENT NOM_PARENT_ABSENT,
        K.NOM_PRENOM_DOUTEUX NOM_DOUTEUX,
        K.NOM_PARENT_DOUTEUX NOM_PARENT_DOUTEUX,
        K.DATE_NAISSANCE_ABSENT DATE_NAISSANCE_ABSENT,
        K.DATE_NAISSANCE_TUT_ABSENT DATE_NAISSANCE_TUT_ABSENT,
        K.DATE_EXPIRATION_ABSENT DATE_EXPIRATION_ABSENT,
        K.ADDRESSE_ABSENT ADDRESSE_ABSENT,
        K.ADDRESSE_DOUTEUSE ADDRESSE_DOUTEUSE,
        K.TYPE_PERSONNE_INCONNU TYPE_PERSONNE_INCONNU,
        K.MINEUR_MAL_IDENTIFIE MINEUR_MAL_IDENTIFIE,
        K.TYPE_PERSONNE TYPE_PERSONNE,
        K.DATE_NAISSANCE_DOUTEUX DATE_NAISSANCE_DOUTEUX,
        K.DATE_NAISSANCE_TUT_DOUTEUX DATE_NAISSANCE_TUT_DOUTEUX,
        K.DATE_EXPIRATION_DOUTEUSE DATE_EXPIRATION_DOUTEUSE,
        K.CNI_EXPIRE CNI_EXPIRE,
        K.MULTI_SIM MULTI_SIM,
        K.EST_PRESENT_ZEB EST_PRESENT_ZEB,
        K.EST_PRESENT_ART EST_PRESENT_ART,
        K.EST_PRESENT_GP EST_PRESENT_GP,
        K.EST_PRESENT_OCM EST_PRESENT_OCM,
        K.EST_CLIENT_VIP EST_CLIENT_VIP,
        K.CONFORM_OCM_P_MORALE_M2M CONFORM_OCM_P_MORALE_M2M,
        K.CONFORM_ART_P_MORALE_M2M CONFORM_ART_P_MORALE_M2M,
        K.CONFORM_OCM_P_MORALE_FLOTTE CONFORM_OCM_P_MORALE_FLOTTE,
        K.CONFORM_ART_P_MORALE_FLOTTE CONFORM_ART_P_MORALE_FLOTTE,
        K.CONFORM_OCM_P_PHY_MAJEUR CONFORM_OCM_P_PHY_MAJEUR,
        K.CONFORM_ART_P_PHY_MAJEUR CONFORM_ART_P_PHY_MAJEUR,
        K.CONFORM_OCM_P_PHY_MINEUR CONFORM_OCM_P_PHY_MINEUR,
        K.CONFORM_ART_P_PHY_MINEUR CONFORM_ART_P_PHY_MINEUR,
        K.EST_SUSPENDU EST_SUSPENDU,
        K.NOM_STRUCTURE_ABSENT NOM_STRUCTURE_ABSENT,
        K.NUMERO_REGISTRE_ABSENT NUMERO_REGISTRE_ABSENT,
        K.NUMERO_REGISTRE_DOUTEUX NUMERO_REGISTRE_DOUTEUX,
        (case
            when K.TYPE_PERSONNE is  NULL then K.CONFORM_ART_P_PHY_MAJEUR
            when K.TYPE_PERSONNE = 'MAJEUR' then K.CONFORM_ART_P_PHY_MAJEUR
            when K.TYPE_PERSONNE = 'PP' then  K.CONFORM_ART_P_PHY_MAJEUR
            when K.TYPE_PERSONNE = 'MINEUR' then  K.CONFORM_ART_P_PHY_MINEUR
            when K.TYPE_PERSONNE = 'PERSONNE_MORALE' then K.CONFORM_ART_P_MORALE_FLOTTE
            when K.TYPE_PERSONNE = 'MACHINE_2_MACHINE' then  K.CONFORM_ART_P_MORALE_M2M
            else K.TYPE_PERSONNE
        end) CONFORME_ART,
        (case
            when K.TYPE_PERSONNE is  NULL then K.CONFORM_ART_P_PHY_MAJEUR
            when K.TYPE_PERSONNE = 'MAJEUR' then K.CONFORM_ART_P_PHY_MAJEUR
            when K.TYPE_PERSONNE = 'PP' then K.CONFORM_OCM_P_PHY_MAJEUR
            when K.TYPE_PERSONNE = 'MINEUR' then K.CONFORM_OCM_P_PHY_MINEUR
            when K.TYPE_PERSONNE = 'PERSONNE_MORALE' then K.CONFORM_OCM_P_MORALE_FLOTTE
            when K.TYPE_PERSONNE = 'MACHINE_2_MACHINE' then K.CONFORM_OCM_P_MORALE_M2M
            else  K.TYPE_PERSONNE
        end) CONFORME_OCM,
        K.IMEI_ABSENT IMEI_ABSENT,
        K.ADRESSE_ABSENT ADRESSE_ABSENT,
        K.EST_PREMIUM EST_PREMIUM,
        K.ADRESSE_TUTEUR ADRESSE_TUTEUR,
        K.TYPE_PIECE_TUTEUR TYPE_PIECE_TUTEUR,
        K.ACCEPTATION_CGV ACCEPTATION_CGV,
        K.CONTRAT_SOUCRIPTION CONTRAT_SOUCRIPTION,
        K.DISPONIBILITE_SCAN DISPONIBILITE_SCAN,
        K.PLAN_LOCALISATION PLAN_LOCALISATION,
        K.DATE_VALIDATION_BO,
        K.STATUT_VALIDATION_BO,
        K.MOTIF_REJET_BO,
        (case
            when K.STATUT_VALIDATION_BO = '1' then 'VERIFIE ET VALIDE'
            when K.STATUT_VALIDATION_BO = '3' then 'VERIFIE ET CORRIGE'
            when K.STATUT_VALIDATION_BO = '-1' then 'VERIFIE ET NON CONFORME NIVEAU 1'
            when K.STATUT_VALIDATION_BO = '-2' then 'VERIFIE ET NON CONFORME NIVEAU 2'
            when K.STATUT_VALIDATION_BO = '-3' then 'VERIFIE ET NON CONFORME NIVEAU 3'
            when K.STATUT_VALIDATION_BO = '-4' then 'PRET POUR LA SUSPENSION'
            when K.STATUT_VALIDATION_BO = '-5' then 'SUSPENDU APPEL SORTANT BO'
            when K.STATUT_VALIDATION_BO = '-6' then 'SUSPENDU HORS BO'
            when K.STATUT_VALIDATION_BO = '-7' then 'MODIFIER AVANT LA SUSPENSION'
            else 'NON VERIFIE'
        end) STATUT_VALIDATION_BOO,
        J.OMNY_TRANSACTION_AMOUNT,--OKAY
        J.OMNY_COMMISSIONS_PAID,--OKAY
        J.OMNY_COMMISSIONS_RECEIVED,--OKAY
        J.OMNY_COMMISSIONS_OTHERS,--OKAY
        J.OMNY_SERVICE_CHARGE_RECEIVED,--OKAY
        J.OMNY_SERVICE_CHARGE_PAID,--OKAY
        J.OMNY_TAXES,--OKAY
        J.OMNY_SERVICE_TYPE,--OKAY
        J.OMNY_SENDER_PRE_BAL,--OKAY
        J.OMNY_SENDER_POST_BAL,--OKAY
        J.OMNY_RECEIVER_PRE_BAL,--OKAY
        J.OMNY_RECEIVER_POST_BAL,--OKAY
        I.ED_AMOUNT,--OKAY
        I.ED_TRANSACTION_TYPE,--OKAY
        I.ED_BYTES_OBTAINED,--OKAY
        I.ED_CONTACT_CHANNEL--OKAY
    FROM
    (
        SELECT
            NVL(A0.MSISDN, A1.MSISDN) AS MSISDN,
            CONTRACT_TYPE,
            COMMERCIAL_OFFER,
            ACTIVATION_DATE,
            DEACTIVATION_DATE,
            LANG,
            OSP_STATUS,
            IMSI,
            GRP_LAST_OG_CALL,
            GRP_LAST_IC_CALL,
            GRP_REMAIN_CREDIT_MAIN,
            GRP_REMAIN_CREDIT_PROMO,
            GRP_GP_STATUS,
            DIR_FIRST_NAME,
            DIR_LAST_NAME,
            DIR_BIRTH_DATE,
            DIR_IDENTIFICATION_TOWN,
            DIR_IDENTIFICATION_DATE,
            PROFESSION_IDENTIFICATEUR,
            SEX,
            --NVL(EST_PRESENT_DANS_ACCOUNT_ACTIVITY,'NON') EST_PRESENT_DANS_ACCOUNT_ACTIVITY,
            --NVL(EST_PRESENT_DANS_DT_BASE_IDENTIF,'NON') EST_PRESENT_DANS_DT_BASE_IDENTIF,
            --NVL(EST_PRESENT_DANS_MSC,'NON') EST_PRESENT_DANS_MSC,
            TYPE_PIECE,
            NUMERO_PIECE,
            DATE_NAISSANCE
        FROM
        (
            SELECT
                NVL(A01.MSISDN, A02.MSISDN) AS MSISDN,
                CONTRACT_TYPE,
                COMMERCIAL_OFFER,
                ACTIVATION_DATE,
                DEACTIVATION_DATE,
                LANG,
                OSP_STATUS,
                IMSI,
                GRP_LAST_OG_CALL,
                GRP_LAST_IC_CALL,
                GRP_REMAIN_CREDIT_MAIN,
                GRP_REMAIN_CREDIT_PROMO,
                GRP_GP_STATUS
                --EST_PRESENT_DANS_ACCOUNT_ACTIVITY
            FROM
            (
                SELECT
                    ACCESS_KEY MSISDN,
                    OSP_CONTRACT_TYPE CONTRACT_TYPE,
                    COMMERCIAL_OFFER,
                    ACTIVATION_DATE,
                    DEACTIVATION_DATE,
                    LANG,
                    OSP_STATUS,
                    MAIN_IMSI IMSI
                FROM MON.SPARK_FT_CONTRACT_SNAPSHOT
                WHERE EVENT_DATE = DATE_ADD('###SLICE_VALUE###',1)
                    AND OSP_STATUS IN ('ACTIVE', 'INACTIVE')
            ) A01
            FULL JOIN
            (
                SELECT
                    MSISDN,
                    OG_CALL GRP_LAST_OG_CALL,
                    IC_CALL_4 GRP_LAST_IC_CALL,
                    REMAIN_CREDIT_MAIN GRP_REMAIN_CREDIT_MAIN,
                    REMAIN_CREDIT_PROMO GRP_REMAIN_CREDIT_PROMO,
                    GP_STATUS GRP_GP_STATUS
                    --'OUI' EST_PRESENT_DANS_ACCOUNT_ACTIVITY
                FROM MON.SPARK_FT_ACCOUNT_ACTIVITY
                WHERE EVENT_DATE = DATE_ADD('###SLICE_VALUE###',1)
            ) A02
            ON A01.MSISDN = A02.MSISDN
        ) A0
        FULL JOIN 
        (
            SELECT
                NVL(A11.MSISDN, A12.MSISDN) MSISDN,
                DIR_FIRST_NAME,
                DIR_LAST_NAME,
                DIR_BIRTH_DATE,
                DIR_IDENTIFICATION_TOWN,
                DIR_IDENTIFICATION_DATE,
                --EST_PRESENT_DANS_DT_BASE_IDENTIF,
                PROFESSION_IDENTIFICATEUR,
                SEX,
                --EST_PRESENT_DANS_MSC,
                TYPE_PIECE,
                NUMERO_PIECE,
                DATE_NAISSANCE
            FROM
            (
                SELECT
                    MSISDN,
                    PRENOM AS DIR_FIRST_NAME,
                    NOM AS DIR_LAST_NAME,
                    NEE_LE AS DIR_BIRTH_DATE,
                    VILLE_VILLAGE AS DIR_IDENTIFICATION_TOWN,
                    TO_DATE(DATE_IDENTIFICATION) AS DIR_IDENTIFICATION_DATE,
                    PROFESSION_IDENTIFICATEUR,
                    GENRE SEX,
                    --'OUI' EST_PRESENT_DANS_DT_BASE_IDENTIF,
                    TYPE_PIECE_IDENTIFICATION TYPE_PIECE,
                    CNI NUMERO_PIECE,
                    NEE_LE DATE_NAISSANCE
                FROM DIM.SPARK_DT_BASE_IDENTIFICATION
            ) A11
            FULL JOIN (
                SELECT
                    MSISDN
                    --'OUI' EST_PRESENT_DANS_MSC
                FROM MON.SPARK_FT_OG_IC_CALL_SNAPSHOT
                WHERE EVENT_DATE=DATE_ADD('###SLICE_VALUE###',1) AND FN_NNP_SIMPLE_DESTINATION(MSISDN)='OCM'
            ) A12
            ON A11.MSISDN = A12.MSISDN
        ) A1 ON A0.MSISDN = A1.MSISDN
        WHERE  NVL(A0.MSISDN, A1.MSISDN) IS NOT NULL
    ) A
    LEFT JOIN 
    (
        SELECT
            MSISDN,
            NVL(MAIN_RATED_AMOUNT, 0) AS DATA_MAIN_RATED_AMOUNT,
            NVL(GOS_DEBIT_AMOUNT, 0) AS DATA_GOS_MAIN_RATED_AMOUNT,
            NVL(PROMTOTAL_VOICE_REVENUEO_RATED_AMOUNT, 0) AS DATA_PROMO_RATED_AMOUNT,
            NVL(MAIN_RATED_AMOUNT_ROAMING, 0) AS DATA_ROAM_MAIN_RATED_AMOUNT,
            NVL(PROMO_RATED_AMOUNT_ROAMING, 0) AS DATA_ROAM_PROMO_RATED_AMOUNT,
            NVL(BYTES_RECEIVED, 0) AS DATA_BYTES_RECEIVED,
            NVL(BYTES_SENT, 0) AS DATA_BYTES_SENT,
            NVL(BYTES_USED_IN_BUNDLE, 0) AS DATA_BYTES_USED_IN_BUNDLE,
            NVL(BYTES_USED_OUT_BUNDLE, 0) AS DATA_BYTES_USED_PAYGO,
            NVL(BYTES_USED_IN_BUNDLE_ROAMING, 0) AS DATA_BYTES_USED_IN_BUNDLE_ROAM,
            NVL(BYTES_USED_OUT_BUNDLE_ROAMING, 0) AS DATA_BYTE_USED_OUT_BUNDLE_ROAM,
            NVL(MMS_COUNT, 0) AS DATA_MMS_USED,
            NVL(BUNDLE_MMS_USED_VOLUME, 0) AS DATA_MMS_USED_IN_BUNDLE
        FROM MON.SPARK_FT_DATA_CONSO_MSISDN_DAY B0
        WHERE EVENT_DATE = '###SLICE_VALUE###'
    ) B ON A.MSISDN = B.MSISDN
    LEFT JOIN
    (
        SELECT
            MSISDN,
            NVL(CONSO_TEL, 0) AS TOTAL_VOICE_REVENUE,
            NVL(CONSO_SMS, 0) AS TOTAL_SMS_REVENUE,
            NVL(INROAM_TOTAL_CONSO, 0) AS ROAM_IN_VOICE_REVENUE,
            NVL(ROAM_MAIN_TEL_CONSO, 0) AS ROAM_OUT_VOICE_REVENUE,
            NVL(INROAM_SMS_CONSO, 0) AS ROAM_IN_SMS_REVENUE,
            NVL(ROAM_SMS_CONSO, 0) AS ROAM_OUT_SMS_REVENUE,
            NVL(TEL_COUNT, 0) AS OG_CALL_TOTAL_COUNT,
            NVL(ONNET_TEL_COUNT, 0) AS OG_CALL_OCM_COUNT,
            NVL(MTN_TEL_COUNT, 0) AS OG_CALL_MTN_COUNT,
            NVL(NEXTTEL_TEL_COUNT, 0) AS OG_CALL_NEXTTEL_COUNT,
            NVL(CAMTEL_TEL_COUNT, 0) AS OG_CALL_CAMTEL_COUNT,
            NVL(SET_TEL_COUNT, 0) AS OG_CALL_SET_COUNT,
            NVL(INROAM_TEL_COUNT, 0) AS OG_CALL_ROAM_IN_COUNT,
            NVL(ROAM_TEL_COUNT, 0) AS OG_CALL_ROAM_OUT_COUNT,
            NVL(SVA_TEL_COUNT, 0) AS OG_CALL_SVA_COUNT,
            NVL(INTERNATIONAL_TEL_COUNT, 0) AS OG_CALL_INTERNATIONAL_COUNT,
            NVL(BILLED_TEL_DURATION, 0) AS OG_RATED_CALL_DURATION,
            NVL(TEL_DURATION, 0) AS OG_TOTAL_CALL_DURATION,
            NVL(ONNET_DURATION, 0) AS RATED_TEL_OCM_DURATION,
            NVL(MTN_BILLED_TEL_DURATION, 0) AS RATED_TEL_MTN_DURATION,
            NVL(NEXTTEL_BILLED_TEL_DURATION, 0) AS RATED_TEL_NEXTTEL_DURATION,
            NVL(CAMTEL_BILLED_TEL_DURATION, 0) AS RATED_TEL_CAMTEL_DURATION,
            NVL(SET_BILLED_TEL_DURATION, 0) AS RATED_TEL_SET_DURATION,
            NVL(INROAM_BILLED_TEL_DURATION, 0) AS RATED_TEL_ROAM_IN_DURATION,
            NVL(ROAM_BILLED_TEL_DURATION, 0) AS RATED_TEL_ROAM_OUT_DURATION,
            NVL(SVA_BILLED_DURATION, 0) AS RATED_TEL_SVA_DURATION,
            NVL(INTERNATIONAL_BIL_TEL_DURATION, 0) AS RATED_TEL_INT_DURATION,
            NVL(CONSO_TEL_MAIN, 0) AS MAIN_RATED_TEL_AMOUNT,
            NVL(CONSO_TEL, 0) - NVL(CONSO_TEL_MAIN, 0) AS PROMO_RATED_TEL_AMOUNT,
            NVL(CONSO_TEL, 0) AS OG_TOTAL_RATED_CALL_AMOUNT,
            NVL(ONNET_MAIN_TEL_CONSO, 0) AS MAIN_RATED_TEL_OCM_AMOUNT,
            NVL(MTN_MAIN_TEL_CONSO, 0) AS MAIN_RATED_TEL_MTN_AMOUNT,
            NVL(NEXTTEL_MAIN_TEL_CONSO, 0) AS MAIN_RATED_TEL_NEXTTEL_AMOUNT,
            NVL(CAMTEL_MAIN_TEL_CONSO, 0) AS MAIN_RATED_TEL_CAMTEL_AMOUNT,
            NVL(SET_MAIN_TEL_CONSO, 0) AS MAIN_RATED_TEL_SET_AMOUNT,
            NVL(INROAM_MAIN_TEL_CONSO, 0) AS MAIN_RATED_TEL_ROAM_IN_AMOUNT,
            NVL(ROAM_MAIN_TEL_CONSO, 0) AS MAIN_RATED_TEL_ROAM_OUT_AMOUNT,
            NVL(SVA_BILLED_TEL_CONSO, 0) AS MAIN_RATED_TEL_SVA_AMOUNT,
            NVL(INTERNATIONAL_MAIN_TEL_CONSO, 0) AS MAIN_RATED_TEL_INT_AMOUNT,
            NVL(ONNET_PROMO_TEL_CONSO, 0) AS PROMO_RATED_TEL_OCM_AMOUNT,
            NVL(MTN_PROMO_TEL_CONSO, 0) AS PROMO_RATED_TEL_MTN_AMOUNT,
            NVL(NEXTTEL_PROMO_TEL_CONSO, 0) AS PROMO_RATED_TEL_NEXTTEL_AMOUNT,
            NVL(CAMTEL_PROMO_TEL_CONSO, 0) AS PROMO_RATED_TEL_CAMTEL_AMOUNT,
            NVL(SET_PROMO_TEL_CONSO, 0) AS PROMO_RATED_TEL_SET_AMOUNT,
            NVL(INROAM_PROMO_TEL_CONSO, 0) AS PROMO_RATED_TEL_ROAMIN_AMOUNT,
            NVL(ROAM_PROMO_TEL_CONSO, 0) AS PROMO_RATED_TEL_ROAMOUT_AMOUNT,
            NVL(INTERNATIONAL_PROMO_TEL_CONSO, 0) AS PROMO_RATED_TEL_INT_AMOUNT,
            NVL(SMS_COUNT, 0) AS OG_SMS_TOTAL_COUNT,
            NVL(ONNET_SMS_COUNT, 0) AS OG_SMS_OCM_COUNT,
            NVL(MTN_SMS_COUNT, 0) AS OG_SMS_MTN_COUNT,
            NVL(NEXTTEL_SMS_COUNT, 0) AS OG_SMS_NEXTTEL_COUNT,
            NVL(CAMTEL_SMS_COUNT, 0) AS OG_SMS_CAMTEL_COUNT,
            NVL(SET_SMS_COUNT, 0) AS OG_SMS_SET_COUNT,
            NVL(INROAM_SMS_COUNT, 0) AS OG_SMS_ROAM_IN_COUNT,
            NVL(ROAM_SMS_COUNT, 0) AS OG_SMS_ROAM_OUT_COUNT,
            NVL(SVA_SMS_COUNT, 0) AS OG_SMS_SVA_COUNT,
            NVL(INTERNATIONAL_SMS_COUNT, 0) AS OG_SMS_INTERNATIONAL_COUNT,
            NVL(MAIN_CALL_COST-(CONSO_TEL_MAIN + OTHERS_VAS_MAIN_COST), 0) AS MAIN_RATED_SMS_AMOUNT,
            NVL(ONNET_SMS_CONSO, 0) AS MAIN_RATED_SMS_OCM_AMOUNT,
            NVL(MTN_SMS_CONSO, 0) AS MAIN_RATED_SMS_MTN_AMOUNT,
            NVL(NEXTTEL_SMS_CONSO, 0) AS MAIN_RATED_SMS_NEXTTEL_AMOUNT,
            NVL(CAMTEL_SMS_CONSO, 0) AS MAIN_RATED_SMS_CAMTEL_AMOUNT,
            NVL(SET_SMS_CONSO, 0) AS MAIN_RATED_SMS_SET_AMOUNT,
            NVL(INROAM_SMS_CONSO, 0) AS MAIN_RATED_SMS_ROAM_IN_AMOUNT,
            NVL(ROAM_SMS_CONSO, 0) AS MAIN_RATED_SMS_ROAM_OUT_AMOUNT,
            NVL(SVA_SMS_CONSO, 0) AS MAIN_RATED_SMS_SVA_AMOUNT,
            NVL(INTERNATIONAL_SMS_CONSO, 0) AS MAIN_RATED_SMS_INT_AMOUNT
        FROM MON.SPARK_FT_CONSO_MSISDN_DAY C0
        WHERE EVENT_DATE = '###SLICE_VALUE###'
    ) C ON A.MSISDN = C.MSISDN
    LEFT JOIN
    (
        SELECT
            (CASE
                WHEN LENGTH(MSISDN) = 13 AND substr(MSISDN,1,3) = '160' AND FN_GET_NNP_MSISDN_SIMPLE_DESTN(MSISDN) IN ('MTN','VIETTEL','OCM') THEN SUBSTR(MSISDN,-9)
                ELSE MSISDN
            END) MSISDN,
            SITE_NAME AS LOC_SITE_NAME,
            TOWNNAME AS LOC_TOWN_NAME,
            ADMINISTRATIVE_REGION AS LOC_ADMINTRATIVE_REGION,
            COMMERCIAL_REGION AS LOC_COMMERCIAL_REGION
        FROM
        (
            SELECT
                D01.*,
                ROW_NUMBER() OVER (PARTITION BY D01.MSISDN ORDER BY D01.LAST_LOCATION_DAY DESC, D01.INSERT_DATE DESC) RN
            FROM MON.SPARK_FT_CLIENT_LAST_SITE_DAY D01
            WHERE D01.EVENT_DATE = '###SLICE_VALUE###'
        ) D0
        WHERE D0.RN=1
            AND FN_GET_OPERATOR_CODE(D0.MSISDN) IN ('SET', 'OCM')
    ) D ON A.MSISDN = D.MSISDN
    LEFT JOIN
    (
        SELECT
            NVL(E0.MSISDN, E1.MSISDN) AS MSISDN,
            NVL(C2S_REFILL_COUNT, 0) AS C2S_REFILL_COUNT,
            NVL(C2S_MAIN_REFILL_AMOUNT, 0) AS C2S_MAIN_REFILL_AMOUNT,
            NVL(C2S_PROMO_REFILL_AMOUNT, 0) AS C2S_PROMO_REFILL_AMOUNT,
            NVL(P2P_REFILL_COUNT, 0) AS P2P_REFILL_COUNT,
            NVL(P2P_REFILL_AMOUNT, 0) AS P2P_REFILL_AMOUNT,
            NVL(SCRATCH_REFILL_COUNT, 0) AS SCRATCH_REFILL_COUNT,
            NVL(SCRATCH_MAIN_REFILL_AMOUNT, 0) AS SCRATCH_MAIN_REFILL_AMOUNT,
            NVL(SCRATCH_PROMO_REFILL_AMOUNT, 0) AS SCRATCH_PROMO_REFILL_AMOUNT,
            NVL(P2P_REFILL_FEES, 0) AS P2P_REFILL_FEES
        FROM
        (
            SELECT
                E01.RECEIVER_MSISDN MSISDN
                ,SUM(CASE WHEN E01.REFILL_MEAN='C2S' THEN 1 ELSE 0 END ) C2S_REFILL_COUNT
                ,SUM(CASE WHEN E01.REFILL_MEAN='C2S' THEN E01.REFILL_AMOUNT ELSE 0 END ) C2S_MAIN_REFILL_AMOUNT
                ,SUM(CASE WHEN E01.REFILL_MEAN='C2S' THEN E01.REFILL_BONUS ELSE 0 END ) C2S_PROMO_REFILL_AMOUNT
                ,SUM(CASE WHEN E01.REFILL_MEAN='SCRATCH' THEN 1 ELSE 0 END ) SCRATCH_REFILL_COUNT
                ,SUM(CASE WHEN E01.REFILL_MEAN='SCRATCH' THEN E01.REFILL_AMOUNT ELSE 0 END ) SCRATCH_MAIN_REFILL_AMOUNT
                ,SUM(CASE WHEN E01.REFILL_MEAN='SCRATCH' THEN E01.REFILL_BONUS ELSE 0 END ) SCRATCH_PROMO_REFILL_AMOUNT
            FROM MON.SPARK_FT_REFILL E01
            WHERE E01.REFILL_DATE = '###SLICE_VALUE###'
                AND E01.TERMINATION_IND='200'
            GROUP BY E01.RECEIVER_MSISDN
        ) E0
        FULL JOIN
        (
            SELECT
                E11.RECEIVER_MSISDN MSISDN
                ,COUNT(*) P2P_REFILL_COUNT
                ,SUM(E11.TRANSFER_AMT) P2P_REFILL_AMOUNT
                ,SUM(E11.TRANSFER_FEES) P2P_REFILL_FEES
            FROM MON.SPARK_FT_CREDIT_TRANSFER E11
            WHERE E11.REFILL_DATE = '###SLICE_VALUE###'
                AND E11.TERMINATION_IND='000'
            GROUP BY E11.RECEIVER_MSISDN
        ) E1
        ON E0.MSISDN = E1.MSISDN
    ) E ON A.MSISDN = E.MSISDN
    LEFT JOIN
    (
        SELECT
            F0.SERVED_PARTY_MSISDN AS MSISDN,
            SUM(CASE WHEN F0.OPERATION_TYPE = 'REIMBURSMENT' THEN F0.REFILL_AMOUNT ELSE 0 END) AS SOS_REIMBURSEMENT_AMOUNT,
            SUM(CASE WHEN F0.OPERATION_TYPE = 'REIMBURSMENT' THEN 1 ELSE 0 END) AS SOS_REIMBURSEMENT_COUNT,
            SUM(CASE WHEN F0.OPERATION_TYPE = 'LOAN' THEN F0.LOAN_AMOUNT ELSE 0 END) AS SOS_LOAN_AMOUNT,
            SUM(CASE WHEN F0.OPERATION_TYPE = 'LOAN' THEN 1 ELSE 0 END) AS SOS_LOAN_COUNT,
            SUM(F0.FEE) AS SOS_FEES
        FROM MON.SPARK_FT_OVERDRAFT F0
        WHERE F0.TRANSACTION_DATE = '###SLICE_VALUE###'
        GROUP BY F0.SERVED_PARTY_MSISDN
    ) F ON A.MSISDN = F.MSISDN
    LEFT JOIN
    (
        SELECT
            G0.MSISDN,
            NVL(G0.TOTAL_SUBS_AMOUNT, 0) AS TOTAL_SUBS_REVENUE
        FROM MON.SPARK_FT_SUBSCRIPTION_MSISDN_DAY G0
        WHERE G0.EVENT_DATE = '###SLICE_VALUE###'
    ) G ON A.MSISDN = G.MSISDN
    LEFT JOIN
    (
        SELECT
            MSISDN,
            SUM(CASE WHEN UPPER(USAGE_MKT) = 'AUTRES' THEN NBRE_SUBS ELSE 0 END) AS SUBS_AUTRES_COUNT,
            SUM(CASE WHEN UPPER(USAGE_MKT) = 'AUTRES' THEN RATED_AMOUNT ELSE 0 END) AS SUBS_AUTRES_AMOUNT,
            SUM(CASE WHEN UPPER(USAGE_MKT) = 'VOIX' THEN NBRE_SUBS ELSE 0 END) AS SUBS_VOICE_COUNT,
            SUM(CASE WHEN UPPER(USAGE_MKT) = 'SMS' THEN NBRE_SUBS ELSE 0 END) AS SUBS_SMS_COUNT,
            SUM(CASE WHEN UPPER(USAGE_MKT) = 'DATA' THEN NBRE_SUBS ELSE 0 END) AS SUBS_DATA_COUNT,
            SUM(CASE WHEN UPPER(USAGE_MKT) = 'VOIX' THEN RATED_AMOUNT ELSE 0 END) AS SUBS_VOICE_AMOUNT,
            SUM(CASE WHEN UPPER(USAGE_MKT) = 'SMS' THEN RATED_AMOUNT ELSE 0 END) AS SUBS_SMS_AMOUNT,
            SUM(CASE WHEN UPPER(USAGE_MKT) = 'DATA' THEN RATED_AMOUNT ELSE 0 END) AS SUBS_DATA_AMOUNT,
            SUM(DATA_VIA_OM) AS DATA_VIA_OM
        FROM
        (
            SELECT
                MSISDN,
                USAGE_MKT,
                SUM(TOTAL_OCCURENCE) AS NBRE_SUBS,
                SUM(RATED_AMOUNT) AS RATED_AMOUNT,
                SUM(CASE WHEN SUBSCRIPTION_CHANNEL='32' THEN RATED_AMOUNT ELSE 0 END ) DATA_VIA_OM
            FROM
            (
                SELECT
                    H010.SERVED_PARTY_MSISDN AS MSISDN,
                    H010.SUBSCRIPTION_SERVICE_DETAILS,
                    H010.TOTAL_OCCURENCE,
                    H010.RATED_AMOUNT,
                    H010.SUBSCRIPTION_CHANNEL
                FROM MON.SPARK_FT_SUBSCRIPTION H010
                WHERE H010.TRANSACTION_DATE = '###SLICE_VALUE###'
            ) H01
            LEFT JOIN
            (
                SELECT
                    H020.EVENT
                    , NVL(H020.USAGE_MKT, 'AUTRES') AS USAGE_MKT
                FROM DIM.DT_SERVICES H020
            ) H02
            ON H01.SUBSCRIPTION_SERVICE_DETAILS = H02.EVENT
            GROUP BY H01.MSISDN, H02.USAGE_MKT
        ) H0 GROUP BY MSISDN
    ) H ON A.MSISDN = H.MSISDN
    LEFT JOIN
    (
        SELECT
            MSISDN,
            SUM(AMOUNT) ED_AMOUNT,
            MAX(TRANSACTION_TYPE) ED_TRANSACTION_TYPE,
            SUM(BYTES_OBTAINED) ED_BYTES_OBTAINED,
            MAX(CONTACT_CHANNEL) ED_CONTACT_CHANNEL
        FROM (
            SELECT
                I01.MSISDN,
                FIRST_VALUE(I01.TRANSACTION_TYPE) OVER (PARTITION BY I01.MSISDN ORDER BY cast(I01.transaction_time as int) DESC) TRANSACTION_TYPE,
                I01.AMOUNT,
                I01.BYTES_OBTAINED,
                FIRST_VALUE(I01.CONTACT_CHANNEL) OVER (PARTITION BY I01.MSISDN ORDER BY cast(I01.transaction_time as int) DESC) CONTACT_CHANNEL
            FROM MON.SPARK_FT_EMERGENCY_DATA I01
            WHERE I01.TRANSACTION_DATE = '###SLICE_VALUE###'
        ) I0
        GROUP BY I0.MSISDN
    ) I ON A.MSISDN = I.MSISDN
    LEFT JOIN
    (
        SELECT
            MSISDN,
            SUM(TRANSACTION_AMOUNT) OMNY_TRANSACTION_AMOUNT,
            SUM(COMMISSIONS_PAID) OMNY_COMMISSIONS_PAID,
            SUM(COMMISSIONS_RECEIVED) OMNY_COMMISSIONS_RECEIVED,
            SUM(COMMISSIONS_OTHERS) OMNY_COMMISSIONS_OTHERS,
            SUM(SERVICE_CHARGE_RECEIVED) OMNY_SERVICE_CHARGE_RECEIVED,
            SUM(SERVICE_CHARGE_PAID) OMNY_SERVICE_CHARGE_PAID,
            SUM(TAXES) OMNY_TAXES,
            MAX(SERVICE_TYPE) OMNY_SERVICE_TYPE,
            MAX(SENDER_PRE_BAL) OMNY_SENDER_PRE_BAL,
            MAX(SENDER_POST_BAL) OMNY_SENDER_POST_BAL,
            MAX(RECEIVER_PRE_BAL) OMNY_RECEIVER_PRE_BAL,
            MAX(RECEIVER_POST_BAL) OMNY_RECEIVER_POST_BAL
        FROM (
            SELECT
                J01.SENDER_MSISDN MSISDN,
                FIRST_VALUE(J01.SERVICE_TYPE) OVER (PARTITION BY J01.SENDER_MSISDN ORDER BY J01.TRANSFER_DATETIME DESC) SERVICE_TYPE,
                J01.TRANSACTION_AMOUNT,
                J01.COMMISSIONS_PAID,
                J01.COMMISSIONS_RECEIVED,
                J01.COMMISSIONS_OTHERS,
                J01.SERVICE_CHARGE_RECEIVED,
                J01.SERVICE_CHARGE_PAID,
                J01.TAXES,
                FIRST_VALUE(J01.SENDER_PRE_BAL) OVER (PARTITION BY J01.SENDER_MSISDN ORDER BY J01.TRANSFER_DATETIME_NQ DESC) SENDER_PRE_BAL,
                FIRST_VALUE(J01.SENDER_POST_BAL) OVER (PARTITION BY J01.SENDER_MSISDN ORDER BY J01.TRANSFER_DATETIME_NQ DESC) SENDER_POST_BAL,
                FIRST_VALUE(J01.RECEIVER_PRE_BAL) OVER (PARTITION BY J01.SENDER_MSISDN ORDER BY J01.TRANSFER_DATETIME_NQ DESC) RECEIVER_PRE_BAL,
                FIRST_VALUE(J01.RECEIVER_POST_BAL) OVER (PARTITION BY J01.SENDER_MSISDN ORDER BY J01.TRANSFER_DATETIME_NQ DESC) RECEIVER_POST_BAL
            FROM CDR.SPARK_IT_OMNY_TRANSACTIONS J01
            WHERE J01.ORIGINAL_FILE_DATE = '###SLICE_VALUE###'
        ) J0
        GROUP BY J0.MSISDN
    ) J ON A.MSISDN = J.MSISDN
    LEFT JOIN
    ( ------------------ IL FAUT CHANGER CECI POUR PRENDRE PLUTOT DANS IT_BDI ------------------
        SELECT
            *
        FROM MON.SPARK_FT_BDI K0
        WHERE K0.EVENT_DATE='2020-02-22'
    ) K ON A.MSISDN = K.MSISDN
    LEFT JOIN
    (
        SELECT
            MSISDN,
            SUBSTR(IMEI_MOST_USED,1,8) AS TER_TAC_CODE,
            SUBSTR(IMEI_MOST_USED,1,8) AS TER_IMEI,
            CONSTRUCTOR AS TER_CONSTRUCTOR,
            MODEL AS TER_MODEL,
            TECHNOLOGIE AS TER_2G_3G_4G_COMPATIBILITY,
            (CASE WHEN TECHNOLOGIE = '2G' THEN 'O' ELSE 'N' END) AS TER_2G_COMPATIBILITY,
            (CASE WHEN TECHNOLOGIE IN ('2.5G', '2.75G', '3G') THEN 'O' ELSE 'N' END) AS TER_3G_COMPATIBILITY,
            (CASE WHEN TECHNOLOGIE = '4G' THEN 'O' ELSE 'N' END) AS TER_4G_COMPATIBILITY
        FROM
        (
            SELECT
                DISTINCT L01.MSISDN,
                L01.IMEI_MOST_USED
            FROM
            (
                SELECT
                    L02.MSISDN
                    , FIRST_VALUE(L02.IMEI) OVER (PARTITION BY L02.MSISDN ORDER BY L02.TOTAL_DAYS_COUNT DESC) IMEI_MOST_USED
                FROM (
                    SELECT
                        L03.MSISDN
                        , SUBSTR(L03.IMEI, 1, 14) IMEI
                        , COUNT(DISTINCT L03.SDATE) TOTAL_DAYS_COUNT
                    FROM MON.SPARK_FT_IMEI_ONLINE L03
                    WHERE L03.SDATE='###SLICE_VALUE###'
                    GROUP BY SUBSTR(L03.IMEI, 1, 14), L03.MSISDN
                ) L02
            ) L01
        ) L0
        LEFT JOIN 
            DIM.DT_HANDSET_REF L1
        ON SUBSTR(L0.IMEI_MOST_USED,1,8) = L1.TAC_CODE
    ) L ON A.MSISDN = L.MSISDN
    LEFT JOIN
    (
        SELECT
            M0.MSISDN
            , M0.INSCRIPTEUR
            , M0.MIDATEDEP
            , M0.MTT_DEPOT
            , M0.NB_DEPOT
            , NULL IDSPEC
            , M0.FIRSTDEPOT
            , M0.FIRSTTRAN
            , M0.DEST_TRAN
            , M0.SERV_TRAN
            , M0.MIDATETR
            , M0.MTT_TRANS
            , M0.NB_TRANSACTION
            , M0.REG_LEVEL
            , M0.SEUIL_OK
            , M0.AUTO_INSCRIPTION
            , M0.BOUCLE_P2P
            , M0.DOUBLE_PROFIL
            , M0.BOUCLE
            , M0.CONFORMITE
        FROM MON.SPARK_FT_OMNY_SDT M0
        WHERE M0.DATE_INSCRIPT = '###SLICE_VALUE###'
    ) M on A.MSISDN = M.MSISDN
) T