INSERT INTO CTI.FT_APPELS_CTI_PREMIUM_VIP PARTITION (EVENT_DATE)
SELECT EVENT_TIME, ANI, DNIS, LAST_VQ, TECHNICAL_RESULT, RESULT_REASON, DUREE_CONVERSATION, UD_site_choisi, INTERACTION_TYPE,
    RESOURCE_NAME, a.Nom, DUREE_FILE, UD_site_cible, a.SEGMENT, TYPE_MSISDN, CURRENT_TIMESTAMP() INSERT_DATE, TO_DATE(EVENT_TIME) EVENT_DATE
FROM ( SELECT DISTINCT EVENT_TIME, TS, CONNID, ANI, DNIS, LAST_VQ, TECHNICAL_RESULT, TECHNICAL_RESULT_CODE, RESULT_REASON, RESULT_REASON_CODE, DUREE_CONVERSATION, PLACE_KEY,
 UD_site_choisi, INTERACTION_TYPE, INTERACTION_TYPE_CODE, PLACE, RESOURCE_TYPE, RESOURCE_NAME, Nom, DUREE_FILE, UD_site_cible,TECHNICAL_DESCRIPTOR_KEY, Segment
FROM CTI.IT_IRF_USER_DATA_CUST WHERE EVENT_DATE = '###SLICE_VALUE###' ) a -- and upper(NVL(INTERACTION_TYPE, ''))='INBOUND'
JOIN (SELECT DISTINCT MSISDN, 'PREMIUM' TYPE_MSISDN FROM DIM.DT_CTI_PREMIUM_NUMBER UNION SELECT DISTINCT MOBILE, 'VIP' TYPE_MSISDN FROM CTI.DT_VIP_MSISDN)b  on a.ANI = b.msisdn
