CREATE TABLE SPOOL.SPOOL_VAS_OCM

(
PERIODE_REFERENCE DATE,
PARTNER_FIRST_NAME varchar(90),
PARTNER_LAST_NAME varchar(90),
ACCOUNT_AGENCY varchar(8),
ACCOUNT_NUMBER varchar(90),
ACCOUNT_KEY varchar(4),
SUM_BAL_DEBUT decimal(17,2),
SUM_CREDIT decimal(17,2),
SUM_DEBIT decimal(17,2),
SUM_BAL_ESTIME decimal(17,2),
INSERT_DATE timestamp
)

PARTITIONED BY (EVENT_DATE DATE)
STORED AS PARQUET TBLPROPERTIES ('PARQUET.COMPRESS' = 'SNAPPY')


