CREATE TABLE SPOOL.SPOOL_VAS_OCM

(
MSISDN varchar(40),
SERVICE varchar(20),
CODE varchar(40),
PARTNER varchar(20),
BILLING decimal(12,2),
BUNDLE varchar(5),
INSERT_DATE timestamp
)

PARTITIONED BY (TRANSACTION_DATE DATE)
STORED AS PARQUET TBLPROPERTIES ('PARQUET.COMPRESS' = 'SNAPPY')



