SELECT IF(T_1.SPOOL_COUNT = 0 AND T_2.FT_COUNTA > 0 AND T_3.FT_COUNTB > 0,"OK","NOK") FT_EXIST
FROM
    (SELECT COUNT(*) SPOOL_COUNT FROM SPOOL.SPOOL_VAS_OCM WHERE TRANSACTION_DATE='###SLICE_VALUE###') T_1,
    (SELECT COUNT(*) FT_COUNTA FROM MON.SPARK_FT_OMNY_BALANCE_SNAPSHOT WHERE EVENT_DATE='###SLICE_VALUE###') T_2,
    (SELECT COUNT(*) FT_COUNTB FROM MON.SPARK_FT_OM_BICEC_TRANSACTION WHERE EVENT_DATE='###SLICE_VALUE###') T_3
