SELECT IF(COUNT(FILE_NAME)> 0, 'NOK','OK') RESULT
FROM (
      SELECT DISTINCT A.FILE_NAME
      FROM (SELECT SPLIT(INPUT__FILE__NAME, "/")[SIZE(SPLIT(INPUT__FILE__NAME, "/")) - 1] FILE_NAME FROM CDR.TT_ZTE_SUBSCRIPTION
      ) A
     ) C
WHERE EXISTS (SELECT 1 FROM CDR.IT_ZTE_SUBSCRIPTION B WHERE CREATEDDATE BETWEEN '2018-10-05' AND '2018-10-12' AND B.ORIGINAL_FILE_NAME = C.FILE_NAME)
