CREATE TABLE CDR.SPARK_IT_ZTE_CHECK_FILE_ALL (
   FILE_NAME VARCHAR (100),
   FILE_TYPE VARCHAR(50),
   ORIGINAL_FILE_NAME VARCHAR (100),
   ORIGINAL_FILE_DATE DATE,
   INSERT_DATE TIMESTAMP
)
PARTITIONED BY (FILE_DATE DATE)
CLUSTERED BY (FILE_TYPE) INTO 5 BUCKETS
STORED AS PARQUET TBLPROPERTIES ('PARQUET.COMPRESS'='SNAPPY')