INSERT INTO CDR.IT_ZEBRA_MASTER PARTITION (TRANSACTION_DATE)
SELECT
	CHANNEL_USER_ID	,
	PARENT_USER_ID	,
	OWNER_USER_ID	,
	USER_TYPE	,
	EXTERNAL_CODE,
	PRIMARY_MSISDN	,
	USER_STATUS	,
	LOGIN_ID	,
	CATEGORY_CODE	,
	CATEGORY_NAME,
	GEOGRAPHICAL_DOMAIN_CODE,
	GEOGRAPHICAL_DOMAIN_NAME,
	CHANNEL_USER_NAME,
	CITY	,
	STATE	,
	COUNTRY	,
	ORIGINAL_FILE_NAME,	
	ORIGINAL_FILE_SIZE, 
	ORIGINAL_FILE_LINE_COUNT, 
    TO_DATE(FROM_UNIXTIME(UNIX_TIMESTAMP(SUBSTRING (ORIGINAL_FILE_NAME, -12, 8),'yyyyMMdd'))) ORIGINAL_FILE_DATE,
	CURRENT_TIMESTAMP() INSERT_DATE,
	TO_DATE(FROM_UNIXTIME(UNIX_TIMESTAMP(SUBSTRING (ORIGINAL_FILE_NAME, -12, 8),'yyyyMMdd'))) TRANSACTION_DATE
FROM CDR.TT_ZEBRA_MASTER C
--LEFT JOIN (SELECT DISTINCT  ORIGINAL_FILE_NAME FILE_NAME FROM CDR.IT_ZEBRA_MASTER WHERE TRANSACTION_DATE BETWEEN DATE_SUB(CURRENT_DATE,${hivevar:date_offset}) AND CURRENT_DATE )T ON T.FILE_NAME=C.ORIGINAL_FILE_NAME
--WHERE T.FILE_NAME IS NULL;