CREATE TABLE cdr.spark_it_zebra_master_balance (
    EVENT_TIME                 VARCHAR(2),
    CHANNEL_USER_ID            VARCHAR(50),
    USER_NAME                  VARCHAR(200),
    MOBILE_NUMBER              VARCHAR(50),
    CATEGORY                   VARCHAR(50),
    MOBILE_NUMBER_1            VARCHAR(50),
    GEOGRAPHICAL_DOMAIN        VARCHAR(50),
    PRODUCT                    VARCHAR(50),
    PARENT_USER_NAME           VARCHAR(200),
    OWNER_USER_NAME            VARCHAR(200),
    AVAILABLE_BALANCE          BIGINT,
    AGENT_BALANCE              BIGINT,
    ORIGINAL_FILE_NAME         VARCHAR(50),
    ORIGINAL_FILE_DATE         DATE,
    INSERT_DATE                TIMESTAMP,
    USER_STATUS                VARCHAR(200),
    TO_CHANGE                  VARCHAR(500),
    MODIFIED_ON                DATE,
    ORIGINAL_FILE_SIZE INT,
    ORIGINAL_FILE_LINE_COUNT INT
)
    COMMENT 'Subs Retail Zebra - FT'
    PARTITIONED BY (EVENT_DATE DATE)
    STORED AS PARQUET
    TBLPROPERTIES ("parquet.compress"="SNAPPY") trim(CHANNEL_USER_ID) CHANNEL_USER_ID

, trim(USER_NAME) USER_NAME
, trim(MOBILE_NUMBER) MOBILE_NUMBER
, trim(CATEGORY) CATEGORY
, trim(MOBILE_NUMBER_1) MOBILE_NUMBER_1
, trim(GEOGRAPHICAL_DOMAIN) GEOGRAPHICAL_DOMAIN
, trim(PRODUCT) PRODUCT
, trim(PARENT_USER_NAME) PARENT_USER_NAME
, trim(OWNER_USER_NAME) OWNER_USER_NAME
, AVAILABLE_BALANCE,
, AGENT_BALANCE,
, trim(USER_STATUS) USER_STATUS
    , TO_DATE(FROM_UNIXTIME(UNIX_TIMESTAMP(TRIM(MODIFIED_ON),'dd-month-yy'))) MODIFIED_ON
, TO_DATE(FROM_UNIXTIME(UNIX_TIMESTAMP(SUBSTRING (ORIGINAL_FILE_NAME, 1, 8),'yyyyMMdd'))) EVENT_DATE
, SUBSTR (TRIM (ORIGINAL_FILE_NAME, 10, 2 ) EVENT_TIME,
, ORIGINAL_FILE_NAME,
, TO_DATE(FROM_UNIXTIME(UNIX_TIMESTAMP(SUBSTRING (ORIGINAL_FILE_NAME, 1, 8),'yyyyMMdd')))  ORIGINAL_FILE_DATE,
, CURRENT_TIMESTAMP INSERT_DATE