CREATE TABLE MON.SPARK_FT_SDT_OM 
(
    EFF_INSCRIPTEUR VARCHAR(100), 
    NBR_SDT_CONFORME BIGINT, 
    NBR_INSCRIPTION BIGINT, 
    NBR_SDT_CONFORME_CUMULE BIGINT, 
    NBR_INSCRIPTION_CUMULE BIGINT,
    INSERT_DATE TIMESTAMP
)
PARTITIONED BY (DATE_INSCRIPT DATE)
STORED AS PARQUET
TBLPROPERTIES ('PARQUET.COMPRESS'='SNAPPY')