SELECT IF(T_1.FT_COUNT = 0 AND T_2.FT_AM > 1 AND T_3.FT_C2S > 1 and T_4.FT_SC > 1 ,"OK","NOK") FT_EXIST
FROM
    (SELECT COUNT(*) FT_COUNT FROM MON.SPARK_ACTIV_IDENTIF_DETAILS WHERE EVENT_DATE= '###SLICE_VALUE###') T_1,
    (SELECT COUNT(*) FT_AM FROM MON.SPARK_FT_ACTIVATION_MONTH1 WHERE EVENT_MONTH = substr('###SLICE_VALUE###',1,7) and ACTIVATION_DATE='###SLICE_VALUE###') T_2,
    (SELECT COUNT(*) FT_C2S FROM MON.SPARK_FT_REFILL WHERE REFILL_DATE = '###SLICE_VALUE###' AND REFILL_MEAN = "C2S")T_3,
    (SELECT COUNT(*) FT_SC  FROM MON.SPARK_FT_REFILL WHERE REFILL_DATE = '###SLICE_VALUE###' AND REFILL_MEAN = "SCRATCH")T_4