SELECT IF(T_1.FT_COUNT = 0 AND T_2.IT_ZTE_ACC_NBR_EXTRACT > 1 AND T_3.IT_ZTE_SUBS_EXTRACT > 1 AND T_4.IT_ZTE_PROD_EXTRACT > 1,"OK","NOK") FT_EXIST
FROM
(SELECT COUNT(*) FT_COUNT FROM MON.ACTIVATION_ALL_BY_DAY WHERE EVENT_DATE= '###SLICE_VALUE###') T_1,
(SELECT COUNT(*) IT_ZTE_ACC_NBR_EXTRACT FROM CDR.IT_ZTE_ACC_NBR_EXTRACT WHERE ORIGINAL_FILE_DATE=DATE_ADD("###SLICE_VALUE###",1)) T_2,
(SELECT COUNT(*) IT_ZTE_SUBS_EXTRACT FROM CDR.IT_ZTE_SUBS_EXTRACT WHERE ORIGINAL_FILE_DATE=DATE_ADD("###SLICE_VALUE###",1)) T_3,
(SELECT COUNT(*) IT_ZTE_PROD_EXTRACT FROM CDR.IT_ZTE_PROD_EXTRACT WHERE ORIGINAL_FILE_DATE=DATE_ADD("###SLICE_VALUE###",1)) T_4,
(SELECT COUNT(*) BASE_IDENTIFICATION FROM DIM.DT_BASE_IDENTIFICATION WHERE DATE_IDENTIFICATION="###SLICE_VALUE###") T_5