SELECT
    from_unixtime(unix_timestamp(TRANSFER_DATETIME) + 3600) DATETIME,
    SENDER_MSISDN MSISDN_A,
    RECEIVER_MSISDN MSISDN_B,
    TRANSACTION_TAG,
    TRANSFER_STATUS,
    ERROR_DESC CAUSE
FROM SPOOL.SPOOL_CX
WHERE EVENT_DATE = "###SLICE_VALUE###"
order by transfer_datetime