CREATE EXTERNAL TABLE IF NOT EXISTS CDR.TT_CUSTOMER_SP_OTARIE
(
   IDCUST	BIGINT
   ,SERVPROVIDER	VARCHAR(300)
   ,ORIGINAL_FILE_NAME	VARCHAR(300)
   ,ORIGINAL_FILE_SIZE INT
   ,ORIGINAL_FILE_LINE_COUNT INT
)
COMMENT 'OTARIE CUSTOMER SP External table'
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t'
LOCATION '/PROD/TT/OTARIE/CUSTOMER_SP'
TBLPROPERTIES ('serialization.null.format'='');