CREATE EXTERNAL TABLE CDR.tt_traffic_cust_cell_otarie (
  ORIGINAL_FILE_NAME VARCHAR(200),
  ORIGINAL_FILE_SIZE INT,
  ORIGINAL_FILE_LINE_COUNT INT,
  TRANSACTION_DATE  DATE,
  IDCUST  BIGINT,
  IDGGSN  BIGINT,
  IDRAT  BIGINT,
  IDTAC  BIGINT,
  IDCELL  BIGINT,
  STATE  VARCHAR(30),
  NBYTESDN  BIGINT,
  NBYTESUP  BIGINT
)
COMMENT 'external tables-TT'
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t'
LOCATION '/PROD/TT/OTARIE/TRAFFIC_CUST_CELL'
TBLPROPERTIES ('serialization.null.format'='')
;