CREATE TABLE CDR.SPARK_IT_DIM_REF_SITES (
    site_code  varchar(100) ,
    cellname  varchar(100) ,
    site_name  varchar(100) ,
    longitude  varchar(100) ,
    latitude  varchar(100) ,
    lac  varchar(100) ,
    ci_2g_3g varchar(100) ,
    idbts_4g varchar(100) ,
    ci bigint ,
    site_program varchar(100) ,
    typedesite varchar(100) ,
    towerheight  varchar(100) ,
    datemad  varchar(100) ,
    datemet  varchar(100) ,
    datearret  varchar(100) ,
    technosite varchar(100) ,
    technologie  varchar(100) ,
    frequences varchar(100) ,
    frequences2  varchar(100) ,
    categorie_site varchar(100) ,
    nombailleur  varchar(100) ,
    expirationbail varchar(100) ,
    typologiesite  varchar(100) ,
    typologiesite2 varchar(100) ,
    codepartenaire varchar(100) ,
    nbretenants  varchar(100) ,
    priorite varchar(100) ,
    config varchar(100) ,
    topology varchar(100) ,
    typologietrans varchar(100) ,
    aggregation  varchar(100) ,
    canaldetransmission  varchar(100) ,
    townname varchar(100) ,
    quartier varchar(100) ,
    region varchar(100) ,
    departement  varchar(100) ,
    arrondissement varchar(100) ,
    typedezone varchar(100) ,
    commercial_region  varchar(100) ,
    zonepmo  varchar(100) ,
    secteur_om varchar(100) ,
    zone varchar(50)  ,
    secteur  varchar(50) ,
    ORIGINAL_FILE_NAME VARCHAR(100),
    ORIGINAL_FILE_SIZE INT,
    ORIGINAL_FILE_LINE_COUNT INT,
    INSERT_DATE TIMESTAMP
)
PARTITIONED BY (ORIGINAL_FILE_DATE VARCHAR(100))
STORED AS PARQUET TBLPROPERTIES ('PARQUET.COMPRESS'='SNAPPY')
