INSERT INTO CDR.SPARK_IT_DIM_REF_SITES PARTITION (ORIGINAL_FILE_DATE)
SELECT
 (CASE WHEN codesite_new like '%N/A%' THEN null ELSE codesite_new END) site_code,
 (CASE WHEN cellule like '%N/A%' THEN null ELSE cellule END) cellname,
 (CASE WHEN nomdusite_new like '%N/A%' THEN null ELSE nomdusite_new END) site_name,
 (CASE WHEN longitude like '%N/A%' THEN null ELSE REPLACE(longitude, '.', ',') END) longitude,
 (CASE WHEN latitude like '%N/A%' THEN null ELSE REPLACE(latitude, '.', ',') END) latitude,
 (CASE WHEN LAC like '%N/A%' THEN null ELSE LAC END) LAC,
 (CASE WHEN CI like '%N/A%' THEN null ELSE CI END) CI_2G_3G,
 (CASE WHEN id_bts_new like '%N/A%' THEN null ELSE id_bts_new END) IDBTS_4G,
 (CASE WHEN techno_cell = '4G' THEN (CASE WHEN id_bts_new like '%N/A%' THEN null ELSE id_bts_new END) ELSE (CASE WHEN CI like '%N/A%' THEN null ELSE CI END) END) CI,
 (CASE WHEN programme like '%N/A%' THEN null ELSE programme END) site_program,
 (CASE WHEN type_de_site like '%N/A%' THEN null ELSE type_de_site END) typedesite,
 (CASE WHEN tower_height like '%N/A%' THEN null ELSE REPLACE(tower_height, '.', ',') END) towerheight,
 (CASE WHEN date_mad_site like '%N/A%' THEN null ELSE (CASE WHEN length(date_mad_site) = 5 THEN date_add('1899-12-30',int(date_mad_site)) ELSE date_mad_site END) END) datemad,
 (CASE WHEN date_met_site like '%N/A%' THEN null ELSE (CASE WHEN length(date_met_site) = 5 THEN date_add('1899-12-30',int(date_met_site)) ELSE date_met_site END) END) datemet,
 (CASE WHEN date_arret_site like '%N/A%' THEN null ELSE (CASE WHEN length(date_arret_site) = 5 THEN date_add('1899-12-30',int(date_arret_site)) ELSE date_arret_site END) END) datearret,
 (CASE WHEN techno_site like '%N/A%' THEN null ELSE techno_site END) technosite,
 (CASE WHEN techno_cell like '%N/A%' THEN null ELSE techno_cell END) technologie,
 (CASE WHEN frequence_cell like '%N/A%' THEN null ELSE frequence_cell END) frequences,
 (CASE WHEN frequences_site like '%N/A%' THEN null ELSE frequences_site END) frequences2,
 (CASE WHEN categorie_de_site like '%N/A%' THEN null ELSE categorie_de_site END) categorie_site,
 (CASE WHEN nom_bailleur like '%N/A%' THEN null ELSE nom_bailleur END) nombailleur,
 (CASE WHEN expiration__bail like '%N/A%' THEN null ELSE (CASE WHEN length(expiration__bail) = 5 THEN date_add('1899-12-30',int(expiration__bail)) ELSE expiration__bail END) END) expirationbail,
 (CASE WHEN typologie_site like '%N/A%' THEN null ELSE typologie_site END) typologiesite,
 (CASE WHEN typologie_site_2 like '%N/A%' THEN null ELSE typologie_site_2 END) typologiesite2,
 (CASE WHEN code_partenaire like '%N/A%' THEN null ELSE code_partenaire END) codepartenaire,
 (CASE WHEN nbre_tenants like '%N/A%' THEN null ELSE nbre_tenants END) nbretenants,
 (CASE WHEN priorite like '%N/A%' THEN null ELSE priorite END) priorite,
 (CASE WHEN config like '%N/A%' THEN null ELSE config END) config,
 (CASE WHEN topology like '%N/A%' THEN null ELSE topology END) topology,
 (CASE WHEN typologie_trans like '%N/A%' THEN null ELSE typologie_trans END) typologietrans,
 (CASE WHEN aggregation like '%N/A%' THEN null ELSE aggregation END) aggregation,
 (CASE WHEN canal_de_transmission like '%N/A%' THEN null ELSE canal_de_transmission END) canaldetransmission,
 (CASE WHEN localite like '%N/A%' THEN null ELSE localite END) townname,
 (CASE WHEN quartier like '%N/A%' THEN null ELSE quartier END) quartier,
 (CASE WHEN region like '%N/A%' THEN null ELSE region END) region,
 (CASE WHEN departement like '%N/A%' THEN null ELSE departement END) departement,
 (CASE WHEN arrondissement like '%N/A%' THEN null ELSE arrondissement END) arrondissement,
 (CASE WHEN type_de_zone like '%N/A%' THEN null ELSE type_de_zone END) typedezone,
 (CASE WHEN region_comerciale like '%N/A%' THEN null ELSE region_comerciale END) commercial_region,
 (CASE WHEN zone_pmo like '%N/A%' THEN null ELSE zone_pmo END) zonepmo,
 (CASE WHEN secteur_om like '%N/A%' THEN null ELSE secteur_om END) secteur_om,
  null zone,
  null secteur,
  ORIGINAL_FILE_NAME,
  ORIGINAL_FILE_SIZE,
  ORIGINAL_FILE_LINE_COUNT,
  CURRENT_TIMESTAMP() INSERT_DATE,
  SUBSTRING(ORIGINAL_FILE_NAME, -22, 6) ORIGINAL_FILE_DATE
FROM CDR.tt_dim_ref_sites C
LEFT JOIN (SELECT DISTINCT  ORIGINAL_FILE_NAME FILE_NAME FROM CDR.SPARK_IT_DIM_REF_SITES WHERE INSERT_DATE BETWEEN DATE_SUB(CURRENT_DATE,100) AND CURRENT_DATE )T ON T.FILE_NAME=C.ORIGINAL_FILE_NAME
WHERE T.FILE_NAME IS NULL
