INSERT INTO MON.SPARK_FT_PULSE_SPIDER_POINT
SELECT SUBSTR(NVL(TRANSACTION_DATE, '###SLICE_VALUE###'), 1,7) EVENT_MONTH, a.MSISDN_PARRAIN,
    nvl(B.MONTANT,0.00) MONTANT, nvl(B.NOMBRE_POINTS,0) NOMBRE_POINTS, nvl(B.NOMBRE_SOUSCRIPTIONS,0) NOMBRE_SOUSCRIPTIONS, nvl(B.NOMBRE_SOUSCRIPTEURS,0) NOMBRE_SOUSCRIPTEURS,
    nvl(B.MONTANT,0.00)+nvl(C.CUMUL_MONTANT,0.00) CUMUL_MONTANT, nvl(B.NOMBRE_POINTS,0)+nvl(C.CUMUL_POINTS,0) CUMUL_POINTS, nvl(B.NOMBRE_SOUSCRIPTIONS,0)+nvl(C.CUMUL_SOUSCRIPTIONS,0) CUMUL_SOUSCRIPTIONS,
    nvl(B.NOMBRE_SOUSCRIPTEURS,0)+nvl(C.CUMUL_SOUSCRIPTEURS,0) CUMUL_SOUSCRIPTEURS, nvl(B.NOMBRE_POINTS,0)+nvl(D.CUMUL_ANNUEL_POINTS,0) CUMUL_ANNUEL_POINTS,
    subs.def_lang_id langue, current_timestamp INSERT_DATE, NVL(TRANSACTION_DATE, '###SLICE_VALUE###') EVENT_DATE
FROM (
    SELECT DISTINCT MSISDN_PARRAIN FROM CDR.SPARK_IT_PULSE_SPIDER_PARRAIN a
    WHERE a.ORIGINAL_FILE_DATE <= '###SLICE_VALUE###'
) A LEFT JOIN (
    SELECT TRANSACTION_DATE, MSISDN_PARRAIN, SUM(RATED_AMOUNT) MONTANT, (10*COUNT(*))+TRUNC(SUM(RATED_AMOUNT)/25) NOMBRE_POINTS,
        COUNT(*) NOMBRE_SOUSCRIPTIONS, COUNT(DISTINCT SERVED_PARTY_MSISDN) NOMBRE_SOUSCRIPTEURS
    FROM TMP.TT_SOUSCRIPTION_PARRAINE WHERE TRANSACTION_DATE = '###SLICE_VALUE###'
        AND STATUT='OK'
    GROUP BY TRANSACTION_DATE, MSISDN_PARRAIN
) B ON A.MSISDN_PARRAIN = B.MSISDN_PARRAIN
LEFT JOIN MON.SPARK_FT_PULSE_SPIDER_POINT C ON A.MSISDN_PARRAIN = C.MSISDN_PARRAIN AND C.EVENT_DATE = date_sub('###SLICE_VALUE###',1) and C.EVENT_MONTH=SUBSTR('###SLICE_VALUE###',1,7)
LEFT JOIN MON.SPARK_FT_PULSE_SPIDER_POINT D ON A.MSISDN_PARRAIN = D.MSISDN_PARRAIN AND D.EVENT_DATE = date_sub('###SLICE_VALUE###',1)
LEFT JOIN ( SELECT a.*, row_number() OVER (PARTITION BY acc_nbr ORDER BY UPDATE_DATE DESC) rn FROM cdr.spark_it_zte_subs_extract a WHERE original_file_date = DATE_ADD('###SLICE_VALUE###', -1)) subs on subs.rn=1 and subs.acc_nbr = a.msisdn_parrain
