CREATE TABLE MON.SPARK_FT_PULSE_SPIDER_POINT (
EVENT_MONTH VARCHAR(10),
MSISDN_PARRAIN VARCHAR(15),
MONTANT DOUBLE,
NOMBRE_POINTS INT,
NOMBRE_SOUSCRIPTIONS INT,
NOMBRE_SOUSCRIPTEURS INT,
CUMUL_MONTANT DOUBLE,
CUMUL_POINTS INT,
CUMUL_SOUSCRIPTIONS INT,
CUMUL_SOUSCRIPTEURS INT,
CUMUL_ANNUEL_POINTS INT,
INSERT_DATE TIMESTAMP
)
PARTITIONED BY (EVENT_DATE DATE)
STORED AS PARQUET TBLPROPERTIES ('PARQUET.COMPRESS'='SNAPPY')