SELECT IF(A.FT_EXIST = 0 and B.FT_COUNT > 0, "OK", "NOK") FROM
(SELECT COUNT(*) FT_EXIST FROM MON.SPARK_FT_RECHARGE_BY_RETAILER_MONTH WHERE EVENT_MONTH = '###SLICE_VALUE###') A,
(SELECT COUNT(*) FT_COUNT FROM MON.SPARK_FT_REFILL where REFILL_DATE BETWEEN TO_DATE(CONCAT('###SLICE_VALUE###','-01')) AND LAST_DAY(CONCAT('###SLICE_VALUE###','-01'))) B