
-- Revenu Bundle Voice
INSERT INTO FT_BUSINESS_ACTIVITY
SELECT
    TRANSACTION_DATE,
    'RU_REV_BUN_VOICE' USAGE_CODE,
    'FT_SUBSCRIPTION' SOURCE_TABLE,
    SUM(AMOUNT_VOICE_ONNET + AMOUNT_VOICE_OFFNET + AMOUNT_VOICE_INTER) KPI,
    SYSDATE INSERT_DATE
FROM FT_SUBSCRIPTION
WHERE TRANSACTION_DATE IN ( SELECT DATECODE
FROM (SELECT DISTINCT DATECODE FROM DIM.DT_DATES
         WHERE DATECODE BETWEEN TRUNC(SYSDATE-dashboard_kpi_day_from) AND TRUNC(SYSDATE-dashboard_kpi_day_bef))
       MINUS
  SELECT DISTINCT TRANSACTION_DATE FROM FT_BUSINESS_ACTIVITY
        WHERE USAGE_CODE='RU_REV_BUN_VOICE'
        AND TRANSACTION_DATE BETWEEN TRUNC(SYSDATE-dashboard_kpi_day_from) AND TRUNC(SYSDATE-dashboard_kpi_day_bef))
GROUP BY TRANSACTION_DATE;

COMMIT;

-- Revenu PayGo Voice
INSERT INTO FT_BUSINESS_ACTIVITY
SELECT
    TRANSACTION_DATE,
    'RU_REV_PG_VOICE' USAGE_CODE,
    'FT_GSM_TRAFFIC_REVENUE_DAILY' SOURCE_TABLE,
    SUM(MAIN_RATED_AMOUNT) KPI,
    SYSDATE INSERT_DATE
FROM FT_GSM_TRAFFIC_REVENUE_DAILY
WHERE TRANSACTION_DATE IN ( SELECT DATECODE
FROM (SELECT DISTINCT DATECODE FROM DIM.DT_DATES
         WHERE DATECODE BETWEEN TRUNC(SYSDATE-dashboard_kpi_day_from) AND TRUNC(SYSDATE-dashboard_kpi_day_bef))
       MINUS
  SELECT DISTINCT TRANSACTION_DATE FROM FT_BUSINESS_ACTIVITY
        WHERE USAGE_CODE='RU_REV_PG_VOICE'
        AND TRANSACTION_DATE BETWEEN TRUNC(SYSDATE-dashboard_kpi_day_from) AND TRUNC(SYSDATE-dashboard_kpi_day_bef))
AND SERVICE_CODE LIKE '%VOX%'
AND CALL_DESTINATION_CODE NOT IN ('VAS', 'EMERG')
GROUP BY TRANSACTION_DATE;

COMMIT;

-- Revenue SMS
INSERT INTO FT_BUSINESS_ACTIVITY
SELECT
    TRANSACTION_DATE,
    'RU_REV_SMS' USAGE_CODE,
    'FT_GSM_TRAFFIC_REVENUE_DAILY|FT_SUBSCRIPTION' SOURCE_TABLE,
    SUM(AMOUNT) KPI,
    SYSDATE INSERT_DATE
FROM (
    SELECT
        TRANSACTION_DATE,
        SUM(MAIN_RATED_AMOUNT) AMOUNT
    FROM FT_GSM_TRAFFIC_REVENUE_DAILY
    WHERE TRANSACTION_DATE IN ( SELECT DATECODE
            FROM (SELECT DISTINCT DATECODE FROM DIM.DT_DATES
                     WHERE DATECODE BETWEEN TRUNC(SYSDATE-dashboard_kpi_day_from) AND TRUNC(SYSDATE-dashboard_kpi_day_bef))
                   MINUS
              SELECT DISTINCT TRANSACTION_DATE FROM FT_BUSINESS_ACTIVITY
                    WHERE USAGE_CODE='RU_REV_SMS'
                    AND TRANSACTION_DATE BETWEEN TRUNC(SYSDATE-dashboard_kpi_day_from) AND TRUNC(SYSDATE-dashboard_kpi_day_bef))
    AND SERVICE_CODE LIKE '%SMS%'
    AND CALL_DESTINATION_CODE NOT IN ('VAS', 'EMERG')
    GROUP BY TRANSACTION_DATE
    UNION ALL
    SELECT
        TRANSACTION_DATE,
        SUM(AMOUNT_SMS_ONNET + AMOUNT_SMS_OFFNET + AMOUNT_SMS_INTER + AMOUNT_SMS_ONNET) AMOUNT
    FROM FT_SUBSCRIPTION
    WHERE TRANSACTION_DATE IN ( SELECT DATECODE
            FROM (SELECT DISTINCT DATECODE FROM DIM.DT_DATES
                     WHERE DATECODE BETWEEN TRUNC(SYSDATE-dashboard_kpi_day_from) AND TRUNC(SYSDATE-dashboard_kpi_day_bef))
                   MINUS
              SELECT DISTINCT TRANSACTION_DATE FROM FT_BUSINESS_ACTIVITY
                    WHERE USAGE_CODE='RU_REV_SMS'
                    AND TRANSACTION_DATE BETWEEN TRUNC(SYSDATE-dashboard_kpi_day_from) AND TRUNC(SYSDATE-dashboard_kpi_day_bef))
    GROUP BY TRANSACTION_DATE
)
GROUP BY TRANSACTION_DATE;

COMMIT;


-- Revenue voice(paygo+bundle), sms
INSERT INTO FT_BUSINESS_ACTIVITY
SELECT TRANSACTION_DATE, 'RU_REV_VOI_SMS' USAGE_CODE, 'FT_BUSINESS_ACTIVIY' SOURCE_TABLE,
    SUM(CASE WHEN USAGE_CODE IN ('RU_REV_BUN_VOICE','RU_REV_PG_VOICE','RU_REV_SMS') THEN KPI ELSE 0 END) KPI, SYSDATE INSERT_DATE
FROM FT_BUSINESS_ACTIVITY
WHERE TRANSACTION_DATE IN (
    SELECT DATECODE
    FROM ((SELECT DISTINCT DATECODE FROM DIM.DT_DATES
             WHERE DATECODE BETWEEN TRUNC(SYSDATE-DASHBOARD_KPI_DAY_FROM) AND TRUNC(SYSDATE- DASHBOARD_KPI_DAY_BEF))
           MINUS
      SELECT DISTINCT TRANSACTION_DATE FROM FT_BUSINESS_ACTIVITY
            WHERE USAGE_CODE='RU_REV_VOI_SMS'
            AND TRANSACTION_DATE BETWEEN TRUNC(SYSDATE-DASHBOARD_KPI_DAY_FROM) AND TRUNC(SYSDATE-DASHBOARD_KPI_DAY_BEF))
    INTERSECT
    ( SELECT TRANSACTION_DATE FROM FT_BUSINESS_ACTIVITY
            WHERE USAGE_CODE IN ('RU_REV_BUN_VOICE','RU_REV_PG_VOICE','RU_REV_SMS')
            AND TRANSACTION_DATE BETWEEN TRUNC(SYSDATE-DASHBOARD_KPI_DAY_FROM) AND TRUNC(SYSDATE-DASHBOARD_KPI_DAY_BEF)
                        GROUP BY TRANSACTION_DATE
            HAVING COUNT(*) = 3)
    )
AND USAGE_CODE IN ('RU_REV_BUN_VOICE','RU_REV_PG_VOICE','RU_REV_SMS')
GROUP BY TRANSACTION_DATE;

COMMIT;

--Revenu Bundle DATA
INSERT INTO FT_BUSINESS_ACTIVITY
SELECT
    TRANSACTION_DATE,
    'RU_REV_BUN_DATA' USAGE_CODE,
    'FT_SUBSCRIPTION' SOURCE_TABLE,
    SUM(AMOUNT_DATA) KPI,
    SYSDATE INSERT_DATE
FROM FT_SUBSCRIPTION
WHERE TRANSACTION_DATE IN ( SELECT DATECODE
            FROM (SELECT DISTINCT DATECODE FROM DIM.DT_DATES
                     WHERE DATECODE BETWEEN TRUNC(SYSDATE-dashboard_kpi_day_from) AND TRUNC(SYSDATE-dashboard_kpi_day_bef))
                   MINUS
              SELECT DISTINCT TRANSACTION_DATE FROM FT_BUSINESS_ACTIVITY
                    WHERE USAGE_CODE='RU_REV_BUN_DATA'
                    AND TRANSACTION_DATE BETWEEN TRUNC(SYSDATE-dashboard_kpi_day_from) AND TRUNC(SYSDATE-dashboard_kpi_day_bef))
GROUP BY TRANSACTION_DATE;

COMMIT;

-- Revenu PayGo DATA
INSERT INTO FT_BUSINESS_ACTIVITY
SELECT
    DATECODE TRANSACTION_DATE,
    'RU_REV_PG_DATA' USAGE_CODE,
    'FT_A_GPRS_ACTIVITY' SOURCE_TABLE,
    SUM(TOTAL_COST) KPI,
    SYSDATE INSERT_DATE
FROM FT_A_GPRS_ACTIVITY
WHERE DATECODE IN ( SELECT DATECODE
            FROM (SELECT DISTINCT DATECODE FROM DIM.DT_DATES
                     WHERE DATECODE BETWEEN TRUNC(SYSDATE-dashboard_kpi_day_from) AND TRUNC(SYSDATE-dashboard_kpi_day_bef))
                   MINUS
              SELECT DISTINCT TRANSACTION_DATE FROM FT_BUSINESS_ACTIVITY
                    WHERE USAGE_CODE='RU_REV_PG_DATA'
                    AND TRANSACTION_DATE BETWEEN TRUNC(SYSDATE-dashboard_kpi_day_from) AND TRUNC(SYSDATE-dashboard_kpi_day_bef))
AND SERVICE_CLASS NOT LIKE '%GOS%'
GROUP BY DATECODE;

COMMIT;


-- Revenue data
INSERT INTO FT_BUSINESS_ACTIVITY
SELECT TRANSACTION_DATE, 'RU_REV_DATA' USAGE_CODE, 'FT_BUSINESS_ACTIVIY' SOURCE_TABLE,
    SUM(CASE WHEN USAGE_CODE IN('RU_REV_BUN_DATA','RU_REV_PG_DATA') THEN KPI ELSE 0 END) KPI, SYSDATE INSERT_DATE
FROM FT_BUSINESS_ACTIVITY
WHERE TRANSACTION_DATE IN (
    SELECT DATECODE
    FROM ((SELECT DISTINCT DATECODE FROM DIM.DT_DATES
             WHERE DATECODE BETWEEN TRUNC(SYSDATE-DASHBOARD_KPI_DAY_FROM) AND TRUNC(SYSDATE- DASHBOARD_KPI_DAY_BEF))
           MINUS
      SELECT DISTINCT TRANSACTION_DATE FROM FT_BUSINESS_ACTIVITY
            WHERE USAGE_CODE='RU_REV_DATA'
            AND TRANSACTION_DATE BETWEEN TRUNC(SYSDATE-DASHBOARD_KPI_DAY_FROM) AND TRUNC(SYSDATE-DASHBOARD_KPI_DAY_BEF))
    INTERSECT
    ( SELECT TRANSACTION_DATE FROM FT_BUSINESS_ACTIVITY
            WHERE USAGE_CODE IN ('RU_REV_BUN_DATA','RU_REV_PG_DATA')
            AND TRANSACTION_DATE BETWEEN TRUNC(SYSDATE-DASHBOARD_KPI_DAY_FROM) AND TRUNC(SYSDATE-DASHBOARD_KPI_DAY_BEF)
                        GROUP BY TRANSACTION_DATE
            HAVING COUNT(*) = 2)
    )
GROUP BY TRANSACTION_DATE;

COMMIT;



-- Revenue voice, sms, data
insert into ft_business_activity
select transaction_date, 'RU_REV_VOI_SMS_DAT' usage_code, 'FT_BUSINESS_ACTIVIY' SOURCE_TABLE,
    SUM(CASE WHEN USAGE_CODE IN('RU_REV_VOI_SMS','RU_REV_DATA') THEN KPI ELSE 0 END) KPI, SYSDATE INSERT_DATE
from ft_business_activity
where transaction_date IN (
    SELECT DATECODE
    FROM ((SELECT DISTINCT DATECODE FROM DIM.DT_DATES
             WHERE DATECODE BETWEEN TRUNC(SYSDATE-DASHBOARD_KPI_DAY_FROM) AND TRUNC(SYSDATE- DASHBOARD_KPI_DAY_BEF))
           MINUS
      SELECT DISTINCT TRANSACTION_DATE FROM FT_BUSINESS_ACTIVITY
            WHERE USAGE_CODE='RU_REV_VOI_SMS_DAT'
            AND TRANSACTION_DATE BETWEEN TRUNC(SYSDATE-DASHBOARD_KPI_DAY_FROM) AND TRUNC(SYSDATE-DASHBOARD_KPI_DAY_BEF))
    INTERSECT
    ( SELECT TRANSACTION_DATE FROM FT_BUSINESS_ACTIVITY
            WHERE USAGE_CODE IN ('RU_REV_VOI_SMS','RU_REV_DATA')
            AND TRANSACTION_DATE BETWEEN TRUNC(SYSDATE-DASHBOARD_KPI_DAY_FROM) AND TRUNC(SYSDATE-DASHBOARD_KPI_DAY_BEF)
                        GROUP BY TRANSACTION_DATE
            HAVING COUNT(*) = 2)
    )
group by transaction_date;

commit;

-- Revenu VAS
INSERT INTO FT_BUSINESS_ACTIVITY
SELECT
    TRANSACTION_DATE,
    'RU_REV_VAS' USAGE_CODE,
    'FT_GSM_TRAFFIC_REVENUE_DAILY|FT_A_GPRS_ACTIVITY' SOURCE_TABLE,
    SUM(AMOUNT) KPI,
    SYSDATE INSERT_DATE
FROM (
   SELECT
        TRANSACTION_DATE,
        SUM(MAIN_RATED_AMOUNT) AMOUNT
    FROM FT_GSM_TRAFFIC_REVENUE_DAILY
    WHERE TRANSACTION_DATE IN ( SELECT DATECODE
            FROM (SELECT DISTINCT DATECODE FROM DIM.DT_DATES
                     WHERE DATECODE BETWEEN TRUNC(SYSDATE-dashboard_kpi_day_from) AND TRUNC(SYSDATE-dashboard_kpi_day_bef))
                   MINUS
              SELECT DISTINCT TRANSACTION_DATE FROM FT_BUSINESS_ACTIVITY
                    WHERE USAGE_CODE='RU_REV_VAS'
                    AND TRANSACTION_DATE BETWEEN TRUNC(SYSDATE-dashboard_kpi_day_from) AND TRUNC(SYSDATE-dashboard_kpi_day_bef))
    AND CALL_DESTINATION_CODE IN ('VAS', 'EMERG')
    GROUP BY TRANSACTION_DATE
    UNION ALL
    SELECT
        DATECODE TRANSACTION_DATE,
        SUM(TOTAL_COST) KPI
    FROM FT_A_GPRS_ACTIVITY
    WHERE DATECODE IN ( SELECT DATECODE
            FROM (SELECT DISTINCT DATECODE FROM DIM.DT_DATES
                     WHERE DATECODE BETWEEN TRUNC(SYSDATE-dashboard_kpi_day_from) AND TRUNC(SYSDATE-dashboard_kpi_day_bef))
                   MINUS
              SELECT DISTINCT TRANSACTION_DATE FROM FT_BUSINESS_ACTIVITY
                    WHERE USAGE_CODE='RU_REV_VAS'
                    AND TRANSACTION_DATE BETWEEN TRUNC(SYSDATE-dashboard_kpi_day_from) AND TRUNC(SYSDATE-dashboard_kpi_day_bef))
    AND SERVICE_CLASS LIKE '%GOS%'
    GROUP BY DATECODE
)
GROUP BY TRANSACTION_DATE;

COMMIT;


-- Total voice traffic
INSERT INTO FT_BUSINESS_ACTIVITY
SELECT
    TRANSACTION_DATE,
    'RU_TOT_VOICE_TRAF' USAGE_CODE,
    'FT_GSM_TRAFFIC_REVENUE_DAILY' SOURCE_TABLE,
    SUM(DURATION/60) KPI,
    SYSDATE INSERT_DATE
FROM FT_GSM_TRAFFIC_REVENUE_DAILY
WHERE TRANSACTION_DATE IN ( SELECT DATECODE
            FROM (SELECT DISTINCT DATECODE FROM DIM.DT_DATES
                     WHERE DATECODE BETWEEN TRUNC(SYSDATE-dashboard_kpi_day_from) AND TRUNC(SYSDATE-dashboard_kpi_day_bef))
                   MINUS
              SELECT DISTINCT TRANSACTION_DATE FROM FT_BUSINESS_ACTIVITY
                    WHERE USAGE_CODE='RU_TOT_VOICE_TRAF'
                    AND TRANSACTION_DATE BETWEEN TRUNC(SYSDATE-dashboard_kpi_day_from) AND TRUNC(SYSDATE-dashboard_kpi_day_bef))
GROUP BY TRANSACTION_DATE;

COMMIT;

-- Total internet traffic
INSERT INTO FT_BUSINESS_ACTIVITY
SELECT
    DATECODE TRANSACTION_DATE,
    'RU_TOT_INT_TRAF' USAGE_CODE,
    'FT_A_GPRS_ACTIVITY' SOURCE_TABLE,
    SUM(BYTES_RECV + BYTES_SEND)/(1024*1024) KPI,
    SYSDATE INSERT_DATE
FROM FT_A_GPRS_ACTIVITY
WHERE DATECODE IN ( SELECT DATECODE
            FROM (SELECT DISTINCT DATECODE FROM DIM.DT_DATES
                     WHERE DATECODE BETWEEN TRUNC(SYSDATE-dashboard_kpi_day_from) AND TRUNC(SYSDATE-dashboard_kpi_day_bef))
                   MINUS
              SELECT DISTINCT TRANSACTION_DATE FROM FT_BUSINESS_ACTIVITY
                    WHERE USAGE_CODE='RU_TOT_INT_TRAF'
                    AND TRANSACTION_DATE BETWEEN TRUNC(SYSDATE-dashboard_kpi_day_from) AND TRUNC(SYSDATE-dashboard_kpi_day_bef))
GROUP BY DATECODE;

COMMIT;


-- Total Bonus traffic voice
INSERT INTO FT_BUSINESS_ACTIVITY
SELECT
    TRANSACTION_DATE,
    'RU_TOT_BONUS_TRAF_VOICE' USAGE_CODE,
    'FT_GSM_TRAFFIC_REVENUE_DAILY' SOURCE_TABLE,
    SUM(DURATION - RATED_DURATION)/(60) KPI,
    SYSDATE INSERT_DATE
FROM FT_GSM_TRAFFIC_REVENUE_DAILY
WHERE TRANSACTION_DATE IN ( SELECT DATECODE
            FROM (SELECT DISTINCT DATECODE FROM DIM.DT_DATES
                     WHERE DATECODE BETWEEN TRUNC(SYSDATE-dashboard_kpi_day_from) AND TRUNC(SYSDATE-dashboard_kpi_day_bef))
                   MINUS
              SELECT DISTINCT TRANSACTION_DATE FROM FT_BUSINESS_ACTIVITY
                    WHERE USAGE_CODE='RU_TOT_BONUS_TRAF_VOICE'
                    AND TRANSACTION_DATE BETWEEN TRUNC(SYSDATE-dashboard_kpi_day_from) AND TRUNC(SYSDATE-dashboard_kpi_day_bef))
AND SERVICE_CODE LIKE '%VOX%'
GROUP BY TRANSACTION_DATE;

COMMIT;


-- Active daily users
INSERT INTO FT_BUSINESS_ACTIVITY
select event_date,'RU_ACTIV_DAILY_USERS' USAGE_CODE, 'FT_GROUP_USER_BASE' SOURCE_TABLE, SUM(dailybase) DAILY_ACTIVE_DAY, SYSDATE INSERT_DATE
from
ft_group_user_base
where event_date IN ( SELECT DATECODE
            FROM (SELECT DISTINCT DATECODE FROM DIM.DT_DATES
                     WHERE DATECODE BETWEEN TRUNC(SYSDATE-dashboard_kpi_day_from) AND TRUNC(SYSDATE-dashboard_kpi_day_bef))
                   MINUS
              SELECT DISTINCT TRANSACTION_DATE FROM FT_BUSINESS_ACTIVITY
                    WHERE USAGE_CODE='RU_ACTIV_DAILY_USERS'
                    AND TRANSACTION_DATE BETWEEN TRUNC(SYSDATE-dashboard_kpi_day_from) AND TRUNC(SYSDATE-dashboard_kpi_day_bef))
GROUP BY EVENT_DATE;

COMMIT;

-- voice users
INSERT INTO FT_BUSINESS_ACTIVITY
SELECT
    EVENT_DATE TRANSACTION_DATE,
    'RU_DAILY_VOICE_USERS' USAGE_CODE,
    'FT_CONSO_MSISDN_DAY' SOURCE_TABLE,
    COUNT(MSISDN) KPI,
    SYSDATE INSERT_DATE
FROM FT_CONSO_MSISDN_DAY
WHERE EVENT_DATE IN ( SELECT DATECODE
            FROM (SELECT DISTINCT DATECODE FROM DIM.DT_DATES
                     WHERE DATECODE BETWEEN TRUNC(SYSDATE-dashboard_kpi_day_from) AND TRUNC(SYSDATE-dashboard_kpi_day_bef))
                   MINUS
              SELECT DISTINCT TRANSACTION_DATE FROM FT_BUSINESS_ACTIVITY
                    WHERE USAGE_CODE='RU_DAILY_VOICE_USERS'
                    AND TRANSACTION_DATE BETWEEN TRUNC(SYSDATE-dashboard_kpi_day_from) AND TRUNC(SYSDATE-dashboard_kpi_day_bef))
AND CONSO_TEL > 0
GROUP BY EVENT_DATE;

COMMIT;


-- Internet users
INSERT INTO FT_BUSINESS_ACTIVITY
SELECT
    EVENT_DATE TRANSACTION_DATE,
    'RU_ACT_DAILY_INT_USERS' USAGE_CODE,
    'FT_DATA_CONSO_MSISDN_DAY' SOURCE_TABLE,
    COUNT(MSISDN),
    SYSDATE INSERT_DATE
FROM FT_DATA_CONSO_MSISDN_DAY
WHERE EVENT_DATE IN ( SELECT DATECODE
            FROM (SELECT DISTINCT DATECODE FROM DIM.DT_DATES
                     WHERE DATECODE BETWEEN TRUNC(SYSDATE-dashboard_kpi_day_from) AND TRUNC(SYSDATE-dashboard_kpi_day_bef))
                   MINUS
              SELECT DISTINCT TRANSACTION_DATE FROM FT_BUSINESS_ACTIVITY
                    WHERE USAGE_CODE='RU_ACT_DAILY_INT_USERS'
                    AND TRANSACTION_DATE BETWEEN TRUNC(SYSDATE-dashboard_kpi_day_from) AND TRUNC(SYSDATE-dashboard_kpi_day_bef))
AND (BYTES_SENT + BYTES_RECEIVED > 0)
GROUP BY EVENT_DATE;

COMMIT;


-- ARPU Daily
INSERT INTO MON.FT_BUSINESS_ACTIVITY
SELECT TRANSACTION_DATE, 'RU_ARPU_DAILY' USAGE_CODE, 'FT_BUSINESS_ACTIVITY' SOURCE_TABLE,  SUM(REVENUE)/SUM(NB_ACTIVE_USERS) ARPU_DAILY, SYSDATE
FROM (
    SELECT TRANSACTION_DATE,
        USAGE_CODE,
        CASE WHEN USAGE_CODE = 'RU_REV_VOI_SMS_DAT' THEN KPI ELSE 0 END REVENUE,
        CASE WHEN USAGE_CODE = 'RU_ACTIV_DAILY_USERS' THEN KPI ELSE 0 END NB_ACTIVE_USERS
     FROM FT_BUSINESS_ACTIVITY
       WHERE USAGE_CODE IN ('RU_REV_VOI_SMS_DAT','RU_ACTIV_DAILY_USERS')
)
WHERE TRANSACTION_DATE IN (
    SELECT DATECODE
    FROM ((SELECT DISTINCT DATECODE FROM DIM.DT_DATES
             WHERE DATECODE BETWEEN TRUNC(SYSDATE-dashboard_kpi_day_from) AND TRUNC(SYSDATE-dashboard_kpi_day_bef))
           MINUS
      SELECT DISTINCT TRANSACTION_DATE FROM FT_BUSINESS_ACTIVITY
            WHERE USAGE_CODE='RU_ARPU_DAILY'
            AND TRANSACTION_DATE BETWEEN TRUNC(SYSDATE-dashboard_kpi_day_from) AND TRUNC(SYSDATE-dashboard_kpi_day_bef))
    INTERSECT
    ( SELECT TRANSACTION_DATE FROM FT_BUSINESS_ACTIVITY
            WHERE USAGE_CODE IN ('RU_REV_VOI_SMS_DAT','RU_ACTIV_DAILY_USERS')
            AND TRANSACTION_DATE BETWEEN TRUNC(SYSDATE-dashboard_kpi_day_from) AND TRUNC(SYSDATE-dashboard_kpi_day_bef)
            GROUP BY TRANSACTION_DATE
            HAVING COUNT(*) = 2)
    )
GROUP BY TRANSACTION_DATE;


COMMIT;


-- ARPU voice
insert into FT_BUSINESS_ACTIVITY
select transaction_date,'RU_ARPU_DAILY_VOICE' usage_code,'FT_BUSINESS_ACTIVITY' SOURCE_TABLE,   sum(REV_VOICE_KPI)/sum(VOICE_USERS_KPI) Voice_Arpu, sysdate
from
(
    select transaction_date
        , (case when usage_code = 'RU_DAILY_VOICE_USERS' then kpi else 0 end ) VOICE_USERS_KPI
        , (case when usage_code IN ('RU_REV_BUN_VOICE', 'RU_REV_PG_VOICE') then kpi else 0 end ) REV_VOICE_KPI
    from FT_BUSINESS_ACTIVITY a
    where usage_code in  ('RU_REV_BUN_VOICE', 'RU_REV_PG_VOICE','RU_DAILY_VOICE_USERS')
    and transaction_date in (
        SELECT datecode
        FROM ((SELECT DISTINCT datecode FROM DIM.DT_DATES
                 WHERE datecode BETWEEN TRUNC(SYSDATE-dashboard_kpi_day_from) AND TRUNC(SYSDATE- dashboard_kpi_day_bef))
               MINUS
          SELECT DISTINCT TRANSACTION_DATE FROM FT_BUSINESS_ACTIVITY
                WHERE USAGE_CODE='RU_ARPU_DAILY_VOICE'
                AND TRANSACTION_DATE BETWEEN trunc(sysdate-dashboard_kpi_day_from) and trunc(sysdate-dashboard_kpi_day_bef))
        INTERSECT
        (SELECT TRANSACTION_DATE FROM FT_BUSINESS_ACTIVITY
                WHERE USAGE_CODE in ('RU_REV_BUN_VOICE', 'RU_REV_PG_VOICE','RU_DAILY_VOICE_USERS')
                AND TRANSACTION_DATE BETWEEN trunc(sysdate-dashboard_kpi_day_from) and trunc(sysdate-dashboard_kpi_day_bef)
                GROUP BY TRANSACTION_DATE
                HAVING COUNT(*) = 3 )
    )
)
group by transaction_date;

COMMIT;


-- ARPU Data
INSERT INTO FT_BUSINESS_ACTIVITY
SELECT
    TRANSACTION_DATE,
    'RU_ARPU_DAILY_DATA' USAGE_CODE,
    'FT_BUSINESS_ACTIVITY' SOURCE_TABLE,
    sum(REV_DATA_KPI)/sum(DATA_USERS_KPI) KPI,
    SYSDATE INSERT_DATE
FROM
(
    select transaction_date
        , (case when usage_code = 'RU_ACT_DAILY_INT_USERS' then kpi else 0 end ) DATA_USERS_KPI
        , (case when usage_code IN ('RU_REV_BUN_DATA', 'RU_REV_PG_DATA') then kpi else 0 end ) REV_DATA_KPI
    from FT_BUSINESS_ACTIVITY a
    where usage_code in  ('RU_REV_BUN_DATA', 'RU_REV_PG_DATA','RU_ACT_DAILY_INT_USERS')
    and transaction_date in (
        SELECT datecode
        FROM ((SELECT DISTINCT datecode FROM DIM.DT_DATES
                 WHERE datecode BETWEEN TRUNC(SYSDATE-dashboard_kpi_day_from) AND TRUNC(SYSDATE- dashboard_kpi_day_bef))
               MINUS
          SELECT DISTINCT TRANSACTION_DATE FROM FT_BUSINESS_ACTIVITY
                WHERE USAGE_CODE='RU_ARPU_DAILY_DATA'
                AND TRANSACTION_DATE BETWEEN trunc(sysdate-dashboard_kpi_day_from) and trunc(sysdate-dashboard_kpi_day_bef))
        INTERSECT
        (SELECT TRANSACTION_DATE FROM FT_BUSINESS_ACTIVITY
                WHERE USAGE_CODE in ('RU_REV_BUN_DATA', 'RU_REV_PG_DATA','RU_ACT_DAILY_INT_USERS')
                AND TRANSACTION_DATE BETWEEN trunc(sysdate-dashboard_kpi_day_from) and trunc(sysdate-dashboard_kpi_day_bef)
                GROUP BY TRANSACTION_DATE
                HAVING COUNT(*) = 3 )
    )
)
group by transaction_date;

COMMIT;


-- AUPU voice
INSERT INTO FT_BUSINESS_ACTIVITY
SELECT
    TRANSACTION_DATE,
    'RU_ARPU_VOICE' USAGE_CODE,
    'FT_BUSINESS_ACTIVITY' SOURCE_TABLE,
    SUM(REV_VOICE_KPI)/SUM(VOICE_USERS_KPI) KPI,
    SYSDATE INSERT_DATE
FROM (
    select transaction_date
        , (case when usage_code = 'RU_DAILY_VOICE_USERS' then kpi else 0 end ) VOICE_USERS_KPI
        , (case when usage_code IN ('RU_TOT_VOICE_TRAF', 'RU_TOT_BONUS_TRAF_VOICE') then kpi else 0 end ) REV_VOICE_KPI
    from FT_BUSINESS_ACTIVITY a
    where usage_code in  ('RU_TOT_VOICE_TRAF', 'RU_TOT_BONUS_TRAF_VOICE','RU_DAILY_VOICE_USERS')
    and transaction_date in (
        SELECT datecode
        FROM ((SELECT DISTINCT datecode FROM DIM.DT_DATES
                 WHERE datecode BETWEEN TRUNC(SYSDATE-dashboard_kpi_day_from) AND TRUNC(SYSDATE- dashboard_kpi_day_bef))
               MINUS
          SELECT DISTINCT TRANSACTION_DATE FROM FT_BUSINESS_ACTIVITY
                WHERE USAGE_CODE='RU_ARPU_VOICE'
                AND TRANSACTION_DATE BETWEEN trunc(sysdate-dashboard_kpi_day_from) and trunc(sysdate-dashboard_kpi_day_bef))
        INTERSECT
        (SELECT TRANSACTION_DATE FROM FT_BUSINESS_ACTIVITY
                WHERE USAGE_CODE in ('RU_TOT_VOICE_TRAF', 'RU_TOT_BONUS_TRAF_VOICE','RU_DAILY_VOICE_USERS')
                AND TRANSACTION_DATE BETWEEN trunc(sysdate-dashboard_kpi_day_from) and trunc(sysdate-dashboard_kpi_day_bef)
                GROUP BY TRANSACTION_DATE
                HAVING COUNT(*) = 3 )
    )
)
group by transaction_date;

commit;


-- AUPU DATA
INSERT INTO FT_BUSINESS_ACTIVITY
SELECT
    TRANSACTION_DATE,
    'RU_ARPU_DATA' USAGE_CODE,
    'FT_BUSINESS_ACTIVITY' SOURCE_TABLE,
    SUM(REV_DATA_KPI)/SUM(DATA_USERS_KPI) KPI,
    SYSDATE INSERT_DATE
FROM (
    select transaction_date
        , (case when usage_code = 'RU_ACT_DAILY_INT_USERS' then kpi else 0 end ) DATA_USERS_KPI
        , (case when usage_code IN ('RU_TOT_INT_TRAF') then kpi else 0 end ) REV_DATA_KPI
    from FT_BUSINESS_ACTIVITY a
    where usage_code in  ('RU_ACT_DAILY_INT_USERS', 'RU_TOT_INT_TRAF')
    and transaction_date in (
        SELECT datecode
        FROM ((SELECT DISTINCT datecode FROM DIM.DT_DATES
                 WHERE datecode BETWEEN TRUNC(SYSDATE-dashboard_kpi_day_from) AND TRUNC(SYSDATE- dashboard_kpi_day_bef))
               MINUS
          SELECT DISTINCT TRANSACTION_DATE FROM FT_BUSINESS_ACTIVITY
                WHERE USAGE_CODE='RU_ARPU_DATA'
                AND TRANSACTION_DATE BETWEEN trunc(sysdate-dashboard_kpi_day_from) and trunc(sysdate-dashboard_kpi_day_bef))
        INTERSECT
        (SELECT TRANSACTION_DATE FROM FT_BUSINESS_ACTIVITY
                WHERE USAGE_CODE in ('RU_ACT_DAILY_INT_USERS', 'RU_TOT_INT_TRAF')
                AND TRANSACTION_DATE BETWEEN trunc(sysdate-dashboard_kpi_day_from) and trunc(sysdate-dashboard_kpi_day_bef)
                GROUP BY TRANSACTION_DATE
                HAVING COUNT(*) = 2 )
    )
)
group by transaction_date;

COMMIT;

-- PPM voice
INSERT INTO FT_BUSINESS_ACTIVITY
SELECT
    TRANSACTION_DATE,
    'RU_PPM_VOICE' USAGE_CODE,
    'FT_BUSINESS_ACTIVITY' SOURCE_TABLE,
    SUM(REV_VOICE_KPI)/SUM(VOICE_USERS_KPI) KPI,
    SYSDATE INSERT_DATE
FROM (
    select transaction_date
        , (case when usage_code IN ('RU_TOT_VOICE_TRAF', 'RU_TOT_BONUS_TRAF_VOICE') then kpi else 0 end ) VOICE_USERS_KPI
        , (case when usage_code IN ('RU_REV_BUN_VOICE', 'RU_REV_PG_VOICE') then kpi else 0 end ) REV_VOICE_KPI
    from FT_BUSINESS_ACTIVITY a
    where usage_code in  ('RU_TOT_VOICE_TRAF', 'RU_TOT_BONUS_TRAF_VOICE','RU_REV_BUN_VOICE', 'RU_REV_PG_VOICE')
    and transaction_date in (
        SELECT datecode
        FROM ((SELECT DISTINCT datecode FROM DIM.DT_DATES
                 WHERE datecode BETWEEN TRUNC(SYSDATE-dashboard_kpi_day_from) AND TRUNC(SYSDATE- dashboard_kpi_day_bef))
               MINUS
          SELECT DISTINCT TRANSACTION_DATE FROM FT_BUSINESS_ACTIVITY
                WHERE USAGE_CODE='RU_PPM_VOICE'
                AND TRANSACTION_DATE BETWEEN trunc(sysdate-dashboard_kpi_day_from) and trunc(sysdate-dashboard_kpi_day_bef))
        INTERSECT
        (SELECT TRANSACTION_DATE FROM FT_BUSINESS_ACTIVITY
                WHERE USAGE_CODE in ('RU_TOT_VOICE_TRAF', 'RU_TOT_BONUS_TRAF_VOICE','RU_REV_BUN_VOICE', 'RU_REV_PG_VOICE')
                AND TRANSACTION_DATE BETWEEN trunc(sysdate-dashboard_kpi_day_from) and trunc(sysdate-dashboard_kpi_day_bef)
                GROUP BY TRANSACTION_DATE
                HAVING COUNT(*) = 4 )
    )
)
group by transaction_date;

COMMIT;


-- PPMo DATA
INSERT INTO FT_BUSINESS_ACTIVITY
SELECT
    TRANSACTION_DATE,
    'RU_PPM_DATA' USAGE_CODE,
    'FT_BUSINESS_ACTIVITY' SOURCE_TABLE,
    SUM(REV_DATA_KPI)/SUM(DATA_USERS_KPI) KPI,
    SYSDATE INSERT_DATE
FROM (
    select transaction_date
        , (case when usage_code = 'RU_TOT_INT_TRAF' then kpi else 0 end ) DATA_USERS_KPI
        , (case when usage_code IN  ('RU_REV_BUN_DATA', 'RU_REV_PG_DATA') then kpi else 0 end ) REV_DATA_KPI
    from FT_BUSINESS_ACTIVITY a
    where usage_code in ('RU_REV_BUN_DATA', 'RU_REV_PG_DATA', 'RU_TOT_INT_TRAF')
    and transaction_date in (
        SELECT datecode
        FROM ((SELECT DISTINCT datecode FROM DIM.DT_DATES
                 WHERE datecode BETWEEN TRUNC(SYSDATE-dashboard_kpi_day_from) AND TRUNC(SYSDATE- dashboard_kpi_day_bef))
               MINUS
          SELECT DISTINCT TRANSACTION_DATE FROM FT_BUSINESS_ACTIVITY
                WHERE USAGE_CODE='RU_PPM_DATA'
                AND TRANSACTION_DATE BETWEEN trunc(sysdate-dashboard_kpi_day_from) and trunc(sysdate-dashboard_kpi_day_bef))
        INTERSECT
        (SELECT TRANSACTION_DATE FROM FT_BUSINESS_ACTIVITY
                WHERE USAGE_CODE in ('RU_REV_BUN_DATA', 'RU_REV_PG_DATA', 'RU_TOT_INT_TRAF')
                AND TRANSACTION_DATE BETWEEN trunc(sysdate-dashboard_kpi_day_from) and trunc(sysdate-dashboard_kpi_day_bef)
                GROUP BY TRANSACTION_DATE
                HAVING COUNT(*) = 3)
    )
)
group by transaction_date;

COMMIT;

