SELECT IF(T_1.FT_A_RAS_IRSF = 0 and T_2.FT_MSC_TRANSACTION > 1 and T_3.FT_CONTRACT_SNAPSHOT > 1,"OK","NOK") FT_EXIST
FROM
    (SELECT COUNT(*) FT_A_RAS_OM_A FROM AGG.SPARK_FT_A_RAS_OM_A WHERE EVENT_DATE='###SLICE_VALUE###') T_1,
    (SELECT COUNT(*) FT_MSC_TRANSACTION FROM MON.SPARK_FT_MSC_TRANSACTION WHERE TRANSACTION_DATE='###SLICE_VALUE###') T_2,
    (SELECT COUNT(*) FT_CONTRACT_SNAPSHOT FROM MON.SPARK_FT_CONTRACT_SNAPSHOT WHERE EVENT_DATE='###SLICE_VALUE###') T_3
