CREATE TABLE IF NOT EXISTS CDR.IT_ZTE_IPP_EXTRACT_TMP (
    IPP_NAME            VARCHAR(500),
    IPP_CODE            INT,
    IPP_AMOUNT          DOUBLE,
    CREATED_DATE        DATE,
    ORIGINAL_FILE_NAME VARCHAR(60),
    ORIGINAL_FILE_SIZE INT,
    ORIGINAL_FILE_LINE_COUNT INT,
    INSERT_DATE TIMESTAMP
)
PARTITIONED BY (ORIGINAL_FILE_DATE DATE)
CLUSTERED BY(ORIGINAL_FILE_NAME) INTO 4 BUCKETS
STORED AS ORC
TBLPROPERTIES ("orc.compress"="ZLIB","orc.stripe.size"="67108864");
