CREATE TABLE CDR.SPARK_IT_ZTE_NOTIF_EXTRACT (
    ORIGINAL_FILE_NAME VARCHAR(200),
    ORIGINAL_FILE_SIZE INT,
    ORIGINAL_FILE_LINE_COUNT INT,
    NOTIF_TYPE VARCHAR(400),
    DESCRIPTION VARCHAR(1000),
    MSISDN VARCHAR(60),
    MESSAGE VARCHAR(4000),
    CREATED_DATE DATE,
    SUBMITTED_DATE DATE
    INSERT_DATE TIMESTAMP
)
PARTITIONED BY (ORIGINAL_FILE_DATE DATE)
CLUSTERED BY(MSISDN) INTO 8 BUCKETS
STORED AS PARQUET TBLPROPERTIES ('PARQUET.COMPRESS'='SNAPPY');


