CREATE TABLE CDR.IT_ZTE_PROD_SPEC_EXTRACT (
  PROD_SPEC_ID	INT,
  PROD_SPEC_TYPE	VARCHAR (200),
  PROD_SPEC_NAME	VARCHAR (200),
  COMMENTS	VARCHAR (200),
  STD_CODE	VARCHAR (200),
  EFF_DATE	VARCHAR (20),
  EXP_DATE	VARCHAR (20),
  STATE	VARCHAR (200),
  STATE_DATE	VARCHAR (20),
  SP_ID	INT,
  ORIGINAL_FILE_NAME VARCHAR(50),
  ORIGINAL_FILE_DATE DATE,
  INSERT_DATE TIMESTAMP
  )
STORED AS ORC 
TBLPROPERTIES ("orc.compress"="ZLIB","orc.stripe.size"="67108864");
