CREATE EXTERNAL TABLE IF NOT EXISTS CDR.IT_ZTE_DEL_EXPBAL (
  ACC_NBR BIGINT,
  SUBS_ID BIGINT,
  ACCT_ID BIGINT,
  BAL_ID  BIGINT,
  ACCT_RES_ID BIGINT,
  ACCT_RES_NAME VARCHAR(50),
  ACCT_BOOK_TYPE_NAME VARCHAR(50),
  CREATION_DATE VARCHAR(20),
  PARTY_TYPE  VARCHAR(20) ,
  PARTY_TYPE_NAME VARCHAR(20), 
  BALANCE_BEFORE  BIGINT,
  ADJUST_AMOUNT BIGINT,
  BALANCE_AFTER BIGINT,
  ADJUST_DAYS BIGINT,
  OLD_EXPIRY_DATE VARCHAR(20),
  ORIGINAL_FILE_NAME VARCHAR(100),
  ORIGINAL_FILE_SIZE INT,
  ORIGINAL_FILE_LINE_COUNT INT
  INSERT_DATE TIMESTAMP
  )
PARTITIONED BY (ORIGINAL_FILE_DATE DATE)
CLUSTERED BY(BAL_ID) INTO 4 BUCKETS
STORED AS ORC
TBLPROPERTIES ('transactional'='true',"orc.compress"="ZLIB","orc.stripe.size"="67108864");
