CREATE TABLE CDR.IT_ZTE_SUBS_EXTRACT (
	SUBS_ID	INT,
	IMSI2	VARCHAR(60),
	SP_ID	INT,
	IMSI	VARCHAR(60),
	PPS_PWD	VARCHAR(60),
	DEF_LANG_ID	INT,
	ROUTING_ID	INT,
	BONUS_AMOUNT	DOUBLE,
	CREDIT_LIMIT_PLAN_ID	INT,
	CREDIT_LIMIT	INT,
	UPDATE_DATE	TIMESTAMP,
	AREA_ID	INT,
	PREFIX	VARCHAR(60),
	ACC_NBR	VARCHAR(60),
	CUST_ID	INT,
	USER_ID	INT,
	ACCT_ID	INT,
	AGENT_ID	INT,
	PRICE_PLAN_ID	INT,
	ORIGINAL_FILE_NAME VARCHAR(50),
	ORIGINAL_FILE_SIZE INT,
	ORIGINAL_FILE_LINE_COUNT INT,
  	INSERT_DATE TIMESTAMP
)
PARTITIONED BY (ORIGINAL_FILE_DATE DATE)
CLUSTERED BY(ACC_NBR) INTO 8 BUCKETS
STORED AS ORC
TBLPROPERTIES ('transactional'='true',"orc.compress"="ZLIB","orc.stripe.size"="67108864");
