INSERT INTO CDR.IT_ZTE_ACCT_EXTRACT PARTITION (ORIGINAL_FILE_DATE)
SELECT
	ACCT_ID,
	CUST_ID,
	SP_ID,
	ROUTING_ID,
	POSTPAID,
	FROM_UNIXTIME(UNIX_TIMESTAMP(STATE_DATE, 'yyyyMMdd HHmmss')) STATE_DATE,
	STATE,
	FROM_UNIXTIME(UNIX_TIMESTAMP(UPDATE_DATE, 'yyyyMMdd HHmmss')) UPDATE_DATE,
	FROM_UNIXTIME(UNIX_TIMESTAMP(CREATED_DATE, 'yyyyMMdd HHmmss')) CREATED_DATE,
	BANK_ACCT_NAME,
	BANK_ACCT_NBR,
	BANK_ID,
	PAYMENT_TYPE,
	BILLING_CYCLE_TYPE_ID,
	ACCT_NBR,
	BILL_FORMAT_ID,
	ORIGINAL_FILE_NAME,
	ORIGINAL_FILE_SIZE,
	ORIGINAL_FILE_LINE_COUNT,
	CURRENT_TIMESTAMP() INSERT_DATE,
	TO_DATE(FROM_UNIXTIME(UNIX_TIMESTAMP(SUBSTRING (ORIGINAL_FILE_NAME, -12, 8),'yyyyMMdd'))) ORIGINAL_FILE_DATE
FROM CDR.TT_ZTE_ACCT_EXTRACT C
WHERE NOT EXISTS (
    SELECT 1 FROM RECEIVED_FILES B
    WHERE ORIGINAL_FILE_MONTH  BETWEEN DATE_FORMAT(DATE_SUB(CURRENT_DATE,${hivevar:date_offset}), 'yyyy-MM') AND DATE_FORMAT(CURRENT_DATE , 'yyyy-MM') 
    AND B.FILE_TYPE = 'ZTE_ACCT_EXTRACT' AND B.ORIGINAL_FILE_NAME = C.ORIGINAL_FILE_NAME
<<<<<<< HEAD
)
=======
);
>>>>>>> master
