INSERT INTO CDR.IT_ZTE_BAL_EXTRACT PARTITION (ORIGINAL_FILE_DATE)
SELECT
	BAL_ID,
	ACCT_ID,
	ACCT_RES_ID,
	GROSS_BAL,
	RESERVE_BAL,
	CONSUME_BAL,
	RATING_BAL,
	BILLING_BAL,
	FROM_UNIXTIME(UNIX_TIMESTAMP(EFF_DATE, 'yyyyMMdd HHmmss')) EFF_DATE,
	FROM_UNIXTIME(UNIX_TIMESTAMP(EXP_DATE, 'yyyyMMdd HHmmss')) EXP_DATE,
	FROM_UNIXTIME(UNIX_TIMESTAMP(UPDATE_DATE, 'yyyyMMdd HHmmss')) UPDATE_DATE,
	CEIL_LIMIT,
	FLOOR_LIMIT,
	DAILY_CEIL_LIMIT,
	DAILY_FLOOR_LIMIT,
	PRIORITY,
	LAST_BAL,
	LAST_RECHARGE,
	ORIGINAL_FILE_NAME,
	ORIGINAL_FILE_SIZE,
	ORIGINAL_FILE_LINE_COUNT,
	CURRENT_TIMESTAMP() INSERT_DATE,
	TO_DATE(FROM_UNIXTIME(UNIX_TIMESTAMP(SUBSTRING (ORIGINAL_FILE_NAME, -12, 8),'yyyyMMdd'))) ORIGINAL_FILE_DATE
FROM CDR.TT_ZTE_BAL_EXTRACT C
WHERE NOT EXISTS (
    SELECT 1 FROM RECEIVED_FILES B
    WHERE ORIGINAL_FILE_MONTH  BETWEEN DATE_FORMAT(DATE_SUB(CURRENT_DATE,${hivevar:date_offset}), 'yyyy-MM') AND DATE_FORMAT(CURRENT_DATE , 'yyyy-MM') 
    AND B.FILE_TYPE = 'ZTE_BAL_EXTRACT' AND B.ORIGINAL_FILE_NAME = C.ORIGINAL_FILE_NAME
<<<<<<< HEAD
)
=======
);
>>>>>>> master
