INSERT INTO CDR.IT_ZTE_PROD_SPEC_EXTRACT SELECT
   PROD_SPEC_ID,
  PROD_SPEC_TYPE,
  PROD_SPEC_NAME,
  COMMENTS,
  STD_CODE,
  EFF_DATE,
  EXP_DATE,
  STATE,
  STATE_DATE,
  SP_ID,
  ORIGINAL_FILE_NAME,
  TO_DATE(FROM_UNIXTIME(UNIX_TIMESTAMP(SUBSTRING(ORIGINAL_FILE_NAME,-12,8),'yyyyMMdd'))) ORIGINAL_FILE_DATE,
  CURRENT_TIMESTAMP() INSERT_DATE
FROM CDR.TT_ZTE_PROD_SPEC_EXTRACT C
WHERE NOT EXISTS (
    SELECT 1 FROM RECEIVED_FILES B
    WHERE ORIGINAL_FILE_MONTH  BETWEEN DATE_FORMAT(DATE_SUB(CURRENT_DATE,${hivevar:date_offset}), 'yyyy-MM') AND DATE_FORMAT(CURRENT_DATE , 'yyyy-MM') 
    AND B.FILE_TYPE = 'ZTE_PROD_SPEC_EXTRACT' AND B.ORIGINAL_FILE_NAME = C.ORIGINAL_FILE_NAME
);

--***************************
--- Log Filed received
-------------------------

INSERT INTO RECEIVED_FILES PARTITION(ORIGINAL_FILE_MONTH)
SELECT 
  ORIGINAL_FILE_NAME,
  'ZTE_PROD_SPEC_EXTRACT' FILE_TYPE,
  TO_DATE(FROM_UNIXTIME(UNIX_TIMESTAMP(SUBSTRING (ORIGINAL_FILE_NAME, -12, 8),'yyyyMMdd'))) ORIGINAL_FILE_DATE,
  MAX(ORIGINAL_FILE_SIZE),
  MAX(ORIGINAL_FILE_LINE_COUNT),
  CURRENT_TIMESTAMP,
  DATE_FORMAT(TO_DATE(FROM_UNIXTIME(UNIX_TIMESTAMP(SUBSTRING (ORIGINAL_FILE_NAME, -12, 8),'yyyyMMdd'))), 'yyyy-MM') ORIGINAL_FILE_MONTH
FROM CDR.TT_ZTE_PROD_SPEC_EXTRACT C
WHERE NOT EXISTS (SELECT 1 FROM RECEIVED_FILES B WHERE ORIGINAL_FILE_MONTH  BETWEEN DATE_FORMAT(DATE_SUB(current_date,${hivevar:date_offset}), 'yyyy-MM') 
                   AND DATE_FORMAT(current_date, 'yyyy-MM') AND B.FILE_TYPE = 'ZTE_PROD_SPEC_EXTRACT' AND B.ORIGINAL_FILE_NAME = C.ORIGINAL_FILE_NAME)
GROUP BY ORIGINAL_FILE_NAME;
