CREATE TABLE AGG.SPARK_FT_A_RAF_OTT(
 TRANSACTION_DATE  DATE,
 NBR_ABONNE        INT,
 CONSO_TOTAL       DOUBLE,
 MOY_CONSO_JOUR    DOUBLE,
 INSERT_DATE TIMESTAMP
) COMMENT 'SPARK_FT_A_RAF_OTT'
PARTITIONED BY (EVENT_DATE DATE)
 STORED AS PARQUET
 TBLPROPERTIES ("parquet.compress"="SNAPPY")