INSERT INTO AGG.SPARK_FT_A_RAF_OTT
SELECT TRANSACTION_DATE,
Count(msisdn) AS NBR_ABONNE,
sum (NBYTEST)/1048576 AS CONSO_TOTAL,
(sum (NBYTEST))/(1048576*(Count(msisdn))) AS MOY_CONSO_JOUR,
CURRENT_TIMESTAMP AS INSERT_DATE,
"###SLICE_VALUE###" EVENT_DATE
FROM MON.SPARK_FT_OTARIE_DATA_TRAFFIC_DAY --PARTITION (CBM_DATA_TRAFFIC_20180219)
WHERE APPLI_TYPE ='VoIP'
AND msisdn <>'0'
AND TRANSACTION_DATE ="###SLICE_VALUE###"
GROUP BY TRANSACTION_DATE,APPLI_TYPE