INSERT INTO CTI.SVI_APPEL_RECUS
SELECT 
DATE_DEBUT_OMS as JOUR,
SERVICE AS NUMERO_APPELE,
SEGMENT_CLIENT,
count(ID_APPEL) AS TOTAL_APP,
count(distinct MSISDN) AS TOTAL_CLI,
CURRENT_TIMESTAMP() INSERT_DATE,
DATE_DEBUT_OMS EVENT_DATE
from CTI.SVI_APPEL
where DATE_DEBUT_OMS = '###SLICE_VALUE###'
group by DATE_DEBUT_OMS,SERVICE,SEGMENT_CLIENT