INSERT INTO CTI.SVI_APPEL_RECUS
SELECT 
    DATE_DEBUT_OMS AS JOUR,
    SERVICE AS NUMERO_APPELE,
    SEGMENT_CLIENT,
    COUNT(ID_APPEL) AS TOTAL_APP,
    COUNT(DISTINCT MSISDN) AS TOTAL_CLI,
    CURRENT_TIMESTAMP() INSERT_DATE,
    DATE_DEBUT_OMS EVENT_DATE
FROM CTI.SVI_APPEL
WHERE DATE_DEBUT_OMS = '###SLICE_VALUE###'
GROUP BY DATE_DEBUT_OMS,
    SERVICE,
    SEGMENT_CLIENT