SELECT IF(T_1.FT_EXIST = 0 and T_2.SVI_APPEL>0  ,"OK","NOK") SVI_APPEL_RECUS
FROM
(SELECT COUNT(*) FT_EXIST FROM CTI.SVI_APPEL_RECUS WHERE EVENT_DATE='###SLICE_VALUE###') T_1,
(SELECT COUNT(*) SVI_APPEL FROM CTI.SVI_APPEL WHERE DATE_DEBUT_OMS='###SLICE_VALUE###') T_2