create table mon.spark_ft_sos_orange_reports
( MSISDN VARCHAR(100),
  SOS_TYPE VARCHAR(100),
  TRANSACTION_TYPE varchar(100),
  MONTANT BIGINT,
  COMMISSION  BIGINT,
  PRICE_PLAN_NAME VARCHAR(100),
  CONTACT_CHANNEL VARCHAR(100),
  REGION_ADMINISTRATIVE VARCHAR(100)
)PARTITIONED BY (EVENT_DATE DATE)
STORED AS PARQUET TBLPROPERTIES ("parquet.compress"="SNAPPY");