INSERT INTO SPOOL.SPOOL_RECYCLAGE_SANS_OM
SELECT MSISDN,
       CURRENT_TIMESTAMP() INSERT_DATE,
       EVENT_DATE
FROM MON.SPARK_FT_MSISDN_RECYCLE
WHERE EVENT_DATE='###SLICE_VVALUE###' 
and EST_PRESENT_OM='false' 
and recyclable=1 and CATEGORIE='RECYCLABLE SANS OM'