INSERT INTO SPOOL.SPOOL_RECYCLAGE_OM
SELECT MSISDN,
       PROD_STATE_DATE,
       PROD_STATE_NAME,
       OSP_ACCOUNT_TYPE,
       EST_PRESENT_OM,
       DUREE_INACTIVITE_OM,
       OM_BALANCE,
       CURRENT_TIMESTAMP() INSERT_DATE,
       EVENT_DATE
FROM MON.SPARK_FT_MSISDN_RECYCLE 
WHERE EVENT_DATE='###SLICE_VVALUE###' 
and EST_PRESENT_OM='true' 
and CATEGORIE='RECYCLABLE AVEC OM'