CREATE TABLE SPOOL.SPOOL_RECYCLAGE_SANS_OM
(
    MSISDN VARCHAR(100),
    INSERT_DATE TIMESTAMP
)
PARTITIONED BY (EVENT_DATE DATE)
STORED AS PARQUET TBLPROPERTIES ('PARQUET.COMPRESS'='SNAPPY')
