SELECT IF( MSC_EXISTS >0 AND FT_EXISTS=0,'OK','NOK') FROM
(SELECT COUNT(*) FT_EXISTS FROM MON.FT_PDM_TRANSACTION WHERE EVENT_DATE = DATE_SUB('###SLICE_VALUE###', 1)) T,
(SELECT COUNT(*) MSC_EXISTS FROM MON.FT_MSC_TRANSACTION WHERE TRANSACTION_DATE = '###SLICE_VALUE###' ) T1