INSERT INTO CDR.IT_POKE_CALL PARTITION(SETUPDATE)
SELECT
  SPLIT(CARDNUMBER,'=')[1] CARDNUMBER,
  SPLIT(SERVICEKEY,'=')[1] SERVICEKEY,
  SPLIT(CALLINGNUMBER,'=')[1] CALLINGNUMBER,
  SPLIT(CALLEDNUMBER,'=')[1] CALLEDNUMBER,
  FROM_UNIXTIME(UNIX_TIMESTAMP(SPLIT(SETUPTIME,'=')[1],'yyyy.MM.dd hh:mm:ss'))  SETUPTIME,
  FROM_UNIXTIME(UNIX_TIMESTAMP(SPLIT(TERMINATETIME,'=')[1],'yyyy.MM.dd hh:mm:ss'))  TERMINATETIME,
  SPLIT(RESULT,'=')[1] RESULT,
  SPLIT(CAUSEVALUE,'=')[1] CAUSEVALUE,
  SUBSTRING (INPUT__FILE__NAME, -50) ORIGINAL_FILE_NAME,
  TO_DATE(FROM_UNIXTIME(UNIX_TIMESTAMP(SUBSTRING (INPUT__FILE__NAME, -10, 8),'yyyyMMdd'))) ORIGINAL_FILE_DATE,
  CURRENT_TIMESTAMP INSERT_DATE,
  NULL ORIGINAL_FILE_SIZE,
  NULL ORIGINAL_FILE_LINE_COUNT,
  TO_DATE(FROM_UNIXTIME(UNIX_TIMESTAMP(SPLIT(SETUPTIME,'=')[1],'yyyy.MM.dd hh:mm:ss'))) SETUPDATE
FROM CDR.TT_POKE_CALL C
LEFT JOIN (SELECT DISTINCT  ORIGINAL_FILE_NAME FILE_NAME FROM CDR.IT_POKE_CALL WHERE SETUPDATE BETWEEN DATE_SUB(CURRENT_DATE,3) AND CURRENT_DATE )T ON T.FILE_NAME=SUBSTRING (C.INPUT__FILE__NAME, -50)
WHERE T.FILE_NAME IS NULL

