CREATE EXTERNAL TABLE CDR.tt_zte_balance_type (
  ORIGINAL_FILE_NAME VARCHAR(200),
  ORIGINAL_FILE_SIZE INT,
  ORIGINAL_FILE_LINE_COUNT INT,
  BALANCE_TYPE_ID DECIMAL(17,2),
  ACCT_ITEM_TYPE_ID DECIMAL(17,2),
  BALANCE_TYPE_NAME VARCHAR(80),
  BALANCE_TYPE_STD_CODE DECIMAL(17,2)
)
COMMENT 'external tables-TT'
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|'
LOCATION '/PROD/TT/IN_ZTE/BALANCE_TYPE'
TBLPROPERTIES ('serialization.null.format'='')
;
