CREATE  EXTERNAL TABLE CDR.TT_BDI_stk_ligne_flotte (
MSISDN VARCHAR(48),
 MSISDN_PARENT VARCHAR(48)
)COMMENT 'external tables-TT'
ROW FORMAT DELIMITED FIELDS TERMINATED BY ';'
LOCATION '/PROD/TT/BDI/FLOTTE/'
TBLPROPERTIES ('serialization.null.format'='');