
INSERT INTO MON.SPARK_FT_OM_TRANSACTION_USERS
SELECT  b.TRANSFER_DATE,
        b.TRANSFER_TIME,
        b.SENDER_MSISDN,
        b.RECEIVER_MSISDN_ACC,
        b.TRANSACTION_AMOUNT,
        b.SERVICE_TYPE,
        b.TRANSFER_STATUS,
        b.SENDER_PRE_BAL,
        b.SENDER_POST_BAL,
        b.RECEIVER_PRE_BAL,
        b.RECEIVER_POST_BAL,
        b.SENDER_ACC_STATUS,
        b.RECEIVER_ACC_STATUS,
        b.ERROR_CODE,
        b.ERROR_DESC,
        b.SENDER_CATEGORY_CODE,
        b.RECIEVER_CATEGORY_CODE,
        b.SENDER_CITY,
        b.RECEIVER_CITY,
        a.SERVICE_CHARGE_AMOUNT,
        CURRENT_TIMESTAMP AS INSERT_DATE
FROM
(
    SELECT *
    FROM CDR.SPARK_IT_OMNY_SERVICE_CHARGE
    WHERE TRANSACTION_DATE = '###SLICE_VALUE###'
) a
RIGHT JOIN
(
    SELECT *
    FROM CDR.SPARK_IT_OMNY_TRANSACTIONS_USER
    WHERE TRANSFER_DATE = '###SLICE_VALUE###'
) b ON a.TRANSACTIONID = b.TRANSFER_ID;
