SELECT IF(T_1.FT_EXIST = 0 and T_2.SPARK_IT_OMNY_SERVICE_CHARGE>0 and T_3.SPARK_IT_OMNY_TRANSACTIONS_USER>0,"OK","NOK")
FROM
(SELECT COUNT(*) FT_EXIST FROM MON.SPARK_FT_OM_TRANSACTION_USERS WHERE EVENT_DATE='###SLICE_VALUE###') T_1,
(SELECT COUNT(*) SPARK_IT_OMNY_SERVICE_CHARGE FROM CDR.SPARK_IT_OMNY_SERVICE_CHARGE WHERE TRANSFER_DATE='###SLICE_VALUE###') T_2,
(SELECT COUNT(*) SPARK_IT_OMNY_TRANSACTIONS_USER FROM CDR.SPARK_IT_OMNY_TRANSACTIONS_USER WHERE TRANSFER_DATE='###SLICE_VALUE###') T_3