SELECT IF(A.FT_EXIST = 0 and B.FT_COUNT>0 , "OK","NOK") FROM
(SELECT COUNT(*) FT_EXIST FROM MON.SPARK_FT_HUA_OPERATOR_OG_IC_SNAPSHOT WHERE EVENT_DATE='###SLICE_VALUE###') A,
(SELECT COUNT(*) FT_COUNT FROM MON.SPARK_FT_MSC_TRANSACTION WHERE TRANSACTION_DATE='###SLICE_VALUE###') B
