INSERT INTO SPOOL.SPOOL_BRI_MSISDN_ET_LOCALISATION_EN_INTERCO
SELECT
MSISDN,
NETWORK,
SITE_NAME,
TOWNNAME,
ADMINISTRATIVE_REGION,
CURRENT_TIMESTAMP INSERT_DATE,
'2020-06-05' EVENT_DATE

FROM
(
SELECT DISTINCT
    MSISDN,
    FIRST_CI AS CI,
    NETWORK
FROM
(
SELECT MSISDN AS MSISDN,
       CI,
       NETWORK,
       FIRST_VALUE(CI) OVER (PARTITION BY MSISDN ORDER BY COUNT(*) DESC) AS FIRST_CI
FROM MON.SPARK_FT_OTHER_PARTY_SITE_TRAFFIC
WHERE EVENT_DATE  BETWEEN TO_DATE(ADD_MONTHS(TO_DATE (concat('###SLICE_VALUE###','-01')), 0 )) AND  Last_day(TO_DATE (concat('###SLICE_VALUE###','-01')))
GROUP BY MSISDN, CI, NETWORK
) T
) a
LEFT JOIN (SELECT CI, SITE_NAME,TOWNNAME,ADMINISTRATIVE_REGION FROM VW_SDT_CI_INFO_NEW) b
ON a.CI = b.CI;