SELECT IF(
    T_1.FT_OTHER_PARTY_SITE_TRAFFIC = 0
    AND T_2.FT_MSC_TRANSACTION > 0
    , "OK"
    , "NOK"
) FT_EXIST
FROM
(SELECT COUNT(*) FT_OTHER_PARTY_SITE_TRAFFIC FROM MON.SPARK_FT_OTHER_PARTY_SITE_TRAFFIC WHERE EVENT_DATE = '###SLICE_VALUE###') T_1,
(SELECT COUNT(*) FT_MSC_TRANSACTION FROM MON.SPARK_FT_MSC_TRANSACTION WHERE TRANSACTION_DATE = '###SLICE_VALUE###') T_2