SELECT IF(T_1.FT_OTHER_PARTY_SITE_TRAFFIC = 0
 AND T_2.SPOOL_BRI_MSISDN_ET_LOCALISATION_EN_INTERCO =0
AND T_3.FT_MSC_TRANSACTION > 0
, "OK", "NOK") FT_EXIST
FROM
(SELECT COUNT(*) FT_OTHER_PARTY_SITE_TRAFFIC FROM MON.SPARK_FT_OTHER_PARTY_SITE_TRAFFIC WHERE EVENT_DATE = '###SLICE_VALUE###' LIMIT 10) T_1,
(SELECT COUNT(*)  SPOOL_BRI_MSISDN_ET_LOCALISATION_EN_INTERCO FROM SPOOL.SPOOL_BRI_MSISDN_ET_LOCALISATION_EN_INTERCO WHERE EVENT_DATE ='###SLICE_VALUE###' LIMIT 10) T_2,
(SELECT COUNT(*) FT_MSC_TRANSACTION FROM MON.SPARK_FT_MSC_TRANSACTION WHERE EVENT_DATE= '###SLICE_VALUE###' LIMIT 10) T_3