SELECT IF(T_1.FT_EXIST = 0 and T_2.CONTRACT_SNAPSHOT_EXIST>0,"OK","NOK") EXTRACT_EXIST
FROM
    (SELECT COUNT(*) FT_EXIST FROM AGG.SPARK_FT_GLOBAL_ACTIVITY_DAILY WHERE TRANSACTION_DATE='###SLICE_VALUE###' AND SOURCE_DATA ='IT_ZTE_ADJUSTMENT') T_1,
    (SELECT COUNT(*) CONTRACT_SNAPSHOT_EXIST FROM MON.SPARK_FT_CONTRACT_SNAPSHOT WHERE EVENT_DATE BETWEEN DATE_SUB('###SLICE_VALUE###',7) AND '###SLICE_VALUE###') T_2
