
CREATE TABLE MON.FT_A_POKE_CALL (
  STATUT VARCHAR(10),
  CAUSE_NAME VARCHAR(100),
  EVENT_COUNT INT,
  MAIN_RATED_AMOUNT DOUBLE,
  PROMO_RATED_AMOUNT DOUBLE,
  EVENT_DATE DATE,
  INSERT_DATE TIMESTAMP
)
STORED AS ORC
TBLPROPERTIES ('transactional'='true',"orc.compress"="ZLIB","orc.stripe.size"="67108864")

