CREATE TABLE CDR.SPARK_IT_PULSE_SPIDER_FORFAIT(
IPP_NAME VARCHAR(60),
IPP_CODE VARCHAR(15),
BEGIN_DATE DATE,
END_DATE DATE,
ORIGINAL_FILE_NAME VARCHAR(50),
ORIGINAL_FILE_SIZE INT,
ORIGINAL_FILE_LINE_COUNT INT,
INSERT_DATE TIMESTAMP
)
PARTITIONED BY (ORIGINAL_FILE_DATE DATE)
STORED AS PARQUET TBLPROPERTIES ('PARQUET.COMPRESS'='SNAPPY')
;