INSERT INTO CDR.SPARK_IT_PULSE_SPIDER_PARRAIN
SELECT
MSISDN_PARRAIN,
MSISDN_PARRAINE,
REGISTER_TIME,
ORIGINAL_FILE_NAME ,
ORIGINAL_FILE_SIZE ,
ORIGINAL_FILE_LINE_COUNT ,
CURRENT_TIMESTAMP() INSERT_DATE,
TO_DATE(FROM_UNIXTIME(UNIX_TIMESTAMP(SUBSTRING(ORIGINAL_FILE_NAME, -12, 8),'yyyyMMdd'))) ORIGINAL_FILE_DATE,
TO_DATE(SUBSTRING(REGISTER_DATE, 1, 10)) REGISTER_DATE
FROM CDR.TT_PULSE_SPIDER_PARRAIN C
LEFT JOIN (SELECT DISTINCT  ORIGINAL_FILE_NAME FILE_NAME FROM CDR.SPARK_IT_PULSE_SPIDER_PARRAIN WHERE ORIGINAL_FILE_DATE BETWEEN DATE_SUB(CURRENT_DATE,${hivevar:date_offset}) AND CURRENT_DATE )T ON T.FILE_NAME=C.ORIGINAL_FILE_NAME
WHERE T.FILE_NAME IS NULL

INSERT INTO CDR.SPARK_IT_PULSE_SPIDER_PARRAIN values
('657330045', '697127779', '2020-06-17 10:50:09', null, null, null, current_timestamp(),'2020-06-17', '2020-06-17' ),
('657294272', '694733209', '2020-06-15 10:25:11', null, null, null, current_timestamp(),'2020-06-15', '2020-06-15' ),
('699946323', '656125632', '2020-06-15 12:45:44', null, null, null, current_timestamp(),'2020-06-15', '2020-06-15' ),
('699946323', '695213779', '2020-06-16 08:31:05', null, null, null, current_timestamp(),'2020-06-16', '2020-06-16' )

INSERT INTO CDR.SPARK_IT_ACHAT_DATA_VIA_OM
SELECT
IDTXN,
MSISDN_PAYER,
MSISDN_PAYEE,
IPP_CODE,
BUNDLE_NAME,
BUNDLE_PRICE,
BUNDLE_DATA_QTY,
STATUS_TANGO_MP,
STATUS_IN_REQUEST,
TIMESTAMP_TXN,
ID_REQUEST_IN,
ORIGINAL_FILE_NAME ,
ORIGINAL_FILE_SIZE ,
ORIGINAL_FILE_LINE_COUNT ,
CURRENT_TIMESTAMP() INSERT_DATE,
TO_DATE(FROM_UNIXTIME(UNIX_TIMESTAMP(SUBSTRING(ORIGINAL_FILE_NAME, -12, 8),'ddMMyyyy'))) ORIGINAL_FILE_DATE
FROM CDR.TT_ACHAT_DATA_VIA_OM C
LEFT JOIN (SELECT DISTINCT  ORIGINAL_FILE_NAME FILE_NAME FROM CDR.SPARK_IT_ACHAT_DATA_VIA_OM WHERE ORIGINAL_FILE_DATE BETWEEN DATE_SUB(CURRENT_DATE,${hivevar:date_offset}) AND CURRENT_DATE )T ON T.FILE_NAME=C.ORIGINAL_FILE_NAME
WHERE T.FILE_NAME IS NULL


INSERT INTO CDR.SPARK_IT_OM_TRANSACTION_ROLLBACK
SELECT
INPUT_TXNID,
OUTPUT_MESSAGE,
OUTPUT_TXNID,
OUTPUT_TXNSTATUS,
ROLLBACK_DATE,
ROLLBACK_STATUS,
SUBSCRIBER_MSISDN,
TXN_AMOUNT,
CHANNEL_MSISDN,
SOURCE,
ORIGINAL_FILE_NAME ,
ORIGINAL_FILE_SIZE ,
ORIGINAL_FILE_LINE_COUNT ,
CURRENT_TIMESTAMP() INSERT_DATE,
TO_DATE(FROM_UNIXTIME(UNIX_TIMESTAMP(SUBSTRING(ORIGINAL_FILE_NAME, -12, 8),'ddMMyyyy'))) ORIGINAL_FILE_DATE
FROM CDR.TT_OM_TRANSACTION_ROLLBACK C
LEFT JOIN (SELECT DISTINCT  ORIGINAL_FILE_NAME FILE_NAME FROM CDR.SPARK_IT_OM_TRANSACTION_ROLLBACK WHERE ORIGINAL_FILE_DATE BETWEEN DATE_SUB(CURRENT_DATE,${hivevar:date_offset}) AND CURRENT_DATE )T ON T.FILE_NAME=C.ORIGINAL_FILE_NAME
WHERE T.FILE_NAME IS NULL
