INSERT INTO CDR.IT_P2P_LOG PARTITION (START_DATE)
SELECT
	TRIM(COMMAND_NAME) COMMAND_NAME,
	TRIM(USSD_ORDER) USSD_ORDER,
	TRIM(RETURN_CODE) RETURN_CODE,
	from_unixtime(unix_timestamp(TRIM(START_DATE_TIME), 'dd/MM/yyyy HH:mm:ss')) START_DATE_TIME,
	from_unixtime(unix_timestamp(TRIM(END_DATE_TIME), 'dd/MM/yyyy HH:mm:ss')) END_DATE_TIME,
	DURATION,
	TRIM(MSISDN_SRC) MSISDN_SRC,
	NVL(CREDIT_SRC, 0) CREDIT_SRC,
	from_unixtime(unix_timestamp(TRIM(VALIDITY_DATE_SRC), 'dd/MM/yyyy')) VALIDITY_DATE_SRC,
	from_unixtime(unix_timestamp(TRIM(INVALIDITY_DATE_SRC), 'dd/MM/yyyy')) INVALIDITY_DATE_SRC,
	TRIM(PROFILE_SRC) PROFILE_SRC,
	TRIM(MSISDN_DEST) MSISDN_DEST,
	NVL(CREDIT_DEST, 0) CREDIT_DEST,
	from_unixtime(unix_timestamp(TRIM(VALIDITY_DATE_DEST), 'dd/MM/yyyy')) VALIDITY_DATE_DEST,
	from_unixtime(unix_timestamp(TRIM(INVALIDITY_DATE_DEST), 'dd/MM/yyyy')) INVALIDITY_DATE_DEST,
	NVL(TRANSACTION_COST, 0) TRANSACTION_COST,
	NVL(TOTAL_AMOUNT_DEBIT, 0) TOTAL_AMOUNT_DEBIT,
	TRIM(ROLLBACK_FLAG) ROLLBACK_FLAG,
	TRIM(ROLLBACK_RESULT) ROLLBACK_RESULT,
	from_unixtime(unix_timestamp(TRIM(COMMAND_END_DATE), 'dd/MM/yyyy-HH:mm:ss')) COMMAND_END_DATE,
	(CASE
	WHEN TRIM (split(TRIM(USSD_ORDER), '-')[0]) = 'TRA' THEN
		(CASE
			WHEN LENGTH (TRIM (split(TRIM(USSD_ORDER), '-')[4])) = 9 THEN
				split(TRIM(USSD_ORDER), '-')[3]
			ELSE 0
		END )
	ELSE NULL
	END ) AMOUNT,
	ORIGINAL_FILE_NAME,
	FROM_UNIXTIME(UNIX_TIMESTAMP(SUBSTRING (ORIGINAL_FILE_NAME, -14, 10),'yyyy-MM-dd')) ORIGINAL_FILE_DATE,
	CURRENT_TIMESTAMP() INSERT_DATE,
	ORIGINAL_FILE_SIZE,
	ORIGINAL_FILE_LINE_COUNT,
	TO_DATE(from_unixtime(unix_timestamp(TRIM(START_DATE_TIME), 'dd/MM/yyyy HH:mm:ss'))) START_DATE
FROM CDR.TT_P2P_LOG  C
WHERE NOT EXISTS (
	SELECT 1 
	FROM RECEIVED_FILES B 
	WHERE ORIGINAL_FILE_MONTH  BETWEEN DATE_FORMAT(DATE_SUB(current_date,${hivevar:date_offset}), 'yyyy-MM') AND DATE_FORMAT(current_date, 'yyyy-MM') 
	AND B.FILE_TYPE = 'P2P_LOG'
	AND B.ORIGINAL_FILE_NAME = C.ORIGINAL_FILE_NAME
);

INSERT INTO RECEIVED_FILES PARTITION(ORIGINAL_FILE_MONTH)
SELECT
  ORIGINAL_FILE_NAME,
  'P2P_LOG' FILE_TYPE,
  TO_DATE(FROM_UNIXTIME(UNIX_TIMESTAMP(SUBSTRING (ORIGINAL_FILE_NAME, -14, 10),'yyyy-MM-dd'))) ORIGINAL_FILE_DATE,
  MAX(ORIGINAL_FILE_SIZE),
  MAX(ORIGINAL_FILE_LINE_COUNT),
  CURRENT_TIMESTAMP,
  DATE_FORMAT(TO_DATE(FROM_UNIXTIME(UNIX_TIMESTAMP(SUBSTRING (ORIGINAL_FILE_NAME, -14, 10),'yyyy-MM-dd'))), 'yyyy-MM') ORIGINAL_FILE_MONTH
FROM CDR.TT_P2P_LOG C
WHERE NOT EXISTS (
	SELECT 1 
	FROM RECEIVED_FILES B 
	WHERE ORIGINAL_FILE_MONTH  BETWEEN DATE_FORMAT(DATE_SUB(current_date,${hivevar:date_offset}), 'yyyy-MM') AND DATE_FORMAT(current_date, 'yyyy-MM') 
	AND B.FILE_TYPE = 'P2P_LOG' 
	AND B.ORIGINAL_FILE_NAME = C.ORIGINAL_FILE_NAME
)
GROUP BY ORIGINAL_FILE_NAME;