INSERT INTO TMP.SPARK_TT_USER_CONTRACT_TYPE
SELECT
    IF(A.MSISDN IS NULL OR B.MAIN_MSISDN IS NULL, NVL(B.MAIN_MSISDN, A.MSISDN), B.MAIN_MSISDN) MSISDN,
    IF(A.MSISDN IS NULL OR B.MAIN_MSISDN IS NULL, NVL(B.CONTRACT_TYPE, A.CONTRACT_TYPE), B.CONTRACT_TYPE) CONTRACT_TYPE,
    IF(A.MSISDN IS NULL OR B.MAIN_MSISDN IS NULL, NVL(B.STATUS_DATE, A.UPDATE_DATE), B.STATUS_DATE) UPDATE_DATE
FROM
    DIM.SPARK_DT_USER_CONTRACT_TYPE A
FULL OUTER JOIN
    (
        SELECT
            B.MAIN_MSISDN
            , IF(B.MAX_STATUS_DATE IS NULL, NULL, B.STATUS_DATE) STATUS_DATE
            , B.CONTRACT_TYPE
        FROM 
        (
            SELECT
                MAIN_MSISDN
                , STATUS_DATE
                , CONTRACT_TYPE
                , MAX(STATUS_DATE) OVER (PARTITION BY MAIN_MSISDN) MAX_STATUS_DATE
            FROM CDR.SPARK_IT_ACCOUNT
            WHERE ORIGINAL_FILE_DATE = "###SLICE_VALUE###"
        ) B
        WHERE (B.MAX_STATUS_DATE IS NOT NULL AND B.STATUS_DATE = B.MAX_STATUS_DATE) OR B.MAX_STATUS_DATE IS NULL
    ) B
ON
    A.MSISDN = B.MAIN_MSISDN