INSERT INTO MON.SPARK_FT_DAILY_LOST_ACCOUNT_REGION
SELECT
SITE_NAME
,sum(case when (OG_CALL = DATE_SUB("###SLICE_VALUE###",31) AND least(IC_CALL_4,IC_CALL_3,IC_CALL_2,IC_CALL_1) <= DATE_SUB("###SLICE_VALUE###",31))
OR
(least(IC_CALL_4,IC_CALL_3,IC_CALL_2,IC_CALL_1)= DATE_SUB("###SLICE_VALUE###",31) AND  OG_CALL<= DATE_SUB("###SLICE_VALUE###",31))
then 1 else 0 end) all30dayslost
--
,sum(case when (OG_CALL = DATE_SUB("###SLICE_VALUE###",41) AND least(IC_CALL_4,IC_CALL_3,IC_CALL_2,IC_CALL_1) <= DATE_SUB("###SLICE_VALUE###",41))
OR
(least(IC_CALL_4,IC_CALL_3,IC_CALL_2,IC_CALL_1)= DATE_SUB("###SLICE_VALUE###",41) AND  OG_CALL<= DATE_SUB("###SLICE_VALUE###",41))
then 1 else 0 end) all40dayslost
--
,sum(case when (OG_CALL = DATE_SUB("###SLICE_VALUE###",51) AND least(IC_CALL_4,IC_CALL_3,IC_CALL_2,IC_CALL_1) <= DATE_SUB("###SLICE_VALUE###",51))
OR
(least(IC_CALL_4,IC_CALL_3,IC_CALL_2,IC_CALL_1)= DATE_SUB("###SLICE_VALUE###",51) AND  OG_CALL<= DATE_SUB("###SLICE_VALUE###",51))
then 1 else 0 end) all50dayslost
--
,sum(case when (OG_CALL = DATE_SUB("###SLICE_VALUE###",61) AND least(IC_CALL_4,IC_CALL_3,IC_CALL_2,IC_CALL_1) <= DATE_SUB("###SLICE_VALUE###",61))
OR
(least(IC_CALL_4,IC_CALL_3,IC_CALL_2,IC_CALL_1)= DATE_SUB("###SLICE_VALUE###",61) AND  OG_CALL<= DATE_SUB("###SLICE_VALUE###",61))
then 1 else 0 end) all60dayslost
--
,sum(case when (OG_CALL = DATE_SUB("###SLICE_VALUE###",71) AND least(IC_CALL_4,IC_CALL_3,IC_CALL_2,IC_CALL_1) <= DATE_SUB("###SLICE_VALUE###",71))
OR
(least(IC_CALL_4,IC_CALL_3,IC_CALL_2,IC_CALL_1)= DATE_SUB("###SLICE_VALUE###",71) AND  OG_CALL<= DATE_SUB("###SLICE_VALUE###",71))
then 1 else 0 end) all70dayslost
--
,sum(case when (OG_CALL = DATE_SUB("###SLICE_VALUE###",81) AND least(IC_CALL_4,IC_CALL_3,IC_CALL_2,IC_CALL_1) <= DATE_SUB("###SLICE_VALUE###",81))
OR
(least(IC_CALL_4,IC_CALL_3,IC_CALL_2,IC_CALL_1)= DATE_SUB("###SLICE_VALUE###",81) AND  OG_CALL<= DATE_SUB("###SLICE_VALUE###",81))
then 1 else 0 end) all80dayslost
--
,sum(case when (OG_CALL = DATE_SUB("###SLICE_VALUE###",91) AND least(IC_CALL_4,IC_CALL_3,IC_CALL_2,IC_CALL_1) <= DATE_SUB("###SLICE_VALUE###",91))
OR
(least(IC_CALL_4,IC_CALL_3,IC_CALL_2,IC_CALL_1)= DATE_SUB("###SLICE_VALUE###",91) AND  OG_CALL<= DATE_SUB("###SLICE_VALUE###",91))
then 1 else 0 end) all90dayslost
,'SPARK_FT_ACCOUNT_ACTIVITY' src_table
,CURRENT_TIMESTAMP insert_date
,"###SLICE_VALUE###" EVENT_DATE
FROM
(SELECT * FROM MON.SPARK_FT_ACCOUNT_ACTIVITY WHERE EVENT_DATE = DATE_ADD("###SLICE_VALUE###",1)) a
LEFT JOIN
(SELECT MSISDN,max(SITE_NAME) SITE_NAME FROM MON.SPARK_FT_CLIENT_LAST_SITE_DAY WHERE EVENT_DATE="###SLICE_VALUE###" GROUP BY MSISDN) b
ON a.MSISDN=b.MSISDN
GROUP BY event_date,SITE_NAME