CREATE EXTERNAL TABLE CDR.TT_SERVICES_DYNAMIQUE
(
  MSISDN     VARCHAR(400),
  BDLE_NAME  VARCHAR(400 ),
  BDLE_COST  DOUBLE
)
COMMENT 'external tables-TT'
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\u003B'
LOCATION '/PROD/TT/OM/SERVICES_DYNAMIQUE'
TBLPROPERTIES ('serialization.null.format'='')
;