
CREATE EXTERNAL TABLE IF NOT EXISTS CDR.TT_OMNY_GRADE_DETAILS (
ORIGINAL_FILE_NAME     VARCHAR(50),
ORIGINAL_FILE_SIZE     INT,
ORIGINAL_FILE_LINE_COUNT INT,
GRADE_CODE           VARCHAR(10),
GRADE_NAME           VARCHAR(40),
CATEGORY_CODE        VARCHAR(10),
STATUS               VARCHAR(5)
)
COMMENT 'OM GRADE_DETAILS'
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|'
LOCATION '/PROD/TT/OM/GRADE_DETAILS'
TBLPROPERTIES ('serialization.null.format'='');
