CREATE EXTERNAL TABLE IF NOT EXISTS CDR.TT_OMNY_GROUP_ROLES (
ORIGINAL_FILE_NAME     VARCHAR(50),
ORIGINAL_FILE_SIZE     INT,
ORIGINAL_FILE_LINE_COUNT INT,
GROUP_ROLE_CODE           VARCHAR(38),
ROLE_CODE                 VARCHAR(20)
)
COMMENT 'OM GROUP_ROLES'
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|'
LOCATION '/PROD/TT/OM/GROUP_ROLES'
TBLPROPERTIES ('serialization.null.format'='');