SELECT IF(
T_1.FT_EXIST = 0 AND
T_2.MSC_TRANSACTION>0
,"OK","NOK") MSC_CMR_BAD_CALL_EXIST
FROM
(SELECT COUNT(*) FT_EXIST FROM MON.SPARK_FT_MSC_CMR_BAD_CALL WHERE TRANSACTION_DATE ='###SLICE_VALUE###') T_1,
(SELECT COUNT(*) MSC_TRANSACTION FROM MON.SPARK_FT_MSC_TRANSACTION WHERE TRANSACTION_DATE='###SLICE_VALUE###') T_2