INSERT INTO MON.SPARK_FT_DATAMART_OM_MARKETING_OLD
SELECT 
GLOB.MSISDN MSISDN, 
GLOB.USER_ID USER_ID, 
COALESCE(UPPER(CLSD.SITE_NAME_B), UPPER(CLSD.SITE_NAME_A), 'INCONNU') SITE_NAME,
GLOB.SERVICE_TYPE SERVICE_TYPE, 
GLOB.VOL VOL, 
GLOB.VAL VAL, 
GLOB.COMMISSION COMMISSION, 
GLOB.REVENU REVENU, 
GLOB.STYLE STYLE, 
GLOB.DETAILS DETAILS,
(CASE WHEN DETAILS LIKE 'REC%' THEN 'IGN' ELSE NULL END) NATURE,
GLOB.JOUR JOUR
FROM (
-- RECHARGE
-- AIRTIME
-- SELF
SELECT 
    SENDER_MSISDN MSISDN, SENDER_USER_ID USER_ID,SERVICE_TYPE, TRANSFER_DATETIME JOUR, COUNT(DISTINCT TRANSFER_ID) VOL, 
    SUM(TRANSACTION_AMOUNT) VAL, SUM(COMMISSIONS_PAID) COMMISSION, SUM(SERVICE_CHARGE_RECEIVED) REVENU, 'TOP_UP' STYLE, 'SELF' DETAILS
FROM CDR.SPARK_IT_OMNY_TRANSACTIONS
WHERE 
    TRANSFER_STATUS='TS' AND TRANSFER_DATETIME = '###SLICE_VALUE###' AND SERVICE_TYPE IN ('RC') AND SENDER_CATEGORY_CODE='SUBS' AND OTHER_MSISDN IS NULL AND
    SENDER_MSISDN NOT IN (SELECT MSISDN FROM BACKUP_DWH.OM_TEST_MSISDNS)
GROUP BY SENDER_MSISDN, SENDER_USER_ID,SERVICE_TYPE, TRANSFER_DATETIME 
-- TIERS_SELF
UNION ALL
SELECT 
    SENDER_MSISDN MSISDN, SENDER_USER_ID USER_ID,SERVICE_TYPE, TRANSFER_DATETIME JOUR, COUNT(DISTINCT TRANSFER_ID) VOL, 
    SUM(TRANSACTION_AMOUNT) VAL, SUM(COMMISSIONS_PAID) COMMISSION, SUM(SERVICE_CHARGE_RECEIVED) REVENU, 'TOP_UP' STYLE, 'TIERS_SELF' DETAILS
FROM CDR.SPARK_IT_OMNY_TRANSACTIONS
WHERE 
    TRANSFER_STATUS='TS' AND TRANSFER_DATETIME = '###SLICE_VALUE###' AND SERVICE_TYPE IN ('RC') AND SENDER_CATEGORY_CODE='SUBS' AND 
    OTHER_MSISDN IS NOT NULL AND OTHER_MSISDN=SENDER_MSISDN AND SENDER_MSISDN NOT IN (SELECT MSISDN FROM BACKUP_DWH.OM_TEST_MSISDNS)
GROUP BY SENDER_MSISDN, SENDER_USER_ID,SERVICE_TYPE, TRANSFER_DATETIME 
-- TIERS
UNION ALL
SELECT 
    SENDER_MSISDN MSISDN, SENDER_USER_ID USER_ID,SERVICE_TYPE, TRANSFER_DATETIME JOUR, COUNT(DISTINCT TRANSFER_ID) VOL, 
    SUM(TRANSACTION_AMOUNT) VAL, SUM(COMMISSIONS_PAID) COMMISSION, SUM(SERVICE_CHARGE_RECEIVED) REVENU, 'TOP_UP' STYLE, 'TIERS' DETAILS
FROM CDR.SPARK_IT_OMNY_TRANSACTIONS
WHERE 
    TRANSFER_STATUS='TS' AND TRANSFER_DATETIME = '###SLICE_VALUE###' AND SERVICE_TYPE IN ('RC') AND SENDER_CATEGORY_CODE='SUBS' AND 
    OTHER_MSISDN IS NOT NULL AND OTHER_MSISDN<>SENDER_MSISDN AND SENDER_MSISDN NOT IN (SELECT MSISDN FROM BACKUP_DWH.OM_TEST_MSISDNS)
GROUP BY SENDER_MSISDN, SENDER_USER_ID,SERVICE_TYPE, TRANSFER_DATETIME 
-- INTERNET
UNION ALL
SELECT 
    SENDER_MSISDN MSISDN, SENDER_USER_ID USER_ID,SERVICE_TYPE, TRANSFER_DATETIME JOUR, COUNT(DISTINCT TRANSFER_ID) VOL, 
    SUM(TRANSACTION_AMOUNT) VAL, SUM(COMMISSIONS_PAID) COMMISSION, SUM(SERVICE_CHARGE_RECEIVED) REVENU, 'RECHARGE' STYLE, 'INTERNET' DETAILS
FROM CDR.SPARK_IT_OMNY_TRANSACTIONS
WHERE 
    TRANSFER_STATUS='TS' AND TRANSFER_DATETIME = '###SLICE_VALUE###' AND SERVICE_TYPE IN ('MERCHPAY') AND SENDER_CATEGORY_CODE='SUBS' AND 
    RECEIVER_MSISDN IN (SELECT MSISDN FROM BACKUP_DWH.INTERNET_MSISDNS) AND SENDER_MSISDN NOT IN (SELECT MSISDN FROM BACKUP_DWH.OM_TEST_MSISDNS)
GROUP BY SENDER_MSISDN, SENDER_USER_ID,SERVICE_TYPE, TRANSFER_DATETIME 
UNION ALL
-- BILL PAYMENTS
-- ENEO
-- ENEO PREPAID
SELECT 
    SENDER_MSISDN MSISDN, SENDER_USER_ID USER_ID,SERVICE_TYPE, TRANSFER_DATETIME JOUR, COUNT(DISTINCT TRANSFER_ID) VOL, 
    SUM(TRANSACTION_AMOUNT) VAL, SUM(COMMISSIONS_PAID) COMMISSION, 
    ROUND(SUM(CASE 
        WHEN SERVICE_CHARGE_RECEIVED > 0 THEN SERVICE_CHARGE_RECEIVED
        WHEN TRANSACTION_AMOUNT BETWEEN 0 AND 4999 THEN 100
        WHEN TRANSACTION_AMOUNT BETWEEN 5000 AND 10000 THEN 220
        WHEN TRANSACTION_AMOUNT BETWEEN 10001 AND 25000 THEN 400
        WHEN TRANSACTION_AMOUNT BETWEEN 25001 AND 50000 THEN 400
        WHEN TRANSACTION_AMOUNT BETWEEN 50001 AND 100000 THEN 500
        ELSE 750 END)/1.1925,0) * 0.6 REVENU, 
    'FACTURIER' STYLE, Y.DETAILS
FROM CDR.SPARK_IT_OMNY_TRANSACTIONS X JOIN BACKUP_DWH.MSISDN_ENEO Y 
ON X.RECEIVER_MSISDN=Y.MSISDN
WHERE 
    TRANSFER_STATUS='TS' AND TRANSFER_DATETIME = '###SLICE_VALUE###' AND SERVICE_TYPE IN ('MERCHPAY', 'BILLPAY') AND SENDER_CATEGORY_CODE='SUBS' AND 
    SENDER_MSISDN NOT IN (SELECT MSISDN FROM BACKUP_DWH.OM_TEST_MSISDNS)
GROUP BY SENDER_MSISDN, SENDER_USER_ID,SERVICE_TYPE, TRANSFER_DATETIME, Y.DETAILS
-- CANAL
UNION ALL
SELECT 
    SENDER_MSISDN MSISDN, SENDER_USER_ID USER_ID,SERVICE_TYPE, TRANSFER_DATETIME JOUR, COUNT(DISTINCT TRANSFER_ID) VOL, 
    SUM(TRANSACTION_AMOUNT) VAL, SUM(COMMISSIONS_PAID) COMMISSION, SUM(SERVICE_CHARGE_RECEIVED) REVENU, 'FACTURIER' STYLE,'CANAL' DETAILS
FROM CDR.SPARK_IT_OMNY_TRANSACTIONS
WHERE 
    TRANSFER_STATUS='TS' AND TRANSFER_DATETIME = '###SLICE_VALUE###' AND SERVICE_TYPE IN ('MERCHPAY') AND SENDER_CATEGORY_CODE='SUBS' AND 
    RECEIVER_MSISDN  IN (SELECT MSISDN FROM  BACKUP_DWH.MSISDN_CANAL) AND SENDER_MSISDN NOT IN (SELECT MSISDN FROM BACKUP_DWH.OM_TEST_MSISDNS)
GROUP BY SENDER_MSISDN, SENDER_USER_ID,SERVICE_TYPE, TRANSFER_DATETIME 
UNION ALL
-- CDE
-- CAMWATER
SELECT 
    SENDER_MSISDN MSISDN, SENDER_USER_ID USER_ID,SERVICE_TYPE, TRANSFER_DATETIME JOUR, COUNT(DISTINCT TRANSFER_ID) VOL, 
    SUM(TRANSACTION_AMOUNT) VAL, SUM(COMMISSIONS_PAID) COMMISSION, SUM(SERVICE_CHARGE_RECEIVED) REVENU, 'FACTURIER' STYLE,'CAMWATER' DETAILS
FROM CDR.SPARK_IT_OMNY_TRANSACTIONS
WHERE 
    TRANSFER_STATUS='TS' AND TRANSFER_DATETIME = '###SLICE_VALUE###' AND SERVICE_TYPE IN ('MERCHPAY', 'BILLPAY') AND SENDER_CATEGORY_CODE='SUBS' AND 
    RECEIVER_MSISDN  IN (SELECT MSISDN FROM BACKUP_DWH.MSISDN_EAU) AND SENDER_MSISDN NOT IN (SELECT MSISDN FROM BACKUP_DWH.OM_TEST_MSISDNS)
GROUP BY SENDER_MSISDN, SENDER_USER_ID,SERVICE_TYPE, TRANSFER_DATETIME 
-- ORANGE
UNION ALL
SELECT 
    SENDER_MSISDN MSISDN, SENDER_USER_ID USER_ID,SERVICE_TYPE, TRANSFER_DATETIME JOUR, COUNT(DISTINCT TRANSFER_ID) VOL, 
    SUM(TRANSACTION_AMOUNT) VAL, SUM(COMMISSIONS_PAID) COMMISSION, SUM(SERVICE_CHARGE_RECEIVED) REVENU, 'FACTURIER' STYLE,'ORANGE' DETAILS
FROM CDR.SPARK_IT_OMNY_TRANSACTIONS
WHERE 
    TRANSFER_STATUS='TS' AND TRANSFER_DATETIME = '###SLICE_VALUE###' AND SERVICE_TYPE IN ('BILLPAY') AND SENDER_CATEGORY_CODE='SUBS' AND 
    RECEIVER_MSISDN IN ('orang') AND SENDER_MSISDN NOT IN (SELECT MSISDN FROM BACKUP_DWH.OM_TEST_MSISDNS)
GROUP BY SENDER_MSISDN, SENDER_USER_ID,SERVICE_TYPE, TRANSFER_DATETIME
-- ALL BILL PAY ASSURANCE 
UNION ALL
SELECT 
    SENDER_MSISDN MSISDN, SENDER_USER_ID USER_ID,SERVICE_TYPE, TRANSFER_DATETIME JOUR, COUNT(DISTINCT TRANSFER_ID) VOL, 
    SUM(TRANSACTION_AMOUNT) VAL, SUM(COMMISSIONS_PAID) COMMISSION, SUM(SERVICE_CHARGE_RECEIVED) REVENU, 'FACTURIER' STYLE,'ASSURANCE' DETAILS
FROM CDR.SPARK_IT_OMNY_TRANSACTIONS
WHERE 
    TRANSFER_STATUS='TS' AND TRANSFER_DATETIME = '###SLICE_VALUE###' AND SERVICE_TYPE IN ('BILLPAY') AND SENDER_CATEGORY_CODE='SUBS' AND 
    RECEIVER_MSISDN NOT IN (SELECT MSISDN FROM BACKUP_DWH.MSISDN_ENEO UNION ALL SELECT MSISDN FROM BACKUP_DWH.MSISDN_EAU UNION SELECT 'orang' MSISDN FROM  BACKUP_DWH.DUAL UNION ALL 
    SELECT MSISDN FROM BACKUP_DWH.OM_TEST_MSISDNS  UNION ALL SELECT MSISDN FROM BACKUP_DWH.MSISDN_GIMAC) AND 
    SENDER_MSISDN NOT IN (SELECT MSISDN FROM BACKUP_DWH.OM_TEST_MSISDNS)
GROUP BY SENDER_MSISDN, SENDER_USER_ID,SERVICE_TYPE, TRANSFER_DATETIME 
-- ASSUR TOUS
UNION ALL
SELECT 
    SENDER_MSISDN MSISDN, SENDER_USER_ID USER_ID,SERVICE_TYPE, TRANSFER_DATETIME JOUR, COUNT(DISTINCT TRANSFER_ID) VOL, 
    SUM(TRANSACTION_AMOUNT) VAL, SUM(COMMISSIONS_PAID) COMMISSION, SUM(SERVICE_CHARGE_RECEIVED) REVENU, 'MICRO-ASSURANCE' STYLE,'ASSUR TOUS' DETAILS
FROM CDR.SPARK_IT_OMNY_TRANSACTIONS
WHERE 
    TRANSFER_STATUS='TS' AND TRANSFER_DATETIME = '###SLICE_VALUE###' AND SERVICE_TYPE IN ('MERCHPAY') AND SENDER_CATEGORY_CODE='SUBS' AND 
    RECEIVER_MSISDN IN (SELECT MSISDN FROM  BACKUP_DWH.MSISDN_ASSUR_TOUS) AND SENDER_MSISDN NOT IN (SELECT MSISDN FROM BACKUP_DWH.OM_TEST_MSISDNS)
GROUP BY SENDER_MSISDN, SENDER_USER_ID,SERVICE_TYPE, TRANSFER_DATETIME 
-- ATLANTIC ASSURANCE
UNION ALL
SELECT 
    SENDER_MSISDN MSISDN, SENDER_USER_ID USER_ID,SERVICE_TYPE, TRANSFER_DATETIME JOUR, COUNT(DISTINCT TRANSFER_ID) VOL, 
    SUM(TRANSACTION_AMOUNT) VAL, SUM(COMMISSIONS_PAID) COMMISSION, SUM(TRANSACTION_AMOUNT)*0.07 REVENU, 'MICRO-ASSURANCE' STYLE,'ATLANTIC ASSURANCE' DETAILS
FROM CDR.SPARK_IT_OMNY_TRANSACTIONS
WHERE 
    TRANSFER_STATUS='TS' AND TRANSFER_DATETIME = '###SLICE_VALUE###' AND SERVICE_TYPE IN ('MERCHPAY') AND SENDER_CATEGORY_CODE='SUBS' AND 
    RECEIVER_MSISDN IN (SELECT MSISDN FROM BACKUP_DWH.MSISDN_ATLANTIC_ASSURANCE) AND SENDER_MSISDN NOT IN (SELECT MSISDN FROM BACKUP_DWH.OM_TEST_MSISDNS)
GROUP BY SENDER_MSISDN, SENDER_USER_ID,SERVICE_TYPE, TRANSFER_DATETIME 
-- ACTIVA
UNION ALL
SELECT 
    SENDER_MSISDN MSISDN, SENDER_USER_ID USER_ID,SERVICE_TYPE, TRANSFER_DATETIME JOUR, COUNT(DISTINCT TRANSFER_ID) VOL, 
    SUM(TRANSACTION_AMOUNT) VAL, SUM(COMMISSIONS_PAID) COMMISSION, SUM(SERVICE_CHARGE_RECEIVED) REVENU, 'MICRO-ASSURANCE' STYLE,'MAKALA' DETAILS
FROM CDR.SPARK_IT_OMNY_TRANSACTIONS
WHERE 
    TRANSFER_STATUS='TS' AND TRANSFER_DATETIME = '###SLICE_VALUE###' AND SERVICE_TYPE IN ('MERCHPAY') AND SENDER_CATEGORY_CODE='SUBS' AND 
    RECEIVER_MSISDN IN (SELECT MSISDN FROM BACKUP_DWH.MSISDN_ACTIVA) AND SENDER_MSISDN NOT IN (SELECT MSISDN FROM BACKUP_DWH.OM_TEST_MSISDNS)
GROUP BY SENDER_MSISDN, SENDER_USER_ID,SERVICE_TYPE, TRANSFER_DATETIME 
-- TRANSFERS
-- TNO_FREE_DEST
UNION ALL
SELECT 
    SENDER_MSISDN MSISDN, SENDER_USER_ID USER_ID,SERVICE_TYPE, TRANSFER_DATETIME JOUR, COUNT(DISTINCT TRANSFER_ID) VOL, 
    SUM(TRANSACTION_AMOUNT) VAL, SUM(COMMISSIONS_PAID) COMMISSION, SUM(SERVICE_CHARGE_RECEIVED) REVENU, 'TNO' STYLE, 'FREE_DEST' DETAILS
FROM CDR.SPARK_IT_OMNY_TRANSACTIONS
WHERE 
    TRANSFER_STATUS='TS' AND TRANSFER_DATETIME = '###SLICE_VALUE###' AND SERVICE_TYPE IN ('P2PNONREG') AND 
    SENDER_CATEGORY_CODE='SUBS' AND TNO_MSISDN IS NULL
GROUP BY SENDER_MSISDN, SENDER_USER_ID,SERVICE_TYPE, TRANSFER_DATETIME 
-- TNO_DEST
UNION ALL
SELECT 
    SENDER_MSISDN MSISDN, SENDER_USER_ID USER_ID,SERVICE_TYPE, TRANSFER_DATETIME JOUR, COUNT(DISTINCT TRANSFER_ID) VOL, 
    SUM(TRANSACTION_AMOUNT) VAL, SUM(COMMISSIONS_PAID) COMMISSION, SUM(SERVICE_CHARGE_RECEIVED) REVENU, 'TNO' STYLE, 'DEST' DETAILS
FROM CDR.SPARK_IT_OMNY_TRANSACTIONS
WHERE 
    TRANSFER_STATUS='TS' AND TRANSFER_DATETIME = '###SLICE_VALUE###' AND SERVICE_TYPE IN ('P2PNONREG') AND SENDER_CATEGORY_CODE='SUBS' AND 
    TNO_MSISDN IS NOT NULL AND SENDER_MSISDN NOT IN (SELECT MSISDN FROM BACKUP_DWH.OM_TEST_MSISDNS) AND 
    RECEIVER_MSISDN NOT IN (SELECT MSISDN FROM BACKUP_DWH.OM_TEST_MSISDNS)
GROUP BY SENDER_MSISDN, SENDER_USER_ID,SERVICE_TYPE, TRANSFER_DATETIME 
-- MARCHAND FOCUS
UNION ALL
SELECT 
    SENDER_MSISDN MSISDN, SENDER_USER_ID USER_ID,SERVICE_TYPE, TRANSFER_DATETIME JOUR, COUNT(DISTINCT TRANSFER_ID) VOL, 
    SUM(TRANSACTION_AMOUNT) VAL, SUM(COMMISSIONS_PAID) COMMISSION, SUM(SERVICE_CHARGE_RECEIVED) REVENU, 'MARCHAND' STYLE, 'FOCUS' DETAILS
FROM CDR.SPARK_IT_OMNY_TRANSACTIONS
WHERE 
    TRANSFER_STATUS='TS' AND TRANSFER_DATETIME = '###SLICE_VALUE###' AND SERVICE_TYPE IN ('MERCHPAY') AND SENDER_CATEGORY_CODE='SUBS' AND 
    RECEIVER_MSISDN NOT IN (SELECT MSISDN FROM BACKUP_DWH.OM_TEST_MSISDNS UNION ALL SELECT MSISDN FROM BACKUP_DWH.NON_MERCHANT_MSISDNS) AND SENDER_MSISDN NOT IN (SELECT MSISDN FROM BACKUP_DWH.OM_TEST_MSISDNS UNION ALL 
    SELECT MSISDN FROM BACKUP_DWH.NON_MERCHANT_MSISDNS UNION ALL SELECT MSISDN FROM BACKUP_DWH.MSISDN_B2W UNION ALL SELECT MSISDN FROM BACKUP_DWH.MSISDN_GIMAC) AND RECEIVER_GRADE_NAME NOT IN ('gradeMinsc')
GROUP BY SENDER_MSISDN, SENDER_USER_ID,SERVICE_TYPE, TRANSFER_DATETIME 
-- MARCHAND MINSEC
UNION ALL
SELECT 
    SENDER_MSISDN MSISDN, SENDER_USER_ID USER_ID,SERVICE_TYPE, TRANSFER_DATETIME JOUR, COUNT(DISTINCT TRANSFER_ID) VOL, 
    SUM(TRANSACTION_AMOUNT) VAL, SUM(COMMISSIONS_PAID) COMMISSION, SUM(SERVICE_CHARGE_RECEIVED) REVENU, 'MARCHAND' STYLE, 'MINSEC' DETAILS
FROM CDR.SPARK_IT_OMNY_TRANSACTIONS
WHERE 
    TRANSFER_STATUS='TS' AND TRANSFER_DATETIME = '###SLICE_VALUE###' AND SERVICE_TYPE IN ('MERCHPAY') AND SENDER_CATEGORY_CODE='SUBS' AND 
    RECEIVER_GRADE_NAME IN ('gradeMinsc') AND RECEIVER_MSISDN NOT IN (SELECT MSISDN FROM BACKUP_DWH.OM_TEST_MSISDNS UNION ALL 
    SELECT MSISDN FROM BACKUP_DWH.NON_MERCHANT_MSISDNS UNION ALL SELECT MSISDN FROM BACKUP_DWH.MSISDN_B2W)
GROUP BY SENDER_MSISDN, SENDER_USER_ID,SERVICE_TYPE, TRANSFER_DATETIME
-- DISTRIBUTION 
-- CASHOUT 
UNION ALL
SELECT 
    SENDER_MSISDN MSISDN, SENDER_USER_ID USER_ID,SERVICE_TYPE, TRANSFER_DATETIME JOUR, COUNT(DISTINCT TRANSFER_ID) VOL, 
    SUM(TRANSACTION_AMOUNT) VAL, SUM(COMMISSIONS_PAID) COMMISSION, SUM(SERVICE_CHARGE_RECEIVED) REVENU, 'DISTRIBUTION' STYLE, 'FOCUS' DETAILS
FROM CDR.SPARK_IT_OMNY_TRANSACTIONS
WHERE 
    TRANSFER_STATUS='TS' AND TRANSFER_DATETIME = '###SLICE_VALUE###' AND SERVICE_TYPE IN ('CASHOUT') AND SENDER_CATEGORY_CODE='SUBS' AND 
    RECEIVER_MSISDN NOT IN  (SELECT MSISDN FROM BACKUP_DWH.OM_TEST_MSISDNS UNION ALL SELECT MSISDN FROM BACKUP_DWH.MSISDN_VISA UNION ALL 
    SELECT MSISDN FROM BACKUP_DWH.MSISDN_B2W  UNION ALL SELECT MSISDN FROM BACKUP_DWH.MSISDN_GIMAC) AND 
    SENDER_MSISDN NOT IN (SELECT MSISDN FROM BACKUP_DWH.OM_TEST_MSISDNS UNION ALL SELECT MSISDN FROM BACKUP_DWH.MSISDN_VISA UNION ALL 
    SELECT MSISDN FROM BACKUP_DWH.MSISDN_B2W  UNION ALL SELECT MSISDN FROM BACKUP_DWH.MSISDN_GIMAC)
GROUP BY SENDER_MSISDN, SENDER_USER_ID,SERVICE_TYPE, TRANSFER_DATETIME 
-- CASH IN 
UNION ALL
SELECT 
    RECEIVER_MSISDN MSISDN, RECEIVER_USER_ID USER_ID,SERVICE_TYPE, TRANSFER_DATETIME JOUR, COUNT(DISTINCT TRANSFER_ID) VOL, 
    SUM(TRANSACTION_AMOUNT) VAL, SUM(COMMISSIONS_PAID) COMMISSION, SUM(SERVICE_CHARGE_RECEIVED) REVENU, 'DISTRIBUTION' STYLE, 'FOCUS' DETAILS
FROM CDR.SPARK_IT_OMNY_TRANSACTIONS
WHERE 
    TRANSFER_STATUS='TS' AND TRANSFER_DATETIME = '###SLICE_VALUE###' AND SERVICE_TYPE IN ('CASHIN') AND RECEIVER_CATEGORY_CODE='SUBS' AND 
    SENDER_MSISDN NOT IN (SELECT MSISDN FROM BACKUP_DWH.MSISDN_B2W UNION SELECT MSISDN FROM BACKUP_DWH.OM_TEST_MSISDNS  UNION ALL SELECT MSISDN FROM BACKUP_DWH.MSISDN_GIMAC) AND 
    RECEIVER_MSISDN NOT IN (SELECT MSISDN FROM BACKUP_DWH.MSISDN_B2W UNION SELECT MSISDN FROM BACKUP_DWH.OM_TEST_MSISDNS  UNION ALL SELECT MSISDN FROM BACKUP_DWH.MSISDN_GIMAC)
GROUP BY RECEIVER_MSISDN , RECEIVER_USER_ID,SERVICE_TYPE, TRANSFER_DATETIME 
-- W2B
-- ECOBANK, AFRILAND, UBA, PANAFRICA, ADVANS
UNION ALL
SELECT 
    SENDER_MSISDN MSISDN, SENDER_USER_ID USER_ID,SERVICE_TYPE, TRANSFER_DATETIME JOUR, COUNT(DISTINCT TRANSFER_ID) VOL, 
    SUM(TRANSACTION_AMOUNT) VAL, SUM(COMMISSIONS_PAID) COMMISSION, SUM(SERVICE_CHARGE_RECEIVED) REVENU, 'B2W' STYLE, B.BANK DETAILS
FROM CDR.SPARK_IT_OMNY_TRANSACTIONS A JOIN BACKUP_DWH.MSISDN_B2W B 
ON A.RECEIVER_MSISDN=B.MSISDN
WHERE 
    TRANSFER_STATUS='TS' AND TRANSFER_DATETIME = '###SLICE_VALUE###' AND SERVICE_TYPE IN ('CASHOUT') AND SENDER_CATEGORY_CODE='SUBS' AND 
    SENDER_MSISDN NOT IN (SELECT MSISDN FROM BACKUP_DWH.OM_TEST_MSISDNS)
GROUP BY SENDER_MSISDN, SENDER_USER_ID,SERVICE_TYPE, B.BANK, TRANSFER_DATETIME 
-- B2W
-- ECOBANK
UNION ALL 
SELECT 
    RECEIVER_MSISDN MSISDN, RECEIVER_USER_ID USER_ID,SERVICE_TYPE, TRANSFER_DATETIME JOUR, COUNT(DISTINCT TRANSFER_ID) VOL, 
    SUM(TRANSACTION_AMOUNT) VAL, SUM(COMMISSIONS_PAID) COMMISSION, SUM(SERVICE_CHARGE_RECEIVED) REVENU, 'B2W' STYLE, B.BANK DETAILS
FROM CDR.SPARK_IT_OMNY_TRANSACTIONS A JOIN BACKUP_DWH.MSISDN_B2W B 
ON A.SENDER_MSISDN=B.MSISDN
WHERE 
    TRANSFER_STATUS='TS' AND TRANSFER_DATETIME = '###SLICE_VALUE###' AND SERVICE_TYPE IN ('CASHIN') AND RECEIVER_CATEGORY_CODE='SUBS' 
    AND RECEIVER_MSISDN NOT IN (SELECT MSISDN FROM BACKUP_DWH.OM_TEST_MSISDNS)
GROUP BY RECEIVER_MSISDN , RECEIVER_USER_ID,SERVICE_TYPE, TRANSFER_DATETIME, B.BANK
-- VISA 
-- PAYMENT
UNION ALL
SELECT 
    SENDER_MSISDN MSISDN, SENDER_USER_ID USER_ID,SERVICE_TYPE, TRANSFER_DATETIME JOUR, COUNT(DISTINCT TRANSFER_ID) VOL, 
    SUM(TRANSACTION_AMOUNT) VAL, SUM(COMMISSIONS_PAID) COMMISSION, SUM(SERVICE_CHARGE_RECEIVED) REVENU, 'VISA' STYLE,'TPE' DETAILS 
FROM CDR.SPARK_IT_OMNY_TRANSACTIONS
WHERE 
    TRANSFER_STATUS='TS' AND TRANSFER_DATETIME = '###SLICE_VALUE###' AND SERVICE_TYPE IN ('MERCHPAY') AND SENDER_CATEGORY_CODE='SUBS' AND 
    RECEIVER_MSISDN  IN (SELECT MSISDN FROM BACKUP_DWH.MSISDN_VISA) AND SENDER_MSISDN NOT IN (SELECT MSISDN FROM BACKUP_DWH.OM_TEST_MSISDNS)
GROUP BY SENDER_MSISDN, SENDER_USER_ID,SERVICE_TYPE, TRANSFER_DATETIME 
-- VISA CASHOUT
UNION ALL
SELECT 
    SENDER_MSISDN MSISDN, SENDER_USER_ID USER_ID,SERVICE_TYPE, TRANSFER_DATETIME JOUR, COUNT(DISTINCT TRANSFER_ID) VOL, 
    SUM(TRANSACTION_AMOUNT) VAL, SUM(COMMISSIONS_PAID) COMMISSION, SUM(SERVICE_CHARGE_RECEIVED) REVENU, 'VISA' STYLE,'GAB' DETAILS
FROM CDR.SPARK_IT_OMNY_TRANSACTIONS
WHERE
    TRANSFER_STATUS='TS' AND TRANSFER_DATETIME = '###SLICE_VALUE###' AND SERVICE_TYPE IN ('CASHOUT') AND SENDER_CATEGORY_CODE='SUBS' AND 
    RECEIVER_MSISDN  IN (SELECT MSISDN FROM BACKUP_DWH.MSISDN_VISA)
GROUP BY SENDER_MSISDN, SENDER_USER_ID,SERVICE_TYPE, TRANSFER_DATETIME
-- P2P
-- P2P TO NOT A SUB
UNION ALL
SELECT 
    SENDER_MSISDN MSISDN, SENDER_USER_ID USER_ID,SERVICE_TYPE, TRANSFER_DATETIME JOUR, COUNT(DISTINCT TRANSFER_ID) VOL, 
    SUM(TRANSACTION_AMOUNT) VAL, SUM(COMMISSIONS_PAID) COMMISSION, SUM(SERVICE_CHARGE_RECEIVED) REVENU, 'TRANSFERT' STYLE, 'SENDER_REC_INCONNU' DETAILS
FROM CDR.SPARK_IT_OMNY_TRANSACTIONS
WHERE 
    TRANSFER_STATUS='TS' AND TRANSFER_DATETIME = '###SLICE_VALUE###' AND SERVICE_TYPE IN ('P2P') AND SENDER_CATEGORY_CODE IN ('SUBS') AND 
    RECEIVER_CATEGORY_CODE NOT IN ('SUBS') AND SENDER_MSISDN NOT IN (SELECT MSISDN FROM BACKUP_DWH.OM_TEST_MSISDNS UNION ALL SELECT MSISDN FROM BACKUP_DWH.MSISDN_GIMAC)
    AND RECEIVER_MSISDN NOT IN (SELECT MSISDN FROM BACKUP_DWH.OM_TEST_MSISDNS UNION ALL SELECT MSISDN FROM BACKUP_DWH.MSISDN_GIMAC)
GROUP BY SENDER_MSISDN, SENDER_USER_ID,SERVICE_TYPE, TRANSFER_DATETIME 
-- P2P TO A SUB
UNION ALL
SELECT 
    SENDER_MSISDN MSISDN, SENDER_USER_ID USER_ID,SERVICE_TYPE, TRANSFER_DATETIME JOUR, COUNT(DISTINCT TRANSFER_ID) VOL, 
    SUM(TRANSACTION_AMOUNT) VAL, SUM(COMMISSIONS_PAID) COMMISSION, SUM(SERVICE_CHARGE_RECEIVED) REVENU, 'TRANSFERT' STYLE, 'SENDER_REC_CONNU' DETAILS
FROM CDR.SPARK_IT_OMNY_TRANSACTIONS
WHERE 
    TRANSFER_STATUS='TS' AND TRANSFER_DATETIME = '###SLICE_VALUE###' AND SERVICE_TYPE IN ('P2P') AND SENDER_CATEGORY_CODE IN ('SUBS') 
    AND RECEIVER_CATEGORY_CODE IN ('SUBS') AND SENDER_MSISDN NOT IN (SELECT MSISDN FROM BACKUP_DWH.OM_TEST_MSISDNS  UNION ALL SELECT MSISDN FROM BACKUP_DWH.MSISDN_GIMAC)
    AND RECEIVER_MSISDN NOT IN (SELECT MSISDN FROM BACKUP_DWH.OM_TEST_MSISDNS  UNION ALL SELECT MSISDN FROM BACKUP_DWH.MSISDN_GIMAC)
GROUP BY SENDER_MSISDN, SENDER_USER_ID,SERVICE_TYPE, TRANSFER_DATETIME 
-- UNKNOWN RECEIVER
UNION ALL
SELECT 
    RECEIVER_MSISDN MSISDN, RECEIVER_USER_ID USER_ID,SERVICE_TYPE, TRANSFER_DATETIME JOUR, COUNT(DISTINCT TRANSFER_ID) VOL, 
    SUM(TRANSACTION_AMOUNT) VAL, SUM(COMMISSIONS_PAID) COMMISSION, SUM(SERVICE_CHARGE_RECEIVED) REVENU, 'TRANSFERT' STYLE, 'RECEIVER_SEN_INCONNU' DETAILS
FROM CDR.SPARK_IT_OMNY_TRANSACTIONS
WHERE 
    TRANSFER_STATUS='TS' AND TRANSFER_DATETIME = '###SLICE_VALUE###' AND SERVICE_TYPE IN ('P2P','OTF') AND RECEIVER_CATEGORY_CODE='SUBS' AND 
    SENDER_MSISDN NOT IN (SELECT MSISDN FROM BACKUP_DWH.MSISDN_B2W UNION SELECT MSISDN FROM BACKUP_DWH.OM_TEST_MSISDNS  UNION ALL SELECT MSISDN FROM BACKUP_DWH.MSISDN_GIMAC) AND SENDER_CATEGORY_CODE NOT IN ('SUBS')
                AND RECEIVER_MSISDN NOT IN (SELECT MSISDN FROM BACKUP_DWH.OM_TEST_MSISDNS  UNION ALL SELECT MSISDN FROM BACKUP_DWH.MSISDN_GIMAC)
GROUP BY RECEIVER_MSISDN , RECEIVER_USER_ID,SERVICE_TYPE, TRANSFER_DATETIME
-- P2P UNKNOWN SENDER
UNION ALL
SELECT 
    RECEIVER_MSISDN MSISDN, RECEIVER_USER_ID USER_ID,SERVICE_TYPE, TRANSFER_DATETIME JOUR, COUNT(DISTINCT TRANSFER_ID) VOL, 
    SUM(TRANSACTION_AMOUNT) VAL, SUM(COMMISSIONS_PAID) COMMISSION, SUM(SERVICE_CHARGE_RECEIVED) REVENU, 'TRANSFERT' STYLE, 'RECEIVER_SEN_CONNU' DETAILS
FROM CDR.SPARK_IT_OMNY_TRANSACTIONS
WHERE 
    TRANSFER_STATUS='TS' AND TRANSFER_DATETIME = '###SLICE_VALUE###' AND SERVICE_TYPE IN ('P2P','OTF') AND RECEIVER_CATEGORY_CODE='SUBS' AND 
    SENDER_MSISDN NOT IN (SELECT MSISDN FROM BACKUP_DWH.MSISDN_B2W UNION SELECT MSISDN FROM BACKUP_DWH.OM_TEST_MSISDNS UNION ALL SELECT MSISDN FROM BACKUP_DWH.MSISDN_GIMAC) AND SENDER_CATEGORY_CODE IN ('SUBS') 
    AND RECEIVER_MSISDN NOT IN (SELECT MSISDN FROM BACKUP_DWH.OM_TEST_MSISDNS)
GROUP BY RECEIVER_MSISDN , RECEIVER_USER_ID,SERVICE_TYPE, TRANSFER_DATETIME
-- SALARY PAYMENTS 
UNION ALL
SELECT 
    RECEIVER_MSISDN MSISDN, RECEIVER_USER_ID USER_ID,SERVICE_TYPE, TRANSFER_DATETIME JOUR, COUNT(DISTINCT TRANSFER_ID) VOL, 
    SUM(TRANSACTION_AMOUNT) VAL, SUM(COMMISSIONS_PAID) COMMISSION, SUM(SERVICE_CHARGE_RECEIVED) REVENU, 'SALAIRE' STYLE, 'FOCUS' DETAILS
FROM CDR.SPARK_IT_OMNY_TRANSACTIONS
WHERE 
    TRANSFER_STATUS='TS' AND TRANSFER_DATETIME = '###SLICE_VALUE###' AND SERVICE_TYPE IN ('ENT2REG') AND RECEIVER_CATEGORY_CODE='SUBS' AND 
    SENDER_MSISDN NOT IN (SELECT MSISDN FROM BACKUP_DWH.MSISDN_B2W UNION SELECT MSISDN FROM BACKUP_DWH.OM_TEST_MSISDNS) AND 
    RECEIVER_MSISDN NOT IN (SELECT MSISDN FROM BACKUP_DWH.MSISDN_B2W UNION SELECT MSISDN FROM BACKUP_DWH.OM_TEST_MSISDNS)
GROUP BY RECEIVER_MSISDN , RECEIVER_USER_ID,SERVICE_TYPE, TRANSFER_DATETIME
-- GIMAC
-- IN
UNION ALL
SELECT 
    RECEIVER_MSISDN MSISDN, RECEIVER_USER_ID USER_ID,SERVICE_TYPE, TRANSFER_DATETIME JOUR, COUNT(DISTINCT TRANSFER_ID) VOL, 
    SUM(TRANSACTION_AMOUNT) VAL, SUM(COMMISSIONS_PAID) COMMISSION, SUM(SERVICE_CHARGE_RECEIVED) REVENU, 'GIMAC' STYLE, 
    (CASE WHEN SERVICE_TYPE='CASHIN' THEN 'IN' ELSE 'OUT' END) DETAILS
FROM CDR.SPARK_IT_OMNY_TRANSACTIONS
WHERE 
    TRANSFER_STATUS='TS' AND TRANSFER_DATETIME = '###SLICE_VALUE###' AND 
    SENDER_MSISDN IN (SELECT MSISDN FROM BACKUP_DWH.MSISDN_GIMAC) AND 
    RECEIVER_MSISDN NOT IN (SELECT MSISDN FROM BACKUP_DWH.MSISDN_B2W UNION SELECT MSISDN FROM BACKUP_DWH.OM_TEST_MSISDNS) AND
    RECEIVER_CATEGORY_CODE='SUBS'
GROUP BY RECEIVER_MSISDN , RECEIVER_USER_ID,SERVICE_TYPE, TRANSFER_DATETIME, (CASE WHEN SERVICE_TYPE='CASHIN' THEN 'IN' ELSE 'OUT' END)
-- GIMAC
-- OUT
UNION ALL
SELECT 
    SENDER_MSISDN MSISDN, SENDER_USER_ID USER_ID,SERVICE_TYPE, TRANSFER_DATETIME JOUR, COUNT(DISTINCT TRANSFER_ID) VOL, 
    SUM(TRANSACTION_AMOUNT) VAL, SUM(COMMISSIONS_PAID) COMMISSION, SUM(SERVICE_CHARGE_RECEIVED) REVENU, 'GIMAC' STYLE, 
    (CASE WHEN SERVICE_TYPE='CASHIN' THEN 'IN' ELSE 'OUT' END) DETAILS
FROM CDR.SPARK_IT_OMNY_TRANSACTIONS
WHERE 
    TRANSFER_STATUS='TS' AND TRANSFER_DATETIME = '###SLICE_VALUE###' AND 
    RECEIVER_MSISDN IN (SELECT MSISDN FROM BACKUP_DWH.MSISDN_GIMAC) AND 
    SENDER_MSISDN NOT IN (SELECT MSISDN FROM BACKUP_DWH.MSISDN_B2W UNION SELECT MSISDN FROM BACKUP_DWH.OM_TEST_MSISDNS) AND 
    SENDER_CATEGORY_CODE='SUBS'
GROUP BY SENDER_MSISDN , SENDER_USER_ID,SERVICE_TYPE, TRANSFER_DATETIME, (CASE WHEN SERVICE_TYPE='CASHIN' THEN 'IN' ELSE 'OUT' END)
) GLOB 
LEFT JOIN (
    SELECT
        A.MSISDN,
        MAX(A.SITE_NAME) SITE_NAME_A,
        MAX(B.SITE_NAME) SITE_NAME_B
    FROM MON.SPARK_FT_CLIENT_LAST_SITE_DAY A
    LEFT JOIN (
        SELECT * FROM MON.SPARK_FT_CLIENT_SITE_TRAFFIC_DAY WHERE EVENT_DATE='###SLICE_VALUE###'
    ) B ON A.MSISDN = B.MSISDN
    WHERE A.EVENT_DATE='###SLICE_VALUE###'
    GROUP BY A.MSISDN
) CLSD 
ON GLOB.MSISDN = CLSD.MSISDN