CREATE TABLE MON.SPARK_REF_OM_PRODUCTS2 (
  `user_id` varchar(255),
  `profile_id` varchar(255),
  `parent_user_id` varchar(255),
  `parent_user_msisdn` varchar(255),
  `msisdn` varchar(255),
  `user_name_prefix` varchar(255),
  `user_first_name` varchar(255),
  `user_last_name` varchar(255),
  `user_short_name` varchar(255),
  `dob` string,
  `registered_on` TIMESTAMP,
  `address1` varchar(255),
  `address2` varchar(255),
  `state` varchar(255),
  `city` varchar(255),
  `country` varchar(255),
  `ssn` varchar(255),
  `designation` varchar(255),
  `division` varchar(255),
  `contact_person` varchar(255),
  `contact_no` varchar(255),
  `employee_code` varchar(255),
  `sex` varchar(255),
  `id_number` varchar(255),
  `e_mail` varchar(255),
  `web_login` varchar(255),
  `account_status` varchar(255),
  `creation_date` TIMESTAMP ,
  `created_by` varchar(255),
  `created_by_msisdn` varchar(255),
  `nomade_created_by` varchar(255),
  `level1_app_date` string,
  `level1_app_by` varchar(255),
  `level2_app_date` string,
  `level2_app_by` varchar(255),
  `owner_id` varchar(255),
  `owner_msisdn` varchar(255),
  `user_domain_code` varchar(255),
  `user_category_code` varchar(255),
  `user_grade_name` varchar(255),
  `modified_by` varchar(255),
  `modified_on` TIMESTAMP,
  `modified_approved_by` varchar(255),
  `modified_approved_on` TIMESTAMP,
  `deleted_on` TIMESTAMP,
  `deactivation_by` varchar(255),
  `department` varchar(255),
  `registration_form_number` varchar(255),
  `remarks` varchar(255),
  `geographical_domain` varchar(255),
  `group_role` varchar(255),
  `first_transaction_on` string,
  `company_code` varchar(255),
  `user_type` varchar(255),
  `action_type` varchar(255),
  `agent_code` varchar(255),
  `creation_type` varchar(255),
  `bulk_id` varchar(255),
  `identity_proof_type` varchar(255),
  `address_proof_type` varchar(255),
  `photo_proof_type` varchar(255),
  `id_type` varchar(255),
  `id_no` varchar(255),
  `id_issue_place` varchar(255),
  `id_issue_date` TIMESTAMP,
  `id_issue_country` varchar(255),
  `id_expiry_date` TIMESTAMP,
  `residence_country` varchar(255),
  `nationality` varchar(255),
  `employer_name` varchar(255),
  `postal_code` varchar(255),
  `souscription_type` varchar(255),
  `mobile_group_role` varchar(255),
  `last_login_on` varchar(255),
  `user_grade_code` varchar(255),
  `parent_first_name` varchar(255),
  `parent_last_name` varchar(255),
  `owner_first_name` varchar(255),
  `owner_last_name` varchar(255),
  `product_line` varchar(255),
  `product` varchar(255),
  `styles` varchar(255),
  `details_marketing` varchar(255),
  `details_confomity` varchar(255),
  `commercial_name` varchar(255),
  `technology` varchar(255),
  `beac` varchar(255),
  `appro` varchar(10)

  )
  PARTITIONED BY (ref_date  DATE)
STORED AS PARQUET TBLPROPERTIES ('PARQUET.COMPRESS'='SNAPPY')

insert into  MON.SPARK_REF_OM_PRODUCTS2 partition(REF_DATE)
select
 user_id,
  profile_id,
  parent_user_id,
  parent_user_msisdn,
  msisdn,
  user_name_prefix,
  user_first_name,
  user_last_name,
  user_short_name,
  dob,
  registered_on,
  address1,
  address2,
  state,
  city,
  country,
  ssn,
  designation,
  division,
  contact_person,
  contact_no,
  employee_code,
  sex,
  id_number,
  e_mail,
  web_login,
  account_status,
  creation_date ,
  created_by,
  created_by_msisdn,
  nomade_created_by,
  level1_app_date,
  level1_app_by,
  level2_app_date,
  level2_app_by,
  owner_id,
  owner_msisdn,
  user_domain_code,
  user_category_code,
  user_grade_name,
  modified_by,
  modified_on,
  modified_approved_by,
  modified_approved_on,
  deleted_on,
  deactivation_by,
  department,
  registration_form_number,
  remarks,
  geographical_domain,
  group_role,
  first_transaction_on,
  company_code,
  user_type,
  action_type,
  agent_code,
  creation_type,
  bulk_id,
  identity_proof_type,
  address_proof_type,
  photo_proof_type,
  id_type,
  id_no,
  id_issue_place,
  id_issue_date,
  id_issue_country,
  id_expiry_date,
  residence_country,
  nationality,
  employer_name,
  postal_code,
  souscription_type,
  mobile_group_role,
  last_login_on,
  user_grade_code,
  parent_first_name,
  parent_last_name,
  owner_first_name,
  owner_last_name,
  product_line,
  product,
  styles,
  details_marketing,
  details_confomity,
  commercial_name,
  technology,
  beac,
  appro,
    to_date(ref_date) ref_date
from backup_dwh.REF_OM_PRODUCTS2
