SELECT IF( T_1.MSC_EXIST > 0 AND T_2.NB_EXPORT < 1 ,"OK","NOK")
FROM
(SELECT COUNT(*) MSC_EXIST FROM CDR.SPARK_IT_OMNY_ACCOUNT_SNAPSHOT_NEW WHERE original_file_date ='###SLICE_VALUE###') T_1,
(SELECT COUNT(*) NB_EXPORT FROM (SELECT * FROM (SELECT * FROM MON.EXPORT_HISTORY WHERE EVENT_DATE='###SLICE_VALUE###' AND JOB_INSTANCEID='${hivevar:job_instanceid}' ORDER BY INSERT_DATE DESC LIMIT 1)  T WHERE T.STATUS = 'OK') M) T_2