SELECT
SRC_TABLE,
SRC_NUM,
DEST_NUM,
date_format(STATE_DATE,'dd/MM/yyyy') STATE_DATE,
date_format(ENTRY_DATE,'dd/MM/yyyy') ENTRY_DATE,
SM_STATE,
DEST_OPERATOR,
SRC_OPERATOR,
SRC_MSC_OPERATOR,
DEST_MSC_OPERATOR,
SRC_EI_TYPE,
DEST_EI_TYPE,
NOTIF_IND,
DELIVERY_SLICEID,
CRA_COUNT,
date_format(INSERT_DATE,'dd/MM/yyyy HH:mm:ss') INSERT_DATE,
BILLS_PLATFORM,
SRC_EI,
DEST_EI,
date_format(BILL_DATE,'dd/MM/yyyy') BILL_DATE
FROM AGG.SPARK_FT_QOS_SMSC_SPECIAL_NUMBER 
WHERE STATE_DATE ='###SLICE_VALUE###'