SELECT
STATE_DATE,
SRC_TABLE,
SRC_NUM,
DEST_NUM,
TRANSACTION_DATE,
ENTRY_DATE,
SM_STATE,
DEST_OPERATOR,
SRC_OPERATOR,
SRC_MSC_OPERATOR,
DEST_MSC_OPERATOR,
SRC_EI_TYPE,
DEST_EI_TYPE,
NOTIF_IND,
DELIVERY_SLICEID,
CRA_COUNT,
INSERT_DATE,
BILLS_PLATFORM,
SRC_EI,
DEST_EI,
BILL_DATE
FROM AGG.SPARK_FT_QOS_SMSC_SPECIAL_NUMBER 
WHERE STATE_DATE ='###SLICE_VALUE###'